suricata: /Users/jlu/suricata/src/alert-fastlog.h File Reference
alert-fastlog.h File Reference
Functions
void AlertFastLogRegister (void)
void TmModuleAlertFastLogIPv4Register (void)
void TmModuleAlertFastLogIPv6Register (void)
OutputInitResult AlertFastLogInitCtx (ConfNode *)
Create a new LogFileCtx for "fast" output style.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file alert-fastlog.h.
Function Documentation
AlertFastLogInitCtx()
OutputInitResult AlertFastLogInitCtx (ConfNode * conf)
Create a new LogFileCtx for "fast" output style.
Parameters
conf The configuration node for this output.
Returns
A LogFileCtx pointer on success, NULL on failure.
Definition at line 225 of file alert-fastlog.c.
References OutputCtx_::data, DEFAULT_LOG_FILENAME, OutputCtx_::DeInit, LogFileFreeCtx(), LogFileNewCtx(), SCCalloc, SCConfLogOpenGeneric(), SCLogDebug, and unlikely.
Referenced by AlertFastLogRegister().
AlertFastLogRegister()
void AlertFastLogRegister (void)
Definition at line 75 of file alert-fastlog.c.
References AlertFastLogCondition(), AlertFastLogger(), AlertFastLogInitCtx(), AlertFastLogRegisterTests(), AlertFastLogThreadDeinit(), AlertFastLogThreadInit(), LOGGER_ALERT_FAST, MODULE_NAME, and OutputRegisterPacketModule().
Referenced by OutputRegisterLoggers().
TmModuleAlertFastLogIPv4Register()
void TmModuleAlertFastLogIPv4Register (void)
TmModuleAlertFastLogIPv6Register()
void TmModuleAlertFastLogIPv6Register (void)