suricata: /Users/jlu/suricata/src/app-layer-htp-range.h File Reference
app-layer-htp-range.h File Reference
#include "suricata-common.h"
#include "util-thash.h"
#include "rust.h"
Data Structures
struct HttpRangeContainerBuffer
struct HttpRangeContainerFile
struct HttpRangeContainerBlock
Typedefs
typedef struct HttpRangeContainerBuffer HttpRangeContainerBuffer
typedef struct HttpRangeContainerFile HttpRangeContainerFile
typedef struct HttpRangeContainerBlock HttpRangeContainerBlock
Functions
void HttpRangeContainersInit (void)
void HttpRangeContainersDestroy (void)
uint32_t HttpRangeContainersTimeoutHash (struct timeval *ts)
int HttpRangeContainerBufferCompare (HttpRangeContainerBuffer *a, HttpRangeContainerBuffer *b)
RB_HEAD (HTTP_RANGES, HttpRangeContainerBuffer)
RB_PROTOTYPE (HTTP_RANGES, HttpRangeContainerBuffer, rb, HttpRangeContainerBufferCompare)
int HttpRangeAppendData (HttpRangeContainerBlock *c, const uint8_t *data, uint32_t len)
File * HttpRangeClose (HttpRangeContainerBlock *c, uint16_t flags)
HttpRangeContainerBlock * HttpRangeContainerOpenFile (const unsigned char *key, uint32_t keylen, const Flow *f, const HTTPContentRange *cr, const StreamingBufferConfig *sbcfg, const unsigned char *name, uint16_t name_len, uint16_t flags, const unsigned char *data, uint32_t data_len)
void HttpRangeFreeBlock (HttpRangeContainerBlock *b)
Typedef Documentation
HttpRangeContainerBlock
typedef struct HttpRangeContainerBlock HttpRangeContainerBlock
A structure representing a single range request : either skipping, buffering, or appending As this belongs to a flow, appending data to it is ensured to be thread-safe Only one block per file has the pointer to the container
HttpRangeContainerBuffer
typedef struct HttpRangeContainerBuffer HttpRangeContainerBuffer
HttpRangeContainerFile
typedef struct HttpRangeContainerFile HttpRangeContainerFile
Item in hash table for a file in multiple ranges Thread-safety is ensured with the thread-safe hash table cf THashData The number of use is increased for each flow opening a new HttpRangeContainerBlock until it closes this HttpRangeContainerBlock The design goal is to have concurrency only on opening and closing a range request and have a lock-free data structure belonging to one Flow (see HttpRangeContainerBlock below) for every append in between (we suppose we have many appends per range request)
Function Documentation
HttpRangeAppendData()
int HttpRangeAppendData (HttpRangeContainerBlock * c, const uint8_t * data, uint32_t len)
Definition at line 396 of file app-layer-htp-range.c.
References HttpRangeContainerBuffer::buffer, HttpRangeContainerBuffer::buflen, HttpRangeContainerBlock::current, THashDataGetResult::data, FileAppendData(), HttpRangeContainerBlock::files, HttpRangeContainerBuffer::gap, len, HttpRangeContainerBuffer::offset, SCLogDebug, and HttpRangeContainerBlock::toskip.
Referenced by HTPFileCloseHandleRange(), and HTPFileStoreChunk().
HttpRangeClose()
File * HttpRangeClose (HttpRangeContainerBlock * c, uint16_t flags)
Note
if f is non-NULL, the ownership of the file is transfered to the caller.
Definition at line 467 of file app-layer-htp-range.c.
References HttpRangeContainerBuffer::buffer, HttpRangeContainerBuffer::buflen, HttpRangeContainerBlock::container, ContainerUrlRangeList, HttpRangeContainerBlock::current, DEBUG_VALIDATE_BUG_ON, FileAppendData(), HttpRangeContainerFile::files, HttpRangeContainerBlock::files, HttpRangeContainerFile::fragment_tree, HttpRangeContainerBuffer::gap, ContainerTHashTable::ht, HttpRangeContainerFile::lastsize, HttpRangeContainerBuffer::offset, RB_FOREACH_SAFE, res, SC_ATOMIC_SUB, SCFree, SCLogDebug, File_::size, HttpRangeContainerBuffer::start, FileContainer_::tail, and HttpRangeContainerBlock::toskip.
HttpRangeContainerBufferCompare()
int HttpRangeContainerBufferCompare (HttpRangeContainerBuffer * a, HttpRangeContainerBuffer * b)
Definition at line 45 of file app-layer-htp-range.c.
References HttpRangeContainerBuffer::buflen, HttpRangeContainerBuffer::offset, and HttpRangeContainerBuffer::start.
HttpRangeContainerOpenFile()
HttpRangeContainerBlock * HttpRangeContainerOpenFile (const unsigned char * key, uint32_t keylen, const Flow * f, const HTTPContentRange * cr, const StreamingBufferConfig * sbcfg, const unsigned char * name, uint16_t name_len, uint16_t flags, const unsigned char * data, uint32_t data_len)
HttpRangeContainersDestroy()
void HttpRangeContainersDestroy (void)
Definition at line 185 of file app-layer-htp-range.c.
References ContainerUrlRangeList, ContainerTHashTable::ht, and THashShutdown().
HttpRangeContainersInit()
void HttpRangeContainersInit (void)
Definition at line 150 of file app-layer-htp-range.c.
References ConfGet(), ContainerUrlRangeList, ContainerTHashTable::ht, HTTP_RANGE_DEFAULT_MEMCAP, HTTP_RANGE_DEFAULT_TIMEOUT, ParseSizeStringU64(), SC_ERR_INVALID_VALUE, SCLogDebug, SCLogWarning, str, StringParseUint32(), and THashInit().
Referenced by PreRunInit().
HttpRangeContainersTimeoutHash()
uint32_t HttpRangeContainersTimeoutHash (struct timeval * ts)
Definition at line 190 of file app-layer-htp-range.c.
References SCLogDebug.
HttpRangeFreeBlock()
void HttpRangeFreeBlock (HttpRangeContainerBlock * b)
Definition at line 611 of file app-layer-htp-range.c.
Referenced by HTPFileClose().
RB_HEAD()
RB_HEAD (HTTP_RANGES , HttpRangeContainerBuffer)
RB_PROTOTYPE()
RB_PROTOTYPE (HTTP_RANGES , HttpRangeContainerBuffer , rb , HttpRangeContainerBufferCompare)