suricata: /Users/jlu/suricata/src/app-layer-tftp.c File Reference
app-layer-tftp.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "stream.h"
#include "conf.h"
#include "util-unittest.h"
#include "app-layer.h"
#include "app-layer-detect-proto.h"
#include "app-layer-parser.h"
#include "app-layer-tftp.h"
#include "rust.h"
Macros
#define TFTP_DEFAULT_PORT "69"
#define TFTP_MIN_FRAME_LEN 4
Functions
void RegisterTFTPParsers (void)
Detailed Description
Author
Clément Galland cleme.nosp@m.nt.g.nosp@m.allan.nosp@m.d@ep.nosp@m.ita.f.nosp@m.r
Parser for NTP application layer running on UDP port 69.
Definition in file app-layer-tftp.c.
Macro Definition Documentation
TFTP_DEFAULT_PORT
#define TFTP_DEFAULT_PORT "69"
Definition at line 43 of file app-layer-tftp.c.
TFTP_MIN_FRAME_LEN
#define TFTP_MIN_FRAME_LEN 4
Definition at line 47 of file app-layer-tftp.c.
Function Documentation
RegisterTFTPParsers()
void RegisterTFTPParsers (void)
Definition at line 160 of file app-layer-tftp.c.
References ALPROTO_TFTP, AppLayerProtoDetectConfProtoDetectionEnabled(), AppLayerProtoDetectPPRegister(), AppLayerProtoDetectRegisterProtocol(), RunmodeIsUnittests(), SCLogDebug, TFTP_DEFAULT_PORT, and TFTP_MIN_FRAME_LEN.