suricata: /Users/jlu/suricata/src/app-layer-ntp.h File Reference
app-layer-ntp.h File Reference
Typedefs
typedef struct NTPState_ NTPState
typedef struct NTPTransaction_ NTPTransaction
Functions
void RegisterNTPParsers (void)
void NTPParserRegisterTests (void)
Detailed Description
Author
Pierre Chifflier chiff.nosp@m.lier.nosp@m.@wzdf.nosp@m.tpd..nosp@m.net
Definition in file app-layer-ntp.h.
Typedef Documentation
NTPState
typedef struct NTPState_ NTPState
Opaque Rust types.
Definition at line 31 of file app-layer-ntp.h.
NTPTransaction
typedef struct NTPTransaction_ NTPTransaction
Definition at line 32 of file app-layer-ntp.h.
Function Documentation
NTPParserRegisterTests()
void NTPParserRegisterTests (void)
Definition at line 51 of file app-layer-ntp.c.
Referenced by RegisterNTPParsers().
RegisterNTPParsers()
void RegisterNTPParsers (void)
Definition at line 38 of file app-layer-ntp.c.
References ALPROTO_NTP, AppLayerParserRegisterProtocolUnittests(), and NTPParserRegisterTests().