suricata: /Users/jlu/suricata/src/app-layer-frames.h File Reference
app-layer-frames.h File Reference
#include "rust.h"
Data Structures
struct Frame
struct Frames
struct FramesContainer
Macros
#define FRAME_FLAG_TX_ID_SET BIT_U8(FRAME_FLAGE_TX_ID_SET)
#define FRAME_FLAG_ENDS_AT_EOF BIT_U8(FRAME_FLAGE_ENDS_AT_EOF)
#define FRAME_FLAG_LOGGED BIT_U8(FRAME_FLAGE_LOGGED)
#define FRAMES_STATIC_CNT 3
Typedefs
typedef int64_t FrameId
typedef struct Frame Frame
typedef struct Frames Frames
typedef struct FramesContainer FramesContainer
Enumerations
enum { FRAME_FLAGE_TX_ID_SET , FRAME_FLAGE_ENDS_AT_EOF , FRAME_FLAGE_LOGGED }
Functions
void FramesFree (Frames *frames)
void FramesPrune (Flow *f, Packet *p)
Frame * AppLayerFrameNewByPointer (Flow *f, const StreamSlice *stream_slice, const uint8_t *frame_start, const int64_t len, int dir, uint8_t frame_type)
create new frame using a pointer to start of the frame
Frame * AppLayerFrameNewByRelativeOffset (Flow *f, const StreamSlice *stream_slice, const uint32_t frame_start_rel, const int64_t len, int dir, uint8_t frame_type)
create new frame using a relative offset from the start of the stream slice
Frame * AppLayerFrameNewByAbsoluteOffset (Flow *f, const StreamSlice *stream_slice, const uint64_t frame_start, const int64_t len, int dir, uint8_t frame_type)
create new frame using the absolute offset from the start of the stream
void AppLayerFrameDump (Flow *f)
Frame * FrameGetByIndex (Frames *frames, const uint32_t idx)
Frame * FrameGetById (Frames *frames, const int64_t id)
Frame * AppLayerFrameGetById (Flow *f, const int direction, const FrameId frame_id)
FrameId AppLayerFrameGetId (Frame *r)
void AppLayerFrameAddEvent (Frame *frame, uint8_t e)
void AppLayerFrameAddEventById (Flow *f, const int dir, const FrameId id, uint8_t e)
void AppLayerFrameSetLength (Frame *frame, int64_t len)
void AppLayerFrameSetLengthById (Flow *f, const int dir, const FrameId id, int64_t len)
void AppLayerFrameSetTxId (Frame *r, uint64_t tx_id)
void AppLayerFrameSetTxIdById (Flow *f, const int dir, const FrameId id, uint64_t tx_id)
void AppLayerFramesSlide (Flow *f, const uint32_t slide, const uint8_t direction)
FramesContainer * AppLayerFramesGetContainer (Flow *f)
FramesContainer * AppLayerFramesSetupContainer (Flow *f)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file app-layer-frames.h.
Macro Definition Documentation
FRAME_FLAG_ENDS_AT_EOF
#define FRAME_FLAG_ENDS_AT_EOF BIT_U8(FRAME_FLAGE_ENDS_AT_EOF)
Definition at line 35 of file app-layer-frames.h.
FRAME_FLAG_LOGGED
#define FRAME_FLAG_LOGGED BIT_U8(FRAME_FLAGE_LOGGED)
Definition at line 37 of file app-layer-frames.h.
FRAME_FLAG_TX_ID_SET
#define FRAME_FLAG_TX_ID_SET BIT_U8(FRAME_FLAGE_TX_ID_SET)
Definition at line 33 of file app-layer-frames.h.
FRAMES_STATIC_CNT
#define FRAMES_STATIC_CNT 3
Definition at line 54 of file app-layer-frames.h.
Typedef Documentation
Frame
typedef struct Frame Frame
FrameId
typedef int64_t FrameId
Definition at line 29 of file app-layer-frames.h.
Frames
typedef struct Frames Frames
FramesContainer
typedef struct FramesContainer FramesContainer
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FRAME_FLAGE_TX_ID_SET
FRAME_FLAGE_ENDS_AT_EOF
FRAME_FLAGE_LOGGED
Definition at line 31 of file app-layer-frames.h.
Function Documentation
AppLayerFrameAddEvent()
void AppLayerFrameAddEvent (Frame * frame, uint8_t e)
Definition at line 582 of file app-layer-frames.c.
References Frame::event_cnt, and Frame::events.
Referenced by AppLayerFrameAddEventById().
AppLayerFrameAddEventById()
void AppLayerFrameAddEventById (Flow * f, const int dir, const FrameId id, uint8_t e)
Definition at line 592 of file app-layer-frames.c.
References AppLayerFrameAddEvent(), and AppLayerFrameGetById().
AppLayerFrameDump()
void AppLayerFrameDump (Flow * f)
Definition at line 524 of file app-layer-frames.c.
References Flow_::alparser, AppLayerFramesGetContainer(), Flow_::proto, and Flow_::protoctx.
AppLayerFrameGetById()
Frame * AppLayerFrameGetById (Flow * f, const int direction, const FrameId frame_id)
Definition at line 636 of file app-layer-frames.c.
References AppLayerFramesGetContainer(), FrameGetById(), FramesContainer::toclient, and FramesContainer::toserver.
Referenced by AppLayerFrameAddEventById(), AppLayerFrameSetLengthById(), and AppLayerFrameSetTxIdById().
AppLayerFrameGetId()
FrameId AppLayerFrameGetId (Frame * r)
Definition at line 598 of file app-layer-frames.c.
References Frame::id.
AppLayerFrameNewByAbsoluteOffset()
Frame * AppLayerFrameNewByAbsoluteOffset (Flow * f, const StreamSlice * stream_slice, const uint64_t frame_start, const int64_t len, int dir, uint8_t frame_type)
create new frame using the absolute offset from the start of the stream
Definition at line 537 of file app-layer-frames.c.
References Flow_::alparser, AppLayerFramesSetupContainer(), BUG_ON, TcpSession_::client, len, offset, Flow_::proto, Flow_::protoctx, SCLogDebug, TcpSession_::server, STREAM_BASE_OFFSET, FramesContainer::toclient, and FramesContainer::toserver.
AppLayerFrameNewByPointer()
Frame * AppLayerFrameNewByPointer (Flow * f, const StreamSlice * stream_slice, const uint8_t * frame_start, const int64_t len, int dir, uint8_t frame_type)
create new frame using a pointer to start of the frame
Definition at line 383 of file app-layer-frames.c.
References Flow_::alparser, AppLayerFramesSetupContainer(), BUG_ON, TcpSession_::client, len, offset, Flow_::proto, Flow_::protoctx, SCLogDebug, TcpSession_::server, STREAM_BASE_OFFSET, FramesContainer::toclient, and FramesContainer::toserver.
AppLayerFrameNewByRelativeOffset()
Frame * AppLayerFrameNewByRelativeOffset (Flow * f, const StreamSlice * stream_slice, const uint32_t frame_start_rel, const int64_t len, int dir, uint8_t frame_type)
create new frame using a relative offset from the start of the stream slice
Definition at line 460 of file app-layer-frames.c.
References Flow_::alparser, BUG_ON, Flow_::proto, and Flow_::protoctx.
AppLayerFrameSetLength()
void AppLayerFrameSetLength (Frame * frame, int64_t len)
Definition at line 607 of file app-layer-frames.c.
References len, and Frame::len.
Referenced by AppLayerFrameSetLengthById().
AppLayerFrameSetLengthById()
void AppLayerFrameSetLengthById (Flow * f, const int dir, const FrameId id, int64_t len)
Definition at line 615 of file app-layer-frames.c.
References AppLayerFrameGetById(), AppLayerFrameSetLength(), and len.
AppLayerFrameSetTxId()
void AppLayerFrameSetTxId (Frame * r, uint64_t tx_id)
Definition at line 621 of file app-layer-frames.c.
References Frame::flags, FRAME_FLAG_TX_ID_SET, and Frame::tx_id.
Referenced by AppLayerFrameSetTxIdById().
AppLayerFrameSetTxIdById()
void AppLayerFrameSetTxIdById (Flow * f, const int dir, const FrameId id, uint64_t tx_id)
Definition at line 630 of file app-layer-frames.c.
References AppLayerFrameGetById(), and AppLayerFrameSetTxId().
AppLayerFramesGetContainer()
FramesContainer * AppLayerFramesGetContainer (Flow * f)
Definition at line 199 of file app-layer-parser.c.
References Flow_::alparser, and AppLayerParserState_::frames.
Referenced by AppLayerFrameDump(), AppLayerFrameGetById(), AppLayerFramesSlide(), and FramesPrune().
AppLayerFramesSetupContainer()
FramesContainer * AppLayerFramesSetupContainer (Flow * f)
Definition at line 206 of file app-layer-parser.c.
References Flow_::alparser, Flow_::alproto, DEBUG_VALIDATE_BUG_ON, AppLayerParserState_::frames, Flow_::proto, Flow_::protoctx, SCCalloc, FramesContainer::toclient, and FramesContainer::toserver.
Referenced by AppLayerFrameNewByAbsoluteOffset(), and AppLayerFrameNewByPointer().
AppLayerFramesSlide()
void AppLayerFramesSlide (Flow * f, const uint32_t slide, const uint8_t direction)
Definition at line 328 of file app-layer-frames.c.
References AppLayerFramesGetContainer(), TcpSession_::client, Flow_::protoctx, and FramesContainer::toserver.
FrameGetById()
Frame * FrameGetById (Frames * frames, const int64_t id)
Definition at line 46 of file app-layer-frames.c.
References Frames::cnt, Frames::dframes, FRAMES_STATIC_CNT, Frame::id, and Frames::sframes.
Referenced by AppLayerFrameGetById().
FrameGetByIndex()
Frame * FrameGetByIndex (Frames * frames, const uint32_t idx)
Definition at line 63 of file app-layer-frames.c.
References Frames::cnt, FRAMES_STATIC_CNT, and Frames::sframes.
FramesFree()
void FramesFree (Frames * frames)
Definition at line 373 of file app-layer-frames.c.
References BUG_ON.
FramesPrune()
void FramesPrune (Flow * f, Packet * p)
Definition at line 745 of file app-layer-frames.c.
References AppLayerFramesGetContainer(), PKT_IS_TOSERVER, Packet_::proto, Flow_::proto, Flow_::protoctx, SCLogDebug, FramesContainer::toclient, and FramesContainer::toserver.