suricata: /Users/jlu/suricata/src/app-layer-ftp.c File Reference
app-layer-ftp.c File Reference
#include "suricata-common.h"
#include "decode.h"
#include "threads.h"
#include "util-print.h"
#include "util-pool.h"
#include "flow-util.h"
#include "flow-storage.h"
#include "detect-engine-state.h"
#include "stream-tcp-private.h"
#include "stream-tcp-reassemble.h"
#include "stream-tcp.h"
#include "stream.h"
#include "app-layer.h"
#include "app-layer-protos.h"
#include "app-layer-parser.h"
#include "app-layer-ftp.h"
#include "app-layer-expectation.h"
#include "app-layer-detect-proto.h"
#include "util-spm.h"
#include "util-mpm.h"
#include "util-unittest.h"
#include "util-debug.h"
#include "util-memcmp.h"
#include "util-memrchr.h"
#include "util-mem.h"
#include "util-misc.h"
#include "util-validate.h"
#include "output-json.h"
#include "rust.h"
Data Structures
struct FTPThreadCtx_
struct FtpInput_
struct FtpTransferCmd
Macros
#define FTP_MPM mpm_default_matcher
Typedefs
typedef struct FTPThreadCtx_ FTPThreadCtx
typedef struct FtpInput_ FtpInput
Functions
SC_ATOMIC_DECLARE (uint64_t, ftp_memuse)
SC_ATOMIC_DECLARE (uint64_t, ftp_memcap)
uint64_t FTPMemuseGlobalCounter (void)
uint64_t FTPMemcapGlobalCounter (void)
void RegisterFTPParsers (void)
void FTPAtExitPrintStats (void)
uint16_t JsonGetNextLineFromBuffer (const char *buffer, const uint16_t len)
void EveFTPDataAddMetadata (const Flow *f, JsonBuilder *jb)
void FTPParserCleanup (void)
Free memory allocated for global FTP parser state.
void FTPParserRegisterTests (void)
Variables
const FtpCommand FtpCommands [FTP_COMMAND_MAX+1]
uint64_t ftp_config_memcap = 0
uint32_t ftp_config_maxtx = 1024
uint32_t ftp_max_line_len = 4096
Detailed Description
Author
Pablo Rincon Crespo pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Jeff Lucovsky jeff@.nosp@m.luco.nosp@m.vsky..nosp@m.org
App Layer Parser for FTP
Definition in file app-layer-ftp.c.
Macro Definition Documentation
FTP_MPM
#define FTP_MPM mpm_default_matcher
Definition at line 70 of file app-layer-ftp.c.
Typedef Documentation
FtpInput
typedef struct FtpInput_ FtpInput
FTPThreadCtx
typedef struct FTPThreadCtx_ FTPThreadCtx
Function Documentation
EveFTPDataAddMetadata()
void EveFTPDataAddMetadata (const Flow * f, JsonBuilder * jb)
Definition at line 1486 of file app-layer-ftp.c.
References Flow_::alstate, FtpDataState_::command, FtpDataState_::file_len, FtpDataState_::file_name, FTP_COMMAND_RETR, FTP_COMMAND_STOR, and JB_SET_STRING.
FTPAtExitPrintStats()
void FTPAtExitPrintStats (void)
Definition at line 1448 of file app-layer-ftp.c.
References SCLogDebug, SCMutexLock, and SCMutexUnlock.
FTPMemcapGlobalCounter()
uint64_t FTPMemcapGlobalCounter (void)
Definition at line 196 of file app-layer-ftp.c.
References SC_ATOMIC_GET.
Referenced by AppLayerRegisterGlobalCounters().
FTPMemuseGlobalCounter()
uint64_t FTPMemuseGlobalCounter (void)
Definition at line 190 of file app-layer-ftp.c.
References SC_ATOMIC_GET.
Referenced by AppLayerRegisterGlobalCounters().
FTPParserCleanup()
void FTPParserCleanup (void)
Free memory allocated for global FTP parser state.
Definition at line 1512 of file app-layer-ftp.c.
Referenced by AppLayerParserDeSetup().
FTPParserRegisterTests()
void FTPParserRegisterTests (void)
Definition at line 1806 of file app-layer-ftp.c.
References UtRegisterTest().
JsonGetNextLineFromBuffer()
uint16_t JsonGetNextLineFromBuffer (const char * buffer, const uint16_t len)
Definition at line 1476 of file app-layer-ftp.c.
References len.
RegisterFTPParsers()
void RegisterFTPParsers (void)
FTP
Definition at line 1373 of file app-layer-ftp.c.
References ALPROTO_FTP, AppLayerProtoDetectConfProtoDetectionEnabled(), and AppLayerProtoDetectRegisterProtocol().
SC_ATOMIC_DECLARE() [1/2]
SC_ATOMIC_DECLARE (uint64_t , ftp_memcap)
SC_ATOMIC_DECLARE() [2/2]
SC_ATOMIC_DECLARE (uint64_t , ftp_memuse)
Variable Documentation
ftp_config_maxtx
uint32_t ftp_config_maxtx = 1024
Definition at line 129 of file app-layer-ftp.c.
ftp_config_memcap
uint64_t ftp_config_memcap = 0
Definition at line 128 of file app-layer-ftp.c.
ftp_max_line_len
uint32_t ftp_max_line_len = 4096
Definition at line 130 of file app-layer-ftp.c.
FtpCommands
const FtpCommand FtpCommands[FTP_COMMAND_MAX+1]
Definition at line 74 of file app-layer-ftp.c.