suricata: /Users/jlu/suricata/src/app-layer-htp-body.c File Reference
app-layer-htp-body.c File Reference
#include "suricata.h"
#include "suricata-common.h"
#include "decode.h"
#include "threads.h"
#include "util-print.h"
#include "util-pool.h"
#include "util-radix-tree.h"
#include "stream-tcp-private.h"
#include "stream-tcp-reassemble.h"
#include "stream-tcp.h"
#include "stream.h"
#include "app-layer-protos.h"
#include "app-layer-parser.h"
#include "app-layer-htp.h"
#include "app-layer-htp-body.h"
#include "app-layer-htp-mem.h"
#include "util-spm.h"
#include "util-debug.h"
#include "app-layer-htp-file.h"
#include "util-time.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "flow-util.h"
#include "detect-engine.h"
#include "detect-engine-state.h"
#include "detect-parse.h"
#include "conf.h"
#include "util-memcmp.h"
Functions
int HtpBodyAppendChunk (const HTPCfgDir *hcfg, HtpBody *body, const uint8_t *data, uint32_t len)
Append a chunk of body to the HtpBody struct.
void HtpBodyPrint (HtpBody *body)
Print the information and chunks of a Body.
void HtpBodyFree (HtpBody *body)
Free the information held in the request body.
void HtpBodyPrune (HtpState *state, HtpBody *body, int direction)
Free request body chunks that are already fully parsed.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Gurvinder Singh gurvi.nosp@m.nder.nosp@m.singh.nosp@m.dahi.nosp@m.ya@gm.nosp@m.ail..nosp@m.com
Pablo Rincon pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Brian Rectanus brect.nosp@m.anu@.nosp@m.gmail.nosp@m..com
This file provides a HTTP protocol support for the engine using HTP library.
Definition in file app-layer-htp-body.c.
Function Documentation
HtpBodyAppendChunk()
int HtpBodyAppendChunk (const HTPCfgDir * hcfg, HtpBody * body, const uint8_t * data, uint32_t len)
Append a chunk of body to the HtpBody struct.
Parameters
body pointer to the HtpBody holding the list
data pointer to the data of the chunk
len length of the chunk pointed by data
Return values
0 ok
-1 error
Definition at line 78 of file app-layer-htp-body.c.
References len, HtpBody_::sb, HTPCfgDir_::sbcfg, SCEnter, and SCReturnInt.
HtpBodyPrune()
void HtpBodyPrune (HtpState * state, HtpBody * body, int direction)
Free request body chunks that are already fully parsed.
Parameters
state htp_state, with reference to our config
body the body to prune
direction STREAM_TOSERVER (request), STREAM_TOCLIENT (response)
Return values
none
Definition at line 182 of file app-layer-htp-body.c.
References HtpBody_::body_inspected, HtpBody_::body_parsed, HtpState_::cfg, HtpBody_::content_len_so_far, HtpBody_::first, HTPFree(), HTPCfgDir_::inspect_min_size, HTPCfgDir_::inspect_window, HtpBody_::last, next, HtpBodyChunk_::next, HTPCfgRec_::request, HTPCfgRec_::response, HtpBody_::sb, HtpBodyChunk_::sbseg, SCEnter, SCLogDebug, SCReturn, StreamingBufferSegmentIsBeforeWindow(), and StreamingBufferSlideToOffset().