suricata: /Users/jlu/suricata/src/app-layer-htp-range.c File Reference
app-layer-htp-range.c File Reference
#include "suricata-common.h"
#include "app-layer-htp-range.h"
#include "util-misc.h"
#include "util-thash.h"
#include "util-memcmp.h"
#include "util-hash-string.h"
#include "util-validate.h"
#include "util-byte.h"
Data Structures
struct ContainerTHashTable
Macros
#define CONTAINER_URLRANGE_HASH_SIZE 256
#define HTTP_RANGE_DEFAULT_TIMEOUT 60
#define HTTP_RANGE_DEFAULT_MEMCAP 100 * 1024 * 1024
Typedefs
typedef struct ContainerTHashTable ContainerTHashTable
Functions
int HttpRangeContainerBufferCompare (HttpRangeContainerBuffer *a, HttpRangeContainerBuffer *b)
RB_GENERATE (HTTP_RANGES, HttpRangeContainerBuffer, rb, HttpRangeContainerBufferCompare)
void HttpRangeContainersInit (void)
void HttpRangeContainersDestroy (void)
uint32_t HttpRangeContainersTimeoutHash (struct timeval *ts)
HttpRangeContainerBlock * HttpRangeContainerOpenFile (const uint8_t *key, uint32_t keylen, const Flow *f, const HTTPContentRange *crparsed, const StreamingBufferConfig *sbcfg, const uint8_t *name, uint16_t name_len, uint16_t flags, const uint8_t *data, uint32_t data_len)
int HttpRangeAppendData (HttpRangeContainerBlock *c, const uint8_t *data, uint32_t len)
File * HttpRangeClose (HttpRangeContainerBlock *c, uint16_t flags)
void HttpRangeFreeBlock (HttpRangeContainerBlock *b)
Variables
ContainerTHashTable ContainerUrlRangeList
Detailed Description
Author
Philippe Antoine p.ant.nosp@m.oine.nosp@m.@cate.nosp@m.nacy.nosp@m.ber.f.nosp@m.r
Definition in file app-layer-htp-range.c.
Macro Definition Documentation
CONTAINER_URLRANGE_HASH_SIZE
#define CONTAINER_URLRANGE_HASH_SIZE 256
Definition at line 43 of file app-layer-htp-range.c.
HTTP_RANGE_DEFAULT_MEMCAP
#define HTTP_RANGE_DEFAULT_MEMCAP 100 * 1024 * 1024
Definition at line 148 of file app-layer-htp-range.c.
HTTP_RANGE_DEFAULT_TIMEOUT
#define HTTP_RANGE_DEFAULT_TIMEOUT 60
Definition at line 147 of file app-layer-htp-range.c.
Typedef Documentation
ContainerTHashTable
typedef struct ContainerTHashTable ContainerTHashTable
Function Documentation
HttpRangeAppendData()
int HttpRangeAppendData (HttpRangeContainerBlock * c, const uint8_t * data, uint32_t len)
Definition at line 396 of file app-layer-htp-range.c.
References HttpRangeContainerBuffer::buffer, HttpRangeContainerBuffer::buflen, HttpRangeContainerBlock::current, THashDataGetResult::data, FileAppendData(), HttpRangeContainerBlock::files, HttpRangeContainerBuffer::gap, len, HttpRangeContainerBuffer::offset, SCLogDebug, and HttpRangeContainerBlock::toskip.
Referenced by HTPFileCloseHandleRange(), and HTPFileStoreChunk().
HttpRangeClose()
File * HttpRangeClose (HttpRangeContainerBlock * c, uint16_t flags)
Note
if f is non-NULL, the ownership of the file is transfered to the caller.
Definition at line 467 of file app-layer-htp-range.c.
References HttpRangeContainerBuffer::buffer, HttpRangeContainerBuffer::buflen, HttpRangeContainerBlock::container, ContainerUrlRangeList, HttpRangeContainerBlock::current, DEBUG_VALIDATE_BUG_ON, FileAppendData(), HttpRangeContainerFile::files, HttpRangeContainerBlock::files, HttpRangeContainerFile::fragment_tree, HttpRangeContainerBuffer::gap, ContainerTHashTable::ht, HttpRangeContainerFile::lastsize, HttpRangeContainerBuffer::offset, RB_FOREACH_SAFE, res, SC_ATOMIC_SUB, SCFree, SCLogDebug, File_::size, HttpRangeContainerBuffer::start, FileContainer_::tail, and HttpRangeContainerBlock::toskip.
HttpRangeContainerBufferCompare()
int HttpRangeContainerBufferCompare (HttpRangeContainerBuffer * a, HttpRangeContainerBuffer * b)
Definition at line 45 of file app-layer-htp-range.c.
References HttpRangeContainerBuffer::buflen, HttpRangeContainerBuffer::offset, and HttpRangeContainerBuffer::start.
HttpRangeContainerOpenFile()
HttpRangeContainerBlock * HttpRangeContainerOpenFile (const uint8_t * key, uint32_t keylen, const Flow * f, const HTTPContentRange * crparsed, const StreamingBufferConfig * sbcfg, const uint8_t * name, uint16_t name_len, uint16_t flags, const uint8_t * data, uint32_t data_len)
Definition at line 362 of file app-layer-htp-range.c.
HttpRangeContainersDestroy()
void HttpRangeContainersDestroy (void)
Definition at line 185 of file app-layer-htp-range.c.
References ContainerUrlRangeList, ContainerTHashTable::ht, and THashShutdown().
HttpRangeContainersInit()
void HttpRangeContainersInit (void)
Definition at line 150 of file app-layer-htp-range.c.
References ConfGet(), ContainerUrlRangeList, ContainerTHashTable::ht, HTTP_RANGE_DEFAULT_MEMCAP, HTTP_RANGE_DEFAULT_TIMEOUT, ParseSizeStringU64(), SC_ERR_INVALID_VALUE, SCLogDebug, SCLogWarning, str, StringParseUint32(), and THashInit().
Referenced by PreRunInit().
HttpRangeContainersTimeoutHash()
uint32_t HttpRangeContainersTimeoutHash (struct timeval * ts)
Definition at line 190 of file app-layer-htp-range.c.
References SCLogDebug.
HttpRangeFreeBlock()
void HttpRangeFreeBlock (HttpRangeContainerBlock * b)
Definition at line 611 of file app-layer-htp-range.c.
Referenced by HTPFileClose().
RB_GENERATE()
RB_GENERATE (HTTP_RANGES , HttpRangeContainerBuffer , rb , HttpRangeContainerBufferCompare)
Variable Documentation
ContainerUrlRangeList
ContainerTHashTable ContainerUrlRangeList
Definition at line 39 of file app-layer-htp-range.c.
Referenced by HttpRangeClose(), HttpRangeContainersDestroy(), and HttpRangeContainersInit().