suricata: /Users/jlu/suricata/src/app-layer.c File Reference
app-layer.c File Reference
#include "suricata-common.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "app-layer-protos.h"
#include "app-layer-expectation.h"
#include "app-layer-ftp.h"
#include "app-layer-detect-proto.h"
#include "app-layer-frames.h"
#include "stream-tcp-reassemble.h"
#include "stream-tcp-private.h"
#include "stream-tcp-inline.h"
#include "stream-tcp.h"
#include "flow.h"
#include "flow-util.h"
#include "flow-private.h"
#include "ippair.h"
#include "util-debug.h"
#include "util-print.h"
#include "util-profiling.h"
#include "util-validate.h"
#include "decode-events.h"
#include "app-layer-htp-mem.h"
#include "util-exception-policy.h"
#include "pkt-var.h"
#include "stream-tcp-util.h"
#include "stream.h"
#include "util-unittest.h"
Data Structures
struct AppLayerThreadCtx_
This is for the app layer in general and it contains per thread context relevant to both the alpd and alp.
struct AppLayerCounterNames_
struct AppLayerCounters_
Macros
#define FLOW_PROTO_CHANGE_MAX_DEPTH 4096
#define MAX_COUNTER_SIZE 64
#define IPPROTOS_MAX 2
#define TEST_START
#define TEST_END
Typedefs
typedef struct AppLayerCounterNames_ AppLayerCounterNames
typedef struct AppLayerCounters_ AppLayerCounters
Functions
void AppLayerSetupCounters (void)
void AppLayerDeSetupCounters (void)
void AppLayerIncTxCounter (ThreadVars *tv, Flow *f, uint64_t step)
void AppLayerIncGapErrorCounter (ThreadVars *tv, Flow *f)
void AppLayerIncAllocErrorCounter (ThreadVars *tv, Flow *f)
void AppLayerIncParserErrorCounter (ThreadVars *tv, Flow *f)
void AppLayerIncInternalErrorCounter (ThreadVars *tv, Flow *f)
int AppLayerHandleTCPData (ThreadVars *tv, TcpReassemblyThreadCtx *ra_ctx, Packet *p, Flow *f, TcpSession *ssn, TcpStream **stream, uint8_t *data, uint32_t data_len, uint8_t flags)
handle TCP data for the app-layer.
int AppLayerHandleUdp (ThreadVars *tv, AppLayerThreadCtx *tctx, Packet *p, Flow *f)
Handle a app layer UDP message.
AppProto AppLayerGetProtoByName (char *alproto_name)
Given a protocol string, returns the corresponding internal protocol id.
const char * AppLayerGetProtoName (AppProto alproto)
Given the internal protocol id, returns a string representation of the protocol.
void AppLayerListSupportedProtocols (void)
int AppLayerSetup (void)
Setup the app layer.
int AppLayerDeSetup (void)
De initializes the app layer.
AppLayerThreadCtx * AppLayerGetCtxThread (ThreadVars *tv)
Creates a new app layer thread context.
void AppLayerDestroyCtxThread (AppLayerThreadCtx *app_tctx)
Destroys the context created by AppLayeGetCtxThread().
void AppLayerProfilingResetInternal (AppLayerThreadCtx *app_tctx)
void AppLayerProfilingStoreInternal (AppLayerThreadCtx *app_tctx, Packet *p)
void AppLayerRegisterGlobalCounters (void)
HACK to work around our broken unix manager (re)init loop.
void AppLayerRegisterThreadCounters (ThreadVars *tv)
Registers per flow counters for all protocols.
void AppLayerUnittestsRegister (void)
Variables
AppLayerCounterNames applayer_counter_names [FLOW_PROTO_APPLAYER_MAX][ALPROTO_MAX]
AppLayerCounters applayer_counters [FLOW_PROTO_APPLAYER_MAX][ALPROTO_MAX]
enum ExceptionPolicy g_applayerparser_error_policy
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Generic App-layer functions
Definition in file app-layer.c.
Macro Definition Documentation
FLOW_PROTO_CHANGE_MAX_DEPTH
#define FLOW_PROTO_CHANGE_MAX_DEPTH 4096
Definition at line 73 of file app-layer.c.
IPPROTOS_MAX
#define IPPROTOS_MAX 2
Definition at line 1043 of file app-layer.c.
MAX_COUNTER_SIZE
#define MAX_COUNTER_SIZE 64
Definition at line 75 of file app-layer.c.
TEST_END
#define TEST_END
Value:
    StreamTcpSessionClear(p->flow->protoctx);                                                      \
    StreamTcpThreadDeinit(&tv, (void *)stt);                                                       \
    StreamTcpFreeConfig(true);                                                                     \
    PacketFree(p);                                                                                 \
    FLOW_DESTROY(&f);                                                                              \
    StatsThreadCleanup(&tv);
Definition at line 1263 of file app-layer.c.
TEST_START
#define TEST_START
Definition at line 1180 of file app-layer.c.
Typedef Documentation
AppLayerCounterNames
typedef struct AppLayerCounterNames_ AppLayerCounterNames
AppLayerCounters
typedef struct AppLayerCounters_ AppLayerCounters
Function Documentation
AppLayerDeSetup()
int AppLayerDeSetup (void)
De initializes the app layer.
   Includes de initializing protocol detection and the protocol parser.
Definition at line 970 of file app-layer.c.
References AppLayerDeSetupCounters(), AppLayerParserDeSetup(), AppLayerProtoDetectDeSetup(), SCEnter, and SCReturnInt.
AppLayerDeSetupCounters()
void AppLayerDeSetupCounters (void)
Definition at line 1165 of file app-layer.c.
References applayer_counter_names, and applayer_counters.
Referenced by AppLayerDeSetup().
AppLayerDestroyCtxThread()
void AppLayerDestroyCtxThread (AppLayerThreadCtx * tctx)
Destroys the context created by AppLayeGetCtxThread().
Parameters
tctx Pointer to the thread context to destroy.
Definition at line 1004 of file app-layer.c.
References AppLayerThreadCtx_::alp_tctx, AppLayerThreadCtx_::alpd_tctx, AppLayerParserThreadCtxFree(), AppLayerProtoDetectDestroyCtxThread(), SCEnter, SCFree, and SCReturn.
Referenced by AppLayerGetCtxThread(), DecodeThreadVarsFree(), and StreamTcpReassembleFreeThreadCtx().
AppLayerGetCtxThread()
AppLayerThreadCtx * AppLayerGetCtxThread (ThreadVars * tv)
Creates a new app layer thread context.
Return values
Pointer to the newly create thread context, on success; NULL, on failure.
Definition at line 982 of file app-layer.c.
References AppLayerThreadCtx_::alp_tctx, AppLayerThreadCtx_::alpd_tctx, AppLayerDestroyCtxThread(), AppLayerParserThreadCtxAlloc(), AppLayerProtoDetectGetCtxThread(), SCEnter, SCMalloc, and SCReturnPtr.
Referenced by DecodeThreadVarsAlloc(), and StreamTcpReassembleInitThreadCtx().
AppLayerGetProtoByName()
AppProto AppLayerGetProtoByName (char * alproto_name)
Given a protocol string, returns the corresponding internal protocol id.
Parameters
The internal protocol id.
Definition at line 921 of file app-layer.c.
References AppLayerProtoDetectGetProtoByName(), SCEnter, and SCReturnCT.
AppLayerGetProtoName()
const char * AppLayerGetProtoName (AppProto alproto)
Given the internal protocol id, returns a string representation of the protocol.
Parameters
alproto The internal protocol id.
Return values
String representation of the protocol.
Definition at line 928 of file app-layer.c.
References AppLayerProtoDetectGetProtoName(), SCEnter, and SCReturnCT.
Referenced by AppLayerListSupportedProtocols(), and AppLayerSetupCounters().
AppLayerHandleTCPData()
int AppLayerHandleTCPData (ThreadVars * tv, TcpReassemblyThreadCtx * ra_ctx, Packet * p, Flow * f, TcpSession * ssn, TcpStream ** stream, uint8_t * data, uint32_t data_len, uint8_t flags)
handle TCP data for the app-layer.
Handles reassembled tcp stream.
First run protocol detection and then when the protocol is known invoke the app layer parser.
Parameters
stream ptr-to-ptr to stream object. Might change if flow dir is reversed.
Definition at line 638 of file app-layer.c.
References AppLayerThreadCtx_::alp_tctx, Flow_::alproto, Flow_::alproto_tc, Flow_::alproto_ts, ALPROTO_UNKNOWN, TcpReassemblyThreadCtx_::app_tctx, AppLayerParserParse(), DEBUG_ASSERT_FLOW_LOCKED, DEBUG_VALIDATE_BUG_ON, ExceptionPolicyApply(), flags, TcpSession_::flags, FlowChangeProto(), FlowUnsetChangeProtoFlag(), g_applayerparser_error_policy, PACKET_PROFILING_APP_END, PACKET_PROFILING_APP_START, PKT_DROP_REASON_APPLAYER_ERROR, SCEnter, SCLogDebug, SCReturnInt, STREAMTCP_FLAG_APP_LAYER_DISABLED, StreamTcpSetStreamFlagAppProtoDetectionCompleted, StreamTcpUpdateAppLayerProgress(), and tv.
Referenced by StreamTcpReassembleAppLayer().
AppLayerHandleUdp()
int AppLayerHandleUdp (ThreadVars * tv, AppLayerThreadCtx * tctx, Packet * p, Flow * f)
Handle a app layer UDP message.
Handles an udp chunk.
If the protocol is yet unknown, the proto detection code is run first.
Parameters
dp_ctx Thread app layer detect context
f locked flow
p UDP packet
Return values
0 ok
-1 error
Definition at line 800 of file app-layer.c.
References ALPROTO_FAILED, Flow_::alproto_tc, Flow_::alproto_ts, flags, FLOW_PKT_TOSERVER, Packet_::flowflags, SCEnter, and SCReturnInt.
AppLayerIncAllocErrorCounter()
void AppLayerIncAllocErrorCounter (ThreadVars * tv, Flow * f)
Definition at line 138 of file app-layer.c.
References AppLayerCounters_::alloc_error_id, Flow_::alproto, applayer_counters, likely, Flow_::protomap, StatsIncr(), and tv.
AppLayerIncGapErrorCounter()
void AppLayerIncGapErrorCounter (ThreadVars * tv, Flow * f)
Definition at line 130 of file app-layer.c.
References Flow_::alproto, applayer_counters, AppLayerCounters_::gap_error_id, likely, Flow_::protomap, StatsIncr(), and tv.
AppLayerIncInternalErrorCounter()
void AppLayerIncInternalErrorCounter (ThreadVars * tv, Flow * f)
Definition at line 154 of file app-layer.c.
References Flow_::alproto, applayer_counters, AppLayerCounters_::internal_error_id, likely, Flow_::protomap, StatsIncr(), and tv.
AppLayerIncParserErrorCounter()
void AppLayerIncParserErrorCounter (ThreadVars * tv, Flow * f)
Definition at line 146 of file app-layer.c.
References Flow_::alproto, applayer_counters, likely, AppLayerCounters_::parser_error_id, Flow_::protomap, StatsIncr(), and tv.
AppLayerIncTxCounter()
void AppLayerIncTxCounter (ThreadVars * tv, Flow * f, uint64_t step)
Definition at line 122 of file app-layer.c.
References Flow_::alproto, applayer_counters, AppLayerCounters_::counter_tx_id, likely, Flow_::protomap, StatsAddUI64(), and tv.
AppLayerListSupportedProtocols()
void AppLayerListSupportedProtocols (void)
Definition at line 935 of file app-layer.c.
References ALPROTO_MAX, AppLayerGetProtoName(), AppLayerProtoDetectSupportedAppProtocols(), SCEnter, and SCReturn.
Referenced by ListAppLayerProtocols().
AppLayerProfilingResetInternal()
void AppLayerProfilingResetInternal (AppLayerThreadCtx * app_tctx)
Definition at line 1021 of file app-layer.c.
References PACKET_PROFILING_APP_RESET.
AppLayerProfilingStoreInternal()
void AppLayerProfilingStoreInternal (AppLayerThreadCtx * app_tctx, Packet * p)
Definition at line 1026 of file app-layer.c.
References PACKET_PROFILING_APP_STORE.
AppLayerRegisterGlobalCounters()
void AppLayerRegisterGlobalCounters (void)
HACK to work around our broken unix manager (re)init loop.
Definition at line 1034 of file app-layer.c.
References ExpectationGetCounter(), FTPMemcapGlobalCounter(), FTPMemuseGlobalCounter(), HTPMemcapGlobalCounter(), HTPMemuseGlobalCounter(), and StatsRegisterGlobalCounter().
Referenced by PreRunInit().
AppLayerRegisterThreadCounters()
void AppLayerRegisterThreadCounters (ThreadVars * tv)
Registers per flow counters for all protocols.
Definition at line 1124 of file app-layer.c.
References AppLayerCounters_::alloc_error_id, ALPROTO_FAILED, ALPROTO_MAX, applayer_counter_names, applayer_counters, AppLayerProtoDetectSupportedAppProtocols(), AppLayerCounters_::counter_id, AppLayerCounters_::counter_tx_id, FlowGetProtoMapping(), AppLayerCounters_::gap_error_id, AppLayerCounters_::internal_error_id, IPPROTOS_MAX, AppLayerCounters_::parser_error_id, StatsRegisterCounter(), and tv.
AppLayerSetup()
int AppLayerSetup (void)
Setup the app layer.
   Includes protocol detection setup and the protocol parser setup.
Return values
0 On success.
-1 On failure.
Definition at line 955 of file app-layer.c.
References AppLayerParserRegisterProtocolParsers(), AppLayerParserSetup(), AppLayerProtoDetectPrepareState(), AppLayerProtoDetectSetup(), AppLayerSetupCounters(), SCEnter, and SCReturnInt.
Referenced by ListAppLayerProtocols(), ListKeywords(), PostConfLoadedSetup(), and RunUnittests().
AppLayerSetupCounters()
void AppLayerSetupCounters (void)
Definition at line 1044 of file app-layer.c.
References ALPROTO_FAILED, ALPROTO_MAX, applayer_counter_names, AppLayerGetProtoName(), AppLayerParserProtoIsRegistered(), AppLayerProtoDetectSupportedAppProtocols(), FlowGetProtoMapping(), IPPROTOS_MAX, and str.
Referenced by AppLayerSetup().
AppLayerUnittestsRegister()
void AppLayerUnittestsRegister (void)
Definition at line 2806 of file app-layer.c.
References SCEnter, and UtRegisterTest().
Variable Documentation
applayer_counter_names
AppLayerCounterNames applayer_counter_names[FLOW_PROTO_APPLAYER_MAX][ALPROTO_MAX]
Definition at line 95 of file app-layer.c.
Referenced by AppLayerDeSetupCounters(), AppLayerRegisterThreadCounters(), and AppLayerSetupCounters().
applayer_counters
AppLayerCounters applayer_counters[FLOW_PROTO_APPLAYER_MAX][ALPROTO_MAX]
Definition at line 97 of file app-layer.c.
Referenced by AppLayerDeSetupCounters(), AppLayerIncAllocErrorCounter(), AppLayerIncGapErrorCounter(), AppLayerIncInternalErrorCounter(), AppLayerIncParserErrorCounter(), AppLayerIncTxCounter(), and AppLayerRegisterThreadCounters().
g_applayerparser_error_policy
enum ExceptionPolicy g_applayerparser_error_policy extern
Definition at line 175 of file app-layer-parser.c.
Referenced by AppLayerHandleTCPData().