suricata: /Users/jlu/suricata/src/app-layer-protos.c File Reference
app-layer-protos.c File Reference
#include "suricata-common.h"
#include "app-layer-protos.h"
Macros
#define CASE_CODE(E) case E: return #E
Functions
const char * AppProtoToString (AppProto alproto)
Maps the ALPROTO_*, to its string equivalent.
AppProto StringToAppProto (const char *proto_name)
Maps a string to its ALPROTO_* equivalent.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file app-layer-protos.c.
Macro Definition Documentation
CASE_CODE
#define CASE_CODE (E) case E: return #E
Definition at line 28 of file app-layer-protos.c.
Function Documentation
AppProtoToString()
const char * AppProtoToString (AppProto alproto)
Maps the ALPROTO_*, to its string equivalent.
Parameters
alproto App layer protocol id.
Return values
String equivalent for the alproto.
Definition at line 30 of file app-layer-protos.c.
References ALPROTO_DCERPC, ALPROTO_DHCP, ALPROTO_DNP3, ALPROTO_DNS, ALPROTO_ENIP, ALPROTO_FAILED, ALPROTO_FTP, ALPROTO_FTPDATA, ALPROTO_HTTP, ALPROTO_HTTP1, ALPROTO_HTTP2, ALPROTO_IKE, ALPROTO_IMAP, ALPROTO_IRC, ALPROTO_JABBER, ALPROTO_KRB5, ALPROTO_MAX, ALPROTO_MODBUS, ALPROTO_MQTT, ALPROTO_NFS, ALPROTO_NTP, ALPROTO_PGSQL, ALPROTO_QUIC, ALPROTO_RDP, ALPROTO_RFB, ALPROTO_SIP, ALPROTO_SMB, ALPROTO_SMTP, ALPROTO_SNMP, ALPROTO_SSH, ALPROTO_TELNET, ALPROTO_TEMPLATE, ALPROTO_TEMPLATE_RUST, ALPROTO_TEST, ALPROTO_TFTP, ALPROTO_TLS, ALPROTO_UNKNOWN, and proto.
Referenced by DetectEngineFrameMpmRegister(), DetectFrameMpmRegister(), DetectSignatureSetAppProto(), EngineAnalysisRules2(), EveAddAppProto(), JsonBuildFileInfoRecord(), LLVMFuzzerInitialize(), LLVMFuzzerTestOneInput(), OutputRegisterTxLogger(), RulesDumpMatchArray(), and RulesDumpTxMatchArray().
StringToAppProto()
AppProto StringToAppProto (const char * proto_name)
Maps a string to its ALPROTO_* equivalent.
Parameters
String equivalent for the alproto.
Return values
alproto App layer protocol id, or ALPROTO_UNKNOWN.
Definition at line 149 of file app-layer-protos.c.
References ALPROTO_DCERPC, ALPROTO_DHCP, ALPROTO_DNP3, ALPROTO_DNS, ALPROTO_ENIP, ALPROTO_FAILED, ALPROTO_FTP, ALPROTO_FTPDATA, ALPROTO_HTTP, ALPROTO_HTTP1, ALPROTO_HTTP2, ALPROTO_IKE, ALPROTO_IMAP, ALPROTO_IRC, ALPROTO_JABBER, ALPROTO_KRB5, ALPROTO_MODBUS, ALPROTO_MQTT, ALPROTO_NFS, ALPROTO_NTP, ALPROTO_PGSQL, ALPROTO_QUIC, ALPROTO_RDP, ALPROTO_RFB, ALPROTO_SIP, ALPROTO_SMB, ALPROTO_SMTP, ALPROTO_SNMP, ALPROTO_SSH, ALPROTO_TELNET, ALPROTO_TEMPLATE, ALPROTO_TEMPLATE_RUST, ALPROTO_TFTP, ALPROTO_TLS, and ALPROTO_UNKNOWN.
Referenced by AppLayerRegisterProtocolDetection(), and LLVMFuzzerInitialize().