suricata: /Users/jlu/suricata/src/app-layer-protos.h File Reference
app-layer-protos.h File Reference
Typedefs
typedef uint16_t AppProto
Enumerations
enum AppProtoEnum {
ALPROTO_UNKNOWN = 0 , ALPROTO_HTTP1 , ALPROTO_FTP , ALPROTO_SMTP ,
ALPROTO_TLS , ALPROTO_SSH , ALPROTO_IMAP , ALPROTO_JABBER ,
ALPROTO_SMB , ALPROTO_DCERPC , ALPROTO_IRC , ALPROTO_DNS ,
ALPROTO_MODBUS , ALPROTO_ENIP , ALPROTO_DNP3 , ALPROTO_NFS ,
ALPROTO_NTP , ALPROTO_FTPDATA , ALPROTO_TFTP , ALPROTO_IKE ,
ALPROTO_KRB5 , ALPROTO_QUIC , ALPROTO_DHCP , ALPROTO_SNMP ,
ALPROTO_SIP , ALPROTO_RFB , ALPROTO_MQTT , ALPROTO_PGSQL ,
ALPROTO_TELNET , ALPROTO_TEMPLATE , ALPROTO_TEMPLATE_RUST , ALPROTO_RDP ,
ALPROTO_HTTP2 , ALPROTO_HTTP , ALPROTO_FAILED , ALPROTO_TEST ,
ALPROTO_MAX
}
Functions
const char * AppProtoToString (AppProto alproto)
Maps the ALPROTO_*, to its string equivalent.
AppProto StringToAppProto (const char *proto_name)
Maps a string to its ALPROTO_* equivalent.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file app-layer-protos.h.
Typedef Documentation
AppProto
typedef uint16_t AppProto
Definition at line 80 of file app-layer-protos.h.
Enumeration Type Documentation
AppProtoEnum
enum AppProtoEnum
Enumerator
ALPROTO_UNKNOWN
ALPROTO_HTTP1
ALPROTO_FTP
ALPROTO_SMTP
ALPROTO_TLS
ALPROTO_SSH
ALPROTO_IMAP
ALPROTO_JABBER
ALPROTO_SMB
ALPROTO_DCERPC
ALPROTO_IRC
ALPROTO_DNS
ALPROTO_MODBUS
ALPROTO_ENIP
ALPROTO_DNP3
ALPROTO_NFS
ALPROTO_NTP
ALPROTO_FTPDATA
ALPROTO_TFTP
ALPROTO_IKE
ALPROTO_KRB5
ALPROTO_QUIC
ALPROTO_DHCP
ALPROTO_SNMP
ALPROTO_SIP
ALPROTO_RFB
ALPROTO_MQTT
ALPROTO_PGSQL
ALPROTO_TELNET
ALPROTO_TEMPLATE
ALPROTO_TEMPLATE_RUST
ALPROTO_RDP
ALPROTO_HTTP2
ALPROTO_HTTP
ALPROTO_FAILED
ALPROTO_TEST
ALPROTO_MAX
Definition at line 28 of file app-layer-protos.h.
Function Documentation
AppProtoToString()
const char * AppProtoToString (AppProto alproto)
Maps the ALPROTO_*, to its string equivalent.
Parameters
alproto App layer protocol id.
Return values
String equivalent for the alproto.
Definition at line 30 of file app-layer-protos.c.
References ALPROTO_DCERPC, ALPROTO_DHCP, ALPROTO_DNP3, ALPROTO_DNS, ALPROTO_ENIP, ALPROTO_FAILED, ALPROTO_FTP, ALPROTO_FTPDATA, ALPROTO_HTTP, ALPROTO_HTTP1, ALPROTO_HTTP2, ALPROTO_IKE, ALPROTO_IMAP, ALPROTO_IRC, ALPROTO_JABBER, ALPROTO_KRB5, ALPROTO_MAX, ALPROTO_MODBUS, ALPROTO_MQTT, ALPROTO_NFS, ALPROTO_NTP, ALPROTO_PGSQL, ALPROTO_QUIC, ALPROTO_RDP, ALPROTO_RFB, ALPROTO_SIP, ALPROTO_SMB, ALPROTO_SMTP, ALPROTO_SNMP, ALPROTO_SSH, ALPROTO_TELNET, ALPROTO_TEMPLATE, ALPROTO_TEMPLATE_RUST, ALPROTO_TEST, ALPROTO_TFTP, ALPROTO_TLS, ALPROTO_UNKNOWN, and proto.
Referenced by DetectEngineFrameMpmRegister(), DetectFrameMpmRegister(), DetectSignatureSetAppProto(), EngineAnalysisRules2(), EveAddAppProto(), JsonBuildFileInfoRecord(), LLVMFuzzerInitialize(), LLVMFuzzerTestOneInput(), OutputRegisterTxLogger(), RulesDumpMatchArray(), and RulesDumpTxMatchArray().
StringToAppProto()
AppProto StringToAppProto (const char * proto_name)
Maps a string to its ALPROTO_* equivalent.
Parameters
String equivalent for the alproto.
Return values
alproto App layer protocol id, or ALPROTO_UNKNOWN.
Definition at line 149 of file app-layer-protos.c.
References ALPROTO_DCERPC, ALPROTO_DHCP, ALPROTO_DNP3, ALPROTO_DNS, ALPROTO_ENIP, ALPROTO_FAILED, ALPROTO_FTP, ALPROTO_FTPDATA, ALPROTO_HTTP, ALPROTO_HTTP1, ALPROTO_HTTP2, ALPROTO_IKE, ALPROTO_IMAP, ALPROTO_IRC, ALPROTO_JABBER, ALPROTO_KRB5, ALPROTO_MODBUS, ALPROTO_MQTT, ALPROTO_NFS, ALPROTO_NTP, ALPROTO_PGSQL, ALPROTO_QUIC, ALPROTO_RDP, ALPROTO_RFB, ALPROTO_SIP, ALPROTO_SMB, ALPROTO_SMTP, ALPROTO_SNMP, ALPROTO_SSH, ALPROTO_TELNET, ALPROTO_TEMPLATE, ALPROTO_TEMPLATE_RUST, ALPROTO_TFTP, ALPROTO_TLS, and ALPROTO_UNKNOWN.
Referenced by AppLayerRegisterProtocolDetection(), and LLVMFuzzerInitialize().