suricata: /Users/jlu/suricata/src/app-layer-http2.h File Reference
app-layer-http2.h File Reference
Functions
void RegisterHTTP2Parsers (void)
void HTTP2MimicHttp1Request (void *, void *)
Detailed Description
Author
Philippe Antoine p.ant.nosp@m.oine.nosp@m.@cate.nosp@m.nacy.nosp@m.ber.f.nosp@m.r
Definition in file app-layer-http2.h.
Function Documentation
HTTP2MimicHttp1Request()
void HTTP2MimicHttp1Request (void * alstate_orig, void * h2s)
Definition at line 74 of file app-layer-http2.c.
References HtpGetTxForH2().
RegisterHTTP2Parsers()
void RegisterHTTP2Parsers (void)
Definition at line 56 of file app-layer-http2.c.
References ALPROTO_HTTP2, AppLayerProtoDetectConfProtoDetectionEnabledDefault(), and AppLayerProtoDetectRegisterProtocol().