suricata: /Users/jlu/suricata/src/app-layer-frames.c File Reference
app-layer-frames.c File Reference
#include "suricata-common.h"
#include "util-print.h"
#include "stream-tcp.h"
#include "app-layer-frames.h"
#include "app-layer-parser.h"
Functions
Frame * FrameGetById (Frames *frames, const int64_t id)
Frame * FrameGetByIndex (Frames *frames, const uint32_t idx)
void AppLayerFramesSlide (Flow *f, const uint32_t slide, const uint8_t direction)
void FramesFree (Frames *frames)
Frame * AppLayerFrameNewByPointer (Flow *f, const StreamSlice *stream_slice, const uint8_t *frame_start, const int64_t len, int dir, uint8_t frame_type)
create new frame using a pointer to start of the frame
Frame * AppLayerFrameNewByRelativeOffset (Flow *f, const StreamSlice *stream_slice, const uint32_t frame_start_rel, const int64_t len, int dir, uint8_t frame_type)
create new frame using a relative offset from the start of the stream slice
void AppLayerFrameDump (Flow *f)
Frame * AppLayerFrameNewByAbsoluteOffset (Flow *f, const StreamSlice *stream_slice, const uint64_t frame_start, const int64_t len, int dir, uint8_t frame_type)
create new frame using the absolute offset from the start of the stream
void AppLayerFrameAddEvent (Frame *r, uint8_t e)
void AppLayerFrameAddEventById (Flow *f, const int dir, const FrameId id, uint8_t e)
FrameId AppLayerFrameGetId (Frame *r)
void AppLayerFrameSetLength (Frame *frame, int64_t len)
void AppLayerFrameSetLengthById (Flow *f, const int dir, const FrameId id, int64_t len)
void AppLayerFrameSetTxId (Frame *r, uint64_t tx_id)
void AppLayerFrameSetTxIdById (Flow *f, const int dir, const FrameId id, uint64_t tx_id)
Frame * AppLayerFrameGetById (Flow *f, const int dir, const FrameId frame_id)
void FramesPrune (Flow *f, Packet *p)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file app-layer-frames.c.
Function Documentation
AppLayerFrameAddEvent()
void AppLayerFrameAddEvent (Frame * r, uint8_t e)
Definition at line 582 of file app-layer-frames.c.
References Frame::event_cnt, and Frame::events.
Referenced by AppLayerFrameAddEventById().
AppLayerFrameAddEventById()
void AppLayerFrameAddEventById (Flow * f, const int dir, const FrameId id, uint8_t e)
Definition at line 592 of file app-layer-frames.c.
References AppLayerFrameAddEvent(), and AppLayerFrameGetById().
AppLayerFrameDump()
void AppLayerFrameDump (Flow * f)
Definition at line 524 of file app-layer-frames.c.
References Flow_::alparser, AppLayerFramesGetContainer(), Flow_::proto, and Flow_::protoctx.
AppLayerFrameGetById()
Frame * AppLayerFrameGetById (Flow * f, const int dir, const FrameId frame_id)
Definition at line 636 of file app-layer-frames.c.
References AppLayerFramesGetContainer(), FrameGetById(), FramesContainer::toclient, and FramesContainer::toserver.
Referenced by AppLayerFrameAddEventById(), AppLayerFrameSetLengthById(), and AppLayerFrameSetTxIdById().
AppLayerFrameGetId()
FrameId AppLayerFrameGetId (Frame * r)
Definition at line 598 of file app-layer-frames.c.
References Frame::id.
AppLayerFrameNewByAbsoluteOffset()
Frame * AppLayerFrameNewByAbsoluteOffset (Flow * f, const StreamSlice * stream_slice, const uint64_t frame_start, const int64_t len, int dir, uint8_t frame_type)
create new frame using the absolute offset from the start of the stream
Definition at line 537 of file app-layer-frames.c.
References Flow_::alparser, AppLayerFramesSetupContainer(), BUG_ON, TcpSession_::client, len, offset, Flow_::proto, Flow_::protoctx, SCLogDebug, TcpSession_::server, STREAM_BASE_OFFSET, FramesContainer::toclient, and FramesContainer::toserver.
AppLayerFrameNewByPointer()
Frame * AppLayerFrameNewByPointer (Flow * f, const StreamSlice * stream_slice, const uint8_t * frame_start, const int64_t len, int dir, uint8_t frame_type)
create new frame using a pointer to start of the frame
Definition at line 383 of file app-layer-frames.c.
References Flow_::alparser, AppLayerFramesSetupContainer(), BUG_ON, TcpSession_::client, len, offset, Flow_::proto, Flow_::protoctx, SCLogDebug, TcpSession_::server, STREAM_BASE_OFFSET, FramesContainer::toclient, and FramesContainer::toserver.
AppLayerFrameNewByRelativeOffset()
Frame * AppLayerFrameNewByRelativeOffset (Flow * f, const StreamSlice * stream_slice, const uint32_t frame_start_rel, const int64_t len, int dir, uint8_t frame_type)
create new frame using a relative offset from the start of the stream slice
Definition at line 460 of file app-layer-frames.c.
References Flow_::alparser, BUG_ON, Flow_::proto, and Flow_::protoctx.
AppLayerFrameSetLength()
void AppLayerFrameSetLength (Frame * frame, int64_t len)
Definition at line 607 of file app-layer-frames.c.
References len, and Frame::len.
Referenced by AppLayerFrameSetLengthById().
AppLayerFrameSetLengthById()
void AppLayerFrameSetLengthById (Flow * f, const int dir, const FrameId id, int64_t len)
Definition at line 615 of file app-layer-frames.c.
References AppLayerFrameGetById(), AppLayerFrameSetLength(), and len.
AppLayerFrameSetTxId()
void AppLayerFrameSetTxId (Frame * r, uint64_t tx_id)
Definition at line 621 of file app-layer-frames.c.
References Frame::flags, FRAME_FLAG_TX_ID_SET, and Frame::tx_id.
Referenced by AppLayerFrameSetTxIdById().
AppLayerFrameSetTxIdById()
void AppLayerFrameSetTxIdById (Flow * f, const int dir, const FrameId id, uint64_t tx_id)
Definition at line 630 of file app-layer-frames.c.
References AppLayerFrameGetById(), and AppLayerFrameSetTxId().
AppLayerFramesSlide()
void AppLayerFramesSlide (Flow * f, const uint32_t slide, const uint8_t direction)
Definition at line 328 of file app-layer-frames.c.
References AppLayerFramesGetContainer(), TcpSession_::client, Flow_::protoctx, and FramesContainer::toserver.
FrameGetById()
Frame * FrameGetById (Frames * frames, const int64_t id)
Definition at line 46 of file app-layer-frames.c.
References Frames::cnt, Frames::dframes, FRAMES_STATIC_CNT, Frame::id, and Frames::sframes.
Referenced by AppLayerFrameGetById().
FrameGetByIndex()
Frame * FrameGetByIndex (Frames * frames, const uint32_t idx)
Definition at line 63 of file app-layer-frames.c.
References Frames::cnt, FRAMES_STATIC_CNT, and Frames::sframes.
FramesFree()
void FramesFree (Frames * frames)
Definition at line 373 of file app-layer-frames.c.
References BUG_ON.
FramesPrune()
void FramesPrune (Flow * f, Packet * p)
Definition at line 745 of file app-layer-frames.c.
References AppLayerFramesGetContainer(), PKT_IS_TOSERVER, Packet_::proto, Flow_::proto, Flow_::protoctx, SCLogDebug, FramesContainer::toclient, and FramesContainer::toserver.