suricata: /Users/jlu/suricata/src/app-layer-ike.h File Reference
app-layer-ike.h File Reference
Typedefs
typedef struct IKEState_ IKEState
typedef struct IKETransaction_ IKETransaction
Functions
void RegisterIKEParsers (void)
void IKEParserRegisterTests (void)
Detailed Description
Author
Pierre Chifflier chiff.nosp@m.lier.nosp@m.@wzdf.nosp@m.tpd..nosp@m.net
Frank Honza frank.nosp@m..hon.nosp@m.za@dc.nosp@m.so.d.nosp@m.e
Definition in file app-layer-ike.h.
Typedef Documentation
IKEState
typedef struct IKEState_ IKEState
Opaque Rust types.
Definition at line 32 of file app-layer-ike.h.
IKETransaction
typedef struct IKETransaction_ IKETransaction
Definition at line 33 of file app-layer-ike.h.
Function Documentation
IKEParserRegisterTests()
void IKEParserRegisterTests (void)
Definition at line 185 of file app-layer-ike.c.
References UtRegisterTest().
Referenced by RegisterIKEParsers().
RegisterIKEParsers()
void RegisterIKEParsers (void)
Definition at line 40 of file app-layer-ike.c.
References ALPROTO_IKE, AppLayerParserRegisterProtocolUnittests(), and IKEParserRegisterTests().