suricata: /Users/jlu/suricata/src/app-layer-htp-mem.c File Reference
app-layer-htp-mem.c File Reference
HTTP layer support
#include "suricata-common.h"
#include "suricata.h"
#include "conf.h"
#include "util-mem.h"
#include "util-misc.h"
#include "app-layer-htp-mem.h"
Functions
SC_ATOMIC_DECLARE (uint64_t, htp_config_memcap)
SC_ATOMIC_DECLARE (uint64_t, htp_memuse)
SC_ATOMIC_DECLARE (uint64_t, htp_memcap)
void HTPParseMemcap ()
uint64_t HTPMemuseGlobalCounter (void)
uint64_t HTPMemcapGlobalCounter (void)
int HTPSetMemcap (uint64_t size)
Update memcap value.
uint64_t HTPGetMemcap (void)
Update memcap value.
void * HTPMalloc (size_t size)
void * HTPCalloc (size_t n, size_t size)
void * HTPRealloc (void *ptr, size_t orig_size, size_t size)
void HTPFree (void *ptr, size_t size)
Detailed Description
Author
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
This file provides a memory handling for the HTTP protocol support.
Definition in file app-layer-htp-mem.c.
Function Documentation
HTPCalloc()
void * HTPCalloc (size_t n, size_t size)
Definition at line 154 of file app-layer-htp-mem.c.
HTPFree()
void HTPFree (void * ptr, size_t size)
Definition at line 191 of file app-layer-htp-mem.c.
References SCFree.
Referenced by HtpBodyFree(), and HtpBodyPrune().
HTPGetMemcap()
uint64_t HTPGetMemcap (void)
Update memcap value.
Return values
memcap value
Definition at line 131 of file app-layer-htp-mem.c.
References SC_ATOMIC_GET.
HTPMalloc()
void * HTPMalloc (size_t size)
Definition at line 137 of file app-layer-htp-mem.c.
HTPMemcapGlobalCounter()
uint64_t HTPMemcapGlobalCounter (void)
Definition at line 91 of file app-layer-htp-mem.c.
References SC_ATOMIC_GET.
Referenced by AppLayerRegisterGlobalCounters().
HTPMemuseGlobalCounter()
uint64_t HTPMemuseGlobalCounter (void)
Definition at line 85 of file app-layer-htp-mem.c.
References SC_ATOMIC_GET.
Referenced by AppLayerRegisterGlobalCounters().
HTPParseMemcap()
void HTPParseMemcap (void)
set config values for memcap, prealloc and hash_size
Definition at line 45 of file app-layer-htp-mem.c.
References ConfGet(), ParseSizeStringU64(), SC_ATOMIC_GET, SC_ATOMIC_INIT, SC_ATOMIC_SET, SC_ERR_SIZE_PARSE, SCLogError, and SCLogInfo.
HTPRealloc()
void * HTPRealloc (void * ptr, size_t orig_size, size_t size)
Definition at line 171 of file app-layer-htp-mem.c.
HTPSetMemcap()
int HTPSetMemcap (uint64_t size)
Update memcap value.
Parameters
size new memcap value
Definition at line 117 of file app-layer-htp-mem.c.
References SC_ATOMIC_GET, and SC_ATOMIC_SET.
SC_ATOMIC_DECLARE() [1/3]
SC_ATOMIC_DECLARE (uint64_t , htp_config_memcap)
SC_ATOMIC_DECLARE() [2/3]
SC_ATOMIC_DECLARE (uint64_t , htp_memcap)
SC_ATOMIC_DECLARE() [3/3]
SC_ATOMIC_DECLARE (uint64_t , htp_memuse)