suricata: /Users/jlu/suricata/src/app-layer-enip.h File Reference
app-layer-enip.h File Reference
Functions
void RegisterENIPUDPParsers (void)
Function to register the ENIP protocol parsers and other functions.
void RegisterENIPTCPParsers (void)
Function to register the ENIP protocol parsers and other functions.
void ENIPParserRegisterTests (void)
Detailed Description
Author
Kevin Wong kwong.nosp@m.@sol.nosp@m.anane.nosp@m.twor.nosp@m.ks.co.nosp@m.m
Definition in file app-layer-enip.h.
Function Documentation
ENIPParserRegisterTests()
void ENIPParserRegisterTests (void)
Definition at line 656 of file app-layer-enip.c.
References UtRegisterTest().
RegisterENIPTCPParsers()
void RegisterENIPTCPParsers (void)
Function to register the ENIP protocol parsers and other functions.
Definition at line 526 of file app-layer-enip.c.
References ALPROTO_ENIP, AppLayerProtoDetectConfProtoDetectionEnabledDefault(), AppLayerProtoDetectPPRegister(), AppLayerProtoDetectRegisterProtocol(), RunmodeIsUnittests(), and SCEnter.
RegisterENIPUDPParsers()
void RegisterENIPUDPParsers (void)
Function to register the ENIP protocol parsers and other functions.
Definition at line 443 of file app-layer-enip.c.
References ALPROTO_ENIP, AppLayerProtoDetectConfProtoDetectionEnabledDefault(), AppLayerProtoDetectPPRegister(), AppLayerProtoDetectRegisterProtocol(), RunmodeIsUnittests(), and SCEnter.