suricata: /Users/jlu/suricata/src/app-layer-ftp.h File Reference
app-layer-ftp.h File Reference
#include "rust.h"
Data Structures
struct FtpCommand_
struct FtpLineState_
struct FTPString_
struct FTPTransaction_
struct FtpState_
struct FtpDataState_
Typedefs
typedef struct FtpCommand_ FtpCommand
typedef uint32_t FtpRequestCommandArgOfs
typedef uint16_t FtpResponseCode
typedef struct FtpLineState_ FtpLineState
typedef struct FTPString_ FTPString
typedef struct FTPTransaction_ FTPTransaction
typedef struct FtpState_ FtpState
typedef struct FtpDataState_ FtpDataState
Enumerations
enum { FTP_STATE_IN_PROGRESS , FTP_STATE_PORT_DONE , FTP_STATE_FINISHED }
enum FtpRequestCommand {
FTP_COMMAND_UNKNOWN = 0 , FTP_COMMAND_ABOR , FTP_COMMAND_ACCT , FTP_COMMAND_ALLO ,
FTP_COMMAND_APPE , FTP_COMMAND_AUTH_TLS , FTP_COMMAND_CDUP , FTP_COMMAND_CHMOD ,
FTP_COMMAND_CWD , FTP_COMMAND_DELE , FTP_COMMAND_EPSV , FTP_COMMAND_HELP ,
FTP_COMMAND_IDLE , FTP_COMMAND_LIST , FTP_COMMAND_MAIL , FTP_COMMAND_MDTM ,
FTP_COMMAND_MKD , FTP_COMMAND_MLFL , FTP_COMMAND_MODE , FTP_COMMAND_MRCP ,
FTP_COMMAND_MRSQ , FTP_COMMAND_MSAM , FTP_COMMAND_MSND , FTP_COMMAND_MSOM ,
FTP_COMMAND_NLST , FTP_COMMAND_NOOP , FTP_COMMAND_PASS , FTP_COMMAND_PASV ,
FTP_COMMAND_PORT , FTP_COMMAND_PWD , FTP_COMMAND_QUIT , FTP_COMMAND_REIN ,
FTP_COMMAND_REST , FTP_COMMAND_RETR , FTP_COMMAND_RMD , FTP_COMMAND_RNFR ,
FTP_COMMAND_RNTO , FTP_COMMAND_SITE , FTP_COMMAND_SIZE , FTP_COMMAND_SMNT ,
FTP_COMMAND_STAT , FTP_COMMAND_STOR , FTP_COMMAND_STOU , FTP_COMMAND_STRU ,
FTP_COMMAND_SYST , FTP_COMMAND_TYPE , FTP_COMMAND_UMASK , FTP_COMMAND_USER ,
FTP_COMMAND_EPRT , FTP_COMMAND_MAX
}
enum {
FTP_FIELD_NONE = 0 , FTP_FIELD_REQUEST_LINE , FTP_FIELD_REQUEST_COMMAND , FTP_FIELD_REQUEST_ARGS ,
FTP_FIELD_RESPONSE_LINE , FTP_FIELD_REPONSE_CODE , FTP_FIELD_MAX
}
enum { FTPDATA_STATE_IN_PROGRESS , FTPDATA_STATE_FINISHED }
Functions
void RegisterFTPParsers (void)
void FTPParserRegisterTests (void)
void FTPAtExitPrintStats (void)
void FTPParserCleanup (void)
Free memory allocated for global FTP parser state.
uint64_t FTPMemuseGlobalCounter (void)
uint64_t FTPMemcapGlobalCounter (void)
uint16_t JsonGetNextLineFromBuffer (const char *buffer, const uint16_t len)
void EveFTPDataAddMetadata (const Flow *f, JsonBuilder *jb)
Variables
const FtpCommand FtpCommands [FTP_COMMAND_MAX+1]
Detailed Description
Author
Pablo Rincon Crespo pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Jeff Lucovsky jeff@.nosp@m.luco.nosp@m.vsky..nosp@m.org
Definition in file app-layer-ftp.h.
Typedef Documentation
FtpCommand
typedef struct FtpCommand_ FtpCommand
FtpDataState
typedef struct FtpDataState_ FtpDataState
FTP Data State for app layer parser
FtpLineState
typedef struct FtpLineState_ FtpLineState
used to hold the line state when we have fragmentation.
FtpRequestCommandArgOfs
typedef uint32_t FtpRequestCommandArgOfs
Definition at line 99 of file app-layer-ftp.h.
FtpResponseCode
typedef uint16_t FtpResponseCode
Definition at line 101 of file app-layer-ftp.h.
FtpState
typedef struct FtpState_ FtpState
FTP State for app layer parser
FTPString
typedef struct FTPString_ FTPString
FTPTransaction
typedef struct FTPTransaction_ FTPTransaction
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FTPDATA_STATE_IN_PROGRESS
FTPDATA_STATE_FINISHED
Definition at line 192 of file app-layer-ftp.h.
anonymous enum
anonymous enum
Enumerator
FTP_STATE_IN_PROGRESS
FTP_STATE_PORT_DONE
FTP_STATE_FINISHED
Definition at line 30 of file app-layer-ftp.h.
anonymous enum
anonymous enum
Enumerator
FTP_FIELD_NONE
FTP_FIELD_REQUEST_LINE
FTP_FIELD_REQUEST_COMMAND
FTP_FIELD_REQUEST_ARGS
FTP_FIELD_RESPONSE_LINE
FTP_FIELD_REPONSE_CODE
FTP_FIELD_MAX
Definition at line 103 of file app-layer-ftp.h.
FtpRequestCommand
enum FtpRequestCommand
Enumerator
FTP_COMMAND_UNKNOWN
FTP_COMMAND_ABOR
FTP_COMMAND_ACCT
FTP_COMMAND_ALLO
FTP_COMMAND_APPE
FTP_COMMAND_AUTH_TLS
FTP_COMMAND_CDUP
FTP_COMMAND_CHMOD
FTP_COMMAND_CWD
FTP_COMMAND_DELE
FTP_COMMAND_EPSV
FTP_COMMAND_HELP
FTP_COMMAND_IDLE
FTP_COMMAND_LIST
FTP_COMMAND_MAIL
FTP_COMMAND_MDTM
FTP_COMMAND_MKD
FTP_COMMAND_MLFL
FTP_COMMAND_MODE
FTP_COMMAND_MRCP
FTP_COMMAND_MRSQ
FTP_COMMAND_MSAM
FTP_COMMAND_MSND
FTP_COMMAND_MSOM
FTP_COMMAND_NLST
FTP_COMMAND_NOOP
FTP_COMMAND_PASS
FTP_COMMAND_PASV
FTP_COMMAND_PORT
FTP_COMMAND_PWD
FTP_COMMAND_QUIT
FTP_COMMAND_REIN
FTP_COMMAND_REST
FTP_COMMAND_RETR
FTP_COMMAND_RMD
FTP_COMMAND_RNFR
FTP_COMMAND_RNTO
FTP_COMMAND_SITE
FTP_COMMAND_SIZE
FTP_COMMAND_SMNT
FTP_COMMAND_STAT
FTP_COMMAND_STOR
FTP_COMMAND_STOU
FTP_COMMAND_STRU
FTP_COMMAND_SYST
FTP_COMMAND_TYPE
FTP_COMMAND_UMASK
FTP_COMMAND_USER
FTP_COMMAND_EPRT
FTP_COMMAND_MAX
Todo:
more if missing..
Definition at line 36 of file app-layer-ftp.h.
Function Documentation
EveFTPDataAddMetadata()
void EveFTPDataAddMetadata (const Flow * f, JsonBuilder * jb)
Definition at line 1486 of file app-layer-ftp.c.
References Flow_::alstate, FtpDataState_::command, FtpDataState_::file_len, FtpDataState_::file_name, FTP_COMMAND_RETR, FTP_COMMAND_STOR, and JB_SET_STRING.
FTPAtExitPrintStats()
void FTPAtExitPrintStats (void)
Definition at line 1448 of file app-layer-ftp.c.
References SCLogDebug, SCMutexLock, and SCMutexUnlock.
FTPMemcapGlobalCounter()
uint64_t FTPMemcapGlobalCounter (void)
Definition at line 196 of file app-layer-ftp.c.
References SC_ATOMIC_GET.
Referenced by AppLayerRegisterGlobalCounters().
FTPMemuseGlobalCounter()
uint64_t FTPMemuseGlobalCounter (void)
Definition at line 190 of file app-layer-ftp.c.
References SC_ATOMIC_GET.
Referenced by AppLayerRegisterGlobalCounters().
FTPParserCleanup()
void FTPParserCleanup (void)
Free memory allocated for global FTP parser state.
Definition at line 1512 of file app-layer-ftp.c.
Referenced by AppLayerParserDeSetup().
FTPParserRegisterTests()
void FTPParserRegisterTests (void)
Definition at line 1806 of file app-layer-ftp.c.
References UtRegisterTest().
JsonGetNextLineFromBuffer()
uint16_t JsonGetNextLineFromBuffer (const char * buffer, const uint16_t len)
Definition at line 1476 of file app-layer-ftp.c.
References len.
RegisterFTPParsers()
void RegisterFTPParsers (void)
FTP
Definition at line 1373 of file app-layer-ftp.c.
References ALPROTO_FTP, AppLayerProtoDetectConfProtoDetectionEnabled(), and AppLayerProtoDetectRegisterProtocol().
Variable Documentation
FtpCommands
const FtpCommand FtpCommands[FTP_COMMAND_MAX+1] extern
Definition at line 74 of file app-layer-ftp.c.