suricata: /Users/jlu/suricata/src/app-layer-htp-xff.c File Reference
app-layer-htp-xff.c File Reference
#include "suricata-common.h"
#include "conf.h"
#include "app-layer-parser.h"
#include "app-layer-htp.h"
#include "app-layer-htp-xff.h"
#include "util-misc.h"
#include "util-memrchr.h"
#include "util-unittest.h"
Macros
#define XFF_CHAIN_MINLEN 7
#define XFF_CHAIN_MAXLEN 256
#define XFF_DEFAULT "X-Forwarded-For"
Functions
int HttpXFFGetIPFromTx (const Flow *f, uint64_t tx_id, HttpXFFCfg *xff_cfg, char *dstbuf, int dstbuflen)
Function to return XFF IP if any in the selected transaction. The caller needs to lock the flow.
int HttpXFFGetIP (const Flow *f, HttpXFFCfg *xff_cfg, char *dstbuf, int dstbuflen)
Function to return XFF IP if any. The caller needs to lock the flow.
void HttpXFFGetCfg (ConfNode *conf, HttpXFFCfg *result)
Function to return XFF configuration from a configuration node.
void HTPXFFParserRegisterTests (void)
Detailed Description
Author
Ignacio Sanchez sanch.nosp@m.ezma.nosp@m.rtin..nosp@m.ji@g.nosp@m.mail..nosp@m.com
Duarte Silva duart.nosp@m.e.si.nosp@m.lva@s.nosp@m.eria.nosp@m.lizin.nosp@m.g.me
Definition in file app-layer-htp-xff.c.
Macro Definition Documentation
XFF_CHAIN_MAXLEN
#define XFF_CHAIN_MAXLEN 256
XFF header value maximum length
Definition at line 39 of file app-layer-htp-xff.c.
XFF_CHAIN_MINLEN
#define XFF_CHAIN_MINLEN 7
XFF header value minimal length
Definition at line 37 of file app-layer-htp-xff.c.
XFF_DEFAULT
#define XFF_DEFAULT "X-Forwarded-For"
Default XFF header name
Definition at line 41 of file app-layer-htp-xff.c.
Function Documentation
HTPXFFParserRegisterTests()
void HTPXFFParserRegisterTests (void)
Definition at line 333 of file app-layer-htp-xff.c.
References UtRegisterTest().
HttpXFFGetCfg()
void HttpXFFGetCfg (ConfNode * conf, HttpXFFCfg * result)
Function to return XFF configuration from a configuration node.
Definition at line 202 of file app-layer-htp-xff.c.
References BUG_ON, ConfNodeChildValueIsTrue(), ConfNodeLookupChild(), ConfNodeLookupChildValue(), HttpXFFCfg_::flags, HttpXFFCfg_::header, SC_WARN_XFF_INVALID_DEPLOYMENT, SC_WARN_XFF_INVALID_HEADER, SC_WARN_XFF_INVALID_MODE, SCLogWarning, XFF_DEFAULT, XFF_DISABLED, XFF_EXTRADATA, XFF_FORWARD, XFF_OVERWRITE, and XFF_REVERSE.
HttpXFFGetIP()
int HttpXFFGetIP (const Flow * f, HttpXFFCfg * xff_cfg, char * dstbuf, int dstbuflen)
Function to return XFF IP if any. The caller needs to lock the flow.
Return values
1 if the IP has been found and returned in dstbuf
0 if the IP has not being found or error
Definition at line 177 of file app-layer-htp-xff.c.
References AppLayerParserGetTxCnt(), FlowGetAppState(), HttpXFFGetIPFromTx(), and SCLogDebug.
HttpXFFGetIPFromTx()
int HttpXFFGetIPFromTx (const Flow * f, uint64_t tx_id, HttpXFFCfg * xff_cfg, char * dstbuf, int dstbuflen)
Function to return XFF IP if any in the selected transaction. The caller needs to lock the flow.
Return values
1 if the IP has been found and returned in dstbuf
0 if the IP has not being found or error
Get the last IP address from the chain
Get the first IP address from the chain
Definition at line 113 of file app-layer-htp-xff.c.
References ALPROTO_HTTP1, AppLayerParserGetTx(), AppLayerParserGetTxCnt(), HttpXFFCfg_::flags, FlowGetAppState(), HttpXFFCfg_::header, memrchr(), Flow_::proto, SCLogDebug, XFF_CHAIN_MAXLEN, XFF_CHAIN_MINLEN, and XFF_REVERSE.
Referenced by HttpXFFGetIP(), and JsonBuildFileInfoRecord().