suricata: /Users/jlu/suricata/src/app-layer-template-rust.c File Reference
app-layer-template-rust.c File Reference
#include "suricata-common.h"
#include "stream.h"
#include "conf.h"
#include "util-unittest.h"
#include "app-layer-detect-proto.h"
#include "app-layer-parser.h"
#include "app-layer-template-rust.h"
#include "rust.h"
Functions
void RegisterTemplateRustParsers (void)
void TemplateRustParserRegisterTests (void)
Detailed Description
Author
FirstName LastName <yourname@domain>
TemplateRust application layer detector and parser for learning and templaterust purposes.
This templaterust implements a simple application layer for something like the echo protocol running on port 7.
Definition in file app-layer-template-rust.c.
Function Documentation
RegisterTemplateRustParsers()
void RegisterTemplateRustParsers (void)
Definition at line 48 of file app-layer-template-rust.c.
References ALPROTO_TEMPLATE_RUST, AppLayerParserRegisterProtocolUnittests(), ConfGetNode(), SCLogNotice, and TemplateRustParserRegisterTests().
TemplateRustParserRegisterTests()
void TemplateRustParserRegisterTests (void)
Definition at line 67 of file app-layer-template-rust.c.
Referenced by RegisterTemplateRustParsers().