suricata: /Users/jlu/suricata/src/app-layer-detect-proto.h File Reference
app-layer-detect-proto.h File Reference
Typedefs
typedef struct AppLayerProtoDetectThreadCtx_ AppLayerProtoDetectThreadCtx
typedef AppProto(* ProbingParserFPtr) (Flow *f, uint8_t flags, const uint8_t *input, uint32_t input_len, uint8_t *rdir)
Functions
AppProto AppLayerProtoDetectGetProto (AppLayerProtoDetectThreadCtx *tctx, Flow *f, const uint8_t *buf, uint32_t buflen, uint8_t ipproto, uint8_t flags, bool *reverse_flow)
Returns the app layer protocol given a buffer.
int AppLayerProtoDetectPrepareState (void)
Prepares the internal state for protocol detection. This needs to be called once all the patterns and probing parser ports have been registered.
void AppLayerProtoDetectPPRegister (uint8_t ipproto, const char *portstr, AppProto alproto, uint16_t min_depth, uint16_t max_depth, uint8_t direction, ProbingParserFPtr ProbingParser1, ProbingParserFPtr ProbingParser2)
register parser at a port
int AppLayerProtoDetectPPParseConfPorts (const char *ipproto_name, uint8_t ipproto, const char *alproto_name, AppProto alproto, uint16_t min_depth, uint16_t max_depth, ProbingParserFPtr ProbingParserTs, ProbingParserFPtr ProbingParserTc)
int AppLayerProtoDetectPMRegisterPatternCS (uint8_t ipproto, AppProto alproto, const char *pattern, uint16_t depth, uint16_t offset, uint8_t direction)
Registers a case-sensitive pattern for protocol detection.
int AppLayerProtoDetectPMRegisterPatternCSwPP (uint8_t ipproto, AppProto alproto, const char *pattern, uint16_t depth, uint16_t offset, uint8_t direction, ProbingParserFPtr PPFunc, uint16_t pp_min_depth, uint16_t pp_max_depth)
int AppLayerProtoDetectPMRegisterPatternCI (uint8_t ipproto, AppProto alproto, const char *pattern, uint16_t depth, uint16_t offset, uint8_t direction)
Registers a case-insensitive pattern for protocol detection.
int AppLayerProtoDetectSetup (void)
The first function to be called. This initializes a global protocol detection context.
void AppLayerProtoDetectReset (Flow *)
Reset proto detect for flow.
bool AppLayerRequestProtocolChange (Flow *f, uint16_t dp, AppProto expect_proto)
request applayer to wrap up this protocol and rerun protocol detection.
bool AppLayerRequestProtocolTLSUpgrade (Flow *f)
request applayer to wrap up this protocol and rerun protocol detection with expectation of TLS. Used by STARTTLS.
int AppLayerProtoDetectDeSetup (void)
Cleans up the app layer protocol detection phase.
void AppLayerProtoDetectRegisterProtocol (AppProto alproto, const char *alproto_name)
Registers a protocol for protocol detection phase.
void AppLayerProtoDetectRegisterAlias (const char *proto_name, const char *proto_alias)
int AppLayerProtoDetectConfProtoDetectionEnabled (const char *ipproto, const char *alproto)
Given a protocol name, checks if proto detection is enabled in the conf file.
int AppLayerProtoDetectConfProtoDetectionEnabledDefault (const char *ipproto, const char *alproto, bool default_enabled)
Given a protocol name, checks if proto detection is enabled in the conf file.
AppLayerProtoDetectThreadCtx * AppLayerProtoDetectGetCtxThread (void)
Inits and returns an app layer protocol detection thread context.
void AppLayerProtoDetectDestroyCtxThread (AppLayerProtoDetectThreadCtx *tctx)
Destroys the app layer protocol detection thread context.
void AppLayerProtoDetectSupportedIpprotos (AppProto alproto, uint8_t *ipprotos)
AppProto AppLayerProtoDetectGetProtoByName (const char *alproto_name)
const char * AppLayerProtoDetectGetProtoName (AppProto alproto)
void AppLayerProtoDetectSupportedAppProtocols (AppProto *alprotos)
void AppLayerRegisterExpectationProto (uint8_t proto, AppProto alproto)
void AppLayerProtoDetectUnittestCtxBackup (void)
Backs up the internal context used by the app layer proto detection module.
void AppLayerProtoDetectUnittestCtxRestore (void)
Restores back the internal context used by the app layer proto detection module, that was previously backed up by calling AppLayerProtoDetectUnittestCtxBackup().
void AppLayerProtoDetectUnittestsRegister (void)
Register unittests for app layer proto detection module.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file app-layer-detect-proto.h.
Typedef Documentation
AppLayerProtoDetectThreadCtx
typedef struct AppLayerProtoDetectThreadCtx_ AppLayerProtoDetectThreadCtx
Definition at line 28 of file app-layer-detect-proto.h.
ProbingParserFPtr
typedef AppProto(* ProbingParserFPtr) (Flow *f, uint8_t flags, const uint8_t *input, uint32_t input_len, uint8_t *rdir)
Definition at line 30 of file app-layer-detect-proto.h.
Function Documentation
AppLayerProtoDetectConfProtoDetectionEnabled()
int AppLayerProtoDetectConfProtoDetectionEnabled (const char * ipproto, const char * alproto)
Given a protocol name, checks if proto detection is enabled in the conf file.
Parameters
alproto Name of the app layer protocol.
Return values
1 If enabled.
0 If disabled.
Definition at line 2080 of file app-layer-detect-proto.c.
References AppLayerProtoDetectConfProtoDetectionEnabledDefault().
Referenced by HTPFreeConfig(), RegisterFTPParsers(), RegisterHTPParsers(), RegisterNFSTCPParsers(), RegisterSMTPParsers(), RegisterSSHParsers(), RegisterSSLParsers(), and RegisterTFTPParsers().
AppLayerProtoDetectConfProtoDetectionEnabledDefault()
int AppLayerProtoDetectConfProtoDetectionEnabledDefault (const char * ipproto, const char * alproto, bool default_enabled)
Given a protocol name, checks if proto detection is enabled in the conf file.
Parameters
alproto Name of the app layer protocol.
default_enabled enable by default if not in the configuration file
Return values
1 If enabled.
0 If disabled.
Definition at line 2015 of file app-layer-detect-proto.c.
References BUG_ON, ConfGetNode(), ConfValIsFalse(), ConfValIsTrue(), FatalError, RunmodeIsUnittests(), SC_ERR_FATAL, SCEnter, SCLogDebug, SCLogError, SCReturnInt, and ConfNode_::val.
Referenced by AppLayerProtoDetectConfProtoDetectionEnabled(), RegisterDNP3Parsers(), RegisterENIPTCPParsers(), RegisterENIPUDPParsers(), RegisterHTTP2Parsers(), and RegisterTemplateParsers().
AppLayerProtoDetectDeSetup()
int AppLayerProtoDetectDeSetup (void)
Cleans up the app layer protocol detection phase.
Todo:
incomplete. Need more work.
Definition at line 1878 of file app-layer-detect-proto.c.
References FLOW_PROTO_DEFAULT, PatIntId, and SCEnter.
Referenced by AppLayerDeSetup().
AppLayerProtoDetectDestroyCtxThread()
void AppLayerProtoDetectDestroyCtxThread (AppLayerProtoDetectThreadCtx * tctx)
Destroys the app layer protocol detection thread context.
Parameters
tctx Pointer to the app layer protocol detection thread context.
Definition at line 2139 of file app-layer-detect-proto.c.
References FLOW_PROTO_DEFAULT, and SCEnter.
Referenced by AppLayerDestroyCtxThread().
AppLayerProtoDetectGetCtxThread()
AppLayerProtoDetectThreadCtx * AppLayerProtoDetectGetCtxThread (void)
Inits and returns an app layer protocol detection thread context.
Parameters
ctx Pointer to the app layer protocol detection context.
Return values
Pointer to the thread context, on success; NULL, on failure.
Definition at line 2085 of file app-layer-detect-proto.c.
References alpd_tctx, FLOW_PROTO_DEFAULT, PatIntId, and SCEnter.
Referenced by AppLayerGetCtxThread(), and LLVMFuzzerTestOneInput().
AppLayerProtoDetectGetProto()
AppProto AppLayerProtoDetectGetProto (AppLayerProtoDetectThreadCtx * tctx, Flow * f, const uint8_t * buf, uint32_t buflen, uint8_t ipproto, uint8_t flags, bool * reverse_flow)
Returns the app layer protocol given a buffer.
Parameters
tctx Pointer to the app layer protocol detection thread context.
f Pointer to the flow.
buf The buffer to be inspected.
buflen The length of the above buffer.
ipproto The ip protocol.
flags The direction bitfield - STREAM_TOSERVER/STREAM_TOCLIENT.
[out] reverse_flow true if flow is detected to be reversed
Return values
The app layer protocol.
Definition at line 1546 of file app-layer-detect-proto.c.
References ALPROTO_MAX, ALPROTO_UNKNOWN, flags, FLOW_IS_PM_DONE, SCEnter, and SCLogDebug.
Referenced by LLVMFuzzerTestOneInput().
AppLayerProtoDetectGetProtoByName()
AppProto AppLayerProtoDetectGetProtoByName (const char * alproto_name)
Definition at line 2182 of file app-layer-detect-proto.c.
References SCEnter.
Referenced by AppLayerGetProtoByName().
AppLayerProtoDetectGetProtoName()
const char * AppLayerProtoDetectGetProtoName (AppProto alproto)
Definition at line 2207 of file app-layer-detect-proto.c.
References ALPROTO_HTTP.
Referenced by AppLayerGetProtoName().
AppLayerProtoDetectPMRegisterPatternCI()
int AppLayerProtoDetectPMRegisterPatternCI (uint8_t ipproto, AppProto alproto, const char * pattern, uint16_t depth, uint16_t offset, uint8_t direction)
Registers a case-insensitive pattern for protocol detection.
Definition at line 1833 of file app-layer-detect-proto.c.
References SCEnter.
AppLayerProtoDetectPMRegisterPatternCS()
int AppLayerProtoDetectPMRegisterPatternCS (uint8_t ipproto, AppProto alproto, const char * pattern, uint16_t depth, uint16_t offset, uint8_t direction)
Registers a case-sensitive pattern for protocol detection.
Definition at line 1806 of file app-layer-detect-proto.c.
References SCEnter.
AppLayerProtoDetectPMRegisterPatternCSwPP()
int AppLayerProtoDetectPMRegisterPatternCSwPP (uint8_t ipproto, AppProto alproto, const char * pattern, uint16_t depth, uint16_t offset, uint8_t direction, ProbingParserFPtr PPFunc, uint16_t pp_min_depth, uint16_t pp_max_depth)
Definition at line 1819 of file app-layer-detect-proto.c.
References SCEnter.
AppLayerProtoDetectPPParseConfPorts()
int AppLayerProtoDetectPPParseConfPorts (const char * ipproto_name, uint8_t ipproto, const char * alproto_name, AppProto alproto, uint16_t min_depth, uint16_t max_depth, ProbingParserFPtr ProbingParserTs, ProbingParserFPtr ProbingParserTc)
Return values
bool 0 if no config was found, 1 if config was found
Definition at line 1732 of file app-layer-detect-proto.c.
References AppLayerProtoDetectPPRegister(), ConfGetNode(), ConfNodeLookupChild(), FatalError, SC_ERR_FATAL, SCEnter, SCLogDebug, SCReturnInt, and ConfNode_::val.
AppLayerProtoDetectPPRegister()
void AppLayerProtoDetectPPRegister (uint8_t ipproto, const char * portstr, AppProto alproto, uint16_t min_depth, uint16_t max_depth, uint8_t direction, ProbingParserFPtr ProbingParser1, ProbingParserFPtr ProbingParser2)
register parser at a port
Parameters
direction STREAM_TOSERVER or STREAM_TOCLIENT for dp or sp
Definition at line 1693 of file app-layer-detect-proto.c.
References DetectPortParse(), head, DetectPort_::port, DetectPort_::port2, and SCEnter.
Referenced by AppLayerProtoDetectPPParseConfPorts(), RegisterDNP3Parsers(), RegisterENIPTCPParsers(), RegisterENIPUDPParsers(), RegisterTemplateParsers(), and RegisterTFTPParsers().
AppLayerProtoDetectPrepareState()
int AppLayerProtoDetectPrepareState (void)
Prepares the internal state for protocol detection. This needs to be called once all the patterns and probing parser ports have been registered.
Definition at line 1649 of file app-layer-detect-proto.c.
References FLOW_PROTO_DEFAULT, and SCEnter.
Referenced by AppLayerSetup().
AppLayerProtoDetectRegisterAlias()
void AppLayerProtoDetectRegisterAlias (const char * proto_name, const char * proto_alias)
Definition at line 1920 of file app-layer-detect-proto.c.
References AppLayerProtoDetectAliases_::next, AppLayerProtoDetectAliases_::proto_alias, AppLayerProtoDetectAliases_::proto_name, SCEnter, SCMalloc, and unlikely.
Referenced by AppLayerRegisterParserAlias().
AppLayerProtoDetectRegisterProtocol()
void AppLayerProtoDetectRegisterProtocol (AppProto alproto, const char * alproto_name)
Registers a protocol for protocol detection phase.
   This is the first function to be called after calling the
   setup function, AppLayerProtoDetectSetup(), before calling any other
   app layer functions, AppLayerParser or AppLayerProtoDetect, alike.
   With this function you are associating/registering a string
   that can be used by users to write rules, i.e.
   you register the http protocol for protocol detection using
   AppLayerProtoDetectRegisterProtocol(ctx, ALPROTO_HTTP1, "http"),
   following which you can write rules like -
   alert http any any -> any any (sid:1;)
   which basically matches on the HTTP protocol.
Parameters
alproto The protocol.
alproto_str The string to associate with the above "alproto". Please send a static string that won't be destroyed post making this call, since this function won't create a copy of the received argument.
Return values
0 On success; -1 On failure.
Definition at line 1910 of file app-layer-detect-proto.c.
References SCEnter.
Referenced by RegisterDNP3Parsers(), RegisterENIPTCPParsers(), RegisterENIPUDPParsers(), RegisterFTPParsers(), RegisterHTPParsers(), RegisterHTTP2Parsers(), RegisterSMTPParsers(), RegisterSSHParsers(), RegisterSSLParsers(), RegisterTemplateParsers(), and RegisterTFTPParsers().
AppLayerProtoDetectReset()
void AppLayerProtoDetectReset (Flow * f)
Reset proto detect for flow.
Definition at line 1996 of file app-layer-detect-proto.c.
References Flow_::alparser, Flow_::alproto, Flow_::alproto_tc, Flow_::alproto_ts, ALPROTO_UNKNOWN, FLOW_RESET_PE_DONE, FLOW_RESET_PM_DONE, FLOW_RESET_PP_DONE, Flow_::probing_parser_toclient_alproto_masks, and Flow_::probing_parser_toserver_alproto_masks.
Referenced by LLVMFuzzerTestOneInput().
AppLayerProtoDetectSetup()
int AppLayerProtoDetectSetup (void)
The first function to be called. This initializes a global protocol detection context.
Return values
0 On succcess;
-1 On failure.
Definition at line 1848 of file app-layer-detect-proto.c.
References SCEnter.
Referenced by AppLayerSetup(), and LLVMFuzzerTestOneInput().
AppLayerProtoDetectSupportedAppProtocols()
void AppLayerProtoDetectSupportedAppProtocols (AppProto * alprotos)
Definition at line 2224 of file app-layer-detect-proto.c.
References ALPROTO_MAX, and SCEnter.
Referenced by AppLayerListSupportedProtocols(), AppLayerRegisterThreadCounters(), and AppLayerSetupCounters().
AppLayerProtoDetectSupportedIpprotos()
void AppLayerProtoDetectSupportedIpprotos (AppProto alproto, uint8_t * ipprotos)
Definition at line 2165 of file app-layer-detect-proto.c.
References ALPROTO_HTTP, ALPROTO_HTTP1, ALPROTO_HTTP2, AppLayerProtoDetectSupportedIpprotos(), and SCEnter.
Referenced by AppLayerProtoDetectSupportedIpprotos().
AppLayerProtoDetectUnittestCtxBackup()
void AppLayerProtoDetectUnittestCtxBackup (void)
Backs up the internal context used by the app layer proto detection module.
Definition at line 2272 of file app-layer-detect-proto.c.
References SCEnter.
AppLayerProtoDetectUnittestCtxRestore()
void AppLayerProtoDetectUnittestCtxRestore (void)
Restores back the internal context used by the app layer proto detection module, that was previously backed up by calling AppLayerProtoDetectUnittestCtxBackup().
Definition at line 2280 of file app-layer-detect-proto.c.
References SCEnter.
AppLayerProtoDetectUnittestsRegister()
void AppLayerProtoDetectUnittestsRegister (void)
Register unittests for app layer proto detection module.
Definition at line 3781 of file app-layer-detect-proto.c.
References SCEnter, and UtRegisterTest().
AppLayerRegisterExpectationProto()
void AppLayerRegisterExpectationProto (uint8_t proto, AppProto alproto)
Definition at line 2253 of file app-layer-detect-proto.c.
References expectation_proto, proto, SC_ERR_NOT_SUPPORTED, and SCLogError.
AppLayerRequestProtocolChange()
bool AppLayerRequestProtocolChange (Flow * f, uint16_t dp, AppProto expect_proto)
request applayer to wrap up this protocol and rerun protocol detection.
When this is called, the old session is reset unconditionally. A 'detect/log' flush packet is generated for both direction before the reset, so allow for final detection and logging.
Parameters
f flow to act on
dp destination port to use in protocol detection. Set to 443 for start tls, set to the HTTP uri port for CONNECT and set to 0 to not use it.
expect_proto expected protocol. AppLayer event will be set if detected protocol differs from this.
Definition at line 1960 of file app-layer-detect-proto.c.
References Flow_::alproto, Flow_::alproto_expect, Flow_::alproto_orig, Flow_::alproto_tc, Flow_::alproto_ts, ALPROTO_UNKNOWN, DEBUG_VALIDATE_BUG_ON, FlowChangeProto(), FlowSetChangeProtoFlag(), and Flow_::protodetect_dp.
Referenced by AppLayerRequestProtocolTLSUpgrade().
AppLayerRequestProtocolTLSUpgrade()
bool AppLayerRequestProtocolTLSUpgrade (Flow * f)
request applayer to wrap up this protocol and rerun protocol detection with expectation of TLS. Used by STARTTLS.
Sets detection port to 443 to make port based TLS detection work for SMTP, FTP etc as well.
Parameters
f flow to act on
Definition at line 1991 of file app-layer-detect-proto.c.
References ALPROTO_TLS, and AppLayerRequestProtocolChange().