suricata: /Users/jlu/suricata/src/app-layer-tftp.h File Reference
app-layer-tftp.h File Reference
Typedefs
typedef struct TFTPState_ TFTPState
typedef struct TFTPTransaction_ TFTPTransaction
Functions
void RegisterTFTPParsers (void)
Detailed Description
Author
Clément Galland cleme.nosp@m.nt.g.nosp@m.allan.nosp@m.d@ep.nosp@m.ita.f.nosp@m.r
Definition in file app-layer-tftp.h.
Typedef Documentation
TFTPState
typedef struct TFTPState_ TFTPState
Opaque Rust types.
Definition at line 30 of file app-layer-tftp.h.
TFTPTransaction
typedef struct TFTPTransaction_ TFTPTransaction
Definition at line 31 of file app-layer-tftp.h.
Function Documentation
RegisterTFTPParsers()
void RegisterTFTPParsers (void)
Definition at line 160 of file app-layer-tftp.c.
References ALPROTO_TFTP, AppLayerProtoDetectConfProtoDetectionEnabled(), AppLayerProtoDetectPPRegister(), AppLayerProtoDetectRegisterProtocol(), RunmodeIsUnittests(), SCLogDebug, TFTP_DEFAULT_PORT, and TFTP_MIN_FRAME_LEN.