suricata: /Users/jlu/suricata/src/app-layer-template.h File Reference
app-layer-template.h File Reference
#include "rust.h"
Data Structures
struct TemplateTransaction
struct TemplateState
Typedefs
typedef struct TemplateTransaction TemplateTransaction
typedef struct TemplateState TemplateState
Functions
void RegisterTemplateParsers (void)
void TemplateParserRegisterTests (void)
Detailed Description
Author
FirstName LastName <yourname@domain>
Definition in file app-layer-template.h.
Typedef Documentation
TemplateState
typedef struct TemplateState TemplateState
TemplateTransaction
typedef struct TemplateTransaction TemplateTransaction
Function Documentation
RegisterTemplateParsers()
void RegisterTemplateParsers (void)
Definition at line 449 of file app-layer-template.c.
References ALPROTO_TEMPLATE, AppLayerProtoDetectConfProtoDetectionEnabledDefault(), AppLayerProtoDetectPPRegister(), AppLayerProtoDetectRegisterProtocol(), RunmodeIsUnittests(), SCLogDebug, SCLogNotice, TEMPLATE_DEFAULT_PORT, and TEMPLATE_MIN_FRAME_LEN.
TemplateParserRegisterTests()
void TemplateParserRegisterTests (void)
Definition at line 550 of file app-layer-template.c.