suricata: /Users/jlu/suricata/src/app-layer-krb5.h File Reference
app-layer-krb5.h File Reference
Typedefs
typedef struct KRB5State_ KRB5State
typedef struct KRB5Transaction_ KRB5Transaction
Functions
void RegisterKRB5Parsers (void)
void KRB5ParserRegisterTests (void)
Detailed Description
Author
Pierre Chifflier chiff.nosp@m.lier.nosp@m.@wzdf.nosp@m.tpd..nosp@m.net
Definition in file app-layer-krb5.h.
Typedef Documentation
KRB5State
typedef struct KRB5State_ KRB5State
Opaque Rust types.
Definition at line 31 of file app-layer-krb5.h.
KRB5Transaction
typedef struct KRB5Transaction_ KRB5Transaction
Definition at line 32 of file app-layer-krb5.h.
Function Documentation
KRB5ParserRegisterTests()
void KRB5ParserRegisterTests (void)
Definition at line 51 of file app-layer-krb5.c.
Referenced by RegisterKRB5Parsers().
RegisterKRB5Parsers()
void RegisterKRB5Parsers (void)
Definition at line 38 of file app-layer-krb5.c.
References ALPROTO_KRB5, AppLayerParserRegisterProtocolUnittests(), and KRB5ParserRegisterTests().