suricata: /Users/jlu/suricata/src/app-layer-template.c File Reference
app-layer-template.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "stream.h"
#include "conf.h"
#include "app-layer.h"
#include "app-layer-detect-proto.h"
#include "app-layer-parser.h"
#include "app-layer-template.h"
#include "util-unittest.h"
#include "util-validate.h"
#include "util-enum.h"
Macros
#define TEMPLATE_DEFAULT_PORT "7"
#define TEMPLATE_MIN_FRAME_LEN 1
Enumerations
enum { TEMPLATE_DECODER_EVENT_EMPTY_MESSAGE }
Functions
void RegisterTemplateParsers (void)
void TemplateParserRegisterTests (void)
Variables
SCEnumCharMap template_decoder_event_table []
Detailed Description
Author
FirstName LastName <yourname@domain>
Template application layer detector and parser for learning and template purposes.
This template implements a simple application layer for something like the echo protocol running on port 7.
Definition in file app-layer-template.c.
Macro Definition Documentation
TEMPLATE_DEFAULT_PORT
#define TEMPLATE_DEFAULT_PORT "7"
Definition at line 51 of file app-layer-template.c.
TEMPLATE_MIN_FRAME_LEN
#define TEMPLATE_MIN_FRAME_LEN 1
Definition at line 55 of file app-layer-template.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
TEMPLATE_DECODER_EVENT_EMPTY_MESSAGE
Definition at line 67 of file app-layer-template.c.
Function Documentation
RegisterTemplateParsers()
void RegisterTemplateParsers (void)
Definition at line 449 of file app-layer-template.c.
References ALPROTO_TEMPLATE, AppLayerProtoDetectConfProtoDetectionEnabledDefault(), AppLayerProtoDetectPPRegister(), AppLayerProtoDetectRegisterProtocol(), RunmodeIsUnittests(), SCLogDebug, SCLogNotice, TEMPLATE_DEFAULT_PORT, and TEMPLATE_MIN_FRAME_LEN.
TemplateParserRegisterTests()
void TemplateParserRegisterTests (void)
Definition at line 550 of file app-layer-template.c.
Variable Documentation
template_decoder_event_table
SCEnumCharMap template_decoder_event_table[]
Initial value:
= {
    {"EMPTY_MESSAGE", TEMPLATE_DECODER_EVENT_EMPTY_MESSAGE},
    { NULL, -1 },
}
Definition at line 71 of file app-layer-template.c.