suricata: /Users/jlu/suricata/src/app-layer-modbus.c File Reference
app-layer-modbus.c File Reference
#include "suricata-common.h"
#include "util-debug.h"
#include "app-layer-parser.h"
#include "app-layer-modbus.h"
#include "detect-engine-build.h"
#include "detect.h"
#include "detect-engine.h"
#include "detect-parse.h"
#include "flow-util.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "stream-tcp.h"
#include "stream-tcp-private.h"
#include "rust.h"
Macros
#define MODBUS_CONFIG_DEFAULT_STREAM_DEPTH 0
Functions
void ModbusParserRegisterTests (void)
void RegisterModbusParsers (void)
Function to register the Modbus protocol parser.
Detailed Description
Author
David DIALLO diall.nosp@m.o@et.nosp@m..esie.nosp@m.a.fr
App-layer parser for Modbus protocol
Definition in file app-layer-modbus.c.
Macro Definition Documentation
MODBUS_CONFIG_DEFAULT_STREAM_DEPTH
#define MODBUS_CONFIG_DEFAULT_STREAM_DEPTH 0
Definition at line 77 of file app-layer-modbus.c.
Function Documentation
ModbusParserRegisterTests()
void ModbusParserRegisterTests (void)
Definition at line 1520 of file app-layer-modbus.c.
References UtRegisterTest().
Referenced by RegisterModbusParsers().
RegisterModbusParsers()
void RegisterModbusParsers (void)
Function to register the Modbus protocol parser.
Definition at line 50 of file app-layer-modbus.c.
References ALPROTO_MODBUS, AppLayerParserRegisterProtocolUnittests(), ModbusParserRegisterTests(), and SCReturn.