suricata: /Users/jlu/suricata/src/app-layer-enip.c File Reference
app-layer-enip.c File Reference
#include "suricata-common.h"
#include "util-debug.h"
#include "util-byte.h"
#include "util-enum.h"
#include "util-mem.h"
#include "util-misc.h"
#include "stream.h"
#include "app-layer.h"
#include "app-layer-protos.h"
#include "app-layer-parser.h"
#include "app-layer-enip.h"
#include "app-layer-enip-common.h"
#include "app-layer-detect-proto.h"
#include "conf.h"
#include "decode.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "pkt-var.h"
#include "util-profiling.h"
#include "flow-util.h"
#include "stream-tcp.h"
Macros
#define ENIP_LEN_REGISTER_SESSION 4
Functions
void RegisterENIPUDPParsers (void)
Function to register the ENIP protocol parsers and other functions.
void RegisterENIPTCPParsers (void)
Function to register the ENIP protocol parsers and other functions.
void ENIPParserRegisterTests (void)
Variables
SCEnumCharMap enip_decoder_event_table []
Detailed Description
Author
Kevin Wong kwong.nosp@m.@sol.nosp@m.anane.nosp@m.twor.nosp@m.ks.co.nosp@m.m
App-layer parser for ENIP protocol
Definition in file app-layer-enip.c.
Macro Definition Documentation
ENIP_LEN_REGISTER_SESSION
#define ENIP_LEN_REGISTER_SESSION 4
Definition at line 345 of file app-layer-enip.c.
Function Documentation
ENIPParserRegisterTests()
void ENIPParserRegisterTests (void)
Definition at line 656 of file app-layer-enip.c.
References UtRegisterTest().
RegisterENIPTCPParsers()
void RegisterENIPTCPParsers (void)
Function to register the ENIP protocol parsers and other functions.
Definition at line 526 of file app-layer-enip.c.
References ALPROTO_ENIP, AppLayerProtoDetectConfProtoDetectionEnabledDefault(), AppLayerProtoDetectPPRegister(), AppLayerProtoDetectRegisterProtocol(), RunmodeIsUnittests(), and SCEnter.
RegisterENIPUDPParsers()
void RegisterENIPUDPParsers (void)
Function to register the ENIP protocol parsers and other functions.
Definition at line 443 of file app-layer-enip.c.
References ALPROTO_ENIP, AppLayerProtoDetectConfProtoDetectionEnabledDefault(), AppLayerProtoDetectPPRegister(), AppLayerProtoDetectRegisterProtocol(), RunmodeIsUnittests(), and SCEnter.
Variable Documentation
enip_decoder_event_table
SCEnumCharMap enip_decoder_event_table[]
Initial value:
= {
    { NULL,                         -1 },
}
Definition at line 57 of file app-layer-enip.c.