suricata: /Users/jlu/suricata/src/app-layer-events.h File Reference
app-layer-events.h File Reference
#include "decode.h"
Data Structures
struct AppLayerDecoderEvents_
Data structure to store app layer decoder events.
Typedefs
typedef enum AppLayerEventType_ AppLayerEventType
Enumerations
enum {
APPLAYER_MISMATCH_PROTOCOL_BOTH_DIRECTIONS , APPLAYER_WRONG_DIRECTION_FIRST_DATA , APPLAYER_DETECT_PROTOCOL_ONLY_ONE_DIRECTION , APPLAYER_PROTO_DETECTION_SKIPPED ,
APPLAYER_NO_TLS_AFTER_STARTTLS , APPLAYER_UNEXPECTED_PROTOCOL
}
enum AppLayerEventType_ { APP_LAYER_EVENT_TYPE_TRANSACTION = 1 , APP_LAYER_EVENT_TYPE_PACKET }
Functions
int AppLayerGetPktEventInfo (const char *event_name, int *event_id)
int AppLayerGetEventInfoById (int event_id, const char **event_name, AppLayerEventType *event_type)
void AppLayerDecoderEventsSetEventRaw (AppLayerDecoderEvents **sevents, uint8_t event)
Set an app layer decoder event.
void AppLayerDecoderEventsResetEvents (AppLayerDecoderEvents *events)
void AppLayerDecoderEventsFreeEvents (AppLayerDecoderEvents **events)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file app-layer-events.h.
Typedef Documentation
AppLayerEventType
typedef enum AppLayerEventType_ AppLayerEventType
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
APPLAYER_MISMATCH_PROTOCOL_BOTH_DIRECTIONS
APPLAYER_WRONG_DIRECTION_FIRST_DATA
APPLAYER_DETECT_PROTOCOL_ONLY_ONE_DIRECTION
APPLAYER_PROTO_DETECTION_SKIPPED
APPLAYER_NO_TLS_AFTER_STARTTLS
APPLAYER_UNEXPECTED_PROTOCOL
Definition at line 46 of file app-layer-events.h.
AppLayerEventType_
enum AppLayerEventType_
Enumerator
APP_LAYER_EVENT_TYPE_TRANSACTION
APP_LAYER_EVENT_TYPE_PACKET
Definition at line 56 of file app-layer-events.h.
Function Documentation
AppLayerDecoderEventsFreeEvents()
void AppLayerDecoderEventsFreeEvents (AppLayerDecoderEvents ** events)
Definition at line 132 of file app-layer-events.c.
AppLayerDecoderEventsResetEvents()
void AppLayerDecoderEventsResetEvents (AppLayerDecoderEvents * events)
Definition at line 123 of file app-layer-events.c.
AppLayerDecoderEventsSetEventRaw()
void AppLayerDecoderEventsSetEventRaw (AppLayerDecoderEvents ** sevents, uint8_t event)
Set an app layer decoder event.
Parameters
sevents Pointer to a AppLayerDecoderEvents pointer. If *sevents is NULL memory will be allocated.
event The event to be stored.
Definition at line 89 of file app-layer-events.c.
References DECODER_EVENTS_BUFFER_STEPS, SCMalloc, and SCRealloc.
Referenced by DetectEngineSetEvent().
AppLayerGetEventInfoById()
int AppLayerGetEventInfoById (int event_id, const char ** event_name, AppLayerEventType * event_type)
Definition at line 51 of file app-layer-events.c.
References app_layer_event_pkt_table, APP_LAYER_EVENT_TYPE_PACKET, SC_ERR_INVALID_ENUM_MAP, SCLogError, and SCMapEnumValueToName().
AppLayerGetPktEventInfo()
int AppLayerGetPktEventInfo (const char * event_name, int * event_id)
Definition at line 67 of file app-layer-events.c.
References app_layer_event_pkt_table, SC_ERR_INVALID_ENUM_MAP, SCLogError, and SCMapEnumNameToValue().