suricata: /Users/jlu/suricata/src/app-layer-template-rust.h File Reference
app-layer-template-rust.h File Reference
Functions
void RegisterTemplateRustParsers (void)
void TemplateRustParserRegisterTests (void)
Detailed Description
Author
FirstName LastName <yourname@domain>
Definition in file app-layer-template-rust.h.
Function Documentation
RegisterTemplateRustParsers()
void RegisterTemplateRustParsers (void)
Definition at line 48 of file app-layer-template-rust.c.
References ALPROTO_TEMPLATE_RUST, AppLayerParserRegisterProtocolUnittests(), ConfGetNode(), SCLogNotice, and TemplateRustParserRegisterTests().
TemplateRustParserRegisterTests()
void TemplateRustParserRegisterTests (void)
Definition at line 67 of file app-layer-template-rust.c.
Referenced by RegisterTemplateRustParsers().