suricata: /Users/jlu/suricata/src/app-layer-http2.c File Reference
app-layer-http2.c File Reference
#include "suricata-common.h"
#include "stream.h"
#include "conf.h"
#include "util-unittest.h"
#include "app-layer-detect-proto.h"
#include "app-layer-parser.h"
#include "app-layer-htp.h"
#include "app-layer-http2.h"
#include "rust.h"
Functions
void RegisterHTTP2Parsers (void)
void HTTP2MimicHttp1Request (void *alstate_orig, void *h2s)
Detailed Description
Author
Philippe Antoine p.ant.nosp@m.oine.nosp@m.@cate.nosp@m.nacy.nosp@m.ber.f.nosp@m.r
Parser for HTTP2, RFC 7540
Definition in file app-layer-http2.c.
Function Documentation
HTTP2MimicHttp1Request()
void HTTP2MimicHttp1Request (void * alstate_orig, void * h2s)
Definition at line 74 of file app-layer-http2.c.
References HtpGetTxForH2().
RegisterHTTP2Parsers()
void RegisterHTTP2Parsers (void)
Definition at line 56 of file app-layer-http2.c.
References ALPROTO_HTTP2, AppLayerProtoDetectConfProtoDetectionEnabledDefault(), and AppLayerProtoDetectRegisterProtocol().