suricata: /Users/jlu/suricata/src/conf-yaml-loader.c File Reference
conf-yaml-loader.c File Reference
#include "suricata-common.h"
#include "conf.h"
#include "conf-yaml-loader.h"
#include <yaml.h>
#include "util-path.h"
#include "util-debug.h"
#include "util-unittest.h"
Macros
#define YAML_VERSION_MAJOR 1
#define YAML_VERSION_MINOR 1
#define RECURSION_LIMIT 128
#define DEFAULT_NAME_LEN 16
#define MANGLE_ERRORS_MAX 10
Enumerations
enum conf_state { CONF_KEY = 0 , CONF_VAL , CONF_INCLUDE }
Functions
int ConfYamlLoadFile (const char *filename)
Load configuration from a YAML file.
int ConfYamlLoadString (const char *string, size_t len)
Load configuration from a YAML string.
int ConfYamlLoadFileWithPrefix (const char *filename, const char *prefix)
Load configuration from a YAML file, insert in tree at 'prefix'.
void ConfYamlRegisterTests (void)
Detailed Description
Author
Endace Technology Limited - Jason Ish jason.nosp@m..ish.nosp@m.@enda.nosp@m.ce.c.nosp@m.om
YAML configuration loader.
Definition in file conf-yaml-loader.c.
Macro Definition Documentation
DEFAULT_NAME_LEN
#define DEFAULT_NAME_LEN 16
Definition at line 44 of file conf-yaml-loader.c.
MANGLE_ERRORS_MAX
#define MANGLE_ERRORS_MAX 10
Definition at line 46 of file conf-yaml-loader.c.
RECURSION_LIMIT
#define RECURSION_LIMIT 128
Definition at line 39 of file conf-yaml-loader.c.
YAML_VERSION_MAJOR
#define YAML_VERSION_MAJOR 1
Definition at line 34 of file conf-yaml-loader.c.
YAML_VERSION_MINOR
#define YAML_VERSION_MINOR 1
Definition at line 35 of file conf-yaml-loader.c.
Enumeration Type Documentation
conf_state
enum conf_state
Enumerator
CONF_KEY
CONF_VAL
CONF_INCLUDE
Definition at line 54 of file conf-yaml-loader.c.
Function Documentation
ConfYamlLoadFile()
int ConfYamlLoadFile (const char * filename)
Load configuration from a YAML file.
This function will load a configuration file. On failure -1 will be returned and it is suggested that the program then exit. Any errors while loading the configuration file will have already been logged.
Parameters
filename Filename of configuration file to load.
Return values
0 on success, -1 on failure.
Definition at line 440 of file conf-yaml-loader.c.
Referenced by ListAppLayerProtocols().
ConfYamlLoadFileWithPrefix()
int ConfYamlLoadFileWithPrefix (const char * filename, const char * prefix)
Load configuration from a YAML file, insert in tree at 'prefix'.
This function will load a configuration file and insert it into the config tree at 'prefix'. This means that if this is called with prefix "abc" and the file contains a parameter "def", it will be loaded as "abc.def".
Parameters
filename Filename of configuration file to load.
prefix Name prefix to use.
Return values
0 on success, -1 on failure.
Definition at line 518 of file conf-yaml-loader.c.
ConfYamlLoadString()
int ConfYamlLoadString (const char * string, size_t len)
Load configuration from a YAML string.
Definition at line 487 of file conf-yaml-loader.c.
Referenced by LLVMFuzzerTestOneInput().
ConfYamlRegisterTests()
void ConfYamlRegisterTests (void)
Definition at line 1000 of file conf-yaml-loader.c.
References UtRegisterTest().