suricata: /Users/jlu/suricata/src/datasets.h File Reference
datasets.h File Reference
#include "util-thash.h"
#include "datasets-reputation.h"
Data Structures
struct Dataset
Macros
#define DATASET_TYPE_NOTSET 0
#define DATASET_NAME_MAX_LEN 63
Typedefs
typedef struct Dataset Dataset
Enumerations
enum DatasetTypes { DATASET_TYPE_STRING = 1 , DATASET_TYPE_MD5 , DATASET_TYPE_SHA256 }
Functions
int DatasetsInit (void)
void DatasetsDestroy (void)
void DatasetsSave (void)
void DatasetReload (void)
void DatasetPostReloadCleanup (void)
enum DatasetTypes DatasetGetTypeFromString (const char *s)
Dataset * DatasetFind (const char *name, enum DatasetTypes type)
look for set by name without creating it
Dataset * DatasetGet (const char *name, enum DatasetTypes type, const char *save, const char *load, uint64_t memcap, uint32_t hashsize)
int DatasetAdd (Dataset *set, const uint8_t *data, const uint32_t data_len)
int DatasetLookup (Dataset *set, const uint8_t *data, const uint32_t data_len)
see if data is part of the set
DataRepResultType DatasetLookupwRep (Dataset *set, const uint8_t *data, const uint32_t data_len, const DataRepType *rep)
int DatasetAddSerialized (Dataset *set, const char *string)
add serialized data to set
int DatasetRemoveSerialized (Dataset *set, const char *string)
remove serialized data from set
Macro Definition Documentation
DATASET_NAME_MAX_LEN
#define DATASET_NAME_MAX_LEN 63
Definition at line 37 of file datasets.h.
DATASET_TYPE_NOTSET
#define DATASET_TYPE_NOTSET 0
Definition at line 31 of file datasets.h.
Typedef Documentation
Dataset
typedef struct Dataset Dataset
Enumeration Type Documentation
DatasetTypes
enum DatasetTypes
Enumerator
DATASET_TYPE_STRING
DATASET_TYPE_MD5
DATASET_TYPE_SHA256
Definition at line 30 of file datasets.h.
Function Documentation
DatasetAdd()
int DatasetAdd (Dataset * set, const uint8_t * data, const uint32_t data_len)
Definition at line 1101 of file datasets.c.
References DATASET_TYPE_STRING, and Dataset::type.
Referenced by DetectDatasetBufferMatch().
DatasetAddSerialized()
int DatasetAddSerialized (Dataset * set, const char * string)
add serialized data to set
Return values
int 1 added
int 0 already in hash
int -1 API error (not added)
int -2 DATA error
Definition at line 1140 of file datasets.c.
References BASE64_ECODE_ERR, BASE64_MODE_STRICT, code, DATASET_TYPE_STRING, DecodeBase64(), and Dataset::type.
DatasetFind()
Dataset * DatasetFind (const char * name, enum DatasetTypes type)
look for set by name without creating it
Definition at line 415 of file datasets.c.
References SCMutexLock, and sets_lock.
DatasetGet()
Dataset * DatasetGet (const char * name, enum DatasetTypes type, const char * save, const char * load, uint64_t memcap, uint32_t hashsize)
Definition at line 429 of file datasets.c.
References DATASET_NAME_MAX_LEN, SCMutexLock, and sets_lock.
DatasetGetTypeFromString()
enum DatasetTypes DatasetGetTypeFromString (const char * s)
Definition at line 52 of file datasets.c.
References DATASET_TYPE_MD5, DATASET_TYPE_NOTSET, DATASET_TYPE_SHA256, and DATASET_TYPE_STRING.
DatasetLookup()
int DatasetLookup (Dataset * set, const uint8_t * data, const uint32_t data_len)
see if data is part of the set
Parameters
set dataset
data data to look up
data_len length in bytes of data
Return values
-1 error
0 not found
1 found
Definition at line 952 of file datasets.c.
References DATASET_TYPE_STRING, and Dataset::type.
Referenced by DetectDatasetBufferMatch().
DatasetLookupwRep()
DataRepResultType DatasetLookupwRep (Dataset * set, const uint8_t * data, const uint32_t data_len, const DataRepType * rep)
Definition at line 968 of file datasets.c.
References DATASET_TYPE_STRING, DataRepResultType::found, and Dataset::type.
Referenced by DetectDatarepBufferMatch().
DatasetPostReloadCleanup()
void DatasetPostReloadCleanup (void)
Definition at line 583 of file datasets.c.
References SCLogDebug, SCMutexLock, and sets_lock.
DatasetReload()
void DatasetReload (void)
Definition at line 561 of file datasets.c.
References SCMutexLock, and sets_lock.
DatasetRemoveSerialized()
int DatasetRemoveSerialized (Dataset * set, const char * string)
remove serialized data from set
Return values
int 1 removed
int 0 found but busy (not removed)
int -1 API error (not removed)
int -2 DATA error
Definition at line 1224 of file datasets.c.
References BASE64_ECODE_ERR, BASE64_MODE_STRICT, code, DATASET_TYPE_STRING, DecodeBase64(), and Dataset::type.
DatasetsDestroy()
void DatasetsDestroy (void)
Definition at line 743 of file datasets.c.
References SCLogDebug.
DatasetsInit()
int DatasetsInit (void)
Definition at line 632 of file datasets.c.
References ConfGetNode(), and SCLogDebug.
Referenced by PreRunPostPrivsDropInit().
DatasetsSave()
void DatasetsSave (void)
Definition at line 790 of file datasets.c.
References SCLogDebug.