suricata: /Users/jlu/suricata/src/datasets.c File Reference
datasets.c File Reference
#include "suricata-common.h"
#include "conf.h"
#include "datasets.h"
#include "datasets-string.h"
#include "datasets-md5.h"
#include "datasets-sha256.h"
#include "datasets-reputation.h"
#include "util-thash.h"
#include "util-print.h"
#include "util-base64.h"
#include "util-byte.h"
#include "util-misc.h"
Enumerations
enum DatasetGetPathType { TYPE_STATE , TYPE_LOAD }
Functions
enum DatasetTypes DatasetGetTypeFromString (const char *s)
Dataset * DatasetFind (const char *name, enum DatasetTypes type)
look for set by name without creating it
Dataset * DatasetGet (const char *name, enum DatasetTypes type, const char *save, const char *load, uint64_t memcap, uint32_t hashsize)
void DatasetReload (void)
void DatasetPostReloadCleanup (void)
int DatasetsInit (void)
void DatasetsDestroy (void)
void DatasetsSave (void)
int DatasetLookup (Dataset *set, const uint8_t *data, const uint32_t data_len)
see if data is part of the set
DataRepResultType DatasetLookupwRep (Dataset *set, const uint8_t *data, const uint32_t data_len, const DataRepType *rep)
int DatasetAdd (Dataset *set, const uint8_t *data, const uint32_t data_len)
int DatasetAddSerialized (Dataset *set, const char *string)
add serialized data to set
int DatasetRemoveSerialized (Dataset *set, const char *string)
remove serialized data from set
Variables
SCMutex sets_lock = SCMUTEX_INITIALIZER
bool g_system
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file datasets.c.
Enumeration Type Documentation
DatasetGetPathType
enum DatasetGetPathType
Enumerator
TYPE_STATE
TYPE_LOAD
Definition at line 377 of file datasets.c.
Function Documentation
DatasetAdd()
int DatasetAdd (Dataset * set, const uint8_t * data, const uint32_t data_len)
Definition at line 1101 of file datasets.c.
References DATASET_TYPE_STRING, and Dataset::type.
Referenced by DetectDatasetBufferMatch().
DatasetAddSerialized()
int DatasetAddSerialized (Dataset * set, const char * string)
add serialized data to set
Return values
int 1 added
int 0 already in hash
int -1 API error (not added)
int -2 DATA error
Definition at line 1140 of file datasets.c.
References BASE64_ECODE_ERR, BASE64_MODE_STRICT, code, DATASET_TYPE_STRING, DecodeBase64(), and Dataset::type.
DatasetFind()
Dataset * DatasetFind (const char * name, enum DatasetTypes type)
look for set by name without creating it
Definition at line 415 of file datasets.c.
References SCMutexLock, and sets_lock.
DatasetGet()
Dataset * DatasetGet (const char * name, enum DatasetTypes type, const char * save, const char * load, uint64_t memcap, uint32_t hashsize)
Definition at line 429 of file datasets.c.
References DATASET_NAME_MAX_LEN, SCMutexLock, and sets_lock.
DatasetGetTypeFromString()
enum DatasetTypes DatasetGetTypeFromString (const char * s)
Definition at line 52 of file datasets.c.
References DATASET_TYPE_MD5, DATASET_TYPE_NOTSET, DATASET_TYPE_SHA256, and DATASET_TYPE_STRING.
DatasetLookup()
int DatasetLookup (Dataset * set, const uint8_t * data, const uint32_t data_len)
see if data is part of the set
Parameters
set dataset
data data to look up
data_len length in bytes of data
Return values
-1 error
0 not found
1 found
Definition at line 952 of file datasets.c.
References DATASET_TYPE_STRING, and Dataset::type.
Referenced by DetectDatasetBufferMatch().
DatasetLookupwRep()
DataRepResultType DatasetLookupwRep (Dataset * set, const uint8_t * data, const uint32_t data_len, const DataRepType * rep)
Definition at line 968 of file datasets.c.
References DATASET_TYPE_STRING, DataRepResultType::found, and Dataset::type.
Referenced by DetectDatarepBufferMatch().
DatasetPostReloadCleanup()
void DatasetPostReloadCleanup (void)
Definition at line 583 of file datasets.c.
References SCLogDebug, SCMutexLock, and sets_lock.
DatasetReload()
void DatasetReload (void)
Definition at line 561 of file datasets.c.
References SCMutexLock, and sets_lock.
DatasetRemoveSerialized()
int DatasetRemoveSerialized (Dataset * set, const char * string)
remove serialized data from set
Return values
int 1 removed
int 0 found but busy (not removed)
int -1 API error (not removed)
int -2 DATA error
Definition at line 1224 of file datasets.c.
References BASE64_ECODE_ERR, BASE64_MODE_STRICT, code, DATASET_TYPE_STRING, DecodeBase64(), and Dataset::type.
DatasetsDestroy()
void DatasetsDestroy (void)
Definition at line 743 of file datasets.c.
References SCLogDebug.
DatasetsInit()
int DatasetsInit (void)
Definition at line 632 of file datasets.c.
References ConfGetNode(), and SCLogDebug.
Referenced by PreRunPostPrivsDropInit().
DatasetsSave()
void DatasetsSave (void)
Definition at line 790 of file datasets.c.
References SCLogDebug.
Variable Documentation
g_system
bool g_system extern
Definition at line 233 of file suricata.c.
sets_lock
SCMutex sets_lock = SCMUTEX_INITIALIZER
Definition at line 37 of file datasets.c.
Referenced by DatasetFind(), DatasetGet(), DatasetPostReloadCleanup(), and DatasetReload().