suricata: /Users/jlu/suricata/src/decode-ipv6.c File Reference
decode-ipv6.c File Reference
Packet decoding
#include "suricata-common.h"
#include "packet-queue.h"
#include "decode.h"
#include "decode-ipv6.h"
#include "decode-icmpv6.h"
#include "decode-events.h"
#include "defrag.h"
#include "pkt-var.h"
#include "util-debug.h"
#include "util-print.h"
#include "util-unittest.h"
#include "util-profiling.h"
#include "util-validate.h"
#include "host.h"
Functions
void DecodeIPV6FragHeader (Packet *p, const uint8_t *pkt, uint16_t hdrextlen, uint16_t plen, uint16_t prev_hdrextlen)
int DecodeIPV6 (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p, const uint8_t *pkt, uint16_t len)
void DecodeIPV6RegisterTests (void)
this function registers unit tests for IPV6 decoder
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Decode IPv6
Definition in file decode-ipv6.c.
Function Documentation
DecodeIPV6()
int DecodeIPV6 (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint16_t len)
Definition at line 572 of file decode-ipv6.c.
References DecodeThreadVars_::counter_ipv6, dtv, StatsIncr(), and tv.
Referenced by DecodeNull(), DecodePPPOESession(), and DecodeRaw().
DecodeIPV6FragHeader()
void DecodeIPV6FragHeader (Packet * p, const uint8_t * pkt, uint16_t hdrextlen, uint16_t plen, uint16_t prev_hdrextlen)
Definition at line 101 of file decode-ipv6.c.
References IPV6ExtHdrs_::fh_data_len, IPV6ExtHdrs_::fh_data_offset, IPV6ExtHdrs_::fh_header_offset, IPV6ExtHdrs_::fh_id, IPV6ExtHdrs_::fh_more_frags_set, IPV6ExtHdrs_::fh_nh, IPV6ExtHdrs_::fh_offset, IPV6ExtHdrs_::fh_prev_hdr_offset, GET_PKT_DATA, Packet_::ip6eh, SCLogDebug, and SCNtohl.
DecodeIPV6RegisterTests()
void DecodeIPV6RegisterTests (void)
this function registers unit tests for IPV6 decoder
Definition at line 907 of file decode-ipv6.c.
References UtRegisterTest().