suricata: /Users/jlu/suricata/src/decode-raw.c File Reference
decode-raw.c File Reference
Packet decoding
#include "suricata-common.h"
#include "decode.h"
#include "decode-raw.h"
#include "decode-events.h"
#include "util-validate.h"
#include "util-unittest.h"
#include "util-debug.h"
#include "pkt-var.h"
#include "util-profiling.h"
#include "host.h"
#include "flow.h"
#include "flow-util.h"
Functions
int DecodeRaw (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p, const uint8_t *pkt, uint32_t len)
void DecodeRawRegisterTests (void)
Registers Raw unit tests.
Detailed Description
Author
William Metcalf willi.nosp@m.am.m.nosp@m.etcal.nosp@m.f@gm.nosp@m.ail.c.nosp@m.om
Decode RAW
Definition in file decode-raw.c.
Function Documentation
DecodeRaw()
int DecodeRaw (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint32_t len)
Definition at line 47 of file decode-raw.c.
References DecodeThreadVars_::counter_raw, DEBUG_VALIDATE_BUG_ON, DecodeIPV4(), DecodeIPV6(), dtv, ENGINE_SET_EVENT, ENGINE_SET_INVALID_EVENT, GET_PKT_DATA, GET_PKT_LEN, IP_GET_RAW_VER, IPRAW_INVALID_IPV, IPV4_HEADER_LEN, IPV4_PKT_TOO_SMALL, len, SCLogDebug, StatsIncr(), TM_ECODE_FAILED, TM_ECODE_OK, tv, and unlikely.
Referenced by ValidateLinkType().
DecodeRawRegisterTests()
void DecodeRawRegisterTests (void)
Registers Raw unit tests.
Todo:
More Raw tests
Definition at line 233 of file decode-raw.c.
References UtRegisterTest().