suricata: /Users/jlu/suricata/src/decode-null.c File Reference
decode-null.c File Reference
Packet decoding
#include "suricata-common.h"
#include "decode.h"
#include "decode-raw.h"
#include "decode-events.h"
#include "util-validate.h"
#include "util-unittest.h"
#include "util-debug.h"
#include "pkt-var.h"
#include "util-profiling.h"
#include "host.h"
#define HDR_SIZE 4
#define AF_INET6_BSD 24
#define AF_INET6_FREEBSD 28
#define AF_INET6_DARWIN 30
#define AF_INET6_LINUX 10
#define AF_INET6_SOLARIS 26
#define AF_INET6_WINSOCK 23
int DecodeNull (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p, const uint8_t *pkt, uint32_t len)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Decode linkype null: http://www.tcpdump.org/linktypes.html
Definition in file decode-null.c.
Macro Definition Documentation
AF_INET6_BSD
#define AF_INET6_BSD 24
Definition at line 49 of file decode-null.c.
AF_INET6_DARWIN
#define AF_INET6_DARWIN 30
Definition at line 51 of file decode-null.c.
AF_INET6_FREEBSD
#define AF_INET6_FREEBSD 28
Definition at line 50 of file decode-null.c.
AF_INET6_LINUX
#define AF_INET6_LINUX 10
Definition at line 52 of file decode-null.c.
AF_INET6_SOLARIS
#define AF_INET6_SOLARIS 26
Definition at line 53 of file decode-null.c.
AF_INET6_WINSOCK
#define AF_INET6_WINSOCK 23
Definition at line 54 of file decode-null.c.
HDR_SIZE
#define HDR_SIZE 4
Definition at line 47 of file decode-null.c.
Function Documentation
DecodeNull()
int DecodeNull (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint32_t len)
Definition at line 56 of file decode-null.c.
References AF_INET6_BSD, AF_INET6_DARWIN, AF_INET6_FREEBSD, AF_INET6_LINUX, AF_INET6_SOLARIS, AF_INET6_WINSOCK, DecodeThreadVars_::counter_null, DEBUG_VALIDATE_BUG_ON, DecodeIPV4(), DecodeIPV6(), dtv, ENGINE_SET_EVENT, ENGINE_SET_INVALID_EVENT, GET_PKT_DATA, GET_PKT_LEN, HDR_SIZE, len, LTNULL_PKT_TOO_SMALL, LTNULL_UNSUPPORTED_TYPE, SCLogDebug, StatsIncr(), TM_ECODE_FAILED, TM_ECODE_OK, tv, type, and unlikely.
Referenced by ValidateLinkType().