suricata: /Users/jlu/suricata/src/decode.h File Reference
decode.h File Reference
#include "suricata-common.h"
#include "suricata-plugin.h"
#include "threadvars.h"
#include "util-debug.h"
#include "decode-events.h"
#include "flow-worker.h"
#include "app-layer-protos.h"
#include "util-napatech.h"
#include "source-nflog.h"
#include "source-nfq.h"
#include "source-ipfw.h"
#include "source-pcap.h"
#include "source-af-packet.h"
#include "source-netmap.h"
#include "source-windivert.h"
#include "action-globals.h"
#include "decode-ethernet.h"
#include "decode-gre.h"
#include "decode-ppp.h"
#include "decode-pppoe.h"
#include "decode-ipv4.h"
#include "decode-ipv6.h"
#include "decode-icmpv4.h"
#include "decode-icmpv6.h"
#include "decode-tcp.h"
#include "decode-udp.h"
#include "decode-sctp.h"
#include "decode-esp.h"
#include "decode-vlan.h"
#include "decode-mpls.h"
Data Structures
struct Address_
struct PacketAlert_
struct PacketAlerts_
struct PacketEngineEvents_
struct PktVar_
struct PktProfilingTmmData_
Per TMM stats storage.
struct PktProfilingData_
struct PktProfilingDetectData_
struct PktProfilingAppData_
struct PktProfilingLoggerData_
struct PktProfilingPrefilterEngine_
struct PktProfilingPrefilterData_
struct PktProfiling_
Per pkt stats storage.
struct Packet_
struct DecodeThreadVars_
Structure to hold thread specific data for all decode modules.
struct CaptureStats_
Macros
#define COUNTERS
#define addr_data32 address.address_un_data32
#define addr_data16 address.address_un_data16
#define addr_data8 address.address_un_data8
#define addr_in6addr address.address_un_in6
#define COPY_ADDRESS(a, b)
#define SET_IPV4_SRC_ADDR(p, a)
#define SET_IPV4_DST_ADDR(p, a)
#define CLEAR_ADDR(a)
#define SET_IPV6_SRC_ADDR(p, a)
#define SET_IPV6_DST_ADDR(p, a)
#define SET_TCP_SRC_PORT(pkt, prt)
#define SET_TCP_DST_PORT(pkt, prt)
#define SET_UDP_SRC_PORT(pkt, prt)
#define SET_UDP_DST_PORT(pkt, prt)
#define SET_SCTP_SRC_PORT(pkt, prt)
#define SET_SCTP_DST_PORT(pkt, prt)
#define GET_IPV4_SRC_ADDR_U32(p) ((p)->src.addr_data32[0])
#define GET_IPV4_DST_ADDR_U32(p) ((p)->dst.addr_data32[0])
#define GET_IPV4_SRC_ADDR_PTR(p) ((p)->src.addr_data32)
#define GET_IPV4_DST_ADDR_PTR(p) ((p)->dst.addr_data32)
#define GET_IPV6_SRC_IN6ADDR(p) ((p)->src.addr_in6addr)
#define GET_IPV6_DST_IN6ADDR(p) ((p)->dst.addr_in6addr)
#define GET_IPV6_SRC_ADDR(p) ((p)->src.addr_data32)
#define GET_IPV6_DST_ADDR(p) ((p)->dst.addr_data32)
#define GET_TCP_SRC_PORT(p) ((p)->sp)
#define GET_TCP_DST_PORT(p) ((p)->dp)
#define GET_PKT_LEN(p) ((p)->pktlen)
#define GET_PKT_DATA(p) ((((p)->ext_pkt) == NULL) ? (uint8_t *)((p) + 1) : (p)->ext_pkt)
#define GET_PKT_DIRECT_DATA(p) (uint8_t *)((p) + 1)
#define GET_PKT_DIRECT_MAX_SIZE(p) (default_packet_size)
#define SET_PKT_LEN(p, len)
#define SET_PORT(v, p) ((p) = (v))
#define COPY_PORT(a, b) ((b) = (a))
#define CMP_ADDR(a1, a2)
#define CMP_PORT(p1, p2) ((p1) == (p2))
#define IP_GET_RAW_VER(pkt) ((((pkt)[0] & 0xf0) >> 4))
#define PKT_IS_IPV4(p) (((p)->ip4h != NULL))
#define PKT_IS_IPV6(p) (((p)->ip6h != NULL))
#define PKT_IS_TCP(p) (((p)->tcph != NULL))
#define PKT_IS_UDP(p) (((p)->udph != NULL))
#define PKT_IS_ICMPV4(p) (((p)->icmpv4h != NULL))
#define PKT_IS_ICMPV6(p) (((p)->icmpv6h != NULL))
#define PKT_IS_TOSERVER(p) (((p)->flowflags & FLOW_PKT_TOSERVER))
#define PKT_IS_TOCLIENT(p) (((p)->flowflags & FLOW_PKT_TOCLIENT))
#define IPH_IS_VALID(p) (PKT_IS_IPV4((p)) || PKT_IS_IPV6((p)))
#define IP_GET_IPPROTO(p)
#define PACKET_ALERT_FLAG_APPLY_ACTION_TO_FLOW 0x1
#define PACKET_ALERT_FLAG_STATE_MATCH 0x02
#define PACKET_ALERT_FLAG_STREAM_MATCH 0x04
#define PACKET_ALERT_FLAG_TX 0x08
#define PACKET_ALERT_RATE_FILTER_MODIFIED 0x10
#define PACKET_ALERT_FLAG_FRAME 0x20
#define PACKET_ALERT_MAX 15
#define PACKET_ENGINE_EVENT_MAX 15
#define tcpvars l4vars.tcpvars
#define icmpv4vars l4vars.icmpv4vars
#define icmpv6vars l4vars.icmpv6vars
#define DEFAULT_MTU 1500
#define MINIMUM_MTU 68
#define DEFAULT_PACKET_SIZE (DEFAULT_MTU + ETHERNET_HEADER_LEN)
#define MAX_PAYLOAD_SIZE (IPV6_HEADER_LEN + 65536 + 28)
#define SIZE_OF_PACKET (default_packet_size + sizeof(Packet))
#define PACKET_CLEAR_L4VARS(p)
#define PACKET_RESET_CHECKSUMS(p)
reset these to -1(indicates that the packet is fresh from the queue)
#define PACKET_FREE_EXTDATA(p)
#define PACKET_INITIALIZE(p)
Initialize a packet structure for use.
#define PACKET_RELEASE_REFS(p)
#define PACKET_REINIT(p)
Recycle a packet structure for reuse.
#define PACKET_RECYCLE(p)
#define PACKET_DESTRUCTOR(p)
Cleanup a packet so that we can free it. No memset needed..
#define PACKET_SET_ACTION(p, a) (p)->action = (a)
#define PACKET_ALERT(p) PACKET_SET_ACTION(p, ACTION_ALERT)
#define PACKET_ACCEPT(p) PACKET_SET_ACTION(p, ACTION_ACCEPT)
#define PACKET_TEST_ACTION(p, a) (p)->action &(a)
#define PACKET_UPDATE_ACTION(p, a) (p)->action |= (a)
#define TUNNEL_INCR_PKT_RTV_NOLOCK(p)
#define TUNNEL_INCR_PKT_TPR(p)
#define TUNNEL_PKT_RTV(p) ((p)->root ? (p)->root->tunnel_rtv_cnt : (p)->tunnel_rtv_cnt)
#define TUNNEL_PKT_TPR(p) ((p)->root ? (p)->root->tunnel_tpr_cnt : (p)->tunnel_tpr_cnt)
#define IS_TUNNEL_PKT(p) (((p)->flags & PKT_TUNNEL))
#define SET_TUNNEL_PKT(p) ((p)->flags |= PKT_TUNNEL)
#define UNSET_TUNNEL_PKT(p) ((p)->flags &= ~PKT_TUNNEL)
#define IS_TUNNEL_ROOT_PKT(p) (IS_TUNNEL_PKT(p) && (p)->root == NULL)
#define IS_TUNNEL_PKT_VERDICTED(p) (((p)->flags & PKT_TUNNEL_VERDICTED))
#define SET_TUNNEL_PKT_VERDICTED(p) ((p)->flags |= PKT_TUNNEL_VERDICTED)
#define ENGINE_SET_EVENT(p, e)
#define ENGINE_SET_INVALID_EVENT(p, e)
#define ENGINE_ISSET_EVENT(p, e)
#define LINKTYPE_NULL DLT_NULL
#define LINKTYPE_ETHERNET DLT_EN10MB
#define LINKTYPE_LINUX_SLL 113
#define LINKTYPE_PPP 9
#define LINKTYPE_RAW DLT_RAW
#define LINKTYPE_RAW2 101
#define LINKTYPE_IPV4 228
#define LINKTYPE_GRE_OVER_IP 778
#define LINKTYPE_CISCO_HDLC DLT_C_HDLC
#define PPP_OVER_GRE 11
#define VLAN_OVER_GRE 13
#define PKT_NOPACKET_INSPECTION BIT_U32(0)
#define PKT_NOPAYLOAD_INSPECTION BIT_U32(2)
#define PKT_ALLOC BIT_U32(3)
#define PKT_HAS_TAG BIT_U32(4)
#define PKT_STREAM_ADD BIT_U32(5)
#define PKT_STREAM_EST BIT_U32(6)
#define PKT_STREAM_EOF BIT_U32(7)
#define PKT_HAS_FLOW BIT_U32(8)
#define PKT_PSEUDO_STREAM_END BIT_U32(9)
#define PKT_STREAM_MODIFIED BIT_U32(10)
#define PKT_MARK_MODIFIED BIT_U32(11)
#define PKT_STREAM_NOPCAPLOG BIT_U32(12)
#define PKT_TUNNEL BIT_U32(13)
#define PKT_TUNNEL_VERDICTED BIT_U32(14)
#define PKT_IGNORE_CHECKSUM BIT_U32(15)
#define PKT_ZERO_COPY BIT_U32(16)
#define PKT_HOST_SRC_LOOKED_UP BIT_U32(17)
#define PKT_HOST_DST_LOOKED_UP BIT_U32(18)
#define PKT_IS_FRAGMENT BIT_U32(19)
#define PKT_IS_INVALID BIT_U32(20)
#define PKT_PROFILE BIT_U32(21)
#define PKT_WANTS_FLOW BIT_U32(22)
#define PKT_PROTO_DETECT_TS_DONE BIT_U32(23)
#define PKT_PROTO_DETECT_TC_DONE BIT_U32(24)
#define PKT_REBUILT_FRAGMENT BIT_U32(25)
#define PKT_DETECT_HAS_STREAMDATA BIT_U32(26)
#define PKT_PSEUDO_DETECTLOG_FLUSH BIT_U32(27)
#define PKT_STREAM_NO_EVENTS BIT_U32(28)
#define PKT_FIRST_ALERTS BIT_U32(29)
#define PKT_FIRST_TAG BIT_U32(30)
#define PKT_IS_PSEUDOPKT(p) ((p)->flags & (PKT_PSEUDO_STREAM_END|PKT_PSEUDO_DETECTLOG_FLUSH))
return 1 if the packet is a pseudo packet
#define PKT_SET_SRC(p, src_val) ((p)->pkt_src = src_val)
#define PKT_DEFAULT_MAX_DECODED_LAYERS 16
Typedefs
typedef struct AppLayerThreadCtx_ AppLayerThreadCtx
typedef struct AppLayerDecoderEvents_ AppLayerDecoderEvents
typedef struct Address_ Address
typedef uint16_t Port
typedef struct PacketAlert_ PacketAlert
typedef struct PacketAlerts_ PacketAlerts
typedef struct PacketEngineEvents_ PacketEngineEvents
typedef struct PktVar_ PktVar
typedef struct PktProfilingTmmData_ PktProfilingTmmData
Per TMM stats storage.
typedef struct PktProfilingData_ PktProfilingData
typedef struct PktProfilingDetectData_ PktProfilingDetectData
typedef struct PktProfilingAppData_ PktProfilingAppData
typedef struct PktProfilingLoggerData_ PktProfilingLoggerData
typedef struct PktProfilingPrefilterEngine_ PktProfilingPrefilterEngine
typedef struct PktProfilingPrefilterData_ PktProfilingPrefilterData
typedef struct PktProfiling_ PktProfiling
Per pkt stats storage.
typedef struct Packet_ Packet
typedef struct DecodeThreadVars_ DecodeThreadVars
Structure to hold thread specific data for all decode modules.
typedef struct CaptureStats_ CaptureStats
typedef int(* DecoderFunc) (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p, const uint8_t *pkt, uint32_t len)
Enumerations
enum ChecksumValidationMode {
CHECKSUM_VALIDATION_DISABLE , CHECKSUM_VALIDATION_ENABLE , CHECKSUM_VALIDATION_AUTO , CHECKSUM_VALIDATION_RXONLY ,
CHECKSUM_VALIDATION_KERNEL
}
enum PktSrcEnum {
PKT_SRC_WIRE = 1 , PKT_SRC_DECODER_GRE , PKT_SRC_DECODER_IPV4 , PKT_SRC_DECODER_IPV6 ,
PKT_SRC_DECODER_TEREDO , PKT_SRC_DEFRAG , PKT_SRC_FFR , PKT_SRC_STREAM_TCP_DETECTLOG_FLUSH ,
PKT_SRC_DECODER_VXLAN , PKT_SRC_DETECT_RELOAD_FLUSH , PKT_SRC_CAPTURE_TIMEOUT , PKT_SRC_DECODER_GENEVE
}
enum PacketDropReason {
PKT_DROP_REASON_NOT_SET = 0 , PKT_DROP_REASON_DECODE_ERROR , PKT_DROP_REASON_DEFRAG_ERROR , PKT_DROP_REASON_DEFRAG_MEMCAP ,
PKT_DROP_REASON_FLOW_MEMCAP , PKT_DROP_REASON_FLOW_DROP , PKT_DROP_REASON_APPLAYER_ERROR , PKT_DROP_REASON_APPLAYER_MEMCAP ,
PKT_DROP_REASON_RULES , PKT_DROP_REASON_RULES_THRESHOLD , PKT_DROP_REASON_STREAM_ERROR , PKT_DROP_REASON_STREAM_MEMCAP ,
PKT_DROP_REASON_STREAM_MIDSTREAM
}
enum DecodeTunnelProto {
DECODE_TUNNEL_ETHERNET , DECODE_TUNNEL_ERSPANII , DECODE_TUNNEL_ERSPANI , DECODE_TUNNEL_VLAN ,
DECODE_TUNNEL_IPV4 , DECODE_TUNNEL_IPV6 , DECODE_TUNNEL_IPV6_TEREDO , DECODE_TUNNEL_PPP ,
DECODE_TUNNEL_NSH , DECODE_TUNNEL_UNSET
}
Functions
void AppLayerDecoderEventsResetEvents (AppLayerDecoderEvents *events)
void AppLayerDecoderEventsFreeEvents (AppLayerDecoderEvents **events)
PacketAlert * PacketAlertCreate (void)
Initialize PacketAlerts with dynamic alerts array size.
void PacketAlertFree (PacketAlert *pa)
void CaptureStatsUpdate (ThreadVars *tv, CaptureStats *s, const Packet *p)
void CaptureStatsSetup (ThreadVars *tv, CaptureStats *s)
Packet * PacketTunnelPktSetup (ThreadVars *tv, DecodeThreadVars *dtv, Packet *parent, const uint8_t *pkt, uint32_t len, enum DecodeTunnelProto proto)
Setup a pseudo packet (tunnel)
Packet * PacketDefragPktSetup (Packet *parent, const uint8_t *pkt, uint32_t len, uint8_t proto)
Setup a pseudo packet (reassembled frags)
void PacketDefragPktSetupParent (Packet *parent)
inform defrag "parent" that a pseudo packet is now associated to it.
void DecodeRegisterPerfCounters (DecodeThreadVars *, ThreadVars *)
Packet * PacketGetFromQueueOrAlloc (void)
Get a packet. We try to get a packet from the packetpool first, but if that is empty we alloc a packet that is free'd again after processing.
Packet * PacketGetFromAlloc (void)
Get a malloced packet.
void PacketDecodeFinalize (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p)
Finalize decoding of a packet.
void PacketUpdateEngineEventCounters (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p)
void PacketFree (Packet *p)
Return a malloced packet.
void PacketFreeOrRelease (Packet *p)
Return a packet to where it was allocated.
int PacketCallocExtPkt (Packet *p, int datalen)
int PacketCopyData (Packet *p, const uint8_t *pktdata, uint32_t pktlen)
Copy data to Packet payload and set packet length.
int PacketSetData (Packet *p, const uint8_t *pktdata, uint32_t pktlen)
Set data for Packet and set length when zero copy is used.
int PacketCopyDataOffset (Packet *p, uint32_t offset, const uint8_t *data, uint32_t datalen)
Copy data to Packet payload at given offset.
const char * PktSrcToString (enum PktSrcEnum pkt_src)
void PacketBypassCallback (Packet *p)
void PacketSwap (Packet *p)
switch direction of a packet
DecodeThreadVars * DecodeThreadVarsAlloc (ThreadVars *)
Alloc and setup DecodeThreadVars.
void DecodeThreadVarsFree (ThreadVars *, DecodeThreadVars *)
void DecodeUpdatePacketCounters (ThreadVars *tv, const DecodeThreadVars *dtv, const Packet *p)
const char * PacketDropReasonToString (enum PacketDropReason r)
int DecodeEthernet (ThreadVars *, DecodeThreadVars *, Packet *, const uint8_t *, uint32_t)
int DecodeSll (ThreadVars *, DecodeThreadVars *, Packet *, const uint8_t *, uint32_t)
int DecodePPP (ThreadVars *, DecodeThreadVars *, Packet *, const uint8_t *, uint32_t)
int DecodePPPOESession (ThreadVars *, DecodeThreadVars *, Packet *, const uint8_t *, uint32_t)
Main decoding function for PPPOE Session packets.
int DecodePPPOEDiscovery (ThreadVars *, DecodeThreadVars *, Packet *, const uint8_t *, uint32_t)
Main decoding function for PPPOE Discovery packets.
int DecodeNull (ThreadVars *, DecodeThreadVars *, Packet *, const uint8_t *, uint32_t)
int DecodeRaw (ThreadVars *, DecodeThreadVars *, Packet *, const uint8_t *, uint32_t)
int DecodeIPV4 (ThreadVars *, DecodeThreadVars *, Packet *, const uint8_t *, uint16_t)
int DecodeIPV6 (ThreadVars *, DecodeThreadVars *, Packet *, const uint8_t *, uint16_t)
int DecodeICMPV4 (ThreadVars *, DecodeThreadVars *, Packet *, const uint8_t *, uint32_t)
Main ICMPv4 decoding function.
int DecodeICMPV6 (ThreadVars *, DecodeThreadVars *, Packet *, const uint8_t *, uint32_t)
Decode ICMPV6 packets and fill the Packet with the decoded info.
int DecodeTCP (ThreadVars *, DecodeThreadVars *, Packet *, const uint8_t *, uint16_t)
int DecodeUDP (ThreadVars *, DecodeThreadVars *, Packet *, const uint8_t *, uint16_t)
int DecodeSCTP (ThreadVars *, DecodeThreadVars *, Packet *, const uint8_t *, uint16_t)
int DecodeESP (ThreadVars *, DecodeThreadVars *, Packet *, const uint8_t *, uint16_t)
Function to decode IPSEC-ESP packets.
int DecodeGRE (ThreadVars *, DecodeThreadVars *, Packet *, const uint8_t *, uint32_t)
Function to decode GRE packets.
int DecodeVLAN (ThreadVars *, DecodeThreadVars *, Packet *, const uint8_t *, uint32_t)
int DecodeVNTag (ThreadVars *, DecodeThreadVars *, Packet *, const uint8_t *, uint32_t)
int DecodeIEEE8021ah (ThreadVars *, DecodeThreadVars *, Packet *, const uint8_t *, uint32_t)
int DecodeGeneve (ThreadVars *, DecodeThreadVars *, Packet *, const uint8_t *, uint32_t)
int DecodeVXLAN (ThreadVars *, DecodeThreadVars *, Packet *, const uint8_t *, uint32_t)
int DecodeMPLS (ThreadVars *, DecodeThreadVars *, Packet *, const uint8_t *, uint32_t)
int DecodeERSPAN (ThreadVars *, DecodeThreadVars *, Packet *, const uint8_t *, uint32_t)
ERSPAN Type II.
int DecodeERSPANTypeI (ThreadVars *, DecodeThreadVars *, Packet *, const uint8_t *, uint32_t)
ERSPAN Type I.
int DecodeCHDLC (ThreadVars *, DecodeThreadVars *, Packet *, const uint8_t *, uint32_t)
int DecodeTEMPLATE (ThreadVars *, DecodeThreadVars *, Packet *, const uint8_t *, uint32_t)
Function to decode TEMPLATE packets.
int DecodeNSH (ThreadVars *, DecodeThreadVars *, Packet *, const uint8_t *, uint32_t)
Function to decode NSH packets.
void DecodeIPV6FragHeader (Packet *p, const uint8_t *pkt, uint16_t hdrextlen, uint16_t plen, uint16_t prev_hdrextlen)
void AddressDebugPrint (Address *)
Debug print function for printing addresses.
void DecodeGlobalConfig (void)
void PacketAlertGetMaxConfig (void)
void DecodeUnregisterCounters (void)
Variables
uint16_t packet_alert_max
int g_default_mtu
uint32_t default_packet_size
uint8_t decoder_max_layers
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file decode.h.
Macro Definition Documentation
addr_data16
#define addr_data16 address.address_un_data16
Definition at line 124 of file decode.h.
addr_data32
#define addr_data32 address.address_un_data32
Definition at line 123 of file decode.h.
addr_data8
#define addr_data8 address.address_un_data8
Definition at line 125 of file decode.h.
addr_in6addr
#define addr_in6addr address.address_un_in6
Definition at line 126 of file decode.h.
CLEAR_ADDR
#define CLEAR_ADDR (a)
Value:
        do {       \
        (a)->family = 0;         \
        (a)->addr_data32[0] = 0; \
        (a)->addr_data32[1] = 0; \
        (a)->addr_data32[2] = 0; \
        (a)->addr_data32[3] = 0; \
    } while (0)
Definition at line 158 of file decode.h.
CMP_ADDR
#define CMP_ADDR (a1, a2)
Value:
    (((a1)->addr_data32[3] == (a2)->addr_data32[3] && \
      (a1)->addr_data32[2] == (a2)->addr_data32[2] && \
      (a1)->addr_data32[1] == (a2)->addr_data32[1] && \
      (a1)->addr_data32[0] == (a2)->addr_data32[0]))
Definition at line 241 of file decode.h.
CMP_PORT
#define CMP_PORT (p1, p2) ((p1) == (p2))
Definition at line 246 of file decode.h.
COPY_ADDRESS
#define COPY_ADDRESS (a, b)
Value:
        do {                    \
        (b)->family = (a)->family;                 \
        (b)->addr_data32[0] = (a)->addr_data32[0]; \
        (b)->addr_data32[1] = (a)->addr_data32[1]; \
        (b)->addr_data32[2] = (a)->addr_data32[2]; \
        (b)->addr_data32[3] = (a)->addr_data32[3]; \
    } while (0)
Definition at line 128 of file decode.h.
COPY_PORT
#define COPY_PORT (a, b) ((b) = (a))
Definition at line 239 of file decode.h.
COUNTERS
#define COUNTERS
Definition at line 28 of file decode.h.
DEFAULT_MTU
#define DEFAULT_MTU 1500
Definition at line 653 of file decode.h.
DEFAULT_PACKET_SIZE
#define DEFAULT_PACKET_SIZE (DEFAULT_MTU + ETHERNET_HEADER_LEN)
Definition at line 656 of file decode.h.
ENGINE_ISSET_EVENT
#define ENGINE_ISSET_EVENT (p, e)
Value:
    ({ \
    int r = 0; \
    uint8_t u; \
    for (u = 0; u < (p)->events.cnt; u++) { \
        if ((p)->events.events[u] == (e)) { \
            r = 1; \
            break; \
        } \
    } \
    r; \
})
Definition at line 1068 of file decode.h.
ENGINE_SET_EVENT
#define ENGINE_SET_EVENT (p, e)
Value:
    do { \
    SCLogDebug("p %p event %d", (p), e); \
    if ((p)->events.cnt < PACKET_ENGINE_EVENT_MAX) { \
        (p)->events.events[(p)->events.cnt] = e; \
        (p)->events.cnt++; \
    } \
} while(0)
Definition at line 1053 of file decode.h.
ENGINE_SET_INVALID_EVENT
#define ENGINE_SET_INVALID_EVENT (p, e)
Value:
    do { \
    p->flags |= PKT_IS_INVALID; \
    ENGINE_SET_EVENT(p, e); \
} while(0)
Definition at line 1061 of file decode.h.
GET_IPV4_DST_ADDR_PTR
#define GET_IPV4_DST_ADDR_PTR (p) ((p)->dst.addr_data32)
Definition at line 217 of file decode.h.
GET_IPV4_DST_ADDR_U32
#define GET_IPV4_DST_ADDR_U32 (p) ((p)->dst.addr_data32[0])
Definition at line 215 of file decode.h.
GET_IPV4_SRC_ADDR_PTR
#define GET_IPV4_SRC_ADDR_PTR (p) ((p)->src.addr_data32)
Definition at line 216 of file decode.h.
GET_IPV4_SRC_ADDR_U32
#define GET_IPV4_SRC_ADDR_U32 (p) ((p)->src.addr_data32[0])
Definition at line 214 of file decode.h.
GET_IPV6_DST_ADDR
#define GET_IPV6_DST_ADDR (p) ((p)->dst.addr_data32)
Definition at line 222 of file decode.h.
GET_IPV6_DST_IN6ADDR
#define GET_IPV6_DST_IN6ADDR (p) ((p)->dst.addr_in6addr)
Definition at line 220 of file decode.h.
GET_IPV6_SRC_ADDR
#define GET_IPV6_SRC_ADDR (p) ((p)->src.addr_data32)
Definition at line 221 of file decode.h.
GET_IPV6_SRC_IN6ADDR
#define GET_IPV6_SRC_IN6ADDR (p) ((p)->src.addr_in6addr)
Definition at line 219 of file decode.h.
GET_PKT_DATA
#define GET_PKT_DATA (p) ((((p)->ext_pkt) == NULL) ? (uint8_t *)((p) + 1) : (p)->ext_pkt)
Definition at line 227 of file decode.h.
GET_PKT_DIRECT_DATA
#define GET_PKT_DIRECT_DATA (p) (uint8_t *)((p) + 1)
Definition at line 228 of file decode.h.
GET_PKT_DIRECT_MAX_SIZE
#define GET_PKT_DIRECT_MAX_SIZE (p) (default_packet_size)
Definition at line 229 of file decode.h.
GET_PKT_LEN
#define GET_PKT_LEN (p) ((p)->pktlen)
Definition at line 226 of file decode.h.
GET_TCP_DST_PORT
#define GET_TCP_DST_PORT (p) ((p)->dp)
Definition at line 224 of file decode.h.
GET_TCP_SRC_PORT
#define GET_TCP_SRC_PORT (p) ((p)->sp)
Definition at line 223 of file decode.h.
icmpv4vars
#define icmpv4vars l4vars.icmpv4vars
Definition at line 551 of file decode.h.
icmpv6vars
#define icmpv6vars l4vars.icmpv6vars
Definition at line 552 of file decode.h.
IP_GET_IPPROTO
#define IP_GET_IPPROTO (p)
Value:
    (p->proto ? p->proto : \
    (PKT_IS_IPV4((p))? IPV4_GET_IPPROTO((p)) : (PKT_IS_IPV6((p))? IPV6_GET_L4PROTO((p)) : 0)))
Definition at line 265 of file decode.h.
IP_GET_RAW_VER
#define IP_GET_RAW_VER (pkt) ((((pkt)[0] & 0xf0) >> 4))
Definition at line 251 of file decode.h.
IPH_IS_VALID
#define IPH_IS_VALID (p) (PKT_IS_IPV4((p)) || PKT_IS_IPV6((p)))
Definition at line 262 of file decode.h.
IS_TUNNEL_PKT
#define IS_TUNNEL_PKT (p) (((p)->flags & PKT_TUNNEL))
Definition at line 963 of file decode.h.
IS_TUNNEL_PKT_VERDICTED
#define IS_TUNNEL_PKT_VERDICTED (p) (((p)->flags & PKT_TUNNEL_VERDICTED))
Definition at line 968 of file decode.h.
IS_TUNNEL_ROOT_PKT
#define IS_TUNNEL_ROOT_PKT (p) (IS_TUNNEL_PKT(p) && (p)->root == NULL)
Definition at line 966 of file decode.h.
LINKTYPE_CISCO_HDLC
#define LINKTYPE_CISCO_HDLC DLT_C_HDLC
Definition at line 1147 of file decode.h.
LINKTYPE_ETHERNET
#define LINKTYPE_ETHERNET DLT_EN10MB
Definition at line 1138 of file decode.h.
LINKTYPE_GRE_OVER_IP
#define LINKTYPE_GRE_OVER_IP 778
Definition at line 1146 of file decode.h.
LINKTYPE_IPV4
#define LINKTYPE_IPV4 228
Definition at line 1145 of file decode.h.
LINKTYPE_LINUX_SLL
#define LINKTYPE_LINUX_SLL 113
Definition at line 1139 of file decode.h.
LINKTYPE_NULL
#define LINKTYPE_NULL DLT_NULL
libpcap shows us the way to linktype codes
Todo:
we need more & maybe put them in a separate file?
Definition at line 1137 of file decode.h.
LINKTYPE_PPP
#define LINKTYPE_PPP 9
Definition at line 1140 of file decode.h.
LINKTYPE_RAW
#define LINKTYPE_RAW DLT_RAW
Definition at line 1141 of file decode.h.
LINKTYPE_RAW2
#define LINKTYPE_RAW2 101
Definition at line 1144 of file decode.h.
MAX_PAYLOAD_SIZE
#define MAX_PAYLOAD_SIZE (IPV6_HEADER_LEN + 65536 + 28)
Definition at line 658 of file decode.h.
MINIMUM_MTU
#define MINIMUM_MTU 68
ipv4 minimum: rfc791
Definition at line 654 of file decode.h.
PACKET_ACCEPT
#define PACKET_ACCEPT (p) PACKET_SET_ACTION(p, ACTION_ACCEPT)
Definition at line 914 of file decode.h.
PACKET_ALERT
#define PACKET_ALERT (p) PACKET_SET_ACTION(p, ACTION_ALERT)
Definition at line 912 of file decode.h.
PACKET_ALERT_FLAG_APPLY_ACTION_TO_FLOW
#define PACKET_ALERT_FLAG_APPLY_ACTION_TO_FLOW 0x1
Definition at line 281 of file decode.h.
PACKET_ALERT_FLAG_FRAME
#define PACKET_ALERT_FLAG_FRAME 0x20
alert is in a frame, frame_id set
Definition at line 291 of file decode.h.
PACKET_ALERT_FLAG_STATE_MATCH
#define PACKET_ALERT_FLAG_STATE_MATCH 0x02
alert was generated based on state
Definition at line 283 of file decode.h.
PACKET_ALERT_FLAG_STREAM_MATCH
#define PACKET_ALERT_FLAG_STREAM_MATCH 0x04
alert was generated based on stream
Definition at line 285 of file decode.h.
PACKET_ALERT_FLAG_TX
#define PACKET_ALERT_FLAG_TX 0x08
alert is in a tx, tx_id set
Definition at line 287 of file decode.h.
PACKET_ALERT_MAX
#define PACKET_ALERT_MAX 15
Definition at line 294 of file decode.h.
PACKET_ALERT_RATE_FILTER_MODIFIED
#define PACKET_ALERT_RATE_FILTER_MODIFIED 0x10
action was changed by rate_filter
Definition at line 289 of file decode.h.
PACKET_CLEAR_L4VARS
#define PACKET_CLEAR_L4VARS (p)
Value:
        do {                         \
        memset(&(p)->l4vars, 0x00, sizeof((p)->l4vars));    \
    } while (0)
Definition at line 758 of file decode.h.
PACKET_DESTRUCTOR
#define PACKET_DESTRUCTOR (p)
Value:
    do {                                                                                           \
        PACKET_RELEASE_REFS((p));                                                                  \
        if ((p)->pktvar != NULL) {                                                                 \
            PktVarFree((p)->pktvar);                                                               \
        }                                                                                          \
        PacketAlertFree((p)->alerts.alerts);                                                       \
        PACKET_FREE_EXTDATA((p));                                                                  \
        SCMutexDestroy(&(p)->tunnel_mutex);                                                        \
        AppLayerDecoderEventsFreeEvents(&(p)->app_layer_events);                                   \
        PACKET_PROFILING_RESET((p));                                                               \
    } while (0)
Cleanup a packet so that we can free it. No memset needed..
Definition at line 884 of file decode.h.
PACKET_ENGINE_EVENT_MAX
#define PACKET_ENGINE_EVENT_MAX 15
number of decoder events we support per packet. Power of 2 minus 1 for memory layout
Definition at line 312 of file decode.h.
PACKET_FREE_EXTDATA
#define PACKET_FREE_EXTDATA (p)
Value:
        do {                 \
        if ((p)->ext_pkt) {                         \
            if (!((p)->flags & PKT_ZERO_COPY)) {    \
                SCFree((p)->ext_pkt);               \
            }                                       \
            (p)->ext_pkt = NULL;                    \
        }                                           \
    } while(0)
Definition at line 771 of file decode.h.
PACKET_INITIALIZE
#define PACKET_INITIALIZE (p)
Value:
    {                                                                                              \
        SCMutexInit(&(p)->tunnel_mutex, NULL);                                                     \
        (p)->alerts.alerts = PacketAlertCreate();                                                  \
        PACKET_RESET_CHECKSUMS((p));                                                               \
        (p)->livedev = NULL;                                                                       \
    }
Initialize a packet structure for use.
Definition at line 783 of file decode.h.
PACKET_RECYCLE
#define PACKET_RECYCLE (p)
Value:
        do { \
        PACKET_RELEASE_REFS((p)); \
        PACKET_REINIT((p)); \
    } while (0)
Definition at line 876 of file decode.h.
PACKET_REINIT
#define PACKET_REINIT (p)
Recycle a packet structure for reuse.
Definition at line 800 of file decode.h.
PACKET_RELEASE_REFS
#define PACKET_RELEASE_REFS (p)
Value:
        do {              \
        FlowDeReference(&((p)->flow));          \
        HostDeReference(&((p)->host_src));      \
        HostDeReference(&((p)->host_dst));      \
    } while (0)
Definition at line 791 of file decode.h.
PACKET_RESET_CHECKSUMS
#define PACKET_RESET_CHECKSUMS (p)
Value:
        do { \
        (p)->level3_comp_csum = -1;   \
        (p)->level4_comp_csum = -1;   \
    } while (0)
reset these to -1(indicates that the packet is fresh from the queue)
Definition at line 765 of file decode.h.
PACKET_SET_ACTION
#define PACKET_SET_ACTION (p, a) (p)->action = (a)
Definition at line 901 of file decode.h.
PACKET_TEST_ACTION
#define PACKET_TEST_ACTION (p, a) (p)->action &(a)
Definition at line 916 of file decode.h.
PACKET_UPDATE_ACTION
#define PACKET_UPDATE_ACTION (p, a) (p)->action |= (a)
Definition at line 918 of file decode.h.
PKT_ALLOC
#define PKT_ALLOC BIT_U32(3)
Packet was alloc'd this run, needs to be freed
Definition at line 1160 of file decode.h.
PKT_DEFAULT_MAX_DECODED_LAYERS
#define PKT_DEFAULT_MAX_DECODED_LAYERS 16
Definition at line 1227 of file decode.h.
PKT_DETECT_HAS_STREAMDATA
#define PKT_DETECT_HAS_STREAMDATA BIT_U32(26)
Set by Detect() if raw stream data is available.
Definition at line 1209 of file decode.h.
PKT_FIRST_ALERTS
#define PKT_FIRST_ALERTS BIT_U32(29)
We had no alert on flow before this packet
Definition at line 1218 of file decode.h.
PKT_FIRST_TAG
#define PKT_FIRST_TAG BIT_U32(30)
Definition at line 1219 of file decode.h.
PKT_HAS_FLOW
#define PKT_HAS_FLOW BIT_U32(8)
Definition at line 1169 of file decode.h.
PKT_HAS_TAG
#define PKT_HAS_TAG BIT_U32(4)
Packet has matched a tag
Definition at line 1162 of file decode.h.
PKT_HOST_DST_LOOKED_UP
#define PKT_HOST_DST_LOOKED_UP BIT_U32(18)
Definition at line 1190 of file decode.h.
PKT_HOST_SRC_LOOKED_UP
#define PKT_HOST_SRC_LOOKED_UP BIT_U32(17)
Definition at line 1189 of file decode.h.
PKT_IGNORE_CHECKSUM
#define PKT_IGNORE_CHECKSUM BIT_U32(15)
Packet checksum is not computed (TX packet for example)
Definition at line 1185 of file decode.h.
PKT_IS_FRAGMENT
#define PKT_IS_FRAGMENT BIT_U32(19)
Packet is a fragment
Definition at line 1193 of file decode.h.
PKT_IS_ICMPV4
#define PKT_IS_ICMPV4 (p) (((p)->icmpv4h != NULL))
Definition at line 257 of file decode.h.
PKT_IS_ICMPV6
#define PKT_IS_ICMPV6 (p) (((p)->icmpv6h != NULL))
Definition at line 258 of file decode.h.
PKT_IS_INVALID
#define PKT_IS_INVALID BIT_U32(20)
Definition at line 1194 of file decode.h.
PKT_IS_IPV4
#define PKT_IS_IPV4 (p) (((p)->ip4h != NULL))
Definition at line 253 of file decode.h.
PKT_IS_IPV6
#define PKT_IS_IPV6 (p) (((p)->ip6h != NULL))
Definition at line 254 of file decode.h.
PKT_IS_PSEUDOPKT
#define PKT_IS_PSEUDOPKT (p) ((p)->flags & (PKT_PSEUDO_STREAM_END|PKT_PSEUDO_DETECTLOG_FLUSH))
return 1 if the packet is a pseudo packet
Definition at line 1222 of file decode.h.
PKT_IS_TCP
#define PKT_IS_TCP (p) (((p)->tcph != NULL))
Definition at line 255 of file decode.h.
PKT_IS_TOCLIENT
#define PKT_IS_TOCLIENT (p) (((p)->flowflags & FLOW_PKT_TOCLIENT))
Definition at line 260 of file decode.h.
PKT_IS_TOSERVER
#define PKT_IS_TOSERVER (p) (((p)->flowflags & FLOW_PKT_TOSERVER))
Definition at line 259 of file decode.h.
PKT_IS_UDP
#define PKT_IS_UDP (p) (((p)->udph != NULL))
Definition at line 256 of file decode.h.
PKT_MARK_MODIFIED
#define PKT_MARK_MODIFIED BIT_U32(11)
Packet mark is modified
Definition at line 1176 of file decode.h.
PKT_NOPACKET_INSPECTION
#define PKT_NOPACKET_INSPECTION BIT_U32(0)
Flag to indicate that packet header or contents should not be inspected
Definition at line 1154 of file decode.h.
PKT_NOPAYLOAD_INSPECTION
#define PKT_NOPAYLOAD_INSPECTION BIT_U32(2)
Flag to indicate that packet contents should not be inspected
Definition at line 1158 of file decode.h.
PKT_PROFILE
#define PKT_PROFILE BIT_U32(21)
Definition at line 1195 of file decode.h.
PKT_PROTO_DETECT_TC_DONE
#define PKT_PROTO_DETECT_TC_DONE BIT_U32(24)
Definition at line 1203 of file decode.h.
PKT_PROTO_DETECT_TS_DONE
#define PKT_PROTO_DETECT_TS_DONE BIT_U32(23)
protocol detection done
Definition at line 1202 of file decode.h.
PKT_PSEUDO_DETECTLOG_FLUSH
#define PKT_PSEUDO_DETECTLOG_FLUSH BIT_U32(27)
Detect/log flush for protocol upgrade
Definition at line 1211 of file decode.h.
PKT_PSEUDO_STREAM_END
#define PKT_PSEUDO_STREAM_END BIT_U32(9)
Pseudo packet to end the stream
Definition at line 1171 of file decode.h.
PKT_REBUILT_FRAGMENT
#define PKT_REBUILT_FRAGMENT BIT_U32(25)
Packet is rebuilt from \ fragments.
Definition at line 1207 of file decode.h.
PKT_SET_SRC
#define PKT_SET_SRC (p, src_val) ((p)->pkt_src = src_val)
Definition at line 1225 of file decode.h.
PKT_STREAM_ADD
#define PKT_STREAM_ADD BIT_U32(5)
Packet payload was added to reassembled stream
Definition at line 1164 of file decode.h.
PKT_STREAM_EOF
#define PKT_STREAM_EOF BIT_U32(7)
Stream is in eof state
Definition at line 1168 of file decode.h.
PKT_STREAM_EST
#define PKT_STREAM_EST BIT_U32(6)
Packet is part of established stream
Definition at line 1166 of file decode.h.
PKT_STREAM_MODIFIED
#define PKT_STREAM_MODIFIED BIT_U32(10)
Packet is modified by the stream engine, we need to recalc the csum and \ reinject/replace
Definition at line 1174 of file decode.h.
PKT_STREAM_NO_EVENTS
#define PKT_STREAM_NO_EVENTS BIT_U32(28)
Packet is part of stream in known bad condition (loss, wrong thread), so flag it for not setting stream events
Definition at line 1215 of file decode.h.
PKT_STREAM_NOPCAPLOG
#define PKT_STREAM_NOPCAPLOG BIT_U32(12)
Exclude packet from pcap logging as it's part of a stream that has reassembly \ depth reached.
Definition at line 1179 of file decode.h.
PKT_TUNNEL
#define PKT_TUNNEL BIT_U32(13)
Definition at line 1181 of file decode.h.
PKT_TUNNEL_VERDICTED
#define PKT_TUNNEL_VERDICTED BIT_U32(14)
Definition at line 1182 of file decode.h.
PKT_WANTS_FLOW
#define PKT_WANTS_FLOW BIT_U32(22)
indication by decoder that it feels the packet should be handled by flow engine: Packet::flow_hash will be set
Definition at line 1199 of file decode.h.
PKT_ZERO_COPY
#define PKT_ZERO_COPY BIT_U32(16)
Packet comes from zero copy (ext_pkt must not be freed)
Definition at line 1187 of file decode.h.
PPP_OVER_GRE
#define PPP_OVER_GRE 11
Definition at line 1148 of file decode.h.
SET_IPV4_DST_ADDR
#define SET_IPV4_DST_ADDR (p, a)
Value:
        do {                              \
        (a)->family = AF_INET;                                    \
        (a)->addr_data32[0] = (uint32_t)(p)->ip4h->s_ip_dst.s_addr; \
        (a)->addr_data32[1] = 0;                                  \
        (a)->addr_data32[2] = 0;                                  \
        (a)->addr_data32[3] = 0;                                  \
    } while (0)
Definition at line 149 of file decode.h.
SET_IPV4_SRC_ADDR
#define SET_IPV4_SRC_ADDR (p, a)
Value:
        do {                              \
        (a)->family = AF_INET;                                    \
        (a)->addr_data32[0] = (uint32_t)(p)->ip4h->s_ip_src.s_addr; \
        (a)->addr_data32[1] = 0;                                  \
        (a)->addr_data32[2] = 0;                                  \
        (a)->addr_data32[3] = 0;                                  \
    } while (0)
Definition at line 141 of file decode.h.
SET_IPV6_DST_ADDR
#define SET_IPV6_DST_ADDR (p, a)
Value:
        do {                    \
        (a)->family = AF_INET6;                         \
        (a)->addr_data32[0] = (p)->ip6h->s_ip6_dst[0];  \
        (a)->addr_data32[1] = (p)->ip6h->s_ip6_dst[1];  \
        (a)->addr_data32[2] = (p)->ip6h->s_ip6_dst[2];  \
        (a)->addr_data32[3] = (p)->ip6h->s_ip6_dst[3];  \
    } while (0)
Definition at line 176 of file decode.h.
SET_IPV6_SRC_ADDR
#define SET_IPV6_SRC_ADDR (p, a)
Value:
        do {                    \
        (a)->family = AF_INET6;                         \
        (a)->addr_data32[0] = (p)->ip6h->s_ip6_src[0];  \
        (a)->addr_data32[1] = (p)->ip6h->s_ip6_src[1];  \
        (a)->addr_data32[2] = (p)->ip6h->s_ip6_src[2];  \
        (a)->addr_data32[3] = (p)->ip6h->s_ip6_src[3];  \
    } while (0)
Definition at line 168 of file decode.h.
SET_PKT_LEN
#define SET_PKT_LEN (p, len)
Value:
    do { \
    (p)->pktlen = (len); \
    } while (0)
Definition at line 231 of file decode.h.
SET_PORT
#define SET_PORT (v, p) ((p) = (v))
Definition at line 238 of file decode.h.
SET_SCTP_DST_PORT
#define SET_SCTP_DST_PORT (pkt, prt)
Value:
        do {            \
        SET_PORT(SCTP_GET_DST_PORT((pkt)), *(prt)); \
    } while (0)
Definition at line 209 of file decode.h.
SET_SCTP_SRC_PORT
#define SET_SCTP_SRC_PORT (pkt, prt)
Value:
        do {            \
        SET_PORT(SCTP_GET_SRC_PORT((pkt)), *(prt)); \
    } while (0)
Definition at line 205 of file decode.h.
SET_TCP_DST_PORT
#define SET_TCP_DST_PORT (pkt, prt)
Value:
        do {            \
        SET_PORT(TCP_GET_DST_PORT((pkt)), *(prt)); \
    } while (0)
Definition at line 190 of file decode.h.
SET_TCP_SRC_PORT
#define SET_TCP_SRC_PORT (pkt, prt)
Value:
        do {            \
        SET_PORT(TCP_GET_SRC_PORT((pkt)), *(prt)); \
    } while (0)
Definition at line 186 of file decode.h.
SET_TUNNEL_PKT
#define SET_TUNNEL_PKT (p) ((p)->flags |= PKT_TUNNEL)
Definition at line 964 of file decode.h.
SET_TUNNEL_PKT_VERDICTED
#define SET_TUNNEL_PKT_VERDICTED (p) ((p)->flags |= PKT_TUNNEL_VERDICTED)
Definition at line 969 of file decode.h.
SET_UDP_DST_PORT
#define SET_UDP_DST_PORT (pkt, prt)
Value:
        do {            \
        SET_PORT(UDP_GET_DST_PORT((pkt)), *(prt)); \
    } while (0)
Definition at line 199 of file decode.h.
SET_UDP_SRC_PORT
#define SET_UDP_SRC_PORT (pkt, prt)
Value:
        do {            \
        SET_PORT(UDP_GET_SRC_PORT((pkt)), *(prt)); \
    } while (0)
Definition at line 196 of file decode.h.
SIZE_OF_PACKET
#define SIZE_OF_PACKET (default_packet_size + sizeof(Packet))
Definition at line 660 of file decode.h.
tcpvars
#define tcpvars l4vars.tcpvars
Definition at line 550 of file decode.h.
TUNNEL_INCR_PKT_RTV_NOLOCK
#define TUNNEL_INCR_PKT_RTV_NOLOCK (p)
Value:
        do {                                          \
        ((p)->root ? (p)->root->tunnel_rtv_cnt++ : (p)->tunnel_rtv_cnt++);          \
    } while (0)
Definition at line 950 of file decode.h.
TUNNEL_INCR_PKT_TPR
#define TUNNEL_INCR_PKT_TPR (p)
Value:
        do {                                                 \
        SCMutexLock((p)->root ? &(p)->root->tunnel_mutex : &(p)->tunnel_mutex);     \
        ((p)->root ? (p)->root->tunnel_tpr_cnt++ : (p)->tunnel_tpr_cnt++);          \
        SCMutexUnlock((p)->root ? &(p)->root->tunnel_mutex : &(p)->tunnel_mutex);   \
    } while (0)
Definition at line 954 of file decode.h.
TUNNEL_PKT_RTV
#define TUNNEL_PKT_RTV (p) ((p)->root ? (p)->root->tunnel_rtv_cnt : (p)->tunnel_rtv_cnt)
Definition at line 960 of file decode.h.
TUNNEL_PKT_TPR
#define TUNNEL_PKT_TPR (p) ((p)->root ? (p)->root->tunnel_tpr_cnt : (p)->tunnel_tpr_cnt)
Definition at line 961 of file decode.h.
UNSET_TUNNEL_PKT
#define UNSET_TUNNEL_PKT (p) ((p)->flags &= ~PKT_TUNNEL)
Definition at line 965 of file decode.h.
VLAN_OVER_GRE
#define VLAN_OVER_GRE 13
Definition at line 1149 of file decode.h.
Typedef Documentation
Address
typedef struct Address_ Address
AppLayerDecoderEvents
typedef struct AppLayerDecoderEvents_ AppLayerDecoderEvents
Definition at line 108 of file decode.h.
AppLayerThreadCtx
typedef struct AppLayerThreadCtx_ AppLayerThreadCtx
Definition at line 102 of file decode.h.
CaptureStats
typedef struct CaptureStats_ CaptureStats
DecoderFunc
typedef int(* DecoderFunc) (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p, const uint8_t *pkt, uint32_t len)
Definition at line 1047 of file decode.h.
DecodeThreadVars
typedef struct DecodeThreadVars_ DecodeThreadVars
Structure to hold thread specific data for all decode modules.
Packet
typedef struct Packet_ Packet
PacketAlert
typedef struct PacketAlert_ PacketAlert
PacketAlerts
typedef struct PacketAlerts_ PacketAlerts
PacketEngineEvents
typedef struct PacketEngineEvents_ PacketEngineEvents
data structure to store decoder, defrag and stream events
PktProfiling
typedef struct PktProfiling_ PktProfiling
Per pkt stats storage.
PktProfilingAppData
typedef struct PktProfilingAppData_ PktProfilingAppData
PktProfilingData
typedef struct PktProfilingData_ PktProfilingData
PktProfilingDetectData
typedef struct PktProfilingDetectData_ PktProfilingDetectData
PktProfilingLoggerData
typedef struct PktProfilingLoggerData_ PktProfilingLoggerData
PktProfilingPrefilterData
typedef struct PktProfilingPrefilterData_ PktProfilingPrefilterData
PktProfilingPrefilterEngine
typedef struct PktProfilingPrefilterEngine_ PktProfilingPrefilterEngine
PktProfilingTmmData
typedef struct PktProfilingTmmData_ PktProfilingTmmData
Per TMM stats storage.
PktVar
typedef struct PktVar_ PktVar
Port
typedef uint16_t Port
Definition at line 237 of file decode.h.
Enumeration Type Documentation
ChecksumValidationMode
enum ChecksumValidationMode
Enumerator
CHECKSUM_VALIDATION_DISABLE
CHECKSUM_VALIDATION_ENABLE
CHECKSUM_VALIDATION_AUTO
CHECKSUM_VALIDATION_RXONLY
CHECKSUM_VALIDATION_KERNEL
Definition at line 45 of file decode.h.
DecodeTunnelProto
enum DecodeTunnelProto
Enumerator
DECODE_TUNNEL_ETHERNET
DECODE_TUNNEL_ERSPANII
DECODE_TUNNEL_ERSPANI
DECODE_TUNNEL_VLAN
DECODE_TUNNEL_IPV4
DECODE_TUNNEL_IPV6
DECODE_TUNNEL_IPV6_TEREDO
separate protocol for stricter error handling
DECODE_TUNNEL_PPP
DECODE_TUNNEL_NSH
DECODE_TUNNEL_UNSET
Definition at line 971 of file decode.h.
PacketDropReason
enum PacketDropReason
Enumerator
PKT_DROP_REASON_NOT_SET
PKT_DROP_REASON_DECODE_ERROR
PKT_DROP_REASON_DEFRAG_ERROR
PKT_DROP_REASON_DEFRAG_MEMCAP
PKT_DROP_REASON_FLOW_MEMCAP
PKT_DROP_REASON_FLOW_DROP
PKT_DROP_REASON_APPLAYER_ERROR
PKT_DROP_REASON_APPLAYER_MEMCAP
PKT_DROP_REASON_RULES
PKT_DROP_REASON_RULES_THRESHOLD
detection_filter in action
PKT_DROP_REASON_STREAM_ERROR
PKT_DROP_REASON_STREAM_MEMCAP
PKT_DROP_REASON_STREAM_MIDSTREAM
Definition at line 398 of file decode.h.
PktSrcEnum
enum PktSrcEnum
Enumerator
PKT_SRC_WIRE
PKT_SRC_DECODER_GRE
PKT_SRC_DECODER_IPV4
PKT_SRC_DECODER_IPV6
PKT_SRC_DECODER_TEREDO
PKT_SRC_DEFRAG
PKT_SRC_FFR
PKT_SRC_STREAM_TCP_DETECTLOG_FLUSH
PKT_SRC_DECODER_VXLAN
PKT_SRC_DETECT_RELOAD_FLUSH
PKT_SRC_CAPTURE_TIMEOUT
PKT_SRC_DECODER_GENEVE
Definition at line 53 of file decode.h.
Function Documentation
AppLayerDecoderEventsFreeEvents()
void AppLayerDecoderEventsFreeEvents (AppLayerDecoderEvents ** events)
Definition at line 132 of file app-layer-events.c.
References SCFree.
Referenced by AppLayerParserStateFree().
AppLayerDecoderEventsResetEvents()
void AppLayerDecoderEventsResetEvents (AppLayerDecoderEvents * events)
Definition at line 123 of file app-layer-events.c.
References AppLayerDecoderEvents_::cnt, and AppLayerDecoderEvents_::event_last_logged.
DecodeCHDLC()
int DecodeCHDLC (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint32_t len)
Definition at line 42 of file decode-chdlc.c.
References CHDLC_HEADER_LEN, CHDLC_PKT_TOO_SMALL, DecodeThreadVars_::counter_chdlc, DEBUG_VALIDATE_BUG_ON, dtv, ENGINE_SET_INVALID_EVENT, len, StatsIncr(), TM_ECODE_FAILED, tv, and unlikely.
Referenced by ValidateLinkType().
DecodeERSPAN()
int DecodeERSPAN (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint32_t len)
ERSPAN Type II.
Definition at line 76 of file decode-erspan.c.
References DecodeThreadVars_::counter_erspan, DEBUG_VALIDATE_BUG_ON, dtv, ENGINE_SET_EVENT, ERSPAN_HEADER_TOO_SMALL, len, StatsIncr(), TM_ECODE_FAILED, and tv.
DecodeERSPANTypeI()
int DecodeERSPANTypeI (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint32_t len)
ERSPAN Type I.
Definition at line 65 of file decode-erspan.c.
References DecodeThreadVars_::counter_erspan, DecodeEthernet(), dtv, len, StatsIncr(), and tv.
DecodeESP()
int DecodeESP (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint16_t len)
Function to decode IPSEC-ESP packets.
Parameters
tv thread vars
dtv decoder thread vars
p packet
pkt raw packet data
len length in bytes of pkt array
Return values
TM_ECODE_OK or TM_ECODE_FAILED on serious error
Definition at line 64 of file decode-esp.c.
References DecodeThreadVars_::counter_esp, DEBUG_VALIDATE_BUG_ON, dtv, StatsIncr(), and tv.
DecodeEthernet()
int DecodeEthernet (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint32_t len)
Definition at line 42 of file decode-ethernet.c.
References DecodeThreadVars_::counter_eth, DEBUG_VALIDATE_BUG_ON, dtv, ENGINE_SET_INVALID_EVENT, ETHERNET_HEADER_LEN, ETHERNET_PKT_TOO_SMALL, len, StatsIncr(), TM_ECODE_FAILED, tv, and unlikely.
Referenced by DecodeErfDag(), DecodeERSPANTypeI(), DecodePfring(), NapatechDecode(), UTHBuildPacketArrayFromEth(), UTHBuildPacketFromEth(), and ValidateLinkType().
DecodeGeneve()
int DecodeGeneve (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint32_t len)
Parameters
pkt payload data directly above UDP header
len length in bytes of pkt
Definition at line 185 of file decode-geneve.c.
References DEBUG_VALIDATE_BUG_ON, DECODE_TUNNEL_UNSET, eth_type, and unlikely.
DecodeGRE()
int DecodeGRE (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint32_t len)
Function to decode GRE packets.
Todo:
We need to make sure this does not allow bypassing inspection. A server may just ignore these and continue processing the packet, but we will not look further into it.
Todo:
We need to make sure this does not allow bypassing inspection. A server may just ignore these and continue processing the packet, but we will not look further into it.
Definition at line 47 of file decode-gre.c.
References DecodeThreadVars_::counter_gre, DEBUG_VALIDATE_BUG_ON, dtv, ENGINE_SET_INVALID_EVENT, GRE_HDR_LEN, GRE_PKT_TOO_SMALL, len, StatsIncr(), TM_ECODE_FAILED, and tv.
DecodeICMPV4()
int DecodeICMPV4 (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint32_t len)
Main ICMPv4 decoding function.
DecodeICMPV4
Definition at line 156 of file decode-icmpv4.c.
References Packet_::code, DecodeThreadVars_::counter_icmpv4, dtv, ENGINE_SET_EVENT, ENGINE_SET_INVALID_EVENT, ICMPV4Vars_::hlen, Packet_::icmp_d, ICMP_DEST_UNREACH, ICMP_ECHOREPLY, Packet_::icmp_s, ICMPV4_HEADER_LEN, ICMPV4_HEADER_PKT_OFFSET, ICMPV4_PKT_TOO_SMALL, ICMPV4_UNKNOWN_CODE, ICMPv4GetCounterpart(), Packet_::icmpv4h, Packet_::icmpv4vars, ICMPV4ExtHdr_::id, ICMPV4Vars_::id, len, NR_ICMP_UNREACH, Packet_::proto, SCLogDebug, ICMPV4ExtHdr_::seq, ICMPV4Vars_::seq, StatsIncr(), TM_ECODE_FAILED, tv, Packet_::type, and unlikely.
DecodeICMPV6()
int DecodeICMPV6 (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint32_t len)
Decode ICMPV6 packets and fill the Packet with the decoded info.
Parameters
tv Pointer to the thread variables
dtv Pointer to the decode thread variables
p Pointer to the packet we are filling
pkt Pointer to the raw packet buffer
len the len of the rest of the packet not processed yet
Return values
void No return value
Definition at line 189 of file decode-icmpv6.c.
References ICMPV6Hdr_::code, Packet_::code, DecodeThreadVars_::counter_icmpv6, DEBUG_VALIDATE_BUG_ON, dtv, ENGINE_SET_EVENT, ENGINE_SET_INVALID_EVENT, ICMP6_DST_UNREACH, ICMP6_DST_UNREACH_REJECTROUTE, Packet_::icmp_d, Packet_::icmp_s, ICMPV6_GET_CODE, ICMPV6_GET_TYPE, ICMPV6_HEADER_LEN, ICMPV6_PKT_TOO_SMALL, ICMPV6_UNKNOWN_CODE, ICMPv6GetCounterpart(), Packet_::icmpv6h, len, Packet_::payload, Packet_::payload_len, Packet_::proto, SCLogDebug, StatsIncr(), TM_ECODE_FAILED, tv, ICMPV6Hdr_::type, Packet_::type, and unlikely.
DecodeIEEE8021ah()
int DecodeIEEE8021ah (ThreadVars * , DecodeThreadVars * , Packet * , const uint8_t * , uint32_t)
DecodeIPV4()
int DecodeIPV4 (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint16_t len)
Definition at line 528 of file decode-ipv4.c.
References DecodeThreadVars_::counter_ipv4, dtv, len, SCLogDebug, StatsIncr(), and tv.
Referenced by DecodeNull(), DecodePPPOESession(), and DecodeRaw().
DecodeIPV6()
int DecodeIPV6 (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint16_t len)
Definition at line 572 of file decode-ipv6.c.
References DecodeThreadVars_::counter_ipv6, dtv, StatsIncr(), and tv.
Referenced by DecodeNull(), DecodePPPOESession(), and DecodeRaw().
DecodeIPV6FragHeader()
void DecodeIPV6FragHeader (Packet * p, const uint8_t * pkt, uint16_t hdrextlen, uint16_t plen, uint16_t prev_hdrextlen)
Definition at line 101 of file decode-ipv6.c.
References IPV6ExtHdrs_::fh_data_len, IPV6ExtHdrs_::fh_data_offset, IPV6ExtHdrs_::fh_header_offset, IPV6ExtHdrs_::fh_id, IPV6ExtHdrs_::fh_more_frags_set, IPV6ExtHdrs_::fh_nh, IPV6ExtHdrs_::fh_offset, IPV6ExtHdrs_::fh_prev_hdr_offset, GET_PKT_DATA, Packet_::ip6eh, SCLogDebug, and SCNtohl.
DecodeMPLS()
int DecodeMPLS (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint32_t len)
Definition at line 49 of file decode-mpls.c.
References DecodeThreadVars_::counter_mpls, DEBUG_VALIDATE_BUG_ON, dtv, StatsIncr(), and tv.
DecodeNSH()
int DecodeNSH (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint32_t len)
Function to decode NSH packets.
Definition at line 46 of file decode-nsh.c.
References DecodeThreadVars_::counter_nsh, DEBUG_VALIDATE_BUG_ON, dtv, ENGINE_SET_INVALID_EVENT, len, NSH_HEADER_TOO_SMALL, StatsIncr(), TM_ECODE_FAILED, and tv.
DecodeNull()
int DecodeNull (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint32_t len)
Definition at line 56 of file decode-null.c.
References AF_INET6_BSD, AF_INET6_DARWIN, AF_INET6_FREEBSD, AF_INET6_LINUX, AF_INET6_SOLARIS, AF_INET6_WINSOCK, DecodeThreadVars_::counter_null, DEBUG_VALIDATE_BUG_ON, DecodeIPV4(), DecodeIPV6(), dtv, ENGINE_SET_EVENT, ENGINE_SET_INVALID_EVENT, GET_PKT_DATA, GET_PKT_LEN, HDR_SIZE, len, LTNULL_PKT_TOO_SMALL, LTNULL_UNSUPPORTED_TYPE, SCLogDebug, StatsIncr(), TM_ECODE_FAILED, TM_ECODE_OK, tv, type, and unlikely.
Referenced by ValidateLinkType().
DecodePPP()
int DecodePPP (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint32_t len)
Definition at line 44 of file decode-ppp.c.
References DecodeThreadVars_::counter_ppp, DEBUG_VALIDATE_BUG_ON, dtv, ENGINE_SET_INVALID_EVENT, len, PPP_HEADER_LEN, PPP_PKT_TOO_SMALL, StatsIncr(), TM_ECODE_FAILED, tv, and unlikely.
Referenced by ValidateLinkType().
DecodePPPOEDiscovery()
int DecodePPPOEDiscovery (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint32_t len)
Main decoding function for PPPOE Discovery packets.
Definition at line 50 of file decode-pppoe.c.
References DecodeThreadVars_::counter_pppoe, DEBUG_VALIDATE_BUG_ON, dtv, ENGINE_SET_INVALID_EVENT, len, PPPOE_CODE_PADI, PPPOE_CODE_PADO, PPPOE_CODE_PADR, PPPOE_CODE_PADS, PPPOE_CODE_PADT, PPPOE_DISCOVERY_HEADER_MIN_LEN, pppoe_length, PPPOE_MALFORMED_TAGS, PPPOE_PKT_TOO_SMALL, PPPOE_WRONG_CODE, Packet_::pppoedh, SCLogDebug, SCNtohs, StatsIncr(), TM_ECODE_FAILED, TM_ECODE_OK, and tv.
DecodePPPOESession()
int DecodePPPOESession (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint32_t len)
Main decoding function for PPPOE Session packets.
Definition at line 130 of file decode-pppoe.c.
References DecodeThreadVars_::counter_pppoe, DEBUG_VALIDATE_BUG_ON, DecodeIPV4(), DecodeIPV6(), dtv, ENGINE_SET_EVENT, ENGINE_SET_INVALID_EVENT, IPV4_GET_RAW_VER, IPV4_HEADER_LEN, IPV6_HEADER_LEN, len, PPP_APPLE, PPP_APPLECP, PPP_BRPDU, PPP_CHAP, PPP_DECNET, PPP_DECNETCP, PPP_HELLO, PPP_IP, PPP_IPCP, PPP_IPV6, PPP_IPV6CP, PPP_IPX, PPP_IPXCP, PPP_LCP, PPP_LQM, PPP_LUXCOM, PPP_MPLS_MCAST, PPP_MPLS_UCAST, PPP_MPLSCP, PPP_NS, PPP_NSCP, PPP_OSI, PPP_OSICP, PPP_PAP, PPP_SNS, PPP_STII, PPP_STIICP, PPP_UNSUP_PROTO, PPP_VINES, PPP_VINESCP, PPP_VJ_COMP, PPP_VJ_UCOMP, PPP_WRONG_TYPE, PPPIPV4_PKT_TOO_SMALL, PPPIPV6_PKT_TOO_SMALL, PPPOESessionHdr_::pppoe_code, PPPOESessionHdr_::pppoe_length, PPPOE_PKT_TOO_SMALL, PPPOE_SESSION_GET_TYPE, PPPOE_SESSION_GET_VERSION, PPPOE_SESSION_HEADER_MIN_LEN, Packet_::pppoesh, PPPVJU_PKT_TOO_SMALL, PPPOESessionHdr_::protocol, SCLogDebug, SCNtohs, PPPOESessionHdr_::session_id, StatsIncr(), TM_ECODE_FAILED, TM_ECODE_OK, tv, and unlikely.
DecodeRaw()
int DecodeRaw (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint32_t len)
Definition at line 47 of file decode-raw.c.
References DecodeThreadVars_::counter_raw, DEBUG_VALIDATE_BUG_ON, DecodeIPV4(), DecodeIPV6(), dtv, ENGINE_SET_EVENT, ENGINE_SET_INVALID_EVENT, GET_PKT_DATA, GET_PKT_LEN, IP_GET_RAW_VER, IPRAW_INVALID_IPV, IPV4_HEADER_LEN, IPV4_PKT_TOO_SMALL, len, SCLogDebug, StatsIncr(), TM_ECODE_FAILED, TM_ECODE_OK, tv, and unlikely.
Referenced by ValidateLinkType().
DecodeSCTP()
int DecodeSCTP (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint16_t len)
Definition at line 66 of file decode-sctp.c.
References DecodeThreadVars_::counter_sctp, dtv, StatsIncr(), tv, and unlikely.
DecodeSll()
int DecodeSll (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint32_t len)
Definition at line 41 of file decode-sll.c.
References DecodeThreadVars_::counter_sll, DEBUG_VALIDATE_BUG_ON, dtv, ENGINE_SET_INVALID_EVENT, len, SLL_HEADER_LEN, SLL_PKT_TOO_SMALL, StatsIncr(), TM_ECODE_FAILED, tv, and unlikely.
Referenced by ValidateLinkType().
DecodeTCP()
int DecodeTCP (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint16_t len)
Definition at line 251 of file decode-tcp.c.
References DecodeThreadVars_::counter_tcp, dtv, StatsIncr(), tv, and unlikely.
DecodeTEMPLATE()
int DecodeTEMPLATE (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint32_t len)
Function to decode TEMPLATE packets.
Parameters
tv thread vars
dtv decoder thread vars
p packet
pkt raw packet data
len length in bytes of pkt array
Return values
TM_ECODE_OK or TM_ECODE_FAILED on serious error
Definition at line 51 of file decode-template.c.
References DEBUG_VALIDATE_BUG_ON, len, and TM_ECODE_FAILED.
DecodeUDP()
int DecodeUDP (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint16_t len)
Definition at line 75 of file decode-udp.c.
References DecodeThreadVars_::counter_udp, dtv, StatsIncr(), tv, and unlikely.
DecodeVLAN()
int DecodeVLAN (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint32_t len)
Definition at line 60 of file decode-vlan.c.
References DecodeThreadVars_::counter_vlan, DecodeThreadVars_::counter_vlan_qinq, DEBUG_VALIDATE_BUG_ON, dtv, ENGINE_SET_INVALID_EVENT, len, proto, StatsIncr(), TM_ECODE_FAILED, tv, VLAN_HEADER_LEN, VLAN_HEADER_TOO_SMALL, and Packet_::vlan_idx.
DecodeVNTag()
int DecodeVNTag (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint32_t len)
Definition at line 58 of file decode-vntag.c.
References DecodeThreadVars_::counter_vntag, DEBUG_VALIDATE_BUG_ON, dtv, ENGINE_SET_INVALID_EVENT, len, StatsIncr(), TM_ECODE_FAILED, tv, VNTAG_HEADER_LEN, and VNTAG_HEADER_TOO_SMALL.
DecodeVXLAN()
int DecodeVXLAN (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint32_t len)
Parameters
pkt payload data directly above UDP header
len length in bytes of pkt
Definition at line 126 of file decode-vxlan.c.
References DEBUG_VALIDATE_BUG_ON, and unlikely.
Variable Documentation
g_default_mtu
int g_default_mtu extern
highest mtu of the interfaces we monitor
Definition at line 231 of file suricata.c.