suricata: /Users/jlu/suricata/src/decode-icmpv6.c File Reference
decode-icmpv6.c File Reference
Packet decoding
#include "suricata-common.h"
#include "decode-icmpv6.h"
#include "decode.h"
#include "decode-tcp.h"
#include "decode-sctp.h"
#include "decode-udp.h"
#include "decode-events.h"
#include "util-unittest.h"
#include "flow.h"
#include "util-debug.h"
#include "util-print.h"
#include "util-validate.h"
#include "pkt-var.h"
#include "util-profiling.h"
#include "host.h"
Macros
#define CASE_CODE(t, r) case (t): return r; case (r): return t;
Functions
int ICMPv6GetCounterpart (uint8_t type)
int DecodeICMPV6 (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p, const uint8_t *pkt, uint32_t len)
Decode ICMPV6 packets and fill the Packet with the decoded info.
void DecodeICMPV6RegisterTests (void)
Registers ICMPV6 unit tests.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Decode ICMPv6
Definition in file decode-icmpv6.c.
Macro Definition Documentation
CASE_CODE
#define CASE_CODE (t, r) case (t): return r; case (r): return t;
Function Documentation
DecodeICMPV6()
int DecodeICMPV6 (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint32_t len)
Decode ICMPV6 packets and fill the Packet with the decoded info.
Parameters
tv Pointer to the thread variables
dtv Pointer to the decode thread variables
p Pointer to the packet we are filling
pkt Pointer to the raw packet buffer
len the len of the rest of the packet not processed yet
Return values
void No return value
Definition at line 189 of file decode-icmpv6.c.
References ICMPV6Hdr_::code, Packet_::code, DecodeThreadVars_::counter_icmpv6, DEBUG_VALIDATE_BUG_ON, dtv, ENGINE_SET_EVENT, ENGINE_SET_INVALID_EVENT, ICMP6_DST_UNREACH, ICMP6_DST_UNREACH_REJECTROUTE, Packet_::icmp_d, Packet_::icmp_s, ICMPV6_GET_CODE, ICMPV6_GET_TYPE, ICMPV6_HEADER_LEN, ICMPV6_PKT_TOO_SMALL, ICMPV6_UNKNOWN_CODE, ICMPv6GetCounterpart(), Packet_::icmpv6h, len, Packet_::payload, Packet_::payload_len, Packet_::proto, SCLogDebug, StatsIncr(), TM_ECODE_FAILED, tv, ICMPV6Hdr_::type, Packet_::type, and unlikely.
DecodeICMPV6RegisterTests()
void DecodeICMPV6RegisterTests (void)
Registers ICMPV6 unit tests.
Todo:
More ICMPv6 tests
Definition at line 1563 of file decode-icmpv6.c.
References UtRegisterTest().
ICMPv6GetCounterpart()
int ICMPv6GetCounterpart (uint8_t type)
Return values
type counterpart type or -1
Definition at line 157 of file decode-icmpv6.c.
References CASE_CODE, CERT_PATH_ADVERT, CERT_PATH_SOLICIT, DUPL_ADDR_CONFIRM, DUPL_ADDR_REQUEST, HOME_AGENT_AD_REPLY, HOME_AGENT_AD_REQUEST, ICMP6_ECHO_REPLY, ICMP6_ECHO_REQUEST, ICMP6_NI_QUERY, ICMP6_NI_REPLY, MC_ROUTER_ADVERT, MC_ROUTER_SOLICIT, MLD_LISTENER_QUERY, MLD_LISTENER_REPORT, MOBILE_PREFIX_ADVERT, MOBILE_PREFIX_SOLICIT, ND_NEIGHBOR_ADVERT, ND_NEIGHBOR_SOLICIT, ND_ROUTER_ADVERT, ND_ROUTER_SOLICIT, and type.
Referenced by DecodeICMPV6().