suricata: /Users/jlu/suricata/src/decode-chdlc.c File Reference
decode-chdlc.c File Reference
Packet decoding
#include "suricata-common.h"
#include "decode.h"
#include "decode-chdlc.h"
#include "decode-events.h"
#include "util-validate.h"
#include "util-unittest.h"
#include "util-debug.h"
Functions
int DecodeCHDLC (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p, const uint8_t *pkt, uint32_t len)
void DecodeCHDLCRegisterTests (void)
Registers Ethernet unit tests.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Decode Cisco HDLC
Definition in file decode-chdlc.c.
Function Documentation
DecodeCHDLC()
int DecodeCHDLC (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint32_t len)
Definition at line 42 of file decode-chdlc.c.
References CHDLC_HEADER_LEN, CHDLC_PKT_TOO_SMALL, DecodeThreadVars_::counter_chdlc, DEBUG_VALIDATE_BUG_ON, dtv, ENGINE_SET_INVALID_EVENT, len, StatsIncr(), TM_ECODE_FAILED, tv, and unlikely.
Referenced by ValidateLinkType().
DecodeCHDLCRegisterTests()
void DecodeCHDLCRegisterTests (void)
Registers Ethernet unit tests.
Todo:
More Ethernet tests
Definition at line 105 of file decode-chdlc.c.
References UtRegisterTest().