suricata: /Users/jlu/suricata/src/decode-geneve.h File Reference
decode-geneve.h File Reference
Functions
void DecodeGeneveRegisterTests (void)
void DecodeGeneveConfig (void)
bool DecodeGeneveEnabledForPort (const uint16_t sp, const uint16_t dp)
Detailed Description
Author
Ali Jad Khalil jadkh.nosp@m.al@a.nosp@m.mazon.nosp@m..com
Geneve decoder.
Definition in file decode-geneve.h.
Function Documentation
DecodeGeneveConfig()
void DecodeGeneveConfig (void)
Definition at line 128 of file decode-geneve.c.
References ConfGetBool().
Referenced by DecodeGlobalConfig().
DecodeGeneveEnabledForPort()
bool DecodeGeneveEnabledForPort (const uint16_t sp, const uint16_t dp)
Definition at line 90 of file decode-geneve.c.
References SCLogDebug.
DecodeGeneveRegisterTests()
void DecodeGeneveRegisterTests (void)
Definition at line 495 of file decode-geneve.c.
References UtRegisterTest().