suricata: /Users/jlu/suricata/src/decode-vxlan.h File Reference
decode-vxlan.h File Reference
Functions
void DecodeVXLANRegisterTests (void)
void DecodeVXLANConfig (void)
bool DecodeVXLANEnabledForPort (const uint16_t sp, const uint16_t dp)
Detailed Description
Author
Henrik Kramshoej hlk@k.nosp@m.rams.nosp@m.e.org
VXLAN decoder.
Definition in file decode-vxlan.h.
Function Documentation
DecodeVXLANConfig()
void DecodeVXLANConfig (void)
Definition at line 102 of file decode-vxlan.c.
References ConfGetBool().
Referenced by DecodeGlobalConfig().
DecodeVXLANEnabledForPort()
bool DecodeVXLANEnabledForPort (const uint16_t sp, const uint16_t dp)
Definition at line 65 of file decode-vxlan.c.
References SCLogDebug.
DecodeVXLANRegisterTests()
void DecodeVXLANRegisterTests (void)
Definition at line 280 of file decode-vxlan.c.
References UtRegisterTest().