suricata: /Users/jlu/suricata/src/decode-icmpv4.c File Reference
decode-icmpv4.c File Reference
Packet decoding
#include "suricata-common.h"
#include "decode.h"
#include "decode-events.h"
#include "decode-ipv4.h"
#include "decode-icmpv4.h"
#include "flow.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-debug.h"
#include "util-print.h"
#include "util-validate.h"
Macros
#define CASE_CODE(t, r) case (t): return r; case (r): return t;
Functions
int DecodeICMPV4 (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p, const uint8_t *pkt, uint32_t len)
Main ICMPv4 decoding function.
int ICMPv4GetCounterpart (uint8_t type)
void DecodeICMPV4RegisterTests (void)
Registers ICMPV4 unit test.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Decode ICMPv4
Definition in file decode-icmpv4.c.
Macro Definition Documentation
CASE_CODE
#define CASE_CODE (t, r) case (t): return r; case (r): return t;
Function Documentation
DecodeICMPV4()
int DecodeICMPV4 (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint32_t len)
Main ICMPv4 decoding function.
DecodeICMPV4
Definition at line 156 of file decode-icmpv4.c.
References Packet_::code, DecodeThreadVars_::counter_icmpv4, dtv, ENGINE_SET_EVENT, ENGINE_SET_INVALID_EVENT, ICMPV4Vars_::hlen, Packet_::icmp_d, ICMP_DEST_UNREACH, ICMP_ECHOREPLY, Packet_::icmp_s, ICMPV4_HEADER_LEN, ICMPV4_HEADER_PKT_OFFSET, ICMPV4_PKT_TOO_SMALL, ICMPV4_UNKNOWN_CODE, ICMPv4GetCounterpart(), Packet_::icmpv4h, Packet_::icmpv4vars, ICMPV4ExtHdr_::id, ICMPV4Vars_::id, len, NR_ICMP_UNREACH, Packet_::proto, SCLogDebug, ICMPV4ExtHdr_::seq, ICMPV4Vars_::seq, StatsIncr(), TM_ECODE_FAILED, tv, Packet_::type, and unlikely.
DecodeICMPV4RegisterTests()
void DecodeICMPV4RegisterTests (void)
Registers ICMPV4 unit test.
Definition at line 827 of file decode-icmpv4.c.
References UtRegisterTest().
ICMPv4GetCounterpart()
int ICMPv4GetCounterpart (uint8_t type)
Return values
type counterpart type or -1
Definition at line 360 of file decode-icmpv4.c.
References CASE_CODE, ICMP_ADDRESS, ICMP_ADDRESSREPLY, ICMP_ECHO, ICMP_ECHOREPLY, ICMP_INFO_REPLY, ICMP_INFO_REQUEST, ICMP_ROUTERADVERT, ICMP_ROUTERSOLICIT, ICMP_TIMESTAMP, ICMP_TIMESTAMPREPLY, and type.
Referenced by DecodeICMPV4().