suricata: /Users/jlu/suricata/src/decode-erspan.c File Reference
decode-erspan.c File Reference
Packet decoding
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "decode-events.h"
#include "decode-erspan.h"
#include "util-validate.h"
#include "util-unittest.h"
#include "util-debug.h"
Functions
void DecodeERSPANConfig (void)
Functions to decode ERSPAN Type I and II packets.
int DecodeERSPANTypeI (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p, const uint8_t *pkt, uint32_t len)
ERSPAN Type I.
int DecodeERSPAN (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p, const uint8_t *pkt, uint32_t len)
ERSPAN Type II.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Decodes ERSPAN Types I and II
Definition in file decode-erspan.c.
Function Documentation
DecodeERSPAN()
int DecodeERSPAN (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint32_t len)
ERSPAN Type II.
Definition at line 76 of file decode-erspan.c.
References DecodeThreadVars_::counter_erspan, DEBUG_VALIDATE_BUG_ON, dtv, ENGINE_SET_EVENT, ERSPAN_HEADER_TOO_SMALL, len, StatsIncr(), TM_ECODE_FAILED, and tv.
DecodeERSPANConfig()
void DecodeERSPANConfig (void)
Functions to decode ERSPAN Type I and II packets.
Definition at line 52 of file decode-erspan.c.
References ConfGetBool(), SC_WARN_ERSPAN_CONFIG, and SCLogWarning.
Referenced by DecodeGlobalConfig().
DecodeERSPANTypeI()
int DecodeERSPANTypeI (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint32_t len)
ERSPAN Type I.
Definition at line 65 of file decode-erspan.c.
References DecodeThreadVars_::counter_erspan, DecodeEthernet(), dtv, len, StatsIncr(), and tv.