suricata: /Users/jlu/suricata/src/decode-ppp.c File Reference
decode-ppp.c File Reference
Packet decoding
#include "suricata-common.h"
#include "decode.h"
#include "decode-ppp.h"
#include "decode-events.h"
#include "flow.h"
#include "util-validate.h"
#include "util-unittest.h"
#include "util-debug.h"
Functions
int DecodePPP (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p, const uint8_t *pkt, uint32_t len)
void DecodePPPRegisterTests (void)
Detailed Description
Author
Breno Silva Pinto breno.nosp@m..sil.nosp@m.va@gm.nosp@m.ail..nosp@m.com
Decode PPP
Definition in file decode-ppp.c.
Function Documentation
DecodePPP()
int DecodePPP (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p, const uint8_t * pkt, uint32_t len)
Definition at line 44 of file decode-ppp.c.
References DecodeThreadVars_::counter_ppp, DEBUG_VALIDATE_BUG_ON, dtv, ENGINE_SET_INVALID_EVENT, len, PPP_HEADER_LEN, PPP_PKT_TOO_SMALL, StatsIncr(), TM_ECODE_FAILED, tv, and unlikely.
Referenced by ValidateLinkType().
DecodePPPRegisterTests()
void DecodePPPRegisterTests (void)
Definition at line 316 of file decode-ppp.c.
References UtRegisterTest().