suricata: /Users/jlu/suricata/src/defrag-hash.c File Reference
defrag-hash.c File Reference
#include "suricata-common.h"
#include "conf.h"
#include "defrag-hash.h"
#include "defrag-queue.h"
#include "defrag-config.h"
#include "util-random.h"
#include "util-byte.h"
#include "util-misc.h"
#include "util-hash-lookup3.h"
Data Structures
struct DefragHashKey4_
struct DefragHashKey6_
Macros
#define DefragTrackerIncrUsecnt(dt) SC_ATOMIC_ADD((dt)->use_cnt, 1)
#define DefragTrackerDecrUsecnt(dt) SC_ATOMIC_SUB((dt)->use_cnt, 1)
#define DEFRAG_DEFAULT_HASHSIZE 4096
#define DEFRAG_DEFAULT_MEMCAP 16777216
#define DEFRAG_DEFAULT_PREALLOC 1000
#define CMP_DEFRAGTRACKER(d1, d2, id)
Typedefs
typedef struct DefragHashKey4_ DefragHashKey4
typedef struct DefragHashKey6_ DefragHashKey6
Functions
SC_ATOMIC_DECLARE (uint64_t, defrag_memuse)
SC_ATOMIC_DECLARE (unsigned int, defragtracker_counter)
SC_ATOMIC_DECLARE (unsigned int, defragtracker_prune_idx)
int DefragTrackerSetMemcap (uint64_t size)
Update memcap value.
uint64_t DefragTrackerGetMemcap (void)
Return memcap value.
uint64_t DefragTrackerGetMemuse (void)
Return memuse value.
uint32_t DefragTrackerSpareQueueGetSize (void)
void DefragTrackerMoveToSpare (DefragTracker *h)
void DefragTrackerRelease (DefragTracker *t)
void DefragTrackerClearMemory (DefragTracker *dt)
void DefragInitConfig (bool quiet)
initialize the configuration
void DefragHashShutdown (void)
shutdown the flow engine
DefragTracker * DefragGetTrackerFromHash (Packet *p)
DefragTracker * DefragLookupTrackerFromHash (Packet *p)
look up a tracker in the hash
Variables
DefragTrackerHashRow * defragtracker_hash
DefragConfig defrag_config
Macro Definition Documentation
CMP_DEFRAGTRACKER
#define CMP_DEFRAGTRACKER (d1, d2, id)
Value:
    (((CMP_ADDR(&(d1)->src_addr, &(d2)->src) && \
       CMP_ADDR(&(d1)->dst_addr, &(d2)->dst)) || \
      (CMP_ADDR(&(d1)->src_addr, &(d2)->dst) && \
       CMP_ADDR(&(d1)->dst_addr, &(d2)->src))) && \
     (d1)->proto == IP_GET_IPPROTO(d2) &&   \
     (d1)->id == (id) && \
     (d1)->vlan_id[0] == (d2)->vlan_id[0] && \
     (d1)->vlan_id[1] == (d2)->vlan_id[1])
Definition at line 442 of file defrag-hash.c.
DEFRAG_DEFAULT_HASHSIZE
#define DEFRAG_DEFAULT_HASHSIZE 4096
Definition at line 161 of file defrag-hash.c.
DEFRAG_DEFAULT_MEMCAP
#define DEFRAG_DEFAULT_MEMCAP 16777216
Definition at line 162 of file defrag-hash.c.
DEFRAG_DEFAULT_PREALLOC
#define DEFRAG_DEFAULT_PREALLOC 1000
Definition at line 163 of file defrag-hash.c.
DefragTrackerDecrUsecnt
#define DefragTrackerDecrUsecnt (dt) SC_ATOMIC_SUB((dt)->use_cnt, 1)
Definition at line 123 of file defrag-hash.c.
DefragTrackerIncrUsecnt
#define DefragTrackerIncrUsecnt (dt) SC_ATOMIC_ADD((dt)->use_cnt, 1)
Definition at line 121 of file defrag-hash.c.
Typedef Documentation
DefragHashKey4
typedef struct DefragHashKey4_ DefragHashKey4
DefragHashKey6
typedef struct DefragHashKey6_ DefragHashKey6
Function Documentation
DefragGetTrackerFromHash()
DefragTracker * DefragGetTrackerFromHash (Packet * p)
Definition at line 535 of file defrag-hash.c.
DefragHashShutdown()
void DefragHashShutdown (void)
shutdown the flow engine
Warning
Not thread safe
Definition at line 301 of file defrag-hash.c.
Referenced by DefragDestroy().
DefragInitConfig()
void DefragInitConfig (bool quiet)
initialize the configuration
Warning
Not thread safe
set config values for memcap, prealloc and hash_size
Definition at line 167 of file defrag-hash.c.
References defrag_config, DefragTrackerQueueInit(), SC_ATOMIC_INIT, and SCLogDebug.
DefragLookupTrackerFromHash()
DefragTracker * DefragLookupTrackerFromHash (Packet * p)
look up a tracker in the hash
Parameters
a address to look up
Return values
h LOCKED tracker or NULL
Definition at line 634 of file defrag-hash.c.
DefragTrackerClearMemory()
void DefragTrackerClearMemory (DefragTracker * dt)
Definition at line 156 of file defrag-hash.c.
References DefragTrackerFreeFrags().
DefragTrackerGetMemcap()
uint64_t DefragTrackerGetMemcap (void)
Return memcap value.
Return values
memcap value
Definition at line 60 of file defrag-hash.c.
References defrag_config, and SC_ATOMIC_GET.
DefragTrackerGetMemuse()
uint64_t DefragTrackerGetMemuse (void)
Return memuse value.
Return values
memuse value
Definition at line 71 of file defrag-hash.c.
References SC_ATOMIC_GET.
DefragTrackerMoveToSpare()
void DefragTrackerMoveToSpare (DefragTracker * h)
Definition at line 82 of file defrag-hash.c.
References DefragTrackerEnqueue().
DefragTrackerRelease()
void DefragTrackerRelease (DefragTracker * t)
Definition at line 150 of file defrag-hash.c.
References DefragTrackerDecrUsecnt, DefragTracker_::lock, and SCMutexUnlock.
DefragTrackerSetMemcap()
int DefragTrackerSetMemcap (uint64_t size)
Update memcap value.
Parameters
size new memcap value
Definition at line 45 of file defrag-hash.c.
References defrag_config, SC_ATOMIC_GET, and SC_ATOMIC_SET.
DefragTrackerSpareQueueGetSize()
uint32_t DefragTrackerSpareQueueGetSize (void)
Definition at line 77 of file defrag-hash.c.
References DefragTrackerQueueLen().
SC_ATOMIC_DECLARE() [1/3]
SC_ATOMIC_DECLARE (uint64_t , defrag_memuse)
SC_ATOMIC_DECLARE() [2/3]
SC_ATOMIC_DECLARE (unsigned int , defragtracker_counter)
SC_ATOMIC_DECLARE() [3/3]
SC_ATOMIC_DECLARE (unsigned int , defragtracker_prune_idx)
Variable Documentation
defrag_config
DefragConfig defrag_config
Definition at line 30 of file defrag-hash.c.
Referenced by DefragInitConfig(), DefragTrackerGetMemcap(), and DefragTrackerSetMemcap().
defragtracker_hash
DefragTrackerHashRow* defragtracker_hash
defrag tracker hash table
Definition at line 29 of file defrag-hash.c.