suricata: /Users/jlu/suricata/src/defrag-hash.h File Reference
defrag-hash.h File Reference
#include "decode.h"
#include "defrag.h"
Data Structures
struct DefragTrackerHashRow_
struct DefragConfig_
Macros
#define DRLOCK_MUTEX
#define DRLOCK_TYPE SCMutex
#define DRLOCK_INIT(fb) SCMutexInit(&(fb)->lock, NULL)
#define DRLOCK_DESTROY(fb) SCMutexDestroy(&(fb)->lock)
#define DRLOCK_LOCK(fb) SCMutexLock(&(fb)->lock)
#define DRLOCK_TRYLOCK(fb) SCMutexTrylock(&(fb)->lock)
#define DRLOCK_UNLOCK(fb) SCMutexUnlock(&(fb)->lock)
#define DEFRAG_VERBOSE 0
#define DEFRAG_QUIET 1
#define DEFRAG_CHECK_MEMCAP(size) ((((uint64_t)SC_ATOMIC_GET(defrag_memuse) + (uint64_t)(size)) <= SC_ATOMIC_GET(defrag_config.memcap)))
check if a memory alloc would fit in the memcap
Typedefs
typedef struct DefragTrackerHashRow_ DefragTrackerHashRow
typedef struct DefragConfig_ DefragConfig
Functions
SC_ATOMIC_EXTERN (uint64_t, defrag_memuse)
SC_ATOMIC_EXTERN (unsigned int, defragtracker_counter)
SC_ATOMIC_EXTERN (unsigned int, defragtracker_prune_idx)
void DefragInitConfig (bool quiet)
initialize the configuration
void DefragHashShutdown (void)
shutdown the flow engine
DefragTracker * DefragLookupTrackerFromHash (Packet *)
look up a tracker in the hash
DefragTracker * DefragGetTrackerFromHash (Packet *)
void DefragTrackerRelease (DefragTracker *)
void DefragTrackerClearMemory (DefragTracker *)
void DefragTrackerMoveToSpare (DefragTracker *)
uint32_t DefragTrackerSpareQueueGetSize (void)
int DefragTrackerSetMemcap (uint64_t)
Update memcap value.
uint64_t DefragTrackerGetMemcap (void)
Return memcap value.
uint64_t DefragTrackerGetMemuse (void)
Return memuse value.
Variables
DefragTrackerHashRow * defragtracker_hash
DefragConfig defrag_config
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file defrag-hash.h.
Macro Definition Documentation
DEFRAG_CHECK_MEMCAP
#define DEFRAG_CHECK_MEMCAP (size) ((((uint64_t)SC_ATOMIC_GET(defrag_memuse) + (uint64_t)(size)) <= SC_ATOMIC_GET(defrag_config.memcap)))
check if a memory alloc would fit in the memcap
Parameters
size memory allocation size to check
Return values
1 it fits
0 no fit
Definition at line 85 of file defrag-hash.h.
DEFRAG_QUIET
#define DEFRAG_QUIET 1
Definition at line 68 of file defrag-hash.h.
DEFRAG_VERBOSE
#define DEFRAG_VERBOSE 0
Definition at line 67 of file defrag-hash.h.
DRLOCK_DESTROY
#define DRLOCK_DESTROY (fb) SCMutexDestroy(&(fb)->lock)
Definition at line 50 of file defrag-hash.h.
DRLOCK_INIT
#define DRLOCK_INIT (fb) SCMutexInit(&(fb)->lock, NULL)
Definition at line 49 of file defrag-hash.h.
DRLOCK_LOCK
#define DRLOCK_LOCK (fb) SCMutexLock(&(fb)->lock)
Definition at line 51 of file defrag-hash.h.
DRLOCK_MUTEX
#define DRLOCK_MUTEX
Spinlocks or Mutex for the flow buckets.
Definition at line 32 of file defrag-hash.h.
DRLOCK_TRYLOCK
#define DRLOCK_TRYLOCK (fb) SCMutexTrylock(&(fb)->lock)
Definition at line 52 of file defrag-hash.h.
DRLOCK_TYPE
#define DRLOCK_TYPE SCMutex
Definition at line 48 of file defrag-hash.h.
DRLOCK_UNLOCK
#define DRLOCK_UNLOCK (fb) SCMutexUnlock(&(fb)->lock)
Definition at line 53 of file defrag-hash.h.
Typedef Documentation
DefragConfig
typedef struct DefragConfig_ DefragConfig
DefragTrackerHashRow
typedef struct DefragTrackerHashRow_ DefragTrackerHashRow
Function Documentation
DefragGetTrackerFromHash()
DefragTracker * DefragGetTrackerFromHash (Packet * p)
Definition at line 535 of file defrag-hash.c.
DefragHashShutdown()
void DefragHashShutdown (void)
shutdown the flow engine
Warning
Not thread safe
Definition at line 301 of file defrag-hash.c.
Referenced by DefragDestroy().
DefragInitConfig()
void DefragInitConfig (bool quiet)
initialize the configuration
Warning
Not thread safe
set config values for memcap, prealloc and hash_size
Definition at line 167 of file defrag-hash.c.
References defrag_config, DefragTrackerQueueInit(), SC_ATOMIC_INIT, and SCLogDebug.
DefragLookupTrackerFromHash()
DefragTracker * DefragLookupTrackerFromHash (Packet * p)
look up a tracker in the hash
Parameters
a address to look up
Return values
h LOCKED tracker or NULL
Definition at line 634 of file defrag-hash.c.
DefragTrackerClearMemory()
void DefragTrackerClearMemory (DefragTracker * dt)
Definition at line 156 of file defrag-hash.c.
References DefragTrackerFreeFrags().
DefragTrackerGetMemcap()
uint64_t DefragTrackerGetMemcap (void)
Return memcap value.
Return values
memcap value
Definition at line 60 of file defrag-hash.c.
References defrag_config, and SC_ATOMIC_GET.
DefragTrackerGetMemuse()
uint64_t DefragTrackerGetMemuse (void)
Return memuse value.
Return values
memuse value
Definition at line 71 of file defrag-hash.c.
References SC_ATOMIC_GET.
DefragTrackerMoveToSpare()
void DefragTrackerMoveToSpare (DefragTracker * h)
Definition at line 82 of file defrag-hash.c.
References DefragTrackerEnqueue().
DefragTrackerRelease()
void DefragTrackerRelease (DefragTracker * t)
Definition at line 150 of file defrag-hash.c.
References DefragTrackerDecrUsecnt, DefragTracker_::lock, and SCMutexUnlock.
DefragTrackerSetMemcap()
int DefragTrackerSetMemcap (uint64_t size)
Update memcap value.
Parameters
size new memcap value
Definition at line 45 of file defrag-hash.c.
References defrag_config, SC_ATOMIC_GET, and SC_ATOMIC_SET.
DefragTrackerSpareQueueGetSize()
uint32_t DefragTrackerSpareQueueGetSize (void)
Definition at line 77 of file defrag-hash.c.
References DefragTrackerQueueLen().
SC_ATOMIC_EXTERN() [1/3]
SC_ATOMIC_EXTERN (uint64_t , defrag_memuse)
SC_ATOMIC_EXTERN() [2/3]
SC_ATOMIC_EXTERN (unsigned int , defragtracker_counter)
SC_ATOMIC_EXTERN() [3/3]
SC_ATOMIC_EXTERN (unsigned int , defragtracker_prune_idx)
Variable Documentation
defrag_config
DefragConfig defrag_config extern
Definition at line 30 of file defrag-hash.c.
Referenced by DefragInitConfig(), DefragTrackerGetMemcap(), and DefragTrackerSetMemcap().
defragtracker_hash
DefragTrackerHashRow* defragtracker_hash extern
defrag tracker hash table
Definition at line 29 of file defrag-hash.c.