suricata: /Users/jlu/suricata/src/defrag-queue.c File Reference
defrag-queue.c File Reference
#include "suricata-common.h"
#include "threads.h"
#include "defrag-queue.h"
#include "util-error.h"
#include "util-debug.h"
#include "util-print.h"
Functions
DefragTrackerQueue * DefragTrackerQueueInit (DefragTrackerQueue *q)
DefragTrackerQueue * DefragTrackerQueueNew ()
void DefragTrackerQueueDestroy (DefragTrackerQueue *q)
Destroy a tracker queue.
void DefragTrackerEnqueue (DefragTrackerQueue *q, DefragTracker *dt)
add a tracker to a queue
DefragTracker * DefragTrackerDequeue (DefragTrackerQueue *q)
remove a tracker from the queue
uint32_t DefragTrackerQueueLen (DefragTrackerQueue *q)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Defrag tracker queue handler functions
Definition in file defrag-queue.c.
Function Documentation
DefragTrackerDequeue()
DefragTracker * DefragTrackerDequeue (DefragTrackerQueue * q)
remove a tracker from the queue
Parameters
q queue
Return values
dt tracker or NULL if empty list.
Definition at line 102 of file defrag-queue.c.
References DefragTrackerQueue_::bot, BUG_ON, DQLOCK_LOCK, DQLOCK_UNLOCK, DefragTrackerQueue_::len, DefragTracker_::lnext, DefragTracker_::lprev, and DefragTrackerQueue_::top.
DefragTrackerEnqueue()
void DefragTrackerEnqueue (DefragTrackerQueue * q, DefragTracker * dt)
add a tracker to a queue
Parameters
q queue
dt tracker
Definition at line 69 of file defrag-queue.c.
References DefragTrackerQueue_::bot, BUG_ON, DQLOCK_LOCK, DQLOCK_UNLOCK, DefragTrackerQueue_::len, DefragTracker_::lnext, DefragTracker_::lprev, and DefragTrackerQueue_::top.
Referenced by DefragTrackerMoveToSpare().
DefragTrackerQueueDestroy()
void DefragTrackerQueueDestroy (DefragTrackerQueue * q)
Destroy a tracker queue.
Parameters
q the tracker queue to destroy
Definition at line 58 of file defrag-queue.c.
References DQLOCK_DESTROY.
DefragTrackerQueueInit()
DefragTrackerQueue * DefragTrackerQueueInit (DefragTrackerQueue * q)
Definition at line 33 of file defrag-queue.c.
References DQLOCK_INIT.
Referenced by DefragInitConfig(), and DefragTrackerQueueNew().
DefragTrackerQueueLen()
uint32_t DefragTrackerQueueLen (DefragTrackerQueue * q)
Definition at line 135 of file defrag-queue.c.
References DQLOCK_LOCK, DQLOCK_UNLOCK, len, and DefragTrackerQueue_::len.
Referenced by DefragTrackerSpareQueueGetSize().
DefragTrackerQueueNew()
DefragTrackerQueue * DefragTrackerQueueNew (void)
Definition at line 42 of file defrag-queue.c.
References DefragTrackerQueueInit(), SC_ERR_FATAL, SCLogError, and SCMalloc.