suricata: /Users/jlu/suricata/src/detect-http-uri.c File Reference
detect-http-uri.c File Reference
HTTP layer support
#include "suricata-common.h"
#include "threads.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-engine-prefilter.h"
#include "detect-content.h"
#include "detect-pcre.h"
#include "detect-urilen.h"
#include "flow.h"
#include "flow-var.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-spm.h"
#include "util-print.h"
#include "app-layer.h"
#include "app-layer-htp.h"
#include "detect-http-uri.h"
#include "stream-tcp.h"
#include "tests/detect-http-uri.c"
void DetectHttpUriRegister (void)
Registration function for keywords: http_uri and http.uri.
int DetectHttpUriSetup (DetectEngineCtx *de_ctx, Signature *s, const char *str)
this function setups the http_uri modifier keyword used in the rule
Detailed Description
Author
Gerardo Iglesias igles.nosp@m.iasg.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file detect-http-uri.c.
Function Documentation
DetectHttpUriRegister()
void DetectHttpUriRegister (void)
Registration function for keywords: http_uri and http.uri.
Definition at line 89 of file detect-http-uri.c.
References SigTableElmt_::desc, DETECT_AL_HTTP_URI, DetectHttpUriSetup(), SigTableElmt_::name, SigTableElmt_::RegisterTests, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
DetectHttpUriSetup()
int DetectHttpUriSetup (DetectEngineCtx * de_ctx, Signature * s, const char * str)
this function setups the http_uri modifier keyword used in the rule
Parameters
de_ctx Pointer to the Detection Engine Context
s Pointer to the Signature to which the current keyword belongs
str Should hold an empty string always
Return values
0 On success
-1 On failure
Definition at line 184 of file detect-http-uri.c.
References de_ctx, DETECT_AL_HTTP_URI, DetectEngineContentModifierBufferSetup(), and str.
Referenced by DetectHttpUriRegister().