suricata: /Users/jlu/suricata/src/detect-base64-decode.h File Reference
detect-base64-decode.h File Reference
Functions
void DetectBase64DecodeRegister (void)
int DetectBase64DecodeDoMatch (DetectEngineThreadCtx *, const Signature *, const SigMatchData *, const uint8_t *, uint32_t)
Function Documentation
DetectBase64DecodeDoMatch()
int DetectBase64DecodeDoMatch (DetectEngineThreadCtx * det_ctx, const Signature * s, const SigMatchData * smd, const uint8_t * payload, uint32_t payload_len)
Definition at line 66 of file detect-base64-decode.c.
References DetectEngineThreadCtx_::base64_decoded, DetectEngineThreadCtx_::base64_decoded_len, DetectEngineThreadCtx_::base64_decoded_len_max, BASE64_MODE_RELAX, DetectEngineThreadCtx_::buffer_offset, DetectBase64Decode_::bytes, SigMatchData_::ctx, DecodeBase64(), MIN, DetectBase64Decode_::offset, payload_len, PrintRawDataFp(), DetectBase64Decode_::relative, and SCLogDebug.
DetectBase64DecodeRegister()
void DetectBase64DecodeRegister (void)
Definition at line 48 of file detect-base64-decode.c.
References SigTableElmt_::desc, DETECT_BASE64_DECODE, SigTableElmt_::name, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().