suricata: /Users/jlu/suricata/src/detect-http-uri.h File Reference
detect-http-uri.h File Reference
Functions
int DetectHttpUriSetup (DetectEngineCtx *, Signature *, const char *)
this function setups the http_uri modifier keyword used in the rule
void DetectHttpUriRegister (void)
Registration function for keywords: http_uri and http.uri.
Detailed Description
Author
Gerardo Iglesias Galvan igles.nosp@m.iasg.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Definition in file detect-http-uri.h.
Function Documentation
DetectHttpUriRegister()
void DetectHttpUriRegister (void)
Registration function for keywords: http_uri and http.uri.
Definition at line 89 of file detect-http-uri.c.
References SigTableElmt_::desc, DETECT_AL_HTTP_URI, DetectHttpUriSetup(), SigTableElmt_::name, SigTableElmt_::RegisterTests, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
DetectHttpUriSetup()
int DetectHttpUriSetup (DetectEngineCtx * de_ctx, Signature * s, const char * str)
this function setups the http_uri modifier keyword used in the rule
Parameters
de_ctx Pointer to the Detection Engine Context
s Pointer to the Signature to which the current keyword belongs
str Should hold an empty string always
Return values
0 On success
-1 On failure
Definition at line 184 of file detect-http-uri.c.
References de_ctx, DETECT_AL_HTTP_URI, DetectEngineContentModifierBufferSetup(), and str.
Referenced by DetectHttpUriRegister().