suricata: /Users/jlu/suricata/src/detect-engine-sigorder.h File Reference
detect-engine-sigorder.h File Reference
Data Structures
struct SCSigSignatureWrapper_
Signature wrapper used by signature ordering module while ordering signatures.
struct SCSigOrderFunc_
Structure holding the signature ordering function used by the signature ordering module.
Typedefs
typedef struct SCSigSignatureWrapper_ SCSigSignatureWrapper
Signature wrapper used by signature ordering module while ordering signatures.
typedef struct SCSigOrderFunc_ SCSigOrderFunc
Structure holding the signature ordering function used by the signature ordering module.
Enumerations
enum SCRadixUserDataType {
SC_RADIX_USER_DATA_FLOWBITS , SC_RADIX_USER_DATA_FLOWVAR , SC_RADIX_USER_DATA_PKTVAR , SC_RADIX_USER_DATA_FLOWINT ,
SC_RADIX_USER_DATA_HOSTBITS , SC_RADIX_USER_DATA_IPPAIRBITS , SC_RADIX_USER_DATA_MAX
}
Different kinds of helper data that can be used by the signature ordering module. Used by the "user" field in SCSigSignatureWrapper.
Functions
void SCSigOrderSignatures (DetectEngineCtx *)
Orders the signatures.
void SCSigRegisterSignatureOrderingFuncs (DetectEngineCtx *)
Lets you register the Signature ordering functions. The order in which the functions are registered shows the priority. The first function registered provides more priority than the function registered after it. To add a new registration function, register it by listing it in the correct position in the below sequence, based on the priority you would want to offer to that keyword.
void SCSigRegisterSignatureOrderingTests (void)
void SCSigSignatureOrderingModuleCleanup (DetectEngineCtx *)
De-registers all the signature ordering functions registered.
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file detect-engine-sigorder.h.
Typedef Documentation
SCSigOrderFunc
typedef struct SCSigOrderFunc_ SCSigOrderFunc
Structure holding the signature ordering function used by the signature ordering module.
SCSigSignatureWrapper
typedef struct SCSigSignatureWrapper_ SCSigSignatureWrapper
Signature wrapper used by signature ordering module while ordering signatures.
Enumeration Type Documentation
SCRadixUserDataType
enum SCRadixUserDataType
Different kinds of helper data that can be used by the signature ordering module. Used by the "user" field in SCSigSignatureWrapper.
Enumerator
SC_RADIX_USER_DATA_FLOWBITS
SC_RADIX_USER_DATA_FLOWVAR
SC_RADIX_USER_DATA_PKTVAR
SC_RADIX_USER_DATA_FLOWINT
SC_RADIX_USER_DATA_HOSTBITS
SC_RADIX_USER_DATA_IPPAIRBITS
SC_RADIX_USER_DATA_MAX
Definition at line 31 of file detect-engine-sigorder.h.
Function Documentation
SCSigOrderSignatures()
void SCSigOrderSignatures (DetectEngineCtx * de_ctx)
Orders the signatures.
Parameters
de_ctx Pointer to the Detection Engine Context that holds the signatures to be ordered
Definition at line 729 of file detect-engine-sigorder.c.
References de_ctx, SCLogDebug, and DetectEngineCtx_::sig_list.
Referenced by UTHMatchPackets().
SCSigRegisterSignatureOrderingFuncs()
void SCSigRegisterSignatureOrderingFuncs (DetectEngineCtx * de_ctx)
Lets you register the Signature ordering functions. The order in which the functions are registered shows the priority. The first function registered provides more priority than the function registered after it. To add a new registration function, register it by listing it in the correct position in the below sequence, based on the priority you would want to offer to that keyword.
Parameters
de_ctx Pointer to the detection engine context from which the signatures have to be ordered.
Definition at line 789 of file detect-engine-sigorder.c.
References SCLogDebug.
Referenced by UTHMatchPackets().
SCSigRegisterSignatureOrderingTests()
void SCSigRegisterSignatureOrderingTests (void)
Definition at line 2153 of file detect-engine-sigorder.c.
References UtRegisterTest().
SCSigSignatureOrderingModuleCleanup()
void SCSigSignatureOrderingModuleCleanup (DetectEngineCtx * de_ctx)
De-registers all the signature ordering functions registered.
Parameters
de_ctx Pointer to the detection engine context from which the signatures were ordered.
Definition at line 809 of file detect-engine-sigorder.c.
References de_ctx, SCSigOrderFunc_::next, DetectEngineCtx_::sc_sig_order_funcs, and SCFree.
Referenced by DetectEngineCtxFree(), and UTHMatchPackets().