suricata: /Users/jlu/suricata/src/detect-engine.c File Reference
detect-engine.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "detect.h"
#include "flow.h"
#include "flow-private.h"
#include "flow-util.h"
#include "flow-worker.h"
#include "conf.h"
#include "conf-yaml-loader.h"
#include "datasets.h"
#include "app-layer-parser.h"
#include "app-layer-htp.h"
#include "detect-parse.h"
#include "detect-engine-sigorder.h"
#include "detect-engine-build.h"
#include "detect-engine-siggroup.h"
#include "detect-engine-address.h"
#include "detect-engine-port.h"
#include "detect-engine-prefilter.h"
#include "detect-engine-mpm.h"
#include "detect-engine-iponly.h"
#include "detect-engine-tag.h"
#include "detect-engine-frame.h"
#include "detect-engine-file.h"
#include "detect-engine.h"
#include "detect-engine-state.h"
#include "detect-engine-payload.h"
#include "detect-fast-pattern.h"
#include "detect-byte-extract.h"
#include "detect-content.h"
#include "detect-uricontent.h"
#include "detect-tcphdr.h"
#include "detect-engine-threshold.h"
#include "detect-engine-content-inspection.h"
#include "detect-engine-loader.h"
#include "util-classification-config.h"
#include "util-reference-config.h"
#include "util-threshold-config.h"
#include "util-error.h"
#include "util-hash.h"
#include "util-byte.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-action.h"
#include "util-magic.h"
#include "util-signal.h"
#include "util-spm.h"
#include "util-device.h"
#include "util-var-name.h"
#include "util-profiling.h"
#include "util-validate.h"
#include "util-hash-string.h"
#include "util-enum.h"
#include "tm-threads.h"
#include "runmodes.h"
#include "reputation.h"
#include "util-hash-lookup3.h"
Data Structures
struct DetectEngineSyncer_
struct TenantLoaderCtx_
Macros
#define DETECT_ENGINE_DEFAULT_INSPECTION_RECURSION_LIMIT 3000
Typedefs
typedef struct DetectEngineSyncer_ DetectEngineSyncer
typedef struct TenantLoaderCtx_ TenantLoaderCtx
Enumerations
enum DetectEngineSyncState { IDLE , RELOAD }
Functions
void DetectPktInspectEngineRegister (const char *name, InspectionBufferGetPktDataPtr GetPktData, InspectionBufferPktInspectFunc Callback)
register inspect engine at start up time
void DetectFrameInspectEngineRegister (const char *name, int dir, InspectionBufferFrameInspectFunc Callback, AppProto alproto, uint8_t type)
register inspect engine at start up time
void DetectAppLayerInspectEngineRegister2 (const char *name, AppProto alproto, uint32_t dir, int progress, InspectEngineFuncPtr2 Callback2, InspectionBufferGetDataPtr GetData)
register inspect engine at start up time
void DetectEngineFrameInspectEngineRegister (DetectEngineCtx *de_ctx, const char *name, int dir, InspectionBufferFrameInspectFunc Callback, AppProto alproto, uint8_t type)
register inspect engine at start up time
int DetectEngineAppInspectionEngine2Signature (DetectEngineCtx *de_ctx, Signature *s)
void DetectEngineAppInspectionEngineSignatureFree (DetectEngineCtx *de_ctx, Signature *s)
free app inspect engines for a signature
int DetectBufferTypeMaxId (void)
int DetectBufferTypeRegister (const char *name)
void DetectBufferTypeSupportsFrames (const char *name)
void DetectBufferTypeSupportsPacket (const char *name)
void DetectBufferTypeSupportsMpm (const char *name)
void DetectBufferTypeSupportsTransformations (const char *name)
int DetectBufferTypeGetByName (const char *name)
const DetectBufferType * DetectEngineBufferTypeGetById (const DetectEngineCtx *de_ctx, const int id)
const char * DetectEngineBufferTypeGetNameById (const DetectEngineCtx *de_ctx, const int id)
int DetectEngineBufferTypeRegisterWithFrameEngines (DetectEngineCtx *de_ctx, const char *name, const int direction, const AppProto alproto, const uint8_t frame_type)
int DetectEngineBufferTypeRegister (DetectEngineCtx *de_ctx, const char *name)
void DetectBufferTypeSetDescriptionByName (const char *name, const char *desc)
const char * DetectEngineBufferTypeGetDescriptionById (const DetectEngineCtx *de_ctx, const int id)
const char * DetectBufferTypeGetDescriptionByName (const char *name)
void DetectEngineBufferTypeSupportsFrames (DetectEngineCtx *de_ctx, const char *name)
void DetectEngineBufferTypeSupportsPacket (DetectEngineCtx *de_ctx, const char *name)
void DetectEngineBufferTypeSupportsMpm (DetectEngineCtx *de_ctx, const char *name)
void DetectEngineBufferTypeSupportsTransformations (DetectEngineCtx *de_ctx, const char *name)
bool DetectEngineBufferTypeSupportsPacketGetById (const DetectEngineCtx *de_ctx, const int id)
bool DetectEngineBufferTypeSupportsMpmGetById (const DetectEngineCtx *de_ctx, const int id)
void DetectBufferTypeRegisterSetupCallback (const char *name, void(*SetupCallback)(const DetectEngineCtx *, Signature *))
void DetectEngineBufferRunSetupCallback (const DetectEngineCtx *de_ctx, const int id, Signature *s)
void DetectBufferTypeRegisterValidateCallback (const char *name, bool(*ValidateCallback)(const Signature *, const char **sigerror))
bool DetectEngineBufferRunValidateCallback (const DetectEngineCtx *de_ctx, const int id, const Signature *s, const char **sigerror)
int DetectBufferSetActiveList (Signature *s, const int list)
int DetectBufferGetActiveList (DetectEngineCtx *de_ctx, Signature *s)
void InspectionBufferClean (DetectEngineThreadCtx *det_ctx)
InspectionBuffer * InspectionBufferGet (DetectEngineThreadCtx *det_ctx, const int list_id)
InspectionBuffer * InspectionBufferMultipleForListGet (DetectEngineThreadCtx *det_ctx, const int list_id, const uint32_t local_id)
for a InspectionBufferMultipleForList get a InspectionBuffer
void InspectionBufferInit (InspectionBuffer *buffer, uint32_t initial_size)
void InspectionBufferSetupMulti (InspectionBuffer *buffer, const DetectEngineTransforms *transforms, const uint8_t *data, const uint32_t data_len)
setup the buffer with our initial data
void InspectionBufferSetup (DetectEngineThreadCtx *det_ctx, const int list_id, InspectionBuffer *buffer, const uint8_t *data, const uint32_t data_len)
setup the buffer with our initial data
void InspectionBufferFree (InspectionBuffer *buffer)
void InspectionBufferCheckAndExpand (InspectionBuffer *buffer, uint32_t min_size)
make sure that the buffer has at least 'min_size' bytes Expand the buffer if necessary
void InspectionBufferCopy (InspectionBuffer *buffer, uint8_t *buf, uint32_t buf_len)
bool DetectEngineBufferTypeValidateTransform (DetectEngineCtx *de_ctx, int sm_list, const uint8_t *content, uint16_t content_len, const char **namestr)
Check content byte array compatibility with transforms.
void InspectionBufferApplyTransforms (InspectionBuffer *buffer, const DetectEngineTransforms *transforms)
void DetectBufferTypeCloseRegistration (void)
int DetectEngineBufferTypeGetByIdTransforms (DetectEngineCtx *de_ctx, const int id, TransformData *transforms, int transform_cnt)
bool DetectEnginePktInspectionRun (ThreadVars *tv, DetectEngineThreadCtx *det_ctx, const Signature *s, Flow *f, Packet *p, uint8_t *alert_flags)
int DetectEnginePktInspectionSetup (Signature *s)
int DetectEngineReloadStart (void)
int DetectEngineReloadIsStart (void)
void DetectEngineReloadSetIdle (void)
int DetectEngineReloadIsIdle (void)
uint8_t DetectEngineInspectGenericList (DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, const struct DetectEngineAppInspectionEngine_ *engine, const Signature *s, Flow *f, uint8_t flags, void *alstate, void *txv, uint64_t tx_id)
Do the content inspection & validation for a signature.
uint8_t DetectEngineInspectBufferGeneric (DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, const DetectEngineAppInspectionEngine *engine, const Signature *s, Flow *f, uint8_t flags, void *alstate, void *txv, uint64_t tx_id)
Do the content inspection & validation for a signature.
int DetectEngineInspectPktBufferGeneric (DetectEngineThreadCtx *det_ctx, const DetectEnginePktInspectionEngine *engine, const Signature *s, Packet *p, uint8_t *_alert_flags)
Do the content inspection & validation for a signature.
DetectEngineCtx * DetectEngineCtxInitStubForMT (void)
DetectEngineCtx * DetectEngineCtxInitStubForDD (void)
DetectEngineCtx * DetectEngineCtxInit (void)
DetectEngineCtx * DetectEngineCtxInitWithPrefix (const char *prefix)
void DetectEngineCtxFree (DetectEngineCtx *de_ctx)
Free a DetectEngineCtx::
void DetectEngineResetMaxSigId (DetectEngineCtx *de_ctx)
TmEcode DetectEngineThreadCtxInit (ThreadVars *tv, void *initdata, void **data)
initialize thread specific detection engine context
DetectEngineThreadCtx * DetectEngineThreadCtxInitForReload (ThreadVars *tv, DetectEngineCtx *new_de_ctx, int mt)
TmEcode DetectEngineThreadCtxDeinit (ThreadVars *tv, void *data)
void DetectEngineThreadCtxInfo (ThreadVars *t, DetectEngineThreadCtx *det_ctx)
int DetectRegisterThreadCtxFuncs (DetectEngineCtx *de_ctx, const char *name, void *(*InitFunc)(void *), void *data, void(*FreeFunc)(void *), int mode)
Register Thread keyword context Funcs.
int DetectUnregisterThreadCtxFuncs (DetectEngineCtx *de_ctx, void *data, const char *name)
Remove Thread keyword context registration.
void * DetectThreadCtxGetKeywordThreadCtx (DetectEngineThreadCtx *det_ctx, int id)
Retrieve thread local keyword ctx by id.
int DetectRegisterThreadCtxGlobalFuncs (const char *name, void *(*InitFunc)(void *), void *data, void(*FreeFunc)(void *))
Register Thread keyword context Funcs (Global)
void * DetectThreadCtxGetGlobalKeywordThreadCtx (DetectEngineThreadCtx *det_ctx, int id)
Retrieve thread local keyword ctx by id.
int DetectEngineEnabled (void)
Check if detection is enabled.
uint32_t DetectEngineGetVersion (void)
void DetectEngineBumpVersion (void)
DetectEngineCtx * DetectEngineGetCurrent (void)
DetectEngineCtx * DetectEngineReference (DetectEngineCtx *de_ctx)
int DetectEngineMultiTenantEnabled (void)
int DetectEngineLoadTenantBlocking (uint32_t tenant_id, const char *yaml)
Load a tenant and wait for loading to complete.
int DetectEngineReloadTenantBlocking (uint32_t tenant_id, const char *yaml, int reload_cnt)
Reload a tenant and wait for loading to complete.
int DetectEngineMultiTenantSetup (void)
setup multi-detect / multi-tenancy
int DetectEngineTentantRegisterLivedev (uint32_t tenant_id, int device_id)
int DetectEngineTentantRegisterVlanId (uint32_t tenant_id, uint16_t vlan_id)
int DetectEngineTentantUnregisterVlanId (uint32_t tenant_id, uint16_t vlan_id)
int DetectEngineTentantRegisterPcapFile (uint32_t tenant_id)
int DetectEngineTentantUnregisterPcapFile (uint32_t tenant_id)
DetectEngineCtx * DetectEngineGetByTenantId (int tenant_id)
void DetectEngineDeReference (DetectEngineCtx **de_ctx)
int DetectEngineAddToMaster (DetectEngineCtx *de_ctx)
int DetectEngineMoveToFreeList (DetectEngineCtx *de_ctx)
void DetectEnginePruneFreeList (void)
int DetectEngineReload (const SCInstance *suri)
Reload the detection engine.
int DetectEngineMTApply (void)
void DetectEngineSetParseMetadata (void)
void DetectEngineUnsetParseMetadata (void)
int DetectEngineMustParseMetadata (void)
const char * DetectSigmatchListEnumToString (enum DetectSigmatchListEnum type)
void DetectEngineSetEvent (DetectEngineThreadCtx *det_ctx, uint8_t e)
AppLayerDecoderEvents * DetectEngineGetEvents (DetectEngineThreadCtx *det_ctx)
int DetectEngineGetEventInfo (const char *event_name, int *event_id, AppLayerEventType *event_type)
void DetectEngineRegisterTests ()
Variables
SCEnumCharMap det_ctx_event_table []
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file detect-engine.c.
Macro Definition Documentation
DETECT_ENGINE_DEFAULT_INSPECTION_RECURSION_LIMIT
#define DETECT_ENGINE_DEFAULT_INSPECTION_RECURSION_LIMIT 3000
Definition at line 90 of file detect-engine.c.
Typedef Documentation
DetectEngineSyncer
typedef struct DetectEngineSyncer_ DetectEngineSyncer
TenantLoaderCtx
typedef struct TenantLoaderCtx_ TenantLoaderCtx
Enumeration Type Documentation
DetectEngineSyncState
enum DetectEngineSyncState
Enumerator
IDLE
ready to start a reload
RELOAD
command main thread to do the reload
Definition at line 1879 of file detect-engine.c.
Function Documentation
DetectAppLayerInspectEngineRegister2()
void DetectAppLayerInspectEngineRegister2 (const char * name, AppProto alproto, uint32_t dir, int progress, InspectEngineFuncPtr2 Callback2, InspectionBufferGetDataPtr GetData)
register inspect engine at start up time
Registers an app inspection engine.
Note
errors are fatal
Definition at line 227 of file detect-engine.c.
DetectBufferGetActiveList()
int DetectBufferGetActiveList (DetectEngineCtx * de_ctx, Signature * s)
Definition at line 1313 of file detect-engine.c.
References BUG_ON, DetectEngineTransforms::cnt, de_ctx, DETECT_SM_LIST_DYNAMIC_START, DETECT_SM_LIST_NOTSET, DetectEngineBufferTypeGetByIdTransforms(), Signature_::init_data, SignatureInitData_::list, SignatureInitData_::list_set, SC_ERR_INVALID_SIGNATURE, SCLogDebug, SCLogError, SCReturnInt, DetectEngineTransforms::transforms, and SignatureInitData_::transforms.
Referenced by DetectContentSetup().
DetectBufferSetActiveList()
int DetectBufferSetActiveList (Signature * s, const int list)
Definition at line 1300 of file detect-engine.c.
DetectBufferTypeCloseRegistration()
void DetectBufferTypeCloseRegistration (void)
Definition at line 1658 of file detect-engine.c.
References BUG_ON.
Referenced by SigTableSetup().
DetectBufferTypeGetByName()
int DetectBufferTypeGetByName (const char * name)
Definition at line 1086 of file detect-engine.c.
Referenced by DetectEngineAppInspectionEngine2Signature(), DetectFrameInspectEngineRegister(), DetectFrameMpmRegister(), and DetectPktInspectEngineRegister().
DetectBufferTypeGetDescriptionByName()
const char * DetectBufferTypeGetDescriptionByName (const char * name)
Definition at line 1203 of file detect-engine.c.
DetectBufferTypeMaxId()
int DetectBufferTypeMaxId (void)
Definition at line 922 of file detect-engine.c.
Referenced by SigAlloc().
DetectBufferTypeRegister()
int DetectBufferTypeRegister (const char * name)
Definition at line 1032 of file detect-engine.c.
References BUG_ON.
Referenced by DetectFrameInspectEngineRegister(), and DetectPktInspectEngineRegister().
DetectBufferTypeRegisterSetupCallback()
void DetectBufferTypeRegisterSetupCallback (const char * name, void(*)(const DetectEngineCtx *, Signature *) SetupCallback)
Definition at line 1262 of file detect-engine.c.
References BUG_ON.
DetectBufferTypeRegisterValidateCallback()
void DetectBufferTypeRegisterValidateCallback (const char * name, bool(*)(const Signature *, const char **sigerror) ValidateCallback)
Definition at line 1280 of file detect-engine.c.
References BUG_ON.
DetectBufferTypeSetDescriptionByName()
void DetectBufferTypeSetDescriptionByName (const char * name, const char * desc)
Definition at line 1183 of file detect-engine.c.
References BUG_ON.
DetectBufferTypeSupportsFrames()
void DetectBufferTypeSupportsFrames (const char * name)
Definition at line 1046 of file detect-engine.c.
References BUG_ON.
Referenced by DetectFrameMpmRegister().
DetectBufferTypeSupportsMpm()
void DetectBufferTypeSupportsMpm (const char * name)
Definition at line 1066 of file detect-engine.c.
References BUG_ON.
Referenced by DetectFrameMpmRegister().
DetectBufferTypeSupportsPacket()
void DetectBufferTypeSupportsPacket (const char * name)
Definition at line 1056 of file detect-engine.c.
References BUG_ON.
DetectBufferTypeSupportsTransformations()
void DetectBufferTypeSupportsTransformations (const char * name)
Definition at line 1076 of file detect-engine.c.
References BUG_ON.
Referenced by DetectFrameMpmRegister().
DetectEngineAddToMaster()
int DetectEngineAddToMaster (DetectEngineCtx * de_ctx)
Definition at line 4332 of file detect-engine.c.
References de_ctx, and SCLogDebug.
DetectEngineAppInspectionEngine2Signature()
int DetectEngineAppInspectionEngine2Signature (DetectEngineCtx * de_ctx, Signature * s)
Note
for the file inspect engine, the id DE_STATE_ID_FILE_INSPECT is assigned.
Definition at line 587 of file detect-engine.c.
References DetectEngineFrameInspectionEngine::alproto, Signature_::alproto, ALPROTO_UNKNOWN, de_ctx, DETECT_SM_LIST_DYNAMIC_START, DetectBufferTypeGetByName(), DetectEngineCtx_::frame_inspect_engines, Signature_::init_data, SignatureInitData_::mpm_sm, SignatureInitData_::mpm_sm_list, SCLogDebug, SigMatchList2DataArray(), DetectEngineFrameInspectionEngine::sm_list, SignatureInitData_::smlists, and SignatureInitData_::smlists_array_size.
DetectEngineAppInspectionEngineSignatureFree()
void DetectEngineAppInspectionEngineSignatureFree (DetectEngineCtx * de_ctx, Signature * s)
free app inspect engines for a signature
For lists that are registered multiple times, like http_header and http_cookie, making the engines owner of the lists is complicated. Multiple engines in a sig may be pointing to the same list. To address this the 'free' code needs to be extra careful about not double freeing, so it takes an approach to first fill an array of the to-free pointers before freeing them.
Definition at line 843 of file detect-engine.c.
References Signature_::app_inspect, BUG_ON, SigMatchData_::ctx, de_ctx, Signature_::frame_inspect, SigTableElmt_::Free, SigMatchData_::is_last, MAX, next, DetectEngineAppInspectionEngine_::next, DetectEnginePktInspectionEngine::next, DetectEngineFrameInspectionEngine::next, Signature_::pkt_inspect, SCFree, sigmatch_table, DetectEngineAppInspectionEngine_::sm_list, DetectEnginePktInspectionEngine::sm_list, DetectEngineFrameInspectionEngine::sm_list, DetectEngineAppInspectionEngine_::smd, DetectEnginePktInspectionEngine::smd, DetectEngineFrameInspectionEngine::smd, and SigMatchData_::type.
DetectEngineBufferRunSetupCallback()
void DetectEngineBufferRunSetupCallback (const DetectEngineCtx * de_ctx, const int id, Signature * s)
Definition at line 1272 of file detect-engine.c.
References de_ctx, DetectEngineBufferTypeGetById(), and DetectBufferType_::SetupCallback.
DetectEngineBufferRunValidateCallback()
bool DetectEngineBufferRunValidateCallback (const DetectEngineCtx * de_ctx, const int id, const Signature * s, const char ** sigerror)
Definition at line 1290 of file detect-engine.c.
References de_ctx, DetectEngineBufferTypeGetById(), and DetectBufferType_::ValidateCallback.
DetectEngineBufferTypeGetById()
const DetectBufferType * DetectEngineBufferTypeGetById (const DetectEngineCtx * de_ctx, const int id)
Definition at line 1106 of file detect-engine.c.
References DetectEngineCtx_::buffer_type_hash_id, de_ctx, HashListTableLookup(), DetectBufferType_::id, and res.
Referenced by DetectEngineBufferRunSetupCallback(), DetectEngineBufferRunValidateCallback(), DetectEngineBufferTypeGetByIdTransforms(), DetectEngineBufferTypeGetDescriptionById(), DetectEngineBufferTypeGetNameById(), DetectEngineBufferTypeSupportsMpmGetById(), DetectEngineBufferTypeSupportsPacketGetById(), and DetectEngineBufferTypeValidateTransform().
DetectEngineBufferTypeGetByIdTransforms()
int DetectEngineBufferTypeGetByIdTransforms (DetectEngineCtx * de_ctx, const int id, TransformData * transforms, int transform_cnt)
Definition at line 1665 of file detect-engine.c.
References DetectEngineCtx_::buffer_type_hash_id, DetectEngineCtx_::buffer_type_hash_name, DetectEngineCtx_::buffer_type_id, BUG_ON, DetectEngineTransforms::cnt, de_ctx, DetectAppLayerMpmRegisterByParentId(), DetectEngineBufferTypeGetById(), DetectFrameMpmRegisterByParentId(), DetectPktMpmRegisterByParentId(), DetectBufferType_::frame, HashListTableAdd(), HashListTableLookup(), DetectBufferType_::id, DetectBufferType_::mpm, DetectBufferType_::name, DetectBufferType_::packet, DetectBufferType_::parent_id, res, SC_ERR_INVALID_SIGNATURE, SCCalloc, SCLogDebug, SCLogError, DetectBufferType_::SetupCallback, strlcpy(), DetectBufferType_::supports_transforms, DetectEngineTransforms::transforms, DetectBufferType_::transforms, and DetectBufferType_::ValidateCallback.
Referenced by DetectBufferGetActiveList().
DetectEngineBufferTypeGetDescriptionById()
const char * DetectEngineBufferTypeGetDescriptionById (const DetectEngineCtx * de_ctx, const int id)
Definition at line 1194 of file detect-engine.c.
References de_ctx, DetectBufferType_::description, and DetectEngineBufferTypeGetById().
DetectEngineBufferTypeGetNameById()
const char * DetectEngineBufferTypeGetNameById (const DetectEngineCtx * de_ctx, const int id)
Definition at line 1116 of file detect-engine.c.
References de_ctx, DetectEngineBufferTypeGetById(), and res.
Referenced by DumpPatterns(), EngineAnalysisRules2(), and SignatureIsIPOnly().
DetectEngineBufferTypeRegister()
int DetectEngineBufferTypeRegister (DetectEngineCtx * de_ctx, const char * name)
Definition at line 1173 of file detect-engine.c.
Referenced by DetectEngineFrameInspectEngineRegister(), and DetectEngineFrameMpmRegister().
DetectEngineBufferTypeRegisterWithFrameEngines()
int DetectEngineBufferTypeRegisterWithFrameEngines (DetectEngineCtx * de_ctx, const char * name, const int direction, const AppProto alproto, const uint8_t frame_type)
Definition at line 1139 of file detect-engine.c.
DetectEngineBufferTypeSupportsFrames()
void DetectEngineBufferTypeSupportsFrames (DetectEngineCtx * de_ctx, const char * name)
Definition at line 1212 of file detect-engine.c.
Referenced by DetectEngineFrameMpmRegister().
DetectEngineBufferTypeSupportsMpm()
void DetectEngineBufferTypeSupportsMpm (DetectEngineCtx * de_ctx, const char * name)
Definition at line 1228 of file detect-engine.c.
Referenced by DetectEngineFrameMpmRegister().
DetectEngineBufferTypeSupportsMpmGetById()
bool DetectEngineBufferTypeSupportsMpmGetById (const DetectEngineCtx * de_ctx, const int id)
Definition at line 1253 of file detect-engine.c.
References de_ctx, DetectEngineBufferTypeGetById(), DetectBufferType_::mpm, and SCLogDebug.
Referenced by DetectGetLastSMFromMpmLists(), and FastPatternSupportEnabledForSigMatchList().
DetectEngineBufferTypeSupportsPacket()
void DetectEngineBufferTypeSupportsPacket (DetectEngineCtx * de_ctx, const char * name)
Definition at line 1220 of file detect-engine.c.
DetectEngineBufferTypeSupportsPacketGetById()
bool DetectEngineBufferTypeSupportsPacketGetById (const DetectEngineCtx * de_ctx, const int id)
Definition at line 1244 of file detect-engine.c.
References de_ctx, DetectEngineBufferTypeGetById(), DetectBufferType_::packet, and SCLogDebug.
DetectEngineBufferTypeSupportsTransformations()
void DetectEngineBufferTypeSupportsTransformations (DetectEngineCtx * de_ctx, const char * name)
Definition at line 1236 of file detect-engine.c.
Referenced by DetectEngineFrameMpmRegister().
DetectEngineBufferTypeValidateTransform()
bool DetectEngineBufferTypeValidateTransform (DetectEngineCtx * de_ctx, int sm_list, const uint8_t * content, uint16_t content_len, const char ** namestr)
Check content byte array compatibility with transforms.
The "content" array is presented to the transforms so that each transform may validate that it's compatible with the transform.
When a transform indicates the byte array is incompatible, none of the subsequent transforms, if any, are invoked. This means the first positive validation result terminates the loop.
Parameters
de_ctx Detection engine context.
sm_list The SM list id.
content The byte array being validated
namestr returns the name of the transform that is incompatible with content.
Return values
true (false) If any of the transforms indicate the byte array is (is not) compatible.
Definition at line 1527 of file detect-engine.c.
References BUG_ON, DetectEngineTransforms::cnt, de_ctx, DetectEngineBufferTypeGetById(), SigTableElmt_::name, TransformData_::options, sigmatch_table, TransformData_::transform, DetectEngineTransforms::transforms, DetectBufferType_::transforms, and SigTableElmt_::TransformValidate.
Referenced by DetectContentSetup().
DetectEngineBumpVersion()
void DetectEngineBumpVersion (void)
Definition at line 3602 of file detect-engine.c.
DetectEngineCtxFree()
void DetectEngineCtxFree (DetectEngineCtx * de_ctx)
Free a DetectEngineCtx::
Parameters
de_ctx DetectEngineCtx:: to be freed
Definition at line 2445 of file detect-engine.c.
References de_ctx, DetectEngineFreeFastPatternList(), DetectParseDupSigHashFree(), MpmFactoryDeRegisterAllMpmCtxProfiles(), MpmStoreFree(), DetectEngineCtx_::profile_ctx, DetectEngineCtx_::profile_keyword_ctx, DetectEngineCtx_::profile_sgh_ctx, SCClassConfDeInitContext(), SCFree, SCProfilingKeywordDestroyCtx(), SCProfilingPrefilterDestroyCtx(), SCProfilingRuleDestroyCtx(), SCProfilingSghDestroyCtx(), SCRConfDeInitContext(), SCSigSignatureOrderingModuleCleanup(), DetectEngineCtx_::sig_array, SigCleanSignatures(), SigGroupCleanup(), SigGroupHeadHashFree(), DetectEngineCtx_::spm_global_thread_ctx, SpmDestroyGlobalThreadCtx(), and ThresholdContextDestroy().
Referenced by UTHGenericTest(), UTHPacketMatchSig(), UTHPacketMatchSigMpm(), and UTHParseSignature().
DetectEngineCtxInit()
DetectEngineCtx * DetectEngineCtxInit (void)
Definition at line 2406 of file detect-engine.c.
Referenced by DetectEngineCtxInitWithPrefix(), UTHGenericTest(), UTHPacketMatchSig(), UTHPacketMatchSigMpm(), and UTHParseSignature().
DetectEngineCtxInitStubForDD()
DetectEngineCtx * DetectEngineCtxInitStubForDD (void)
Definition at line 2401 of file detect-engine.c.
DetectEngineCtxInitStubForMT()
DetectEngineCtx * DetectEngineCtxInitStubForMT (void)
Definition at line 2396 of file detect-engine.c.
DetectEngineCtxInitWithPrefix()
DetectEngineCtx * DetectEngineCtxInitWithPrefix (const char * prefix)
Definition at line 2411 of file detect-engine.c.
References DetectEngineCtxInit().
DetectEngineDeReference()
void DetectEngineDeReference (DetectEngineCtx ** de_ctx)
Definition at line 4308 of file detect-engine.c.
References BUG_ON, and de_ctx.
DetectEngineEnabled()
int DetectEngineEnabled (void)
Check if detection is enabled.
Return values
bool true or false
Definition at line 3578 of file detect-engine.c.
DetectEngineFrameInspectEngineRegister()
void DetectEngineFrameInspectEngineRegister (DetectEngineCtx * de_ctx, const char * name, int dir, InspectionBufferFrameInspectFunc Callback, AppProto alproto, uint8_t type)
register inspect engine at start up time
Note
errors are fatal
Definition at line 420 of file detect-engine.c.
References DetectEngineFrameInspectionEngine::alproto, BUG_ON, DetectEngineFrameInspectionEngine::Callback, de_ctx, DETECT_SM_LIST_MATCH, DetectEngineBufferTypeRegister(), DetectEngineFrameInspectionEngine::dir, FatalError, DetectEngineCtx_::frame_inspect_engines, SC_ERR_INITIALIZATION, SC_ERR_INVALID_ARGUMENTS, SCCalloc, SCLogError, SIG_FLAG_TOSERVER, DetectEngineFrameInspectionEngine::sm_list, DetectEngineFrameInspectionEngine::sm_list_base, type, DetectEngineFrameInspectionEngine::type, unlikely, and DetectEngineFrameInspectionEngine::v1.
DetectEngineGetByTenantId()
DetectEngineCtx * DetectEngineGetByTenantId (int tenant_id)
Definition at line 4282 of file detect-engine.c.
DetectEngineGetCurrent()
DetectEngineCtx * DetectEngineGetCurrent (void)
Definition at line 3611 of file detect-engine.c.
Referenced by DetectEngineThreadCtxInit().
DetectEngineGetEventInfo()
int DetectEngineGetEventInfo (const char * event_name, int * event_id, AppLayerEventType * event_type)
Definition at line 4652 of file detect-engine.c.
References APP_LAYER_EVENT_TYPE_TRANSACTION, det_ctx_event_table, SC_ERR_INVALID_ENUM_MAP, SCLogError, and SCMapEnumNameToValue().
DetectEngineGetEvents()
AppLayerDecoderEvents * DetectEngineGetEvents (DetectEngineThreadCtx * det_ctx)
Definition at line 4647 of file detect-engine.c.
References DetectEngineThreadCtx_::decoder_events.
DetectEngineGetVersion()
uint32_t DetectEngineGetVersion (void)
Definition at line 3592 of file detect-engine.c.
References version.
DetectEngineInspectBufferGeneric()
uint8_t DetectEngineInspectBufferGeneric (DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, const DetectEngineAppInspectionEngine * engine, const Signature * s, Flow * f, uint8_t flags, void * alstate, void * txv, uint64_t tx_id)
Do the content inspection & validation for a signature.
Parameters
de_ctx Detection engine context
det_ctx Detection engine thread context
s Signature to inspect
f Flow
flags app layer flags
state App layer state
Return values
0 no match.
1 match.
2 Sig can't match.
Definition at line 1994 of file detect-engine.c.
References Flow_::alproto, AppLayerParserGetStateProgress(), DetectEngineThreadCtx_::buffer_offset, de_ctx, DETECT_CI_FLAGS_END, DETECT_CI_FLAGS_START, DETECT_ENGINE_CONTENT_INSPECTION_MODE_STATE, DETECT_ENGINE_INSPECT_SIG_CANT_MATCH, DETECT_ENGINE_INSPECT_SIG_MATCH, DETECT_ENGINE_INSPECT_SIG_NO_MATCH, DetectEngineContentInspection(), DetectEngineThreadCtx_::discontinue_matching, flags, InspectionBuffer::flags, DetectEngineAppInspectionEngine_::GetData, InspectionBuffer::inspect, InspectionBuffer::inspect_len, InspectionBuffer::inspect_offset, DetectEngineThreadCtx_::inspection_recursion_counter, DetectEngineAppInspectionEngine_::mpm, offset, DetectEngineAppInspectionEngine_::progress, Flow_::proto, SCLogDebug, DetectEngineAppInspectionEngine_::sm_list, DetectEngineAppInspectionEngine_::smd, DetectEngineAppInspectionEngine_::transforms, unlikely, and DetectEngineAppInspectionEngine_::v2.
DetectEngineInspectGenericList()
uint8_t DetectEngineInspectGenericList (DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, const struct DetectEngineAppInspectionEngine_ * engine, const Signature * s, Flow * f, uint8_t flags, void * alstate, void * txv, uint64_t tx_id)
Do the content inspection & validation for a signature.
Parameters
de_ctx Detection engine context
det_ctx Detection engine thread context
s Signature to inspect
sm SigMatch to inspect
f Flow
flags app layer flags
state App layer state
Return values
0 no match
1 match
Definition at line 1951 of file detect-engine.c.
References SigMatchData_::ctx, DETECT_ENGINE_INSPECT_SIG_CANT_MATCH, DETECT_ENGINE_INSPECT_SIG_MATCH, DETECT_ENGINE_INSPECT_SIG_NO_MATCH, flags, SigMatchData_::is_last, KEYWORD_PROFILING_END, KEYWORD_PROFILING_START, SCLogDebug, sigmatch_table, DetectEngineAppInspectionEngine_::smd, and SigMatchData_::type.
DetectEngineInspectPktBufferGeneric()
int DetectEngineInspectPktBufferGeneric (DetectEngineThreadCtx * det_ctx, const DetectEnginePktInspectionEngine * engine, const Signature * s, Packet * p, uint8_t * _alert_flags)
Do the content inspection & validation for a signature.
Parameters
de_ctx Detection engine context
det_ctx Detection engine thread context
s Signature to inspect
p Packet
Return values
0 no match.
1 match.
Definition at line 2057 of file detect-engine.c.
References DetectEngineThreadCtx_::buffer_offset, DetectEngineThreadCtx_::de_ctx, DETECT_CI_FLAGS_END, DETECT_CI_FLAGS_START, DETECT_ENGINE_CONTENT_INSPECTION_MODE_HEADER, DETECT_ENGINE_INSPECT_SIG_MATCH, DETECT_ENGINE_INSPECT_SIG_NO_MATCH, DetectEngineContentInspection(), DetectEngineThreadCtx_::discontinue_matching, InspectionBuffer::flags, Packet_::flow, DetectEnginePktInspectionEngine::GetData, InspectionBuffer::inspect, InspectionBuffer::inspect_len, DetectEngineThreadCtx_::inspection_recursion_counter, DetectEnginePktInspectionEngine::mpm, offset, SCLogDebug, DetectEnginePktInspectionEngine::sm_list, DetectEnginePktInspectionEngine::smd, DetectEnginePktInspectionEngine::transforms, unlikely, and DetectEnginePktInspectionEngine::v1.
DetectEngineLoadTenantBlocking()
int DetectEngineLoadTenantBlocking (uint32_t tenant_id, const char * yaml)
Load a tenant and wait for loading to complete.
Definition at line 3837 of file detect-engine.c.
DetectEngineMoveToFreeList()
int DetectEngineMoveToFreeList (DetectEngineCtx * de_ctx)
Definition at line 4348 of file detect-engine.c.
DetectEngineMTApply()
int DetectEngineMTApply (void)
Definition at line 4542 of file detect-engine.c.
DetectEngineMultiTenantEnabled()
int DetectEngineMultiTenantEnabled (void)
TODO locking? Not needed if this is a one time setting at startup
Definition at line 3643 of file detect-engine.c.
DetectEngineMultiTenantSetup()
int DetectEngineMultiTenantSetup (void)
setup multi-detect / multi-tenancy
See if MT is enabled. If so, setup the selector, tenants and mappings. Tenants and mappings are optional, and can also dynamically be added and removed from the unix socket.
Definition at line 3983 of file detect-engine.c.
References TENANT_SELECTOR_UNKNOWN.
DetectEngineMustParseMetadata()
int DetectEngineMustParseMetadata (void)
Definition at line 4607 of file detect-engine.c.
Referenced by DetectMetadataHashInit().
DetectEnginePktInspectionRun()
bool DetectEnginePktInspectionRun (ThreadVars * tv, DetectEngineThreadCtx * det_ctx, const Signature * s, Flow * f, Packet * p, uint8_t * alert_flags)
Definition at line 1809 of file detect-engine.c.
References Signature_::id, DetectEnginePktInspectionEngine::next, Signature_::pkt_inspect, SCEnter, and SCLogDebug.
DetectEnginePktInspectionSetup()
int DetectEnginePktInspectionSetup (Signature * s)
Definition at line 1857 of file detect-engine.c.
References DETECT_SM_LIST_PMATCH, Signature_::init_data, SignatureInitData_::init_flags, SIG_FLAG_INIT_STATE_MATCH, and Signature_::sm_arrays.
DetectEnginePruneFreeList()
void DetectEnginePruneFreeList (void)
Definition at line 4399 of file detect-engine.c.
DetectEngineReference()
DetectEngineCtx * DetectEngineReference (DetectEngineCtx * de_ctx)
Definition at line 3634 of file detect-engine.c.
References de_ctx, and DetectEngineCtx_::ref_cnt.
Referenced by DetectEngineThreadCtxInitForReload().
DetectEngineRegisterTests()
void DetectEngineRegisterTests (void)
Definition at line 4871 of file detect-engine.c.
References UtRegisterTest().
DetectEngineReload()
int DetectEngineReload (const SCInstance * suri)
Reload the detection engine.
Parameters
filename YAML file to load for the detect config
Return values
-1 error
0 ok
Definition at line 4438 of file detect-engine.c.
References SCInstance_::conf_filename, and SCLogNotice.
DetectEngineReloadIsIdle()
int DetectEngineReloadIsIdle (void)
Definition at line 1927 of file detect-engine.c.
References SCMutexLock.
DetectEngineReloadIsStart()
int DetectEngineReloadIsStart (void)
Definition at line 1907 of file detect-engine.c.
References SCMutexLock.
DetectEngineReloadSetIdle()
void DetectEngineReloadSetIdle (void)
Definition at line 1919 of file detect-engine.c.
References SCMutexLock.
DetectEngineReloadStart()
int DetectEngineReloadStart (void)
Definition at line 1893 of file detect-engine.c.
References SCMutexLock.
DetectEngineReloadTenantBlocking()
int DetectEngineReloadTenantBlocking (uint32_t tenant_id, const char * yaml, int reload_cnt)
Reload a tenant and wait for loading to complete.
Definition at line 3851 of file detect-engine.c.
DetectEngineResetMaxSigId()
void DetectEngineResetMaxSigId (DetectEngineCtx * de_ctx)
Definition at line 2827 of file detect-engine.c.
References de_ctx, and DetectEngineCtx_::signum.
Referenced by SigCleanSignatures().
DetectEngineSetEvent()
void DetectEngineSetEvent (DetectEngineThreadCtx * det_ctx, uint8_t e)
Definition at line 4641 of file detect-engine.c.
References AppLayerDecoderEventsSetEventRaw(), DetectEngineThreadCtx_::decoder_events, and DetectEngineThreadCtx_::events.
Referenced by FileSwfDecompression(), FileSwfLzmaDecompression(), FileSwfZlibDecompression(), and InspectionBufferMultipleForListGet().
DetectEngineSetParseMetadata()
void DetectEngineSetParseMetadata (void)
Definition at line 4597 of file detect-engine.c.
DetectEngineTentantRegisterLivedev()
int DetectEngineTentantRegisterLivedev (uint32_t tenant_id, int device_id)
Definition at line 4250 of file detect-engine.c.
DetectEngineTentantRegisterPcapFile()
int DetectEngineTentantRegisterPcapFile (uint32_t tenant_id)
Definition at line 4265 of file detect-engine.c.
References SCLogInfo, and TENANT_SELECTOR_DIRECT.
DetectEngineTentantRegisterVlanId()
int DetectEngineTentantRegisterVlanId (uint32_t tenant_id, uint16_t vlan_id)
Definition at line 4255 of file detect-engine.c.
DetectEngineTentantUnregisterPcapFile()
int DetectEngineTentantUnregisterPcapFile (uint32_t tenant_id)
Definition at line 4271 of file detect-engine.c.
References SCLogInfo, and TENANT_SELECTOR_DIRECT.
DetectEngineTentantUnregisterVlanId()
int DetectEngineTentantUnregisterVlanId (uint32_t tenant_id, uint16_t vlan_id)
Definition at line 4260 of file detect-engine.c.
DetectEngineThreadCtxDeinit()
TmEcode DetectEngineThreadCtxDeinit (ThreadVars * tv, void * data)
Definition at line 3368 of file detect-engine.c.
References HashTableFree(), DetectEngineThreadCtx_::mt_det_ctxs_hash, SC_ERR_INVALID_ARGUMENTS, SCLogWarning, and TM_ECODE_OK.
Referenced by DetectEngineThreadCtxInit(), UTHMatchPackets(), UTHMatchPacketsWithResults(), UTHPacketMatchSig(), and UTHPacketMatchSigMpm().
DetectEngineThreadCtxInfo()
void DetectEngineThreadCtxInfo (ThreadVars * t, DetectEngineThreadCtx * det_ctx)
Definition at line 3386 of file detect-engine.c.
References DetectEngineThreadCtx_::de_ctx, DetectEngineCtx_::mpm_matcher, DetectEngineThreadCtx_::mtc, DetectEngineThreadCtx_::mtcu, and PatternMatchThreadPrint().
DetectEngineThreadCtxInit()
TmEcode DetectEngineThreadCtxInit (ThreadVars * tv, void * initdata, void ** data)
initialize thread specific detection engine context
Note
there is a special case when using delayed detect. In this case the function is called twice per thread. The first time the rules are not yet loaded. de_ctx->delayed_detect_initialized will be 0. The 2nd time they will be loaded. de_ctx->delayed_detect_initialized will be 1. This is needed to do the per thread counter registration before the packet runtime starts. In delayed detect mode, the first call will return a NULL ptr through the data ptr.
Parameters
tv ThreadVars for this thread
initdata pointer to de_ctx
data[out] pointer to store our thread detection ctx
Return values
TM_ECODE_OK if all went well
TM_ECODE_FAILED on serious errors
alert counter setup
Definition at line 3154 of file detect-engine.c.
References DetectEngineThreadCtx_::de_ctx, DETECT_ENGINE_TYPE_NORMAL, DETECT_ENGINE_TYPE_TENANT, DetectEngineGetCurrent(), DetectEngineThreadCtxDeinit(), RunmodeIsUnittests(), SCMalloc, TM_ECODE_FAILED, DetectEngineThreadCtx_::tv, tv, DetectEngineCtx_::type, and unlikely.
Referenced by UTHMatchPackets(), UTHMatchPacketsWithResults(), UTHPacketMatchSig(), and UTHPacketMatchSigMpm().
DetectEngineThreadCtxInitForReload()
DetectEngineThreadCtx * DetectEngineThreadCtxInitForReload (ThreadVars * tv, DetectEngineCtx * new_de_ctx, int mt)
alert counter setup
Definition at line 3219 of file detect-engine.c.
References DetectEngineThreadCtx_::de_ctx, DETECT_ENGINE_TYPE_NORMAL, DETECT_ENGINE_TYPE_TENANT, DetectEngineReference(), SCFree, SCMalloc, DetectEngineCtx_::tenant_id, DetectEngineThreadCtx_::tenant_id, DetectEngineThreadCtx_::tv, tv, DetectEngineCtx_::type, and unlikely.
DetectEngineUnsetParseMetadata()
void DetectEngineUnsetParseMetadata (void)
Definition at line 4602 of file detect-engine.c.
DetectFrameInspectEngineRegister()
void DetectFrameInspectEngineRegister (const char * name, int dir, InspectionBufferFrameInspectFunc Callback, AppProto alproto, uint8_t type)
register inspect engine at start up time
Note
errors are fatal
Definition at line 179 of file detect-engine.c.
References DetectEngineFrameInspectionEngine::alproto, BUG_ON, DetectEngineFrameInspectionEngine::Callback, DETECT_SM_LIST_MATCH, DetectBufferTypeGetByName(), DetectBufferTypeRegister(), DetectEngineFrameInspectionEngine::dir, FatalError, SC_ERR_INITIALIZATION, SC_ERR_INVALID_ARGUMENTS, SCCalloc, SCLogError, SIG_FLAG_TOSERVER, DetectEngineFrameInspectionEngine::sm_list, DetectEngineFrameInspectionEngine::sm_list_base, type, DetectEngineFrameInspectionEngine::type, unlikely, and DetectEngineFrameInspectionEngine::v1.
DetectPktInspectEngineRegister()
void DetectPktInspectEngineRegister (const char * name, InspectionBufferGetPktDataPtr GetPktData, InspectionBufferPktInspectFunc Callback)
register inspect engine at start up time
Note
errors are fatal
Definition at line 136 of file detect-engine.c.
References BUG_ON, DetectEnginePktInspectionEngine::Callback, DETECT_SM_LIST_MATCH, DetectBufferTypeGetByName(), DetectBufferTypeRegister(), FatalError, DetectEnginePktInspectionEngine::GetData, SC_ERR_INITIALIZATION, SC_ERR_INVALID_ARGUMENTS, SCCalloc, SCLogError, DetectEnginePktInspectionEngine::sm_list, DetectEnginePktInspectionEngine::sm_list_base, unlikely, and DetectEnginePktInspectionEngine::v1.
DetectRegisterThreadCtxFuncs()
int DetectRegisterThreadCtxFuncs (DetectEngineCtx * de_ctx, const char * name, void *(*)(void *) InitFunc, void * data, void(*)(void *) FreeFunc, int mode)
Register Thread keyword context Funcs.
Parameters
de_ctx detection engine to register in
name keyword name for error printing
InitFunc function ptr
data keyword init data to pass to Func. Can be NULL.
FreeFunc function ptr
mode 0 normal (ctx per keyword instance) 1 shared (one ctx per det_ct)
Return values
id for retrieval of ctx at runtime
-1 on error
Note
make sure "data" remains valid and it free'd elsewhere. It's recommended to store it in the keywords global ctx so that it's freed when the de_ctx is freed.
Definition at line 3432 of file detect-engine.c.
References BUG_ON, de_ctx, HashListTableInit(), and DetectEngineCtx_::keyword_hash.
DetectRegisterThreadCtxGlobalFuncs()
int DetectRegisterThreadCtxGlobalFuncs (const char * name, void *(*)(void *) InitFunc, void * data, void(*)(void *) FreeFunc)
Register Thread keyword context Funcs (Global)
IDs stay static over reloads and between tenants
Parameters
name keyword name for error printing
InitFunc function ptr
FreeFunc function ptr
Return values
id for retrieval of ctx at runtime
-1 on error
Definition at line 3522 of file detect-engine.c.
References BUG_ON.
DetectSigmatchListEnumToString()
const char * DetectSigmatchListEnumToString (enum DetectSigmatchListEnum type)
Definition at line 4612 of file detect-engine.c.
References DETECT_SM_LIST_BASE64_DATA, DETECT_SM_LIST_MATCH, DETECT_SM_LIST_MAX, DETECT_SM_LIST_PMATCH, DETECT_SM_LIST_POSTMATCH, DETECT_SM_LIST_SUPPRESS, DETECT_SM_LIST_THRESHOLD, DETECT_SM_LIST_TMATCH, and type.
DetectThreadCtxGetGlobalKeywordThreadCtx()
void * DetectThreadCtxGetGlobalKeywordThreadCtx (DetectEngineThreadCtx * det_ctx, int id)
Retrieve thread local keyword ctx by id.
Parameters
det_ctx detection engine thread ctx to retrieve the ctx from
id id of the ctx returned by DetectRegisterThreadCtxInitFunc at keyword init.
Return values
ctx or NULL on error
Definition at line 3566 of file detect-engine.c.
References DetectEngineThreadCtx_::global_keyword_ctxs_array, and DetectEngineThreadCtx_::global_keyword_ctxs_size.
Referenced by HttpHeaderGetBufferSpace().
DetectThreadCtxGetKeywordThreadCtx()
void * DetectThreadCtxGetKeywordThreadCtx (DetectEngineThreadCtx * det_ctx, int id)
Retrieve thread local keyword ctx by id.
Parameters
det_ctx detection engine thread ctx to retrieve the ctx from
id id of the ctx returned by DetectRegisterThreadCtxInitFunc at keyword init.
Return values
ctx or NULL on error
Definition at line 3502 of file detect-engine.c.
References DetectEngineThreadCtx_::keyword_ctxs_array, and DetectEngineThreadCtx_::keyword_ctxs_size.
Referenced by DetectPcrePayloadMatch().
DetectUnregisterThreadCtxFuncs()
int DetectUnregisterThreadCtxFuncs (DetectEngineCtx * de_ctx, void * data, const char * name)
Remove Thread keyword context registration.
Parameters
de_ctx detection engine to deregister from
det_ctx detection engine thread context to deregister from
data keyword init data to pass to Func. Can be NULL.
name keyword name for error printing
Return values
1 Item unregistered
0 otherwise
Note
make sure "data" remains valid and it free'd elsewhere. It's recommended to store it in the keywords global ctx so that it's freed when the de_ctx is freed.
Definition at line 3484 of file detect-engine.c.
References DetectEngineThreadKeywordCtxItem_::data, de_ctx, HashListTableRemove(), and DetectEngineCtx_::keyword_hash.
InspectionBufferApplyTransforms()
void InspectionBufferApplyTransforms (InspectionBuffer * buffer, const DetectEngineTransforms * transforms)
Definition at line 1552 of file detect-engine.c.
References BUG_ON, DETECT_TRANSFORMS_MAX, TransformData_::options, SCLogDebug, sigmatch_table, TransformData_::transform, SigTableElmt_::Transform, and DetectEngineTransforms::transforms.
Referenced by InspectionBufferSetupMulti().
InspectionBufferCheckAndExpand()
void InspectionBufferCheckAndExpand (InspectionBuffer * buffer, uint32_t min_size)
make sure that the buffer has at least 'min_size' bytes Expand the buffer if necessary
Definition at line 1480 of file detect-engine.c.
References InspectionBuffer::buf, likely, SCRealloc, and InspectionBuffer::size.
Referenced by FileSwfDecompression(), and InspectionBufferCopy().
InspectionBufferClean()
void InspectionBufferClean (DetectEngineThreadCtx * det_ctx)
Definition at line 1343 of file detect-engine.c.
References DetectEngineThreadCtx_::buffers, InspectionBufferMultipleForList::init, InspectionBuffer::inspect, DetectEngineThreadCtx_::inspect, InspectionBufferMultipleForList::inspection_buffers, InspectionBufferMultipleForList::max, DetectEngineThreadCtx_::multi_inspect, DetectEngineThreadCtx_::to_clear_idx, and DetectEngineThreadCtx_::to_clear_queue.
InspectionBufferCopy()
void InspectionBufferCopy (InspectionBuffer * buffer, uint8_t * buf, uint32_t buf_len)
Definition at line 1497 of file detect-engine.c.
References InspectionBuffer::buf, InspectionBuffer::inspect, InspectionBuffer::inspect_len, InspectionBufferCheckAndExpand(), MIN, and InspectionBuffer::size.
InspectionBufferFree()
void InspectionBufferFree (InspectionBuffer * buffer)
Definition at line 1468 of file detect-engine.c.
References InspectionBuffer::buf, and SCFree.
InspectionBufferGet()
InspectionBuffer * InspectionBufferGet (DetectEngineThreadCtx * det_ctx, const int list_id)
Definition at line 1369 of file detect-engine.c.
References DetectEngineThreadCtx_::buffers, and DetectEngineThreadCtx_::inspect.
Referenced by InspectionBufferSetup().
InspectionBufferInit()
void InspectionBufferInit (InspectionBuffer * buffer, uint32_t initial_size)
Definition at line 1426 of file detect-engine.c.
References InspectionBuffer::buf, SCCalloc, and InspectionBuffer::size.
InspectionBufferMultipleForListGet()
InspectionBuffer * InspectionBufferMultipleForListGet (DetectEngineThreadCtx * det_ctx, const int list_id, const uint32_t local_id)
for a InspectionBufferMultipleForList get a InspectionBuffer
Parameters
fb the multiple buffer array
local_id the index to get a buffer
buffer the inspect buffer or NULL in case of error
Definition at line 1389 of file detect-engine.c.
References DETECT_EVENT_TOO_MANY_BUFFERS, DetectEngineSetEvent(), and unlikely.
Referenced by DetectFrame2InspectBuffer().
InspectionBufferSetup()
void InspectionBufferSetup (DetectEngineThreadCtx * det_ctx, const int list_id, InspectionBuffer * buffer, const uint8_t * data, const uint32_t data_len)
setup the buffer with our initial data
Definition at line 1450 of file detect-engine.c.
References DEBUG_VALIDATE_BUG_ON, InspectionBuffer::inspect, DetectEngineThreadCtx_::inspect, InspectionBuffer::inspect_len, InspectionBufferGet(), InspectionBuffer::len, InspectionBuffer::orig, InspectionBuffer::orig_len, DetectEngineThreadCtx_::to_clear_idx, and DetectEngineThreadCtx_::to_clear_queue.
InspectionBufferSetupMulti()
void InspectionBufferSetupMulti (InspectionBuffer * buffer, const DetectEngineTransforms * transforms, const uint8_t * data, const uint32_t data_len)
setup the buffer with our initial data
Definition at line 1436 of file detect-engine.c.
References DEBUG_VALIDATE_BUG_ON, InspectionBuffer::inspect, InspectionBuffer::inspect_len, InspectionBufferApplyTransforms(), InspectionBuffer::len, InspectionBuffer::orig, and InspectionBuffer::orig_len.
Variable Documentation
det_ctx_event_table
SCEnumCharMap det_ctx_event_table[]
Initial value:
= {
    { "TEST", DET_CTX_EVENT_TEST },
    { "NO_MEMORY", FILE_DECODER_EVENT_NO_MEM },
    { "INVALID_SWF_LENGTH", FILE_DECODER_EVENT_INVALID_SWF_LENGTH },
    { "INVALID_SWF_VERSION", FILE_DECODER_EVENT_INVALID_SWF_VERSION },
    { "Z_DATA_ERROR", FILE_DECODER_EVENT_Z_DATA_ERROR },
    { "Z_STREAM_ERROR", FILE_DECODER_EVENT_Z_STREAM_ERROR },
    { "Z_BUF_ERROR", FILE_DECODER_EVENT_Z_BUF_ERROR },
    { "Z_UNKNOWN_ERROR", FILE_DECODER_EVENT_Z_UNKNOWN_ERROR },
    { "LZMA_DECODER_ERROR", FILE_DECODER_EVENT_LZMA_DECODER_ERROR },
    { "LZMA_MEMLIMIT_ERROR", FILE_DECODER_EVENT_LZMA_MEMLIMIT_ERROR },
    { "LZMA_OPTIONS_ERROR", FILE_DECODER_EVENT_LZMA_OPTIONS_ERROR },
    { "LZMA_FORMAT_ERROR", FILE_DECODER_EVENT_LZMA_FORMAT_ERROR },
    { "LZMA_DATA_ERROR", FILE_DECODER_EVENT_LZMA_DATA_ERROR },
    { "LZMA_BUF_ERROR", FILE_DECODER_EVENT_LZMA_BUF_ERROR },
    { "LZMA_UNKNOWN_ERROR", FILE_DECODER_EVENT_LZMA_UNKNOWN_ERROR },
    {
            "TOO_MANY_BUFFERS",
            DETECT_EVENT_TOO_MANY_BUFFERS,
    },
    { NULL, -1 },
}
Definition at line 108 of file detect-engine.c.
Referenced by DetectEngineGetEventInfo().