suricata: /Users/jlu/suricata/src/detect-ipproto.c File Reference
detect-ipproto.c File Reference
#include "suricata-common.h"
#include "decode.h"
#include "detect.h"
#include "detect-ipproto.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-engine-build.h"
#include "detect-engine-siggroup.h"
#include "detect-engine-address.h"
#include "util-byte.h"
#include "util-proto-name.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-debug.h"
Macros
#define PARSE_REGEX "^([!<>]?)\\s*([^\\s]+)$"
Regex for parsing our options.
Functions
void DetectIPProtoRegister (void)
Registration function for ip_proto keyword.
void DetectIPProtoRemoveAllSMs (DetectEngineCtx *de_ctx, Signature *s)
Detailed Description
Author
Brian Rectanus brect.nosp@m.anu@.nosp@m.gmail.nosp@m..com
Implements the ip_proto keyword
Definition in file detect-ipproto.c.
Macro Definition Documentation
PARSE_REGEX
#define PARSE_REGEX "^([!<>]?)\\s*([^\\s]+)$"
Regex for parsing our options.
Definition at line 50 of file detect-ipproto.c.
Function Documentation
DetectIPProtoRegister()
void DetectIPProtoRegister (void)
Registration function for ip_proto keyword.
Definition at line 60 of file detect-ipproto.c.
References SigTableElmt_::desc, DETECT_IPPROTO, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
DetectIPProtoRemoveAllSMs()
void DetectIPProtoRemoveAllSMs (DetectEngineCtx * de_ctx, Signature * s)
Definition at line 430 of file detect-ipproto.c.
References de_ctx, DETECT_IPPROTO, DETECT_SM_LIST_MATCH, Signature_::init_data, SigMatch_::next, SigMatchFree(), SigMatchRemoveSMFromList(), SignatureInitData_::smlists, and SigMatch_::type.