suricata: /Users/jlu/suricata/src/detect-engine-alert.c File Reference
detect-engine-alert.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "detect-engine-alert.h"
#include "detect-engine-threshold.h"
#include "detect-engine-tag.h"
#include "decode.h"
#include "flow.h"
#include "flow-private.h"
#include "util-profiling.h"
#include "util-validate.h"
#include "tests/detect-engine-alert.c"
Functions
void PacketAlertTagInit (void)
PacketAlert * PacketAlertGetTag (void)
int PacketAlertCheck (Packet *p, uint32_t sid)
Check if a certain sid alerted, this is used in the test functions.
void AlertQueueInit (DetectEngineThreadCtx *det_ctx)
void AlertQueueFree (DetectEngineThreadCtx *det_ctx)
void AlertQueueAppend (DetectEngineThreadCtx *det_ctx, const Signature *s, Packet *p, uint64_t tx_id, uint8_t alert_flags)
Append signature to local packet alert queue for later preprocessing.
void PacketAlertFinalize (DetectEngineCtx *de_ctx, DetectEngineThreadCtx *det_ctx, Packet *p)
Check the threshold of the sigs that match, set actions, break on pass action This function iterate the packet alerts array, removing those that didn't match the threshold, and those that match after a signature with the action "pass". The array is sorted by action priority/order.
Function Documentation
AlertQueueAppend()
void AlertQueueAppend (DetectEngineThreadCtx * det_ctx, const Signature * s, Packet * p, uint64_t tx_id, uint8_t alert_flags)
Append signature to local packet alert queue for later preprocessing.
Definition at line 273 of file detect-engine-alert.c.
References PacketAlert_::action, Signature_::action, ACTION_DROP, Packet_::alerts, and PacketAlerts_::drop.
AlertQueueFree()
void AlertQueueFree (DetectEngineThreadCtx * det_ctx)
Definition at line 225 of file detect-engine-alert.c.
References DetectEngineThreadCtx_::alert_queue, DetectEngineThreadCtx_::alert_queue_capacity, and SCFree.
AlertQueueInit()
void AlertQueueInit (DetectEngineThreadCtx * det_ctx)
Definition at line 212 of file detect-engine-alert.c.
References DetectEngineThreadCtx_::alert_queue, DetectEngineThreadCtx_::alert_queue_capacity, DetectEngineThreadCtx_::alert_queue_size, FatalError, packet_alert_max, SC_ERR_MEM_ALLOC, SCCalloc, and SCLogDebug.
PacketAlertCheck()
int PacketAlertCheck (Packet * p, uint32_t sid)
Check if a certain sid alerted, this is used in the test functions.
Parameters
p Packet on which we want to check if the signature alerted or not
sid Signature id of the signature that has to be checked for a match
Return values
match A value > 0 on a match; 0 on no match
Definition at line 142 of file detect-engine-alert.c.
References PacketAlerts_::alerts, Packet_::alerts, PacketAlerts_::cnt, Signature_::id, and PacketAlert_::s.
Referenced by UTHCheckPacketMatchResults(), UTHPacketMatchSig(), and UTHPacketMatchSigMpm().
PacketAlertFinalize()
void PacketAlertFinalize (DetectEngineCtx * de_ctx, DetectEngineThreadCtx * det_ctx, Packet * p)
Check the threshold of the sigs that match, set actions, break on pass action This function iterate the packet alerts array, removing those that didn't match the threshold, and those that match after a signature with the action "pass". The array is sorted by action priority/order.
Parameters
de_ctx detection engine context
det_ctx detection engine thread context
p pointer to the packet
Definition at line 348 of file detect-engine-alert.c.
References DetectEngineThreadCtx_::alert_queue, DetectEngineThreadCtx_::alert_queue_size, and SCEnter.
PacketAlertGetTag()
PacketAlert * PacketAlertGetTag (void)
Definition at line 58 of file detect-engine-alert.c.
PacketAlertTagInit()
void PacketAlertTagInit (void)
Definition at line 42 of file detect-engine-alert.c.