suricata: /Users/jlu/suricata/src/detect-bytemath.c File Reference
detect-bytemath.c File Reference
#include "suricata-common.h"
#include "threads.h"
#include "decode.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-engine-state.h"
#include "detect-engine-build.h"
#include "detect-content.h"
#include "detect-pcre.h"
#include "detect-byte.h"
#include "detect-bytemath.h"
#include "app-layer-parser.h"
#include "app-layer-protos.h"
#include "rust-bindings.h"
#include "flow.h"
#include "flow-var.h"
#include "flow-util.h"
#include "util-byte.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-spm.h"
Macros
#define DETECT_BYTEMATH_ENDIAN_DEFAULT (uint8_t) BigEndian
#define DETECT_BYTEMATH_BASE_DEFAULT (uint8_t) BaseDec
Functions
void DetectBytemathRegister (void)
Registers the keyword handlers for the "byte_math" keyword.
int DetectByteMathDoMatch (DetectEngineThreadCtx *det_ctx, const SigMatchData *smd, const Signature *s, const uint8_t *payload, uint16_t payload_len, uint64_t rvalue, uint64_t *value, uint8_t endian)
SigMatch * DetectByteMathRetrieveSMVar (const char *arg, const Signature *s)
Lookup the SigMatch for a named byte_math variable.
Detailed Description
Author
Jeff Lucovsky jeff@.nosp@m.luco.nosp@m.vsky..nosp@m.org
Definition in file detect-bytemath.c.
Macro Definition Documentation
DETECT_BYTEMATH_BASE_DEFAULT
#define DETECT_BYTEMATH_BASE_DEFAULT (uint8_t) BaseDec
Definition at line 64 of file detect-bytemath.c.
DETECT_BYTEMATH_ENDIAN_DEFAULT
#define DETECT_BYTEMATH_ENDIAN_DEFAULT (uint8_t) BigEndian
Definition at line 63 of file detect-bytemath.c.
Function Documentation
DetectByteMathDoMatch()
int DetectByteMathDoMatch (DetectEngineThreadCtx * det_ctx, const SigMatchData * smd, const Signature * s, const uint8_t * payload, uint16_t payload_len, uint64_t rvalue, uint64_t * value, uint8_t endian)
Definition at line 79 of file detect-bytemath.c.
References DetectEngineThreadCtx_::buffer_offset, BUG_ON, BYTE_BIG_ENDIAN, BYTE_LITTLE_ENDIAN, ByteExtractStringUint64(), ByteExtractUint64(), SigMatchData_::ctx, len, payload_len, and SCLogDebug.
DetectBytemathRegister()
void DetectBytemathRegister (void)
Registers the keyword handlers for the "byte_math" keyword.
Definition at line 68 of file detect-bytemath.c.
References DETECT_BYTEMATH, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::Setup, and sigmatch_table.
Referenced by SigTableSetup().
DetectByteMathRetrieveSMVar()
SigMatch * DetectByteMathRetrieveSMVar (const char * arg, const Signature * s)
Lookup the SigMatch for a named byte_math variable.
Parameters
arg The name of the byte_math variable to lookup.
s Pointer the signature to look in.
Return values
A pointer to the SigMatch if found, otherwise NULL.
Definition at line 403 of file detect-bytemath.c.
References Signature_::init_data, and SignatureInitData_::smlists_array_size.
Referenced by DetectByteRetrieveSMVar().