suricata: /Users/jlu/suricata/src/detect-engine-profile.h File Reference
detect-engine-profile.h File Reference
Functions
void RulesDumpTxMatchArray (const DetectEngineThreadCtx *det_ctx, const SigGroupHead *sgh, const Packet *p, const uint64_t tx_id, const uint32_t rule_cnt, const uint32_t pkt_prefilter_cnt)
void RulesDumpMatchArray (const DetectEngineThreadCtx *det_ctx, const SigGroupHead *sgh, const Packet *p)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file detect-engine-profile.h.
Function Documentation
RulesDumpMatchArray()
void RulesDumpMatchArray (const DetectEngineThreadCtx * det_ctx, const SigGroupHead * sgh, const Packet * p)
Definition at line 83 of file detect-engine-profile.c.
References Flow_::alproto, AppProtoToString(), ConfigGetLogDirectory(), CreateEveHeader(), Packet_::flow, Signature_::id, SigGroupHead_::id, LOG_DIR_PACKET, DetectEngineThreadCtx_::match_array, DetectEngineThreadCtx_::match_array_cnt, and DetectEngineThreadCtx_::non_pf_store_cnt.
RulesDumpTxMatchArray()
void RulesDumpTxMatchArray (const DetectEngineThreadCtx * det_ctx, const SigGroupHead * sgh, const Packet * p, const uint64_t tx_id, const uint32_t rule_cnt, const uint32_t pkt_prefilter_cnt)
Definition at line 38 of file detect-engine-profile.c.
References Flow_::alproto, AppProtoToString(), ConfigGetLogDirectory(), CreateEveHeaderWithTxId(), DetectEngineThreadCtx_::de_ctx, Packet_::flow, Signature_::id, RuleMatchCandidateTx::id, SigGroupHead_::id, LOG_DIR_PACKET, DetectEngineThreadCtx_::non_pf_store_cnt, DetectEngineCtx_::sig_array, SigIntId, and DetectEngineThreadCtx_::tx_candidates.