suricata: /Users/jlu/suricata/src/detect-tls-random.h File Reference
detect-tls-random.h File Reference
Functions
void DetectTlsRandomTimeRegister (void)
void DetectTlsRandomBytesRegister (void)
void DetectTlsRandomRegister (void)
Registration function for keyword: tls.random.
Function Documentation
DetectTlsRandomBytesRegister()
void DetectTlsRandomBytesRegister (void)
Definition at line 81 of file detect-tls-random.c.
References SigTableElmt_::desc, DETECT_AL_TLS_RANDOM_BYTES, SigTableElmt_::name, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by DetectTlsRandomRegister().
DetectTlsRandomRegister()
void DetectTlsRandomRegister (void)
Registration function for keyword: tls.random.
Definition at line 112 of file detect-tls-random.c.
References SigTableElmt_::desc, DETECT_AL_TLS_RANDOM, DetectTlsRandomBytesRegister(), DetectTlsRandomTimeRegister(), SigTableElmt_::name, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
DetectTlsRandomTimeRegister()
void DetectTlsRandomTimeRegister (void)
Definition at line 55 of file detect-tls-random.c.
References SigTableElmt_::desc, DETECT_AL_TLS_RANDOM_TIME, SigTableElmt_::name, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by DetectTlsRandomRegister().