suricata: /Users/jlu/suricata/src/detect-engine-frame.c File Reference
detect-engine-frame.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "app-layer-parser.h"
#include "app-layer-frames.h"
#include "detect-engine.h"
#include "detect-engine-prefilter.h"
#include "detect-engine-content-inspection.h"
#include "detect-engine-mpm.h"
#include "detect-engine-frame.h"
#include "stream-tcp.h"
#include "util-profiling.h"
#include "util-validate.h"
#include "util-print.h"
Data Structures
struct PrefilterMpmFrameCtx
struct FrameStreamData
Typedefs
typedef struct PrefilterMpmFrameCtx PrefilterMpmFrameCtx
Functions
void DetectRunPrefilterFrame (DetectEngineThreadCtx *det_ctx, const SigGroupHead *sgh, Packet *p, const Frames *frames, const Frame *frame, const AppProto alproto, const uint32_t idx)
int PrefilterGenericMpmFrameRegister (DetectEngineCtx *de_ctx, SigGroupHead *sgh, MpmCtx *mpm_ctx, const DetectBufferMpmRegistery *mpm_reg, int list_id)
int DetectRunFrameInspectRule (ThreadVars *tv, DetectEngineThreadCtx *det_ctx, const Signature *s, Flow *f, Packet *p, const Frames *frames, const Frame *frame, const uint32_t idx)
InspectionBuffer * DetectFrame2InspectBuffer (DetectEngineThreadCtx *det_ctx, const DetectEngineTransforms *transforms, Packet *p, const Frames *frames, const Frame *frame, const int list_id, const uint32_t idx, const bool first)
int DetectEngineInspectFrameBufferGeneric (DetectEngineThreadCtx *det_ctx, const DetectEngineFrameInspectionEngine *engine, const Signature *s, Packet *p, const Frames *frames, const Frame *frame, const uint32_t idx)
Do the content inspection & validation for a signature.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file detect-engine-frame.c.
Typedef Documentation
PrefilterMpmFrameCtx
typedef struct PrefilterMpmFrameCtx PrefilterMpmFrameCtx
Function Documentation
DetectEngineInspectFrameBufferGeneric()
int DetectEngineInspectFrameBufferGeneric (DetectEngineThreadCtx * det_ctx, const DetectEngineFrameInspectionEngine * engine, const Signature * s, Packet * p, const Frames * frames, const Frame * frame, const uint32_t idx)
Do the content inspection & validation for a signature.
Parameters
de_ctx Detection engine context
det_ctx Detection engine thread context
s Signature to inspect
p Packet
frame stream frame to inspect
Return values
0 no match.
1 match.
Definition at line 367 of file detect-engine-frame.c.
References DetectEngineThreadCtx_::buffer_offset, BUG_ON, DetectEngineThreadCtx_::de_ctx, FrameStreamData::det_ctx, DETECT_CI_FLAGS_END, DETECT_CI_FLAGS_START, DETECT_ENGINE_CONTENT_INSPECTION_MODE_FRAME, DETECT_ENGINE_INSPECT_SIG_MATCH, DETECT_ENGINE_INSPECT_SIG_NO_MATCH, DetectEngineContentInspection(), DetectFrame2InspectBuffer(), DetectEngineThreadCtx_::discontinue_matching, InspectionBuffer::flags, Packet_::flow, FrameStreamData::frame, FrameStreamData::idx, InspectionBuffer::inspect, InspectionBuffer::inspect_len, InspectionBuffer::inspect_offset, DetectEngineThreadCtx_::inspection_recursion_counter, Frame::len, FrameStreamData::list_id, DetectEngineFrameInspectionEngine::mpm, offset, Frame::rel_offset, SCLogDebug, DetectEngineFrameInspectionEngine::sm_list, DetectEngineFrameInspectionEngine::smd, FrameStreamData::transforms, DetectEngineFrameInspectionEngine::transforms, Frame::type, unlikely, and DetectEngineFrameInspectionEngine::v1.
DetectFrame2InspectBuffer()
InspectionBuffer * DetectFrame2InspectBuffer (DetectEngineThreadCtx * det_ctx, const DetectEngineTransforms * transforms, Packet * p, const Frames * frames, const Frame * frame, const int list_id, const uint32_t idx, const bool first)
Definition at line 277 of file detect-engine-frame.c.
References BUG_ON, FrameStreamData::det_ctx, Packet_::flow, FrameStreamData::idx, InspectionBuffer::inspect, InspectionBufferMultipleForListGet(), FrameStreamData::list_id, and Packet_::proto.
Referenced by DetectEngineInspectFrameBufferGeneric().
DetectRunFrameInspectRule()
int DetectRunFrameInspectRule (ThreadVars * tv, DetectEngineThreadCtx * det_ctx, const Signature * s, Flow * f, Packet * p, const Frames * frames, const Frame * frame, const uint32_t idx)
Definition at line 134 of file detect-engine-frame.c.
References Flow_::alproto, AppLayerParserGetFrameNameById(), BUG_ON, Signature_::frame_inspect, Frame::id, Signature_::id, DetectEngineFrameInspectionEngine::next, Flow_::proto, SCLogDebug, and Frame::type.
DetectRunPrefilterFrame()
void DetectRunPrefilterFrame (DetectEngineThreadCtx * det_ctx, const SigGroupHead * sgh, Packet * p, const Frames * frames, const Frame * frame, const AppProto alproto, const uint32_t idx)
Definition at line 43 of file detect-engine-frame.c.
References PrefilterEngine_::alproto, ALPROTO_UNKNOWN, BUG_ON, PrefilterEngine_::cb, PrefilterEngine_::ctx, SigGroupHead_::frame_engines, PrefilterEngine_::frame_type, PrefilterEngine_::gid, PrefilterEngine_::is_last, Packet_::pcap_cnt, PrefilterEngine_::pectx, PREFILTER_PROFILING_END, PREFILTER_PROFILING_START, PrefilterEngine_::PrefilterFrame, SCLogDebug, and Frame::type.
PrefilterGenericMpmFrameRegister()
int PrefilterGenericMpmFrameRegister (DetectEngineCtx * de_ctx, SigGroupHead * sgh, MpmCtx * mpm_ctx, const DetectBufferMpmRegistery * mpm_reg, int list_id)
Definition at line 114 of file detect-engine-frame.c.
References DetectBufferMpmRegistery_::alproto, ALPROTO_UNKNOWN, BUG_ON, de_ctx, DetectBufferMpmRegistery_::frame_v1, PrefilterMpmFrameCtx::list_id, PrefilterMpmFrameCtx::mpm_ctx, PrefilterAppendFrameEngine(), SCCalloc, SCEnter, PrefilterMpmFrameCtx::transforms, and DetectBufferMpmRegistery_::transforms.