suricata: /Users/jlu/suricata/src/detect-http2.c File Reference
detect-http2.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-content.h"
#include "detect-engine.h"
#include "detect-engine-uint.h"
#include "detect-engine-mpm.h"
#include "detect-engine-prefilter.h"
#include "detect-engine-content-inspection.h"
#include "detect-http2.h"
#include "util-byte.h"
#include "rust.h"
#include "util-profiling.h"
#include "tests/detect-http2.c"
Functions
void DetectHTTP2frameTypeRegisterTests (void)
this function registers unit tests for DetectHTTP2frameType
void DetectHTTP2errorCodeRegisterTests (void)
void DetectHTTP2priorityRegisterTests (void)
void DetectHTTP2windowRegisterTests (void)
void DetectHTTP2settingsRegisterTests (void)
void DetectHTTP2sizeUpdateRegisterTests (void)
void DetectHTTP2frametypeFree (DetectEngineCtx *de_ctx, void *ptr)
this function will free memory associated with uint8_t
void DetectHTTP2errorcodeFree (DetectEngineCtx *de_ctx, void *ptr)
this function will free memory associated with uint32_t
void DetectHTTP2priorityFree (DetectEngineCtx *de_ctx, void *ptr)
this function will free memory associated with uint32_t
void DetectHTTP2windowFree (DetectEngineCtx *de_ctx, void *ptr)
this function will free memory associated with uint32_t
void DetectHTTP2sizeUpdateFree (DetectEngineCtx *de_ctx, void *ptr)
this function will free memory associated with uint32_t
void DetectHTTP2settingsFree (DetectEngineCtx *de_ctx, void *ptr)
this function will free memory associated with rust signature context
void DetectHTTP2RegisterTests (void)
void DetectHttp2Register (void)
Registration function for HTTP2 keywords.
Detailed Description
Author
Philippe Antoine p.ant.nosp@m.oine.nosp@m.@cate.nosp@m.nacy.nosp@m.ber.f.nosp@m.r
Definition in file detect-http2.c.
Function Documentation
DetectHTTP2errorcodeFree()
void DetectHTTP2errorcodeFree (DetectEngineCtx * de_ctx, void * ptr)
this function will free memory associated with uint32_t
Parameters
ptr pointer to uint32_t
Definition at line 408 of file detect-http2.c.
References SCFree.
DetectHTTP2errorCodeRegisterTests()
void DetectHTTP2errorCodeRegisterTests (void)
Definition at line 68 of file detect-http2.c.
References UtRegisterTest().
DetectHTTP2frametypeFree()
void DetectHTTP2frametypeFree (DetectEngineCtx * de_ctx, void * ptr)
this function will free memory associated with uint8_t
Parameters
ptr pointer to uint8_t
Definition at line 322 of file detect-http2.c.
References SCFree.
DetectHTTP2frameTypeRegisterTests()
void DetectHTTP2frameTypeRegisterTests (void)
this function registers unit tests for DetectHTTP2frameType
Definition at line 46 of file detect-http2.c.
References UtRegisterTest().
DetectHTTP2priorityFree()
void DetectHTTP2priorityFree (DetectEngineCtx * de_ctx, void * ptr)
this function will free memory associated with uint32_t
Parameters
ptr pointer to DetectU8Data
Definition at line 475 of file detect-http2.c.
DetectHTTP2priorityRegisterTests()
void DetectHTTP2priorityRegisterTests (void)
Definition at line 90 of file detect-http2.c.
References UtRegisterTest().
DetectHttp2Register()
void DetectHttp2Register (void)
Registration function for HTTP2 keywords.
Definition at line 118 of file detect-http2.c.
References SigTableElmt_::AppLayerTxMatch, SigTableElmt_::desc, DETECT_HTTP2_FRAMETYPE, SigTableElmt_::Match, SigTableElmt_::name, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
DetectHTTP2RegisterTests()
void DetectHTTP2RegisterTests (void)
DetectHTTP2settingsFree()
void DetectHTTP2settingsFree (DetectEngineCtx * de_ctx, void * ptr)
this function will free memory associated with rust signature context
Parameters
ptr pointer to rust signature context
Definition at line 656 of file detect-http2.c.
DetectHTTP2settingsRegisterTests()
void DetectHTTP2settingsRegisterTests (void)
Definition at line 135 of file detect-http2.c.
References UtRegisterTest().
DetectHTTP2sizeUpdateFree()
void DetectHTTP2sizeUpdateFree (DetectEngineCtx * de_ctx, void * ptr)
this function will free memory associated with uint32_t
Parameters
ptr pointer to DetectU8Data
Definition at line 599 of file detect-http2.c.
DetectHTTP2sizeUpdateRegisterTests()
void DetectHTTP2sizeUpdateRegisterTests (void)
Definition at line 158 of file detect-http2.c.
References UtRegisterTest().
DetectHTTP2windowFree()
void DetectHTTP2windowFree (DetectEngineCtx * de_ctx, void * ptr)
this function will free memory associated with uint32_t
Parameters
ptr pointer to DetectU8Data
Definition at line 542 of file detect-http2.c.
DetectHTTP2windowRegisterTests()
void DetectHTTP2windowRegisterTests (void)
Definition at line 112 of file detect-http2.c.
References UtRegisterTest().