suricata: /Users/jlu/suricata/src/detect-engine-loader.c File Reference
detect-engine-loader.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "conf.h"
#include "detect.h"
#include "detect-parse.h"
#include "runmodes.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "queue.h"
#include "util-signal.h"
#include "detect-engine-loader.h"
#include "detect-engine-build.h"
#include "detect-engine-analyzer.h"
#include "detect-engine-mpm.h"
#include "detect-engine-sigorder.h"
#include "util-detect.h"
#include "util-threshold-config.h"
Data Structures
struct DetectLoaderThreadData_
Macros
#define NLOADERS 4
Typedefs
typedef struct DetectLoaderThreadData_ DetectLoaderThreadData
Functions
char * DetectLoadCompleteSigPath (const DetectEngineCtx *de_ctx, const char *sig_file)
Create the path if default-rule-path was specified.
int SigLoadSignatures (DetectEngineCtx *de_ctx, char *sig_file, int sig_file_exclusive)
Load signatures.
void TmThreadWakeupDetectLoaderThreads ()
Unpauses all threads present in tv_root.
int DetectLoaderQueueTask (int loader_id, LoaderFunc Func, void *func_ctx)
int DetectLoadersSync (void)
wait for loader tasks to complete
void DetectLoadersInit (void)
void TmThreadContinueDetectLoaderThreads ()
Unpauses all threads present in tv_root.
SC_ATOMIC_DECLARE (int, detect_loader_cnt)
void DetectLoaderThreadSpawn (void)
spawn the detect loader manager thread
void TmModuleDetectLoaderRegister (void)
Variables
int rule_reload
int engine_analysis
int rule_engine_analysis_set = 0
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file detect-engine-loader.c.
Macro Definition Documentation
NLOADERS
#define NLOADERS 4
Definition at line 399 of file detect-engine-loader.c.
Typedef Documentation
DetectLoaderThreadData
typedef struct DetectLoaderThreadData_ DetectLoaderThreadData
Function Documentation
DetectLoadCompleteSigPath()
char * DetectLoadCompleteSigPath (const DetectEngineCtx * de_ctx, const char * sig_file)
Create the path if default-rule-path was specified.
Parameters
sig_file The name of the file
Return values
str Pointer to the string path + sig_file
Definition at line 60 of file detect-engine-loader.c.
References ConfGetNode(), DetectEngineCtx_::config_prefix, de_ctx, ConfNode_::final, PathIsRelative(), SC_ERR_INVALID_ARGUMENTS, SCLogDebug, SCLogError, SCMalloc, SCStrdup, strlcat(), strlcpy(), unlikely, and ConfNode_::val.
DetectLoaderQueueTask()
int DetectLoaderQueueTask (int loader_id, LoaderFunc Func, void * func_ctx)
Parameters
loader -1 for auto select
Return values
loader_id or negative in case of error
Definition at line 407 of file detect-engine-loader.c.
DetectLoadersInit()
void DetectLoadersInit (void)
Definition at line 478 of file detect-engine-loader.c.
References ConfGetInt(), NLOADERS, SC_ERR_INVALID_ARGUMENTS, and SCLogError.
DetectLoadersSync()
int DetectLoadersSync (void)
wait for loader tasks to complete
Return values
result 0 for ok, -1 for errors
Definition at line 440 of file detect-engine-loader.c.
References SCLogDebug.
DetectLoaderThreadSpawn()
void DetectLoaderThreadSpawn (void)
spawn the detect loader manager thread
Definition at line 624 of file detect-engine-loader.c.
SC_ATOMIC_DECLARE()
SC_ATOMIC_DECLARE (int , detect_loader_cnt)
SigLoadSignatures()
int SigLoadSignatures (DetectEngineCtx * de_ctx, char * sig_file, int sig_file_exclusive)
Load signatures.
Parameters
de_ctx Pointer to the detection engine context
sig_file Filename (or pattern) holding signatures
sig_file_exclusive File passed in 'sig_file' should be loaded exclusively.
Return values
-1 on error
Definition at line 282 of file detect-engine-loader.c.
References DetectEngineCtx_::config_prefix, de_ctx, RUNMODE_ENGINE_ANALYSIS, RunmodeGetCurrent(), SCEnter, and DetectEngineCtx_::sig_stat.
TmModuleDetectLoaderRegister()
void TmModuleDetectLoaderRegister (void)
Definition at line 649 of file detect-engine-loader.c.
References TmModule_::name, TmModule_::ThreadInit, TMM_DETECTLOADER, and tmm_modules.
TmThreadContinueDetectLoaderThreads()
void TmThreadContinueDetectLoaderThreads (void)
Unpauses all threads present in tv_root.
Definition at line 529 of file detect-engine-loader.c.
References ThreadVars_::name, ThreadVars_::next, SCMutexLock, SCMutexUnlock, TmThreadContinue(), tv, tv_root, tv_root_lock, and TVT_MAX.
TmThreadWakeupDetectLoaderThreads()
void TmThreadWakeupDetectLoaderThreads (void)
Unpauses all threads present in tv_root.
Definition at line 505 of file detect-engine-loader.c.
References BUG_ON, ThreadVars_::ctrl_cond, ThreadVars_::name, ThreadVars_::next, SCMutexLock, SCMutexUnlock, tv, tv_root, tv_root_lock, and TVT_MAX.
Variable Documentation
engine_analysis
int engine_analysis extern
rule_engine_analysis_set
int rule_engine_analysis_set = 0
Definition at line 53 of file detect-engine-loader.c.
Referenced by DetectFlowbitsAnalyze().
rule_reload
int rule_reload extern