suricata: /Users/jlu/suricata/src/detect-flowvar.h File Reference
detect-flowvar.h File Reference
Data Structures
struct DetectFlowvarData_
Typedefs
typedef struct DetectFlowvarData_ DetectFlowvarData
Functions
void DetectFlowvarRegister (void)
int DetectFlowvarPostMatchSetup (DetectEngineCtx *de_ctx, Signature *s, uint32_t idx)
Setup a post-match for flowvar storage We're piggyback riding the DetectFlowvarData struct.
int DetectVarStoreMatch (DetectEngineThreadCtx *, uint32_t, uint8_t *, uint16_t, int)
Store flowvar in det_ctx so we can exec it post-match.
int DetectVarStoreMatchKeyValue (DetectEngineThreadCtx *, uint8_t *, uint16_t, uint8_t *, uint16_t, int)
Store flowvar in det_ctx so we can exec it post-match.
void DetectVarProcessListInternal (DetectVarList *fs, Flow *f, Packet *p)
Handle flowvar candidate list in det_ctx: clean up the list.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file detect-flowvar.h.
Typedef Documentation
DetectFlowvarData
typedef struct DetectFlowvarData_ DetectFlowvarData
Function Documentation
DetectFlowvarPostMatchSetup()
int DetectFlowvarPostMatchSetup (DetectEngineCtx * de_ctx, Signature * s, uint32_t idx)
Setup a post-match for flowvar storage We're piggyback riding the DetectFlowvarData struct.
Definition at line 259 of file detect-flowvar.c.
References SigMatch_::ctx, DETECT_FLOWVAR_POSTMATCH, DETECT_SM_LIST_POSTMATCH, DetectFlowvarData_::idx, SCMalloc, SigMatchAlloc(), SigMatchAppendSMToList(), SigMatch_::type, and unlikely.
DetectFlowvarRegister()
void DetectFlowvarRegister (void)
Definition at line 55 of file detect-flowvar.c.
References DETECT_FLOWVAR, DetectFlowvarMatch(), SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::Setup, and sigmatch_table.
Referenced by SigTableSetup().
DetectVarProcessListInternal()
void DetectVarProcessListInternal (DetectVarList * fs, Flow * f, Packet * p)
Handle flowvar candidate list in det_ctx: clean up the list.
Only called from DetectVarProcessList() when varlist is not NULL.
Definition at line 352 of file detect-flowvar.c.
References DetectVarList_::buffer, DetectVarList_::key, next, DetectVarList_::next, and SCFree.
DetectVarStoreMatch()
int DetectVarStoreMatch (DetectEngineThreadCtx * det_ctx, uint32_t idx, uint8_t * buffer, uint16_t len, int type)
Store flowvar in det_ctx so we can exec it post-match.
Definition at line 223 of file detect-flowvar.c.
References DetectVarList_::buffer, DetectVarList_::idx, len, DetectVarList_::len, DetectVarList_::next, SCCalloc, SCFree, type, DetectVarList_::type, unlikely, and DetectEngineThreadCtx_::varlist.
DetectVarStoreMatchKeyValue()
int DetectVarStoreMatchKeyValue (DetectEngineThreadCtx * det_ctx, uint8_t * key, uint16_t key_len, uint8_t * buffer, uint16_t len, int type)
Store flowvar in det_ctx so we can exec it post-match.
Definition at line 203 of file detect-flowvar.c.
References DetectVarList_::buffer, DetectVarList_::key, DetectVarList_::key_len, len, DetectVarList_::len, DetectVarList_::next, SCCalloc, type, DetectVarList_::type, unlikely, and DetectEngineThreadCtx_::varlist.