suricata: /Users/jlu/suricata/src/detect-replace.h File Reference
detect-replace.h File Reference
#include "detect-content.h"
Functions
DetectReplaceList * DetectReplaceAddToList (DetectReplaceList *replist, uint8_t *found, DetectContentData *cd)
void DetectReplaceExecuteInternal (Packet *p, DetectReplaceList *replist)
void DetectReplaceFreeInternal (DetectReplaceList *replist)
void DetectReplaceRegister (void)
Detailed Description
Author
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Definition in file detect-replace.h.
Function Documentation
DetectReplaceAddToList()
DetectReplaceList * DetectReplaceAddToList (DetectReplaceList * replist, uint8_t * found, DetectContentData * cd)
Definition at line 188 of file detect-replace.c.
References DetectReplaceList_::cd, DetectContentData_::content_len, DetectReplaceList_::found, DetectReplaceList_::next, DetectContentData_::replace_len, SCLogDebug, SCMalloc, and unlikely.
Referenced by DetectEngineContentInspection().
DetectReplaceExecuteInternal()
void DetectReplaceExecuteInternal (Packet * p, DetectReplaceList * replist)
Definition at line 210 of file detect-replace.c.
References DetectReplaceList_::cd, Packet_::flags, DetectReplaceList_::found, DetectReplaceList_::next, PKT_STREAM_MODIFIED, ReCalculateChecksum(), DetectContentData_::replace, DetectContentData_::replace_len, SCFree, and SCLogDebug.
DetectReplaceFreeInternal()
void DetectReplaceFreeInternal (DetectReplaceList * replist)
Definition at line 227 of file detect-replace.c.
References DetectReplaceList_::next, SCFree, and SCLogDebug.
DetectReplaceRegister()
void DetectReplaceRegister (void)
Definition at line 70 of file detect-replace.c.
References SigTableElmt_::desc, DETECT_REPLACE, SigTableElmt_::Match, SigTableElmt_::name, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().