suricata: /Users/jlu/suricata/src/detect-template-buffer.c File Reference
detect-template-buffer.c File Reference
#include "suricata-common.h"
#include "conf.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-engine-prefilter.h"
#include "app-layer-template.h"
#include "detect-template-buffer.h"
#include "tests/detect-template-buffer.c"
Functions
void DetectTemplateBufferRegister (void)
Detailed Description
Author
FirstName LastName <yourname@domain>
Set up of the "template_buffer" keyword to allow content inspections on the decoded template application layer buffers.
Definition in file detect-template-buffer.c.
Function Documentation
DetectTemplateBufferRegister()
void DetectTemplateBufferRegister (void)
Definition at line 53 of file detect-template-buffer.c.
References ConfGetNode(), SigTableElmt_::desc, DETECT_AL_TEMPLATE_BUFFER, SigTableElmt_::name, RunmodeIsUnittests(), SigTableElmt_::Setup, and sigmatch_table.
Referenced by SigTableSetup().