suricata: /Users/jlu/suricata/src/detect-parse.h File Reference
detect-parse.h File Reference
Data Structures
struct DetectParseRegex
Typedefs
typedef struct DetectParseRegex DetectParseRegex
Enumerations
enum { SIG_DIREC_NORMAL , SIG_DIREC_SWITCHED }
enum { SIG_DIREC_SRC , SIG_DIREC_DST }
Functions
Signature * SigAlloc (void)
void SigFree (DetectEngineCtx *de_ctx, Signature *s)
Signature * SigInit (DetectEngineCtx *, const char *sigstr)
Parses a signature and adds it to the Detection Engine Context.
Signature * SigInitReal (DetectEngineCtx *, const char *)
SigMatchData * SigMatchList2DataArray (SigMatch *head)
convert SigMatch list to SigMatchData array
void SigParseRegisterTests (void)
Signature * DetectEngineAppendSig (DetectEngineCtx *, const char *)
Parse and append a Signature into the Detection Engine Context signature list.
void SigMatchAppendSMToList (Signature *, SigMatch *, int)
Append a SigMatch to the list type.
void SigMatchRemoveSMFromList (Signature *, SigMatch *, int)
int SigMatchListSMBelongsTo (const Signature *, const SigMatch *)
int DetectParseDupSigHashInit (DetectEngineCtx *)
Initializes the hash table that is used to cull duplicate sigs.
void DetectParseDupSigHashFree (DetectEngineCtx *)
Frees the hash table that is used to cull duplicate sigs.
int DetectEngineContentModifierBufferSetup (DetectEngineCtx *de_ctx, Signature *s, const char *arg, int sm_type, int sm_list, AppProto alproto)
bool SigMatchSilentErrorEnabled (const DetectEngineCtx *de_ctx, const enum DetectKeywordId id)
bool SigMatchStrictEnabled (const enum DetectKeywordId id)
const char * DetectListToHumanString (int list)
const char * DetectListToString (int list)
void SigTableApplyStrictCommandlineOption (const char *str)
SigMatch * DetectGetLastSM (const Signature *)
Returns the sm with the largest index (added latest) from this sig.
SigMatch * DetectGetLastSMFromMpmLists (const DetectEngineCtx *de_ctx, const Signature *s)
get the last SigMatch from lists that support MPM.
SigMatch * DetectGetLastSMFromLists (const Signature *s,...)
Returns the sm with the largest index (added latest) from the lists passed to us.
SigMatch * DetectGetLastSMByListPtr (const Signature *s, SigMatch *sm_list,...)
Returns the sm with the largest index (added last) from the list passed to us as a pointer.
SigMatch * DetectGetLastSMByListId (const Signature *s, int list_id,...)
Returns the sm with the largest index (added last) from the list passed to us as an id.
int DetectSignatureAddTransform (Signature *s, int transform, void *options)
int WARN_UNUSED DetectSignatureSetAppProto (Signature *s, AppProto alproto)
DetectParseRegex * DetectSetupPCRE2 (const char *parse_str, int opts)
bool DetectSetupParseRegexesOpts (const char *parse_str, DetectParseRegex *parse_regex, int opts)
void DetectSetupParseRegexes (const char *parse_str, DetectParseRegex *parse_regex)
void DetectParseRegexAddToFreeList (DetectParseRegex *parse_regex)
add regex and/or study to at exit free list
void DetectParseFreeRegexes (void)
void DetectParseFreeRegex (DetectParseRegex *r)
int DetectParsePcreExec (DetectParseRegex *parse_regex, const char *str, int start_offset, int options)
int SC_Pcre2SubstringCopy (pcre2_match_data *match_data, uint32_t number, PCRE2_UCHAR *buffer, PCRE2_SIZE *bufflen)
int SC_Pcre2SubstringGet (pcre2_match_data *match_data, uint32_t number, PCRE2_UCHAR **bufferptr, PCRE2_SIZE *bufflen)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file detect-parse.h.
Typedef Documentation
DetectParseRegex
typedef struct DetectParseRegex DetectParseRegex
Enumeration Type Documentation
anonymous enum
anonymous enum
Flags to indicate if the Signature parsing must be done switching the source and dest (for ip addresses and ports) or otherwise as normal
Enumerator
SIG_DIREC_NORMAL
SIG_DIREC_SWITCHED
Definition at line 30 of file detect-parse.h.
anonymous enum
anonymous enum
Flags to indicate if are referencing the source of the Signature or the destination (for ip addresses and ports)
Enumerator
SIG_DIREC_SRC
SIG_DIREC_DST
Definition at line 37 of file detect-parse.h.
Function Documentation
DetectEngineAppendSig()
Signature * DetectEngineAppendSig (DetectEngineCtx * de_ctx, const char * sigstr)
Parse and append a Signature into the Detection Engine Context signature list.
If the signature is bidirectional it should append two signatures (with the addresses switched) into the list. Also handle duplicate signatures. In case of duplicate sigs, use the ones that have the latest revision. We use the sid and the msg to identify duplicate sigs. If 2 sigs have the same sid and gid, they are duplicates.
Parameters
de_ctx Pointer to the Detection Engine Context.
sigstr Pointer to a character string containing the signature to be parsed.
sig_file Pointer to a character string containing the filename from which signature is read
lineno Line number from where signature is read
Return values
Pointer to the head Signature in the detection engine ctx sig_list on success; NULL on failure.
In DetectEngineAppendSig(), the signatures are prepended and we always return the first one so if the signature is bidirectional, the returned sig will point through "next" ptr to the cloned signatures with the switched addresses
Definition at line 2421 of file detect-parse.c.
References de_ctx, and SigInit().
Referenced by UTHAppendSigs(), and UTHParseSignature().
DetectEngineContentModifierBufferSetup()
int DetectEngineContentModifierBufferSetup (DetectEngineCtx * de_ctx, Signature * s, const char * arg, int sm_type, int sm_list, AppProto alproto)
Parameters
arg NULL or empty string
Definition at line 146 of file detect-parse.c.
References Signature_::alproto, ALPROTO_UNKNOWN, DETECT_SM_LIST_NOTSET, Signature_::init_data, SignatureInitData_::list, SC_ERR_INVALID_ARGUMENT, SC_ERR_INVALID_SIGNATURE, SCLogError, and sigmatch_table.
Referenced by DetectHttpUriSetup().
DetectGetLastSM()
SigMatch * DetectGetLastSM (const Signature * s)
Returns the sm with the largest index (added latest) from this sig.
Return values
sm_last Pointer to last sm
Definition at line 575 of file detect-parse.c.
References SigMatch_::idx, Signature_::init_data, SignatureInitData_::smlists_array_size, and SignatureInitData_::smlists_tail.
DetectGetLastSMByListId()
SigMatch * DetectGetLastSMByListId (const Signature * s, int list_id, ...)
Returns the sm with the largest index (added last) from the list passed to us as an id.
Parameters
list_id id of the list to be searched
va_args list of keyword types terminated by -1
Return values
sm_last to last sm.
Definition at line 540 of file detect-parse.c.
References Signature_::init_data, SignatureInitData_::smlists_array_size, and SignatureInitData_::smlists_tail.
DetectGetLastSMByListPtr()
SigMatch * DetectGetLastSMByListPtr (const Signature * s, SigMatch * sm_list, ...)
Returns the sm with the largest index (added last) from the list passed to us as a pointer.
Parameters
sm_list pointer to the SigMatch we should look before
va_args list of keyword types terminated by -1
Return values
sm_last to last sm.
Definition at line 508 of file detect-parse.c.
Referenced by DetectGetLastSMFromMpmLists().
DetectGetLastSMFromLists()
SigMatch * DetectGetLastSMFromLists (const Signature * s, ...)
Returns the sm with the largest index (added latest) from the lists passed to us.
Return values
Pointer to Last sm.
Definition at line 468 of file detect-parse.c.
References DETECT_SM_LIST_NOTSET, Signature_::init_data, SignatureInitData_::list, SignatureInitData_::smlists, and SignatureInitData_::smlists_array_size.
DetectGetLastSMFromMpmLists()
SigMatch * DetectGetLastSMFromMpmLists (const DetectEngineCtx * de_ctx, const Signature * s)
get the last SigMatch from lists that support MPM.
Note
only supports the lists that are registered through DetectBufferTypeSupportsMpm().
Definition at line 429 of file detect-parse.c.
References de_ctx, DETECT_CONTENT, DETECT_SM_LIST_NOTSET, DetectEngineBufferTypeSupportsMpmGetById(), DetectGetLastSMByListPtr(), Signature_::init_data, SignatureInitData_::list, SignatureInitData_::smlists_array_size, and SignatureInitData_::smlists_tail.
DetectListToHumanString()
const char * DetectListToHumanString (int list)
Definition at line 114 of file detect-parse.c.
Referenced by DumpPatterns().
DetectListToString()
const char * DetectListToString (int list)
Definition at line 131 of file detect-parse.c.
DetectParseDupSigHashFree()
void DetectParseDupSigHashFree (DetectEngineCtx * de_ctx)
Frees the hash table that is used to cull duplicate sigs.
Parameters
de_ctx Pointer to the detection engine context that holds this table.
Definition at line 2240 of file detect-parse.c.
References de_ctx, DetectEngineCtx_::dup_sig_hash_table, and HashListTableFree().
Referenced by DetectEngineCtxFree().
DetectParseDupSigHashInit()
int DetectParseDupSigHashInit (DetectEngineCtx * de_ctx)
Initializes the hash table that is used to cull duplicate sigs.
Parameters
de_ctx Pointer to the detection engine context.
Return values
0 On success.
-1 On failure.
Definition at line 2223 of file detect-parse.c.
References de_ctx, DetectEngineCtx_::dup_sig_hash_table, and HashListTableInit().
DetectParseFreeRegex()
void DetectParseFreeRegex (DetectParseRegex * r)
Definition at line 2482 of file detect-parse.c.
References DetectParseRegex::context, DetectParseRegex::match, and DetectParseRegex::regex.
DetectParseFreeRegexes()
void DetectParseFreeRegexes (void)
Definition at line 2495 of file detect-parse.c.
DetectParsePcreExec()
int DetectParsePcreExec (DetectParseRegex * parse_regex, const char * str, int start_offset, int options)
Definition at line 2475 of file detect-parse.c.
DetectParseRegexAddToFreeList()
void DetectParseRegexAddToFreeList (DetectParseRegex * parse_regex)
add regex and/or study to at exit free list
Definition at line 2511 of file detect-parse.c.
References FatalError, DetectParseRegex::match, DetectParseRegex::next, DetectParseRegex::regex, SC_ERR_MEM_ALLOC, and SCCalloc.
Referenced by DetectSetupParseRegexesOpts().
DetectSetupParseRegexes()
void DetectSetupParseRegexes (const char * parse_str, DetectParseRegex * parse_regex)
Definition at line 2598 of file detect-parse.c.
References DetectSetupParseRegexesOpts(), FatalError, and SC_ERR_PCRE_COMPILE.
DetectSetupParseRegexesOpts()
bool DetectSetupParseRegexesOpts (const char * parse_str, DetectParseRegex * parse_regex, int opts)
Definition at line 2523 of file detect-parse.c.
References DetectParseRegexAddToFreeList(), DetectParseRegex::match, DetectParseRegex::regex, SC_ERR_PCRE_COMPILE, and SCLogError.
Referenced by DetectSetupParseRegexes().
DetectSetupPCRE2()
DetectParseRegex * DetectSetupPCRE2 (const char * parse_str, int opts)
Definition at line 2546 of file detect-parse.c.
References DetectParseRegex::match, DetectParseRegex::next, DetectParseRegex::regex, SC_ERR_PCRE_COMPILE, SCCalloc, SCFree, and SCLogError.
DetectSignatureAddTransform()
int DetectSignatureAddTransform (Signature * s, int transform, void * options)
Definition at line 1465 of file detect-parse.c.
References DetectEngineTransforms::cnt, DETECT_TRANSFORMS_MAX, Signature_::init_data, SignatureInitData_::list, SignatureInitData_::list_set, TransformData_::options, SC_ERR_INVALID_SIGNATURE, SCLogDebug, SCLogError, SCReturnInt, Signature_::sig_str, TransformData_::transform, DetectEngineTransforms::transforms, and SignatureInitData_::transforms.
DetectSignatureSetAppProto()
int WARN_UNUSED DetectSignatureSetAppProto (Signature * s, AppProto alproto)
Definition at line 1490 of file detect-parse.c.
References Signature_::alproto, ALPROTO_DCERPC, ALPROTO_FAILED, ALPROTO_SMB, ALPROTO_UNKNOWN, AppProtoToString(), SC_ERR_CONFLICTING_RULE_KEYWORDS, SC_ERR_INVALID_ARGUMENT, and SCLogError.
SC_Pcre2SubstringCopy()
int SC_Pcre2SubstringCopy (pcre2_match_data * match_data, uint32_t number, PCRE2_UCHAR * buffer, PCRE2_SIZE * bufflen)
Definition at line 2574 of file detect-parse.c.
SC_Pcre2SubstringGet()
int SC_Pcre2SubstringGet (pcre2_match_data * match_data, uint32_t number, PCRE2_UCHAR ** bufferptr, PCRE2_SIZE * bufflen)
Definition at line 2586 of file detect-parse.c.
SigAlloc()
Signature * SigAlloc (void)
Definition at line 1264 of file detect-parse.c.
References DETECT_SM_LIST_NOTSET, DetectBufferTypeMaxId(), Signature_::init_data, SignatureInitData_::list, SignatureInitData_::mpm_sm_list, Signature_::prio, SCCalloc, SCFree, SCLogDebug, SCMalloc, SignatureInitData_::smlists, SignatureInitData_::smlists_array_size, SignatureInitData_::smlists_tail, and unlikely.
SigFree()
void SigFree (DetectEngineCtx * de_ctx, Signature * s)
Definition at line 1389 of file detect-parse.c.
SigInit()
Signature * SigInit (DetectEngineCtx * de_ctx, const char * sigstr)
Parses a signature and adds it to the Detection Engine Context.
Parameters
de_ctx Pointer to the Detection Engine Context.
sigstr Pointer to a character string containing the signature to be parsed.
Return values
Pointer to the Signature instance on success; NULL on failure.
Definition at line 2116 of file detect-parse.c.
Referenced by DetectEngineAppendSig().
SigInitReal()
Signature * SigInitReal (DetectEngineCtx * , const char *)
SigMatchAppendSMToList()
void SigMatchAppendSMToList (Signature * s, SigMatch * new, int list)
Append a SigMatch to the list type.
Parameters
s Signature.
new The sig match to append.
list The list to append to.
Definition at line 349 of file detect-parse.c.
Referenced by DetectContentSetup(), and DetectFlowvarPostMatchSetup().
SigMatchList2DataArray()
SigMatchData * SigMatchList2DataArray (SigMatch * head)
convert SigMatch list to SigMatchData array
Note
ownership of sm->ctx is transferred to smd->ctx
Definition at line 1647 of file detect-parse.c.
References len.
Referenced by DetectEngineAppInspectionEngine2Signature().
SigMatchListSMBelongsTo()
int SigMatchListSMBelongsTo (const Signature * s, const SigMatch * key_sm)
Definition at line 625 of file detect-parse.c.
References Signature_::init_data, and SignatureInitData_::smlists_array_size.
SigMatchRemoveSMFromList()
void SigMatchRemoveSMFromList (Signature * s, SigMatch * sm, int sm_list)
Definition at line 387 of file detect-parse.c.
References Signature_::init_data, SigMatch_::next, SigMatch_::prev, SignatureInitData_::smlists, and SignatureInitData_::smlists_tail.
Referenced by DetectIPProtoRemoveAllSMs().
SigMatchSilentErrorEnabled()
bool SigMatchSilentErrorEnabled (const DetectEngineCtx * de_ctx, const enum DetectKeywordId id)
Definition at line 292 of file detect-parse.c.
References de_ctx, and DetectEngineCtx_::sm_types_silent_error.
SigMatchStrictEnabled()
bool SigMatchStrictEnabled (const enum DetectKeywordId id)
Definition at line 298 of file detect-parse.c.
References DETECT_TBLSIZE, flags, SIGMATCH_STRICT_PARSING, and sigmatch_table.
SigParseRegisterTests()
void SigParseRegisterTests (void)
Definition at line 4270 of file detect-parse.c.
References DetectParseRegisterTests(), and UtRegisterTest().
Referenced by SigRegisterTests().
SigTableApplyStrictCommandlineOption()
void SigTableApplyStrictCommandlineOption (const char * str)
Definition at line 306 of file detect-parse.c.
References DETECT_TBLSIZE, FatalError, SigTableElmt_::flags, SC_ERR_MEM_ALLOC, SCStrdup, SIGMATCH_STRICT_PARSING, sigmatch_table, and str.