suricata: /Users/jlu/suricata/src/detect-dataset.c File Reference
detect-dataset.c File Reference
#include "suricata-common.h"
#include "decode.h"
#include "detect.h"
#include "threads.h"
#include "datasets.h"
#include "detect-dataset.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-engine-state.h"
#include "util-debug.h"
#include "util-print.h"
#include "util-misc.h"
Functions
int DetectDatasetMatch (ThreadVars *, DetectEngineThreadCtx *, Packet *, const Signature *, const SigMatchCtx *)
void DetectDatasetFree (DetectEngineCtx *, void *)
void DetectDatasetRegister (void)
int DetectDatasetBufferMatch (DetectEngineThreadCtx *det_ctx, const DetectDatasetData *sd, const uint8_t *data, const uint32_t data_len)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Implements the dataset keyword
Definition in file detect-dataset.c.
Function Documentation
DetectDatasetBufferMatch()
int DetectDatasetBufferMatch (DetectEngineThreadCtx * det_ctx, const DetectDatasetData * sd, const uint8_t * data, const uint32_t data_len)
Definition at line 61 of file detect-dataset.c.
References DetectDatasetData_::cmd, DatasetAdd(), DatasetLookup(), DETECT_DATASET_CMD_ISNOTSET, DETECT_DATASET_CMD_ISSET, DETECT_DATASET_CMD_SET, SCLogDebug, and DetectDatasetData_::set.
DetectDatasetFree()
void DetectDatasetFree (DetectEngineCtx * de_ctx, void * ptr)
Definition at line 427 of file detect-dataset.c.
References SCFree.
DetectDatasetMatch()
int DetectDatasetMatch (ThreadVars * , DetectEngineThreadCtx * , Packet * , const Signature * , const SigMatchCtx *)
DetectDatasetRegister()
void DetectDatasetRegister (void)
Definition at line 47 of file detect-dataset.c.
References SigTableElmt_::desc, DETECT_DATASET, SigTableElmt_::name, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().