suricata: /Users/jlu/suricata/src/detect-bytemath.h File Reference
detect-bytemath.h File Reference
Functions
void DetectBytemathRegister (void)
Registers the keyword handlers for the "byte_math" keyword.
SigMatch * DetectByteMathRetrieveSMVar (const char *, const Signature *)
Lookup the SigMatch for a named byte_math variable.
int DetectByteMathDoMatch (DetectEngineThreadCtx *, const SigMatchData *, const Signature *, const uint8_t *, uint16_t, uint64_t, uint64_t *, uint8_t)
Detailed Description
Author
Jeff Lucovsky jeff@.nosp@m.luco.nosp@m.vsky..nosp@m.org
Definition in file detect-bytemath.h.
Function Documentation
DetectByteMathDoMatch()
int DetectByteMathDoMatch (DetectEngineThreadCtx * det_ctx, const SigMatchData * smd, const Signature * s, const uint8_t * payload, uint16_t payload_len, uint64_t rvalue, uint64_t * value, uint8_t endian)
Definition at line 79 of file detect-bytemath.c.
References DetectEngineThreadCtx_::buffer_offset, BUG_ON, BYTE_BIG_ENDIAN, BYTE_LITTLE_ENDIAN, ByteExtractStringUint64(), ByteExtractUint64(), SigMatchData_::ctx, len, payload_len, and SCLogDebug.
DetectBytemathRegister()
void DetectBytemathRegister (void)
Registers the keyword handlers for the "byte_math" keyword.
Definition at line 68 of file detect-bytemath.c.
References DETECT_BYTEMATH, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::Setup, and sigmatch_table.
Referenced by SigTableSetup().
DetectByteMathRetrieveSMVar()
SigMatch * DetectByteMathRetrieveSMVar (const char * arg, const Signature * s)
Lookup the SigMatch for a named byte_math variable.
Parameters
arg The name of the byte_math variable to lookup.
s Pointer the signature to look in.
Return values
A pointer to the SigMatch if found, otherwise NULL.
Definition at line 403 of file detect-bytemath.c.
References Signature_::init_data, and SignatureInitData_::smlists_array_size.
Referenced by DetectByteRetrieveSMVar().