suricata: /Users/jlu/suricata/src/detect-engine-port.h File Reference
detect-engine-port.h File Reference
Functions
int DetectPortParse (const DetectEngineCtx *, DetectPort **head, const char *str)
Function for parsing port strings.
DetectPort * DetectPortCopySingle (DetectEngineCtx *, DetectPort *)
Function that return a copy of DetectPort src sigs.
int DetectPortInsert (DetectEngineCtx *, DetectPort **, DetectPort *)
function for inserting a port group object. This also makes sure SigGroupContainer lists are handled correctly.
void DetectPortCleanupList (const DetectEngineCtx *de_ctx, DetectPort *head)
Free a DetectPort list and each of its members.
DetectPort * DetectPortLookupGroup (DetectPort *dp, uint16_t port)
Function that find the group matching address in a group head.
bool DetectPortListsAreEqual (DetectPort *list1, DetectPort *list2)
Checks if two port group lists are equal.
void DetectPortPrint (DetectPort *)
Helper function that print the DetectPort info.
void DetectPortPrintList (DetectPort *head)
Helper function used to print the list of ports present in this DetectPort list.
int DetectPortCmp (DetectPort *, DetectPort *)
Function that compare port groups.
void DetectPortFree (const DetectEngineCtx *de_ctx, DetectPort *)
Free a DetectPort and its members.
int DetectPortTestConfVars (void)
DetectPort * DetectPortHashLookup (DetectEngineCtx *de_ctx, DetectPort *dp)
Used to lookup a DetectPort hash from the detection engine context DetectPort hash table.
void DetectPortHashFree (DetectEngineCtx *de_ctx)
Frees the hash table - DetectEngineCtx->sgh_hash_table, allocated by DetectPortInit() function.
int DetectPortHashAdd (DetectEngineCtx *de_ctx, DetectPort *dp)
Adds a DetectPort to the detection engine context DetectPort hash table.
int DetectPortHashInit (DetectEngineCtx *de_ctx)
Initializes the hash table in the detection engine context to hold the DetectPort hash.
void DetectPortTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file detect-engine-port.h.
Function Documentation
DetectPortCleanupList()
void DetectPortCleanupList (const DetectEngineCtx * de_ctx, DetectPort * head)
Free a DetectPort list and each of its members.
Parameters
head Pointer to the DetectPort list head
Definition at line 121 of file detect-engine-port.c.
References de_ctx, DetectPortFree(), head, next, and DetectPort_::next.
Referenced by SigAddressCleanupStage1().
DetectPortCmp()
int DetectPortCmp (DetectPort * a, DetectPort * b)
Function that compare port groups.
Parameters
a pointer to DetectPort "a"
b pointer to DetectPort "b"
Return values
PORT_XX (Port enum value, XX is EQ, ES, EB, LE, etc)
PORT_ER on error
Definition at line 555 of file detect-engine-port.c.
References BUG_ON, DetectPort_::flags, DetectPort_::port, DetectPort_::port2, PORT_EB, PORT_EQ, PORT_ER, PORT_ES, PORT_FLAG_ANY, PORT_GE, PORT_GT, PORT_LE, and PORT_LT.
Referenced by DetectPortInsert(), and DetectPortListsAreEqual().
DetectPortCopySingle()
DetectPort * DetectPortCopySingle (DetectEngineCtx * de_ctx, DetectPort * src)
Function that return a copy of DetectPort src sigs.
Parameters
de_ctx Pointer to the current Detection Engine Context
src Pointer to a DetectPort group to copy
Return values
Pointer to a DetectPort instance (copy of src)
NULL on error
Definition at line 611 of file detect-engine-port.c.
References dst, and src.
DetectPortFree()
void DetectPortFree (const DetectEngineCtx * de_ctx, DetectPort * dp)
Free a DetectPort and its members.
Parameters
dp Pointer to the DetectPort that has to be freed.
Definition at line 80 of file detect-engine-port.c.
References de_ctx, DetectPort_::flags, PORT_SIGGROUPHEAD_COPY, SCFree, DetectPort_::sh, and SigGroupHeadFree().
Referenced by DetectPortCleanupList(), and DetectPortInsert().
DetectPortHashAdd()
int DetectPortHashAdd (DetectEngineCtx * de_ctx, DetectPort * dp)
Adds a DetectPort to the detection engine context DetectPort hash table.
Parameters
de_ctx Pointer to the detection engine context.
dp Pointer to the DetectPort.
Return values
ret 0 on Successfully adding the DetectPort; -1 on failure.
Definition at line 1452 of file detect-engine-port.c.
References de_ctx, DetectEngineCtx_::dport_hash_table, and HashListTableAdd().
DetectPortHashFree()
void DetectPortHashFree (DetectEngineCtx * de_ctx)
Frees the hash table - DetectEngineCtx->sgh_hash_table, allocated by DetectPortInit() function.
Parameters
de_ctx Pointer to the detection engine context.
Definition at line 1483 of file detect-engine-port.c.
References de_ctx, DetectEngineCtx_::dport_hash_table, HashListTableFree(), and DetectEngineCtx_::sgh_hash_table.
DetectPortHashInit()
int DetectPortHashInit (DetectEngineCtx * de_ctx)
Initializes the hash table in the detection engine context to hold the DetectPort hash.
Parameters
de_ctx Pointer to the detection engine context.
Return values
0 On success.
-1 On failure.
Definition at line 1432 of file detect-engine-port.c.
References de_ctx, DetectEngineCtx_::dport_hash_table, and HashListTableInit().
DetectPortHashLookup()
DetectPort * DetectPortHashLookup (DetectEngineCtx * de_ctx, DetectPort * dp)
Used to lookup a DetectPort hash from the detection engine context DetectPort hash table.
Parameters
de_ctx Pointer to the detection engine context.
sgh Pointer to the DetectPort.
Return values
rsgh On success a pointer to the DetectPort if the DetectPort is found in the hash table; NULL on failure.
Definition at line 1468 of file detect-engine-port.c.
References de_ctx, DetectEngineCtx_::dport_hash_table, HashListTableLookup(), SCEnter, and SCReturnPtr.
DetectPortInsert()
int DetectPortInsert (DetectEngineCtx * de_ctx, DetectPort ** head, DetectPort * new)
function for inserting a port group object. This also makes sure SigGroupContainer lists are handled correctly.
Parameters
de_ctx Pointer to the current detection engine context
head Pointer to the DetectPort list head
dp DetectPort to search in the DetectPort list
Return values
1 inserted
0 not inserted, memory of new is freed
-1 error
Todo:
rewrite to avoid recursive calls
Definition at line 150 of file detect-engine-port.c.
References BUG_ON, de_ctx, DetectPortCmp(), DetectPortFree(), head, DetectPort_::next, PORT_EQ, PORT_ER, PORT_GT, PORT_LT, DetectPort_::prev, SCLogDebug, DetectPort_::sh, and SigGroupHeadCopySigs().
DetectPortListsAreEqual()
bool DetectPortListsAreEqual (DetectPort * list1, DetectPort * list2)
Checks if two port group lists are equal.
Parameters
list1 Pointer to the first port group list.
list2 Pointer to the second port group list.
Return values
true On success.
false On failure.
Definition at line 699 of file detect-engine-port.c.
References DetectPortCmp(), DetectPort_::next, and PORT_EQ.
DetectPortLookupGroup()
DetectPort * DetectPortLookupGroup (DetectPort * dp, uint16_t port)
Function that find the group matching address in a group head.
Parameters
dp Pointer to DetectPort group where we try to find the group
port port to search/lookup
Return values
Pointer to the DetectPort group of our port if it matched
NULL if port is not in the list
Definition at line 674 of file detect-engine-port.c.
References DetectPort_::next.
Referenced by IPOnlyMatchPacket().
DetectPortParse()
int DetectPortParse (const DetectEngineCtx * de_ctx, DetectPort ** head, const char * str)
Function for parsing port strings.
Parameters
de_ctx Pointer to the detection engine context
head Pointer to the head of the DetectPort group list
str Pointer to the port string
Return values
0 on success
-1 on error
Definition at line 1247 of file detect-engine-port.c.
References SCLogDebug, and str.
Referenced by AppLayerProtoDetectPPRegister().
DetectPortPrint()
void DetectPortPrint (DetectPort * dp)
Helper function that print the DetectPort info.
Return values
none
Definition at line 651 of file detect-engine-port.c.
References DetectPort_::flags, DetectPort_::port, DetectPort_::port2, PORT_FLAG_ANY, and SCLogDebug.
DetectPortPrintList()
void DetectPortPrintList (DetectPort * head)
Helper function used to print the list of ports present in this DetectPort list.
Parameters
head Pointer to the DetectPort list head
Definition at line 100 of file detect-engine-port.c.
DetectPortTestConfVars()
int DetectPortTestConfVars (void)
Definition at line 1169 of file detect-engine-port.c.
References ConfGetNode(), ConfNode_::name, next, SCLogDebug, TAILQ_FOREACH, TAILQ_HEAD_INITIALIZER, and ConfNode_::val.
DetectPortTests()
void DetectPortTests (void)
Definition at line 2469 of file detect-engine-port.c.
References UtRegisterTest().