suricata: /Users/jlu/suricata/src/detect-dataset.h File Reference
detect-dataset.h File Reference
#include "datasets.h"
Data Structures
struct DetectDatasetData_
Macros
#define DETECT_DATASET_CMD_SET 0
#define DETECT_DATASET_CMD_UNSET 1
#define DETECT_DATASET_CMD_ISNOTSET 2
#define DETECT_DATASET_CMD_ISSET 3
#define DETECT_DATASET_CMD_MAX 4
Typedefs
typedef struct DetectDatasetData_ DetectDatasetData
Functions
int DetectDatasetBufferMatch (DetectEngineThreadCtx *det_ctx, const DetectDatasetData *sd, const uint8_t *data, const uint32_t data_len)
void DetectDatasetRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file detect-dataset.h.
Macro Definition Documentation
DETECT_DATASET_CMD_ISNOTSET
#define DETECT_DATASET_CMD_ISNOTSET 2
Definition at line 31 of file detect-dataset.h.
DETECT_DATASET_CMD_ISSET
#define DETECT_DATASET_CMD_ISSET 3
Definition at line 32 of file detect-dataset.h.
DETECT_DATASET_CMD_MAX
#define DETECT_DATASET_CMD_MAX 4
Definition at line 34 of file detect-dataset.h.
DETECT_DATASET_CMD_SET
#define DETECT_DATASET_CMD_SET 0
Definition at line 29 of file detect-dataset.h.
DETECT_DATASET_CMD_UNSET
#define DETECT_DATASET_CMD_UNSET 1
Definition at line 30 of file detect-dataset.h.
Typedef Documentation
DetectDatasetData
typedef struct DetectDatasetData_ DetectDatasetData
Function Documentation
DetectDatasetBufferMatch()
int DetectDatasetBufferMatch (DetectEngineThreadCtx * det_ctx, const DetectDatasetData * sd, const uint8_t * data, const uint32_t data_len)
Definition at line 61 of file detect-dataset.c.
References DetectDatasetData_::cmd, DatasetAdd(), DatasetLookup(), DETECT_DATASET_CMD_ISNOTSET, DETECT_DATASET_CMD_ISSET, DETECT_DATASET_CMD_SET, SCLogDebug, and DetectDatasetData_::set.
DetectDatasetRegister()
void DetectDatasetRegister (void)
Definition at line 47 of file detect-dataset.c.
References SigTableElmt_::desc, DETECT_DATASET, SigTableElmt_::name, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().