suricata: /Users/jlu/suricata/src/detect-template-buffer.h File Reference
detect-template-buffer.h File Reference
Functions
void DetectTemplateBufferRegister (void)
Detailed Description
Author
FirstName LastName <yourname@domain>
Definition in file detect-template-buffer.h.
Function Documentation
DetectTemplateBufferRegister()
void DetectTemplateBufferRegister (void)
Definition at line 53 of file detect-template-buffer.c.
References ConfGetNode(), SigTableElmt_::desc, DETECT_AL_TEMPLATE_BUFFER, SigTableElmt_::name, RunmodeIsUnittests(), SigTableElmt_::Setup, and sigmatch_table.
Referenced by SigTableSetup().