suricata: /Users/jlu/suricata/src/detect-base64-decode.c File Reference
detect-base64-decode.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-base64-decode.h"
#include "util-base64.h"
#include "util-byte.h"
#include "util-print.h"
#include "detect-engine-build.h"
#include "detect-engine.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "app-layer-parser.h"
#include "flow-util.h"
#include "stream-tcp.h"
Data Structures
struct DetectBase64Decode_
Macros
#define BASE64_DECODE_MAX 65535
Typedefs
typedef struct DetectBase64Decode_ DetectBase64Decode
Functions
void DetectBase64DecodeRegister (void)
int DetectBase64DecodeDoMatch (DetectEngineThreadCtx *det_ctx, const Signature *s, const SigMatchData *smd, const uint8_t *payload, uint32_t payload_len)
Macro Definition Documentation
BASE64_DECODE_MAX
#define BASE64_DECODE_MAX 65535
Definition at line 28 of file detect-base64-decode.c.
Typedef Documentation
DetectBase64Decode
typedef struct DetectBase64Decode_ DetectBase64Decode
Function Documentation
DetectBase64DecodeDoMatch()
int DetectBase64DecodeDoMatch (DetectEngineThreadCtx * det_ctx, const Signature * s, const SigMatchData * smd, const uint8_t * payload, uint32_t payload_len)
Definition at line 66 of file detect-base64-decode.c.
References DetectEngineThreadCtx_::base64_decoded, DetectEngineThreadCtx_::base64_decoded_len, DetectEngineThreadCtx_::base64_decoded_len_max, BASE64_MODE_RELAX, DetectEngineThreadCtx_::buffer_offset, DetectBase64Decode_::bytes, SigMatchData_::ctx, DecodeBase64(), MIN, DetectBase64Decode_::offset, payload_len, PrintRawDataFp(), DetectBase64Decode_::relative, and SCLogDebug.
DetectBase64DecodeRegister()
void DetectBase64DecodeRegister (void)
Definition at line 48 of file detect-base64-decode.c.
References SigTableElmt_::desc, DETECT_BASE64_DECODE, SigTableElmt_::name, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().