suricata: /Users/jlu/suricata/src/detect-ipproto.h File Reference
detect-ipproto.h File Reference
Data Structures
struct DetectIPProtoData_
Macros
#define DETECT_IPPROTO_OP_EQ '='
#define DETECT_IPPROTO_OP_NOT '!'
#define DETECT_IPPROTO_OP_LT '<'
#define DETECT_IPPROTO_OP_GT '>'
Typedefs
typedef struct DetectIPProtoData_ DetectIPProtoData
Functions
void DetectIPProtoRegister (void)
Registration function for ip_proto keyword.
void DetectIPProtoRemoveAllSMs (DetectEngineCtx *, Signature *)
Detailed Description
Author
Brian Rectanus brect.nosp@m.anu@.nosp@m.gmail.nosp@m..com
Definition in file detect-ipproto.h.
Macro Definition Documentation
DETECT_IPPROTO_OP_EQ
#define DETECT_IPPROTO_OP_EQ '='
IPProto Operators "equals" operator (default)
Definition at line 28 of file detect-ipproto.h.
DETECT_IPPROTO_OP_GT
#define DETECT_IPPROTO_OP_GT '>'
"greater than" operator
Definition at line 31 of file detect-ipproto.h.
DETECT_IPPROTO_OP_LT
#define DETECT_IPPROTO_OP_LT '<'
"less than" operator
Definition at line 30 of file detect-ipproto.h.
DETECT_IPPROTO_OP_NOT
#define DETECT_IPPROTO_OP_NOT '!'
"not" operator
Definition at line 29 of file detect-ipproto.h.
Typedef Documentation
DetectIPProtoData
typedef struct DetectIPProtoData_ DetectIPProtoData
ip_proto data
Function Documentation
DetectIPProtoRegister()
void DetectIPProtoRegister (void)
Registration function for ip_proto keyword.
Definition at line 60 of file detect-ipproto.c.
References SigTableElmt_::desc, DETECT_IPPROTO, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
DetectIPProtoRemoveAllSMs()
void DetectIPProtoRemoveAllSMs (DetectEngineCtx * de_ctx, Signature * s)
Definition at line 430 of file detect-ipproto.c.
References de_ctx, DETECT_IPPROTO, DETECT_SM_LIST_MATCH, Signature_::init_data, SigMatch_::next, SigMatchFree(), SigMatchRemoveSMFromList(), SignatureInitData_::smlists, and SigMatch_::type.