suricata: /Users/jlu/suricata/src/detect-metadata.c File Reference
detect-metadata.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-metadata.h"
#include "util-hash-string.h"
#include "util-unittest.h"
#include "rust.h"
#include "util-validate.h"
Macros
#define MD_STR "\"metadata\":"
#define MD_STR_LEN (sizeof(MD_STR) - 1)
Functions
void DetectMetadataRegister (void)
void DetectMetadataFree (DetectMetadata *mdata)
Free a Metadata object.
int DetectMetadataHashInit (DetectEngineCtx *de_ctx)
void DetectMetadataHashFree (DetectEngineCtx *de_ctx)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Implements metadata keyword support
Todo:
Do we need to do anything more this is used in snort host attribute table It is also used for rule managment.
Definition in file detect-metadata.c.
Macro Definition Documentation
MD_STR
#define MD_STR "\"metadata\":"
MD_STR_LEN
#define MD_STR_LEN (sizeof(MD_STR) - 1)
Function Documentation
DetectMetadataFree()
void DetectMetadataFree (DetectMetadata * mdata)
Free a Metadata object.
Definition at line 60 of file detect-metadata.c.
References SCEnter, SCFree, and SCReturn.
DetectMetadataHashFree()
void DetectMetadataHashFree (DetectEngineCtx * de_ctx)
Definition at line 80 of file detect-metadata.c.
References de_ctx, HashTableFree(), and DetectEngineCtx_::metadata_table.
DetectMetadataHashInit()
int DetectMetadataHashInit (DetectEngineCtx * de_ctx)
Definition at line 69 of file detect-metadata.c.
References de_ctx, DetectEngineMustParseMetadata(), HashTableInit(), DetectEngineCtx_::metadata_table, StringHashCompareFunc(), StringHashFreeFunc(), and StringHashFunc().
DetectMetadataRegister()
void DetectMetadataRegister (void)
Definition at line 44 of file detect-metadata.c.
References SigTableElmt_::desc, DETECT_METADATA, SigTableElmt_::Match, SigTableElmt_::name, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().