suricata: /Users/jlu/suricata/src/detect-http-headers.h File Reference
detect-http-headers.h File Reference
Functions
void DetectHttpHeadersRegister (void)
Function Documentation
DetectHttpHeadersRegister()
void DetectHttpHeadersRegister (void)
Definition at line 29 of file detect-http-headers.c.
References RegisterHttpHeadersAccept(), RegisterHttpHeadersAcceptEnc(), RegisterHttpHeadersAcceptLang(), RegisterHttpHeadersConnection(), RegisterHttpHeadersContentLen(), RegisterHttpHeadersContentType(), RegisterHttpHeadersLocation(), RegisterHttpHeadersReferer(), and RegisterHttpHeadersServer().
Referenced by SigTableSetup().