suricata: /Users/jlu/suricata/src/detect-engine-mpm.c File Reference
detect-engine-mpm.c File Reference
#include "suricata.h"
#include "suricata-common.h"
#include "app-layer-protos.h"
#include "decode.h"
#include "detect.h"
#include "detect-engine.h"
#include "detect-engine-siggroup.h"
#include "detect-engine-mpm.h"
#include "detect-engine-iponly.h"
#include "detect-parse.h"
#include "detect-engine-prefilter.h"
#include "util-mpm.h"
#include "util-memcmp.h"
#include "util-memcpy.h"
#include "conf.h"
#include "detect-fast-pattern.h"
#include "detect-tcphdr.h"
#include "detect-udphdr.h"
#include "flow.h"
#include "flow-var.h"
#include "detect-flow.h"
#include "detect-content.h"
#include "detect-engine-payload.h"
#include "stream.h"
#include "util-misc.h"
#include "util-enum.h"
#include "util-debug.h"
#include "util-print.h"
#include "util-validate.h"
#include "util-hash-string.h"
Data Structures
struct SidsArray
Macros
#define SGH_PROTO(sgh, p) ((sgh)->init->protos[(p)] == 1)
#define SGH_DIRECTION_TS(sgh) ((sgh)->init->direction & SIG_FLAG_TOSERVER)
#define SGH_DIRECTION_TC(sgh) ((sgh)->init->direction & SIG_FLAG_TOCLIENT)
Functions
void DetectAppLayerMpmRegister2 (const char *name, int direction, int priority, int(*PrefilterRegister)(DetectEngineCtx *de_ctx, SigGroupHead *sgh, MpmCtx *mpm_ctx, const DetectBufferMpmRegistery *mpm_reg, int list_id), InspectionBufferGetDataPtr GetData, AppProto alproto, int tx_min_progress)
register a MPM engine
void DetectAppLayerMpmRegisterByParentId (DetectEngineCtx *de_ctx, const int id, const int parent_id, DetectEngineTransforms *transforms)
copy a mpm engine from parent_id, add in transforms
void DetectMpmInitializeAppMpms (DetectEngineCtx *de_ctx)
int DetectMpmPrepareAppMpms (DetectEngineCtx *de_ctx)
initialize mpm contexts for applayer buffers that are in "single or "shared" mode.
void DetectFrameMpmRegister (const char *name, int direction, int priority, int(*PrefilterRegister)(DetectEngineCtx *de_ctx, SigGroupHead *sgh, MpmCtx *mpm_ctx, const DetectBufferMpmRegistery *mpm_reg, int list_id), AppProto alproto, uint8_t type)
register a MPM engine
void DetectFrameMpmRegisterByParentId (DetectEngineCtx *de_ctx, const int id, const int parent_id, DetectEngineTransforms *transforms)
copy a mpm engine from parent_id, add in transforms
void DetectEngineFrameMpmRegister (DetectEngineCtx *de_ctx, const char *name, int direction, int priority, int(*PrefilterRegister)(DetectEngineCtx *de_ctx, SigGroupHead *sgh, MpmCtx *mpm_ctx, const DetectBufferMpmRegistery *mpm_reg, int list_id), AppProto alproto, uint8_t type)
void DetectMpmInitializeFrameMpms (DetectEngineCtx *de_ctx)
int DetectMpmPrepareFrameMpms (DetectEngineCtx *de_ctx)
initialize mpm contexts for applayer buffers that are in "single or "shared" mode.
void DetectPktMpmRegister (const char *name, int priority, int(*PrefilterRegister)(DetectEngineCtx *de_ctx, SigGroupHead *sgh, MpmCtx *mpm_ctx, const DetectBufferMpmRegistery *mpm_reg, int list_id), InspectionBufferGetPktDataPtr GetData)
register a MPM engine
void DetectPktMpmRegisterByParentId (DetectEngineCtx *de_ctx, const int id, const int parent_id, DetectEngineTransforms *transforms)
copy a mpm engine from parent_id, add in transforms
void DetectMpmInitializePktMpms (DetectEngineCtx *de_ctx)
int DetectMpmPreparePktMpms (DetectEngineCtx *de_ctx)
initialize mpm contexts for applayer buffers that are in "single or "shared" mode.
void DetectMpmInitializeBuiltinMpms (DetectEngineCtx *de_ctx)
int DetectMpmPrepareBuiltinMpms (DetectEngineCtx *de_ctx)
initialize mpm contexts for builtin buffers that are in "single or "shared" mode.
int SignatureHasPacketContent (const Signature *s)
check if a signature has patterns that are to be inspected against a packets payload (as opposed to the stream payload)
int SignatureHasStreamContent (const Signature *s)
check if a signature has patterns that are to be inspected against the stream payload (as opposed to the individual packets payload(s))
uint8_t PatternMatchDefaultMatcher (void)
Function to return the multi pattern matcher algorithm to be used by the engine, based on the mpm-algo setting in yaml Use the default mpm if none is specified in the yaml file.
void PatternMatchDestroy (MpmCtx *mpm_ctx, uint16_t mpm_matcher)
void PatternMatchThreadPrint (MpmThreadCtx *mpm_thread_ctx, uint16_t mpm_matcher)
void PatternMatchThreadDestroy (MpmThreadCtx *mpm_thread_ctx, uint16_t mpm_matcher)
void PatternMatchThreadPrepare (MpmThreadCtx *mpm_thread_ctx, uint16_t mpm_matcher)
uint32_t PatternStrength (uint8_t *pat, uint16_t patlen)
Predict a strength value for patterns.
void RetrieveFPForSig (const DetectEngineCtx *de_ctx, Signature *s)
int MpmStoreInit (DetectEngineCtx *de_ctx)
Initializes the MpmStore mpm hash table to be used by the detection engine context.
void MpmStoreReportStats (const DetectEngineCtx *de_ctx)
void MpmStoreFree (DetectEngineCtx *de_ctx)
Frees the hash table - DetectEngineCtx->mpm_hash_table, allocated by MpmStoreInit() function.
MpmStore * MpmStorePrepareBuffer (DetectEngineCtx *de_ctx, SigGroupHead *sgh, enum MpmBuiltinBuffers buf)
Get MpmStore for a built-in buffer type.
int PatternMatchPrepareGroup (DetectEngineCtx *de_ctx, SigGroupHead *sh)
Prepare the pattern matcher ctx in a sig group head.
int DetectSetFastPatternAndItsId (DetectEngineCtx *de_ctx)
Figure out the FP and their respective content ids for all the sigs in the engine.
void EngineAnalysisAddAllRulePatterns (DetectEngineCtx *de_ctx, const Signature *s)
add all patterns on our stats hash Used to fill the hash later used by DumpPatterns()
Variables
const char * builtin_mpms []
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Multi pattern matcher
Definition in file detect-engine-mpm.c.
Macro Definition Documentation
SGH_DIRECTION_TC
#define SGH_DIRECTION_TC (sgh) ((sgh)->init->direction & SIG_FLAG_TOCLIENT)
Definition at line 1014 of file detect-engine-mpm.c.
SGH_DIRECTION_TS
#define SGH_DIRECTION_TS (sgh) ((sgh)->init->direction & SIG_FLAG_TOSERVER)
Definition at line 1013 of file detect-engine-mpm.c.
SGH_PROTO
#define SGH_PROTO (sgh, p) ((sgh)->init->protos[(p)] == 1)
Definition at line 1012 of file detect-engine-mpm.c.
Function Documentation
DetectAppLayerMpmRegister2()
void DetectAppLayerMpmRegister2 (const char * name, int direction, int priority, int(*)(DetectEngineCtx *de_ctx, SigGroupHead *sgh, MpmCtx *mpm_ctx, const DetectBufferMpmRegistery *mpm_reg, int list_id) PrefilterRegister, InspectionBufferGetDataPtr GetData, AppProto alproto, int tx_min_progress)
register a MPM engine
register an app layer keyword for mpm
Note
to be used at start up / registration only. Errors are fatal.
Definition at line 89 of file detect-engine-mpm.c.
DetectAppLayerMpmRegisterByParentId()
void DetectAppLayerMpmRegisterByParentId (DetectEngineCtx * de_ctx, const int id, const int parent_id, DetectEngineTransforms * transforms)
copy a mpm engine from parent_id, add in transforms
Definition at line 148 of file detect-engine-mpm.c.
References DetectBufferMpmRegistery_::alproto, DetectEngineCtx_::app_mpms_list, DetectEngineCtx_::app_mpms_list_cnt, DetectBufferMpmRegistery_::app_v2, BUG_ON, DetectEngineTransforms::cnt, de_ctx, DEBUG_VALIDATE_BUG_ON, DETECT_BUFFER_MPM_TYPE_APP, DetectEngineRegisterFastPatternForId(), DetectBufferMpmRegistery_::direction, DetectBufferMpmRegistery_::GetData, DetectBufferMpmRegistery_::id, MpmFactoryRegisterMpmCtxProfile(), DetectBufferMpmRegistery_::name, SigTableElmt_::name, DetectBufferMpmRegistery_::next, DetectBufferMpmRegistery_::pname, DetectBufferMpmRegistery_::PrefilterRegisterWithListId, DetectBufferMpmRegistery_::priority, SCCalloc, SCLogDebug, DetectBufferMpmRegistery_::sgh_mpm_context, ShortenString(), sigmatch_table, DetectBufferMpmRegistery_::sm_list, DetectBufferMpmRegistery_::sm_list_base, strlcat(), strlcpy(), TransformData_::transform, DetectEngineTransforms::transforms, DetectBufferMpmRegistery_::transforms, DetectBufferMpmRegistery_::tx_min_progress, and DetectBufferMpmRegistery_::type.
Referenced by DetectEngineBufferTypeGetByIdTransforms().
DetectEngineFrameMpmRegister()
void DetectEngineFrameMpmRegister (DetectEngineCtx * de_ctx, const char * name, int direction, int priority, int(*)(DetectEngineCtx *de_ctx, SigGroupHead *sgh, MpmCtx *mpm_ctx, const DetectBufferMpmRegistery *mpm_reg, int list_id) PrefilterRegister, AppProto alproto, uint8_t type)
Definition at line 380 of file detect-engine-mpm.c.
References DetectBufferMpmRegistery_::alproto, AppProtoToString(), BUG_ON, ConfGetBool(), de_ctx, DETECT_BUFFER_MPM_TYPE_FRAME, DetectEngineBufferTypeRegister(), DetectEngineBufferTypeSupportsFrames(), DetectEngineBufferTypeSupportsMpm(), DetectEngineBufferTypeSupportsTransformations(), DetectEngineRegisterFastPatternForId(), DetectBufferMpmRegistery_::direction, ENGINE_SGH_MPM_FACTORY_CONTEXT_SINGLE, FatalError, DetectEngineCtx_::frame_mpms_list, DetectEngineCtx_::frame_mpms_list_cnt, DetectBufferMpmRegistery_::frame_v1, MPM_CTX_FACTORY_UNIQUE_CONTEXT, MpmFactoryRegisterMpmCtxProfile(), DetectBufferMpmRegistery_::name, DetectBufferMpmRegistery_::next, DetectBufferMpmRegistery_::pname, DetectBufferMpmRegistery_::PrefilterRegisterWithListId, DetectBufferMpmRegistery_::priority, SC_ERR_INITIALIZATION, SCCalloc, SCLogDebug, DetectBufferMpmRegistery_::sgh_mpm_context, DetectEngineCtx_::sgh_mpm_ctx_cnf, DetectBufferMpmRegistery_::sm_list, type, and DetectBufferMpmRegistery_::type.
DetectFrameMpmRegister()
void DetectFrameMpmRegister (const char * name, int direction, int priority, int(*)(DetectEngineCtx *de_ctx, SigGroupHead *sgh, MpmCtx *mpm_ctx, const DetectBufferMpmRegistery *mpm_reg, int list_id) PrefilterRegister, AppProto alproto, uint8_t type)
register a MPM engine
Note
to be used at start up / registration only. Errors are fatal.
Definition at line 293 of file detect-engine-mpm.c.
References DetectBufferMpmRegistery_::alproto, AppProtoToString(), BUG_ON, DETECT_BUFFER_MPM_TYPE_FRAME, DetectBufferTypeGetByName(), DetectBufferTypeSupportsFrames(), DetectBufferTypeSupportsMpm(), DetectBufferTypeSupportsTransformations(), DetectBufferMpmRegistery_::direction, FatalError, DetectBufferMpmRegistery_::frame_v1, DetectBufferMpmRegistery_::name, DetectBufferMpmRegistery_::pname, DetectBufferMpmRegistery_::PrefilterRegisterWithListId, DetectBufferMpmRegistery_::priority, SC_ERR_INITIALIZATION, SCCalloc, SCLogDebug, DetectBufferMpmRegistery_::sm_list, type, and DetectBufferMpmRegistery_::type.
DetectFrameMpmRegisterByParentId()
void DetectFrameMpmRegisterByParentId (DetectEngineCtx * de_ctx, const int id, const int parent_id, DetectEngineTransforms * transforms)
copy a mpm engine from parent_id, add in transforms
Definition at line 341 of file detect-engine-mpm.c.
References BUG_ON, de_ctx, DEBUG_VALIDATE_BUG_ON, DETECT_BUFFER_MPM_TYPE_FRAME, DetectEngineRegisterFastPatternForId(), DetectBufferMpmRegistery_::direction, DetectEngineCtx_::frame_mpms_list, DetectEngineCtx_::frame_mpms_list_cnt, DetectBufferMpmRegistery_::frame_v1, DetectBufferMpmRegistery_::id, DetectBufferMpmRegistery_::name, DetectBufferMpmRegistery_::next, DetectBufferMpmRegistery_::pname, DetectBufferMpmRegistery_::PrefilterRegisterWithListId, DetectBufferMpmRegistery_::priority, SCCalloc, SCLogDebug, DetectBufferMpmRegistery_::sgh_mpm_context, DetectBufferMpmRegistery_::sm_list, DetectBufferMpmRegistery_::sm_list_base, DetectBufferMpmRegistery_::transforms, and DetectBufferMpmRegistery_::type.
Referenced by DetectEngineBufferTypeGetByIdTransforms().
DetectMpmInitializeAppMpms()
void DetectMpmInitializeAppMpms (DetectEngineCtx * de_ctx)
Definition at line 215 of file detect-engine-mpm.c.
DetectMpmInitializeBuiltinMpms()
void DetectMpmInitializeBuiltinMpms (DetectEngineCtx * de_ctx)
Definition at line 716 of file detect-engine-mpm.c.
References de_ctx, and DetectEngineCtx_::sgh_mpm_context_proto_tcp_packet.
DetectMpmInitializeFrameMpms()
void DetectMpmInitializeFrameMpms (DetectEngineCtx * de_ctx)
Definition at line 442 of file detect-engine-mpm.c.
DetectMpmInitializePktMpms()
void DetectMpmInitializePktMpms (DetectEngineCtx * de_ctx)
Definition at line 615 of file detect-engine-mpm.c.
DetectMpmPrepareAppMpms()
int DetectMpmPrepareAppMpms (DetectEngineCtx * de_ctx)
initialize mpm contexts for applayer buffers that are in "single or "shared" mode.
Definition at line 268 of file detect-engine-mpm.c.
References DetectEngineCtx_::app_mpms_list, de_ctx, DetectBufferMpmRegistery_::direction, MPM_CTX_FACTORY_UNIQUE_CONTEXT, DetectEngineCtx_::mpm_matcher, mpm_table, MpmFactoryGetMpmCtxForProfile(), DetectBufferMpmRegistery_::next, MpmTableElmt_::Prepare, DetectBufferMpmRegistery_::sgh_mpm_context, and SIG_FLAG_TOSERVER.
DetectMpmPrepareBuiltinMpms()
int DetectMpmPrepareBuiltinMpms (DetectEngineCtx * de_ctx)
initialize mpm contexts for builtin buffers that are in "single or "shared" mode.
Definition at line 729 of file detect-engine-mpm.c.
References de_ctx, MPM_CTX_FACTORY_UNIQUE_CONTEXT, DetectEngineCtx_::mpm_matcher, mpm_table, MpmFactoryGetMpmCtxForProfile(), MpmTableElmt_::Prepare, DetectEngineCtx_::sgh_mpm_context_proto_other_packet, DetectEngineCtx_::sgh_mpm_context_proto_tcp_packet, DetectEngineCtx_::sgh_mpm_context_proto_udp_packet, and DetectEngineCtx_::sgh_mpm_context_stream.
DetectMpmPrepareFrameMpms()
int DetectMpmPrepareFrameMpms (DetectEngineCtx * de_ctx)
initialize mpm contexts for applayer buffers that are in "single or "shared" mode.
Definition at line 497 of file detect-engine-mpm.c.
References de_ctx, DetectBufferMpmRegistery_::direction, DetectEngineCtx_::frame_mpms_list, MPM_CTX_FACTORY_UNIQUE_CONTEXT, DetectEngineCtx_::mpm_matcher, mpm_table, MpmFactoryGetMpmCtxForProfile(), DetectBufferMpmRegistery_::name, DetectBufferMpmRegistery_::next, MpmTableElmt_::Prepare, SCLogDebug, DetectBufferMpmRegistery_::sgh_mpm_context, and SIG_FLAG_TOSERVER.
DetectMpmPreparePktMpms()
int DetectMpmPreparePktMpms (DetectEngineCtx * de_ctx)
initialize mpm contexts for applayer buffers that are in "single or "shared" mode.
Definition at line 670 of file detect-engine-mpm.c.
References de_ctx, MPM_CTX_FACTORY_UNIQUE_CONTEXT, DetectEngineCtx_::mpm_matcher, mpm_table, MpmFactoryGetMpmCtxForProfile(), DetectBufferMpmRegistery_::name, DetectBufferMpmRegistery_::next, DetectEngineCtx_::pkt_mpms_list, MpmTableElmt_::Prepare, SCLogDebug, and DetectBufferMpmRegistery_::sgh_mpm_context.
DetectPktMpmRegister()
void DetectPktMpmRegister (const char * name, int priority, int(*)(DetectEngineCtx *de_ctx, SigGroupHead *sgh, MpmCtx *mpm_ctx, const DetectBufferMpmRegistery *mpm_reg, int list_id) PrefilterRegister, InspectionBufferGetPktDataPtr GetData)
register a MPM engine
Note
to be used at start up / registration only. Errors are fatal.
Definition at line 525 of file detect-engine-mpm.c.
DetectPktMpmRegisterByParentId()
void DetectPktMpmRegisterByParentId (DetectEngineCtx * de_ctx, const int id, const int parent_id, DetectEngineTransforms * transforms)
copy a mpm engine from parent_id, add in transforms
Definition at line 577 of file detect-engine-mpm.c.
References BUG_ON, de_ctx, DEBUG_VALIDATE_BUG_ON, DETECT_BUFFER_MPM_TYPE_PKT, DetectEngineRegisterFastPatternForId(), DetectBufferMpmRegistery_::GetData, DetectBufferMpmRegistery_::id, DetectBufferMpmRegistery_::name, DetectBufferMpmRegistery_::next, DetectEngineCtx_::pkt_mpms_list, DetectEngineCtx_::pkt_mpms_list_cnt, DetectBufferMpmRegistery_::pkt_v1, DetectBufferMpmRegistery_::pname, DetectBufferMpmRegistery_::PrefilterRegisterWithListId, DetectBufferMpmRegistery_::priority, SCCalloc, SCLogDebug, DetectBufferMpmRegistery_::sgh_mpm_context, DetectBufferMpmRegistery_::sm_list, DetectBufferMpmRegistery_::sm_list_base, DetectBufferMpmRegistery_::transforms, and DetectBufferMpmRegistery_::type.
Referenced by DetectEngineBufferTypeGetByIdTransforms().
DetectSetFastPatternAndItsId()
int DetectSetFastPatternAndItsId (DetectEngineCtx * de_ctx)
Figure out the FP and their respective content ids for all the sigs in the engine.
Parameters
de_ctx Detection engine context.
Return values
0 On success.
-1 On failure.
Definition at line 2246 of file detect-engine-mpm.c.
Referenced by SigGroupBuild().
EngineAnalysisAddAllRulePatterns()
void EngineAnalysisAddAllRulePatterns (DetectEngineCtx * de_ctx, const Signature * s)
add all patterns on our stats hash Used to fill the hash later used by DumpPatterns()
Note
sets up the hash table on first call
Definition at line 2310 of file detect-engine-mpm.c.
References de_ctx, HashListTableInit(), and DetectEngineCtx_::pattern_hash_table.
MpmStoreFree()
void MpmStoreFree (DetectEngineCtx * de_ctx)
Frees the hash table - DetectEngineCtx->mpm_hash_table, allocated by MpmStoreInit() function.
Parameters
de_ctx Pointer to the detection engine context.
Definition at line 1459 of file detect-engine-mpm.c.
References de_ctx, HashListTableFree(), and DetectEngineCtx_::mpm_hash_table.
Referenced by DetectEngineCtxFree().
MpmStoreInit()
int MpmStoreInit (DetectEngineCtx * de_ctx)
Initializes the MpmStore mpm hash table to be used by the detection engine context.
Parameters
de_ctx Pointer to the detection engine context.
Return values
0 On success.
-1 On failure.
Definition at line 1295 of file detect-engine-mpm.c.
References de_ctx, HashListTableInit(), and DetectEngineCtx_::mpm_hash_table.
MpmStorePrepareBuffer()
MpmStore * MpmStorePrepareBuffer (DetectEngineCtx * de_ctx, SigGroupHead * sgh, enum MpmBuiltinBuffers buf)
Get MpmStore for a built-in buffer type.
Definition at line 1569 of file detect-engine-mpm.c.
Referenced by PatternMatchPrepareGroup().
MpmStoreReportStats()
void MpmStoreReportStats (const DetectEngineCtx * de_ctx)
Definition at line 1361 of file detect-engine-mpm.c.
References MpmStore_::buffer, DetectEngineCtx_::buffer_type_id, de_ctx, DETECT_SM_LIST_PMATCH, HashListTableGetListData, HashListTableGetListHead(), HashListTableGetListNext, MpmStore_::mpm_ctx, DetectEngineCtx_::mpm_hash_table, MPMB_MAX, and MpmStore_::sm_list.
PatternMatchDefaultMatcher()
uint8_t PatternMatchDefaultMatcher (void)
Function to return the multi pattern matcher algorithm to be used by the engine, based on the mpm-algo setting in yaml Use the default mpm if none is specified in the yaml file.
Return values
mpm algo value
Definition at line 856 of file detect-engine-mpm.c.
References ConfGet(), FatalError, mpm_default_matcher, mpm_table, MPM_TABLE_SIZE, SC_ERR_FATAL, SC_ERR_INVALID_VALUE, and SC_ERR_INVALID_YAML_CONF_ENTRY.
PatternMatchDestroy()
void PatternMatchDestroy (MpmCtx * mpm_ctx, uint16_t mpm_matcher)
Definition at line 898 of file detect-engine-mpm.c.
References MpmTableElmt_::DestroyCtx, mpm_table, and SCLogDebug.
PatternMatchPrepareGroup()
int PatternMatchPrepareGroup (DetectEngineCtx * de_ctx, SigGroupHead * sh)
Prepare the pattern matcher ctx in a sig group head.
Definition at line 2055 of file detect-engine-mpm.c.
References de_ctx, MpmStore_::mpm_ctx, MPMB_TCP_PKT_TS, MPMB_TCP_STREAM_TS, MpmStorePrepareBuffer(), PrefilterPktPayloadRegister(), PrefilterPktStreamRegister(), SGH_DIRECTION_TS, and SGH_PROTO.
Referenced by PrefilterSetupRuleGroup().
PatternMatchThreadDestroy()
void PatternMatchThreadDestroy (MpmThreadCtx * mpm_thread_ctx, uint16_t mpm_matcher)
Definition at line 909 of file detect-engine-mpm.c.
References MpmTableElmt_::DestroyThreadCtx, mpm_table, and SCLogDebug.
PatternMatchThreadPrepare()
void PatternMatchThreadPrepare (MpmThreadCtx * mpm_thread_ctx, uint16_t mpm_matcher)
Definition at line 915 of file detect-engine-mpm.c.
References MpmInitThreadCtx(), and SCLogDebug.
PatternMatchThreadPrint()
void PatternMatchThreadPrint (MpmThreadCtx * mpm_thread_ctx, uint16_t mpm_matcher)
Definition at line 904 of file detect-engine-mpm.c.
References SCLogDebug.
Referenced by DetectEngineThreadCtxInfo().
PatternStrength()
uint32_t PatternStrength (uint8_t * pat, uint16_t patlen)
Predict a strength value for patterns.
Patterns with high character diversity score higher. Alpha chars score not so high Other printable + a few common codes a little higher Everything else highest. Longer patterns score better than short patters.
Parameters
pat pattern
patlen length of the pattern
Return values
s pattern score
Definition at line 934 of file detect-engine-mpm.c.
RetrieveFPForSig()
void RetrieveFPForSig (const DetectEngineCtx * de_ctx, Signature * s)
Definition at line 1080 of file detect-engine-mpm.c.
References SigMatch_::ctx, de_ctx, DETECT_CONTENT, DETECT_CONTENT_FAST_PATTERN, DETECT_SM_LIST_PMATCH, DETECT_SM_LIST_POSTMATCH, DETECT_SM_LIST_SUPPRESS, DETECT_SM_LIST_THRESHOLD, DETECT_SM_LIST_TMATCH, FastPatternSupportEnabledForSigMatchList(), DetectContentData_::flags, Signature_::init_data, SignatureInitData_::mpm_sm, SigMatch_::next, SignatureInitData_::smlists, SignatureInitData_::smlists_array_size, and SigMatch_::type.
SignatureHasPacketContent()
int SignatureHasPacketContent (const Signature * s)
check if a signature has patterns that are to be inspected against a packets payload (as opposed to the stream payload)
Parameters
s signature
Return values
1 true
0 false
Definition at line 786 of file detect-engine-mpm.c.
References DETECT_SM_LIST_PMATCH, Signature_::flags, Signature_::init_data, DetectProto_::proto, Signature_::proto, SCEnter, SCLogDebug, SCReturnInt, SIG_FLAG_REQUIRE_PACKET, Signature_::sm_arrays, and SignatureInitData_::smlists.
SignatureHasStreamContent()
int SignatureHasStreamContent (const Signature * s)
check if a signature has patterns that are to be inspected against the stream payload (as opposed to the individual packets payload(s))
Parameters
s signature
Return values
1 true
0 false
Definition at line 822 of file detect-engine-mpm.c.
References DETECT_SM_LIST_PMATCH, Signature_::flags, Signature_::init_data, DetectProto_::proto, Signature_::proto, SCEnter, SCLogDebug, SCReturnInt, SIG_FLAG_REQUIRE_STREAM, Signature_::sm_arrays, and SignatureInitData_::smlists.
Variable Documentation
builtin_mpms
const char* builtin_mpms[]
Initial value:
= {
    "toserver TCP packet",
    "toclient TCP packet",
    "toserver TCP stream",
    "toclient TCP stream",
    "toserver UDP packet",
    "toclient UDP packet",
    "other IP packet",
    NULL }
Definition at line 66 of file detect-engine-mpm.c.