suricata: /Users/jlu/suricata/src/detect-tls-random.c File Reference
detect-tls-random.c File Reference
#include "suricata-common.h"
#include "threads.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-content.h"
#include "flow.h"
#include "stream-tcp.h"
#include "app-layer.h"
#include "app-layer-ssl.h"
#include "detect-engine-prefilter.h"
#include "detect-tls-random.h"
Macros
#define DETECT_TLS_RANDOM_TIME_LEN 4
#define DETECT_TLS_RANDOM_BYTES_LEN 28
Functions
void DetectTlsRandomTimeRegister (void)
void DetectTlsRandomBytesRegister (void)
void DetectTlsRandomRegister (void)
Registration function for keyword: tls.random.
Macro Definition Documentation
DETECT_TLS_RANDOM_BYTES_LEN
#define DETECT_TLS_RANDOM_BYTES_LEN 28
Definition at line 36 of file detect-tls-random.c.
DETECT_TLS_RANDOM_TIME_LEN
#define DETECT_TLS_RANDOM_TIME_LEN 4
Definition at line 35 of file detect-tls-random.c.
Function Documentation
DetectTlsRandomBytesRegister()
void DetectTlsRandomBytesRegister (void)
Definition at line 81 of file detect-tls-random.c.
References SigTableElmt_::desc, DETECT_AL_TLS_RANDOM_BYTES, SigTableElmt_::name, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by DetectTlsRandomRegister().
DetectTlsRandomRegister()
void DetectTlsRandomRegister (void)
Registration function for keyword: tls.random.
Definition at line 112 of file detect-tls-random.c.
References SigTableElmt_::desc, DETECT_AL_TLS_RANDOM, DetectTlsRandomBytesRegister(), DetectTlsRandomTimeRegister(), SigTableElmt_::name, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by SigTableSetup().
DetectTlsRandomTimeRegister()
void DetectTlsRandomTimeRegister (void)
Definition at line 55 of file detect-tls-random.c.
References SigTableElmt_::desc, DETECT_AL_TLS_RANDOM_TIME, SigTableElmt_::name, SigTableElmt_::Setup, sigmatch_table, and SigTableElmt_::url.
Referenced by DetectTlsRandomRegister().