suricata: /Users/jlu/suricata/src/detect-engine-build.h File Reference
detect-engine-build.h File Reference
Functions
void PacketCreateMask (Packet *p, SignatureMask *mask, AppProto alproto, bool app_decoder_events)
int SignatureIsFilestoring (const Signature *)
Check if a signature contains the filestore keyword.
int SignatureIsFilemagicInspecting (const Signature *)
Check if a signature contains the filemagic keyword.
int SignatureIsFileMd5Inspecting (const Signature *)
Check if a signature contains the filemd5 keyword.
int SignatureIsFileSha1Inspecting (const Signature *s)
Check if a signature contains the filesha1 keyword.
int SignatureIsFileSha256Inspecting (const Signature *s)
Check if a signature contains the filesha256 keyword.
int SignatureIsFilesizeInspecting (const Signature *)
Check if a signature contains the filesize keyword.
void SignatureSetType (DetectEngineCtx *de_ctx, Signature *s)
int SigAddressPrepareStage1 (DetectEngineCtx *de_ctx)
Preprocess signature, classify ip-only, etc, build sig array.
int SigAddressPrepareStage2 (DetectEngineCtx *de_ctx)
Fill the global src group head, with the sigs included.
int SigAddressPrepareStage3 (DetectEngineCtx *de_ctx)
int SigAddressPrepareStage4 (DetectEngineCtx *de_ctx)
finalize preparing sgh's
int SigAddressCleanupStage1 (DetectEngineCtx *de_ctx)
void SigCleanSignatures (DetectEngineCtx *)
int SigGroupBuild (DetectEngineCtx *)
Convert the signature list into the runtime match structure.
int SigGroupCleanup (DetectEngineCtx *de_ctx)
Function Documentation
PacketCreateMask()
void PacketCreateMask (Packet * p, SignatureMask * mask, AppProto alproto, bool app_decoder_events)
Definition at line 410 of file detect-engine-build.c.
References ALPROTO_DCERPC, ALPROTO_SMB, Packet_::app_layer_events, PacketEngineEvents_::cnt, Packet_::events, Packet_::flags, MASK_TCP_INITDEINIT_FLAGS, MASK_TCP_UNUSUAL_FLAGS, Packet_::payload_len, PKT_DETECT_HAS_STREAMDATA, PKT_HAS_FLOW, PKT_IS_PSEUDOPKT, PKT_IS_TCP, PKT_NOPAYLOAD_INSPECTION, SCLogDebug, SIG_MASK_REQUIRE_DCERPC, SIG_MASK_REQUIRE_ENGINE_EVENT, SIG_MASK_REQUIRE_FLAGS_INITDEINIT, SIG_MASK_REQUIRE_FLAGS_UNUSUAL, SIG_MASK_REQUIRE_FLOW, SIG_MASK_REQUIRE_NO_PAYLOAD, SIG_MASK_REQUIRE_PAYLOAD, and Packet_::tcph.
SigAddressCleanupStage1()
int SigAddressCleanupStage1 (DetectEngineCtx * de_ctx)
Definition at line 1741 of file detect-engine-build.c.
References BUG_ON, de_ctx, DE_QUIET, DetectEngineCtx_::decoder_event_sgh, DetectPortCleanupList(), DetectEngineCtx_::flags, DetectEngineCtx_::flow_gh, FLOW_STATES, DetectEngineCtx_::io_ctx, IPOnlyDeinit(), SCFree, SCLogDebug, SCLogInfo, DetectEngineLookupFlow_::sgh, DetectEngineCtx_::sgh_array, DetectEngineCtx_::sgh_array_cnt, DetectEngineCtx_::sgh_array_size, SigGroupHeadFree(), DetectEngineLookupFlow_::tcp, and DetectEngineLookupFlow_::udp.
Referenced by SigGroupCleanup().
SigAddressPrepareStage1()
int SigAddressPrepareStage1 (DetectEngineCtx * de_ctx)
Preprocess signature, classify ip-only, etc, build sig array.
Parameters
de_ctx Pointer to the Detection Engine Context
Return values
0 on success
-1 on failure
Definition at line 1357 of file detect-engine-build.c.
SigAddressPrepareStage2()
int SigAddressPrepareStage2 (DetectEngineCtx * de_ctx)
Fill the global src group head, with the sigs included.
Parameters
de_ctx Pointer to the Detection Engine Context whose Signatures have to be processed
Return values
0 On success
-1 On failure
Definition at line 1692 of file detect-engine-build.c.
References de_ctx, DetectEngineCtx_::flow_gh, DetectEngineCtx_::io_ctx, IPOnlyInit(), SCLogDebug, and DetectEngineLookupFlow_::tcp.
SigAddressPrepareStage3()
int SigAddressPrepareStage3 (DetectEngineCtx * de_ctx)
Definition at line 1734 of file detect-engine-build.c.
SigAddressPrepareStage4()
int SigAddressPrepareStage4 (DetectEngineCtx * de_ctx)
finalize preparing sgh's
Definition at line 1818 of file detect-engine-build.c.
References SCEnter.
SigCleanSignatures()
void SigCleanSignatures (DetectEngineCtx * de_ctx)
Definition at line 45 of file detect-engine-build.c.
References de_ctx, DetectEngineResetMaxSigId(), Signature_::next, DetectEngineCtx_::sig_list, and SigFree().
Referenced by DetectEngineCtxFree(), and UTHPacketMatchSig().
SigGroupBuild()
int SigGroupBuild (DetectEngineCtx * de_ctx)
Convert the signature list into the runtime match structure.
Parameters
de_ctx Pointer to the Detection Engine Context whose Signatures have to be processed
Return values
0 On Success.
-1 On failure.
Definition at line 1953 of file detect-engine-build.c.
References de_ctx, DetectSetFastPatternAndItsId(), Signature_::next, Signature_::num, DetectEngineCtx_::sig_list, and DetectEngineCtx_::signum.
Referenced by UTHMatchPackets(), UTHMatchPacketsWithResults(), UTHPacketMatchSig(), and UTHPacketMatchSigMpm().
SigGroupCleanup()
int SigGroupCleanup (DetectEngineCtx * de_ctx)
Definition at line 2021 of file detect-engine-build.c.
References de_ctx, and SigAddressCleanupStage1().
Referenced by DetectEngineCtxFree(), UTHMatchPackets(), and UTHPacketMatchSig().
SignatureIsFilemagicInspecting()
int SignatureIsFilemagicInspecting (const Signature * s)
Check if a signature contains the filemagic keyword.
Parameters
s signature
Return values
0 no
1 yes
Definition at line 109 of file detect-engine-build.c.
References Signature_::file_flags, and FILE_SIG_NEED_MAGIC.
Referenced by SigGroupHeadSetFilemagicFlag().
SignatureIsFileMd5Inspecting()
int SignatureIsFileMd5Inspecting (const Signature * s)
Check if a signature contains the filemd5 keyword.
Parameters
s signature
Return values
0 no
1 yes
Definition at line 128 of file detect-engine-build.c.
References Signature_::file_flags, and FILE_SIG_NEED_MD5.
Referenced by SigGroupHeadSetFileHashFlag().
SignatureIsFileSha1Inspecting()
int SignatureIsFileSha1Inspecting (const Signature * s)
Check if a signature contains the filesha1 keyword.
Parameters
s signature
Return values
0 no
1 yes
Definition at line 144 of file detect-engine-build.c.
References Signature_::file_flags, and FILE_SIG_NEED_SHA1.
Referenced by SigGroupHeadSetFileHashFlag().
SignatureIsFileSha256Inspecting()
int SignatureIsFileSha256Inspecting (const Signature * s)
Check if a signature contains the filesha256 keyword.
Parameters
s signature
Return values
0 no
1 yes
Definition at line 160 of file detect-engine-build.c.
References Signature_::file_flags, and FILE_SIG_NEED_SHA256.
Referenced by SigGroupHeadSetFileHashFlag().
SignatureIsFilesizeInspecting()
int SignatureIsFilesizeInspecting (const Signature * s)
Check if a signature contains the filesize keyword.
Parameters
s signature
Return values
0 no
1 yes
Definition at line 176 of file detect-engine-build.c.
References Signature_::file_flags, and FILE_SIG_NEED_SIZE.
Referenced by SigGroupHeadSetFilesizeFlag().
SignatureIsFilestoring()
int SignatureIsFilestoring (const Signature * s)
Check if a signature contains the filestore keyword.
Parameters
s signature
Return values
0 no
1 yes
Definition at line 90 of file detect-engine-build.c.
References Signature_::flags, and SIG_FLAG_FILESTORE.
Referenced by SigGroupHeadSetFilestoreCount().
SignatureSetType()
void SignatureSetType (DetectEngineCtx * de_ctx, Signature * s)
Definition at line 1329 of file detect-engine-build.c.