suricata: /Users/jlu/suricata/src/device-storage.c File Reference
device-storage.c File Reference
#include "suricata-common.h"
#include "device-storage.h"
#include "util-unittest.h"
Functions
unsigned int LiveDevStorageSize (void)
LiveDevStorageId LiveDevStorageRegister (const char *name, const unsigned int size, void *(*Alloc)(unsigned int), void(*Free)(void *))
Register a LiveDevice storage.
int LiveDevSetStorageById (LiveDevice *d, LiveDevStorageId id, void *ptr)
Store a pointer in a given LiveDevice storage.
void * LiveDevGetStorageById (LiveDevice *d, LiveDevStorageId id)
Get a value from a given LiveDevice storage.
void * LiveDevAllocStorageById (LiveDevice *d, LiveDevStorageId id)
void LiveDevFreeStorageById (LiveDevice *d, LiveDevStorageId id)
void LiveDevFreeStorage (LiveDevice *d)
Detailed Description
Author
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Device wrapper around storage api
Definition in file device-storage.c.
Function Documentation
LiveDevAllocStorageById()
void * LiveDevAllocStorageById (LiveDevice * d, LiveDevStorageId id)
Definition at line 99 of file device-storage.c.
References STORAGE_DEVICE, and StorageAllocByIdPrealloc().
LiveDevFreeStorage()
void LiveDevFreeStorage (LiveDevice * d)
Definition at line 110 of file device-storage.c.
References LiveDevStorageSize(), STORAGE_DEVICE, and StorageFreeAll().
LiveDevFreeStorageById()
void LiveDevFreeStorageById (LiveDevice * d, LiveDevStorageId id)
Definition at line 105 of file device-storage.c.
References STORAGE_DEVICE, and StorageFreeById().
LiveDevStorageSize()
unsigned int LiveDevStorageSize (void)
Definition at line 30 of file device-storage.c.
References STORAGE_DEVICE, and StorageGetSize().
Referenced by LiveDevFreeStorage(), and LiveRegisterDevice().