suricata: /Users/jlu/suricata/src/flow-worker.c File Reference
flow-worker.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "detect.h"
#include "stream-tcp.h"
#include "app-layer.h"
#include "detect-engine.h"
#include "output.h"
#include "app-layer-parser.h"
#include "app-layer-frames.h"
#include "util-profiling.h"
#include "util-validate.h"
#include "util-time.h"
#include "tmqh-packetpool.h"
#include "flow-util.h"
#include "flow-manager.h"
#include "flow-timeout.h"
#include "flow-spare-pool.h"
#include "flow-worker.h"
Data Structures
struct FlowTimeoutCounters
struct FlowWorkerThreadData_
Typedefs
typedef DetectEngineThreadCtx * DetectEngineThreadCtxPtr
typedef struct FlowTimeoutCounters FlowTimeoutCounters
typedef struct FlowWorkerThreadData_ FlowWorkerThreadData
Functions
Packet * FlowForceReassemblyPseudoPacketGet (int direction, Flow *f, TcpSession *ssn)
TmEcode Detect (ThreadVars *tv, Packet *p, void *data)
Detection engine thread wrapper.
TmEcode StreamTcp (ThreadVars *, Packet *, void *, PacketQueueNoLock *pq)
void FlowWorkerReplaceDetectCtx (void *flow_worker, void *detect_ctx)
void * FlowWorkerGetDetectCtxPtr (void *flow_worker)
const char * ProfileFlowWorkerIdToString (enum ProfileFlowWorkerId fwi)
void TmModuleFlowWorkerRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Flow Workers are single thread modules taking care of (almost) everything related to packets with flows:
Lookup/creation
Stream tracking, reassembly
Applayer update
Detection
This all while holding the flow lock.
Definition in file flow-worker.c.
Typedef Documentation
DetectEngineThreadCtxPtr
typedef DetectEngineThreadCtx* DetectEngineThreadCtxPtr
Definition at line 57 of file flow-worker.c.
FlowTimeoutCounters
typedef struct FlowTimeoutCounters FlowTimeoutCounters
FlowWorkerThreadData
typedef struct FlowWorkerThreadData_ FlowWorkerThreadData
Function Documentation
Detect()
TmEcode Detect (ThreadVars * tv, Packet * p, void * data)
Detection engine thread wrapper.
Parameters
tv thread vars
p packet to inspect
data thread specific data
pq packet queue
Return values
TM_ECODE_FAILED error
TM_ECODE_OK ok
Definition at line 1717 of file detect.c.
References de_ctx, DEBUG_VALIDATE_PACKET, DetectEngineThreadCtx_::mt_det_ctxs_cnt, SC_ATOMIC_GET, SC_ATOMIC_SET, SCLogDebug, Packet_::tenant_id, DetectEngineThreadCtx_::TenantGetId, and unlikely.
FlowForceReassemblyPseudoPacketGet()
Packet * FlowForceReassemblyPseudoPacketGet (int direction, Flow * f, TcpSession * ssn)
Definition at line 273 of file flow-timeout.c.
References PACKET_PROFILING_START, PacketPoolGetPacket(), and PacketPoolWait().
FlowWorkerGetDetectCtxPtr()
void * FlowWorkerGetDetectCtxPtr (void * flow_worker)
Definition at line 620 of file flow-worker.c.
References SC_ATOMIC_GET.
FlowWorkerReplaceDetectCtx()
void FlowWorkerReplaceDetectCtx (void * flow_worker, void * detect_ctx)
Definition at line 613 of file flow-worker.c.
References SC_ATOMIC_SET.
ProfileFlowWorkerIdToString()
const char * ProfileFlowWorkerIdToString (enum ProfileFlowWorkerId fwi)
Definition at line 627 of file flow-worker.c.
References PROFILE_FLOWWORKER_APPLAYERUDP, PROFILE_FLOWWORKER_DETECT, PROFILE_FLOWWORKER_FLOW, PROFILE_FLOWWORKER_FLOW_EVICTED, PROFILE_FLOWWORKER_FLOW_INJECTED, PROFILE_FLOWWORKER_SIZE, PROFILE_FLOWWORKER_STREAM, and PROFILE_FLOWWORKER_TCPPRUNE.
StreamTcp()
TmEcode StreamTcp (ThreadVars * tv, Packet * p, void * data, PacketQueueNoLock * pq)
Definition at line 5348 of file stream-tcp.c.
References StreamTcpThread_::counter_tcp_no_flow, Packet_::flow, FlowGetPacketDirection(), Packet_::pcap_cnt, PKT_IS_TCP, SCLogDebug, StatsIncr(), t_pcapcnt, TM_ECODE_OK, TOSERVER, and tv.
TmModuleFlowWorkerRegister()
void TmModuleFlowWorkerRegister (void)
Definition at line 656 of file flow-worker.c.
References TmModule_::name, TmModule_::ThreadInit, TMM_FLOWWORKER, and tmm_modules.
Referenced by RegisterAllModules().