suricata: /Users/jlu/suricata/src/flow-bypass.h File Reference
flow-bypass.h File Reference
Data Structures
struct flows_stats
Typedefs
typedef int(* BypassedCheckFunc) (ThreadVars *th_v, struct flows_stats *bypassstats, struct timespec *curtime, void *data)
typedef int(* BypassedCheckFuncInit) (ThreadVars *th_v, struct timespec *curtime, void *data)
typedef int(* BypassedUpdateFunc) (Flow *f, Packet *p, void *data)
Functions
void FlowAddToBypassed (Flow *f)
void BypassedFlowManagerThreadSpawn (void)
spawn the flow bypass manager thread
void TmModuleBypassedFlowManagerRegister (void)
int BypassedFlowManagerRegisterCheckFunc (BypassedCheckFunc CheckFunc, BypassedCheckFuncInit CheckFuncInit, void *data)
int BypassedFlowManagerRegisterUpdateFunc (BypassedUpdateFunc UpdateFunc, void *data)
void BypassedFlowUpdate (Flow *f, Packet *p)
Detailed Description
Author
Eric Leblond elebl.nosp@m.ond@.nosp@m.stamu.nosp@m.s-ne.nosp@m.twork.nosp@m.s.co.nosp@m.m
Definition in file flow-bypass.h.
Typedef Documentation
BypassedCheckFunc
typedef int(* BypassedCheckFunc) (ThreadVars *th_v, struct flows_stats *bypassstats, struct timespec *curtime, void *data)
Definition at line 33 of file flow-bypass.h.
BypassedCheckFuncInit
typedef int(* BypassedCheckFuncInit) (ThreadVars *th_v, struct timespec *curtime, void *data)
Definition at line 36 of file flow-bypass.h.
BypassedUpdateFunc
typedef int(* BypassedUpdateFunc) (Flow *f, Packet *p, void *data)
Definition at line 38 of file flow-bypass.h.
Function Documentation
BypassedFlowManagerRegisterCheckFunc()
int BypassedFlowManagerRegisterCheckFunc (BypassedCheckFunc CheckFunc, BypassedCheckFuncInit CheckFuncInit, void * data)
BypassedFlowManagerRegisterUpdateFunc()
int BypassedFlowManagerRegisterUpdateFunc (BypassedUpdateFunc UpdateFunc, void * data)
BypassedFlowManagerThreadSpawn()
void BypassedFlowManagerThreadSpawn (void)
spawn the flow bypass manager thread
Definition at line 184 of file flow-bypass.c.
References BUG_ON, thread_name_flow_bypass, TM_ECODE_OK, TmThreadCreateMgmtThreadByName(), and TmThreadSpawn().
BypassedFlowUpdate()
void BypassedFlowUpdate (Flow * f, Packet * p)
Definition at line 204 of file flow-bypass.c.
Referenced by FlowHandlePacketUpdate().
FlowAddToBypassed()
void FlowAddToBypassed (Flow * f)
TmModuleBypassedFlowManagerRegister()
void TmModuleBypassedFlowManagerRegister (void)
Definition at line 215 of file flow-bypass.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Management, TmModule_::name, SCLogDebug, TmModule_::ThreadDeinit, TmModule_::ThreadInit, TM_FLAG_MANAGEMENT_TM, TMM_BYPASSEDFLOWMANAGER, and tmm_modules.
Referenced by RegisterAllModules().