suricata: /Users/jlu/suricata/src/flow-var.h File Reference
flow-var.h File Reference
#include "flow.h"
#include "util-var.h"
Data Structures
struct FlowVarTypeStr
struct FlowVarTypeInt_
struct FlowVar_
Macros
#define FLOWVAR_TYPE_STR 1
#define FLOWVAR_TYPE_INT 2
Typedefs
typedef struct FlowVarTypeStr FlowVarTypeStr
typedef struct FlowVarTypeInt_ FlowVarTypeInt
typedef struct FlowVar_ FlowVar
Functions
void FlowVarAddIdValue (Flow *, uint32_t id, uint8_t *value, uint16_t size)
void FlowVarAddKeyValue (Flow *f, uint8_t *key, uint16_t keysize, uint8_t *value, uint16_t size)
void FlowVarAddIntNoLock (Flow *, uint32_t, uint32_t)
void FlowVarAddInt (Flow *, uint32_t, uint32_t)
FlowVar * FlowVarGet (Flow *, uint32_t)
get the flowvar with index 'idx' from the flow
FlowVar * FlowVarGetByKey (Flow *f, const uint8_t *key, uint16_t keylen)
get the flowvar with index 'idx' from the flow
void FlowVarFree (FlowVar *)
void FlowVarPrint (GenericVar *)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Pablo Rincon pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Definition in file flow-var.h.
Macro Definition Documentation
FLOWVAR_TYPE_INT
#define FLOWVAR_TYPE_INT 2
Definition at line 34 of file flow-var.h.
FLOWVAR_TYPE_STR
#define FLOWVAR_TYPE_STR 1
Available data types for Flowvars
Definition at line 33 of file flow-var.h.
Typedef Documentation
FlowVar
typedef struct FlowVar_ FlowVar
Generic Flowvar Structure
FlowVarTypeInt
typedef struct FlowVarTypeInt_ FlowVarTypeInt
Struct used to hold the integer data type for flowvars
FlowVarTypeStr
typedef struct FlowVarTypeStr FlowVarTypeStr
Struct used to hold the string data type for flowvars
Function Documentation
FlowVarAddIdValue()
void FlowVarAddIdValue (Flow * f, uint32_t id, uint8_t * value, uint16_t size)
Flowvar Interface API
Definition at line 113 of file flow-var.c.
References FlowVar_::data, FlowVar_::datatype, DETECT_FLOWVAR, Flow_::flowvar, FLOWVAR_TYPE_STR, FlowVarGet(), FlowVar_::fv_str, GenericVarAppend(), FlowVar_::idx, FlowVar_::next, SCCalloc, FlowVar_::type, unlikely, FlowVarTypeStr::value, and FlowVarTypeStr::value_len.
FlowVarAddInt()
void FlowVarAddInt (Flow * f, uint32_t idx, uint32_t value)
Definition at line 156 of file flow-var.c.
References FlowVarAddIntNoLock().
FlowVarAddIntNoLock()
void FlowVarAddIntNoLock (Flow * f, uint32_t idx, uint32_t value)
Definition at line 135 of file flow-var.c.
References FlowVar_::data, FlowVar_::datatype, DETECT_FLOWVAR, Flow_::flowvar, FLOWVAR_TYPE_INT, FlowVarGet(), FlowVar_::fv_int, GenericVarAppend(), FlowVar_::idx, FlowVar_::next, SCMalloc, FlowVar_::type, unlikely, and FlowVarTypeInt_::value.
Referenced by DetectFlowintMatch(), and FlowVarAddInt().
FlowVarAddKeyValue()
void FlowVarAddKeyValue (Flow * f, uint8_t * key, uint16_t keysize, uint8_t * value, uint16_t size)
Definition at line 94 of file flow-var.c.
References FlowVar_::data, FlowVar_::datatype, DETECT_FLOWVAR, Flow_::flowvar, FLOWVAR_TYPE_STR, FlowVar_::fv_str, GenericVarAppend(), FlowVar_::idx, FlowVar_::key, FlowVar_::keylen, FlowVar_::next, SCCalloc, FlowVar_::type, unlikely, FlowVarTypeStr::value, and FlowVarTypeStr::value_len.
FlowVarFree()
void FlowVarFree (FlowVar * fv)
Definition at line 161 of file flow-var.c.
References FlowVar_::data, FlowVar_::datatype, FLOWVAR_TYPE_STR, FlowVar_::fv_str, SCFree, and FlowVarTypeStr::value.
Referenced by GenericVarFree().
FlowVarGet()
FlowVar * FlowVarGet (Flow * f, uint32_t idx)
get the flowvar with index 'idx' from the flow
Note
flow is not locked by this function, caller is responsible
Definition at line 78 of file flow-var.c.
References DETECT_FLOWVAR, Flow_::flowvar, GenericVar_::idx, GenericVar_::next, and GenericVar_::type.
Referenced by DetectFlowintMatch(), DetectFlowvarMatch(), FlowVarAddIdValue(), and FlowVarAddIntNoLock().
FlowVarGetByKey()
FlowVar * FlowVarGetByKey (Flow * f, const uint8_t * key, uint16_t keylen)
get the flowvar with index 'idx' from the flow
Note
flow is not locked by this function, caller is responsible
Definition at line 54 of file flow-var.c.
References DETECT_FLOWVAR, Flow_::flowvar, GenericVar_::idx, FlowVar_::key, FlowVar_::keylen, GenericVar_::next, and GenericVar_::type.
FlowVarPrint()
void FlowVarPrint (GenericVar * gv)
Definition at line 173 of file flow-var.c.
References FlowVar_::data, FlowVar_::datatype, DETECT_FLOWINT, DETECT_FLOWVAR, FLOWVAR_TYPE_INT, FLOWVAR_TYPE_STR, FlowVarPrint(), FlowVar_::fv_int, FlowVar_::fv_str, FlowVar_::idx, GenericVar_::next, SCLogDebug, SCLogDebugEnabled(), GenericVar_::type, FlowVarTypeStr::value, FlowVarTypeInt_::value, and FlowVarTypeStr::value_len.
Referenced by FlowVarPrint().