suricata: /Users/jlu/suricata/src/flow-bypass.c File Reference
flow-bypass.c File Reference
#include "suricata-common.h"
#include "tm-threads.h"
#include "flow.h"
#include "flow-bypass.h"
#include "flow-private.h"
#include "util-ebpf.h"
#include "runmodes.h"
Functions
void BypassedFlowManagerThreadSpawn ()
spawn the flow bypass manager thread
void BypassedFlowUpdate (Flow *f, Packet *p)
void TmModuleBypassedFlowManagerRegister (void)
Detailed Description
Author
Eric Leblond elebl.nosp@m.ond@.nosp@m.stamu.nosp@m.s-ne.nosp@m.twork.nosp@m.s.co.nosp@m.m
Definition in file flow-bypass.c.
Function Documentation
BypassedFlowManagerThreadSpawn()
void BypassedFlowManagerThreadSpawn (void)
spawn the flow bypass manager thread
Definition at line 184 of file flow-bypass.c.
References BUG_ON, thread_name_flow_bypass, TM_ECODE_OK, TmThreadCreateMgmtThreadByName(), and TmThreadSpawn().
BypassedFlowUpdate()
void BypassedFlowUpdate (Flow * f, Packet * p)
Definition at line 204 of file flow-bypass.c.
Referenced by FlowHandlePacketUpdate().
TmModuleBypassedFlowManagerRegister()
void TmModuleBypassedFlowManagerRegister (void)
Definition at line 215 of file flow-bypass.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Management, TmModule_::name, SCLogDebug, TmModule_::ThreadDeinit, TmModule_::ThreadInit, TM_FLAG_MANAGEMENT_TM, TMM_BYPASSEDFLOWMANAGER, and tmm_modules.
Referenced by RegisterAllModules().