suricata: /Users/jlu/suricata/src/flow-timeout.c File Reference
flow-timeout.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "conf.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "runmodes.h"
#include "util-random.h"
#include "util-time.h"
#include "flow.h"
#include "flow-queue.h"
#include "flow-hash.h"
#include "flow-util.h"
#include "flow-var.h"
#include "flow-private.h"
#include "flow-manager.h"
#include "flow-timeout.h"
#include "pkt-var.h"
#include "host.h"
#include "stream-tcp-private.h"
#include "stream-tcp-reassemble.h"
#include "stream-tcp.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-byte.h"
#include "util-debug.h"
#include "util-privs.h"
#include "util-datalink.h"
#include "detect.h"
#include "detect-engine-state.h"
#include "stream.h"
#include "app-layer-parser.h"
#include "app-layer.h"
#include "util-profiling.h"
Functions
Packet * FlowForceReassemblyPseudoPacketGet (int direction, Flow *f, TcpSession *ssn)
int FlowForceReassemblyNeedReassembly (Flow *f)
Check if a flow needs forced reassembly, or any other processing.
void FlowForceReassemblyForFlow (Flow *f)
void FlowForceReassembly (void)
Force reassembly for all the flows that have unprocessed segments.
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file flow-timeout.c.
Function Documentation
FlowForceReassembly()
void FlowForceReassembly (void)
Force reassembly for all the flows that have unprocessed segments.
Definition at line 424 of file flow-timeout.c.
Referenced by PostRunDeinit().
FlowForceReassemblyForFlow()
void FlowForceReassemblyForFlow (Flow * f)
Definition at line 350 of file flow-timeout.c.
References Flow_::thread_id, and TmThreadsInjectFlowById().
FlowForceReassemblyNeedReassembly()
int FlowForceReassemblyNeedReassembly (Flow * f)
Check if a flow needs forced reassembly, or any other processing.
Parameters
f LOCKED flow
Return values
0 no
1 yes
Definition at line 296 of file flow-timeout.c.
References Flow_::alparser, Flow_::alproto, ALPROTO_UNKNOWN, Flow_::alstate, AppLayerParserGetTransactionActive(), AppLayerParserGetTxCnt(), Flow_::ffr_tc, Flow_::ffr_ts, Flow_::protoctx, SCReturnInt, TcpSession_::state, STREAM_HAS_UNPROCESSED_SEGMENTS_NEED_ONLY_DETECTION, STREAM_HAS_UNPROCESSED_SEGMENTS_NONE, StreamNeedsReassembly(), TCP_CLOSED, and TCP_ESTABLISHED.
FlowForceReassemblyPseudoPacketGet()
Packet * FlowForceReassemblyPseudoPacketGet (int direction, Flow * f, TcpSession * ssn)
Definition at line 273 of file flow-timeout.c.
References PACKET_PROFILING_START, PacketPoolGetPacket(), and PacketPoolWait().