suricata: /Users/jlu/suricata/src/flow-timeout.h File Reference
flow-timeout.h File Reference
Functions
void FlowForceReassemblyForFlow (Flow *f)
int FlowForceReassemblyNeedReassembly (Flow *f)
Check if a flow needs forced reassembly, or any other processing.
void FlowForceReassembly (void)
Force reassembly for all the flows that have unprocessed segments.
void FlowForceReassemblySetup (int detect_disabled)
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file flow-timeout.h.
Function Documentation
FlowForceReassembly()
void FlowForceReassembly (void)
Force reassembly for all the flows that have unprocessed segments.
Definition at line 424 of file flow-timeout.c.
Referenced by PostRunDeinit().
FlowForceReassemblyForFlow()
void FlowForceReassemblyForFlow (Flow * f)
Definition at line 350 of file flow-timeout.c.
References Flow_::thread_id, and TmThreadsInjectFlowById().
FlowForceReassemblyNeedReassembly()
int FlowForceReassemblyNeedReassembly (Flow * f)
Check if a flow needs forced reassembly, or any other processing.
Parameters
f LOCKED flow
Return values
0 no
1 yes
Definition at line 296 of file flow-timeout.c.
References Flow_::alparser, Flow_::alproto, ALPROTO_UNKNOWN, Flow_::alstate, AppLayerParserGetTransactionActive(), AppLayerParserGetTxCnt(), Flow_::ffr_tc, Flow_::ffr_ts, Flow_::protoctx, SCReturnInt, TcpSession_::state, STREAM_HAS_UNPROCESSED_SEGMENTS_NEED_ONLY_DETECTION, STREAM_HAS_UNPROCESSED_SEGMENTS_NONE, StreamNeedsReassembly(), TCP_CLOSED, and TCP_ESTABLISHED.
FlowForceReassemblySetup()
void FlowForceReassemblySetup (int detect_disabled)