suricata: /Users/jlu/suricata/src/flow-queue.h File Reference
flow-queue.h File Reference
#include "suricata-common.h"
#include "flow.h"
Data Structures
struct FlowQueuePrivate_
struct FlowQueue_
Macros
#define FQLOCK_MUTEX
#define qtop priv.top
#define qbot priv.bot
#define qlen priv.len
#define FQLOCK_INIT(q) SCMutexInit(&(q)->m, NULL)
#define FQLOCK_DESTROY(q) SCMutexDestroy(&(q)->m)
#define FQLOCK_LOCK(q) SCMutexLock(&(q)->m)
#define FQLOCK_TRYLOCK(q) SCMutexTrylock(&(q)->m)
#define FQLOCK_UNLOCK(q) SCMutexUnlock(&(q)->m)
Typedefs
typedef struct FlowQueuePrivate_ FlowQueuePrivate
typedef struct FlowQueue_ FlowQueue
Functions
FlowQueue * FlowQueueNew (void)
FlowQueue * FlowQueueInit (FlowQueue *)
void FlowQueueDestroy (FlowQueue *)
Destroy a flow queue.
void FlowEnqueue (FlowQueue *, Flow *)
add a flow to a queue
Flow * FlowDequeue (FlowQueue *)
remove a flow from the queue
void FlowQueueRemove (FlowQueue *fq, Flow *f)
void FlowQueueRemoveLock (FlowQueue *fq, Flow *f)
void FlowQueuePrivateAppendFlow (FlowQueuePrivate *fqc, Flow *f)
void FlowQueuePrivatePrependFlow (FlowQueuePrivate *fqc, Flow *f)
void FlowQueueAppendPrivate (FlowQueue *fq, FlowQueuePrivate *fqp)
void FlowQueuePrivateAppendPrivate (FlowQueuePrivate *dest, FlowQueuePrivate *src)
FlowQueuePrivate FlowQueueExtractPrivate (FlowQueue *fq)
Flow * FlowQueuePrivateGetFromTop (FlowQueuePrivate *fqp)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file flow-queue.h.
Macro Definition Documentation
FQLOCK_DESTROY
#define FQLOCK_DESTROY (q) SCMutexDestroy(&(q)->m)
Definition at line 72 of file flow-queue.h.
FQLOCK_INIT
#define FQLOCK_INIT (q) SCMutexInit(&(q)->m, NULL)
Definition at line 71 of file flow-queue.h.
FQLOCK_LOCK
#define FQLOCK_LOCK (q) SCMutexLock(&(q)->m)
Definition at line 73 of file flow-queue.h.
FQLOCK_MUTEX
#define FQLOCK_MUTEX
Spinlocks or Mutex for the flow queues.
Definition at line 32 of file flow-queue.h.
FQLOCK_TRYLOCK
#define FQLOCK_TRYLOCK (q) SCMutexTrylock(&(q)->m)
Definition at line 74 of file flow-queue.h.
FQLOCK_UNLOCK
#define FQLOCK_UNLOCK (q) SCMutexUnlock(&(q)->m)
Definition at line 75 of file flow-queue.h.
qbot
#define qbot priv.bot
Definition at line 61 of file flow-queue.h.
qlen
#define qlen priv.len
Definition at line 62 of file flow-queue.h.
qtop
#define qtop priv.top
Definition at line 60 of file flow-queue.h.
Typedef Documentation
FlowQueue
typedef struct FlowQueue_ FlowQueue
FlowQueuePrivate
typedef struct FlowQueuePrivate_ FlowQueuePrivate
Function Documentation
FlowDequeue()
Flow * FlowDequeue (FlowQueue * q)
remove a flow from the queue
Parameters
q queue
Return values
f flow or NULL if empty list.
Definition at line 191 of file flow-queue.c.
References FlowQueuePrivateGetFromTop(), FQLOCK_LOCK, and FlowQueue_::priv.
Referenced by FlowShutdown().
FlowEnqueue()
void FlowEnqueue (FlowQueue * q, Flow * f)
add a flow to a queue
Parameters
q queue
f flow
Definition at line 173 of file flow-queue.c.
References BUG_ON, FlowQueuePrivateAppendFlow(), FQLOCK_LOCK, and FlowQueue_::priv.
FlowQueueAppendPrivate()
void FlowQueueAppendPrivate (FlowQueue * fq, FlowQueuePrivate * fqp)
Definition at line 119 of file flow-queue.c.
References FlowQueuePrivate_::bot, FQLOCK_LOCK, FlowQueuePrivate_::len, and FlowQueuePrivate_::top.
FlowQueueDestroy()
void FlowQueueDestroy (FlowQueue * q)
Destroy a flow queue.
Parameters
q the flow queue to destroy
Definition at line 60 of file flow-queue.c.
References FQLOCK_DESTROY.
Referenced by FlowShutdown().
FlowQueueExtractPrivate()
FlowQueuePrivate FlowQueueExtractPrivate (FlowQueue * fq)
Definition at line 140 of file flow-queue.c.
References FQLOCK_LOCK, and FlowQueue_::priv.
FlowQueueInit()
FlowQueue * FlowQueueInit (FlowQueue * q)
Definition at line 46 of file flow-queue.c.
References FQLOCK_INIT.
Referenced by FlowInitConfig(), and FlowQueueNew().
FlowQueueNew()
FlowQueue * FlowQueueNew (void)
Definition at line 35 of file flow-queue.c.
References FlowQueueInit(), SC_ERR_FATAL, SCLogError, and SCMalloc.
FlowQueuePrivateAppendFlow()
void FlowQueuePrivateAppendFlow (FlowQueuePrivate * fqc, Flow * f)
Definition at line 65 of file flow-queue.c.
References FlowQueuePrivate_::bot, FlowQueuePrivate_::len, Flow_::next, and FlowQueuePrivate_::top.
Referenced by FlowEnqueue().
FlowQueuePrivateAppendPrivate()
void FlowQueuePrivateAppendPrivate (FlowQueuePrivate * dest, FlowQueuePrivate * src)
Definition at line 88 of file flow-queue.c.
References FlowQueuePrivate_::bot, FlowQueuePrivate_::len, Flow_::next, src, and FlowQueuePrivate_::top.
FlowQueuePrivateGetFromTop()
Flow * FlowQueuePrivateGetFromTop (FlowQueuePrivate * fqp)
Definition at line 151 of file flow-queue.c.
References FlowQueuePrivate_::bot, FlowQueuePrivate_::len, Flow_::next, and FlowQueuePrivate_::top.
Referenced by FlowDequeue(), and UTHBuildPacketOfFlows().
FlowQueuePrivatePrependFlow()
void FlowQueuePrivatePrependFlow (FlowQueuePrivate * fqc, Flow * f)
Definition at line 78 of file flow-queue.c.
References FlowQueuePrivate_::bot, FlowQueuePrivate_::len, Flow_::next, and FlowQueuePrivate_::top.
FlowQueueRemove()
void FlowQueueRemove (FlowQueue * fq, Flow * f)
FlowQueueRemoveLock()
void FlowQueueRemoveLock (FlowQueue * fq, Flow * f)