suricata: /Users/jlu/suricata/src/flow-storage.h File Reference
flow-storage.h File Reference
#include "flow.h"
Data Structures
struct FlowStorageId
Typedefs
typedef struct FlowStorageId FlowStorageId
Functions
unsigned int FlowStorageSize (void)
void * FlowGetStorageById (Flow *h, FlowStorageId id)
int FlowSetStorageById (Flow *h, FlowStorageId id, void *ptr)
void * FlowAllocStorageById (Flow *h, FlowStorageId id)
void FlowFreeStorageById (Flow *h, FlowStorageId id)
void FlowFreeStorage (Flow *h)
void RegisterFlowStorageTests (void)
FlowStorageId FlowStorageRegister (const char *name, const unsigned int size, void *(*Alloc)(unsigned int), void(*Free)(void *))
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Flow wrapper around storage api
Definition in file flow-storage.h.
Typedef Documentation
FlowStorageId
typedef struct FlowStorageId FlowStorageId
Function Documentation
FlowAllocStorageById()
void * FlowAllocStorageById (Flow * h, FlowStorageId id)
Definition at line 49 of file flow-storage.c.
References STORAGE_FLOW, and StorageAllocByIdPrealloc().
FlowFreeStorage()
void FlowFreeStorage (Flow * h)
Definition at line 59 of file flow-storage.c.
References FlowStorageSize(), STORAGE_FLOW, and StorageFreeAll().
Referenced by FlowClearMemory().
FlowFreeStorageById()
void FlowFreeStorageById (Flow * h, FlowStorageId id)
Definition at line 54 of file flow-storage.c.
References STORAGE_FLOW, and StorageFreeById().
FlowGetStorageById()
void * FlowGetStorageById (Flow * h, FlowStorageId id)
Definition at line 39 of file flow-storage.c.
References STORAGE_FLOW, and StorageGetById().
Referenced by CreateJSONEther(), EveAddFlow(), PacketBypassCallback(), and TagFlowAdd().
FlowSetStorageById()
int FlowSetStorageById (Flow * h, FlowStorageId id, void * ptr)
Definition at line 44 of file flow-storage.c.
References STORAGE_FLOW, and StorageSetById().
Referenced by PacketBypassCallback().
FlowStorageRegister()
FlowStorageId FlowStorageRegister (const char * name, const unsigned int size, void *(*)(unsigned int) Alloc, void(*)(void *) Free)
Definition at line 65 of file flow-storage.c.
References FlowStorageId::id, STORAGE_FLOW, and StorageRegister().
Referenced by RegisterFlowBypassInfo().
FlowStorageSize()
unsigned int FlowStorageSize (void)
Definition at line 34 of file flow-storage.c.
References STORAGE_FLOW, and StorageGetSize().
Referenced by FlowAlloc(), FlowFree(), FlowFreeStorage(), and FlowInitConfig().
RegisterFlowStorageTests()
void RegisterFlowStorageTests (void)
Definition at line 294 of file flow-storage.c.
References UtRegisterTest().