suricata: /Users/jlu/suricata/src/flow-manager.h File Reference
flow-manager.h File Reference
Macros
#define FlowWakeupFlowManagerThread() SCCtrlCondSignal(&flow_manager_ctrl_cond)
#define FlowWakeupFlowRecyclerThread() SCCtrlCondSignal(&flow_recycler_ctrl_cond)
#define FlowTimeoutsReset() FlowTimeoutsInit()
Functions
void FlowTimeoutsInit (void)
void FlowTimeoutsEmergency (void)
void FlowManagerThreadSpawn (void)
spawn the flow manager thread
void FlowDisableFlowManagerThread (void)
Used to disable flow manager thread(s).
void FlowRecyclerThreadSpawn (void)
spawn the flow recycler thread
void FlowDisableFlowRecyclerThread (void)
Used to disable flow recycler thread(s).
void TmModuleFlowManagerRegister (void)
void TmModuleFlowRecyclerRegister (void)
Variables
SCCtrlCondT flow_manager_ctrl_cond
SCCtrlMutex flow_manager_ctrl_mutex
SCCtrlCondT flow_recycler_ctrl_cond
SCCtrlMutex flow_recycler_ctrl_mutex
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file flow-manager.h.
Macro Definition Documentation
FlowTimeoutsReset
#define FlowTimeoutsReset () FlowTimeoutsInit()
Definition at line 35 of file flow-manager.h.
FlowWakeupFlowManagerThread
#define FlowWakeupFlowManagerThread () SCCtrlCondSignal(&flow_manager_ctrl_cond)
Definition at line 30 of file flow-manager.h.
FlowWakeupFlowRecyclerThread
#define FlowWakeupFlowRecyclerThread () SCCtrlCondSignal(&flow_recycler_ctrl_cond)
Definition at line 33 of file flow-manager.h.
Function Documentation
FlowDisableFlowManagerThread()
void FlowDisableFlowManagerThread (void)
Used to disable flow manager thread(s).
Todo:
Kinda hackish since it uses the tv name to identify flow manager thread. We need an all weather identification scheme.
Definition at line 143 of file flow-manager.c.
References FatalError, ThreadVars_::name, ThreadVars_::next, SC_ATOMIC_SET, SC_ERR_SHUTDOWN, SCMutexLock, SCMutexUnlock, SleepMsec, thread_name_flow_mgr, THV_KILL, THV_RUNNING_DONE, TmThreadsCheckFlag(), TmThreadsSetFlag(), tv, tv_root, tv_root_lock, and TVT_MGMT.
Referenced by PostRunDeinit().
FlowDisableFlowRecyclerThread()
void FlowDisableFlowRecyclerThread (void)
Used to disable flow recycler thread(s).
Note
this should only be called when the flow manager is already gone
Todo:
Kinda hackish since it uses the tv name to identify flow recycler thread. We need an all weather identification scheme.
Definition at line 1184 of file flow-manager.c.
FlowManagerThreadSpawn()
void FlowManagerThreadSpawn (void)
spawn the flow manager thread
Definition at line 951 of file flow-manager.c.
References ConfGetInt(), FatalError, and SC_ERR_INVALID_ARGUMENTS.
FlowRecyclerThreadSpawn()
void FlowRecyclerThreadSpawn (void)
spawn the flow recycler thread
Definition at line 1143 of file flow-manager.c.
References ConfGetInt(), FatalError, and SC_ERR_INVALID_ARGUMENTS.
FlowTimeoutsEmergency()
void FlowTimeoutsEmergency (void)
Definition at line 105 of file flow-manager.c.
References flow_timeouts_emerg, and SC_ATOMIC_SET.
FlowTimeoutsInit()
void FlowTimeoutsInit (void)
Definition at line 100 of file flow-manager.c.
References flow_timeouts_normal, and SC_ATOMIC_SET.
Referenced by FlowInitFlowProto().
TmModuleFlowManagerRegister()
void TmModuleFlowManagerRegister (void)
Definition at line 1246 of file flow-manager.c.
References TmModule_::name, TmModule_::ThreadInit, TMM_FLOWMANAGER, and tmm_modules.
Referenced by RegisterAllModules().
TmModuleFlowRecyclerRegister()
void TmModuleFlowRecyclerRegister (void)
Definition at line 1260 of file flow-manager.c.
References TmModule_::name, TmModule_::ThreadInit, TMM_FLOWRECYCLER, and tmm_modules.
Referenced by RegisterAllModules().
Variable Documentation
flow_manager_ctrl_cond
SCCtrlCondT flow_manager_ctrl_cond extern
flow manager scheduling condition
Definition at line 95 of file flow-manager.c.
flow_manager_ctrl_mutex
SCCtrlMutex flow_manager_ctrl_mutex extern
Definition at line 96 of file flow-manager.c.
flow_recycler_ctrl_cond
SCCtrlCondT flow_recycler_ctrl_cond extern
Definition at line 97 of file flow-manager.c.
flow_recycler_ctrl_mutex
SCCtrlMutex flow_recycler_ctrl_mutex extern
Definition at line 98 of file flow-manager.c.