suricata: /Users/jlu/suricata/src/flow-queue.c File Reference
flow-queue.c File Reference
#include "suricata-common.h"
#include "threads.h"
#include "flow-private.h"
#include "flow-queue.h"
#include "flow-util.h"
#include "util-error.h"
#include "util-debug.h"
#include "util-print.h"
Functions
FlowQueue * FlowQueueNew ()
FlowQueue * FlowQueueInit (FlowQueue *q)
void FlowQueueDestroy (FlowQueue *q)
Destroy a flow queue.
void FlowQueuePrivateAppendFlow (FlowQueuePrivate *fqc, Flow *f)
void FlowQueuePrivatePrependFlow (FlowQueuePrivate *fqc, Flow *f)
void FlowQueuePrivateAppendPrivate (FlowQueuePrivate *dest, FlowQueuePrivate *src)
void FlowQueueAppendPrivate (FlowQueue *fq, FlowQueuePrivate *fqc)
FlowQueuePrivate FlowQueueExtractPrivate (FlowQueue *fq)
Flow * FlowQueuePrivateGetFromTop (FlowQueuePrivate *fqc)
void FlowEnqueue (FlowQueue *q, Flow *f)
add a flow to a queue
Flow * FlowDequeue (FlowQueue *q)
remove a flow from the queue
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Flow queue handler functions
Definition in file flow-queue.c.
Function Documentation
FlowDequeue()
Flow * FlowDequeue (FlowQueue * q)
remove a flow from the queue
Parameters
q queue
Return values
f flow or NULL if empty list.
Definition at line 191 of file flow-queue.c.
References FlowQueuePrivateGetFromTop(), FQLOCK_LOCK, and FlowQueue_::priv.
Referenced by FlowShutdown().
FlowEnqueue()
void FlowEnqueue (FlowQueue * q, Flow * f)
add a flow to a queue
Parameters
q queue
f flow
Definition at line 173 of file flow-queue.c.
References BUG_ON, FlowQueuePrivateAppendFlow(), FQLOCK_LOCK, and FlowQueue_::priv.
FlowQueueAppendPrivate()
void FlowQueueAppendPrivate (FlowQueue * fq, FlowQueuePrivate * fqc)
Definition at line 119 of file flow-queue.c.
References FlowQueuePrivate_::bot, FQLOCK_LOCK, FlowQueuePrivate_::len, and FlowQueuePrivate_::top.
FlowQueueDestroy()
void FlowQueueDestroy (FlowQueue * q)
Destroy a flow queue.
Parameters
q the flow queue to destroy
Definition at line 60 of file flow-queue.c.
References FQLOCK_DESTROY.
Referenced by FlowShutdown().
FlowQueueExtractPrivate()
FlowQueuePrivate FlowQueueExtractPrivate (FlowQueue * fq)
Definition at line 140 of file flow-queue.c.
References FQLOCK_LOCK, and FlowQueue_::priv.
FlowQueueInit()
FlowQueue * FlowQueueInit (FlowQueue * q)
Definition at line 46 of file flow-queue.c.
References FQLOCK_INIT.
Referenced by FlowInitConfig(), and FlowQueueNew().
FlowQueueNew()
FlowQueue * FlowQueueNew (void)
Definition at line 35 of file flow-queue.c.
References FlowQueueInit(), SC_ERR_FATAL, SCLogError, and SCMalloc.
FlowQueuePrivateAppendFlow()
void FlowQueuePrivateAppendFlow (FlowQueuePrivate * fqc, Flow * f)
Definition at line 65 of file flow-queue.c.
References FlowQueuePrivate_::bot, FlowQueuePrivate_::len, Flow_::next, and FlowQueuePrivate_::top.
Referenced by FlowEnqueue().
FlowQueuePrivateAppendPrivate()
void FlowQueuePrivateAppendPrivate (FlowQueuePrivate * dest, FlowQueuePrivate * src)
Definition at line 88 of file flow-queue.c.
References FlowQueuePrivate_::bot, FlowQueuePrivate_::len, Flow_::next, src, and FlowQueuePrivate_::top.
FlowQueuePrivateGetFromTop()
Flow * FlowQueuePrivateGetFromTop (FlowQueuePrivate * fqc)
Definition at line 151 of file flow-queue.c.
References FlowQueuePrivate_::bot, FlowQueuePrivate_::len, Flow_::next, and FlowQueuePrivate_::top.
Referenced by FlowDequeue(), and UTHBuildPacketOfFlows().
FlowQueuePrivatePrependFlow()
void FlowQueuePrivatePrependFlow (FlowQueuePrivate * fqc, Flow * f)
Definition at line 78 of file flow-queue.c.
References FlowQueuePrivate_::bot, FlowQueuePrivate_::len, Flow_::next, and FlowQueuePrivate_::top.