suricata: /Users/jlu/suricata/src/flow-storage.c File Reference
flow-storage.c File Reference
#include "suricata-common.h"
#include "flow-storage.h"
#include "flow-hash.h"
#include "flow-util.h"
#include "util-unittest.h"
Functions
unsigned int FlowStorageSize (void)
void * FlowGetStorageById (Flow *f, FlowStorageId id)
int FlowSetStorageById (Flow *f, FlowStorageId id, void *ptr)
void * FlowAllocStorageById (Flow *f, FlowStorageId id)
void FlowFreeStorageById (Flow *f, FlowStorageId id)
void FlowFreeStorage (Flow *f)
FlowStorageId FlowStorageRegister (const char *name, const unsigned int size, void *(*Alloc)(unsigned int), void(*Free)(void *))
void RegisterFlowStorageTests (void)
Detailed Description
Author
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
based on host-storage by Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Flow wrapper around storage api
Definition in file flow-storage.c.
Function Documentation
FlowAllocStorageById()
void * FlowAllocStorageById (Flow * f, FlowStorageId id)
Definition at line 49 of file flow-storage.c.
References STORAGE_FLOW, and StorageAllocByIdPrealloc().
FlowFreeStorage()
void FlowFreeStorage (Flow * f)
Definition at line 59 of file flow-storage.c.
References FlowStorageSize(), STORAGE_FLOW, and StorageFreeAll().
Referenced by FlowClearMemory().
FlowFreeStorageById()
void FlowFreeStorageById (Flow * f, FlowStorageId id)
Definition at line 54 of file flow-storage.c.
References STORAGE_FLOW, and StorageFreeById().
FlowGetStorageById()
void * FlowGetStorageById (Flow * f, FlowStorageId id)
Definition at line 39 of file flow-storage.c.
References STORAGE_FLOW, and StorageGetById().
Referenced by CreateJSONEther(), EveAddFlow(), PacketBypassCallback(), and TagFlowAdd().
FlowSetStorageById()
int FlowSetStorageById (Flow * f, FlowStorageId id, void * ptr)
Definition at line 44 of file flow-storage.c.
References STORAGE_FLOW, and StorageSetById().
Referenced by PacketBypassCallback().
FlowStorageRegister()
FlowStorageId FlowStorageRegister (const char * name, const unsigned int size, void *(*)(unsigned int) Alloc, void(*)(void *) Free)
Definition at line 65 of file flow-storage.c.
References FlowStorageId::id, STORAGE_FLOW, and StorageRegister().
Referenced by RegisterFlowBypassInfo().
FlowStorageSize()
unsigned int FlowStorageSize (void)
Definition at line 34 of file flow-storage.c.
References STORAGE_FLOW, and StorageGetSize().
Referenced by FlowAlloc(), FlowFree(), FlowFreeStorage(), and FlowInitConfig().
RegisterFlowStorageTests()
void RegisterFlowStorageTests (void)
Definition at line 294 of file flow-storage.c.
References UtRegisterTest().