suricata: /Users/jlu/suricata/src/flow-util.c File Reference
flow-util.c File Reference
#include "suricata-common.h"
#include "threads.h"
#include "flow.h"
#include "flow-private.h"
#include "flow-util.h"
#include "flow-var.h"
#include "app-layer.h"
#include "util-var.h"
#include "util-debug.h"
#include "util-macset.h"
#include "flow-storage.h"
#include "detect.h"
#include "detect-engine-state.h"
#include "decode-icmpv4.h"
Functions
Flow * FlowAlloc (void)
allocate a flow
void FlowFree (Flow *f)
cleanup & free the memory of a flow
uint8_t FlowGetProtoMapping (uint8_t proto)
Function to map the protocol to the defined FLOW_PROTO_* enumeration.
uint8_t FlowGetReverseProtoMapping (uint8_t rproto)
void FlowInit (Flow *f, const Packet *p)
FlowStorageId GetFlowBypassInfoID (void)
void RegisterFlowBypassInfo (void)
void FlowEndCountersRegister (ThreadVars *t, FlowEndCounters *fec)
Variables
FlowStorageId g_bypass_info_id = { .id = -1 }
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Flow utility functions
Definition in file flow-util.c.
Function Documentation
FlowAlloc()
Flow * FlowAlloc (void)
allocate a flow
We check against the memuse counter. If it passes that check we increment the counter first, then we try to alloc.
Return values
f the flow or NULL on out of memory
Definition at line 52 of file flow-util.c.
References FLOW_CHECK_MEMCAP, FLOW_INITIALIZE, FlowStorageSize(), SC_ATOMIC_ADD, SC_ATOMIC_SUB, SCMalloc, and unlikely.
Referenced by FlowGetFromFlowKey(), and LLVMFuzzerTestOneInput().
FlowEndCountersRegister()
void FlowEndCountersRegister (ThreadVars * t, FlowEndCounters * fec)
Definition at line 245 of file flow-util.c.
References FlowEndCounters_::flow_state, FLOW_STATE_CLOSED, FLOW_STATE_ESTABLISHED, FLOW_STATE_LOCAL_BYPASSED, FLOW_STATE_NEW, FLOW_STATE_SIZE, FlowEndCounters_::flow_tcp_liberal, FlowEndCounters_::flow_tcp_state, StatsRegisterCounter(), TCP_CLOSE_WAIT, TCP_CLOSED, TCP_CLOSING, TCP_ESTABLISHED, TCP_FIN_WAIT1, TCP_FIN_WAIT2, TCP_LAST_ACK, TCP_NONE, TCP_SYN_RECV, TCP_SYN_SENT, and TCP_TIME_WAIT.
FlowFree()
void FlowFree (Flow * f)
cleanup & free the memory of a flow
Parameters
f flow to clear & destroy
Definition at line 81 of file flow-util.c.
References FLOW_DESTROY, FlowStorageSize(), SC_ATOMIC_SUB, and SCFree.
Referenced by FlowReset(), FlowShutdown(), LLVMFuzzerTestOneInput(), and UTHBuildPacketOfFlows().
FlowGetProtoMapping()
uint8_t FlowGetProtoMapping (uint8_t proto)
Function to map the protocol to the defined FLOW_PROTO_* enumeration.
Parameters
proto protocol which is needed to be mapped
Definition at line 96 of file flow-util.c.
References FLOW_PROTO_DEFAULT, FLOW_PROTO_ICMP, FLOW_PROTO_TCP, FLOW_PROTO_UDP, and proto.
Referenced by AppLayerParserApplyTxConfig(), AppLayerParserGetEventInfo(), AppLayerParserGetEventInfoById(), AppLayerParserParse(), AppLayerParserProtocolGetLoggerBits(), AppLayerParserProtocolHasLogger(), AppLayerParserProtoIsRegistered(), AppLayerRegisterThreadCounters(), AppLayerSetupCounters(), FlowGetFromFlowKey(), FlowReset(), FlowSetProtoFreeFunc(), FlowShutdown(), and LLVMFuzzerTestOneInput().
FlowGetReverseProtoMapping()
uint8_t FlowGetReverseProtoMapping (uint8_t rproto)
Definition at line 110 of file flow-util.c.
References FLOW_PROTO_ICMP, FLOW_PROTO_TCP, and FLOW_PROTO_UDP.
Referenced by AppLayerParserThreadCtxAlloc(), and AppLayerParserThreadCtxFree().
FlowInit()
void FlowInit (Flow * f, const Packet * p)
Definition at line 144 of file flow-util.c.
References Packet_::code, Flow_::code, Flow_::dp, Flow_::dst, Flow_::flags, FLOW_IPV4, FLOW_IPV6, FLOW_SET_IPV4_DST_ADDR_FROM_PACKET, FLOW_SET_IPV4_SRC_ADDR_FROM_PACKET, FLOW_SET_IPV6_DST_ADDR_FROM_PACKET, FLOW_SET_IPV6_SRC_ADDR_FROM_PACKET, Packet_::icmp_s, Flow_::icmp_s, Packet_::icmpv4h, IPV4_GET_IPTTL, IPV6_GET_HLIM, Packet_::livedev, Flow_::livedev, Flow_::max_ttl_toserver, Flow_::min_ttl_toserver, PKT_IS_IPV4, PKT_IS_IPV6, Packet_::proto, Flow_::proto, Packet_::recursion_level, Flow_::recursion_level, SCEnter, SCLogDebug, SET_TCP_DST_PORT, SET_TCP_SRC_PORT, SET_UDP_DST_PORT, SET_UDP_SRC_PORT, Flow_::sp, Flow_::src, Packet_::tcph, Packet_::type, Flow_::type, Packet_::udph, Packet_::vlan_id, Flow_::vlan_id, Packet_::vlan_idx, and Flow_::vlan_idx.
GetFlowBypassInfoID()
FlowStorageId GetFlowBypassInfoID (void)
Definition at line 221 of file flow-util.c.
References g_bypass_info_id.
Referenced by EveAddFlow(), and PacketBypassCallback().
RegisterFlowBypassInfo()
void RegisterFlowBypassInfo (void)
Definition at line 239 of file flow-util.c.
References FlowStorageRegister(), and g_bypass_info_id.
Referenced by PostConfLoadedSetup().
Variable Documentation
g_bypass_info_id
FlowStorageId g_bypass_info_id = { .id = -1 }
Definition at line 219 of file flow-util.c.
Referenced by GetFlowBypassInfoID(), and RegisterFlowBypassInfo().