suricata: /Users/jlu/suricata/src/tests/fuzz/fuzz_applayerparserparse.c File Reference
fuzz_applayerparserparse.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "app-layer-detect-proto.h"
#include "flow-util.h"
#include "app-layer-parser.h"
#include "util-unittest-helper.h"
#include "util-byte.h"
#include "conf-yaml-loader.h"
#include "confyaml.c"
Macros
#define HEADER_LEN 6
#define ALPROTO_MAXTX 4096
Functions
int LLVMFuzzerTestOneInput (const uint8_t *data, size_t size)
int LLVMFuzzerInitialize (int *argc, char ***argv)
Variables
AppLayerParserThreadCtx * alp_tctx = NULL
const uint8_t separator [] = {0x01, 0xD5, 0xCA, 0x7A}
SCInstance surifuzz
AppProto forceLayer = 0
Detailed Description
Author
Philippe Antoine conta.nosp@m.ct@c.nosp@m.atena.nosp@m.cybe.nosp@m.r.fr fuzz target for AppLayerParserParse
Definition in file fuzz_applayerparserparse.c.
Macro Definition Documentation
ALPROTO_MAXTX
#define ALPROTO_MAXTX 4096
Definition at line 64 of file fuzz_applayerparserparse.c.
HEADER_LEN
#define HEADER_LEN 6
Definition at line 16 of file fuzz_applayerparserparse.c.
Function Documentation
LLVMFuzzerInitialize()
int LLVMFuzzerInitialize (int * argc, char *** argv)
Definition at line 39 of file fuzz_applayerparserparse.c.
References ALPROTO_UNKNOWN, AppProtoToString(), ByteExtractStringUint16(), forceLayer, and StringToAppProto().
LLVMFuzzerTestOneInput()
int LLVMFuzzerTestOneInput (const uint8_t * data, size_t size)
Definition at line 66 of file fuzz_applayerparserparse.c.
References alp_tctx, Flow_::alparser, Flow_::alproto, ALPROTO_MAX, APP_LAYER_PARSER_EOF_TC, APP_LAYER_PARSER_EOF_TS, AppLayerParserParse(), AppLayerParserStateIssetFlag(), AppLayerParserThreadCtxAlloc(), AppLayerParserTransactionsCleanup(), configNoChecksum, ConfigSetLogDirectory(), ConfYamlLoadString(), Flow_::dp, Flow_::dst, flags, Flow_::flags, FLOW_IPV4, FlowAlloc(), FlowChangeProto(), FlowFree(), FlowGetProtoMapping(), FLOWLOCK_UNLOCK, FLOWLOCK_WRLOCK, forceLayer, GlobalsInitPreConfig(), HEADER_LEN, InitGlobal(), PostConfLoadedSetup(), Flow_::proto, Flow_::protoctx, Flow_::protomap, run_mode, RUNMODE_PCAP_FILE, separator, setenv(), Flow_::sp, Flow_::src, and surifuzz.
Variable Documentation
alp_tctx
AppLayerParserThreadCtx* alp_tctx = NULL
Definition at line 21 of file fuzz_applayerparserparse.c.
Referenced by LLVMFuzzerTestOneInput().
forceLayer
AppProto forceLayer = 0
Definition at line 37 of file fuzz_applayerparserparse.c.
Referenced by LLVMFuzzerInitialize(), and LLVMFuzzerTestOneInput().
separator
const uint8_t separator[] = {0x01, 0xD5, 0xCA, 0x7A}
Definition at line 35 of file fuzz_applayerparserparse.c.
Referenced by LLVMFuzzerTestOneInput().
surifuzz
SCInstance surifuzz
Definition at line 36 of file fuzz_applayerparserparse.c.
Referenced by LLVMFuzzerTestOneInput().