suricata: /Users/jlu/suricata/src/tests/fuzz/fuzz_applayerprotodetectgetproto.c File Reference
fuzz_applayerprotodetectgetproto.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "app-layer-detect-proto.h"
#include "flow-util.h"
#include "app-layer-parser.h"
#include "util-unittest-helper.h"
#include "conf-yaml-loader.h"
#include "confyaml.c"
Macros
#define HEADER_LEN 6
#define PROTO_DETECT_MAX_LEN 1024
Functions
int LLVMFuzzerTestOneInput (const uint8_t *data, size_t size)
Variables
AppLayerProtoDetectThreadCtx * alpd_tctx = NULL
Detailed Description
Author
Philippe Antoine conta.nosp@m.ct@c.nosp@m.atena.nosp@m.cybe.nosp@m.r.fr fuzz target for AppLayerProtoDetectGetProto
Definition in file fuzz_applayerprotodetectgetproto.c.
Macro Definition Documentation
HEADER_LEN
#define HEADER_LEN 6
Definition at line 16 of file fuzz_applayerprotodetectgetproto.c.
PROTO_DETECT_MAX_LEN
#define PROTO_DETECT_MAX_LEN 1024
Definition at line 19 of file fuzz_applayerprotodetectgetproto.c.
Function Documentation
LLVMFuzzerTestOneInput()
int LLVMFuzzerTestOneInput (const uint8_t * data, size_t size)
Definition at line 27 of file fuzz_applayerprotodetectgetproto.c.
References alpd_tctx, ALPROTO_FAILED, ALPROTO_UNKNOWN, AppLayerParserRegisterProtocolParsers(), AppLayerParserSetup(), AppLayerProtoDetectGetCtxThread(), AppLayerProtoDetectGetProto(), AppLayerProtoDetectReset(), AppLayerProtoDetectSetup(), AppProtoToString(), configNoChecksum, ConfYamlLoadString(), flags, FlowFree(), FlowGetProtoMapping(), HEADER_LEN, InitGlobal(), MpmTableSetup(), Flow_::proto, PROTO_DETECT_MAX_LEN, Flow_::protoctx, Flow_::protomap, run_mode, RUNMODE_UNITTEST, SpmTableSetup(), and TestHelperBuildFlow().
Variable Documentation
alpd_tctx
AppLayerProtoDetectThreadCtx* alpd_tctx = NULL
Definition at line 25 of file fuzz_applayerprotodetectgetproto.c.
Referenced by AppLayerProtoDetectGetCtxThread(), and LLVMFuzzerTestOneInput().