suricata: Packet decoding
Packet decoding
Code in charge of protocol decoding.
Files
file decode-chdlc.c
file decode-erspan.c
file decode-esp.c
file decode-ethernet.c
file decode-gre.c
file decode-icmpv4.c
file decode-icmpv6.c
file decode-ipv4.c
file decode-ipv6.c
file decode-nsh.c
file decode-null.c
file decode-ppp.c
file decode-pppoe.c
file decode-raw.c
file decode-sctp.c
file decode-sll.c
file decode-tcp.c
file decode-template.c
file decode-teredo.c
file decode-udp.c
file decode-vlan.c
file decode-vntag.c
file decode.c
Functions
PacketAlert * PacketAlertCreate (void)
Initialize PacketAlerts with dynamic alerts array size.
void PacketAlertFree (PacketAlert *pa)
void PacketFree (Packet *p)
Return a malloced packet.
void PacketDecodeFinalize (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p)
Finalize decoding of a packet.
void PacketUpdateEngineEventCounters (ThreadVars *tv, DecodeThreadVars *dtv, Packet *p)
Packet * PacketGetFromAlloc (void)
Get a malloced packet.
void PacketFreeOrRelease (Packet *p)
Return a packet to where it was allocated.
Packet * PacketGetFromQueueOrAlloc (void)
Get a packet. We try to get a packet from the packetpool first, but if that is empty we alloc a packet that is free'd again after processing.
int PacketCallocExtPkt (Packet *p, int datalen)
int PacketCopyDataOffset (Packet *p, uint32_t offset, const uint8_t *data, uint32_t datalen)
Copy data to Packet payload at given offset.
int PacketCopyData (Packet *p, const uint8_t *pktdata, uint32_t pktlen)
Copy data to Packet payload and set packet length.
Packet * PacketTunnelPktSetup (ThreadVars *tv, DecodeThreadVars *dtv, Packet *parent, const uint8_t *pkt, uint32_t len, enum DecodeTunnelProto proto)
Setup a pseudo packet (tunnel)
Packet * PacketDefragPktSetup (Packet *parent, const uint8_t *pkt, uint32_t len, uint8_t proto)
Setup a pseudo packet (reassembled frags)
void PacketDefragPktSetupParent (Packet *parent)
inform defrag "parent" that a pseudo packet is now associated to it.
void PacketBypassCallback (Packet *p)
void PacketSwap (Packet *p)
switch direction of a packet
void DecodeUnregisterCounters (void)
void DecodeRegisterPerfCounters (DecodeThreadVars *dtv, ThreadVars *tv)
void DecodeUpdatePacketCounters (ThreadVars *tv, const DecodeThreadVars *dtv, const Packet *p)
void AddressDebugPrint (Address *a)
Debug print function for printing addresses.
DecodeThreadVars * DecodeThreadVarsAlloc (ThreadVars *tv)
Alloc and setup DecodeThreadVars.
void DecodeThreadVarsFree (ThreadVars *tv, DecodeThreadVars *dtv)
int PacketSetData (Packet *p, const uint8_t *pktdata, uint32_t pktlen)
Set data for Packet and set length when zero copy is used.
const char * PktSrcToString (enum PktSrcEnum pkt_src)
const char * PacketDropReasonToString (enum PacketDropReason r)
void CaptureStatsUpdate (ThreadVars *tv, CaptureStats *s, const Packet *p)
void CaptureStatsSetup (ThreadVars *tv, CaptureStats *s)
void DecodeGlobalConfig (void)
void PacketAlertGetMaxConfig (void)
Variables
uint32_t default_packet_size = 0
bool stats_decoder_events
const char * stats_decoder_events_prefix
bool stats_stream_events
uint8_t decoder_max_layers = PKT_DEFAULT_MAX_DECODED_LAYERS
uint16_t packet_alert_max = PACKET_ALERT_MAX
Detailed Description
Code in charge of protocol decoding.
The task of decoding packets is made in different files and as Suricata is supporting encapsulation there is a potential recursivity in the call.
For each protocol a DecodePROTO function is provided. For example we have DecodeIPV4() for IPv4 and DecodePPP() for PPP.
These functions have all a pkt and a len argument which are respectively a pointer to the protocol data and the length of this protocol data.
Attention
The pkt parameter must point to the effective data because it will be used later to set per protocol pointer like Packet::tcph
Function Documentation
AddressDebugPrint()
void AddressDebugPrint (Address * a)
Debug print function for printing addresses.
Parameters
Address object
Todo:
IPv6
Definition at line 670 of file decode.c.
References Address_::family, PrintInet(), and SCLogDebug.
CaptureStatsSetup()
void CaptureStatsSetup (ThreadVars * tv, CaptureStats * s)
Definition at line 830 of file decode.c.
References CaptureStats_::counter_ips_accepted, CaptureStats_::counter_ips_blocked, CaptureStats_::counter_ips_rejected, CaptureStats_::counter_ips_replaced, StatsRegisterCounter(), and tv.
CaptureStatsUpdate()
void CaptureStatsUpdate (ThreadVars * tv, CaptureStats * s, const Packet * p)
Definition at line 817 of file decode.c.
References unlikely.
DecodeGlobalConfig()
void DecodeGlobalConfig (void)
Definition at line 838 of file decode.c.
References ConfGetInt(), DecodeERSPANConfig(), DecodeGeneveConfig(), decoder_max_layers, DecodeTeredoConfig(), DecodeVXLANConfig(), PacketAlertGetMaxConfig(), SC_ERR_INVALID_VALUE, and SCLogWarning.
DecodeRegisterPerfCounters()
void DecodeRegisterPerfCounters (DecodeThreadVars * dtv, ThreadVars * tv)
Definition at line 526 of file decode.c.
References BUG_ON, code, DecodeThreadVars_::counter_avg_pkt_size, DecodeThreadVars_::counter_bytes, DecodeThreadVars_::counter_chdlc, DecodeThreadVars_::counter_defrag_ipv4_fragments, DecodeThreadVars_::counter_defrag_ipv4_reassembled, DecodeThreadVars_::counter_defrag_ipv4_timeouts, DecodeThreadVars_::counter_defrag_ipv6_fragments, DecodeThreadVars_::counter_defrag_ipv6_reassembled, DecodeThreadVars_::counter_defrag_ipv6_timeouts, DecodeThreadVars_::counter_defrag_max_hit, DecodeThreadVars_::counter_erspan, DecodeThreadVars_::counter_esp, DecodeThreadVars_::counter_eth, DecodeThreadVars_::counter_flow_active, DecodeThreadVars_::counter_flow_get_used, DecodeThreadVars_::counter_flow_get_used_eval, DecodeThreadVars_::counter_flow_get_used_eval_busy, DecodeThreadVars_::counter_flow_get_used_eval_reject, DecodeThreadVars_::counter_flow_get_used_failed, DecodeThreadVars_::counter_flow_icmp4, DecodeThreadVars_::counter_flow_icmp6, DecodeThreadVars_::counter_flow_memcap, DecodeThreadVars_::counter_flow_spare_sync, DecodeThreadVars_::counter_flow_spare_sync_avg, DecodeThreadVars_::counter_flow_spare_sync_empty, DecodeThreadVars_::counter_flow_spare_sync_incomplete, DecodeThreadVars_::counter_flow_tcp, DecodeThreadVars_::counter_flow_tcp_reuse, DecodeThreadVars_::counter_flow_total, DecodeThreadVars_::counter_flow_udp, DecodeThreadVars_::counter_geneve, DecodeThreadVars_::counter_gre, DecodeThreadVars_::counter_icmpv4, DecodeThreadVars_::counter_icmpv6, DecodeThreadVars_::counter_ieee8021ah, DecodeThreadVars_::counter_invalid, DecodeThreadVars_::counter_ipv4, DecodeThreadVars_::counter_ipv4inipv6, DecodeThreadVars_::counter_ipv6, DecodeThreadVars_::counter_ipv6inipv6, DecodeThreadVars_::counter_max_mac_addrs_dst, DecodeThreadVars_::counter_max_mac_addrs_src, DecodeThreadVars_::counter_max_pkt_size, DecodeThreadVars_::counter_mpls, DecodeThreadVars_::counter_nsh, DecodeThreadVars_::counter_null, DecodeThreadVars_::counter_pkts, DecodeThreadVars_::counter_ppp, DecodeThreadVars_::counter_pppoe, DecodeThreadVars_::counter_raw, DecodeThreadVars_::counter_sctp, DecodeThreadVars_::counter_sll, DecodeThreadVars_::counter_tcp, DecodeThreadVars_::counter_tcp_active_sessions, DecodeThreadVars_::counter_teredo, DecodeThreadVars_::counter_udp, DecodeThreadVars_::counter_vlan, DecodeThreadVars_::counter_vlan_qinq, DecodeThreadVars_::counter_vntag, DecodeThreadVars_::counter_vxlan, DECODE_EVENT_MAX, DECODE_EVENT_PACKET_MAX, DEvents, dtv, SCMutexLock, stats_decoder_events, stats_stream_events, StatsRegisterAvgCounter(), StatsRegisterCounter(), StatsRegisterMaxCounter(), and tv.
Referenced by DecodeErfDagThreadInit(), DecodePfringThreadInit(), and NapatechDecodeThreadInit().
DecodeThreadVarsAlloc()
DecodeThreadVars * DecodeThreadVarsAlloc (ThreadVars * tv)
Alloc and setup DecodeThreadVars.
Definition at line 687 of file decode.c.
References DecodeThreadVars_::app_tctx, AppLayerGetCtxThread(), DecodeThreadVarsFree(), dtv, DecodeThreadVars_::output_flow_thread_data, OutputFlowLogThreadInit(), SC_ERR_THREAD_INIT, SCLogError, SCMalloc, TM_ECODE_OK, and tv.
Referenced by DecodeErfDagThreadInit(), DecodePfringThreadInit(), and NapatechDecodeThreadInit().
DecodeThreadVarsFree()
void DecodeThreadVarsFree (ThreadVars * tv, DecodeThreadVars * dtv)
Definition at line 706 of file decode.c.
References DecodeThreadVars_::app_tctx, AppLayerDestroyCtxThread(), dtv, DecodeThreadVars_::output_flow_thread_data, OutputFlowLogThreadDeinit(), SCFree, and tv.
Referenced by DecodeErfDagThreadDeinit(), DecodePfringThreadDeinit(), DecodeThreadVarsAlloc(), and NapatechDecodeThreadDeinit().
DecodeUnregisterCounters()
void DecodeUnregisterCounters (void)
Definition at line 516 of file decode.c.
References SCMutexLock.
DecodeUpdatePacketCounters()
void DecodeUpdatePacketCounters (ThreadVars * tv, const DecodeThreadVars * dtv, const Packet * p)
Definition at line 653 of file decode.c.
References DecodeThreadVars_::counter_avg_pkt_size, DecodeThreadVars_::counter_bytes, DecodeThreadVars_::counter_max_pkt_size, DecodeThreadVars_::counter_pkts, dtv, GET_PKT_LEN, StatsAddUI64(), StatsIncr(), StatsSetUI64(), and tv.
Referenced by DecodeErfDag(), DecodePfring(), and NapatechDecode().
PacketAlertCreate()
PacketAlert * PacketAlertCreate (void)
Initialize PacketAlerts with dynamic alerts array size.
Definition at line 86 of file decode.c.
References BUG_ON, packet_alert_max, and SCCalloc.
PacketAlertFree()
void PacketAlertFree (PacketAlert * pa)
Definition at line 94 of file decode.c.
References SCFree.
PacketAlertGetMaxConfig()
void PacketAlertGetMaxConfig (void)
Definition at line 855 of file decode.c.
References ConfGetInt(), packet_alert_max, SC_ERR_INVALID_VALUE, SCLogDebug, and SCLogWarning.
Referenced by DecodeGlobalConfig().
PacketBypassCallback()
void PacketBypassCallback (Packet * p)
Note
if p->flow is set, the flow is locked
Definition at line 444 of file decode.c.
References Packet_::BypassPacketsFlow, Packet_::flow, Flow_::flow_state, FLOW_STATE_LOCAL_BYPASSED, FlowGetStorageById(), FlowSetStorageById(), FlowUpdateState(), GetFlowBypassInfoID(), PKT_IS_PSEUDOPKT, and SCCalloc.
PacketCallocExtPkt()
int PacketCallocExtPkt (Packet * p, int datalen) inline
Definition at line 230 of file decode.c.
References Packet_::ext_pkt, SCCalloc, SET_PKT_LEN, and unlikely.
PacketCopyData()
int PacketCopyData (Packet * p, const uint8_t * pktdata, uint32_t pktlen) inline
Copy data to Packet payload and set packet length.
Parameters
Pointer to the Packet to modify
Pointer to the data to copy
Length of the data to copy
Definition at line 298 of file decode.c.
References PacketCopyDataOffset(), and SET_PKT_LEN.
Referenced by PacketDefragPktSetup(), PacketTunnelPktSetup(), and StreamTcpPseudoSetup().
PacketCopyDataOffset()
int PacketCopyDataOffset (Packet * p, uint32_t offset, const uint8_t * data, uint32_t datalen) inline
Copy data to Packet payload at given offset.
This function copies data/payload to a Packet. It uses the space allocated at Packet creation (pointed by Packet::pkt) or allocate some memory (pointed by Packet::ext_pkt) if the data size is to big to fit in initial space (of size default_packet_size).
Parameters
Pointer to the Packet to modify
Offset of the copy relatively to payload of Packet
Pointer to the data to copy
Length of the data to copy
Definition at line 256 of file decode.c.
References default_packet_size, Packet_::ext_pkt, GET_PKT_DIRECT_DATA, GET_PKT_DIRECT_MAX_SIZE, MAX_PAYLOAD_SIZE, offset, SCMalloc, SET_PKT_LEN, and unlikely.
Referenced by PacketCopyData(), and UTHBuildPacketReal().
PacketDecodeFinalize()
void PacketDecodeFinalize (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p)
Finalize decoding of a packet.
This function needs to be call at the end of decode functions when decoding has been successful.
Definition at line 150 of file decode.c.
References DecodeThreadVars_::counter_invalid, dtv, Packet_::flags, PKT_IS_INVALID, StatsIncr(), and tv.
Referenced by DecodeErfDag(), DecodePfring(), and NapatechDecode().
PacketDefragPktSetup()
Packet * PacketDefragPktSetup (Packet * parent, const uint8_t * pkt, uint32_t len, uint8_t proto)
Setup a pseudo packet (reassembled frags)
Difference with PacketPseudoPktSetup is that this func doesn't increment the recursion level. It needs to be on the same level as the frags because we run the flow engine against this and we need to get the same flow.
Parameters
parent parent packet for this pseudo pkt
pkt raw packet data
len packet data length
proto protocol of the tunneled packet
Return values
p the pseudo packet or NULL if out of memory
Definition at line 388 of file decode.c.
References Packet_::datalink, len, Packet_::livedev, PacketCopyData(), PacketGetFromQueueOrAlloc(), Packet_::recursion_level, Packet_::root, SCEnter, SCReturnPtr, SET_TUNNEL_PKT, Packet_::tenant_id, Packet_::ts, unlikely, Packet_::vlan_id, and Packet_::vlan_idx.
PacketDefragPktSetupParent()
void PacketDefragPktSetupParent (Packet * parent)
inform defrag "parent" that a pseudo packet is now associated to it.
Definition at line 427 of file decode.c.
References SET_TUNNEL_PKT, and TUNNEL_INCR_PKT_TPR.
PacketDropReasonToString()
const char * PacketDropReasonToString (enum PacketDropReason r)
Definition at line 783 of file decode.c.
References PKT_DROP_REASON_APPLAYER_ERROR, PKT_DROP_REASON_APPLAYER_MEMCAP, PKT_DROP_REASON_DECODE_ERROR, PKT_DROP_REASON_DEFRAG_ERROR, PKT_DROP_REASON_DEFRAG_MEMCAP, PKT_DROP_REASON_FLOW_DROP, PKT_DROP_REASON_FLOW_MEMCAP, PKT_DROP_REASON_NOT_SET, PKT_DROP_REASON_RULES, PKT_DROP_REASON_RULES_THRESHOLD, PKT_DROP_REASON_STREAM_ERROR, PKT_DROP_REASON_STREAM_MEMCAP, and PKT_DROP_REASON_STREAM_MIDSTREAM.
PacketFree()
void PacketFree (Packet * p)
Return a malloced packet.
Definition at line 137 of file decode.c.
References PACKET_DESTRUCTOR, and SCFree.
Referenced by PacketFreeOrRelease(), and PacketGetFromAlloc().
PacketFreeOrRelease()
void PacketFreeOrRelease (Packet * p)
Return a packet to where it was allocated.
Definition at line 197 of file decode.c.
References Packet_::flags, PacketFree(), PacketPoolReturnPacket(), PKT_ALLOC, and Packet_::ReleasePacket.
PacketGetFromAlloc()
Packet * PacketGetFromAlloc (void)
Get a malloced packet.
Return values
p packet, NULL on error
Definition at line 176 of file decode.c.
References Packet_::flags, PACKET_INITIALIZE, PACKET_PROFILING_START, PacketFree(), PKT_ALLOC, Packet_::ReleasePacket, SCLogDebug, SCMalloc, SIZE_OF_PACKET, and unlikely.
Referenced by PacketGetFromQueueOrAlloc(), UTHBuildPacketArrayFromEth(), UTHBuildPacketFromEth(), UTHBuildPacketIPV6Real(), and UTHBuildPacketReal().
PacketGetFromQueueOrAlloc()
Packet * PacketGetFromQueueOrAlloc (void)
Get a packet. We try to get a packet from the packetpool first, but if that is empty we alloc a packet that is free'd again after processing.
Return values
p packet, NULL on error
Definition at line 214 of file decode.c.
References DEBUG_VALIDATE_BUG_ON, PACKET_PROFILING_START, PacketGetFromAlloc(), PacketPoolGetPacket(), PacketPoolReturnPacket(), and Packet_::ReleasePacket.
Referenced by PacketDefragPktSetup(), PacketTunnelPktSetup(), ReceiveErfFileLoop(), ReceivePfringLoop(), and StreamTcpPseudoSetup().
PacketSetData()
int PacketSetData (Packet * p, const uint8_t * pktdata, uint32_t pktlen) inline
Set data for Packet and set length when zero copy is used.
Parameters
Pointer to the Packet to modify
Pointer to the data
Length of the data
Definition at line 726 of file decode.c.
References Packet_::ext_pkt, Packet_::flags, PKT_ZERO_COPY, SET_PKT_LEN, and unlikely.
Referenced by ReceivePfringLoop().
PacketSwap()
void PacketSwap (Packet * p)
switch direction of a packet
Definition at line 491 of file decode.c.
References FLOW_PKT_TOCLIENT, FLOW_PKT_TOCLIENT_FIRST, FLOW_PKT_TOSERVER, FLOW_PKT_TOSERVER_FIRST, Packet_::flowflags, and PKT_IS_TOSERVER.
PacketTunnelPktSetup()
Packet * PacketTunnelPktSetup (ThreadVars * tv, DecodeThreadVars * dtv, Packet * parent, const uint8_t * pkt, uint32_t len, enum DecodeTunnelProto proto)
Setup a pseudo packet (tunnel)
Parameters
parent parent packet for this pseudo pkt
pkt raw packet data
len packet data length
proto protocol of the tunneled packet
Return values
p the pseudo packet or NULL if out of memory
Definition at line 314 of file decode.c.
References Packet_::datalink, len, Packet_::livedev, PacketCopyData(), PacketGetFromQueueOrAlloc(), Packet_::recursion_level, Packet_::root, SCEnter, SCReturnPtr, SET_TUNNEL_PKT, Packet_::tenant_id, Packet_::ts, and unlikely.
PacketUpdateEngineEventCounters()
void PacketUpdateEngineEventCounters (ThreadVars * tv, DecodeThreadVars * dtv, Packet * p)
Definition at line 157 of file decode.c.
References PacketEngineEvents_::cnt, DecodeThreadVars_::counter_engine_events, DECODE_EVENT_PACKET_MAX, dtv, PacketEngineEvents_::events, Packet_::events, stats_decoder_events, stats_stream_events, StatsIncr(), and tv.
PktSrcToString()
const char * PktSrcToString (enum PktSrcEnum pkt_src)
Definition at line 739 of file decode.c.
References PKT_SRC_CAPTURE_TIMEOUT, PKT_SRC_DECODER_GENEVE, PKT_SRC_DECODER_GRE, PKT_SRC_DECODER_IPV4, PKT_SRC_DECODER_IPV6, PKT_SRC_DECODER_TEREDO, PKT_SRC_DECODER_VXLAN, PKT_SRC_DEFRAG, PKT_SRC_DETECT_RELOAD_FLUSH, PKT_SRC_FFR, PKT_SRC_STREAM_TCP_DETECTLOG_FLUSH, and PKT_SRC_WIRE.
Variable Documentation
decoder_max_layers
uint8_t decoder_max_layers = PKT_DEFAULT_MAX_DECODED_LAYERS
Definition at line 79 of file decode.c.
Referenced by DecodeGlobalConfig().
default_packet_size
uint32_t default_packet_size = 0
Definition at line 75 of file decode.c.
Referenced by PacketCopyDataOffset(), and RunUnittests().
packet_alert_max
uint16_t packet_alert_max = PACKET_ALERT_MAX
Definition at line 80 of file decode.c.
Referenced by AlertQueueInit(), PacketAlertCreate(), and PacketAlertGetMaxConfig().
stats_decoder_events
bool stats_decoder_events extern
Definition at line 103 of file counters.c.
Referenced by DecodeRegisterPerfCounters(), and PacketUpdateEngineEventCounters().
stats_decoder_events_prefix
const char* stats_decoder_events_prefix extern
add stream events as stats? disabled by default
Definition at line 104 of file counters.c.
stats_stream_events
bool stats_stream_events extern
Definition at line 106 of file counters.c.
Referenced by DecodeRegisterPerfCounters(), and PacketUpdateEngineEventCounters().