suricata: Host storage API
Host storage API
Functions
HostStorageId HostStorageRegister (const char *name, const unsigned int size, void *(*Alloc)(unsigned int), void(*Free)(void *))
Register a Host storage.
int HostSetStorageById (Host *h, HostStorageId id, void *ptr)
Store a pointer in a given Host storage.
void * HostGetStorageById (Host *h, HostStorageId id)
Get a value from a given Host storage.
Detailed Description
The Host storage API is a per-host storage. It is a mean to extend the Host structure with arbitrary data.
You have first to register the storage via HostStorageRegister() during the init of your module. Then you can attach data via HostSetStorageById() and access them via HostGetStorageById().
Function Documentation
HostGetStorageById()
void * HostGetStorageById (Host * h, HostStorageId id)
Get a value from a given Host storage.
Parameters
h a pointer to the Host
id the id of the storage (return of HostStorageRegister() call)
Definition at line 88 of file host-storage.c.
References STORAGE_HOST, and StorageGetById().
Referenced by HostBitList(), HostBitsTimedoutCheck(), HostHasHostBits(), TagHashAddTag(), TagHostHasTag(), TagTimeoutCheck(), ThresholdHostHasThreshold(), and ThresholdHostTimeoutCheck().
HostSetStorageById()
int HostSetStorageById (Host * h, HostStorageId id, void * ptr)
Store a pointer in a given Host storage.
Parameters
h a pointer to the Host
id the id of the storage (return of HostStorageRegister() call)
ptr pointer to the data to store
Definition at line 75 of file host-storage.c.
References STORAGE_HOST, and StorageSetById().
HostStorageRegister()
HostStorageId HostStorageRegister (const char * name, const unsigned int size, void *(*)(unsigned int) Alloc, void(*)(void *) Free)
Register a Host storage.
Parameters
name the name of the storage
size integer coding the size of the stored value (sizeof(void *) is best choice here)
Alloc allocation function for the storage (can be null)
Free free function for the new storage
Return values
The ID of the newly register storage that will be used to access data
It has to be called once during the init of the sub system
Definition at line 59 of file host-storage.c.
References HostStorageId_::id, STORAGE_HOST, and StorageRegister().