suricata: DPDK running mode
DPDK running mode
Files
file runmode-dpdk.c
file source-dpdk.c
file util-dpdk-i40e.c
file util-dpdk-ice.c
file util-dpdk-ixgbe.c
Functions
TmEcode NoDPDKSupportExit (ThreadVars *tv, const void *initdata, void **data)
this function prints an error message and exits.
void TmModuleReceiveDPDKRegister (void)
void TmModuleDecodeDPDKRegister (void)
Registration Function for DecodeDPDK.
Detailed Description
Function Documentation
NoDPDKSupportExit()
TmEcode NoDPDKSupportExit (ThreadVars * tv, const void * initdata, void ** data)
this function prints an error message and exits.
Definition at line 75 of file source-dpdk.c.
References FatalError, ThreadVars_::name, SC_ERR_NO_DPDK, and tv.
Referenced by TmModuleDecodeDPDKRegister(), and TmModuleReceiveDPDKRegister().
TmModuleDecodeDPDKRegister()
void TmModuleDecodeDPDKRegister (void)
Registration Function for DecodeDPDK.
Definition at line 61 of file source-dpdk.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Func, TmModule_::name, NoDPDKSupportExit(), TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_DECODE_TM, TMM_DECODEDPDK, and tmm_modules.
Referenced by RegisterAllModules().
TmModuleReceiveDPDKRegister()
void TmModuleReceiveDPDKRegister (void)
Definition at line 47 of file source-dpdk.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Func, TmModule_::name, NoDPDKSupportExit(), TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_RECEIVE_TM, tmm_modules, and TMM_RECEIVEDPDK.
Referenced by RegisterAllModules().