suricata: HTTP layer support
HTTP layer support
Files
file app-layer-htp-mem.c
file app-layer-htp.c
file app-layer-htp.h
file detect-http-accept-enc.c
file detect-http-accept-lang.c
file detect-http-accept.c
file detect-http-client-body.c
file detect-http-connection.c
file detect-http-content-len.c
file detect-http-content-type.c
file detect-http-cookie.c
file detect-http-header-names.c
file detect-http-header.c
file detect-http-host.c
file detect-http-location.c
file detect-http-method.c
file detect-http-protocol.c
file detect-http-raw-header.c
file detect-http-referer.c
file detect-http-request-line.c
file detect-http-response-line.c
file detect-http-server-body.c
file detect-http-server.c
file detect-http-start.c
file detect-http-stat-code.c
file detect-http-stat-msg.c
file detect-http-ua.c
file detect-http-uri.c
file detect-http-client-body.c
Handle HTTP request body match corresponding to http_client_body keyword.
file detect-http-cookie.c
Handle HTTP cookie match.
file detect-http-header.c
file detect-http-host.c
Handle HTTP host header. HHHD - Http Host Header Data.
file detect-http-method.c
Handle HTTP method match.
file detect-http-raw-header.c
Handle HTTP raw header match.
file detect-http-stat-code.c
file detect-http-stat-msg.c
file detect-http-user-agent.c
Handle HTTP user agent match.
Data Structures
struct HTPCfgDir_
struct HTPCfgRec_
struct HtpBodyChunk_
struct HtpBody_
struct HtpTxUserData_
struct HtpState_
Macros
#define HTP_CONFIG_DEFAULT_REQUEST_BODY_LIMIT 4096U
#define HTP_CONFIG_DEFAULT_RESPONSE_BODY_LIMIT 4096U
#define HTP_CONFIG_DEFAULT_REQUEST_INSPECT_MIN_SIZE 32768U
#define HTP_CONFIG_DEFAULT_REQUEST_INSPECT_WINDOW 4096U
#define HTP_CONFIG_DEFAULT_RESPONSE_INSPECT_MIN_SIZE 32768U
#define HTP_CONFIG_DEFAULT_RESPONSE_INSPECT_WINDOW 4096U
#define HTP_CONFIG_DEFAULT_FIELD_LIMIT_SOFT 9000U
#define HTP_CONFIG_DEFAULT_FIELD_LIMIT_HARD 18000U
#define HTP_CONFIG_DEFAULT_LZMA_LAYERS 0U
#define HTP_CONFIG_DEFAULT_LZMA_MEMLIMIT 1048576U
#define HTP_CONFIG_DEFAULT_COMPRESSION_BOMB_LIMIT 1048576U
#define HTP_CONFIG_DEFAULT_COMPRESSION_TIME_LIMIT 100000
#define HTP_CONFIG_DEFAULT_RANDOMIZE 1
#define HTP_CONFIG_DEFAULT_RANDOMIZE_RANGE 10
#define HTP_BOUNDARY_MAX 200U
#define HTP_FLAG_STATE_CLOSED_TS 0x0002
#define HTP_FLAG_STATE_CLOSED_TC 0x0004
#define HTP_FLAG_STORE_FILES_TS 0x0040
#define HTP_FLAG_STORE_FILES_TC 0x0080
#define HTP_FLAG_STORE_FILES_TX_TS 0x0100
#define HTP_FLAG_STORE_FILES_TX_TC 0x0200
#define HTP_CONTENTTYPE_SET BIT_U8(0)
#define HTP_BOUNDARY_SET BIT_U8(1)
#define HTP_BOUNDARY_OPEN BIT_U8(2)
#define HTP_FILENAME_SET BIT_U8(3)
#define HTP_DONTSTORE BIT_U8(4)
#define HTP_STREAM_DEPTH_SET BIT_U8(5)
#define HTP_REQUIRE_REQUEST_BODY (1 << 0)
#define HTP_REQUIRE_REQUEST_MULTIPART (1 << 1)
#define HTP_REQUIRE_REQUEST_FILE (1 << 2)
#define HTP_REQUIRE_RESPONSE_BODY (1 << 3)
Typedefs
typedef enum HtpSwfCompressType_ HtpSwfCompressType
typedef struct HTPCfgDir_ HTPCfgDir
typedef struct HTPCfgRec_ HTPCfgRec
typedef struct HtpBodyChunk_ HtpBodyChunk
typedef struct HtpBody_ HtpBody
typedef struct HtpTxUserData_ HtpTxUserData
typedef struct HtpState_ HtpState
Enumerations
enum { HTP_BODY_REQUEST_NONE = 0 , HTP_BODY_REQUEST_MULTIPART , HTP_BODY_REQUEST_POST , HTP_BODY_REQUEST_PUT }
enum {
HTTP_DECODER_EVENT_UNKNOWN_ERROR , HTTP_DECODER_EVENT_GZIP_DECOMPRESSION_FAILED , HTTP_DECODER_EVENT_REQUEST_FIELD_MISSING_COLON , HTTP_DECODER_EVENT_RESPONSE_FIELD_MISSING_COLON ,
HTTP_DECODER_EVENT_INVALID_REQUEST_CHUNK_LEN , HTTP_DECODER_EVENT_INVALID_RESPONSE_CHUNK_LEN , HTTP_DECODER_EVENT_INVALID_TRANSFER_ENCODING_VALUE_IN_REQUEST , HTTP_DECODER_EVENT_INVALID_TRANSFER_ENCODING_VALUE_IN_RESPONSE ,
HTTP_DECODER_EVENT_INVALID_CONTENT_LENGTH_FIELD_IN_REQUEST , HTTP_DECODER_EVENT_INVALID_CONTENT_LENGTH_FIELD_IN_RESPONSE , HTTP_DECODER_EVENT_DUPLICATE_CONTENT_LENGTH_FIELD_IN_REQUEST , HTTP_DECODER_EVENT_DUPLICATE_CONTENT_LENGTH_FIELD_IN_RESPONSE ,
HTTP_DECODER_EVENT_100_CONTINUE_ALREADY_SEEN , HTTP_DECODER_EVENT_UNABLE_TO_MATCH_RESPONSE_TO_REQUEST , HTTP_DECODER_EVENT_INVALID_SERVER_PORT_IN_REQUEST , HTTP_DECODER_EVENT_INVALID_AUTHORITY_PORT ,
HTTP_DECODER_EVENT_REQUEST_HEADER_INVALID , HTTP_DECODER_EVENT_RESPONSE_HEADER_INVALID , HTTP_DECODER_EVENT_MISSING_HOST_HEADER , HTTP_DECODER_EVENT_HOST_HEADER_AMBIGUOUS ,
HTTP_DECODER_EVENT_INVALID_REQUEST_FIELD_FOLDING , HTTP_DECODER_EVENT_INVALID_RESPONSE_FIELD_FOLDING , HTTP_DECODER_EVENT_REQUEST_FIELD_TOO_LONG , HTTP_DECODER_EVENT_RESPONSE_FIELD_TOO_LONG ,
HTTP_DECODER_EVENT_FILE_NAME_TOO_LONG , HTTP_DECODER_EVENT_REQUEST_SERVER_PORT_TCP_PORT_MISMATCH , HTTP_DECODER_EVENT_URI_HOST_INVALID , HTTP_DECODER_EVENT_HEADER_HOST_INVALID ,
HTTP_DECODER_EVENT_METHOD_DELIM_NON_COMPLIANT , HTTP_DECODER_EVENT_URI_DELIM_NON_COMPLIANT , HTTP_DECODER_EVENT_REQUEST_LINE_LEADING_WHITESPACE , HTTP_DECODER_EVENT_TOO_MANY_ENCODING_LAYERS ,
HTTP_DECODER_EVENT_ABNORMAL_CE_HEADER , HTTP_DECODER_EVENT_AUTH_UNRECOGNIZED , HTTP_DECODER_EVENT_REQUEST_HEADER_REPETITION , HTTP_DECODER_EVENT_RESPONSE_HEADER_REPETITION ,
HTTP_DECODER_EVENT_RESPONSE_MULTIPART_BYTERANGES , HTTP_DECODER_EVENT_RESPONSE_ABNORMAL_TRANSFER_ENCODING , HTTP_DECODER_EVENT_RESPONSE_CHUNKED_OLD_PROTO , HTTP_DECODER_EVENT_RESPONSE_INVALID_PROTOCOL ,
HTTP_DECODER_EVENT_RESPONSE_INVALID_STATUS , HTTP_DECODER_EVENT_REQUEST_LINE_INCOMPLETE , HTTP_DECODER_EVENT_DOUBLE_ENCODED_URI , HTTP_DECODER_EVENT_REQUEST_LINE_INVALID ,
HTTP_DECODER_EVENT_REQUEST_BODY_UNEXPECTED , HTTP_DECODER_EVENT_LZMA_MEMLIMIT_REACHED , HTTP_DECODER_EVENT_COMPRESSION_BOMB , HTTP_DECODER_EVENT_RANGE_INVALID ,
HTTP_DECODER_EVENT_MULTIPART_GENERIC_ERROR , HTTP_DECODER_EVENT_MULTIPART_NO_FILEDATA , HTTP_DECODER_EVENT_MULTIPART_INVALID_HEADER , HTTP_DECODER_EVENT_TOO_MANY_WARNINGS ,
HTTP_DECODER_EVENT_FAILED_PROTOCOL_CHANGE
}
enum HtpSwfCompressType_ { HTTP_SWF_COMPRESSION_NONE = 0 , HTTP_SWF_COMPRESSION_ZLIB , HTTP_SWF_COMPRESSION_LZMA , HTTP_SWF_COMPRESSION_BOTH }
Functions
struct HtpBodyChunk_ __attribute__ ((__packed__))
DNP3 link header.
SC_ATOMIC_EXTERN (uint32_t, htp_config_flags)
void RegisterHTPParsers (void)
Register the HTTP protocol and state handling functions to APP layer of the engine.
void HTPAtExitPrintStats (void)
Print the stats of the HTTP requests.
void HTPFreeConfig (void)
Clears the HTTP server configuration memory used by HTP library.
void HtpBodyPrint (HtpBody *)
Print the information and chunks of a Body.
void HtpBodyFree (HtpBody *)
Free the information held in the request body.
void HTPStateFree (void *)
Function to frees the HTTP state memory and also frees the HTTP connection parser memory which was used by the HTP library.
void AppLayerHtpEnableRequestBodyCallback (void)
Sets a flag that informs the HTP app layer that some module in the engine needs the http request body data. \initonly.
void AppLayerHtpEnableResponseBodyCallback (void)
Sets a flag that informs the HTP app layer that some module in the engine needs the http request body data. \initonly.
void AppLayerHtpNeedFileInspection (void)
Sets a flag that informs the HTP app layer that some module in the engine needs the http request file.
void AppLayerHtpPrintStats (void)
void HTPConfigure (void)
void HtpConfigCreateBackup (void)
void HtpConfigRestoreBackup (void)
void * HtpGetTxForH2 (void *)
void * HttpHeaderThreadDataInit (void *data)
void HttpHeaderThreadDataFree (void *data)
int HttpHeaderExpandBuffer (HttpHeaderThreadData *td, HttpHeaderBuffer *buf, uint32_t size)
HttpHeaderBuffer * HttpHeaderGetBufferSpace (DetectEngineThreadCtx *det_ctx, Flow *f, uint8_t flags, const int keyword_id, HttpHeaderThreadData **ret_hdr_td)
Detailed Description
Macro Definition Documentation
HTP_BOUNDARY_MAX
#define HTP_BOUNDARY_MAX 200U
a boundary should be smaller in size
Definition at line 64 of file app-layer-htp.h.
HTP_BOUNDARY_OPEN
#define HTP_BOUNDARY_OPEN BIT_U8(2)
We have a boundary string
Definition at line 206 of file app-layer-htp.h.
HTP_BOUNDARY_SET
#define HTP_BOUNDARY_SET BIT_U8(1)
We have a boundary string
Definition at line 205 of file app-layer-htp.h.
HTP_CONFIG_DEFAULT_COMPRESSION_BOMB_LIMIT
#define HTP_CONFIG_DEFAULT_COMPRESSION_BOMB_LIMIT 1048576U
Definition at line 56 of file app-layer-htp.h.
HTP_CONFIG_DEFAULT_COMPRESSION_TIME_LIMIT
#define HTP_CONFIG_DEFAULT_COMPRESSION_TIME_LIMIT 100000
Definition at line 58 of file app-layer-htp.h.
HTP_CONFIG_DEFAULT_FIELD_LIMIT_HARD
#define HTP_CONFIG_DEFAULT_FIELD_LIMIT_HARD 18000U
Definition at line 51 of file app-layer-htp.h.
HTP_CONFIG_DEFAULT_FIELD_LIMIT_SOFT
#define HTP_CONFIG_DEFAULT_FIELD_LIMIT_SOFT 9000U
Definition at line 50 of file app-layer-htp.h.
HTP_CONFIG_DEFAULT_LZMA_LAYERS
#define HTP_CONFIG_DEFAULT_LZMA_LAYERS 0U
Definition at line 53 of file app-layer-htp.h.
HTP_CONFIG_DEFAULT_LZMA_MEMLIMIT
#define HTP_CONFIG_DEFAULT_LZMA_MEMLIMIT 1048576U
Definition at line 55 of file app-layer-htp.h.
HTP_CONFIG_DEFAULT_RANDOMIZE
#define HTP_CONFIG_DEFAULT_RANDOMIZE 1
Definition at line 60 of file app-layer-htp.h.
HTP_CONFIG_DEFAULT_RANDOMIZE_RANGE
#define HTP_CONFIG_DEFAULT_RANDOMIZE_RANGE 10
Definition at line 61 of file app-layer-htp.h.
HTP_CONFIG_DEFAULT_REQUEST_BODY_LIMIT
#define HTP_CONFIG_DEFAULT_REQUEST_BODY_LIMIT 4096U
Definition at line 44 of file app-layer-htp.h.
HTP_CONFIG_DEFAULT_REQUEST_INSPECT_MIN_SIZE
#define HTP_CONFIG_DEFAULT_REQUEST_INSPECT_MIN_SIZE 32768U
Definition at line 46 of file app-layer-htp.h.
HTP_CONFIG_DEFAULT_REQUEST_INSPECT_WINDOW
#define HTP_CONFIG_DEFAULT_REQUEST_INSPECT_WINDOW 4096U
Definition at line 47 of file app-layer-htp.h.
HTP_CONFIG_DEFAULT_RESPONSE_BODY_LIMIT
#define HTP_CONFIG_DEFAULT_RESPONSE_BODY_LIMIT 4096U
Definition at line 45 of file app-layer-htp.h.
HTP_CONFIG_DEFAULT_RESPONSE_INSPECT_MIN_SIZE
#define HTP_CONFIG_DEFAULT_RESPONSE_INSPECT_MIN_SIZE 32768U
Definition at line 48 of file app-layer-htp.h.
HTP_CONFIG_DEFAULT_RESPONSE_INSPECT_WINDOW
#define HTP_CONFIG_DEFAULT_RESPONSE_INSPECT_WINDOW 4096U
Definition at line 49 of file app-layer-htp.h.
HTP_CONTENTTYPE_SET
#define HTP_CONTENTTYPE_SET BIT_U8(0)
We have the content type
Definition at line 204 of file app-layer-htp.h.
HTP_DONTSTORE
#define HTP_DONTSTORE BIT_U8(4)
not storing this file
Definition at line 208 of file app-layer-htp.h.
HTP_FILENAME_SET
#define HTP_FILENAME_SET BIT_U8(3)
filename is registered in the flow
Definition at line 207 of file app-layer-htp.h.
HTP_FLAG_STATE_CLOSED_TC
#define HTP_FLAG_STATE_CLOSED_TC 0x0004
Flag to indicate that HTTP connection is closed
Definition at line 70 of file app-layer-htp.h.
HTP_FLAG_STATE_CLOSED_TS
#define HTP_FLAG_STATE_CLOSED_TS 0x0002
Flag to indicate that HTTP connection is closed
Definition at line 68 of file app-layer-htp.h.
HTP_FLAG_STORE_FILES_TC
#define HTP_FLAG_STORE_FILES_TC 0x0080
Definition at line 72 of file app-layer-htp.h.
HTP_FLAG_STORE_FILES_TS
#define HTP_FLAG_STORE_FILES_TS 0x0040
Definition at line 71 of file app-layer-htp.h.
HTP_FLAG_STORE_FILES_TX_TC
#define HTP_FLAG_STORE_FILES_TX_TC 0x0200
Definition at line 74 of file app-layer-htp.h.
HTP_FLAG_STORE_FILES_TX_TS
#define HTP_FLAG_STORE_FILES_TX_TS 0x0100
Definition at line 73 of file app-layer-htp.h.
HTP_REQUIRE_REQUEST_BODY
#define HTP_REQUIRE_REQUEST_BODY (1 << 0)
part of the engine needs the request body (e.g. http_client_body keyword)
Definition at line 270 of file app-layer-htp.h.
HTP_REQUIRE_REQUEST_FILE
#define HTP_REQUIRE_REQUEST_FILE (1 << 2)
part of the engine needs the request file (e.g. log-file module)
Definition at line 275 of file app-layer-htp.h.
HTP_REQUIRE_REQUEST_MULTIPART
#define HTP_REQUIRE_REQUEST_MULTIPART (1 << 1)
part of the engine needs the request body multipart header (e.g. filename and / or fileext keywords)
Definition at line 273 of file app-layer-htp.h.
HTP_REQUIRE_RESPONSE_BODY
#define HTP_REQUIRE_RESPONSE_BODY (1 << 3)
part of the engine needs the request body (e.g. file_data keyword)
Definition at line 277 of file app-layer-htp.h.
HTP_STREAM_DEPTH_SET
#define HTP_STREAM_DEPTH_SET BIT_U8(5)
stream-depth is set
Definition at line 209 of file app-layer-htp.h.
Typedef Documentation
HtpBody
typedef struct HtpBody_ HtpBody
Struct used to hold all the chunks of a body on a request
HtpBodyChunk
typedef struct HtpBodyChunk_ HtpBodyChunk
Definition at line 187 of file app-layer-htp.h.
HTPCfgDir
typedef struct HTPCfgDir_ HTPCfgDir
HTPCfgRec
typedef struct HTPCfgRec_ HTPCfgRec
Need a linked list in order to keep track of these
HtpState
typedef struct HtpState_ HtpState
HtpSwfCompressType
typedef enum HtpSwfCompressType_ HtpSwfCompressType
HtpTxUserData
typedef struct HtpTxUserData_ HtpTxUserData
Now the Body Chunks will be stored per transaction, at the tx user data
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
HTP_BODY_REQUEST_NONE
HTP_BODY_REQUEST_MULTIPART
HTP_BODY_REQUEST_POST
HTP_BODY_REQUEST_PUT
Definition at line 76 of file app-layer-htp.h.
anonymous enum
anonymous enum
Enumerator
HTTP_DECODER_EVENT_UNKNOWN_ERROR
HTTP_DECODER_EVENT_GZIP_DECOMPRESSION_FAILED
HTTP_DECODER_EVENT_REQUEST_FIELD_MISSING_COLON
HTTP_DECODER_EVENT_RESPONSE_FIELD_MISSING_COLON
HTTP_DECODER_EVENT_INVALID_REQUEST_CHUNK_LEN
HTTP_DECODER_EVENT_INVALID_RESPONSE_CHUNK_LEN
HTTP_DECODER_EVENT_INVALID_TRANSFER_ENCODING_VALUE_IN_REQUEST
HTTP_DECODER_EVENT_INVALID_TRANSFER_ENCODING_VALUE_IN_RESPONSE
HTTP_DECODER_EVENT_INVALID_CONTENT_LENGTH_FIELD_IN_REQUEST
HTTP_DECODER_EVENT_INVALID_CONTENT_LENGTH_FIELD_IN_RESPONSE
HTTP_DECODER_EVENT_DUPLICATE_CONTENT_LENGTH_FIELD_IN_REQUEST
HTTP_DECODER_EVENT_DUPLICATE_CONTENT_LENGTH_FIELD_IN_RESPONSE
HTTP_DECODER_EVENT_100_CONTINUE_ALREADY_SEEN
HTTP_DECODER_EVENT_UNABLE_TO_MATCH_RESPONSE_TO_REQUEST
HTTP_DECODER_EVENT_INVALID_SERVER_PORT_IN_REQUEST
HTTP_DECODER_EVENT_INVALID_AUTHORITY_PORT
HTTP_DECODER_EVENT_REQUEST_HEADER_INVALID
HTTP_DECODER_EVENT_RESPONSE_HEADER_INVALID
HTTP_DECODER_EVENT_MISSING_HOST_HEADER
HTTP_DECODER_EVENT_HOST_HEADER_AMBIGUOUS
HTTP_DECODER_EVENT_INVALID_REQUEST_FIELD_FOLDING
HTTP_DECODER_EVENT_INVALID_RESPONSE_FIELD_FOLDING
HTTP_DECODER_EVENT_REQUEST_FIELD_TOO_LONG
HTTP_DECODER_EVENT_RESPONSE_FIELD_TOO_LONG
HTTP_DECODER_EVENT_FILE_NAME_TOO_LONG
HTTP_DECODER_EVENT_REQUEST_SERVER_PORT_TCP_PORT_MISMATCH
HTTP_DECODER_EVENT_URI_HOST_INVALID
HTTP_DECODER_EVENT_HEADER_HOST_INVALID
HTTP_DECODER_EVENT_METHOD_DELIM_NON_COMPLIANT
HTTP_DECODER_EVENT_URI_DELIM_NON_COMPLIANT
HTTP_DECODER_EVENT_REQUEST_LINE_LEADING_WHITESPACE
HTTP_DECODER_EVENT_TOO_MANY_ENCODING_LAYERS
HTTP_DECODER_EVENT_ABNORMAL_CE_HEADER
HTTP_DECODER_EVENT_AUTH_UNRECOGNIZED
HTTP_DECODER_EVENT_REQUEST_HEADER_REPETITION
HTTP_DECODER_EVENT_RESPONSE_HEADER_REPETITION
HTTP_DECODER_EVENT_RESPONSE_MULTIPART_BYTERANGES
HTTP_DECODER_EVENT_RESPONSE_ABNORMAL_TRANSFER_ENCODING
HTTP_DECODER_EVENT_RESPONSE_CHUNKED_OLD_PROTO
HTTP_DECODER_EVENT_RESPONSE_INVALID_PROTOCOL
HTTP_DECODER_EVENT_RESPONSE_INVALID_STATUS
HTTP_DECODER_EVENT_REQUEST_LINE_INCOMPLETE
HTTP_DECODER_EVENT_DOUBLE_ENCODED_URI
HTTP_DECODER_EVENT_REQUEST_LINE_INVALID
HTTP_DECODER_EVENT_REQUEST_BODY_UNEXPECTED
HTTP_DECODER_EVENT_LZMA_MEMLIMIT_REACHED
HTTP_DECODER_EVENT_COMPRESSION_BOMB
HTTP_DECODER_EVENT_RANGE_INVALID
HTTP_DECODER_EVENT_MULTIPART_GENERIC_ERROR
HTTP_DECODER_EVENT_MULTIPART_NO_FILEDATA
HTTP_DECODER_EVENT_MULTIPART_INVALID_HEADER
HTTP_DECODER_EVENT_TOO_MANY_WARNINGS
HTTP_DECODER_EVENT_FAILED_PROTOCOL_CHANGE
Definition at line 83 of file app-layer-htp.h.
HtpSwfCompressType_
enum HtpSwfCompressType_
Enumerator
HTTP_SWF_COMPRESSION_NONE
HTTP_SWF_COMPRESSION_ZLIB
HTTP_SWF_COMPRESSION_LZMA
HTTP_SWF_COMPRESSION_BOTH
Definition at line 146 of file app-layer-htp.h.
Function Documentation
__attribute__()
struct HtpBodyChunk_ __attribute__ ((__packed__))
DNP3 link header.
DNP3 internal indicators.
DNP3 application header.
Part of the application header for responses only.
Definition at line 102 of file decode-vlan.c.
AppLayerHtpEnableRequestBodyCallback()
void AppLayerHtpEnableRequestBodyCallback (void)
Sets a flag that informs the HTP app layer that some module in the engine needs the http request body data. \initonly.
Definition at line 466 of file app-layer-htp.c.
References HTP_REQUIRE_REQUEST_BODY, SC_ATOMIC_OR, SCEnter, and SCReturn.
Referenced by RunUnittests().
AppLayerHtpEnableResponseBodyCallback()
void AppLayerHtpEnableResponseBodyCallback (void)
Sets a flag that informs the HTP app layer that some module in the engine needs the http request body data. \initonly.
Definition at line 479 of file app-layer-htp.c.
References HTP_REQUIRE_RESPONSE_BODY, SC_ATOMIC_OR, SCEnter, and SCReturn.
AppLayerHtpNeedFileInspection()
void AppLayerHtpNeedFileInspection (void)
Sets a flag that informs the HTP app layer that some module in the engine needs the http request file.
\initonly
Definition at line 508 of file app-layer-htp.c.
References SCEnter.
Referenced by RunUnittests().
AppLayerHtpPrintStats()
void AppLayerHtpPrintStats (void)
Definition at line 2988 of file app-layer-htp.c.
References SCLogPerf, SCMutexLock, and SCMutexUnlock.
HTPAtExitPrintStats()
void HTPAtExitPrintStats (void)
Print the stats of the HTTP requests.
Definition at line 2029 of file app-layer-htp.c.
References SCEnter, SCLogDebug, SCMutexLock, SCMutexUnlock, and SCReturn.
HtpBodyFree()
void HtpBodyFree (HtpBody * body)
Free the information held in the request body.
Parameters
body pointer to the HtpBody holding the list
Return values
none
Definition at line 153 of file app-layer-htp-body.c.
References HtpBody_::first, HTPFree(), HtpBody_::last, HtpBodyChunk_::next, HtpBody_::sb, SCEnter, SCLogDebug, and StreamingBufferFree().
HtpBodyPrint()
void HtpBodyPrint (HtpBody * body)
Print the information and chunks of a Body.
Parameters
body pointer to the HtpBody holding the list
Return values
none
Definition at line 125 of file app-layer-htp-body.c.
References HtpBody_::first, HtpBodyChunk_::next, PrintRawDataFp(), HtpBody_::sb, HtpBodyChunk_::sbseg, SCEnter, SCLogDebug, SCLogDebugEnabled(), and StreamingBufferSegmentGetData().
HtpConfigCreateBackup()
void HtpConfigCreateBackup (void)
Definition at line 3232 of file app-layer-htp.c.
HtpConfigRestoreBackup()
void HtpConfigRestoreBackup (void)
Definition at line 3239 of file app-layer-htp.c.
HTPConfigure()
void HTPConfigure (void)
Definition at line 2916 of file app-layer-htp.c.
References SCEnter.
HTPFreeConfig()
void HTPFreeConfig (void)
Clears the HTTP server configuration memory used by HTP library.
Definition at line 2042 of file app-layer-htp.c.
References AppLayerParserConfParserEnabled(), AppLayerProtoDetectConfProtoDetectionEnabled(), SCEnter, and SCReturn.
HtpGetTxForH2()
void * HtpGetTxForH2 (void * alstate)
Definition at line 3050 of file app-layer-htp.c.
References HtpState_::conn.
Referenced by HTTP2MimicHttp1Request().
HTPStateFree()
void HTPStateFree (void * state)
Function to frees the HTTP state memory and also frees the HTTP connection parser memory which was used by the HTP library.
Definition at line 376 of file app-layer-htp.c.
References HtpState_::connp, SCEnter, SCLogDebug, and SCReturn.
HttpHeaderExpandBuffer()
int HttpHeaderExpandBuffer (HttpHeaderThreadData * td, HttpHeaderBuffer * buf, uint32_t size)
Definition at line 83 of file detect-http-header-common.c.
References HttpHeaderBuffer_::buffer, HttpHeaderBuffer_::len, SCLogDebug, SCRealloc, HttpHeaderBuffer_::size, HttpHeaderThreadData_::size_step, and unlikely.
Referenced by HttpHeaderThreadDataInit().
HttpHeaderGetBufferSpace()
HttpHeaderBuffer * HttpHeaderGetBufferSpace (DetectEngineThreadCtx * det_ctx, Flow * f, uint8_t flags, const int keyword_id, HttpHeaderThreadData ** ret_hdr_td)
Definition at line 102 of file detect-http-header-common.c.
References HttpHeaderThreadData_::buffer, DetectThreadCtxGetGlobalKeywordThreadCtx(), and HttpHeaderBuffer_::len.
HttpHeaderThreadDataFree()
void HttpHeaderThreadDataFree (void * data)
Definition at line 76 of file detect-http-header-common.c.
References HttpHeaderBuffer_::buffer, HttpHeaderThreadData_::buffer, and SCFree.
HttpHeaderThreadDataInit()
void * HttpHeaderThreadDataInit (void * data)
Definition at line 59 of file detect-http-header-common.c.
References HttpHeaderThreadData_::buffer, HttpHeaderExpandBuffer(), SCCalloc, HttpHeaderThreadConfig_::size_step, and HttpHeaderThreadData_::size_step.
RegisterHTPParsers()
void RegisterHTPParsers (void)
Register the HTTP protocol and state handling functions to APP layer of the engine.
HTTP
Definition at line 3165 of file app-layer-htp.c.
References ALPROTO_HTTP1, AppLayerProtoDetectConfProtoDetectionEnabled(), AppLayerProtoDetectRegisterProtocol(), and SCEnter.
SC_ATOMIC_EXTERN()
SC_ATOMIC_EXTERN (uint32_t , htp_config_flags)