suricata: /Users/jlu/suricata/src/host-storage.h File Reference
host-storage.h File Reference
#include "host.h"
Data Structures
struct HostStorageId_
Typedefs
typedef struct HostStorageId_ HostStorageId
Functions
unsigned int HostStorageSize (void)
void * HostGetStorageById (Host *h, HostStorageId id)
Get a value from a given Host storage.
int HostSetStorageById (Host *h, HostStorageId id, void *ptr)
Store a pointer in a given Host storage.
void * HostAllocStorageById (Host *h, HostStorageId id)
void HostFreeStorageById (Host *h, HostStorageId id)
void HostFreeStorage (Host *h)
void RegisterHostStorageTests (void)
HostStorageId HostStorageRegister (const char *name, const unsigned int size, void *(*Alloc)(unsigned int), void(*Free)(void *))
Register a Host storage.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Host wrapper around storage api
Definition in file host-storage.h.
Typedef Documentation
HostStorageId
typedef struct HostStorageId_ HostStorageId
Function Documentation
HostAllocStorageById()
void * HostAllocStorageById (Host * h, HostStorageId id)
Definition at line 99 of file host-storage.c.
References STORAGE_HOST, and StorageAllocByIdPrealloc().
HostFreeStorage()
void HostFreeStorage (Host * h)
Definition at line 109 of file host-storage.c.
References HostStorageSize(), STORAGE_HOST, and StorageFreeAll().
Referenced by HostCleanup(), and HostClearMemory().
HostFreeStorageById()
void HostFreeStorageById (Host * h, HostStorageId id)
Definition at line 104 of file host-storage.c.
References STORAGE_HOST, and StorageFreeById().
HostStorageSize()
unsigned int HostStorageSize (void)
Definition at line 30 of file host-storage.c.
References STORAGE_HOST, and StorageGetSize().
Referenced by HostClearMemory(), HostFreeStorage(), and HostInitConfig().
RegisterHostStorageTests()
void RegisterHostStorageTests (void)
Definition at line 335 of file host-storage.c.
References UtRegisterTest().
Referenced by HostRegisterUnittests().