suricata: /Users/jlu/suricata/src/host-queue.c File Reference
host-queue.c File Reference
#include "suricata-common.h"
#include "threads.h"
#include "host-queue.h"
#include "util-error.h"
#include "util-debug.h"
#include "util-print.h"
Functions
HostQueue * HostQueueInit (HostQueue *q)
HostQueue * HostQueueNew ()
void HostQueueDestroy (HostQueue *q)
Destroy a host queue.
void HostEnqueue (HostQueue *q, Host *h)
add a host to a queue
Host * HostDequeue (HostQueue *q)
remove a host from the queue
uint32_t HostQueueLen (HostQueue *q)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Host queue handler functions
Definition in file host-queue.c.
Function Documentation
HostDequeue()
Host * HostDequeue (HostQueue * q)
remove a host from the queue
Parameters
q queue
Return values
h host or NULL if empty list.
Definition at line 102 of file host-queue.c.
References HostQueue_::bot, BUG_ON, HQLOCK_LOCK, HQLOCK_UNLOCK, HostQueue_::len, Host_::lnext, Host_::lprev, and HostQueue_::top.
Referenced by HostShutdown().
HostEnqueue()
void HostEnqueue (HostQueue * q, Host * h)
add a host to a queue
Parameters
q queue
h host
Definition at line 69 of file host-queue.c.
References HostQueue_::bot, BUG_ON, HQLOCK_LOCK, HQLOCK_UNLOCK, HostQueue_::len, Host_::lnext, Host_::lprev, and HostQueue_::top.
Referenced by HostMoveToSpare().
HostQueueDestroy()
void HostQueueDestroy (HostQueue * q)
Destroy a host queue.
Parameters
q the host queue to destroy
Definition at line 58 of file host-queue.c.
References HQLOCK_DESTROY.
HostQueueInit()
HostQueue * HostQueueInit (HostQueue * q)
Definition at line 33 of file host-queue.c.
References HQLOCK_INIT.
Referenced by HostQueueNew().
HostQueueLen()
uint32_t HostQueueLen (HostQueue * q)
Definition at line 135 of file host-queue.c.
References HQLOCK_LOCK, HQLOCK_UNLOCK, len, and HostQueue_::len.
Referenced by HostSpareQueueGetSize().
HostQueueNew()
HostQueue * HostQueueNew (void)
Definition at line 42 of file host-queue.c.
References HostQueueInit(), SC_ERR_FATAL, SCLogError, and SCMalloc.