suricata: /Users/jlu/suricata/src/host.c File Reference
host.c File Reference
#include "suricata-common.h"
#include "conf.h"
#include "util-debug.h"
#include "host.h"
#include "host-storage.h"
#include "host-bit.h"
#include "util-random.h"
#include "util-misc.h"
#include "util-byte.h"
#include "util-validate.h"
#include "host-queue.h"
#include "detect-tag.h"
#include "detect-engine-tag.h"
#include "detect-engine-threshold.h"
#include "util-hash-lookup3.h"
Macros
#define HOST_DEFAULT_HASHSIZE 4096
#define HOST_DEFAULT_MEMCAP 16777216
#define HOST_DEFAULT_PREALLOC 1000
Functions
SC_ATOMIC_DECLARE (uint64_t, host_memuse)
SC_ATOMIC_DECLARE (uint32_t, host_counter)
SC_ATOMIC_DECLARE (uint32_t, host_prune_idx)
int HostSetMemcap (uint64_t size)
Update memcap value.
uint64_t HostGetMemcap (void)
Return memcap value.
uint64_t HostGetMemuse (void)
Return memuse value.
uint32_t HostSpareQueueGetSize (void)
void HostMoveToSpare (Host *h)
Host * HostAlloc (void)
void HostFree (Host *h)
void HostClearMemory (Host *h)
void HostInitConfig (bool quiet)
initialize the configuration
void HostPrintStats (void)
print some host stats
void HostShutdown (void)
shutdown the flow engine
void HostCleanup (void)
Cleanup the host engine.
void HostRelease (Host *h)
void HostLock (Host *h)
void HostUnlock (Host *h)
Host * HostGetHostFromHash (Address *a)
Host * HostLookupHostFromHash (Address *a)
look up a host in the hash
void HostRegisterUnittests (void)
Variables
HostHashRow * host_hash
HostConfig host_config
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Information about hosts.
Definition in file host.c.
Macro Definition Documentation
HOST_DEFAULT_HASHSIZE
#define HOST_DEFAULT_HASHSIZE 4096
Definition at line 169 of file host.c.
HOST_DEFAULT_MEMCAP
#define HOST_DEFAULT_MEMCAP 16777216
Definition at line 170 of file host.c.
HOST_DEFAULT_PREALLOC
#define HOST_DEFAULT_PREALLOC 1000
Definition at line 171 of file host.c.
Function Documentation
HostAlloc()
Host * HostAlloc (void)
Definition at line 111 of file host.c.
References HOST_CHECK_MEMCAP.
HostCleanup()
void HostCleanup (void)
Cleanup the host engine.
Cleanup the host engine from tag and threshold.
Definition at line 343 of file host.c.
References HostConfig_::hash_size, Host_::hnext, host_config, host_hash, HostClearMemory(), HostFreeStorage(), HostMoveToSpare(), Host_::hprev, HRLOCK_LOCK, HRLOCK_UNLOCK, Host_::iprep, and SC_ATOMIC_GET.
HostClearMemory()
void HostClearMemory (Host * h)
Definition at line 157 of file host.c.
References BUG_ON, HostFreeStorage(), HostStorageSize(), Host_::iprep, SC_ATOMIC_GET, and SRepFreeHostData().
Referenced by HostCleanup(), and HostFree().
HostFree()
void HostFree (Host * h)
Definition at line 132 of file host.c.
References HostClearMemory(), Host_::m, SC_ATOMIC_SUB, SCFree, and SCMutexDestroy.
HostGetHostFromHash()
Host * HostGetHostFromHash (Address * a)
Definition at line 502 of file host.c.
Referenced by TagHashAddTag().
HostGetMemcap()
uint64_t HostGetMemcap (void)
Return memcap value.
Return values
memcap value
Definition at line 83 of file host.c.
References host_config, and SC_ATOMIC_GET.
HostGetMemuse()
uint64_t HostGetMemuse (void)
Return memuse value.
Return values
memuse value
Definition at line 94 of file host.c.
References SC_ATOMIC_GET.
HostInitConfig()
void HostInitConfig (bool quiet)
initialize the configuration
Warning
Not thread safe
set config values for memcap, prealloc and hash_size
Definition at line 175 of file host.c.
References DEBUG_VALIDATE_BUG_ON, HostStorageSize(), and SCLogDebug.
HostLock()
void HostLock (Host * h)
Definition at line 483 of file host.c.
References Host_::m, and SCMutexLock.
HostLookupHostFromHash()
Host * HostLookupHostFromHash (Address * a)
look up a host in the hash
Parameters
a address to look up
Return values
h LOCKED host or NULL
Definition at line 601 of file host.c.
HostMoveToSpare()
void HostMoveToSpare (Host * h)
Definition at line 105 of file host.c.
References HostEnqueue().
Referenced by HostCleanup().
HostPrintStats()
void HostPrintStats (void)
print some host stats
Warning
Not thread safe
Definition at line 293 of file host.c.
References host_config, SC_ATOMIC_GET, and SCLogPerf.
Referenced by HostShutdown().
HostRegisterUnittests()
void HostRegisterUnittests (void)
Definition at line 733 of file host.c.
References RegisterHostStorageTests().
HostRelease()
void HostRelease (Host * h)
Definition at line 477 of file host.c.
References HostDecrUsecnt, Host_::m, and SCMutexUnlock.
HostSetMemcap()
int HostSetMemcap (uint64_t size)
Update memcap value.
Parameters
size new memcap value
Definition at line 68 of file host.c.
References host_config, SC_ATOMIC_GET, and SC_ATOMIC_SET.
HostShutdown()
void HostShutdown (void)
shutdown the flow engine
Warning
Not thread safe
Definition at line 306 of file host.c.
References HostDequeue(), and HostPrintStats().
HostSpareQueueGetSize()
uint32_t HostSpareQueueGetSize (void)
Definition at line 100 of file host.c.
References HostQueueLen().
Referenced by HostGetSpareCount().
HostUnlock()
void HostUnlock (Host * h)
Definition at line 488 of file host.c.
References Host_::m, and SCMutexUnlock.
SC_ATOMIC_DECLARE() [1/3]
SC_ATOMIC_DECLARE (uint32_t , host_counter)
SC_ATOMIC_DECLARE() [2/3]
SC_ATOMIC_DECLARE (uint32_t , host_prune_idx)
SC_ATOMIC_DECLARE() [3/3]
SC_ATOMIC_DECLARE (uint64_t , host_memuse)
Variable Documentation
host_config
HostConfig host_config
Definition at line 53 of file host.c.
Referenced by HostCleanup(), HostGetMemcap(), HostPrintStats(), and HostSetMemcap().
host_hash
HostHashRow* host_hash
host hash table
Definition at line 50 of file host.c.
Referenced by HostCleanup().