suricata: /Users/jlu/suricata/src/ippair-queue.h File Reference
ippair-queue.h File Reference
#include "suricata-common.h"
#include "ippair.h"
Data Structures
struct IPPairQueue_
Macros
#define HQLOCK_MUTEX
#define HQLOCK_INIT(q) SCMutexInit(&(q)->m, NULL)
#define HQLOCK_DESTROY(q) SCMutexDestroy(&(q)->m)
#define HQLOCK_LOCK(q) SCMutexLock(&(q)->m)
#define HQLOCK_TRYLOCK(q) SCMutexTrylock(&(q)->m)
#define HQLOCK_UNLOCK(q) SCMutexUnlock(&(q)->m)
Typedefs
typedef struct IPPairQueue_ IPPairQueue
Functions
IPPairQueue * IPPairQueueNew (void)
IPPairQueue * IPPairQueueInit (IPPairQueue *)
void IPPairQueueDestroy (IPPairQueue *)
Destroy a ippair queue.
void IPPairEnqueue (IPPairQueue *, IPPair *)
add a ippair to a queue
IPPair * IPPairDequeue (IPPairQueue *)
remove a ippair from the queue
uint32_t IPPairQueueLen (IPPairQueue *)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file ippair-queue.h.
Macro Definition Documentation
HQLOCK_DESTROY
#define HQLOCK_DESTROY (q) SCMutexDestroy(&(q)->m)
Definition at line 66 of file ippair-queue.h.
HQLOCK_INIT
#define HQLOCK_INIT (q) SCMutexInit(&(q)->m, NULL)
Definition at line 65 of file ippair-queue.h.
HQLOCK_LOCK
#define HQLOCK_LOCK (q) SCMutexLock(&(q)->m)
Definition at line 67 of file ippair-queue.h.
HQLOCK_MUTEX
#define HQLOCK_MUTEX
Spinlocks or Mutex for the ippair queues.
Definition at line 32 of file ippair-queue.h.
HQLOCK_TRYLOCK
#define HQLOCK_TRYLOCK (q) SCMutexTrylock(&(q)->m)
Definition at line 68 of file ippair-queue.h.
HQLOCK_UNLOCK
#define HQLOCK_UNLOCK (q) SCMutexUnlock(&(q)->m)
Definition at line 69 of file ippair-queue.h.
Typedef Documentation
IPPairQueue
typedef struct IPPairQueue_ IPPairQueue
Function Documentation
IPPairDequeue()
IPPair * IPPairDequeue (IPPairQueue * q)
remove a ippair from the queue
Parameters
q queue
Return values
h ippair or NULL if empty list.
Definition at line 102 of file ippair-queue.c.
References IPPairQueue_::bot, BUG_ON, HQLOCK_LOCK, HQLOCK_UNLOCK, IPPairQueue_::len, IPPair_::lnext, IPPair_::lprev, and IPPairQueue_::top.
Referenced by IPPairShutdown().
IPPairEnqueue()
void IPPairEnqueue (IPPairQueue * q, IPPair * h)
add a ippair to a queue
Parameters
q queue
h ippair
Definition at line 69 of file ippair-queue.c.
References IPPairQueue_::bot, BUG_ON, HQLOCK_LOCK, HQLOCK_UNLOCK, IPPairQueue_::len, IPPair_::lnext, IPPair_::lprev, and IPPairQueue_::top.
Referenced by IPPairMoveToSpare().
IPPairQueueDestroy()
void IPPairQueueDestroy (IPPairQueue * q)
Destroy a ippair queue.
Parameters
q the ippair queue to destroy
Definition at line 58 of file ippair-queue.c.
References HQLOCK_DESTROY.
IPPairQueueInit()
IPPairQueue * IPPairQueueInit (IPPairQueue * q)
Definition at line 33 of file ippair-queue.c.
References HQLOCK_INIT.
Referenced by IPPairQueueNew().
IPPairQueueLen()
uint32_t IPPairQueueLen (IPPairQueue * q)
Definition at line 135 of file ippair-queue.c.
References HQLOCK_LOCK, HQLOCK_UNLOCK, len, and IPPairQueue_::len.
Referenced by IPPairSpareQueueGetSize().
IPPairQueueNew()
IPPairQueue * IPPairQueueNew (void)
Definition at line 42 of file ippair-queue.c.
References IPPairQueueInit(), SC_ERR_FATAL, SCLogError, and SCMalloc.