suricata: /Users/jlu/suricata/src/ippair.c File Reference
ippair.c File Reference
#include "suricata-common.h"
#include "conf.h"
#include "util-debug.h"
#include "ippair.h"
#include "ippair-storage.h"
#include "util-random.h"
#include "util-misc.h"
#include "util-byte.h"
#include "util-validate.h"
#include "ippair-queue.h"
#include "detect-tag.h"
#include "detect-engine-tag.h"
#include "detect-engine-threshold.h"
#include "util-hash-lookup3.h"
Macros
#define IPPAIR_DEFAULT_HASHSIZE 4096
#define IPPAIR_DEFAULT_MEMCAP 16777216
#define IPPAIR_DEFAULT_PREALLOC 1000
Functions
SC_ATOMIC_DECLARE (uint64_t, ippair_memuse)
SC_ATOMIC_DECLARE (uint32_t, ippair_counter)
SC_ATOMIC_DECLARE (uint32_t, ippair_prune_idx)
int IPPairSetMemcap (uint64_t size)
Update memcap value.
uint64_t IPPairGetMemcap (void)
Return memcap value.
uint64_t IPPairGetMemuse (void)
Return memuse value.
uint32_t IPPairSpareQueueGetSize (void)
void IPPairMoveToSpare (IPPair *h)
IPPair * IPPairAlloc (void)
void IPPairFree (IPPair *h)
void IPPairClearMemory (IPPair *h)
void IPPairInitConfig (bool quiet)
initialize the configuration
void IPPairPrintStats (void)
print some ippair stats
void IPPairShutdown (void)
shutdown the flow engine
void IPPairCleanup (void)
Cleanup the ippair engine.
void IPPairRelease (IPPair *h)
void IPPairLock (IPPair *h)
void IPPairUnlock (IPPair *h)
IPPair * IPPairGetIPPairFromHash (Address *a, Address *b)
IPPair * IPPairLookupIPPairFromHash (Address *a, Address *b)
look up a ippair in the hash
void IPPairRegisterUnittests (void)
Variables
IPPairHashRow * ippair_hash
IPPairConfig ippair_config
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Information about ippairs.
Definition in file ippair.c.
Macro Definition Documentation
IPPAIR_DEFAULT_HASHSIZE
#define IPPAIR_DEFAULT_HASHSIZE 4096
Definition at line 163 of file ippair.c.
IPPAIR_DEFAULT_MEMCAP
#define IPPAIR_DEFAULT_MEMCAP 16777216
Definition at line 164 of file ippair.c.
IPPAIR_DEFAULT_PREALLOC
#define IPPAIR_DEFAULT_PREALLOC 1000
Definition at line 165 of file ippair.c.
Function Documentation
IPPairAlloc()
IPPair * IPPairAlloc (void)
Definition at line 109 of file ippair.c.
References IPPAIR_CHECK_MEMCAP.
IPPairCleanup()
void IPPairCleanup (void)
Cleanup the ippair engine.
Cleanup the ippair engine from tag and threshold.
Definition at line 341 of file ippair.c.
References IPPairConfig_::hash_size, IPPair_::hnext, IPPair_::hprev, HRLOCK_LOCK, HRLOCK_UNLOCK, ippair_config, ippair_hash, IPPairClearMemory(), IPPairFreeStorage(), IPPairMoveToSpare(), and SC_ATOMIC_GET.
IPPairClearMemory()
void IPPairClearMemory (IPPair * h)
Definition at line 157 of file ippair.c.
References IPPairFreeStorage(), and IPPairStorageSize().
Referenced by IPPairCleanup(), and IPPairFree().
IPPairFree()
void IPPairFree (IPPair * h)
Definition at line 131 of file ippair.c.
References IPPairClearMemory(), IPPair_::m, SC_ATOMIC_SUB, SCFree, and SCMutexDestroy.
IPPairGetIPPairFromHash()
IPPair * IPPairGetIPPairFromHash (Address * a, Address * b)
Definition at line 545 of file ippair.c.
IPPairGetMemcap()
uint64_t IPPairGetMemcap (void)
Return memcap value.
Return values
memcap value
Definition at line 81 of file ippair.c.
References ippair_config, and SC_ATOMIC_GET.
IPPairGetMemuse()
uint64_t IPPairGetMemuse (void)
Return memuse value.
Return values
memuse value
Definition at line 92 of file ippair.c.
References SC_ATOMIC_GET.
IPPairInitConfig()
void IPPairInitConfig (bool quiet)
initialize the configuration
Warning
Not thread safe
set config values for memcap, prealloc and hash_size
Definition at line 169 of file ippair.c.
References DEBUG_VALIDATE_BUG_ON, IPPairStorageSize(), and SCLogDebug.
Referenced by PreRunInit(), and StreamTcpUTInit().
IPPairLock()
void IPPairLock (IPPair * h)
Definition at line 527 of file ippair.c.
References IPPair_::m, and SCMutexLock.
IPPairLookupIPPairFromHash()
IPPair * IPPairLookupIPPairFromHash (Address * a, Address * b)
look up a ippair in the hash
Parameters
a address to look up
Return values
h LOCKED ippair or NULL
Definition at line 644 of file ippair.c.
IPPairMoveToSpare()
void IPPairMoveToSpare (IPPair * h)
Definition at line 103 of file ippair.c.
References IPPairEnqueue().
Referenced by IPPairCleanup().
IPPairPrintStats()
void IPPairPrintStats (void)
print some ippair stats
Warning
Not thread safe
Definition at line 290 of file ippair.c.
References ippair_config, SC_ATOMIC_GET, and SCLogPerf.
Referenced by IPPairShutdown().
IPPairRegisterUnittests()
void IPPairRegisterUnittests (void)
Definition at line 776 of file ippair.c.
References RegisterIPPairStorageTests().
IPPairRelease()
void IPPairRelease (IPPair * h)
Definition at line 521 of file ippair.c.
References IPPairDecrUsecnt, IPPair_::m, and SCMutexUnlock.
IPPairSetMemcap()
int IPPairSetMemcap (uint64_t size)
Update memcap value.
Parameters
size new memcap value
Definition at line 66 of file ippair.c.
References ippair_config, SC_ATOMIC_GET, and SC_ATOMIC_SET.
IPPairShutdown()
void IPPairShutdown (void)
shutdown the flow engine
Warning
Not thread safe
Definition at line 303 of file ippair.c.
References IPPairDequeue(), and IPPairPrintStats().
IPPairSpareQueueGetSize()
uint32_t IPPairSpareQueueGetSize (void)
Definition at line 98 of file ippair.c.
References IPPairQueueLen().
Referenced by IPPairGetSpareCount().
IPPairUnlock()
void IPPairUnlock (IPPair * h)
Definition at line 532 of file ippair.c.
References IPPair_::m, and SCMutexUnlock.
SC_ATOMIC_DECLARE() [1/3]
SC_ATOMIC_DECLARE (uint32_t , ippair_counter)
SC_ATOMIC_DECLARE() [2/3]
SC_ATOMIC_DECLARE (uint32_t , ippair_prune_idx)
SC_ATOMIC_DECLARE() [3/3]
SC_ATOMIC_DECLARE (uint64_t , ippair_memuse)
Variable Documentation
ippair_config
IPPairConfig ippair_config
Definition at line 52 of file ippair.c.
Referenced by IPPairCleanup(), IPPairGetMemcap(), IPPairPrintStats(), and IPPairSetMemcap().
ippair_hash
IPPairHashRow* ippair_hash
ippair hash table
Definition at line 49 of file ippair.c.
Referenced by IPPairCleanup().