suricata: /Users/jlu/suricata/src/ippair-storage.h File Reference
ippair-storage.h File Reference
#include "ippair.h"
Data Structures
struct IPPairStorageId
Typedefs
typedef struct IPPairStorageId IPPairStorageId
Functions
unsigned int IPPairStorageSize (void)
void * IPPairGetStorageById (IPPair *h, IPPairStorageId id)
int IPPairSetStorageById (IPPair *h, IPPairStorageId id, void *ptr)
void * IPPairAllocStorageById (IPPair *h, IPPairStorageId id)
void IPPairFreeStorageById (IPPair *h, IPPairStorageId id)
void IPPairFreeStorage (IPPair *h)
void RegisterIPPairStorageTests (void)
IPPairStorageId IPPairStorageRegister (const char *name, const unsigned int size, void *(*Alloc)(unsigned int), void(*Free)(void *))
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
IPPair wrapper around storage api
Definition in file ippair-storage.h.
Typedef Documentation
IPPairStorageId
typedef struct IPPairStorageId IPPairStorageId
Function Documentation
IPPairAllocStorageById()
void * IPPairAllocStorageById (IPPair * h, IPPairStorageId id)
Definition at line 45 of file ippair-storage.c.
References STORAGE_IPPAIR, and StorageAllocByIdPrealloc().
IPPairFreeStorage()
void IPPairFreeStorage (IPPair * h)
Definition at line 55 of file ippair-storage.c.
References IPPairStorageSize(), STORAGE_IPPAIR, and StorageFreeAll().
Referenced by IPPairCleanup(), and IPPairClearMemory().
IPPairFreeStorageById()
void IPPairFreeStorageById (IPPair * h, IPPairStorageId id)
Definition at line 50 of file ippair-storage.c.
References STORAGE_IPPAIR, and StorageFreeById().
IPPairGetStorageById()
void * IPPairGetStorageById (IPPair * h, IPPairStorageId id)
Definition at line 35 of file ippair-storage.c.
References STORAGE_IPPAIR, and StorageGetById().
Referenced by IPPairBitsTimedoutCheck(), IPPairHasBits(), ThresholdIPPairHasThreshold(), and ThresholdIPPairTimeoutCheck().
IPPairSetStorageById()
int IPPairSetStorageById (IPPair * h, IPPairStorageId id, void * ptr)
Definition at line 40 of file ippair-storage.c.
References STORAGE_IPPAIR, and StorageSetById().
IPPairStorageRegister()
IPPairStorageId IPPairStorageRegister (const char * name, const unsigned int size, void *(*)(unsigned int) Alloc, void(*)(void *) Free)
Definition at line 61 of file ippair-storage.c.
References IPPairStorageId::id, STORAGE_IPPAIR, and StorageRegister().
IPPairStorageSize()
unsigned int IPPairStorageSize (void)
Definition at line 30 of file ippair-storage.c.
References STORAGE_IPPAIR, and StorageGetSize().
Referenced by IPPairClearMemory(), IPPairFreeStorage(), and IPPairInitConfig().
RegisterIPPairStorageTests()
void RegisterIPPairStorageTests (void)
Definition at line 297 of file ippair-storage.c.
References UtRegisterTest().
Referenced by IPPairRegisterUnittests().