suricata: /Users/jlu/suricata/src/ippair-queue.c File Reference
ippair-queue.c File Reference
#include "suricata-common.h"
#include "threads.h"
#include "ippair-queue.h"
#include "util-error.h"
#include "util-debug.h"
#include "util-print.h"
Functions
IPPairQueue * IPPairQueueInit (IPPairQueue *q)
IPPairQueue * IPPairQueueNew ()
void IPPairQueueDestroy (IPPairQueue *q)
Destroy a ippair queue.
void IPPairEnqueue (IPPairQueue *q, IPPair *h)
add a ippair to a queue
IPPair * IPPairDequeue (IPPairQueue *q)
remove a ippair from the queue
uint32_t IPPairQueueLen (IPPairQueue *q)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
IPPair queue handler functions
Definition in file ippair-queue.c.
Function Documentation
IPPairDequeue()
IPPair * IPPairDequeue (IPPairQueue * q)
remove a ippair from the queue
Parameters
q queue
Return values
h ippair or NULL if empty list.
Definition at line 102 of file ippair-queue.c.
References IPPairQueue_::bot, BUG_ON, HQLOCK_LOCK, HQLOCK_UNLOCK, IPPairQueue_::len, IPPair_::lnext, IPPair_::lprev, and IPPairQueue_::top.
Referenced by IPPairShutdown().
IPPairEnqueue()
void IPPairEnqueue (IPPairQueue * q, IPPair * h)
add a ippair to a queue
Parameters
q queue
h ippair
Definition at line 69 of file ippair-queue.c.
References IPPairQueue_::bot, BUG_ON, HQLOCK_LOCK, HQLOCK_UNLOCK, IPPairQueue_::len, IPPair_::lnext, IPPair_::lprev, and IPPairQueue_::top.
Referenced by IPPairMoveToSpare().
IPPairQueueDestroy()
void IPPairQueueDestroy (IPPairQueue * q)
Destroy a ippair queue.
Parameters
q the ippair queue to destroy
Definition at line 58 of file ippair-queue.c.
References HQLOCK_DESTROY.
IPPairQueueInit()
IPPairQueue * IPPairQueueInit (IPPairQueue * q)
Definition at line 33 of file ippair-queue.c.
References HQLOCK_INIT.
Referenced by IPPairQueueNew().
IPPairQueueLen()
uint32_t IPPairQueueLen (IPPairQueue * q)
Definition at line 135 of file ippair-queue.c.
References HQLOCK_LOCK, HQLOCK_UNLOCK, len, and IPPairQueue_::len.
Referenced by IPPairSpareQueueGetSize().
IPPairQueueNew()
IPPairQueue * IPPairQueueNew (void)
Definition at line 42 of file ippair-queue.c.
References IPPairQueueInit(), SC_ERR_FATAL, SCLogError, and SCMalloc.