suricata: /Users/jlu/suricata/src/ippair-bit.h File Reference
ippair-bit.h File Reference
#include "ippair.h"
Functions
void IPPairBitInitCtx (void)
void IPPairBitRegisterTests (void)
int IPPairHasBits (IPPair *host)
int IPPairBitsTimedoutCheck (IPPair *h, struct timeval *ts)
void IPPairBitSet (IPPair *, uint32_t, uint32_t)
void IPPairBitUnset (IPPair *, uint32_t)
void IPPairBitToggle (IPPair *, uint32_t, uint32_t)
int IPPairBitIsset (IPPair *, uint32_t, uint32_t)
int IPPairBitIsnotset (IPPair *, uint32_t, uint32_t)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file ippair-bit.h.
Function Documentation
IPPairBitInitCtx()
void IPPairBitInitCtx (void)
Definition at line 49 of file ippair-bit.c.
IPPairBitIsnotset()
int IPPairBitIsnotset (IPPair * h, uint32_t idx, uint32_t ts)
Definition at line 171 of file ippair-bit.c.
IPPairBitIsset()
int IPPairBitIsset (IPPair * h, uint32_t idx, uint32_t ts)
Definition at line 157 of file ippair-bit.c.
IPPairBitRegisterTests()
void IPPairBitRegisterTests (void)
Definition at line 492 of file ippair-bit.c.
References UtRegisterTest().
IPPairBitSet()
void IPPairBitSet (IPPair * h, uint32_t idx, uint32_t expire)
Definition at line 131 of file ippair-bit.c.
IPPairBitsTimedoutCheck()
int IPPairBitsTimedoutCheck (IPPair * h, struct timeval * ts)
Return values
1 ippair timed out wrt xbits
0 ippair still has active (non-expired) xbits
Definition at line 67 of file ippair-bit.c.
References IPPairGetStorageById().
IPPairBitToggle()
void IPPairBitToggle (IPPair * h, uint32_t idx, uint32_t expire)
Definition at line 147 of file ippair-bit.c.
IPPairBitUnset()
void IPPairBitUnset (IPPair * h, uint32_t idx)
Definition at line 139 of file ippair-bit.c.
IPPairHasBits()
int IPPairHasBits (IPPair * host)
Definition at line 58 of file ippair-bit.c.
References IPPairGetStorageById().