suricata: /Users/jlu/suricata/src/log-cf-common.c File Reference
log-cf-common.c File Reference
#include "log-cf-common.h"
#include "util-print.h"
#include "util-unittest.h"
#include "util-time.h"
Functions
LogCustomFormatNode * LogCustomFormatNodeAlloc ()
Creates a custom format node.
LogCustomFormat * LogCustomFormatAlloc ()
Creates a custom format.
void LogCustomFormatNodeFree (LogCustomFormatNode *node)
Frees memory held by a custom format node.
void LogCustomFormatFree (LogCustomFormat *cf)
Frees memory held by a custom format.
int LogCustomFormatParse (LogCustomFormat *cf, const char *format)
Parses and saves format nodes for custom format.
void LogCustomFormatAddNode (LogCustomFormat *cf, LogCustomFormatNode *node)
Adds a node to custom format.
void LogCustomFormatWriteTimestamp (MemBuffer *buffer, const char *fmt, const struct timeval *ts)
Writes a timestamp with given format into a MemBuffer.
void LogCustomFormatRegister (void)
Detailed Description
Author
Paulo Pacheco fooin.nosp@m.ha@g.nosp@m.mail..nosp@m.com
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Ignacio Sanchez sanch.nosp@m.ezma.nosp@m.rtin..nosp@m.ji@g.nosp@m.mail..nosp@m.com
Common custom logging format
Definition in file log-cf-common.c.
Function Documentation
LogCustomFormatAddNode()
void LogCustomFormatAddNode (LogCustomFormat * cf, LogCustomFormatNode * node)
Adds a node to custom format.
Parameters
LogCustomFormat * cf - custom format
LogCustomFormatNode * node - node to add
Definition at line 184 of file log-cf-common.c.
References LogCustomFormat_::cf_n, LogCustomFormat_::cf_nodes, LogCustomFormatNode_::data, LOG_MAXN_NODES, LogCustomFormatNode_::maxlen, SC_WARN_LOG_CF_TOO_MANY_NODES, SCLogDebug, SCLogWarning, and LogCustomFormatNode_::type.
Referenced by LogCustomFormatParse().
LogCustomFormatAlloc()
LogCustomFormat * LogCustomFormatAlloc (void)
Creates a custom format.
Return values
LogCustomFormat * ptr if created
NULL if failed to allocate
Definition at line 53 of file log-cf-common.c.
References SC_ERR_MEM_ALLOC, SCCalloc, SCLogError, and unlikely.
Referenced by LogHttpLogInitCtx().
LogCustomFormatFree()
void LogCustomFormatFree (LogCustomFormat * cf)
Frees memory held by a custom format.
Parameters
LogCustomFormat * cf - format to relaease
Definition at line 79 of file log-cf-common.c.
References LogCustomFormat_::cf_n, LogCustomFormat_::cf_nodes, LogCustomFormatNodeFree(), and SCFree.
LogCustomFormatNodeAlloc()
LogCustomFormatNode * LogCustomFormatNodeAlloc (void)
Creates a custom format node.
Return values
LogCustomFormatNode * ptr if created
NULL if failed to allocate
Definition at line 38 of file log-cf-common.c.
References SC_ERR_MEM_ALLOC, SCCalloc, SCLogError, and unlikely.
Referenced by LogCustomFormatParse().
LogCustomFormatNodeFree()
void LogCustomFormatNodeFree (LogCustomFormatNode * node)
Frees memory held by a custom format node.
Parameters
LogCustomFormatNode * node - node to relaease
Definition at line 67 of file log-cf-common.c.
References SCFree.
Referenced by LogCustomFormatFree(), and LogCustomFormatParse().
LogCustomFormatParse()
int LogCustomFormatParse (LogCustomFormat * cf, const char * format)
Parses and saves format nodes for custom format.
Parameters
LogCustomFormat * cf - custom format to build
const char * format - string with format specification
Definition at line 95 of file log-cf-common.c.
References LogCustomFormat_::cf_n, LogCustomFormatNode_::data, LOG_CF_LITERAL, LOG_MAXN_NODES, LOG_NODE_MAXOUTPUTLEN, LOG_NODE_STRLEN, LogCustomFormatAddNode(), LogCustomFormatNodeAlloc(), LogCustomFormatNodeFree(), LogCustomFormatNode_::maxlen, strlcpy(), and LogCustomFormatNode_::type.
Referenced by LogHttpLogInitCtx().
LogCustomFormatRegister()
void LogCustomFormatRegister (void)
Definition at line 270 of file log-cf-common.c.
Referenced by OutputRegisterLoggers().
LogCustomFormatWriteTimestamp()
void LogCustomFormatWriteTimestamp (MemBuffer * buffer, const char * fmt, const struct timeval * ts)
Writes a timestamp with given format into a MemBuffer.
Parameters
MemBuffer * buffer - where to write
const char * fmt - format to be used write timestamp
const struct timeveal *ts - the timetstamp
Definition at line 210 of file log-cf-common.c.
References MemBuffer_::buffer, CreateFormattedTimeString(), MemBuffer_::offset, PrintRawUriBuf(), SCLocalTime(), MemBuffer_::size, TIMESTAMP_DEFAULT_FORMAT, and ts.