suricata: /Users/jlu/suricata/src/log-pcap.h File Reference
log-pcap.h File Reference
Macros
#define PCAP_OUTPUT_BUFFER_SIZE 65535
Functions
void PcapLogRegister (void)
void PcapLogProfileSetup (void)
char * PcapLogGetFilename (void)
Detailed Description
Author
William Metcalf Willi.nosp@m.am.M.nosp@m.etcal.nosp@m.f@gm.nosp@m.ail.c.nosp@m.om
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Pcap packet logging module.
Definition in file log-pcap.h.
Macro Definition Documentation
PCAP_OUTPUT_BUFFER_SIZE
#define PCAP_OUTPUT_BUFFER_SIZE 65535
Definition at line 31 of file log-pcap.h.
Function Documentation
PcapLogGetFilename()
char * PcapLogGetFilename (void)
Definition at line 1911 of file log-pcap.c.
References pcap_file_thread.
PcapLogProfileSetup()
void PcapLogProfileSetup (void)
Definition at line 2036 of file log-pcap.c.
References ConfGetNode(), and ConfNodeChildValueIsTrue().
PcapLogRegister()
void PcapLogRegister (void)
Definition at line 220 of file log-pcap.c.
References LOGGER_PCAP, MODULE_NAME, and OutputRegisterPacketModule().
Referenced by OutputRegisterLoggers().