suricata: /Users/jlu/suricata/src/log-tlslog.h File Reference
log-tlslog.h File Reference
Functions
void LogTlsLogRegister (void)
int TLSGetIPInformations (const Packet *p, char *srcip, size_t srcip_len, Port *sp, char *dstip, size_t dstip_len, Port *dp, int ipproto)
Detailed Description
Author
Roliers Jean-Paul popof.nosp@m..fpn.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Definition in file log-tlslog.h.
Function Documentation
LogTlsLogRegister()
void LogTlsLogRegister (void)
Definition at line 534 of file log-tlslog.c.
References LOGGER_TLS, MODULE_NAME, and OutputRegisterTxModuleWithProgress().
Referenced by OutputRegisterLoggers().
TLSGetIPInformations()
int TLSGetIPInformations (const Packet * p, char * srcip, size_t srcip_len, Port * sp, char * dstip, size_t dstip_len, Port * dp, int ipproto)
Definition at line 95 of file log-tlslog.c.
References Packet_::dp, GET_IPV4_DST_ADDR_PTR, GET_IPV4_SRC_ADDR_PTR, GET_IPV6_DST_ADDR, GET_IPV6_SRC_ADDR, PKT_IS_TOSERVER, PrintInet(), and Packet_::sp.