suricata: /Users/jlu/suricata/src/log-cf-common.h File Reference
log-cf-common.h File Reference
#include "suricata-common.h"
#include "util-buffer.h"
Data Structures
struct LogCustomFormatNode_
struct LogCustomFormat_
Macros
#define LOG_MAXN_NODES 64
#define LOG_NODE_STRLEN 256
#define LOG_NODE_MAXOUTPUTLEN 8192
#define TIMESTAMP_DEFAULT_FORMAT "%D-%H:%M:%S"
#define TIMESTAMP_DEFAULT_FORMAT_LEN 62
#define LOG_CF_NONE "-"
#define LOG_CF_LITERAL '%'
#define LOG_CF_TIMESTAMP 't'
#define LOG_CF_TIMESTAMP_U 'z'
#define LOG_CF_CLIENT_IP 'a'
#define LOG_CF_SERVER_IP 'A'
#define LOG_CF_CLIENT_PORT 'p'
#define LOG_CF_SERVER_PORT 'P'
#define LOG_CF_STAR_SEPARATOR "[**]"
#define LOG_CF_SPACE_SEPARATOR " "
#define LOG_CF_UNKNOWN_VALUE "-"
#define LOG_CF_WRITE_STAR_SEPATATOR(buffer) MemBufferWriteString(buffer, LOG_CF_STAR_SEPARATOR);
#define LOG_CF_WRITE_SPACE_SEPARATOR(buffer) MemBufferWriteString(buffer, LOG_CF_SPACE_SEPARATOR);
#define LOG_CF_WRITE_UNKNOWN_VALUE(buffer) MemBufferWriteString(buffer, LOG_CF_UNKNOWN_VALUE);
Typedefs
typedef struct LogCustomFormatNode_ LogCustomFormatNode
typedef struct LogCustomFormat_ LogCustomFormat
Functions
LogCustomFormatNode * LogCustomFormatNodeAlloc (void)
Creates a custom format node.
LogCustomFormat * LogCustomFormatAlloc (void)
Creates a custom format.
void LogCustomFormatNodeFree (LogCustomFormatNode *node)
Frees memory held by a custom format node.
void LogCustomFormatFree (LogCustomFormat *cf)
Frees memory held by a custom format.
void LogCustomFormatAddNode (LogCustomFormat *cf, LogCustomFormatNode *node)
Adds a node to custom format.
int LogCustomFormatParse (LogCustomFormat *cf, const char *format)
Parses and saves format nodes for custom format.
void LogCustomFormatWriteTimestamp (MemBuffer *buffer, const char *fmt, const struct timeval *ts)
Writes a timestamp with given format into a MemBuffer.
void LogCustomFormatRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Ignacio Sanchez sanch.nosp@m.ezma.nosp@m.rtin..nosp@m.ji@g.nosp@m.mail..nosp@m.com
Paulo Pacheco fooin.nosp@m.ha@g.nosp@m.mail..nosp@m.com
Common custom loggging format
Definition in file log-cf-common.h.
Macro Definition Documentation
LOG_CF_CLIENT_IP
#define LOG_CF_CLIENT_IP 'a'
Definition at line 43 of file log-cf-common.h.
LOG_CF_CLIENT_PORT
#define LOG_CF_CLIENT_PORT 'p'
Definition at line 45 of file log-cf-common.h.
LOG_CF_LITERAL
#define LOG_CF_LITERAL '%'
Definition at line 40 of file log-cf-common.h.
LOG_CF_NONE
#define LOG_CF_NONE "-"
Definition at line 39 of file log-cf-common.h.
LOG_CF_SERVER_IP
#define LOG_CF_SERVER_IP 'A'
Definition at line 44 of file log-cf-common.h.
LOG_CF_SERVER_PORT
#define LOG_CF_SERVER_PORT 'P'
Definition at line 46 of file log-cf-common.h.
LOG_CF_SPACE_SEPARATOR
#define LOG_CF_SPACE_SEPARATOR " "
Definition at line 50 of file log-cf-common.h.
LOG_CF_STAR_SEPARATOR
#define LOG_CF_STAR_SEPARATOR "[**]"
Definition at line 49 of file log-cf-common.h.
LOG_CF_TIMESTAMP
#define LOG_CF_TIMESTAMP 't'
Definition at line 41 of file log-cf-common.h.
LOG_CF_TIMESTAMP_U
#define LOG_CF_TIMESTAMP_U 'z'
Definition at line 42 of file log-cf-common.h.
LOG_CF_UNKNOWN_VALUE
#define LOG_CF_UNKNOWN_VALUE "-"
Definition at line 51 of file log-cf-common.h.
LOG_CF_WRITE_SPACE_SEPARATOR
#define LOG_CF_WRITE_SPACE_SEPARATOR (buffer) MemBufferWriteString(buffer, LOG_CF_SPACE_SEPARATOR);
Definition at line 56 of file log-cf-common.h.
LOG_CF_WRITE_STAR_SEPATATOR
#define LOG_CF_WRITE_STAR_SEPATATOR (buffer) MemBufferWriteString(buffer, LOG_CF_STAR_SEPARATOR);
Definition at line 53 of file log-cf-common.h.
LOG_CF_WRITE_UNKNOWN_VALUE
#define LOG_CF_WRITE_UNKNOWN_VALUE (buffer) MemBufferWriteString(buffer, LOG_CF_UNKNOWN_VALUE);
Definition at line 59 of file log-cf-common.h.
LOG_MAXN_NODES
#define LOG_MAXN_NODES 64
Definition at line 31 of file log-cf-common.h.
LOG_NODE_MAXOUTPUTLEN
#define LOG_NODE_MAXOUTPUTLEN 8192
Definition at line 33 of file log-cf-common.h.
LOG_NODE_STRLEN
#define LOG_NODE_STRLEN 256
Definition at line 32 of file log-cf-common.h.
TIMESTAMP_DEFAULT_FORMAT
#define TIMESTAMP_DEFAULT_FORMAT "%D-%H:%M:%S"
Definition at line 35 of file log-cf-common.h.
TIMESTAMP_DEFAULT_FORMAT_LEN
#define TIMESTAMP_DEFAULT_FORMAT_LEN 62
Definition at line 36 of file log-cf-common.h.
Typedef Documentation
LogCustomFormat
typedef struct LogCustomFormat_ LogCustomFormat
LogCustomFormatNode
typedef struct LogCustomFormatNode_ LogCustomFormatNode
Function Documentation
LogCustomFormatAddNode()
void LogCustomFormatAddNode (LogCustomFormat * cf, LogCustomFormatNode * node)
Adds a node to custom format.
Parameters
LogCustomFormat * cf - custom format
LogCustomFormatNode * node - node to add
Definition at line 184 of file log-cf-common.c.
References LogCustomFormat_::cf_n, LogCustomFormat_::cf_nodes, LogCustomFormatNode_::data, LOG_MAXN_NODES, LogCustomFormatNode_::maxlen, SC_WARN_LOG_CF_TOO_MANY_NODES, SCLogDebug, SCLogWarning, and LogCustomFormatNode_::type.
Referenced by LogCustomFormatParse().
LogCustomFormatAlloc()
LogCustomFormat * LogCustomFormatAlloc (void)
Creates a custom format.
Return values
LogCustomFormat * ptr if created
NULL if failed to allocate
Definition at line 53 of file log-cf-common.c.
References SC_ERR_MEM_ALLOC, SCCalloc, SCLogError, and unlikely.
Referenced by LogHttpLogInitCtx().
LogCustomFormatFree()
void LogCustomFormatFree (LogCustomFormat * cf)
Frees memory held by a custom format.
Parameters
LogCustomFormat * cf - format to relaease
Definition at line 79 of file log-cf-common.c.
References LogCustomFormat_::cf_n, LogCustomFormat_::cf_nodes, LogCustomFormatNodeFree(), and SCFree.
LogCustomFormatNodeAlloc()
LogCustomFormatNode * LogCustomFormatNodeAlloc (void)
Creates a custom format node.
Return values
LogCustomFormatNode * ptr if created
NULL if failed to allocate
Definition at line 38 of file log-cf-common.c.
References SC_ERR_MEM_ALLOC, SCCalloc, SCLogError, and unlikely.
Referenced by LogCustomFormatParse().
LogCustomFormatNodeFree()
void LogCustomFormatNodeFree (LogCustomFormatNode * node)
Frees memory held by a custom format node.
Parameters
LogCustomFormatNode * node - node to relaease
Definition at line 67 of file log-cf-common.c.
References SCFree.
Referenced by LogCustomFormatFree(), and LogCustomFormatParse().
LogCustomFormatParse()
int LogCustomFormatParse (LogCustomFormat * cf, const char * format)
Parses and saves format nodes for custom format.
Parameters
LogCustomFormat * cf - custom format to build
const char * format - string with format specification
Definition at line 95 of file log-cf-common.c.
References LogCustomFormat_::cf_n, LogCustomFormatNode_::data, LOG_CF_LITERAL, LOG_MAXN_NODES, LOG_NODE_MAXOUTPUTLEN, LOG_NODE_STRLEN, LogCustomFormatAddNode(), LogCustomFormatNodeAlloc(), LogCustomFormatNodeFree(), LogCustomFormatNode_::maxlen, strlcpy(), and LogCustomFormatNode_::type.
Referenced by LogHttpLogInitCtx().
LogCustomFormatRegister()
void LogCustomFormatRegister (void)
Definition at line 270 of file log-cf-common.c.
Referenced by OutputRegisterLoggers().
LogCustomFormatWriteTimestamp()
void LogCustomFormatWriteTimestamp (MemBuffer * buffer, const char * fmt, const struct timeval * ts)
Writes a timestamp with given format into a MemBuffer.
Parameters
MemBuffer * buffer - where to write
const char * fmt - format to be used write timestamp
const struct timeveal *ts - the timetstamp
Definition at line 210 of file log-cf-common.c.
References MemBuffer_::buffer, CreateFormattedTimeString(), MemBuffer_::offset, PrintRawUriBuf(), SCLocalTime(), MemBuffer_::size, TIMESTAMP_DEFAULT_FORMAT, and ts.