suricata: /Users/jlu/suricata/src/log-tcp-data.c File Reference
log-tcp-data.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "pkt-var.h"
#include "conf.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "util-print.h"
#include "util-unittest.h"
#include "util-debug.h"
#include "output.h"
#include "log-tcp-data.h"
#include "app-layer-htp.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "util-privs.h"
#include "util-buffer.h"
#include "util-logopenfile.h"
#include "util-time.h"
Data Structures
struct LogTcpDataFileCtx_
struct LogTcpDataLogThread_
Macros
#define DEFAULT_LOG_FILENAME "tcp-data.log"
#define MODULE_NAME "LogTcpDataLog"
#define OUTPUT_BUFFER_SIZE 65535
Typedefs
typedef struct LogTcpDataFileCtx_ LogTcpDataFileCtx
typedef struct LogTcpDataLogThread_ LogTcpDataLogThread
Functions
TmEcode LogTcpDataLogThreadInit (ThreadVars *, const void *, void **)
TmEcode LogTcpDataLogThreadDeinit (ThreadVars *, void *)
int LogTcpDataLogger (ThreadVars *tv, void *thread_data, const Flow *f, const uint8_t *data, uint32_t data_len, uint64_t tx_id, uint8_t flags)
void LogTcpDataLogRegister (void)
OutputInitResult LogTcpDataLogInitCtx (ConfNode *conf)
Create a new http log LogFileCtx.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file log-tcp-data.c.
Macro Definition Documentation
DEFAULT_LOG_FILENAME
#define DEFAULT_LOG_FILENAME "tcp-data.log"
Definition at line 49 of file log-tcp-data.c.
MODULE_NAME
#define MODULE_NAME "LogTcpDataLog"
Definition at line 51 of file log-tcp-data.c.
OUTPUT_BUFFER_SIZE
#define OUTPUT_BUFFER_SIZE 65535
Definition at line 53 of file log-tcp-data.c.
Typedef Documentation
LogTcpDataFileCtx
typedef struct LogTcpDataFileCtx_ LogTcpDataFileCtx
LogTcpDataLogThread
typedef struct LogTcpDataLogThread_ LogTcpDataLogThread
Function Documentation
LogTcpDataLogger()
int LogTcpDataLogger (ThreadVars * tv, void * thread_data, const Flow * f, const uint8_t * data, uint32_t data_len, uint64_t tx_id, uint8_t flags)
Definition at line 166 of file log-tcp-data.c.
References LogTcpDataFileCtx_::dir, SCEnter, and LogTcpDataLogThread_::tcpdatalog_ctx.
Referenced by LogTcpDataLogRegister().
LogTcpDataLogInitCtx()
OutputInitResult LogTcpDataLogInitCtx (ConfNode * conf)
Create a new http log LogFileCtx.
Parameters
conf Pointer to ConfNode containing this loggers configuration.
Returns
NULL if failure, LogFileCtx* to the file_ctx if succesful
Definition at line 227 of file log-tcp-data.c.
References ConfigGetLogDirectory(), ConfNodeLookupChildValue(), OutputCtx_::data, DEFAULT_LOG_FILENAME, OutputCtx_::DeInit, LogTcpDataFileCtx_::dir, LogTcpDataFileCtx_::file, LogTcpDataFileCtx_::file_ctx, LogTcpDataFileCtx_::log_dir, LogFileFreeCtx(), LogFileNewCtx(), ConfNode_::name, SC_ERR_TCPDATA_LOG_GENERIC, SCCalloc, SCConfLogOpenGeneric(), SCFree, SCLogError, SCLogInfo, SCMalloc, SCMkDir, STREAMING_HTTP_BODIES, STREAMING_TCP_DATA, strlcpy(), LogTcpDataFileCtx_::type, and unlikely.
Referenced by LogTcpDataLogRegister().
LogTcpDataLogRegister()
void LogTcpDataLogRegister (void)
Definition at line 61 of file log-tcp-data.c.
References LOGGER_TCP_DATA, LogTcpDataLogger(), LogTcpDataLogInitCtx(), LogTcpDataLogThreadDeinit(), LogTcpDataLogThreadInit(), MODULE_NAME, OutputRegisterStreamingModule(), STREAMING_HTTP_BODIES, and STREAMING_TCP_DATA.
Referenced by OutputRegisterLoggers().
LogTcpDataLogThreadDeinit()
TmEcode LogTcpDataLogThreadDeinit (ThreadVars * t, void * data)
Definition at line 208 of file log-tcp-data.c.
References LogTcpDataLogThread_::buffer, MemBufferFree(), SCFree, and TM_ECODE_OK.
Referenced by LogTcpDataLogRegister().
LogTcpDataLogThreadInit()
TmEcode LogTcpDataLogThreadInit (ThreadVars * t, const void * initdata, void ** data)
Definition at line 181 of file log-tcp-data.c.
References LogTcpDataLogThread_::buffer, MemBufferCreateNew(), OUTPUT_BUFFER_SIZE, SCFree, SCLogDebug, SCMalloc, LogTcpDataLogThread_::tcpdatalog_ctx, TM_ECODE_FAILED, TM_ECODE_OK, and unlikely.
Referenced by LogTcpDataLogRegister().