suricata: /Users/jlu/suricata/src/log-tcp-data.h File Reference
log-tcp-data.h File Reference
Functions
void LogTcpDataLogRegister (void)
OutputInitResult LogTcpDataLogInitCtx (ConfNode *)
Create a new http log LogFileCtx.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file log-tcp-data.h.
Function Documentation
LogTcpDataLogInitCtx()
OutputInitResult LogTcpDataLogInitCtx (ConfNode * conf)
Create a new http log LogFileCtx.
Parameters
conf Pointer to ConfNode containing this loggers configuration.
Returns
NULL if failure, LogFileCtx* to the file_ctx if succesful
Definition at line 227 of file log-tcp-data.c.
References ConfigGetLogDirectory(), ConfNodeLookupChildValue(), OutputCtx_::data, DEFAULT_LOG_FILENAME, OutputCtx_::DeInit, LogTcpDataFileCtx_::dir, LogTcpDataFileCtx_::file, LogTcpDataFileCtx_::file_ctx, LogTcpDataFileCtx_::log_dir, LogFileFreeCtx(), LogFileNewCtx(), ConfNode_::name, SC_ERR_TCPDATA_LOG_GENERIC, SCCalloc, SCConfLogOpenGeneric(), SCFree, SCLogError, SCLogInfo, SCMalloc, SCMkDir, STREAMING_HTTP_BODIES, STREAMING_TCP_DATA, strlcpy(), LogTcpDataFileCtx_::type, and unlikely.
Referenced by LogTcpDataLogRegister().
LogTcpDataLogRegister()
void LogTcpDataLogRegister (void)
Definition at line 61 of file log-tcp-data.c.
References LOGGER_TCP_DATA, LogTcpDataLogger(), LogTcpDataLogInitCtx(), LogTcpDataLogThreadDeinit(), LogTcpDataLogThreadInit(), MODULE_NAME, OutputRegisterStreamingModule(), STREAMING_HTTP_BODIES, and STREAMING_TCP_DATA.
Referenced by OutputRegisterLoggers().