suricata: /Users/jlu/suricata/src/tests/fuzz/onefile.c File Reference
onefile.c File Reference
#include "suricata-common.h"
Functions
int LLVMFuzzerTestOneInput (const uint8_t *Data, size_t Size)
int main (int argc, char **argv)
Function Documentation
LLVMFuzzerTestOneInput()
int LLVMFuzzerTestOneInput (const uint8_t * Data, size_t Size)
Definition at line 66 of file fuzz_applayerparserparse.c.
References alp_tctx, Flow_::alparser, alpd_tctx, Flow_::alproto, ALPROTO_FAILED, ALPROTO_MAX, ALPROTO_UNKNOWN, APP_LAYER_PARSER_EOF_TC, APP_LAYER_PARSER_EOF_TS, AppLayerParserParse(), AppLayerParserRegisterProtocolParsers(), AppLayerParserSetup(), AppLayerParserStateIssetFlag(), AppLayerParserThreadCtxAlloc(), AppLayerParserTransactionsCleanup(), AppLayerProtoDetectGetCtxThread(), AppLayerProtoDetectGetProto(), AppLayerProtoDetectReset(), AppLayerProtoDetectSetup(), AppProtoToString(), configNoChecksum, ConfigSetLogDirectory(), ConfYamlLoadString(), de_ctx, Flow_::dp, Flow_::dst, flags, Flow_::flags, FLOW_IPV4, FlowAlloc(), FlowChangeProto(), FlowFree(), FlowGetProtoMapping(), FLOWLOCK_UNLOCK, FLOWLOCK_WRLOCK, forceLayer, GlobalsInitPreConfig(), HEADER_LEN, InitGlobal(), MpmTableSetup(), PostConfLoadedSetup(), Flow_::proto, PROTO_DETECT_MAX_LEN, Flow_::protoctx, Flow_::protomap, run_mode, RUNMODE_PCAP_FILE, RUNMODE_UNITTEST, SCClassConfInit(), SCReferenceConfInit(), separator, setenv(), SigTableSetup(), Flow_::sp, SpmTableSetup(), Flow_::src, surifuzz, and TestHelperBuildFlow().
main()
int main (int argc, char ** argv)
Definition at line 45 of file onefile.c.