suricata: /Users/jlu/suricata/src/output-json-netflow.c File Reference
output-json-netflow.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "pkt-var.h"
#include "conf.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "util-print.h"
#include "util-unittest.h"
#include "util-debug.h"
#include "output.h"
#include "util-privs.h"
#include "util-buffer.h"
#include "util-device.h"
#include "util-proto-name.h"
#include "util-logopenfile.h"
#include "util-time.h"
#include "output-json.h"
#include "output-json-netflow.h"
#include "stream-tcp-private.h"
Functions
void JsonNetFlowLogRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Implements Unidirectiontal NetFlow JSON logging portion of the engine.
Definition in file output-json-netflow.c.
Function Documentation
JsonNetFlowLogRegister()
void JsonNetFlowLogRegister (void)
Definition at line 294 of file output-json-netflow.c.
References LOGGER_JSON_NETFLOW, OutputJsonLogInitSub(), and OutputRegisterFlowSubModule().
Referenced by OutputRegisterLoggers().