suricata: /Users/jlu/suricata/src/output-json-http.h File Reference
output-json-http.h File Reference
Functions
void JsonHttpLogRegister (void)
bool EveHttpAddMetadata (const Flow *f, uint64_t tx_id, JsonBuilder *js)
void EveHttpLogJSONBodyPrintable (JsonBuilder *js, Flow *f, uint64_t tx_id)
void EveHttpLogJSONBodyBase64 (JsonBuilder *js, Flow *f, uint64_t tx_id)
Detailed Description
Author
Tom DeCanio td@np.nosp@m.ulse.nosp@m.tech..nosp@m.com
Definition in file output-json-http.h.
Function Documentation
EveHttpAddMetadata()
bool EveHttpAddMetadata (const Flow * f, uint64_t tx_id, JsonBuilder * js)
Definition at line 515 of file output-json-http.c.
References ALPROTO_HTTP1, AppLayerParserGetTx(), and FlowGetAppState().
Referenced by JsonBuildFileInfoRecord().
EveHttpLogJSONBodyBase64()
void EveHttpLogJSONBodyBase64 (JsonBuilder * js, Flow * f, uint64_t tx_id)
Definition at line 435 of file output-json-http.c.
References ALPROTO_HTTP1, AppLayerParserGetTx(), and FlowGetAppState().
EveHttpLogJSONBodyPrintable()
void EveHttpLogJSONBodyPrintable (JsonBuilder * js, Flow * f, uint64_t tx_id)
Definition at line 404 of file output-json-http.c.
References ALPROTO_HTTP1, AppLayerParserGetTx(), and FlowGetAppState().
JsonHttpLogRegister()
void JsonHttpLogRegister (void)
Definition at line 669 of file output-json-http.c.
References LOGGER_JSON_HTTP, and OutputRegisterTxSubModule().
Referenced by OutputRegisterLoggers().