suricata: /Users/jlu/suricata/src/output-json-ike.c File Reference
output-json-ike.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "pkt-var.h"
#include "conf.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "util-unittest.h"
#include "util-buffer.h"
#include "util-debug.h"
#include "util-byte.h"
#include "output.h"
#include "output-json.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "app-layer-ike.h"
#include "output-json-ike.h"
#include "rust.h"
Data Structures
struct LogIKEFileCtx_
struct LogIKELogThread_
Macros
#define LOG_IKE_DEFAULT 0
#define LOG_IKE_EXTENDED (1 << 0)
Typedefs
typedef struct LogIKEFileCtx_ LogIKEFileCtx
typedef struct LogIKELogThread_ LogIKELogThread
Functions
bool EveIKEAddMetadata (const Flow *f, uint64_t tx_id, JsonBuilder *js)
void JsonIKELogRegister (void)
Detailed Description
Author
Pierre Chifflier chiff.nosp@m.lier.nosp@m.@wzdf.nosp@m.tpd..nosp@m.net
Frank Honza frank.nosp@m..hon.nosp@m.za@dc.nosp@m.so.d.nosp@m.e
Implement JSON/eve logging app-layer IKE.
Definition in file output-json-ike.c.
Macro Definition Documentation
LOG_IKE_DEFAULT
#define LOG_IKE_DEFAULT 0
Definition at line 52 of file output-json-ike.c.
LOG_IKE_EXTENDED
#define LOG_IKE_EXTENDED (1 << 0)
Definition at line 53 of file output-json-ike.c.
Typedef Documentation
LogIKEFileCtx
typedef struct LogIKEFileCtx_ LogIKEFileCtx
LogIKELogThread
typedef struct LogIKELogThread_ LogIKELogThread
Function Documentation
EveIKEAddMetadata()
bool EveIKEAddMetadata (const Flow * f, uint64_t tx_id, JsonBuilder * js)
Definition at line 65 of file output-json-ike.c.
References ALPROTO_IKE, AppLayerParserGetTx(), FlowGetAppState(), LOG_IKE_EXTENDED, and Flow_::proto.
JsonIKELogRegister()
void JsonIKELogRegister (void)
Definition at line 182 of file output-json-ike.c.
References LOGGER_JSON_IKE, and OutputRegisterTxSubModule().
Referenced by OutputRegisterLoggers().