suricata: /Users/jlu/suricata/src/output-json-tls.h File Reference
output-json-tls.h File Reference
#include "app-layer-ssl.h"
Functions
void JsonTlsLogRegister (void)
void JsonTlsLogJSONBasic (JsonBuilder *js, SSLState *ssl_state)
void JsonTlsLogJSONExtended (JsonBuilder *js, SSLState *ssl_state)
Detailed Description
Author
Tom DeCanio td@np.nosp@m.ulse.nosp@m.tech..nosp@m.com
Definition in file output-json-tls.h.
Function Documentation
JsonTlsLogJSONBasic()
void JsonTlsLogJSONBasic (JsonBuilder * js, SSLState * ssl_state)
Definition at line 331 of file output-json-tls.c.
Referenced by JsonTlsLogJSONExtended().
JsonTlsLogJSONExtended()
void JsonTlsLogJSONExtended (JsonBuilder * js, SSLState * ssl_state)
Definition at line 409 of file output-json-tls.c.
References JsonTlsLogJSONBasic().
JsonTlsLogRegister()
void JsonTlsLogRegister (void)
Definition at line 666 of file output-json-tls.c.
References LOGGER_JSON_TLS, and OutputRegisterTxSubModuleWithProgress().
Referenced by OutputRegisterLoggers().