suricata: /Users/jlu/suricata/src/output-json-smb.c File Reference
output-json-smb.c File Reference
#include "suricata-common.h"
#include "pkt-var.h"
#include "conf.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "util-unittest.h"
#include "util-buffer.h"
#include "util-debug.h"
#include "util-byte.h"
#include "output.h"
#include "output-json.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "output-json-smb.h"
#include "rust.h"
Functions
bool EveSMBAddMetadata (const Flow *f, uint64_t tx_id, JsonBuilder *jb)
void JsonSMBLogRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Implement JSON/eve logging app-layer SMB.
Definition in file output-json-smb.c.
Function Documentation
EveSMBAddMetadata()
bool EveSMBAddMetadata (const Flow * f, uint64_t tx_id, JsonBuilder * jb)
Definition at line 49 of file output-json-smb.c.
References ALPROTO_SMB, AppLayerParserGetTx(), FlowGetAppState(), and Flow_::proto.
Referenced by JsonBuildFileInfoRecord().
JsonSMBLogRegister()
void JsonSMBLogRegister (void)
Definition at line 94 of file output-json-smb.c.
References LOGGER_JSON_SMB, and OutputRegisterTxSubModule().
Referenced by OutputRegisterLoggers().