suricata: /Users/jlu/suricata/src/output-json-template.c File Reference
output-json-template.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "pkt-var.h"
#include "conf.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "util-unittest.h"
#include "util-buffer.h"
#include "util-debug.h"
#include "util-byte.h"
#include "output.h"
#include "output-json.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "app-layer-template.h"
#include "output-json-template.h"
Data Structures
struct LogTemplateFileCtx_
struct LogTemplateLogThread_
Typedefs
typedef struct LogTemplateFileCtx_ LogTemplateFileCtx
typedef struct LogTemplateLogThread_ LogTemplateLogThread
Functions
void JsonTemplateLogRegister (void)
Detailed Description
Author
FirstName LastName <yourname@domain>
Implement JSON/eve logging app-layer Template.
Definition in file output-json-template.c.
Typedef Documentation
LogTemplateFileCtx
typedef struct LogTemplateFileCtx_ LogTemplateFileCtx
LogTemplateLogThread
typedef struct LogTemplateLogThread_ LogTemplateLogThread
Function Documentation
JsonTemplateLogRegister()
void JsonTemplateLogRegister (void)
Definition at line 175 of file output-json-template.c.
References ConfGetNode(), LOGGER_JSON_TEMPLATE, and OutputRegisterTxSubModule().
Referenced by OutputRegisterLoggers().