suricata: /Users/jlu/suricata/src/output-json-http2.c File Reference
output-json-http2.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "pkt-var.h"
#include "conf.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "util-print.h"
#include "util-unittest.h"
#include "util-debug.h"
#include "app-layer-parser.h"
#include "output.h"
#include "app-layer-http2.h"
#include "app-layer.h"
#include "util-privs.h"
#include "util-buffer.h"
#include "util-logopenfile.h"
#include "output-json.h"
#include "output-json-http2.h"
#include "rust.h"
Data Structures
struct OutputHttp2Ctx_
struct JsonHttp2LogThread_
Macros
#define MODULE_NAME "LogHttp2Log"
Typedefs
typedef struct OutputHttp2Ctx_ OutputHttp2Ctx
typedef struct JsonHttp2LogThread_ JsonHttp2LogThread
Functions
bool EveHTTP2AddMetadata (const Flow *f, uint64_t tx_id, JsonBuilder *jb)
void JsonHttp2LogRegister (void)
Detailed Description
Author
Philippe Antoine p.ant.nosp@m.oine.nosp@m.@cate.nosp@m.nacy.nosp@m.ber.f.nosp@m.r
Implements HTTP2 JSON logging portion of the engine.
Definition in file output-json-http2.c.
Macro Definition Documentation
MODULE_NAME
#define MODULE_NAME "LogHttp2Log"
Definition at line 52 of file output-json-http2.c.
Typedef Documentation
JsonHttp2LogThread
typedef struct JsonHttp2LogThread_ JsonHttp2LogThread
OutputHttp2Ctx
typedef struct OutputHttp2Ctx_ OutputHttp2Ctx
Function Documentation
EveHTTP2AddMetadata()
bool EveHTTP2AddMetadata (const Flow * f, uint64_t tx_id, JsonBuilder * jb)
Definition at line 65 of file output-json-http2.c.
References ALPROTO_HTTP2, AppLayerParserGetTx(), FlowGetAppState(), and Flow_::proto.
Referenced by JsonBuildFileInfoRecord().
JsonHttp2LogRegister()
void JsonHttp2LogRegister (void)
Definition at line 178 of file output-json-http2.c.
References LOGGER_JSON_HTTP2, MODULE_NAME, and OutputRegisterTxSubModuleWithProgress().
Referenced by OutputRegisterLoggers().