suricata: /Users/jlu/suricata/src/output.h File Reference
output.h File Reference
#include "output-packet.h"
#include "output-tx.h"
#include "output-file.h"
#include "output-filedata.h"
#include "output-flow.h"
#include "output-streaming.h"
#include "output-stats.h"
Data Structures
struct OutputLoggerThreadStore_
struct OutputInitResult_
struct OutputModule_
Macros
#define DEFAULT_LOG_MODE_APPEND "yes"
#define DEFAULT_LOG_FILETYPE "regular"
Typedefs
typedef struct OutputLoggerThreadStore_ OutputLoggerThreadStore
typedef struct OutputInitResult_ OutputInitResult
typedef OutputInitResult(* OutputInitFunc) (ConfNode *)
typedef OutputInitResult(* OutputInitSubFunc) (ConfNode *, OutputCtx *)
typedef TmEcode(* OutputLogFunc) (ThreadVars *, Packet *, void *)
typedef uint32_t(* OutputGetActiveCountFunc) (void)
typedef struct OutputModule_ OutputModule
Functions
typedef TAILQ_HEAD (OutputModuleList_, OutputModule_) OutputModuleList
void OutputRegisterModule (const char *, const char *, OutputInitFunc)
void OutputRegisterPacketModule (LoggerId id, const char *name, const char *conf_name, OutputInitFunc InitFunc, PacketLogger LogFunc, PacketLogCondition ConditionFunc, ThreadInitFunc, ThreadDeinitFunc, ThreadExitPrintStatsFunc)
Register a packet output module.
void OutputRegisterPacketSubModule (LoggerId id, const char *parent_name, const char *name, const char *conf_name, OutputInitSubFunc InitFunc, PacketLogger LogFunc, PacketLogCondition ConditionFunc, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Register a packet output sub-module.
void OutputRegisterTxModule (LoggerId id, const char *name, const char *conf_name, OutputInitFunc InitFunc, AppProto alproto, TxLogger TxLogFunc, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Register a tx output module.
void OutputRegisterTxSubModule (LoggerId id, const char *parent_name, const char *name, const char *conf_name, OutputInitSubFunc InitFunc, AppProto alproto, TxLogger TxLogFunc, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
void OutputRegisterTxModuleWithCondition (LoggerId id, const char *name, const char *conf_name, OutputInitFunc InitFunc, AppProto alproto, TxLogger TxLogFunc, TxLoggerCondition TxLogCondition, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Register a tx output module with condition.
void OutputRegisterTxSubModuleWithCondition (LoggerId id, const char *parent_name, const char *name, const char *conf_name, OutputInitSubFunc InitFunc, AppProto alproto, TxLogger TxLogFunc, TxLoggerCondition TxLogCondition, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
void OutputRegisterTxModuleWithProgress (LoggerId id, const char *name, const char *conf_name, OutputInitFunc InitFunc, AppProto alproto, TxLogger TxLogFunc, int tc_log_progress, int ts_log_progress, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Register a tx output module with progress.
void OutputRegisterTxSubModuleWithProgress (LoggerId id, const char *parent_name, const char *name, const char *conf_name, OutputInitSubFunc InitFunc, AppProto alproto, TxLogger TxLogFunc, int tc_log_progress, int ts_log_progress, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
void OutputRegisterFileModule (LoggerId id, const char *name, const char *conf_name, OutputInitFunc InitFunc, FileLogger FileLogFunc, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Register a file output module.
void OutputRegisterFileSubModule (LoggerId id, const char *parent_name, const char *name, const char *conf_name, OutputInitSubFunc InitFunc, FileLogger FileLogFunc, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Register a file output sub-module.
void OutputRegisterFiledataModule (LoggerId id, const char *name, const char *conf_name, OutputInitFunc InitFunc, FiledataLogger FiledataLogFunc, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Register a file data output module.
void OutputRegisterFiledataSubModule (LoggerId, const char *parent_name, const char *name, const char *conf_name, OutputInitSubFunc InitFunc, FiledataLogger FiledataLogFunc, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Register a file data output sub-module.
void OutputRegisterFlowSubModule (LoggerId id, const char *parent_name, const char *name, const char *conf_name, OutputInitSubFunc InitFunc, FlowLogger FlowLogFunc, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Register a flow output sub-module.
void OutputRegisterStreamingModule (LoggerId id, const char *name, const char *conf_name, OutputInitFunc InitFunc, StreamingLogger StreamingLogFunc, enum OutputStreamingType stream_type, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Register a streaming data output module.
void OutputRegisterStreamingSubModule (LoggerId id, const char *parent_name, const char *name, const char *conf_name, OutputInitSubFunc InitFunc, StreamingLogger StreamingLogFunc, enum OutputStreamingType stream_type, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Register a streaming data output sub-module.
void OutputRegisterStatsModule (LoggerId id, const char *name, const char *conf_name, OutputInitFunc InitFunc, StatsLogger StatsLogFunc, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Register a stats data output module.
void OutputRegisterStatsSubModule (LoggerId id, const char *parent_name, const char *name, const char *conf_name, OutputInitSubFunc InitFunc, StatsLogger StatsLogFunc, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Register a stats data output sub-module.
OutputModule * OutputGetModuleByConfName (const char *name)
Get an output module by name.
void OutputDeregisterAll (void)
Deregister all modules. Useful for a memory clean exit.
int OutputDropLoggerEnable (void)
void OutputDropLoggerDisable (void)
void OutputRegisterFileRotationFlag (int *flag)
Register a flag for file rotation notification.
void OutputUnregisterFileRotationFlag (int *flag)
Unregister a file rotation flag.
void OutputNotifyFileRotation (void)
Notifies all registered file rotation notification flags.
void OutputRegisterRootLogger (ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats, OutputLogFunc LogFunc, OutputGetActiveCountFunc ActiveCntFunc)
void TmModuleLoggerRegister (void)
TmEcode OutputLoggerLog (ThreadVars *, Packet *, void *)
TmEcode OutputLoggerThreadInit (ThreadVars *, const void *, void **)
TmEcode OutputLoggerThreadDeinit (ThreadVars *, void *)
void OutputLoggerExitPrintStats (ThreadVars *, void *)
void OutputSetupActiveLoggers (void)
void OutputClearActiveLoggers (void)
Variables
OutputModuleList output_modules
Detailed Description
Author
Endace Technology Limited, Jason Ish jason.nosp@m..ish.nosp@m.@enda.nosp@m.ce.c.nosp@m.om
Definition in file output.h.
Macro Definition Documentation
DEFAULT_LOG_FILETYPE
#define DEFAULT_LOG_FILETYPE "regular"
Definition at line 28 of file output.h.
DEFAULT_LOG_MODE_APPEND
#define DEFAULT_LOG_MODE_APPEND "yes"
Definition at line 27 of file output.h.
Typedef Documentation
OutputGetActiveCountFunc
typedef uint32_t(* OutputGetActiveCountFunc) (void)
Definition at line 52 of file output.h.
OutputInitFunc
typedef OutputInitResult(* OutputInitFunc) (ConfNode *)
Definition at line 49 of file output.h.
OutputInitResult
typedef struct OutputInitResult_ OutputInitResult
OutputInitSubFunc
typedef OutputInitResult(* OutputInitSubFunc) (ConfNode *, OutputCtx *)
Definition at line 50 of file output.h.
OutputLogFunc
typedef TmEcode(* OutputLogFunc) (ThreadVars *, Packet *, void *)
Definition at line 51 of file output.h.
OutputLoggerThreadStore
typedef struct OutputLoggerThreadStore_ OutputLoggerThreadStore
OutputModule
typedef struct OutputModule_ OutputModule
Function Documentation
OutputClearActiveLoggers()
void OutputClearActiveLoggers (void)
Definition at line 1011 of file output.c.
References SCFree, TAILQ_FIRST, and TAILQ_REMOVE.
OutputDeregisterAll()
void OutputDeregisterAll (void)
Deregister all modules. Useful for a memory clean exit.
Definition at line 801 of file output.c.
References output_modules, SCFree, TAILQ_FIRST, and TAILQ_REMOVE.
OutputDropLoggerDisable()
void OutputDropLoggerDisable (void)
Definition at line 821 of file output.c.
OutputDropLoggerEnable()
int OutputDropLoggerEnable (void)
Definition at line 813 of file output.c.
OutputGetModuleByConfName()
OutputModule * OutputGetModuleByConfName (const char * conf_name)
Get an output module by name.
Return values
The OutputModule with the given name or NULL if no output module with the given name is registered.
Definition at line 786 of file output.c.
References OutputModule_::conf_name, output_modules, and TAILQ_FOREACH.
OutputLoggerExitPrintStats()
void OutputLoggerExitPrintStats (ThreadVars * tv, void * thread_data)
Definition at line 951 of file output.c.
OutputLoggerLog()
TmEcode OutputLoggerLog (ThreadVars * tv, Packet * p, void * thread_data)
Definition at line 879 of file output.c.
OutputLoggerThreadDeinit()
TmEcode OutputLoggerThreadDeinit (ThreadVars * tv, void * thread_data)
Definition at line 925 of file output.c.
References TM_ECODE_FAILED.
OutputLoggerThreadInit()
TmEcode OutputLoggerThreadInit (ThreadVars * tv, const void * initdata, void ** data)
Definition at line 894 of file output.c.
OutputNotifyFileRotation()
void OutputNotifyFileRotation (void)
Notifies all registered file rotation notification flags.
Definition at line 872 of file output.c.
References OutputFileRolloverFlag, and TAILQ_FOREACH.
OutputRegisterFiledataModule()
void OutputRegisterFiledataModule (LoggerId id, const char * name, const char * conf_name, OutputInitFunc InitFunc, FiledataLogger FiledataLogFunc, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Register a file data output module.
This function will register an output module so it can be configured with the configuration file.
Return values
Returns 0 on success, -1 on failure.
Definition at line 509 of file output.c.
References OutputModule_::conf_name, FatalError, OutputModule_::FiledataLogFunc, OutputModule_::InitFunc, OutputModule_::logger_id, OutputModule_::name, output_modules, SC_ERR_FATAL, SCCalloc, SCLogDebug, TAILQ_INSERT_TAIL, OutputModule_::ThreadDeinit, OutputModule_::ThreadExitPrintStats, OutputModule_::ThreadInit, and unlikely.
Referenced by OutputFilestoreRegister().
OutputRegisterFiledataSubModule()
void OutputRegisterFiledataSubModule (LoggerId id, const char * parent_name, const char * name, const char * conf_name, OutputInitSubFunc InitFunc, FiledataLogger FiledataLogFunc, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Register a file data output sub-module.
This function will register an output module so it can be configured with the configuration file.
Return values
Returns 0 on success, -1 on failure.
Definition at line 548 of file output.c.
References OutputModule_::conf_name, FatalError, OutputModule_::FiledataLogFunc, OutputModule_::InitSubFunc, OutputModule_::logger_id, OutputModule_::name, output_modules, OutputModule_::parent_name, SC_ERR_FATAL, SCCalloc, SCLogDebug, TAILQ_INSERT_TAIL, OutputModule_::ThreadDeinit, OutputModule_::ThreadExitPrintStats, OutputModule_::ThreadInit, and unlikely.
OutputRegisterFileModule()
void OutputRegisterFileModule (LoggerId id, const char * name, const char * conf_name, OutputInitFunc InitFunc, FileLogger FileLogFunc, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Register a file output module.
This function will register an output module so it can be configured with the configuration file.
Return values
Returns 0 on success, -1 on failure.
Definition at line 431 of file output.c.
References OutputModule_::conf_name, FatalError, OutputModule_::FileLogFunc, OutputModule_::InitFunc, OutputModule_::logger_id, OutputModule_::name, output_modules, SC_ERR_FATAL, SCCalloc, SCLogDebug, TAILQ_INSERT_TAIL, OutputModule_::ThreadDeinit, OutputModule_::ThreadExitPrintStats, OutputModule_::ThreadInit, and unlikely.
OutputRegisterFileRotationFlag()
void OutputRegisterFileRotationFlag (int * flag)
Register a flag for file rotation notification.
Parameters
flag A pointer that will be set to 1 when file rotation is requested.
Definition at line 833 of file output.c.
References OutputFileRolloverFlag, SC_ERR_MEM_ALLOC, SCCalloc, SCLogError, TAILQ_INSERT_TAIL, and unlikely.
OutputRegisterFileSubModule()
void OutputRegisterFileSubModule (LoggerId id, const char * parent_name, const char * name, const char * conf_name, OutputInitSubFunc InitFunc, FileLogger FileLogFunc, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Register a file output sub-module.
This function will register an output module so it can be configured with the configuration file.
Return values
Returns 0 on success, -1 on failure.
Definition at line 469 of file output.c.
References OutputModule_::conf_name, FatalError, OutputModule_::FileLogFunc, OutputModule_::InitSubFunc, OutputModule_::logger_id, OutputModule_::name, output_modules, OutputModule_::parent_name, SC_ERR_FATAL, SCCalloc, SCLogDebug, TAILQ_INSERT_TAIL, OutputModule_::ThreadDeinit, OutputModule_::ThreadExitPrintStats, OutputModule_::ThreadInit, and unlikely.
Referenced by JsonFileLogRegister().
OutputRegisterFlowSubModule()
void OutputRegisterFlowSubModule (LoggerId id, const char * parent_name, const char * name, const char * conf_name, OutputInitSubFunc InitFunc, FlowLogger FlowLogFunc, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Register a flow output sub-module.
This function will register an output module so it can be configured with the configuration file.
Return values
Returns 0 on success, -1 on failure.
Definition at line 588 of file output.c.
References OutputModule_::conf_name, FatalError, OutputModule_::FlowLogFunc, OutputModule_::InitSubFunc, OutputModule_::logger_id, OutputModule_::name, output_modules, OutputModule_::parent_name, SC_ERR_FATAL, SCCalloc, SCLogDebug, TAILQ_INSERT_TAIL, OutputModule_::ThreadDeinit, OutputModule_::ThreadExitPrintStats, OutputModule_::ThreadInit, and unlikely.
Referenced by JsonFlowLogRegister(), and JsonNetFlowLogRegister().
OutputRegisterModule()
void OutputRegisterModule (const char * , const char * , OutputInitFunc)
Referenced by OutputJsonRegister().
OutputRegisterPacketModule()
void OutputRegisterPacketModule (LoggerId id, const char * name, const char * conf_name, OutputInitFunc InitFunc, PacketLogger PacketLogFunc, PacketLogCondition PacketConditionFunc, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Register a packet output module.
This function will register an output module so it can be configured with the configuration file.
Return values
Returns 0 on success, -1 on failure.
Definition at line 177 of file output.c.
References OutputModule_::conf_name, FatalError, OutputModule_::InitFunc, OutputModule_::logger_id, OutputModule_::name, output_modules, OutputModule_::PacketConditionFunc, OutputModule_::PacketLogFunc, SC_ERR_FATAL, SCCalloc, SCLogDebug, TAILQ_INSERT_TAIL, OutputModule_::ThreadDeinit, OutputModule_::ThreadExitPrintStats, OutputModule_::ThreadInit, and unlikely.
Referenced by AlertDebugLogRegister(), AlertFastLogRegister(), AlertSyslogRegister(), and PcapLogRegister().
OutputRegisterPacketSubModule()
void OutputRegisterPacketSubModule (LoggerId id, const char * parent_name, const char * name, const char * conf_name, OutputInitSubFunc InitFunc, PacketLogger PacketLogFunc, PacketLogCondition PacketConditionFunc, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Register a packet output sub-module.
This function will register an output module so it can be configured with the configuration file.
Return values
Returns 0 on success, -1 on failure.
Definition at line 217 of file output.c.
References OutputModule_::conf_name, FatalError, OutputModule_::InitSubFunc, OutputModule_::logger_id, OutputModule_::name, output_modules, OutputModule_::PacketConditionFunc, OutputModule_::PacketLogFunc, OutputModule_::parent_name, SC_ERR_FATAL, SCCalloc, SCLogDebug, TAILQ_INSERT_TAIL, OutputModule_::ThreadDeinit, OutputModule_::ThreadExitPrintStats, OutputModule_::ThreadInit, and unlikely.
Referenced by JsonAlertLogRegister(), JsonAnomalyLogRegister(), JsonDropLogRegister(), JsonFrameLogRegister(), and JsonMetadataLogRegister().
OutputRegisterRootLogger()
void OutputRegisterRootLogger (ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats, OutputLogFunc LogFunc, OutputGetActiveCountFunc ActiveCntFunc)
Definition at line 965 of file output.c.
References RootLogger_::ActiveCntFunc, BUG_ON, FatalError, RootLogger_::LogFunc, SC_ERR_MEM_ALLOC, SCCalloc, TAILQ_INSERT_TAIL, RootLogger_::ThreadDeinit, RootLogger_::ThreadExitPrintStats, and RootLogger_::ThreadInit.
Referenced by OutputFiledataLoggerRegister(), OutputFileLoggerRegister(), OutputPacketLoggerRegister(), OutputStreamingLoggerRegister(), and OutputTxLoggerRegister().
OutputRegisterStatsModule()
void OutputRegisterStatsModule (LoggerId id, const char * name, const char * conf_name, OutputInitFunc InitFunc, StatsLogger StatsLogFunc, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Register a stats data output module.
This function will register an output module so it can be configured with the configuration file.
Return values
Returns 0 on success, -1 on failure.
Definition at line 710 of file output.c.
References OutputModule_::conf_name, FatalError, OutputModule_::InitFunc, OutputModule_::logger_id, OutputModule_::name, output_modules, SC_ERR_FATAL, SCCalloc, SCLogDebug, OutputModule_::StatsLogFunc, TAILQ_INSERT_TAIL, OutputModule_::ThreadDeinit, OutputModule_::ThreadExitPrintStats, OutputModule_::ThreadInit, and unlikely.
Referenced by LogStatsLogRegister().
OutputRegisterStatsSubModule()
void OutputRegisterStatsSubModule (LoggerId id, const char * parent_name, const char * name, const char * conf_name, OutputInitSubFunc InitFunc, StatsLogger StatsLogFunc, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Register a stats data output sub-module.
This function will register an output module so it can be configured with the configuration file.
Return values
Returns 0 on success, -1 on failure.
Definition at line 748 of file output.c.
References OutputModule_::conf_name, FatalError, OutputModule_::InitSubFunc, OutputModule_::logger_id, OutputModule_::name, output_modules, OutputModule_::parent_name, SC_ERR_FATAL, SCCalloc, SCLogDebug, OutputModule_::StatsLogFunc, TAILQ_INSERT_TAIL, OutputModule_::ThreadDeinit, OutputModule_::ThreadExitPrintStats, OutputModule_::ThreadInit, and unlikely.
Referenced by JsonStatsLogRegister().
OutputRegisterStreamingModule()
void OutputRegisterStreamingModule (LoggerId id, const char * name, const char * conf_name, OutputInitFunc InitFunc, StreamingLogger StreamingLogFunc, enum OutputStreamingType stream_type, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Register a streaming data output module.
This function will register an output module so it can be configured with the configuration file.
Return values
Returns 0 on success, -1 on failure.
Definition at line 628 of file output.c.
References OutputModule_::conf_name, FatalError, OutputModule_::InitFunc, OutputModule_::logger_id, OutputModule_::name, output_modules, SC_ERR_FATAL, SCCalloc, SCLogDebug, OutputModule_::stream_type, OutputModule_::StreamingLogFunc, TAILQ_INSERT_TAIL, OutputModule_::ThreadDeinit, OutputModule_::ThreadExitPrintStats, OutputModule_::ThreadInit, and unlikely.
Referenced by LogTcpDataLogRegister().
OutputRegisterStreamingSubModule()
void OutputRegisterStreamingSubModule (LoggerId id, const char * parent_name, const char * name, const char * conf_name, OutputInitSubFunc InitFunc, StreamingLogger StreamingLogFunc, enum OutputStreamingType stream_type, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Register a streaming data output sub-module.
This function will register an output module so it can be configured with the configuration file.
Return values
Returns 0 on success, -1 on failure.
Definition at line 669 of file output.c.
References OutputModule_::conf_name, FatalError, OutputModule_::InitSubFunc, OutputModule_::logger_id, OutputModule_::name, output_modules, OutputModule_::parent_name, SC_ERR_FATAL, SCCalloc, SCLogDebug, OutputModule_::stream_type, OutputModule_::StreamingLogFunc, TAILQ_INSERT_TAIL, OutputModule_::ThreadDeinit, OutputModule_::ThreadExitPrintStats, OutputModule_::ThreadInit, and unlikely.
OutputRegisterTxModule()
void OutputRegisterTxModule (LoggerId id, const char * name, const char * conf_name, OutputInitFunc InitFunc, AppProto alproto, TxLogger TxLogFunc, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Register a tx output module.
This function will register an output module so it can be configured with the configuration file.
Return values
Returns 0 on success, -1 on failure.
Definition at line 401 of file output.c.
Referenced by LogHttpLogRegister().
OutputRegisterTxModuleWithCondition()
void OutputRegisterTxModuleWithCondition (LoggerId id, const char * name, const char * conf_name, OutputInitFunc InitFunc, AppProto alproto, TxLogger TxLogFunc, TxLoggerCondition TxLogCondition, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Register a tx output module with condition.
This function will register an output module so it can be configured with the configuration file.
Return values
Returns 0 on success, -1 on failure.
Definition at line 339 of file output.c.
Referenced by LogTlsStoreRegister().
OutputRegisterTxModuleWithProgress()
void OutputRegisterTxModuleWithProgress (LoggerId id, const char * name, const char * conf_name, OutputInitFunc InitFunc, AppProto alproto, TxLogger TxLogFunc, int tc_log_progress, int ts_log_progress, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Register a tx output module with progress.
This function will register an output module so it can be configured with the configuration file.
Return values
Returns 0 on success, -1 on failure.
Definition at line 370 of file output.c.
Referenced by LogTlsLogRegister().
OutputRegisterTxSubModule()
void OutputRegisterTxSubModule (LoggerId id, const char * parent_name, const char * name, const char * conf_name, OutputInitSubFunc InitFunc, AppProto alproto, TxLogger TxLogFunc, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Definition at line 412 of file output.c.
Referenced by JsonDCERPCLogRegister(), JsonDHCPLogRegister(), JsonDnsLogRegister(), JsonFTPLogRegister(), JsonHttpLogRegister(), JsonIKELogRegister(), JsonKRB5LogRegister(), JsonModbusLogRegister(), JsonMQTTLogRegister(), JsonNFSLogRegister(), JsonPgsqlLogRegister(), JsonQuicLogRegister(), JsonRdpLogRegister(), JsonRFBLogRegister(), JsonSIPLogRegister(), JsonSMBLogRegister(), JsonSmtpLogRegister(), JsonSNMPLogRegister(), JsonTemplateLogRegister(), JsonTemplateRustLogRegister(), and JsonTFTPLogRegister().
OutputRegisterTxSubModuleWithCondition()
void OutputRegisterTxSubModuleWithCondition (LoggerId id, const char * parent_name, const char * name, const char * conf_name, OutputInitSubFunc InitFunc, AppProto alproto, TxLogger TxLogFunc, TxLoggerCondition TxLogCondition, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Definition at line 350 of file output.c.
Referenced by JsonSshLogRegister().
OutputRegisterTxSubModuleWithProgress()
void OutputRegisterTxSubModuleWithProgress (LoggerId id, const char * parent_name, const char * name, const char * conf_name, OutputInitSubFunc InitFunc, AppProto alproto, TxLogger TxLogFunc, int tc_log_progress, int ts_log_progress, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, ThreadExitPrintStatsFunc ThreadExitPrintStats)
Definition at line 381 of file output.c.
Referenced by JsonDNP3LogRegister(), JsonHttp2LogRegister(), and JsonTlsLogRegister().
OutputSetupActiveLoggers()
void OutputSetupActiveLoggers (void)
Definition at line 998 of file output.c.
References TAILQ_FIRST.
OutputUnregisterFileRotationFlag()
void OutputUnregisterFileRotationFlag (int * flag)
Unregister a file rotation flag.
Note that it is safe to call this function with a flag that may not have been registered, in which case this function won't do anything.
Parameters
flag A pointer that has been previously registered for file rotation notifications.
Definition at line 855 of file output.c.
References next, OutputFileRolloverFlag, SCFree, TAILQ_FIRST, TAILQ_NEXT, and TAILQ_REMOVE.
Referenced by LogFileFreeCtx().
TAILQ_HEAD()
typedef TAILQ_HEAD (OutputModuleList_ , OutputModule_)
TmModuleLoggerRegister()
void TmModuleLoggerRegister (void)
Definition at line 1020 of file output.c.
References OutputRegisterLoggers(), and OutputRegisterRootLoggers().
Referenced by RegisterAllModules().
Variable Documentation
output_modules
OutputModuleList output_modules extern
Referenced by OutputDeregisterAll(), OutputGetModuleByConfName(), OutputRegisterFiledataModule(), OutputRegisterFiledataSubModule(), OutputRegisterFileModule(), OutputRegisterFileSubModule(), OutputRegisterFlowSubModule(), OutputRegisterPacketModule(), OutputRegisterPacketSubModule(), OutputRegisterStatsModule(), OutputRegisterStatsSubModule(), OutputRegisterStreamingModule(), and OutputRegisterStreamingSubModule().