suricata: /Users/jlu/suricata/src/output-json-sip.c File Reference
output-json-sip.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "pkt-var.h"
#include "conf.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "util-unittest.h"
#include "util-buffer.h"
#include "util-debug.h"
#include "util-byte.h"
#include "output.h"
#include "output-json.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "app-layer-sip.h"
#include "output-json-sip.h"
#include "rust.h"
Functions
void JsonSIPAddMetadata (JsonBuilder *js, const Flow *f, uint64_t tx_id)
void JsonSIPLogRegister (void)
Detailed Description
Author
Giuseppe Longo giuse.nosp@m.ppe@.nosp@m.glong.nosp@m.o.it
Implement JSON/eve logging app-layer SIP.
Definition in file output-json-sip.c.
Function Documentation
JsonSIPAddMetadata()
void JsonSIPAddMetadata (JsonBuilder * js, const Flow * f, uint64_t tx_id)
Definition at line 51 of file output-json-sip.c.
References ALPROTO_SIP, AppLayerParserGetTx(), FlowGetAppState(), and Flow_::proto.
JsonSIPLogRegister()
void JsonSIPLogRegister (void)
Definition at line 94 of file output-json-sip.c.
References LOGGER_JSON_SIP, and OutputRegisterTxSubModule().
Referenced by OutputRegisterLoggers().