suricata: /Users/jlu/suricata/src/output-json-flow.c File Reference
output-json-flow.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "pkt-var.h"
#include "conf.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "util-print.h"
#include "util-unittest.h"
#include "util-debug.h"
#include "output.h"
#include "util-privs.h"
#include "util-buffer.h"
#include "util-device.h"
#include "util-proto-name.h"
#include "util-logopenfile.h"
#include "util-time.h"
#include "output-json.h"
#include "output-json-flow.h"
#include "stream-tcp.h"
#include "stream-tcp-private.h"
#include "flow-storage.h"
Functions
void EveAddAppProto (Flow *f, JsonBuilder *js)
void EveAddFlow (Flow *f, JsonBuilder *js)
void JsonFlowLogRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Implements Flow JSON logging portion of the engine.
Definition in file output-json-flow.c.
Function Documentation
EveAddAppProto()
void EveAddAppProto (Flow * f, JsonBuilder * js)
Definition at line 168 of file output-json-flow.c.
References Flow_::alproto, Flow_::alproto_expect, Flow_::alproto_orig, Flow_::alproto_tc, Flow_::alproto_ts, ALPROTO_UNKNOWN, and AppProtoToString().
EveAddFlow()
void EveAddFlow (Flow * f, JsonBuilder * js)
Definition at line 189 of file output-json-flow.c.
References CreateIsoTimeString(), FlowGetStorageById(), GetFlowBypassInfoID(), Flow_::startts, Flow_::todstbytecnt, FlowBypassInfo_::todstbytecnt, Flow_::todstpktcnt, FlowBypassInfo_::todstpktcnt, Flow_::tosrcbytecnt, FlowBypassInfo_::tosrcbytecnt, Flow_::tosrcpktcnt, and FlowBypassInfo_::tosrcpktcnt.
JsonFlowLogRegister()
void JsonFlowLogRegister (void)
Definition at line 340 of file output-json-flow.c.
References LOGGER_JSON_FLOW, OutputJsonLogInitSub(), and OutputRegisterFlowSubModule().
Referenced by OutputRegisterLoggers().