suricata: /Users/jlu/suricata/src/output-json-common.c File Reference
output-json-common.c File Reference
#include "suricata-common.h"
#include "pkt-var.h"
#include "conf.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "util-unittest.h"
#include "util-buffer.h"
#include "util-debug.h"
#include "util-byte.h"
#include "output.h"
#include "output-json.h"
#include "app-layer.h"
#include "app-layer-parser.h"
Functions
OutputJsonThreadCtx * CreateEveThreadCtx (ThreadVars *t, OutputJsonCtx *ctx)
void FreeEveThreadCtx (OutputJsonThreadCtx *ctx)
OutputInitResult OutputJsonLogInitSub (ConfNode *conf, OutputCtx *parent_ctx)
TmEcode JsonLogThreadInit (ThreadVars *t, const void *initdata, void **data)
TmEcode JsonLogThreadDeinit (ThreadVars *t, void *data)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file output-json-common.c.
Function Documentation
CreateEveThreadCtx()
OutputJsonThreadCtx * CreateEveThreadCtx (ThreadVars * t, OutputJsonCtx * ctx)
Definition at line 43 of file output-json-common.c.
References OutputJsonThreadCtx_::buffer, OutputJsonThreadCtx_::ctx, OutputJsonCtx_::file_ctx, OutputJsonThreadCtx_::file_ctx, ThreadVars_::id, JSON_OUTPUT_BUFFER_SIZE, LogFileEnsureExists(), MemBufferCreateNew(), MemBufferFree(), SCCalloc, SCFree, and unlikely.
FreeEveThreadCtx()
void FreeEveThreadCtx (OutputJsonThreadCtx * ctx)
Definition at line 72 of file output-json-common.c.
References OutputJsonThreadCtx_::buffer, MemBufferFree(), and SCFree.
Referenced by JsonLogThreadDeinit().
JsonLogThreadDeinit()
TmEcode JsonLogThreadDeinit (ThreadVars * t, void * data)
Definition at line 137 of file output-json-common.c.
References FreeEveThreadCtx(), and TM_ECODE_OK.
JsonLogThreadInit()
TmEcode JsonLogThreadInit (ThreadVars * t, const void * initdata, void ** data)
Definition at line 104 of file output-json-common.c.
References OutputJsonThreadCtx_::buffer, OutputJsonThreadCtx_::ctx, OutputJsonCtx_::file_ctx, OutputJsonThreadCtx_::file_ctx, ThreadVars_::id, JSON_OUTPUT_BUFFER_SIZE, LogFileEnsureExists(), MemBufferCreateNew(), MemBufferFree(), SCCalloc, SCFree, TM_ECODE_FAILED, TM_ECODE_OK, and unlikely.
OutputJsonLogInitSub()
OutputInitResult OutputJsonLogInitSub (ConfNode * conf, OutputCtx * parent_ctx)
Definition at line 87 of file output-json-common.c.
References OutputCtx_::data, OutputCtx_::DeInit, SCCalloc, and unlikely.
Referenced by JsonFlowLogRegister(), JsonMetadataLogRegister(), and JsonNetFlowLogRegister().