suricata: /Users/jlu/suricata/src/output-json-rfb.c File Reference
output-json-rfb.c File Reference
#include "suricata-common.h"
#include "conf.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "util-unittest.h"
#include "util-buffer.h"
#include "util-debug.h"
#include "util-byte.h"
#include "output.h"
#include "output-json.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "app-layer-rfb.h"
#include "output-json-rfb.h"
#include "rust-bindings.h"
Functions
bool JsonRFBAddMetadata (const Flow *f, uint64_t tx_id, JsonBuilder *js)
void JsonRFBLogRegister (void)
Detailed Description
Author
Frank Honza frank.nosp@m..hon.nosp@m.za@dc.nosp@m.so.d.nosp@m.e
Implement JSON/eve logging app-layer RFB.
Definition in file output-json-rfb.c.
Function Documentation
JsonRFBAddMetadata()
bool JsonRFBAddMetadata (const Flow * f, uint64_t tx_id, JsonBuilder * js)
Definition at line 49 of file output-json-rfb.c.
References ALPROTO_RFB, AppLayerParserGetTx(), FlowGetAppState(), and Flow_::proto.
JsonRFBLogRegister()
void JsonRFBLogRegister (void)
Definition at line 93 of file output-json-rfb.c.
References LOGGER_JSON_RFB, and OutputRegisterTxSubModule().
Referenced by OutputRegisterLoggers().