suricata: /Users/jlu/suricata/src/output-json-file.h File Reference
output-json-file.h File Reference
#include "app-layer-htp-xff.h"
Typedefs
typedef struct OutputJsonCtx_ OutputJsonCtx
Functions
void JsonFileLogRegister (void)
JsonBuilder * JsonBuildFileInfoRecord (const Packet *p, const File *ff, const bool stored, uint8_t dir, HttpXFFCfg *xff_cfg, OutputJsonCtx *eve_ctx)
Detailed Description
Author
Tom DeCanio td@np.nosp@m.ulse.nosp@m.tech..nosp@m.com
Definition in file output-json-file.h.
Typedef Documentation
OutputJsonCtx
typedef struct OutputJsonCtx_ OutputJsonCtx
Definition at line 29 of file output-json-file.h.
Function Documentation
JsonBuildFileInfoRecord()
JsonBuilder * JsonBuildFileInfoRecord (const Packet * p, const File * ff, const bool stored, uint8_t dir, HttpXFFCfg * xff_cfg, OutputJsonCtx * eve_ctx)
Definition at line 83 of file output-json-file.c.
References Flow_::alproto, ALPROTO_HTTP1, ALPROTO_HTTP2, ALPROTO_NFS, ALPROTO_SMB, ALPROTO_SMTP, AppProtoToString(), CreateEveHeader(), DEBUG_VALIDATE_BUG_ON, JsonAddrInfo_::dst_ip, EveEmailAddMetadata(), EveFileInfo(), EveHTTP2AddMetadata(), EveHttpAddMetadata(), EveNFSAddMetadata(), EveNFSAddMetadataRPC(), EveSMBAddMetadata(), EveSMTPAddMetadata(), HttpXFFCfg_::flags, Packet_::flow, FLOW_PKT_TOCLIENT, Packet_::flowflags, FlowGetAppProtocol(), HttpXFFGetIPFromTx(), json_addr_info_zero, JSON_ADDR_LEN, JsonAddrInfoInit(), LOG_DIR_FLOW, LOG_DIR_FLOW_TOCLIENT, LOG_DIR_FLOW_TOSERVER, JsonAddrInfo_::src_ip, strlcpy(), File_::txid, unlikely, XFF_DISABLED, XFF_EXTRADATA, XFF_MAXLEN, and XFF_OVERWRITE.
JsonFileLogRegister()
void JsonFileLogRegister (void)
Definition at line 340 of file output-json-file.c.
References LOGGER_JSON_FILE, and OutputRegisterFileSubModule().
Referenced by OutputRegisterLoggers().