suricata: /Users/jlu/suricata/src/output-json-modbus.c File Reference
output-json-modbus.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "pkt-var.h"
#include "conf.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "util-unittest.h"
#include "util-buffer.h"
#include "util-debug.h"
#include "util-byte.h"
#include "output.h"
#include "output-json.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "output-json-modbus.h"
#include "rust.h"
Data Structures
struct LogModbusFileCtx_
struct JsonModbusLogThread_
Typedefs
typedef struct LogModbusFileCtx_ LogModbusFileCtx
typedef struct JsonModbusLogThread_ JsonModbusLogThread
Functions
bool JsonModbusAddMetadata (const Flow *f, uint64_t tx_id, JsonBuilder *js)
void JsonModbusLogRegister (void)
Typedef Documentation
JsonModbusLogThread
typedef struct JsonModbusLogThread_ JsonModbusLogThread
LogModbusFileCtx
typedef struct LogModbusFileCtx_ LogModbusFileCtx
Function Documentation
JsonModbusAddMetadata()
bool JsonModbusAddMetadata (const Flow * f, uint64_t tx_id, JsonBuilder * js)
Definition at line 139 of file output-json-modbus.c.
References ALPROTO_MODBUS, AppLayerParserGetTx(), FlowGetAppState(), and Flow_::proto.
JsonModbusLogRegister()
void JsonModbusLogRegister (void)
Definition at line 152 of file output-json-modbus.c.
References LOGGER_JSON_MODBUS, and OutputRegisterTxSubModule().
Referenced by OutputRegisterLoggers().