suricata: /Users/jlu/suricata/src/output-json-email-common.h File Reference
output-json-email-common.h File Reference
Data Structures
struct OutputJsonEmailCtx_
struct JsonEmailLogThread_
Typedefs
typedef struct OutputJsonEmailCtx_ OutputJsonEmailCtx
typedef struct JsonEmailLogThread_ JsonEmailLogThread
Functions
TmEcode EveEmailLogJson (JsonEmailLogThread *aft, JsonBuilder *js, const Packet *p, Flow *f, void *state, void *vtx, uint64_t tx_id)
bool EveEmailAddMetadata (const Flow *f, uint32_t tx_id, JsonBuilder *js)
void OutputEmailInitConf (ConfNode *conf, OutputJsonEmailCtx *email_ctx)
Detailed Description
Author
Tom DeCanio td@np.nosp@m.ulse.nosp@m.tech..nosp@m.com
Definition in file output-json-email-common.h.
Typedef Documentation
JsonEmailLogThread
typedef struct JsonEmailLogThread_ JsonEmailLogThread
OutputJsonEmailCtx
typedef struct OutputJsonEmailCtx_ OutputJsonEmailCtx
Function Documentation
EveEmailAddMetadata()
bool EveEmailAddMetadata (const Flow * f, uint32_t tx_id, JsonBuilder * js)
Definition at line 379 of file output-json-email-common.c.
References ALPROTO_SMTP, AppLayerParserGetTx(), and FlowGetAppState().
Referenced by JsonBuildFileInfoRecord().
EveEmailLogJson()
TmEcode EveEmailLogJson (JsonEmailLogThread * aft, JsonBuilder * js, const Packet * p, Flow * f, void * state, void * vtx, uint64_t tx_id)
Definition at line 355 of file output-json-email-common.c.
References JsonEmailLogThread_::emaillog_ctx.
OutputEmailInitConf()
void OutputEmailInitConf (ConfNode * conf, OutputJsonEmailCtx * email_ctx)
Definition at line 392 of file output-json-email-common.c.
References config_field, ConfNodeLookupChild(), ConfNodeLookupChildValue(), ConfValIsTrue(), email_field, email_fields, OutputJsonEmailCtx_::fields, OutputJsonEmailCtx_::flags, LOG_EMAIL_BODY_MD5, LOG_EMAIL_EXTENDED, LOG_EMAIL_SUBJECT_MD5, next, SCLogInfo, TAILQ_FOREACH, and ConfNode_::val.