suricata: /Users/jlu/suricata/src/output-filestore.c File Reference
output-filestore.c File Reference
#include "suricata-common.h"
#include "stream-tcp.h"
#include "app-layer-parser.h"
#include "app-layer-htp.h"
#include "app-layer-htp-xff.h"
#include "app-layer-smtp.h"
#include "feature.h"
#include "output.h"
#include "output-filestore.h"
#include "output-json-file.h"
#include "util-print.h"
#include "util-misc.h"
Data Structures
struct OutputFilestoreCtx_
struct OutputFilestoreLogThread_
Macros
#define MODULE_NAME "OutputFilestore"
#define SHA256_STRING_LEN (SC_SHA256_LEN * 2)
#define LEAF_DIR_MAX_LEN 4
#define FILESTORE_PREFIX_MAX (PATH_MAX - SHA256_STRING_LEN - LEAF_DIR_MAX_LEN)
#define WARN_ONCE(err_code, ...)
Typedefs
typedef struct OutputFilestoreCtx_ OutputFilestoreCtx
typedef struct OutputFilestoreLogThread_ OutputFilestoreLogThread
Functions
void OutputFilestoreRegister (void)
void OutputFilestoreRegisterGlobalCounters (void)
Macro Definition Documentation
FILESTORE_PREFIX_MAX
#define FILESTORE_PREFIX_MAX (PATH_MAX - SHA256_STRING_LEN - LEAF_DIR_MAX_LEN)
Definition at line 41 of file output-filestore.c.
LEAF_DIR_MAX_LEN
#define LEAF_DIR_MAX_LEN 4
Definition at line 40 of file output-filestore.c.
MODULE_NAME
#define MODULE_NAME "OutputFilestore"
Definition at line 35 of file output-filestore.c.
SHA256_STRING_LEN
#define SHA256_STRING_LEN (SC_SHA256_LEN * 2)
Definition at line 39 of file output-filestore.c.
WARN_ONCE
#define WARN_ONCE (err_code, ...)
Value:
        do {                   \
        if (!once_errs[err_code]) {                      \
            once_errs[err_code] = true;                  \
            SCLogWarning(err_code, __VA_ARGS__);         \
        }                                                \
    } while (0)
Definition at line 67 of file output-filestore.c.
Typedef Documentation
OutputFilestoreCtx
typedef struct OutputFilestoreCtx_ OutputFilestoreCtx
OutputFilestoreLogThread
typedef struct OutputFilestoreLogThread_ OutputFilestoreLogThread
Function Documentation
OutputFilestoreRegister()
void OutputFilestoreRegister (void)
Definition at line 524 of file output-filestore.c.
References LOGGER_FILE_STORE, MODULE_NAME, and OutputRegisterFiledataModule().
Referenced by OutputRegisterLoggers().
OutputFilestoreRegisterGlobalCounters()
void OutputFilestoreRegisterGlobalCounters (void)
Definition at line 535 of file output-filestore.c.
References StatsRegisterGlobalCounter().
Referenced by PreRunInit().