suricata: /Users/jlu/suricata/src/output-json-metadata.c File Reference
output-json-metadata.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "flow.h"
#include "conf.h"
#include "threads.h"
#include "tm-threads.h"
#include "threadvars.h"
#include "util-debug.h"
#include "util-misc.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "detect-reference.h"
#include "app-layer-parser.h"
#include "app-layer-dnp3.h"
#include "app-layer-htp.h"
#include "app-layer-htp-xff.h"
#include "util-classification-config.h"
#include "util-syslog.h"
#include "util-logopenfile.h"
#include "output.h"
#include "output-json.h"
#include "output-json-metadata.h"
#include "util-byte.h"
#include "util-privs.h"
#include "util-print.h"
#include "util-proto-name.h"
#include "util-optimize.h"
#include "util-buffer.h"
Macros
#define MODULE_NAME "JsonMetadataLog"
Functions
void JsonMetadataLogRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Logs vars in JSON format.
Definition in file output-json-metadata.c.
Macro Definition Documentation
MODULE_NAME
#define MODULE_NAME "JsonMetadataLog"
Definition at line 64 of file output-json-metadata.c.
Function Documentation
JsonMetadataLogRegister()
void JsonMetadataLogRegister (void)
Definition at line 98 of file output-json-metadata.c.
References LOGGER_JSON_METADATA, MODULE_NAME, OutputJsonLogInitSub(), and OutputRegisterPacketSubModule().
Referenced by OutputRegisterLoggers().