suricata: /Users/jlu/suricata/src/output-json.h File Reference
output-json.h File Reference
#include "suricata-common.h"
#include "util-buffer.h"
#include "util-logopenfile.h"
#include "output.h"
#include "rust.h"
#include "app-layer-htp-xff.h"
#include "suricata-plugin.h"
Data Structures
struct JsonAddrInfo_
struct OutputJSONMemBufferWrapper_
struct OutputJsonCommonSettings_
struct OutputJsonCtx_
struct OutputJsonThreadCtx_
Macros
#define JSON_ADDR_LEN 46
#define JSON_PROTO_LEN 16
#define JSON_OUTPUT_BUFFER_SIZE 65535
Typedefs
typedef struct JsonAddrInfo_ JsonAddrInfo
typedef struct OutputJSONMemBufferWrapper_ OutputJSONMemBufferWrapper
typedef struct OutputJsonCommonSettings_ OutputJsonCommonSettings
typedef struct OutputJsonCtx_ OutputJsonCtx
typedef struct OutputJsonThreadCtx_ OutputJsonThreadCtx
Enumerations
enum OutputJsonLogDirection { LOG_DIR_PACKET = 0 , LOG_DIR_FLOW , LOG_DIR_FLOW_TOCLIENT , LOG_DIR_FLOW_TOSERVER }
Functions
void OutputJsonRegister (void)
void JsonAddrInfoInit (const Packet *p, enum OutputJsonLogDirection dir, JsonAddrInfo *addr)
json_t * SCJsonString (const char *val)
void CreateEveFlowId (JsonBuilder *js, const Flow *f)
void EveFileInfo (JsonBuilder *js, const File *file, const bool stored)
void EveTcpFlags (uint8_t flags, JsonBuilder *js)
jsonify tcp flags field Only add 'true' fields in an attempt to keep things reasonably compact.
void EvePacket (const Packet *p, JsonBuilder *js, unsigned long max_length)
Jsonify a packet.
JsonBuilder * CreateEveHeader (const Packet *p, enum OutputJsonLogDirection dir, const char *event_type, JsonAddrInfo *addr, OutputJsonCtx *eve_ctx)
JsonBuilder * CreateEveHeaderWithTxId (const Packet *p, enum OutputJsonLogDirection dir, const char *event_type, JsonAddrInfo *addr, uint64_t tx_id, OutputJsonCtx *eve_ctx)
int OutputJSONBuffer (json_t *js, LogFileCtx *file_ctx, MemBuffer **buffer)
int OutputJsonBuilderBuffer (JsonBuilder *js, OutputJsonThreadCtx *ctx)
OutputInitResult OutputJsonInitCtx (ConfNode *)
Create a new LogFileCtx for "fast" output style.
OutputInitResult OutputJsonLogInitSub (ConfNode *conf, OutputCtx *parent_ctx)
TmEcode JsonLogThreadInit (ThreadVars *t, const void *initdata, void **data)
TmEcode JsonLogThreadDeinit (ThreadVars *t, void *data)
void EveAddCommonOptions (const OutputJsonCommonSettings *cfg, const Packet *p, const Flow *f, JsonBuilder *js)
void EveAddMetadata (const Packet *p, const Flow *f, JsonBuilder *js)
int OutputJSONMemBufferCallback (const char *str, size_t size, void *data)
OutputJsonThreadCtx * CreateEveThreadCtx (ThreadVars *t, OutputJsonCtx *ctx)
void FreeEveThreadCtx (OutputJsonThreadCtx *ctx)
Variables
const JsonAddrInfo json_addr_info_zero
Detailed Description
Author
Tom DeCanio td@np.nosp@m.ulse.nosp@m.tech..nosp@m.com
Definition in file output-json.h.
Macro Definition Documentation
JSON_ADDR_LEN
#define JSON_ADDR_LEN 46
Definition at line 45 of file output-json.h.
JSON_OUTPUT_BUFFER_SIZE
#define JSON_OUTPUT_BUFFER_SIZE 65535
Definition at line 63 of file output-json.h.
JSON_PROTO_LEN
#define JSON_PROTO_LEN 16
Definition at line 46 of file output-json.h.
Typedef Documentation
JsonAddrInfo
typedef struct JsonAddrInfo_ JsonAddrInfo
OutputJsonCommonSettings
typedef struct OutputJsonCommonSettings_ OutputJsonCommonSettings
OutputJsonCtx
typedef struct OutputJsonCtx_ OutputJsonCtx
OutputJSONMemBufferWrapper
typedef struct OutputJSONMemBufferWrapper_ OutputJSONMemBufferWrapper
OutputJsonThreadCtx
typedef struct OutputJsonThreadCtx_ OutputJsonThreadCtx
Enumeration Type Documentation
OutputJsonLogDirection
enum OutputJsonLogDirection
Enumerator
LOG_DIR_PACKET
LOG_DIR_FLOW
LOG_DIR_FLOW_TOCLIENT
LOG_DIR_FLOW_TOSERVER
Definition at line 38 of file output-json.h.
Function Documentation
CreateEveFlowId()
void CreateEveFlowId (JsonBuilder * js, const Flow * f)
Definition at line 726 of file output-json.c.
Referenced by CreateEveHeader().
CreateEveHeader()
JsonBuilder * CreateEveHeader (const Packet * p, enum OutputJsonLogDirection dir, const char * event_type, JsonAddrInfo * addr, OutputJsonCtx * eve_ctx)
Definition at line 821 of file output-json.c.
References CreateEveFlowId(), CreateIsoTimeString(), Packet_::flow, Packet_::ts, and unlikely.
Referenced by CreateEveHeaderWithTxId(), JsonBuildFileInfoRecord(), and RulesDumpMatchArray().
CreateEveHeaderWithTxId()
JsonBuilder * CreateEveHeaderWithTxId (const Packet * p, enum OutputJsonLogDirection dir, const char * event_type, JsonAddrInfo * addr, uint64_t tx_id, OutputJsonCtx * eve_ctx)
Definition at line 904 of file output-json.c.
References CreateEveHeader(), and unlikely.
Referenced by RulesDumpTxMatchArray().
CreateEveThreadCtx()
OutputJsonThreadCtx * CreateEveThreadCtx (ThreadVars * t, OutputJsonCtx * ctx)
Definition at line 43 of file output-json-common.c.
References OutputJsonThreadCtx_::buffer, OutputJsonThreadCtx_::ctx, OutputJsonCtx_::file_ctx, OutputJsonThreadCtx_::file_ctx, ThreadVars_::id, JSON_OUTPUT_BUFFER_SIZE, LogFileEnsureExists(), MemBufferCreateNew(), MemBufferFree(), SCCalloc, SCFree, and unlikely.
EveAddCommonOptions()
void EveAddCommonOptions (const OutputJsonCommonSettings * cfg, const Packet * p, const Flow * f, JsonBuilder * js)
Definition at line 413 of file output-json.c.
References CreateJSONEther(), EveAddMetadata(), OutputJsonCommonSettings_::include_community_id, OutputJsonCommonSettings_::include_ethernet, and OutputJsonCommonSettings_::include_metadata.
EveAddMetadata()
void EveAddMetadata (const Packet * p, const Flow * f, JsonBuilder * js)
Definition at line 388 of file output-json.c.
References Flow_::flowvar, and Packet_::pktvar.
Referenced by EveAddCommonOptions().
EveFileInfo()
void EveFileInfo (JsonBuilder * js, const File * file, const bool stored)
Definition at line 130 of file output-json.c.
References File_::end, FILE_HAS_GAPS, FILE_MD5, FILE_SHA1, FILE_SHA256, FILE_STATE_CLOSED, FILE_STATE_ERROR, FILE_STATE_TRUNCATED, File_::file_store_id, FileTrackedSize(), File_::flags, JB_SET_FALSE, JB_SET_STRING, JB_SET_TRUE, File_::md5, File_::name, File_::name_len, File_::sha1, File_::sha256, File_::sid, File_::sid_cnt, File_::start, File_::state, and File_::txid.
Referenced by JsonBuildFileInfoRecord().
EvePacket()
void EvePacket (const Packet * p, JsonBuilder * js, unsigned long max_length)
Jsonify a packet.
Parameters
p Packet
js JSON object
max_length If non-zero, restricts the number of packet data bytes handled.
Definition at line 437 of file output-json.c.
References Packet_::datalink, GET_PKT_DATA, and GET_PKT_LEN.
EveTcpFlags()
void EveTcpFlags (uint8_t flags, JsonBuilder * js)
jsonify tcp flags field Only add 'true' fields in an attempt to keep things reasonably compact.
Definition at line 454 of file output-json.c.
References flags, JB_SET_TRUE, TH_ACK, TH_CWR, TH_ECN, TH_FIN, TH_PUSH, TH_RST, TH_SYN, and TH_URG.
FreeEveThreadCtx()
void FreeEveThreadCtx (OutputJsonThreadCtx * ctx)
Definition at line 72 of file output-json-common.c.
References OutputJsonThreadCtx_::buffer, MemBufferFree(), and SCFree.
Referenced by JsonLogThreadDeinit().
JsonAddrInfoInit()
void JsonAddrInfoInit (const Packet * p, enum OutputJsonLogDirection dir, JsonAddrInfo * addr)
Definition at line 474 of file output-json.c.
References DEBUG_VALIDATE_BUG_ON, Packet_::dp, JsonAddrInfo_::dp, JsonAddrInfo_::dst_ip, GET_IPV4_DST_ADDR_PTR, GET_IPV4_SRC_ADDR_PTR, GET_IPV6_DST_ADDR, GET_IPV6_SRC_ADDR, IP_GET_IPPROTO, JSON_ADDR_LEN, known_proto, LOG_DIR_FLOW, LOG_DIR_FLOW_TOCLIENT, LOG_DIR_FLOW_TOSERVER, LOG_DIR_PACKET, PKT_IS_IPV4, PKT_IS_IPV6, PKT_IS_TOCLIENT, PKT_IS_TOSERVER, PrintInet(), Packet_::proto, JsonAddrInfo_::proto, SCProtoNameValid(), Packet_::sp, JsonAddrInfo_::sp, JsonAddrInfo_::src_ip, and strlcpy().
Referenced by JsonBuildFileInfoRecord().
JsonLogThreadDeinit()
TmEcode JsonLogThreadDeinit (ThreadVars * t, void * data)
Definition at line 137 of file output-json-common.c.
References FreeEveThreadCtx(), and TM_ECODE_OK.
JsonLogThreadInit()
TmEcode JsonLogThreadInit (ThreadVars * t, const void * initdata, void ** data)
Definition at line 104 of file output-json-common.c.
References OutputJsonThreadCtx_::buffer, OutputJsonThreadCtx_::ctx, OutputJsonCtx_::file_ctx, OutputJsonThreadCtx_::file_ctx, ThreadVars_::id, JSON_OUTPUT_BUFFER_SIZE, LogFileEnsureExists(), MemBufferCreateNew(), MemBufferFree(), SCCalloc, SCFree, TM_ECODE_FAILED, TM_ECODE_OK, and unlikely.
OutputJSONBuffer()
int OutputJSONBuffer (json_t * js, LogFileCtx * file_ctx, MemBuffer ** buffer)
Definition at line 930 of file output-json.c.
References OutputJSONMemBufferWrapper_::buffer, LogFileCtx_::is_pcap_offline, LogFileCtx_::json_flags, JSON_OUTPUT_BUFFER_SIZE, LogFileWrite(), MemBufferWriteRaw, OutputJSONMemBufferCallback(), PcapFileGetFilename(), LogFileCtx_::prefix, LogFileCtx_::prefix_len, LogFileCtx_::sensor_name, and TM_ECODE_OK.
OutputJsonBuilderBuffer()
int OutputJsonBuilderBuffer (JsonBuilder * js, OutputJsonThreadCtx * ctx)
Definition at line 959 of file output-json.c.
References OutputJsonThreadCtx_::buffer, OutputJsonThreadCtx_::file_ctx, LogFileCtx_::is_pcap_offline, LogFileWrite(), MEMBUFFER_OFFSET, MEMBUFFER_SIZE, MemBufferExpand(), MemBufferReset, MemBufferWriteRaw, PcapFileGetFilename(), LogFileCtx_::prefix, LogFileCtx_::prefix_len, and LogFileCtx_::sensor_name.
OutputJsonInitCtx()
OutputInitResult OutputJsonInitCtx (ConfNode * conf)
Create a new LogFileCtx for "fast" output style.
Parameters
conf The configuration node for this output.
Returns
A LogFileCtx pointer on success, NULL on failure.
Definition at line 1065 of file output-json.c.
References ConfGet(), ConfNodeLookupChildValue(), OutputCtx_::data, OutputCtx_::DeInit, OutputJsonCtx_::file_ctx, LogFileNewCtx(), SC_ERR_DEPRECATED_CONF, SCCalloc, SCLogDebug, SCLogWarning, SCStrdup, LogFileCtx_::sensor_name, and unlikely.
Referenced by OutputJsonRegister().
OutputJsonLogInitSub()
OutputInitResult OutputJsonLogInitSub (ConfNode * conf, OutputCtx * parent_ctx)
Definition at line 87 of file output-json-common.c.
References OutputCtx_::data, OutputCtx_::DeInit, SCCalloc, and unlikely.
Referenced by JsonFlowLogRegister(), JsonMetadataLogRegister(), and JsonNetFlowLogRegister().
OutputJSONMemBufferCallback()
int OutputJSONMemBufferCallback (const char * str, size_t size, void * data)
Definition at line 917 of file output-json.c.
References OutputJSONMemBufferWrapper_::buffer, OutputJSONMemBufferWrapper_::expand_by, MEMBUFFER_OFFSET, MEMBUFFER_SIZE, MemBufferExpand(), MemBufferWriteRaw, and str.
Referenced by OutputJSONBuffer().
OutputJsonRegister()
void OutputJsonRegister (void)
Definition at line 90 of file output-json.c.
References MODULE_NAME, OutputJsonInitCtx(), and OutputRegisterModule().
Referenced by OutputRegisterLoggers().
SCJsonString()
json_t * SCJsonString (const char * val)
Definition at line 102 of file output-json.c.
References MAX_JSON_SIZE, offset, and PrintBufferData.
Variable Documentation
json_addr_info_zero
const JsonAddrInfo json_addr_info_zero extern
Definition at line 88 of file output-json.c.
Referenced by JsonBuildFileInfoRecord().