suricata: /Users/jlu/suricata/src/output-tx.h File Reference
output-tx.h File Reference
#include "decode.h"
Typedefs
typedef int(* TxLogger) (ThreadVars *, void *thread_data, const Packet *, Flow *f, void *state, void *tx, uint64_t tx_id)
typedef int(* TxLoggerCondition) (ThreadVars *, const Packet *, void *state, void *tx, uint64_t tx_id)
Functions
int OutputRegisterTxLogger (LoggerId id, const char *name, AppProto alproto, TxLogger LogFunc, OutputCtx *, int tc_log_progress, int ts_log_progress, TxLoggerCondition LogCondition, ThreadInitFunc, ThreadDeinitFunc, void(*ThreadExitPrintStats)(ThreadVars *, void *))
void OutputTxLoggerRegister (void)
void OutputTxShutdown (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
AppLayer TX Logger Output registration functions
Definition in file output-tx.h.
Typedef Documentation
TxLogger
typedef int(* TxLogger) (ThreadVars *, void *thread_data, const Packet *, Flow *f, void *state, void *tx, uint64_t tx_id)
tx logger function pointer type
Definition at line 32 of file output-tx.h.
TxLoggerCondition
typedef int(* TxLoggerCondition) (ThreadVars *, const Packet *, void *state, void *tx, uint64_t tx_id)
tx logger condition function pointer type, must return true for tx that should be logged
Definition at line 37 of file output-tx.h.
Function Documentation
OutputRegisterTxLogger()
int OutputRegisterTxLogger (LoggerId id, const char * name, AppProto alproto, TxLogger LogFunc, OutputCtx * output_ctx, int tc_log_progress, int ts_log_progress, TxLoggerCondition LogCondition, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, void(*)(ThreadVars *, void *) ThreadExitPrintStats)
Definition at line 62 of file output-tx.c.
References OutputTxLogger_::alproto, ALPROTO_UNKNOWN, AppLayerParserGetStateProgressCompletionStatus(), AppLayerParserIsEnabled(), AppProtoToString(), OutputTxLogger_::id, OutputTxLogger_::LogCondition, OutputTxLogger_::LogFunc, OutputTxLogger_::logger_id, OutputTxLogger_::name, OutputTxLogger_::output_ctx, SCLogNotice, SCMalloc, OutputTxLogger_::tc_log_progress, OutputTxLogger_::ThreadDeinit, OutputTxLogger_::ThreadExitPrintStats, OutputTxLogger_::ThreadInit, and OutputTxLogger_::ts_log_progress.
OutputTxLoggerRegister()
void OutputTxLoggerRegister (void)
Definition at line 440 of file output-tx.c.
References OutputRegisterRootLogger().
Referenced by OutputRegisterRootLoggers().
OutputTxShutdown()
void OutputTxShutdown (void)
Definition at line 446 of file output-tx.c.
References OutputTxLogger_::alproto, and ALPROTO_MAX.