suricata: /Users/jlu/suricata/src/output-json-smtp.c File Reference
output-json-smtp.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "pkt-var.h"
#include "conf.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "util-print.h"
#include "util-unittest.h"
#include "util-debug.h"
#include "output.h"
#include "app-layer-smtp.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "util-privs.h"
#include "util-buffer.h"
#include "util-proto-name.h"
#include "util-logopenfile.h"
#include "util-time.h"
#include "output-json.h"
#include "output-json-smtp.h"
#include "output-json-email-common.h"
Functions
bool EveSMTPAddMetadata (const Flow *f, uint64_t tx_id, JsonBuilder *js)
void JsonSmtpLogRegister (void)
Detailed Description
Author
Tom DeCanio td@np.nosp@m.ulse.nosp@m.tech..nosp@m.com
Implements SMTP JSON logging portion of the engine.
Definition in file output-json-smtp.c.
Function Documentation
EveSMTPAddMetadata()
bool EveSMTPAddMetadata (const Flow * f, uint64_t tx_id, JsonBuilder * js)
Definition at line 96 of file output-json-smtp.c.
References ALPROTO_SMTP, AppLayerParserGetTx(), and FlowGetAppState().
Referenced by JsonBuildFileInfoRecord().
JsonSmtpLogRegister()
void JsonSmtpLogRegister (void)
Definition at line 192 of file output-json-smtp.c.
References LOGGER_JSON_SMTP, and OutputRegisterTxSubModule().
Referenced by OutputRegisterLoggers().