suricata: /Users/jlu/suricata/src/output-json-modbus.h File Reference
output-json-modbus.h File Reference
Functions
void JsonModbusLogRegister (void)
bool JsonModbusAddMetadata (const Flow *f, uint64_t tx_id, JsonBuilder *js)
Function Documentation
JsonModbusAddMetadata()
bool JsonModbusAddMetadata (const Flow * f, uint64_t tx_id, JsonBuilder * js)
Definition at line 139 of file output-json-modbus.c.
References ALPROTO_MODBUS, AppLayerParserGetTx(), FlowGetAppState(), and Flow_::proto.
JsonModbusLogRegister()
void JsonModbusLogRegister (void)
Definition at line 152 of file output-json-modbus.c.
References LOGGER_JSON_MODBUS, and OutputRegisterTxSubModule().
Referenced by OutputRegisterLoggers().