suricata: /Users/jlu/suricata/src/output-json-nfs.c File Reference
output-json-nfs.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "pkt-var.h"
#include "conf.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "util-unittest.h"
#include "util-buffer.h"
#include "util-debug.h"
#include "util-byte.h"
#include "output.h"
#include "output-json.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "output-json-nfs.h"
#include "rust.h"
Functions
bool EveNFSAddMetadataRPC (const Flow *f, uint64_t tx_id, JsonBuilder *jb)
bool EveNFSAddMetadata (const Flow *f, uint64_t tx_id, JsonBuilder *jb)
void JsonNFSLogRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Implement JSON/eve logging app-layer NFS.
Definition in file output-json-nfs.c.
Function Documentation
EveNFSAddMetadata()
bool EveNFSAddMetadata (const Flow * f, uint64_t tx_id, JsonBuilder * jb)
Definition at line 62 of file output-json-nfs.c.
References ALPROTO_NFS, AppLayerParserGetTx(), FlowGetAppState(), and Flow_::proto.
Referenced by JsonBuildFileInfoRecord().
EveNFSAddMetadataRPC()
bool EveNFSAddMetadataRPC (const Flow * f, uint64_t tx_id, JsonBuilder * jb)
Definition at line 50 of file output-json-nfs.c.
References ALPROTO_NFS, AppLayerParserGetTx(), FlowGetAppState(), and Flow_::proto.
Referenced by JsonBuildFileInfoRecord().
JsonNFSLogRegister()
void JsonNFSLogRegister (void)
Definition at line 110 of file output-json-nfs.c.
References LOGGER_JSON_NFS, and OutputRegisterTxSubModule().
Referenced by OutputRegisterLoggers().