suricata: /Users/jlu/suricata/src/output-json-http2.h File Reference
output-json-http2.h File Reference
Functions
void JsonHttp2LogRegister (void)
bool EveHTTP2AddMetadata (const Flow *f, uint64_t tx_id, JsonBuilder *jb)
Detailed Description
Author
Philippe Antoine p.ant.nosp@m.oine.nosp@m.@cate.nosp@m.nacy.nosp@m.ber.f.nosp@m.r
Definition in file output-json-http2.h.
Function Documentation
EveHTTP2AddMetadata()
bool EveHTTP2AddMetadata (const Flow * f, uint64_t tx_id, JsonBuilder * jb)
Definition at line 65 of file output-json-http2.c.
References ALPROTO_HTTP2, AppLayerParserGetTx(), FlowGetAppState(), and Flow_::proto.
Referenced by JsonBuildFileInfoRecord().
JsonHttp2LogRegister()
void JsonHttp2LogRegister (void)
Definition at line 178 of file output-json-http2.c.
References LOGGER_JSON_HTTP2, MODULE_NAME, and OutputRegisterTxSubModuleWithProgress().
Referenced by OutputRegisterLoggers().