suricata: /Users/jlu/suricata/src/output-json-frame.h File Reference
output-json-frame.h File Reference
#include "app-layer-frames.h"
#include "stream-tcp-private.h"
Functions
void FrameJsonLogOneFrame (const uint8_t ipproto, const Frame *frame, const Flow *f, const TcpStream *stream, const Packet *p, JsonBuilder *jb)
log a single frame
void JsonFrameLogRegister (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Logs frames in JSON format.
Definition in file output-json-frame.h.
Function Documentation
FrameJsonLogOneFrame()
void FrameJsonLogOneFrame (const uint8_t ipproto, const Frame * frame, const Flow * f, const TcpStream * stream, const Packet * p, JsonBuilder * jb)
log a single frame
Note
ipproto argument is passed to assist static code analyzers
Definition at line 217 of file output-json-frame.c.
References Flow_::alproto, AppLayerParserGetFrameNameById(), DEBUG_VALIDATE_BUG_ON, Frame::id, len, Frame::len, PKT_IS_TOSERVER, Packet_::proto, Flow_::proto, Frame::rel_offset, STREAM_BASE_OFFSET, StreamTcpGetUsable(), and Frame::type.
JsonFrameLogRegister()
void JsonFrameLogRegister (void)
Definition at line 498 of file output-json-frame.c.
References LOGGER_JSON_FRAME, MODULE_NAME, and OutputRegisterPacketSubModule().
Referenced by OutputRegisterLoggers().