suricata: /Users/jlu/suricata/src/output-json-smtp.h File Reference
output-json-smtp.h File Reference
Functions
void JsonSmtpLogRegister (void)
bool EveSMTPAddMetadata (const Flow *f, uint64_t tx_id, JsonBuilder *js)
Detailed Description
Author
Tom DeCanio td@np.nosp@m.ulse.nosp@m.tech..nosp@m.com
Definition in file output-json-smtp.h.
Function Documentation
EveSMTPAddMetadata()
bool EveSMTPAddMetadata (const Flow * f, uint64_t tx_id, JsonBuilder * js)
Definition at line 96 of file output-json-smtp.c.
References ALPROTO_SMTP, AppLayerParserGetTx(), and FlowGetAppState().
Referenced by JsonBuildFileInfoRecord().
JsonSmtpLogRegister()
void JsonSmtpLogRegister (void)
Definition at line 192 of file output-json-smtp.c.
References LOGGER_JSON_SMTP, and OutputRegisterTxSubModule().
Referenced by OutputRegisterLoggers().