suricata: /Users/jlu/suricata/src/output-json-sip.h File Reference
output-json-sip.h File Reference
Functions
void JsonSIPLogRegister (void)
void JsonSIPAddMetadata (JsonBuilder *js, const Flow *f, uint64_t tx_id)
Detailed Description
Author
Giuseppe Longo giuse.nosp@m.ppe@.nosp@m.glong.nosp@m.o.it
Definition in file output-json-sip.h.
Function Documentation
JsonSIPAddMetadata()
void JsonSIPAddMetadata (JsonBuilder * js, const Flow * f, uint64_t tx_id)
Definition at line 51 of file output-json-sip.c.
References ALPROTO_SIP, AppLayerParserGetTx(), FlowGetAppState(), and Flow_::proto.
JsonSIPLogRegister()
void JsonSIPLogRegister (void)
Definition at line 94 of file output-json-sip.c.
References LOGGER_JSON_SIP, and OutputRegisterTxSubModule().
Referenced by OutputRegisterLoggers().