suricata: /Users/jlu/suricata/src/output-json-quic.c File Reference
output-json-quic.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "pkt-var.h"
#include "conf.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "util-unittest.h"
#include "util-buffer.h"
#include "util-debug.h"
#include "util-byte.h"
#include "output.h"
#include "output-json.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "output-json-quic.h"
#include "rust.h"
Data Structures
struct LogQuicFileCtx_
struct JsonQuicLogThread_
Typedefs
typedef struct LogQuicFileCtx_ LogQuicFileCtx
typedef struct JsonQuicLogThread_ JsonQuicLogThread
Functions
bool JsonQuicAddMetadata (const Flow *f, uint64_t tx_id, JsonBuilder *js)
void JsonQuicLogRegister (void)
Detailed Description
Implements JSON/eve logging for Quic app-layer.
Definition in file output-json-quic.c.
Typedef Documentation
JsonQuicLogThread
typedef struct JsonQuicLogThread_ JsonQuicLogThread
LogQuicFileCtx
typedef struct LogQuicFileCtx_ LogQuicFileCtx
Function Documentation
JsonQuicAddMetadata()
bool JsonQuicAddMetadata (const Flow * f, uint64_t tx_id, JsonBuilder * js)
Definition at line 143 of file output-json-quic.c.
References ALPROTO_QUIC, AppLayerParserGetTx(), FlowGetAppState(), and Flow_::proto.
JsonQuicLogRegister()
void JsonQuicLogRegister (void)
Definition at line 156 of file output-json-quic.c.
References LOGGER_JSON_QUIC, and OutputRegisterTxSubModule().
Referenced by OutputRegisterLoggers().