suricata: /Users/jlu/suricata/src/output-json-flow.h File Reference
output-json-flow.h File Reference
Functions
void JsonFlowLogRegister (void)
void EveAddFlow (Flow *f, JsonBuilder *js)
void EveAddAppProto (Flow *f, JsonBuilder *js)
Detailed Description
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file output-json-flow.h.
Function Documentation
EveAddAppProto()
void EveAddAppProto (Flow * f, JsonBuilder * js)
Definition at line 168 of file output-json-flow.c.
References Flow_::alproto, Flow_::alproto_expect, Flow_::alproto_orig, Flow_::alproto_tc, Flow_::alproto_ts, ALPROTO_UNKNOWN, and AppProtoToString().
EveAddFlow()
void EveAddFlow (Flow * f, JsonBuilder * js)
Definition at line 189 of file output-json-flow.c.
References CreateIsoTimeString(), FlowGetStorageById(), GetFlowBypassInfoID(), Flow_::startts, Flow_::todstbytecnt, FlowBypassInfo_::todstbytecnt, Flow_::todstpktcnt, FlowBypassInfo_::todstpktcnt, Flow_::tosrcbytecnt, FlowBypassInfo_::tosrcbytecnt, Flow_::tosrcpktcnt, and FlowBypassInfo_::tosrcpktcnt.
JsonFlowLogRegister()
void JsonFlowLogRegister (void)
Definition at line 340 of file output-json-flow.c.
References LOGGER_JSON_FLOW, OutputJsonLogInitSub(), and OutputRegisterFlowSubModule().
Referenced by OutputRegisterLoggers().