suricata: /Users/jlu/suricata/src/output-filestore.h File Reference
output-filestore.h File Reference
Functions
void OutputFilestoreRegister (void)
void OutputFilestoreInitConfig (void)
void OutputFilestoreRegisterGlobalCounters (void)
Function Documentation
OutputFilestoreInitConfig()
void OutputFilestoreInitConfig (void)
OutputFilestoreRegister()
void OutputFilestoreRegister (void)
Definition at line 524 of file output-filestore.c.
References LOGGER_FILE_STORE, MODULE_NAME, and OutputRegisterFiledataModule().
Referenced by OutputRegisterLoggers().
OutputFilestoreRegisterGlobalCounters()
void OutputFilestoreRegisterGlobalCounters (void)
Definition at line 535 of file output-filestore.c.
References StatsRegisterGlobalCounter().
Referenced by PreRunInit().