suricata: /Users/jlu/suricata/src/output-tx.c File Reference
output-tx.c File Reference
#include "suricata-common.h"
#include "tm-modules.h"
#include "output.h"
#include "output-tx.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "util-profiling.h"
#include "util-validate.h"
Data Structures
struct OutputTxLoggerThreadData_
struct OutputTxLogger_
Typedefs
typedef struct OutputTxLoggerThreadData_ OutputTxLoggerThreadData
typedef struct OutputTxLogger_ OutputTxLogger
Functions
int OutputRegisterTxLogger (LoggerId id, const char *name, AppProto alproto, TxLogger LogFunc, OutputCtx *output_ctx, int tc_log_progress, int ts_log_progress, TxLoggerCondition LogCondition, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, void(*ThreadExitPrintStats)(ThreadVars *, void *))
void OutputTxLoggerRegister (void)
void OutputTxShutdown (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
AppLayer TX Logger Output registration functions
Definition in file output-tx.c.
Typedef Documentation
OutputTxLogger
typedef struct OutputTxLogger_ OutputTxLogger
OutputTxLoggerThreadData
typedef struct OutputTxLoggerThreadData_ OutputTxLoggerThreadData
per thread data for this module, contains a list of per thread data for the packet loggers.
Function Documentation
OutputRegisterTxLogger()
int OutputRegisterTxLogger (LoggerId id, const char * name, AppProto alproto, TxLogger LogFunc, OutputCtx * output_ctx, int tc_log_progress, int ts_log_progress, TxLoggerCondition LogCondition, ThreadInitFunc ThreadInit, ThreadDeinitFunc ThreadDeinit, void(*)(ThreadVars *, void *) ThreadExitPrintStats)
Definition at line 62 of file output-tx.c.
References OutputTxLogger_::alproto, ALPROTO_UNKNOWN, AppLayerParserGetStateProgressCompletionStatus(), AppLayerParserIsEnabled(), AppProtoToString(), OutputTxLogger_::id, OutputTxLogger_::LogCondition, OutputTxLogger_::LogFunc, OutputTxLogger_::logger_id, OutputTxLogger_::name, OutputTxLogger_::output_ctx, SCLogNotice, SCMalloc, OutputTxLogger_::tc_log_progress, OutputTxLogger_::ThreadDeinit, OutputTxLogger_::ThreadExitPrintStats, OutputTxLogger_::ThreadInit, and OutputTxLogger_::ts_log_progress.
OutputTxLoggerRegister()
void OutputTxLoggerRegister (void)
Definition at line 440 of file output-tx.c.
References OutputRegisterRootLogger().
Referenced by OutputRegisterRootLoggers().
OutputTxShutdown()
void OutputTxShutdown (void)
Definition at line 446 of file output-tx.c.
References OutputTxLogger_::alproto, and ALPROTO_MAX.