suricata: /Users/jlu/suricata/src/packet-queue.h File Reference
packet-queue.h File Reference
Data Structures
struct PacketQueueNoLock_
simple fifo queue for packets
struct PacketQueue_
simple fifo queue for packets with mutex and cond Calling the mutex or triggering the cond is responsibility of the caller
Typedefs
typedef struct PacketQueueNoLock_ PacketQueueNoLock
simple fifo queue for packets
typedef struct PacketQueue_ PacketQueue
simple fifo queue for packets with mutex and cond Calling the mutex or triggering the cond is responsibility of the caller
Functions
void PacketEnqueueNoLock (PacketQueueNoLock *qnl, struct Packet_ *p)
void PacketEnqueue (PacketQueue *, struct Packet_ *)
struct Packet_ * PacketDequeueNoLock (PacketQueueNoLock *qnl)
struct Packet_ * PacketDequeue (PacketQueue *)
PacketQueue * PacketQueueAlloc (void)
void PacketQueueFree (PacketQueue *)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file packet-queue.h.
Typedef Documentation
PacketQueue
typedef struct PacketQueue_ PacketQueue
simple fifo queue for packets with mutex and cond Calling the mutex or triggering the cond is responsibility of the caller
Note
PacketQueueNoLock and PacketQueue need to keep identical layouts except for the mutex_q and cond_q fields.
PacketQueueNoLock
typedef struct PacketQueueNoLock_ PacketQueueNoLock
simple fifo queue for packets
Note
PacketQueueNoLock and PacketQueue need to keep identical layouts except for the mutex_q and cond_q fields.
Function Documentation
PacketDequeue()
struct Packet_ * PacketDequeue (PacketQueue * q)
Definition at line 212 of file packet-queue.c.
Referenced by TmqhInputFlow(), TmqhInputSimple(), and TmqhReleasePacketsToPacketPool().
PacketDequeueNoLock()
struct Packet_ * PacketDequeueNoLock (PacketQueueNoLock * qnl)
Definition at line 206 of file packet-queue.c.
PacketEnqueue()
void PacketEnqueue (PacketQueue * q, struct Packet_ * p)
Definition at line 173 of file packet-queue.c.
Referenced by TmqhOutputFlowHash(), TmqhOutputFlowIPPair(), and TmqhOutputSimple().
PacketEnqueueNoLock()
void PacketEnqueueNoLock (PacketQueueNoLock * qnl, struct Packet_ * p)
Definition at line 167 of file packet-queue.c.
PacketQueueAlloc()
PacketQueue * PacketQueueAlloc (void)
Definition at line 217 of file packet-queue.c.
References PacketQueue_::cond_q, PacketQueue_::mutex_q, SCCalloc, SCCondInit, and SCMutexInit.
PacketQueueFree()
void PacketQueueFree (PacketQueue * pq)
Definition at line 227 of file packet-queue.c.
References PacketQueue_::cond_q, PacketQueue_::mutex_q, SCCondDestroy, SCFree, and SCMutexDestroy.
Referenced by TmqResetQueues().