suricata: /Users/jlu/suricata/src/packet-queue.c File Reference
packet-queue.c File Reference
#include "suricata-common.h"
#include "decode.h"
#include "packet-queue.h"
#include "threads.h"
#include "suricata.h"
#include "util-var.h"
#include "pkt-var.h"
Functions
void PacketEnqueueNoLock (PacketQueueNoLock *qnl, Packet *p)
void PacketEnqueue (PacketQueue *q, Packet *p)
Packet * PacketDequeueNoLock (PacketQueueNoLock *qnl)
Packet * PacketDequeue (PacketQueue *q)
PacketQueue * PacketQueueAlloc (void)
void PacketQueueFree (PacketQueue *pq)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Packet Queue portion of the engine.
Definition in file packet-queue.c.
Function Documentation
PacketDequeue()
Packet * PacketDequeue (PacketQueue * q)
Definition at line 212 of file packet-queue.c.
Referenced by TmqhInputFlow(), TmqhInputSimple(), and TmqhReleasePacketsToPacketPool().
PacketDequeueNoLock()
Packet * PacketDequeueNoLock (PacketQueueNoLock * qnl)
Definition at line 206 of file packet-queue.c.
PacketEnqueue()
void PacketEnqueue (PacketQueue * q, Packet * p)
Definition at line 173 of file packet-queue.c.
Referenced by TmqhOutputFlowHash(), TmqhOutputFlowIPPair(), and TmqhOutputSimple().
PacketEnqueueNoLock()
void PacketEnqueueNoLock (PacketQueueNoLock * qnl, Packet * p)
Definition at line 167 of file packet-queue.c.
PacketQueueAlloc()
PacketQueue * PacketQueueAlloc (void)
Definition at line 217 of file packet-queue.c.
References PacketQueue_::cond_q, PacketQueue_::mutex_q, SCCalloc, SCCondInit, and SCMutexInit.
PacketQueueFree()
void PacketQueueFree (PacketQueue * pq)
Definition at line 227 of file packet-queue.c.
References PacketQueue_::cond_q, PacketQueue_::mutex_q, SCCondDestroy, SCFree, and SCMutexDestroy.
Referenced by TmqResetQueues().