suricata: /Users/jlu/suricata/src/runmode-dpdk.c File Reference
runmode-dpdk.c File Reference
DPDK running mode
#include "suricata-common.h"
#include "runmodes.h"
#include "runmode-dpdk.h"
#include "source-dpdk.h"
#include "util-runmodes.h"
#include "util-byte.h"
#include "util-cpu.h"
#include "util-dpdk.h"
#include "util-dpdk-i40e.h"
#include "util-dpdk-ice.h"
#include "util-dpdk-ixgbe.h"
#include "util-time.h"
Functions
const char * RunModeDpdkGetDefaultMode (void)
void RunModeDpdkRegister (void)
int RunModeIdsDpdkWorkers (void)
Workers version of the DPDK processing.
Detailed Description
Author
Lukas Sismis lukas.nosp@m..sis.nosp@m.mis@g.nosp@m.mail.nosp@m..com
DPDK runmode
Definition in file runmode-dpdk.c.
Function Documentation
RunModeDpdkGetDefaultMode()
const char * RunModeDpdkGetDefaultMode (void)
Definition at line 1313 of file runmode-dpdk.c.
Referenced by RunModeDispatch().
RunModeDpdkRegister()
void RunModeDpdkRegister (void)
Definition at line 1318 of file runmode-dpdk.c.
References RUNMODE_DPDK, RunModeIdsDpdkWorkers(), and RunModeRegisterNewRunMode().
RunModeIdsDpdkWorkers()
int RunModeIdsDpdkWorkers (void)
Workers version of the DPDK processing.
Start N threads with each thread doing all the work.
Definition at line 1332 of file runmode-dpdk.c.
References FatalError, RunModeInitialize(), RunModeSetLiveCaptureWorkers(), SC_ERR_FATAL, SCEnter, SCLogDebug, SCReturnInt, thread_name_workers, and TimeModeSetLive().
Referenced by RunModeDpdkRegister().