suricata: /Users/jlu/suricata/src/runmode-af-packet.c File Reference
runmode-af-packet.c File Reference
AF_PACKET running mode
#include "suricata-common.h"
#include "tm-threads.h"
#include "conf.h"
#include "runmodes.h"
#include "runmode-af-packet.h"
#include "output.h"
#include "log-httplog.h"
#include "detect-engine-mpm.h"
#include "alert-fastlog.h"
#include "alert-debuglog.h"
#include "flow-bypass.h"
#include "util-debug.h"
#include "util-time.h"
#include "util-cpu.h"
#include "util-affinity.h"
#include "util-device.h"
#include "util-runmodes.h"
#include "util-ioctl.h"
#include "util-ebpf.h"
#include "util-byte.h"
#include "source-af-packet.h"
int max_pending_packets
const char * RunModeAFPGetDefaultMode (void)
void RunModeIdsAFPRegister (void)
int AFPRunModeIsIPS ()
int RunModeIdsAFPAutoFp (void)
int RunModeIdsAFPSingle (void)
Single thread version of the AF_PACKET processing.
int RunModeIdsAFPWorkers (void)
Workers version of the AF_PACKET processing.
Detailed Description
Author
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
AF_PACKET socket runmode
Definition in file runmode-af-packet.c.
Function Documentation
AFPRunModeIsIPS()
int AFPRunModeIsIPS (void)
Definition at line 693 of file runmode-af-packet.c.
References ConfFindDeviceConfig(), ConfGetChildValueWithDefault(), ConfGetNode(), ConfNodeLookupKeyValue(), LiveGetDeviceCount(), LiveGetDeviceName(), SC_ERR_INVALID_ARGUMENT, SC_ERR_INVALID_VALUE, SCLogError, and SCLogInfo.
RunModeAFPGetDefaultMode()
const char * RunModeAFPGetDefaultMode (void)
Definition at line 61 of file runmode-af-packet.c.
Referenced by RunModeDispatch().
RunModeIdsAFPAutoFp()
int RunModeIdsAFPAutoFp (void)
Definition at line 774 of file runmode-af-packet.c.
References AFPPeersListInit(), ConfGet(), FatalError, RunModeInitialize(), RunModeSetLiveCaptureAutoFp(), SC_ERR_FATAL, SCEnter, SCLogDebug, TimeModeSetLive(), and TM_ECODE_OK.
Referenced by RunModeIdsAFPRegister().
RunModeIdsAFPRegister()
void RunModeIdsAFPRegister (void)
Definition at line 66 of file runmode-af-packet.c.
References RUNMODE_AFP_DEV, RunModeIdsAFPAutoFp(), RunModeIdsAFPSingle(), RunModeIdsAFPWorkers(), and RunModeRegisterNewRunMode().
RunModeIdsAFPSingle()
int RunModeIdsAFPSingle (void)
Single thread version of the AF_PACKET processing.
Definition at line 818 of file runmode-af-packet.c.
References AFPPeersListInit(), ConfGet(), FatalError, RunModeInitialize(), RunModeSetLiveCaptureSingle(), SC_ERR_FATAL, SCEnter, TimeModeSetLive(), and TM_ECODE_OK.
Referenced by RunModeIdsAFPRegister().
RunModeIdsAFPWorkers()
int RunModeIdsAFPWorkers (void)
Workers version of the AF_PACKET processing.
Start N threads with each thread doing all the work.
Definition at line 860 of file runmode-af-packet.c.
References AFPPeersListInit(), ConfGet(), FatalError, RunModeInitialize(), RunModeSetLiveCaptureWorkers(), SC_ERR_FATAL, SCEnter, TimeModeSetLive(), and TM_ECODE_OK.
Referenced by RunModeIdsAFPRegister().
Variable Documentation
max_pending_packets
int max_pending_packets extern
Maximum packets to simultaneously process.
Definition at line 222 of file suricata.c.
Referenced by PacketPoolInit(), and PacketPoolPostRunmodes().