suricata: /Users/jlu/suricata/src/runmode-windivert.h File Reference
runmode-windivert.h File Reference
Functions
int RunModeIpsWinDivertAutoFp (void)
void RunModeIpsWinDivertRegister (void)
const char * RunModeIpsWinDivertGetDefaultMode (void)
Detailed Description
Author
Jacob Masen-Smith jacob.nosp@m.@eve.nosp@m.ngx.c.nosp@m.om
Definition in file runmode-windivert.h.
Function Documentation
RunModeIpsWinDivertAutoFp()
int RunModeIpsWinDivertAutoFp (void)
Definition at line 53 of file runmode-windivert.c.
References LiveDeviceHasNoStats(), RunModeInitialize(), RunModeSetIPSAutoFp(), SCEnter, and TimeModeSetLive().
Referenced by RunModeIpsWinDivertRegister().
RunModeIpsWinDivertGetDefaultMode()
const char * RunModeIpsWinDivertGetDefaultMode (void)
Definition at line 40 of file runmode-windivert.c.
Referenced by RunModeDispatch().
RunModeIpsWinDivertRegister()
void RunModeIpsWinDivertRegister (void)
Definition at line 45 of file runmode-windivert.c.
References RUNMODE_WINDIVERT, RunModeIpsWinDivertAutoFp(), and RunModeRegisterNewRunMode().