suricata: /Users/jlu/suricata/src/runmodes.h File Reference
runmodes.h File Reference
Enumerations
enum RunModes {
RUNMODE_UNKNOWN = 0 , RUNMODE_PCAP_DEV , RUNMODE_PCAP_FILE , RUNMODE_PFRING ,
RUNMODE_NFQ , RUNMODE_NFLOG , RUNMODE_IPFW , RUNMODE_ERF_FILE ,
RUNMODE_DAG , RUNMODE_AFP_DEV , RUNMODE_NETMAP , RUNMODE_DPDK ,
RUNMODE_UNITTEST , RUNMODE_NAPATECH , RUNMODE_UNIX_SOCKET , RUNMODE_WINDIVERT ,
RUNMODE_PLUGIN , RUNMODE_USER_MAX , RUNMODE_LIST_KEYWORDS , RUNMODE_LIST_APP_LAYERS ,
RUNMODE_LIST_RUNMODES , RUNMODE_PRINT_VERSION , RUNMODE_PRINT_BUILDINFO , RUNMODE_PRINT_USAGE ,
RUNMODE_DUMP_CONFIG , RUNMODE_CONF_TEST , RUNMODE_LIST_UNITTEST , RUNMODE_ENGINE_ANALYSIS ,
RUNMODE_DUMP_FEATURES , RUNMODE_MAX
}
Functions
char * RunmodeGetActive (void)
const char * RunModeGetMainMode (void)
void RunModeListRunmodes (void)
Lists all registered runmodes.
void RunModeDispatch (int, const char *, const char *capture_plugin_name, const char *capture_plugin_args)
void RunModeRegisterRunModes (void)
Register all runmodes in the engine.
void RunModeRegisterNewRunMode (enum RunModes, const char *, const char *, int(*RunModeFunc)(void))
Registers a new runmode.
void RunModeInitialize (void)
void RunModeInitializeOutputs (void)
void RunModeShutDown (void)
int RunModeOutputFileEnabled (void)
int RunModeOutputFiledataEnabled (void)
bool IsRunModeOffline (enum RunModes run_mode_to_check)
bool IsRunModeSystem (enum RunModes run_mode_to_check)
void RunModeEnablesBypassManager (void)
int RunModeNeedsBypassManager (void)
Variables
const char * thread_name_autofp
const char * thread_name_single
const char * thread_name_workers
const char * thread_name_verdict
const char * thread_name_flow_mgr
const char * thread_name_flow_bypass
const char * thread_name_flow_rec
const char * thread_name_unix_socket
const char * thread_name_detect_loader
const char * thread_name_counter_stats
const char * thread_name_counter_wakeup
int threading_set_cpu_affinity
float threading_detect_ratio
uint64_t threading_set_stack_size
int debuglog_enabled
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file runmodes.h.
Enumeration Type Documentation
RunModes
enum RunModes
Enumerator
RUNMODE_UNKNOWN
RUNMODE_PCAP_DEV
RUNMODE_PCAP_FILE
RUNMODE_PFRING
RUNMODE_NFQ
RUNMODE_NFLOG
RUNMODE_IPFW
RUNMODE_ERF_FILE
RUNMODE_DAG
RUNMODE_AFP_DEV
RUNMODE_NETMAP
RUNMODE_DPDK
RUNMODE_UNITTEST
RUNMODE_NAPATECH
RUNMODE_UNIX_SOCKET
RUNMODE_WINDIVERT
RUNMODE_PLUGIN
RUNMODE_USER_MAX
RUNMODE_LIST_KEYWORDS
RUNMODE_LIST_APP_LAYERS
RUNMODE_LIST_RUNMODES
RUNMODE_PRINT_VERSION
RUNMODE_PRINT_BUILDINFO
RUNMODE_PRINT_USAGE
RUNMODE_DUMP_CONFIG
RUNMODE_CONF_TEST
RUNMODE_LIST_UNITTEST
RUNMODE_ENGINE_ANALYSIS
RUNMODE_DUMP_FEATURES
RUNMODE_MAX
Definition at line 27 of file runmodes.h.
Function Documentation
IsRunModeOffline()
bool IsRunModeOffline (enum RunModes run_mode_to_check)
bool indicating if run mode is offline
Definition at line 545 of file runmodes.c.
References RUNMODE_CONF_TEST, RUNMODE_ENGINE_ANALYSIS, RUNMODE_ERF_FILE, RUNMODE_PCAP_FILE, and RUNMODE_UNIX_SOCKET.
Referenced by ConfUnixSocketIsEnable().
IsRunModeSystem()
bool IsRunModeSystem (enum RunModes run_mode_to_check)
Definition at line 532 of file runmodes.c.
References RUNMODE_ENGINE_ANALYSIS, RUNMODE_ERF_FILE, and RUNMODE_PCAP_FILE.
RunModeDispatch()
void RunModeDispatch (int runmode, const char * custom_mode, const char * capture_plugin_name, const char * capture_plugin_args)
Definition at line 305 of file runmodes.c.
References ConfGet(), FatalError, SCCapturePlugin_::GetDefaultMode, RUNMODE_AFP_DEV, RUNMODE_DAG, RUNMODE_DPDK, RUNMODE_ERF_FILE, RUNMODE_IPFW, RUNMODE_NAPATECH, RUNMODE_NETMAP, RUNMODE_NFLOG, RUNMODE_NFQ, RUNMODE_PCAP_DEV, RUNMODE_PCAP_FILE, RUNMODE_PFRING, RUNMODE_PLUGIN, RUNMODE_UNIX_SOCKET, RUNMODE_WINDIVERT, RunModeAFPGetDefaultMode(), RunModeDpdkGetDefaultMode(), RunModeErfDagGetDefaultMode(), RunModeErfFileGetDefaultMode(), RunModeFilePcapGetDefaultMode(), RunModeIdsGetDefaultMode(), RunModeIdsNflogGetDefaultMode(), RunModeIdsPfringGetDefaultMode(), RunModeIpsIPFWGetDefaultMode(), RunModeIpsNFQGetDefaultMode(), RunModeIpsWinDivertGetDefaultMode(), RunModeNapatechGetDefaultMode(), RunModeNetmapGetDefaultMode(), RunModeUnixSocketGetDefaultMode(), SC_ERR_FATAL, SC_ERR_PLUGIN, SC_ERR_RUNMODE, SCLogWarning, SCPluginFindCaptureByName(), SCStrdup, and unlikely.
RunModeEnablesBypassManager()
void RunModeEnablesBypassManager (void)
Definition at line 439 of file runmodes.c.
RunmodeGetActive()
char * RunmodeGetActive (void)
Return the running mode
The returned string must not be freed.
Returns
a string containing the current running mode
Definition at line 213 of file runmodes.c.
RunModeGetMainMode()
const char * RunModeGetMainMode (void)
Return the running mode
The returned string must not be freed.
Returns
a string containing the current running mode
Definition at line 225 of file runmodes.c.
References RunmodeGetCurrent().
RunModeInitialize()
void RunModeInitialize (void)
Initialize multithreading settings.
Definition at line 946 of file runmodes.c.
References AffinitySetupLoadFromConfig(), ConfGet(), ConfGetBool(), ConfGetFloat(), ConfGetNode(), FALSE, FatalError, ParseSizeStringU64(), SC_ERR_INVALID_ARGUMENT, SCLogDebug, threading_detect_ratio, threading_set_cpu_affinity, threading_set_stack_size, TRUE, and WarnInvalidConfEntry.
Referenced by RunModeErfFileAutoFp(), RunModeErfFileSingle(), RunModeFilePcapAutoFp(), RunModeFilePcapSingle(), RunModeIdsAFPAutoFp(), RunModeIdsAFPSingle(), RunModeIdsAFPWorkers(), RunModeIdsDpdkWorkers(), RunModeIdsErfDagAutoFp(), RunModeIdsErfDagSingle(), RunModeIdsErfDagWorkers(), RunModeIdsPcapAutoFp(), RunModeIdsPcapSingle(), RunModeIdsPcapWorkers(), RunModeIdsPfringAutoFp(), RunModeIdsPfringSingle(), RunModeIdsPfringWorkers(), RunModeIpsIPFWAutoFp(), RunModeIpsIPFWWorker(), RunModeIpsNFQAutoFp(), RunModeIpsNFQWorker(), and RunModeIpsWinDivertAutoFp().
RunModeInitializeOutputs()
void RunModeInitializeOutputs (void)
Initialize the output modules.
Definition at line 763 of file runmodes.c.
References ConfGetNode().
Referenced by PreRunPostPrivsDropInit().
RunModeListRunmodes()
void RunModeListRunmodes (void)
Lists all registered runmodes.
Definition at line 262 of file runmodes.c.
References RUNMODE_UNKNOWN, and RUNMODE_USER_MAX.
RunModeNeedsBypassManager()
int RunModeNeedsBypassManager (void)
Definition at line 444 of file runmodes.c.
RunModeOutputFiledataEnabled()
int RunModeOutputFiledataEnabled (void)
Definition at line 527 of file runmodes.c.
RunModeOutputFileEnabled()
int RunModeOutputFileEnabled (void)
Definition at line 522 of file runmodes.c.
RunModeRegisterNewRunMode()
void RunModeRegisterNewRunMode (enum RunModes runmode, const char * name, const char * description, int(*)(void) RunModeFunc)
Registers a new runmode.
Parameters
runmode Runmode type.
name Custom mode for this specific runmode type. Within each runmode type, each custom name is a primary key.
description Description for this runmode.
RunModeFunc The function to be run for this runmode.
Definition at line 460 of file runmodes.c.
Referenced by RunModeDpdkRegister(), RunModeErfDagRegister(), RunModeErfFileRegister(), RunModeFilePcapRegister(), RunModeIdsAFPRegister(), RunModeIdsNetmapRegister(), RunModeIdsNflogRegister(), RunModeIdsPcapRegister(), RunModeIdsPfringRegister(), RunModeIpsIPFWRegister(), RunModeIpsNFQRegister(), RunModeIpsWinDivertRegister(), RunModeNapatechRegister(), RunModeUnixSocketRegister(), and UtRunModeRegister().
RunModeRegisterRunModes()
void RunModeRegisterRunModes (void)
Register all runmodes in the engine.
Definition at line 235 of file runmodes.c.
Referenced by InitGlobal().
RunModeShutDown()
void RunModeShutDown (void)
Cleanup the run mode.
Definition at line 563 of file runmodes.c.
Variable Documentation
debuglog_enabled
int debuglog_enabled extern
Definition at line 73 of file runmodes.c.
thread_name_autofp
const char* thread_name_autofp extern
Definition at line 78 of file runmodes.c.
Referenced by RunModeErfFileAutoFp(), RunModeFilePcapAutoFp(), RunModeSetIPSAutoFp(), and TmThreadWaitOnThreadInit().
thread_name_counter_stats
const char* thread_name_counter_stats extern
Definition at line 87 of file runmodes.c.
thread_name_counter_wakeup
const char* thread_name_counter_wakeup extern
Definition at line 88 of file runmodes.c.
thread_name_detect_loader
const char* thread_name_detect_loader extern
Definition at line 86 of file runmodes.c.
thread_name_flow_bypass
const char* thread_name_flow_bypass extern
Definition at line 84 of file runmodes.c.
Referenced by BypassedFlowManagerThreadSpawn().
thread_name_flow_mgr
const char* thread_name_flow_mgr extern
Definition at line 82 of file runmodes.c.
Referenced by FlowDisableFlowManagerThread(), and TmThreadWaitOnThreadInit().
thread_name_flow_rec
const char* thread_name_flow_rec extern
Definition at line 83 of file runmodes.c.
Referenced by TmThreadWaitOnThreadInit().
thread_name_single
const char* thread_name_single extern
Definition at line 79 of file runmodes.c.
Referenced by RunModeErfFileSingle(), and RunModeFilePcapSingle().
thread_name_unix_socket
const char* thread_name_unix_socket extern
Definition at line 85 of file runmodes.c.
thread_name_verdict
const char* thread_name_verdict extern
Definition at line 81 of file runmodes.c.
Referenced by RunModeSetIPSAutoFp(), and TmThreadWaitOnThreadInit().
thread_name_workers
const char* thread_name_workers extern
Definition at line 80 of file runmodes.c.
Referenced by RunModeErfFileAutoFp(), RunModeFilePcapAutoFp(), RunModeIdsDpdkWorkers(), RunModeSetIPSAutoFp(), RunModeSetIPSWorker(), RunModeSetLiveCaptureAutoFp(), and TmThreadWaitOnThreadInit().
threading_detect_ratio
float threading_detect_ratio extern
Definition at line 941 of file runmodes.c.
Referenced by RunModeErfFileAutoFp(), RunModeFilePcapAutoFp(), RunModeInitialize(), and TmThreadsGetWorkerThreadMax().
threading_set_cpu_affinity
int threading_set_cpu_affinity extern
Definition at line 74 of file runmodes.c.
Referenced by RunModeErfFileAutoFp(), RunModeInitialize(), and TmThreadSetCPU().
threading_set_stack_size
uint64_t threading_set_stack_size extern
Definition at line 75 of file runmodes.c.
Referenced by RunModeInitialize(), and TmThreadSpawn().