suricata: /Users/jlu/suricata/src/runmode-erf-file.c File Reference
runmode-erf-file.c File Reference
#include "suricata-common.h"
#include "tm-threads.h"
#include "conf.h"
#include "runmodes.h"
#include "runmode-erf-file.h"
#include "output.h"
#include "detect-engine.h"
#include "util-debug.h"
#include "util-time.h"
#include "util-cpu.h"
#include "util-affinity.h"
#include "util-runmodes.h"
Functions
const char * RunModeErfFileGetDefaultMode (void)
void RunModeErfFileRegister (void)
int RunModeErfFileSingle (void)
int RunModeErfFileAutoFp (void)
Function Documentation
RunModeErfFileAutoFp()
int RunModeErfFileAutoFp (void)
Definition at line 108 of file runmode-erf-file.c.
References ConfGet(), FatalError, PRIO_LOW, PRIO_MEDIUM, RunmodeAutoFpCreatePickupQueuesString(), RunModeInitialize(), SC_ERR_FATAL, SCEnter, SCFree, SCLogDebug, SCLogInfo, SCReturnInt, thread_name_autofp, thread_name_workers, threading_detect_ratio, threading_set_cpu_affinity, TimeModeSetOffline(), TM_ECODE_OK, TM_QUEUE_NAME_MAX, TM_THREAD_NAME_MAX, TmModuleGetByName(), TmSlotSetFuncAppend(), TmThreadCreatePacketHandler(), TmThreadGetNbThreads(), TmThreadSetCPUAffinity(), TmThreadSetGroupName(), TmThreadSetThreadPriority(), TmThreadSpawn(), tv, UtilCpuGetNumProcessorsOnline(), and WORKER_CPU_SET.
Referenced by RunModeErfFileRegister().
RunModeErfFileGetDefaultMode()
const char * RunModeErfFileGetDefaultMode (void)
Definition at line 34 of file runmode-erf-file.c.
Referenced by RunModeDispatch().
RunModeErfFileRegister()
void RunModeErfFileRegister (void)
Definition at line 39 of file runmode-erf-file.c.
References RUNMODE_ERF_FILE, RunModeErfFileAutoFp(), RunModeErfFileSingle(), and RunModeRegisterNewRunMode().
RunModeErfFileSingle()
int RunModeErfFileSingle (void)
Definition at line 53 of file runmode-erf-file.c.
References ConfGet(), FatalError, RunModeInitialize(), SC_ERR_FATAL, SCEnter, SCLogInfo, SCReturnInt, thread_name_single, TimeModeSetOffline(), TM_ECODE_OK, TmModuleGetByName(), TmSlotSetFuncAppend(), TmThreadCreatePacketHandler(), TmThreadSpawn(), and tv.
Referenced by RunModeErfFileRegister().