suricata: /Users/jlu/suricata/src/runmode-erf-dag.c File Reference
runmode-erf-dag.c File Reference
#include "suricata-common.h"
#include "tm-threads.h"
#include "conf.h"
#include "runmodes.h"
#include "runmode-erf-dag.h"
#include "output.h"
#include "detect-engine.h"
#include "util-debug.h"
#include "util-time.h"
#include "util-cpu.h"
#include "util-affinity.h"
#include "util-runmodes.h"
Functions
const char * RunModeErfDagGetDefaultMode (void)
void RunModeErfDagRegister (void)
int RunModeIdsErfDagSingle (void)
int RunModeIdsErfDagAutoFp (void)
int RunModeIdsErfDagWorkers (void)
Function Documentation
RunModeErfDagGetDefaultMode()
const char * RunModeErfDagGetDefaultMode (void)
Definition at line 43 of file runmode-erf-dag.c.
Referenced by RunModeDispatch().
RunModeErfDagRegister()
void RunModeErfDagRegister (void)
Definition at line 48 of file runmode-erf-dag.c.
References RUNMODE_DAG, RunModeIdsErfDagAutoFp(), RunModeIdsErfDagSingle(), RunModeIdsErfDagWorkers(), and RunModeRegisterNewRunMode().
RunModeIdsErfDagAutoFp()
int RunModeIdsErfDagAutoFp (void)
Definition at line 95 of file runmode-erf-dag.c.
References RunModeInitialize(), RunModeSetLiveCaptureAutoFp(), SCEnter, and TimeModeSetLive().
Referenced by RunModeErfDagRegister().
RunModeIdsErfDagSingle()
int RunModeIdsErfDagSingle (void)
Definition at line 70 of file runmode-erf-dag.c.
References RunModeInitialize(), RunModeSetLiveCaptureSingle(), SCEnter, and TimeModeSetLive().
Referenced by RunModeErfDagRegister().
RunModeIdsErfDagWorkers()
int RunModeIdsErfDagWorkers (void)
Definition at line 120 of file runmode-erf-dag.c.
References RunModeInitialize(), RunModeSetLiveCaptureWorkers(), SCEnter, and TimeModeSetLive().
Referenced by RunModeErfDagRegister().