suricata: /Users/jlu/suricata/src/runmode-nfq.h File Reference
runmode-nfq.h File Reference
Functions
int RunModeIpsNFQAutoFp (void)
int RunModeIpsNFQWorker (void)
void RunModeIpsNFQRegister (void)
const char * RunModeIpsNFQGetDefaultMode (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file runmode-nfq.h.
Function Documentation
RunModeIpsNFQAutoFp()
int RunModeIpsNFQAutoFp (void)
Definition at line 59 of file runmode-nfq.c.
References LiveDeviceHasNoStats(), NFQGetThread(), RunModeInitialize(), RunModeSetIPSAutoFp(), SCEnter, and TimeModeSetLive().
Referenced by RunModeIpsNFQRegister().
RunModeIpsNFQGetDefaultMode()
const char * RunModeIpsNFQGetDefaultMode (void)
Definition at line 42 of file runmode-nfq.c.
Referenced by RunModeDispatch().
RunModeIpsNFQRegister()
void RunModeIpsNFQRegister (void)
Definition at line 47 of file runmode-nfq.c.
References RUNMODE_NFQ, RunModeIpsNFQAutoFp(), RunModeIpsNFQWorker(), and RunModeRegisterNewRunMode().
RunModeIpsNFQWorker()
int RunModeIpsNFQWorker (void)
Definition at line 79 of file runmode-nfq.c.
References LiveDeviceHasNoStats(), NFQGetThread(), RunModeInitialize(), RunModeSetIPSWorker(), SCEnter, and TimeModeSetLive().
Referenced by RunModeIpsNFQRegister().