suricata: /Users/jlu/suricata/src/runmode-napatech.c File Reference
runmode-napatech.c File Reference
#include "suricata-common.h"
#include "tm-threads.h"
#include "conf.h"
#include "runmodes.h"
#include "output.h"
#include "util-debug.h"
#include "util-time.h"
#include "util-cpu.h"
#include "util-byte.h"
#include "util-affinity.h"
#include "util-runmodes.h"
#include "util-device.h"
#include "util-napatech.h"
#include "runmode-napatech.h"
#include "source-napatech.h"
Macros
#define NT_RUNMODE_AUTOFP 1
#define NT_RUNMODE_WORKERS 2
#define MAX_STREAMS 256
Functions
uint16_t NapatechGetNumConfiguredStreams (void)
uint16_t NapatechGetNumFirstStream (void)
uint16_t NapatechGetNumLastStream (void)
bool NapatechIsAutoConfigEnabled (void)
bool NapatechUseHWBypass (void)
const char * RunModeNapatechGetDefaultMode (void)
void RunModeNapatechRegister (void)
int RunModeNapatechAutoFp (void)
int RunModeNapatechWorkers (void)
Detailed Description
Author
nPulse Technologies, LLC.
Matt Keeler mk@np.nosp@m.ulse.nosp@m.tech..nosp@m.com
Definition in file runmode-napatech.c.
Macro Definition Documentation
MAX_STREAMS
#define MAX_STREAMS 256
Definition at line 48 of file runmode-napatech.c.
NT_RUNMODE_AUTOFP
#define NT_RUNMODE_AUTOFP 1
Definition at line 41 of file runmode-napatech.c.
NT_RUNMODE_WORKERS
#define NT_RUNMODE_WORKERS 2
Definition at line 42 of file runmode-napatech.c.
Function Documentation
NapatechGetNumConfiguredStreams()
uint16_t NapatechGetNumConfiguredStreams (void)
Definition at line 55 of file runmode-napatech.c.
Referenced by NapatechStreamThreadExitStats().
NapatechGetNumFirstStream()
uint16_t NapatechGetNumFirstStream (void)
Definition at line 60 of file runmode-napatech.c.
NapatechGetNumLastStream()
uint16_t NapatechGetNumLastStream (void)
Definition at line 65 of file runmode-napatech.c.
NapatechIsAutoConfigEnabled()
bool NapatechIsAutoConfigEnabled (void)
Definition at line 70 of file runmode-napatech.c.
Referenced by NapatechGetStreamConfig().
NapatechUseHWBypass()
bool NapatechUseHWBypass (void)
Definition at line 75 of file runmode-napatech.c.
RunModeNapatechAutoFp()
int RunModeNapatechAutoFp (void)
Definition at line 289 of file runmode-napatech.c.
RunModeNapatechGetDefaultMode()
const char * RunModeNapatechGetDefaultMode (void)
Definition at line 82 of file runmode-napatech.c.
Referenced by RunModeDispatch().
RunModeNapatechRegister()
void RunModeNapatechRegister (void)
Definition at line 87 of file runmode-napatech.c.
References RUNMODE_NAPATECH, RunModeNapatechWorkers(), and RunModeRegisterNewRunMode().
RunModeNapatechWorkers()
int RunModeNapatechWorkers (void)
Definition at line 294 of file runmode-napatech.c.
Referenced by RunModeNapatechRegister().