suricata: /Users/jlu/suricata/src/runmodes.c File Reference
runmodes.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "detect-engine.h"
#include "detect-engine-mpm.h"
#include "app-layer-parser.h"
#include "tm-threads.h"
#include "util-debug.h"
#include "util-time.h"
#include "util-cpu.h"
#include "util-byte.h"
#include "util-affinity.h"
#include "conf.h"
#include "queue.h"
#include "runmodes.h"
#include "runmode-af-packet.h"
#include "runmode-dpdk.h"
#include "runmode-erf-dag.h"
#include "runmode-erf-file.h"
#include "runmode-ipfw.h"
#include "runmode-napatech.h"
#include "runmode-netmap.h"
#include "runmode-nflog.h"
#include "runmode-nfq.h"
#include "runmode-pcap.h"
#include "runmode-pcap-file.h"
#include "runmode-pfring.h"
#include "runmode-unix-socket.h"
#include "runmode-windivert.h"
#include "util-unittest.h"
#include "util-misc.h"
#include "util-plugin.h"
#include "output.h"
#include "alert-fastlog.h"
#include "alert-debuglog.h"
#include "log-httplog.h"
#include "source-pfring.h"
#include "tmqh-flow.h"
#include "flow-manager.h"
#include "flow-bypass.h"
#include "counters.h"
#include "suricata-plugin.h"
Data Structures
struct RunMode_
Holds description for a runmode.
struct RunModes_
struct OutputFreeList_
Typedefs
typedef struct RunMode_ RunMode
Holds description for a runmode.
typedef struct RunModes_ RunModes
typedef struct OutputFreeList_ OutputFreeList
Functions
char * RunmodeGetActive (void)
const char * RunModeGetMainMode (void)
void RunModeRegisterRunModes (void)
Register all runmodes in the engine.
void RunModeListRunmodes (void)
Lists all registered runmodes.
void RunModeDispatch (int runmode, const char *custom_mode, const char *capture_plugin_name, const char *capture_plugin_args)
void RunModeEnablesBypassManager (void)
int RunModeNeedsBypassManager (void)
void RunModeRegisterNewRunMode (enum RunModes runmode, const char *name, const char *description, int(*RunModeFunc)(void))
Registers a new runmode.
int RunModeOutputFileEnabled (void)
int RunModeOutputFiledataEnabled (void)
bool IsRunModeSystem (enum RunModes run_mode_to_check)
bool IsRunModeOffline (enum RunModes run_mode_to_check)
void RunModeShutDown (void)
void RunModeInitializeOutputs (void)
void RunModeInitialize (void)
Variables
int debuglog_enabled = 0
int threading_set_cpu_affinity = FALSE
uint64_t threading_set_stack_size = 0
const char * thread_name_autofp = "RX"
const char * thread_name_single = "W"
const char * thread_name_workers = "W"
const char * thread_name_verdict = "TX"
const char * thread_name_flow_mgr = "FM"
const char * thread_name_flow_rec = "FR"
const char * thread_name_flow_bypass = "FB"
const char * thread_name_unix_socket = "US"
const char * thread_name_detect_loader = "DL"
const char * thread_name_counter_stats = "CS"
const char * thread_name_counter_wakeup = "CW"
float threading_detect_ratio = 1
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Pre-cooked threading runmodes.
Definition in file runmodes.c.
Typedef Documentation
OutputFreeList
typedef struct OutputFreeList_ OutputFreeList
RunMode
typedef struct RunMode_ RunMode
Holds description for a runmode.
RunModes
typedef struct RunModes_ RunModes
Function Documentation
IsRunModeOffline()
bool IsRunModeOffline (enum RunModes run_mode_to_check)
bool indicating if run mode is offline
Definition at line 545 of file runmodes.c.
References RUNMODE_CONF_TEST, RUNMODE_ENGINE_ANALYSIS, RUNMODE_ERF_FILE, RUNMODE_PCAP_FILE, and RUNMODE_UNIX_SOCKET.
Referenced by ConfUnixSocketIsEnable().
IsRunModeSystem()
bool IsRunModeSystem (enum RunModes run_mode_to_check)
Definition at line 532 of file runmodes.c.
References RUNMODE_ENGINE_ANALYSIS, RUNMODE_ERF_FILE, and RUNMODE_PCAP_FILE.
RunModeDispatch()
void RunModeDispatch (int runmode, const char * custom_mode, const char * capture_plugin_name, const char * capture_plugin_args)
Definition at line 305 of file runmodes.c.
References ConfGet(), FatalError, SCCapturePlugin_::GetDefaultMode, RUNMODE_AFP_DEV, RUNMODE_DAG, RUNMODE_DPDK, RUNMODE_ERF_FILE, RUNMODE_IPFW, RUNMODE_NAPATECH, RUNMODE_NETMAP, RUNMODE_NFLOG, RUNMODE_NFQ, RUNMODE_PCAP_DEV, RUNMODE_PCAP_FILE, RUNMODE_PFRING, RUNMODE_PLUGIN, RUNMODE_UNIX_SOCKET, RUNMODE_WINDIVERT, RunModeAFPGetDefaultMode(), RunModeDpdkGetDefaultMode(), RunModeErfDagGetDefaultMode(), RunModeErfFileGetDefaultMode(), RunModeFilePcapGetDefaultMode(), RunModeIdsGetDefaultMode(), RunModeIdsNflogGetDefaultMode(), RunModeIdsPfringGetDefaultMode(), RunModeIpsIPFWGetDefaultMode(), RunModeIpsNFQGetDefaultMode(), RunModeIpsWinDivertGetDefaultMode(), RunModeNapatechGetDefaultMode(), RunModeNetmapGetDefaultMode(), RunModeUnixSocketGetDefaultMode(), SC_ERR_FATAL, SC_ERR_PLUGIN, SC_ERR_RUNMODE, SCLogWarning, SCPluginFindCaptureByName(), SCStrdup, and unlikely.
RunModeEnablesBypassManager()
void RunModeEnablesBypassManager (void)
Definition at line 439 of file runmodes.c.
RunmodeGetActive()
char * RunmodeGetActive (void)
Return the running mode
The returned string must not be freed.
Returns
a string containing the current running mode
Definition at line 213 of file runmodes.c.
RunModeGetMainMode()
const char * RunModeGetMainMode (void)
Return the running mode
The returned string must not be freed.
Returns
a string containing the current running mode
Definition at line 225 of file runmodes.c.
References RunmodeGetCurrent().
RunModeInitialize()
void RunModeInitialize (void)
Initialize multithreading settings.
Definition at line 946 of file runmodes.c.
References AffinitySetupLoadFromConfig(), ConfGet(), ConfGetBool(), ConfGetFloat(), ConfGetNode(), FALSE, FatalError, ParseSizeStringU64(), SC_ERR_INVALID_ARGUMENT, SCLogDebug, threading_detect_ratio, threading_set_cpu_affinity, threading_set_stack_size, TRUE, and WarnInvalidConfEntry.
Referenced by RunModeErfFileAutoFp(), RunModeErfFileSingle(), RunModeFilePcapAutoFp(), RunModeFilePcapSingle(), RunModeIdsAFPAutoFp(), RunModeIdsAFPSingle(), RunModeIdsAFPWorkers(), RunModeIdsDpdkWorkers(), RunModeIdsErfDagAutoFp(), RunModeIdsErfDagSingle(), RunModeIdsErfDagWorkers(), RunModeIdsPcapAutoFp(), RunModeIdsPcapSingle(), RunModeIdsPcapWorkers(), RunModeIdsPfringAutoFp(), RunModeIdsPfringSingle(), RunModeIdsPfringWorkers(), RunModeIpsIPFWAutoFp(), RunModeIpsIPFWWorker(), RunModeIpsNFQAutoFp(), RunModeIpsNFQWorker(), and RunModeIpsWinDivertAutoFp().
RunModeInitializeOutputs()
void RunModeInitializeOutputs (void)
Initialize the output modules.
Definition at line 763 of file runmodes.c.
References ConfGetNode().
Referenced by PreRunPostPrivsDropInit().
RunModeListRunmodes()
void RunModeListRunmodes (void)
Lists all registered runmodes.
Definition at line 262 of file runmodes.c.
References RUNMODE_UNKNOWN, and RUNMODE_USER_MAX.
RunModeNeedsBypassManager()
int RunModeNeedsBypassManager (void)
Definition at line 444 of file runmodes.c.
RunModeOutputFiledataEnabled()
int RunModeOutputFiledataEnabled (void)
Definition at line 527 of file runmodes.c.
RunModeOutputFileEnabled()
int RunModeOutputFileEnabled (void)
Definition at line 522 of file runmodes.c.
RunModeRegisterNewRunMode()
void RunModeRegisterNewRunMode (enum RunModes runmode, const char * name, const char * description, int(*)(void) RunModeFunc)
Registers a new runmode.
Parameters
runmode Runmode type.
name Custom mode for this specific runmode type. Within each runmode type, each custom name is a primary key.
description Description for this runmode.
RunModeFunc The function to be run for this runmode.
Definition at line 460 of file runmodes.c.
Referenced by RunModeDpdkRegister(), RunModeErfDagRegister(), RunModeErfFileRegister(), RunModeFilePcapRegister(), RunModeIdsAFPRegister(), RunModeIdsNetmapRegister(), RunModeIdsNflogRegister(), RunModeIdsPcapRegister(), RunModeIdsPfringRegister(), RunModeIpsIPFWRegister(), RunModeIpsNFQRegister(), RunModeIpsWinDivertRegister(), RunModeNapatechRegister(), RunModeUnixSocketRegister(), and UtRunModeRegister().
RunModeRegisterRunModes()
void RunModeRegisterRunModes (void)
Register all runmodes in the engine.
Definition at line 235 of file runmodes.c.
Referenced by InitGlobal().
RunModeShutDown()
void RunModeShutDown (void)
Cleanup the run mode.
Definition at line 563 of file runmodes.c.
Variable Documentation
debuglog_enabled
int debuglog_enabled = 0
Definition at line 73 of file runmodes.c.
thread_name_autofp
const char* thread_name_autofp = "RX"
Definition at line 78 of file runmodes.c.
Referenced by RunModeErfFileAutoFp(), RunModeFilePcapAutoFp(), RunModeSetIPSAutoFp(), and TmThreadWaitOnThreadInit().
thread_name_counter_stats
const char* thread_name_counter_stats = "CS"
Definition at line 87 of file runmodes.c.
thread_name_counter_wakeup
const char* thread_name_counter_wakeup = "CW"
Definition at line 88 of file runmodes.c.
thread_name_detect_loader
const char* thread_name_detect_loader = "DL"
Definition at line 86 of file runmodes.c.
thread_name_flow_bypass
const char* thread_name_flow_bypass = "FB"
Definition at line 84 of file runmodes.c.
Referenced by BypassedFlowManagerThreadSpawn().
thread_name_flow_mgr
const char* thread_name_flow_mgr = "FM"
Definition at line 82 of file runmodes.c.
Referenced by FlowDisableFlowManagerThread(), and TmThreadWaitOnThreadInit().
thread_name_flow_rec
const char* thread_name_flow_rec = "FR"
Definition at line 83 of file runmodes.c.
Referenced by TmThreadWaitOnThreadInit().
thread_name_single
const char* thread_name_single = "W"
Definition at line 79 of file runmodes.c.
Referenced by RunModeErfFileSingle(), and RunModeFilePcapSingle().
thread_name_unix_socket
const char* thread_name_unix_socket = "US"
Definition at line 85 of file runmodes.c.
thread_name_verdict
const char* thread_name_verdict = "TX"
Definition at line 81 of file runmodes.c.
Referenced by RunModeSetIPSAutoFp(), and TmThreadWaitOnThreadInit().
thread_name_workers
const char* thread_name_workers = "W"
Definition at line 80 of file runmodes.c.
Referenced by RunModeErfFileAutoFp(), RunModeFilePcapAutoFp(), RunModeIdsDpdkWorkers(), RunModeSetIPSAutoFp(), RunModeSetIPSWorker(), RunModeSetLiveCaptureAutoFp(), and TmThreadWaitOnThreadInit().
threading_detect_ratio
float threading_detect_ratio = 1
Definition at line 941 of file runmodes.c.
Referenced by RunModeErfFileAutoFp(), RunModeFilePcapAutoFp(), RunModeInitialize(), and TmThreadsGetWorkerThreadMax().
threading_set_cpu_affinity
int threading_set_cpu_affinity = FALSE
Definition at line 74 of file runmodes.c.
Referenced by RunModeErfFileAutoFp(), RunModeInitialize(), and TmThreadSetCPU().
threading_set_stack_size
uint64_t threading_set_stack_size = 0
Definition at line 75 of file runmodes.c.
Referenced by RunModeInitialize(), and TmThreadSpawn().