suricata: /Users/jlu/suricata/src/runmode-ipfw.h File Reference
runmode-ipfw.h File Reference
Functions
int RunModeIpsIPFWAutoFp (void)
int RunModeIpsIPFWWorker (void)
void RunModeIpsIPFWRegister (void)
const char * RunModeIpsIPFWGetDefaultMode (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file runmode-ipfw.h.
Function Documentation
RunModeIpsIPFWAutoFp()
int RunModeIpsIPFWAutoFp (void)
Definition at line 62 of file runmode-ipfw.c.
References IPFWGetThread(), LiveDeviceHasNoStats(), RunModeInitialize(), RunModeSetIPSAutoFp(), SCEnter, and TimeModeSetLive().
Referenced by RunModeIpsIPFWRegister().
RunModeIpsIPFWGetDefaultMode()
const char * RunModeIpsIPFWGetDefaultMode (void)
Definition at line 44 of file runmode-ipfw.c.
Referenced by RunModeDispatch().
RunModeIpsIPFWRegister()
void RunModeIpsIPFWRegister (void)
Definition at line 49 of file runmode-ipfw.c.
References RUNMODE_IPFW, RunModeIpsIPFWAutoFp(), RunModeIpsIPFWWorker(), and RunModeRegisterNewRunMode().
RunModeIpsIPFWWorker()
int RunModeIpsIPFWWorker (void)
Definition at line 82 of file runmode-ipfw.c.
References IPFWGetThread(), LiveDeviceHasNoStats(), RunModeInitialize(), RunModeSetIPSWorker(), SCEnter, and TimeModeSetLive().
Referenced by RunModeIpsIPFWRegister().