suricata: /Users/jlu/suricata/src/runmode-napatech.h File Reference
runmode-napatech.h File Reference
#include <nt.h>
Functions
int RunModeNapatechAutoFp (void)
int RunModeNapatechWorkers (void)
void RunModeNapatechRegister (void)
const char * RunModeNapatechGetDefaultMode (void)
uint16_t NapatechGetNumConfiguredStreams (void)
uint16_t NapatechGetNumFirstStream (void)
uint16_t NapatechGetNumLastStream (void)
bool NapatechIsAutoConfigEnabled (void)
bool NapatechUseHWBypass (void)
Detailed Description
\autor nPulse Technologies, LLC.
Author
Matt Keeler mk@np.nosp@m.ulse.nosp@m.tech..nosp@m.com
Definition in file runmode-napatech.h.
Function Documentation
NapatechGetNumConfiguredStreams()
uint16_t NapatechGetNumConfiguredStreams (void)
Definition at line 55 of file runmode-napatech.c.
Referenced by NapatechStreamThreadExitStats().
NapatechGetNumFirstStream()
uint16_t NapatechGetNumFirstStream (void)
Definition at line 60 of file runmode-napatech.c.
NapatechGetNumLastStream()
uint16_t NapatechGetNumLastStream (void)
Definition at line 65 of file runmode-napatech.c.
NapatechIsAutoConfigEnabled()
bool NapatechIsAutoConfigEnabled (void)
Definition at line 70 of file runmode-napatech.c.
Referenced by NapatechGetStreamConfig().
NapatechUseHWBypass()
bool NapatechUseHWBypass (void)
Definition at line 75 of file runmode-napatech.c.
RunModeNapatechAutoFp()
int RunModeNapatechAutoFp (void)
Definition at line 289 of file runmode-napatech.c.
RunModeNapatechGetDefaultMode()
const char * RunModeNapatechGetDefaultMode (void)
Definition at line 82 of file runmode-napatech.c.
Referenced by RunModeDispatch().
RunModeNapatechRegister()
void RunModeNapatechRegister (void)
Definition at line 87 of file runmode-napatech.c.
References RUNMODE_NAPATECH, RunModeNapatechWorkers(), and RunModeRegisterNewRunMode().
RunModeNapatechWorkers()
int RunModeNapatechWorkers (void)
Definition at line 294 of file runmode-napatech.c.
Referenced by RunModeNapatechRegister().