suricata: /Users/jlu/suricata/src/runmode-unittests.c File Reference
runmode-unittests.c File Reference
#include "suricata-common.h"
#include "util-unittest.h"
#include "runmode-unittests.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-address.h"
#include "detect-engine-proto.h"
#include "detect-engine-port.h"
#include "detect-engine-mpm.h"
#include "detect-engine-sigorder.h"
#include "detect-engine-payload.h"
#include "detect-engine-dcepayload.h"
#include "detect-engine-state.h"
#include "detect-engine-tag.h"
#include "detect-engine-enip.h"
#include "detect-fast-pattern.h"
#include "flow.h"
#include "flow-timeout.h"
#include "flow-manager.h"
#include "flow-var.h"
#include "flow-bit.h"
#include "pkt-var.h"
#include "host.h"
#include "host-bit.h"
#include "ippair.h"
#include "ippair-bit.h"
#include "unix-manager.h"
#include "stream-tcp.h"
#include "app-layer-detect-proto.h"
#include "app-layer-parser.h"
#include "app-layer.h"
#include "app-layer-htp.h"
#include "app-layer-ftp.h"
#include "app-layer-ssl.h"
#include "app-layer-ssh.h"
#include "app-layer-smtp.h"
#include "util-action.h"
#include "util-radix-tree.h"
#include "util-host-os-info.h"
#include "util-cidr.h"
#include "util-unittest-helper.h"
#include "util-time.h"
#include "util-rule-vars.h"
#include "util-classification-config.h"
#include "util-threshold-config.h"
#include "util-reference-config.h"
#include "util-profiling.h"
#include "util-magic.h"
#include "util-memcmp.h"
#include "util-misc.h"
#include "util-signal.h"
#include "reputation.h"
#include "util-atomic.h"
#include "util-spm.h"
#include "util-hash.h"
#include "util-hashlist.h"
#include "util-bloomfilter.h"
#include "util-bloomfilter-counting.h"
#include "util-pool.h"
#include "util-byte.h"
#include "util-proto-name.h"
#include "util-macset.h"
#include "util-memrchr.h"
#include "util-mpm-ac.h"
#include "util-mpm-hs.h"
#include "conf.h"
#include "conf-yaml-loader.h"
#include "tmqh-flow.h"
#include "defrag.h"
#include "detect-engine-siggroup.h"
#include "util-streaming-buffer.h"
#include "util-lua.h"
#include "util-luajit.h"
#include "tm-modules.h"
#include "tmqh-packetpool.h"
#include "decode-chdlc.h"
#include "decode-geneve.h"
#include "decode-nsh.h"
#include "decode-raw.h"
#include "decode-vntag.h"
#include "decode-vxlan.h"
Functions
void TmqhSetup (void)
void RunUnittests (int list_unittests, const char *regex_arg)
Detailed Description
Author
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Definition in file runmode-unittests.c.
Function Documentation
RunUnittests()
void RunUnittests (int list_unittests, const char * regex_arg)
Run or list unittests
Parameters
list_unittests If set to 1, list unittests. Run them if set to 0.
regex_arg A regular expression to select unittests to run
This function is terminal and will call exit after being called.
Definition at line 229 of file runmode-unittests.c.
References AppLayerHtpEnableRequestBodyCallback(), AppLayerHtpNeedFileInspection(), AppLayerSetup(), default_packet_size, DEFAULT_PACKET_SIZE, GlobalsInitPreConfig(), HostBitInitCtx(), MpmTableSetup(), regex_arg, RegisterAllModules(), SCClassConfInit(), SCReferenceConfInit(), SigTableSetup(), SpmTableSetup(), StorageFinalize(), StorageInit(), TagInitCtx(), TmqhSetup(), UtInitialize(), and UtRunSelftest().
TmqhSetup()
void TmqhSetup (void)
Definition at line 39 of file tm-queuehandlers.c.
References tmqh_table, TmqhFlowRegister(), TmqhPacketpoolRegister(), and TmqhSimpleRegister().
Referenced by RunUnittests().