suricata: /Users/jlu/suricata/src/runmode-dpdk.h File Reference
runmode-dpdk.h File Reference
Data Structures
struct DPDKIfaceConfigAttributes_
Typedefs
typedef struct DPDKIfaceConfigAttributes_ DPDKIfaceConfigAttributes
Functions
int RunModeIdsDpdkWorkers (void)
Workers version of the DPDK processing.
void RunModeDpdkRegister (void)
const char * RunModeDpdkGetDefaultMode (void)
Detailed Description
Author
Lukas Sismis lukas.nosp@m..sis.nosp@m.mis@g.nosp@m.mail.nosp@m..com
Definition in file runmode-dpdk.h.
Typedef Documentation
DPDKIfaceConfigAttributes
typedef struct DPDKIfaceConfigAttributes_ DPDKIfaceConfigAttributes
Function Documentation
RunModeDpdkGetDefaultMode()
const char * RunModeDpdkGetDefaultMode (void)
Definition at line 1313 of file runmode-dpdk.c.
Referenced by RunModeDispatch().
RunModeDpdkRegister()
void RunModeDpdkRegister (void)
Definition at line 1318 of file runmode-dpdk.c.
References RUNMODE_DPDK, RunModeIdsDpdkWorkers(), and RunModeRegisterNewRunMode().
RunModeIdsDpdkWorkers()
int RunModeIdsDpdkWorkers (void)
Workers version of the DPDK processing.
Start N threads with each thread doing all the work.
Definition at line 1332 of file runmode-dpdk.c.
References FatalError, RunModeInitialize(), RunModeSetLiveCaptureWorkers(), SC_ERR_FATAL, SCEnter, SCLogDebug, SCReturnInt, thread_name_workers, and TimeModeSetLive().
Referenced by RunModeDpdkRegister().