suricata: /Users/jlu/suricata/src/source-pfring.h File Reference
source-pfring.h File Reference
Data Structures
struct PfringIfaceConfig_
struct PfringPacketVars_
per packet Pfring vars
Macros
#define PFRING_IFACE_NAME_LENGTH 48
#define PFRING_CONF_FLAGS_CLUSTER (1 << 0)
#define PFRING_CONF_FLAGS_BYPASS (1 << 1)
#define CLUSTER_FLOW 0
#define CLUSTER_ROUND_ROBIN 1
#define CLUSTER_FLOW_5_TUPLE 4
Typedefs
typedef struct PfringThreadVars_ PfringThreadVars
typedef struct PfringIfaceConfig_ PfringIfaceConfig
typedef struct PfringPacketVars_ PfringPacketVars
per packet Pfring vars
Functions
void TmModuleReceivePfringRegister (void)
Registration Function for RecievePfring.
void TmModuleDecodePfringRegister (void)
Registration Function for DecodePfring.
int PfringConfGetThreads (void)
void PfringLoadConfig (void)
Detailed Description
Author
William Metcalf willi.nosp@m.am.m.nosp@m.etcal.nosp@m.f@gm.nosp@m.ail.c.nosp@m.om
Definition in file source-pfring.h.
Macro Definition Documentation
CLUSTER_FLOW
#define CLUSTER_FLOW 0
Definition at line 73 of file source-pfring.h.
CLUSTER_FLOW_5_TUPLE
#define CLUSTER_FLOW_5_TUPLE 4
Definition at line 75 of file source-pfring.h.
CLUSTER_ROUND_ROBIN
#define CLUSTER_ROUND_ROBIN 1
Definition at line 74 of file source-pfring.h.
PFRING_CONF_FLAGS_BYPASS
#define PFRING_CONF_FLAGS_BYPASS (1 << 1)
Definition at line 33 of file source-pfring.h.
PFRING_CONF_FLAGS_CLUSTER
#define PFRING_CONF_FLAGS_CLUSTER (1 << 0)
Definition at line 32 of file source-pfring.h.
PFRING_IFACE_NAME_LENGTH
#define PFRING_IFACE_NAME_LENGTH 48
Definition at line 27 of file source-pfring.h.
Typedef Documentation
PfringIfaceConfig
typedef struct PfringIfaceConfig_ PfringIfaceConfig
PfringPacketVars
typedef struct PfringPacketVars_ PfringPacketVars
per packet Pfring vars
This structure is used to pass packet metadata in callbacks.
PfringThreadVars
typedef struct PfringThreadVars_ PfringThreadVars
Definition at line 29 of file source-pfring.h.
Function Documentation
PfringConfGetThreads()
int PfringConfGetThreads (void)
PfringLoadConfig()
void PfringLoadConfig (void)
TmModuleDecodePfringRegister()
void TmModuleDecodePfringRegister (void)
Registration Function for DecodePfring.
Todo:
Unit tests are needed for this module.
Definition at line 178 of file source-pfring.c.
References DecodePfring(), DecodePfringThreadDeinit(), DecodePfringThreadInit(), TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_DECODE_TM, TMM_DECODEPFRING, and tmm_modules.
Referenced by RegisterAllModules().
TmModuleReceivePfringRegister()
void TmModuleReceivePfringRegister (void)
Registration Function for RecievePfring.
Todo:
Unit tests are needed for this module.
Definition at line 162 of file source-pfring.c.
References TmModule_::flags, TmModule_::Func, TmModule_::name, PfringBreakLoop(), TmModule_::PktAcqBreakLoop, TmModule_::PktAcqLoop, ReceivePfringLoop(), ReceivePfringThreadDeinit(), ReceivePfringThreadExitStats(), ReceivePfringThreadInit(), TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_RECEIVE_TM, tmm_modules, and TMM_RECEIVEPFRING.
Referenced by RegisterAllModules().