suricata: /Users/jlu/suricata/src/source-nfq.h File Reference
source-nfq.h File Reference
#include "threads.h"
#include <linux/netfilter.h>
#include <libnetfilter_queue/libnetfilter_queue.h>
Data Structures
struct NFQPacketVars_
struct NFQQueueVars_
struct NFQGlobalVars_
Macros
#define NFQ_MAX_QUEUE 65535
Typedefs
typedef struct NFQPacketVars_ NFQPacketVars
typedef struct NFQQueueVars_ NFQQueueVars
typedef struct NFQGlobalVars_ NFQGlobalVars
Functions
void NFQInitConfig (bool quiet)
To initialize the NFQ global configuration data.
int NFQRegisterQueue (const uint16_t number)
Add a single Netfilter queue.
int NFQParseAndRegisterQueues (const char *queues)
Parses and adds Netfilter queue(s).
int NFQGetQueueCount (void)
void * NFQGetQueue (int number)
Get a pointer to the NFQ queue at index.
int NFQGetQueueNum (int number)
void * NFQGetThread (int number)
Get a pointer to the NFQ thread at index.
void NFQContextsClean (void)
Clean global contexts. Must be called on exit.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file source-nfq.h.
Macro Definition Documentation
NFQ_MAX_QUEUE
#define NFQ_MAX_QUEUE 65535
Definition at line 34 of file source-nfq.h.
Typedef Documentation
NFQGlobalVars
typedef struct NFQGlobalVars_ NFQGlobalVars
NFQPacketVars
typedef struct NFQPacketVars_ NFQPacketVars
NFQQueueVars
typedef struct NFQQueueVars_ NFQQueueVars
Function Documentation
NFQContextsClean()
void NFQContextsClean (void)
Clean global contexts. Must be called on exit.
Definition at line 1277 of file source-nfq.c.
NFQGetQueue()
void * NFQGetQueue (int number)
Get a pointer to the NFQ queue at index.
Parameters
number idx of the queue in our array
Return values
ptr pointer to the NFQThreadVars at index
NULL on error
Definition at line 926 of file source-nfq.c.
References unlikely.
NFQGetQueueCount()
int NFQGetQueueCount (void)
NFQGetQueueNum()
int NFQGetQueueNum (int number)
NFQGetThread()
void * NFQGetThread (int number)
Get a pointer to the NFQ thread at index.
This function is temporary used as configuration parser.
Parameters
number idx of the queue in our array
Return values
ptr pointer to the NFQThreadVars at index
NULL on error
Definition at line 944 of file source-nfq.c.
References unlikely.
Referenced by RunModeIpsNFQAutoFp(), and RunModeIpsNFQWorker().
NFQInitConfig()
void NFQInitConfig (bool quiet)
To initialize the NFQ global configuration data.
Parameters
quiet It tells the mode of operation, if it is TRUE nothing will be get printed.
Definition at line 205 of file source-nfq.c.
References NFQCnf_::batchcount, NFQCnf_::bypass_mark, NFQCnf_::bypass_mask, ConfGet(), ConfGetBool(), ConfGetInt(), FatalError, NFQCnf_::flags, NFQCnf_::mark, NFQCnf_::mask, NFQCnf_::mode, NFQCnf_::next_queue, NFQ_ACCEPT_MODE, nfq_config, NFQ_FLAG_FAIL_OPEN, NFQ_REPEAT_MODE, NFQ_ROUTE_MODE, SC_ERR_FATAL, SC_ERR_INVALID_ARGUMENT, SC_ERR_NFQ_NOSUPPORT, SCLogDebug, SCLogError, SCLogInfo, and SCLogWarning.
NFQParseAndRegisterQueues()
int NFQParseAndRegisterQueues (const char * queues)
Parses and adds Netfilter queue(s).
Parameters
string with the queue number or range
Return values
0 on success.
-1 on failure.
Definition at line 863 of file source-nfq.c.
References SC_ERR_INVALID_ARGUMENT, SCLogError, and SCRealloc.
NFQRegisterQueue()
int NFQRegisterQueue (const uint16_t number)
Add a single Netfilter queue.
Parameters
string with the queue number
Return values
0 on success.
-1 on failure.
Definition at line 804 of file source-nfq.c.
References UtilCpuGetNumProcessorsOnline().