suricata: /Users/jlu/suricata/src/source-nflog.c File Reference
source-nflog.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "packet-queue.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "tm-modules.h"
#include "tm-queuehandlers.h"
#include "tmqh-packetpool.h"
#include "runmodes.h"
#include "util-error.h"
#include "util-device.h"
#include "util-datalink.h"
Functions
TmEcode NoNFLOGSupportExit (ThreadVars *, const void *, void **)
void TmModuleReceiveNFLOGRegister (void)
void TmModuleDecodeNFLOGRegister (void)
Detailed Description
Author
Giuseppe Longo giuse.nosp@m.ppel.nosp@m.ng@gm.nosp@m.ail..nosp@m.com
Netfilter's netfilter_log support
Definition in file source-nflog.c.
Function Documentation
NoNFLOGSupportExit()
TmEcode NoNFLOGSupportExit (ThreadVars * tv, const void * initdata, void ** data)
Handle the case where no NFLOG support is compiled in.
Definition at line 61 of file source-nflog.c.
References ThreadVars_::name, SC_ERR_NFLOG_NOSUPPORT, SCLogError, and tv.
Referenced by TmModuleDecodeNFLOGRegister(), and TmModuleReceiveNFLOGRegister().
TmModuleDecodeNFLOGRegister()
void TmModuleDecodeNFLOGRegister (void)
Definition at line 55 of file source-nflog.c.
References TmModule_::name, NoNFLOGSupportExit(), TmModule_::ThreadInit, TMM_DECODENFLOG, and tmm_modules.
Referenced by RegisterAllModules().
TmModuleReceiveNFLOGRegister()
void TmModuleReceiveNFLOGRegister (void)
Definition at line 49 of file source-nflog.c.
References TmModule_::name, NoNFLOGSupportExit(), TmModule_::ThreadInit, tmm_modules, and TMM_RECEIVENFLOG.
Referenced by RegisterAllModules().