suricata: /Users/jlu/suricata/src/source-windivert.c File Reference
source-windivert.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "tm-threads.h"
#include "util-byte.h"
#include "util-debug.h"
#include "util-device.h"
#include "util-error.h"
#include "util-ioctl.h"
#include "util-privs.h"
#include "util-unittest.h"
#include "runmodes.h"
#include "queue.h"
#include "source-windivert-prototypes.h"
#include "source-windivert.h"
Functions
TmEcode NoWinDivertSupportExit (ThreadVars *, const void *, void **)
void TmModuleReceiveWinDivertRegister (void)
void TmModuleVerdictWinDivertRegister (void)
void TmModuleDecodeWinDivertRegister (void)
Detailed Description
Author
Jacob Masen-Smith jacob.nosp@m.@eve.nosp@m.ngx.c.nosp@m.om
WinDivert emulation of netfilter_queue functionality to hook into Suricata's IPS mode. Supported solely on Windows.
Definition in file source-windivert.c.
Function Documentation
NoWinDivertSupportExit()
TmEcode NoWinDivertSupportExit (ThreadVars * tv, const void * initdata, void ** data)
Definition at line 81 of file source-windivert.c.
References ThreadVars_::name, SC_ERR_WINDIVERT_NOSUPPORT, SCLogError, and tv.
Referenced by TmModuleDecodeWinDivertRegister(), TmModuleReceiveWinDivertRegister(), and TmModuleVerdictWinDivertRegister().
TmModuleDecodeWinDivertRegister()
void TmModuleDecodeWinDivertRegister (void)
Definition at line 74 of file source-windivert.c.
References TmModule_::flags, TmModule_::name, NoWinDivertSupportExit(), TmModule_::ThreadInit, TM_FLAG_DECODE_TM, TMM_DECODEWINDIVERT, and tmm_modules.
Referenced by RegisterAllModules().
TmModuleReceiveWinDivertRegister()
void TmModuleReceiveWinDivertRegister (void)
Definition at line 61 of file source-windivert.c.
References TmModule_::flags, TmModule_::name, NoWinDivertSupportExit(), TmModule_::ThreadInit, TM_FLAG_RECEIVE_TM, tmm_modules, and TMM_RECEIVEWINDIVERT.
Referenced by RegisterAllModules().
TmModuleVerdictWinDivertRegister()
void TmModuleVerdictWinDivertRegister (void)
Definition at line 68 of file source-windivert.c.
References TmModule_::name, NoWinDivertSupportExit(), TmModule_::ThreadInit, tmm_modules, and TMM_VERDICTWINDIVERT.
Referenced by RegisterAllModules().