suricata: /Users/jlu/suricata/src/source-napatech.h File Reference
source-napatech.h File Reference
#include <nt.h>
Data Structures
struct NapatechStreamDevConf
Functions
void TmModuleNapatechStreamRegister (void)
Register the Napatech receiver (reader) module.
TmEcode NapatechStreamThreadDeinit (ThreadVars *tv, void *data)
Deinitializes the NAPATECH card.
void TmModuleNapatechDecodeRegister (void)
Register the Napatech decoder module.
int NapatechSetPortmap (int port, int peer)
int NapatechGetAdapter (uint8_t port)
Detailed Description
Author
nPulse Technologies, LLC.
Matt Keeler mk@np.nosp@m.ulse.nosp@m.tech..nosp@m.com
Definition in file source-napatech.h.
Function Documentation
NapatechGetAdapter()
int NapatechGetAdapter (uint8_t port)
NapatechSetPortmap()
int NapatechSetPortmap (int port, int peer)
NapatechStreamThreadDeinit()
TmEcode NapatechStreamThreadDeinit (ThreadVars * tv, void * data)
Deinitializes the NAPATECH card.
Parameters
tv pointer to ThreadVars
data pointer that gets cast into PcapThreadVars for ptv
Definition at line 1082 of file source-napatech.c.
References NapatechThreadVars_::rx_stream, SCEnter, SCLogDebug, SCReturnInt, NapatechThreadVars_::stream_id, and TM_ECODE_OK.
Referenced by TmModuleNapatechStreamRegister().
TmModuleNapatechDecodeRegister()
void TmModuleNapatechDecodeRegister (void)
Register the Napatech decoder module.
Definition at line 161 of file source-napatech.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Func, TmModule_::name, NapatechDecode(), NapatechDecodeThreadDeinit(), NapatechDecodeThreadInit(), TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_DECODE_TM, TMM_DECODENAPATECH, and tmm_modules.
Referenced by RegisterAllModules().
TmModuleNapatechStreamRegister()
void TmModuleNapatechStreamRegister (void)
Register the Napatech receiver (reader) module.
Definition at line 129 of file source-napatech.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Func, TmModule_::name, NapatechPacketLoop(), NapatechStreamThreadDeinit(), NapatechStreamThreadExitStats(), NapatechStreamThreadInit(), TmModule_::PktAcqBreakLoop, TmModule_::PktAcqLoop, SC_ATOMIC_INIT, SC_CAP_NET_RAW, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_RECEIVE_TM, tmm_modules, and TMM_RECEIVENAPATECH.
Referenced by RegisterAllModules().