suricata: /Users/jlu/suricata/src/source-pcap-file-directory-helper.h File Reference
source-pcap-file-directory-helper.h File Reference
#include "suricata-common.h"
#include "source-pcap-file-helper.h"
#include "queue.h"
Data Structures
struct PendingFile_
struct PcapFileDirectoryVars_
Typedefs
typedef struct PendingFile_ PendingFile
typedef struct PcapFileDirectoryVars_ PcapFileDirectoryVars
Functions
void CleanupPendingFile (PendingFile *pending)
void CleanupPcapFileDirectoryVars (PcapFileDirectoryVars *ptv)
TmEcode PcapDetermineDirectoryOrFile (char *filename, DIR **directory)
TmEcode PcapDirectoryDispatch (PcapFileDirectoryVars *ptv)
Detailed Description
Author
Danny Browning danny.nosp@m..bro.nosp@m.wning.nosp@m.@pro.nosp@m.tectw.nosp@m.ise..nosp@m.com
Definition in file source-pcap-file-directory-helper.h.
Typedef Documentation
PcapFileDirectoryVars
typedef struct PcapFileDirectoryVars_ PcapFileDirectoryVars
Data specific to a directory of pcap files
PendingFile
typedef struct PendingFile_ PendingFile
Function Documentation
CleanupPcapFileDirectoryVars()
void CleanupPcapFileDirectoryVars (PcapFileDirectoryVars * ptv)
Cleanup resources associated with a PcapFileDirectoryVars object
Parameters
ptv Object to be cleaned up
Definition at line 106 of file source-pcap-file-directory-helper.c.
References CleanupPcapFileFileVars(), CleanupPendingFile(), PcapFileDirectoryVars_::current_file, PcapFileDirectoryVars_::directory, PcapFileDirectoryVars_::filename, next, SCFree, PcapFileDirectoryVars_::shared, TAILQ_EMPTY, TAILQ_FIRST, and TAILQ_REMOVE.
CleanupPendingFile()
void CleanupPendingFile (PendingFile * pending)
Cleanup resources associated with a PendingFile object
Parameters
pending Object to be cleaned up
Definition at line 97 of file source-pcap-file-directory-helper.c.
References PendingFile_::filename, and SCFree.
Referenced by CleanupPcapFileDirectoryVars().
PcapDetermineDirectoryOrFile()
TmEcode PcapDetermineDirectoryOrFile (char * filename, DIR ** directory)
Determine if a given string represents a file or directory. If a directory, populate the directory object.
Parameters
filename String to check
directory Directory point to populate if directory
Returns
TM_ECODE_OK if string or directory
Definition at line 171 of file source-pcap-file-directory-helper.c.
References SC_ERR_FOPEN, SCLogDebug, SCLogError, TM_ECODE_FAILED, and TM_ECODE_OK.
PcapDirectoryDispatch()
TmEcode PcapDirectoryDispatch (PcapFileDirectoryVars * ptv)
Dispatch a directory for processing, where information for processing the directory is contained in a PcapFileDirectoryVars object
Parameters
ptv PcapFileDirectoryVars object containing information for processing the directory
Returns
Definition at line 498 of file source-pcap-file-directory-helper.c.
References PcapFileDirectoryVars_::poll_interval, SCEnter, and PcapFileDirectoryVars_::should_loop.