suricata: /Users/jlu/suricata/src/source-pcap-file.h File Reference
source-pcap-file.h File Reference
Functions
void TmModuleReceivePcapFileRegister (void)
void TmModuleDecodePcapFileRegister (void)
void PcapIncreaseInvalidChecksum (void)
void PcapFileGlobalInit (void)
const char * PcapFileGetFilename (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file source-pcap-file.h.
Function Documentation
PcapFileGetFilename()
const char * PcapFileGetFilename (void)
Definition at line 120 of file source-pcap-file-helper.c.
References pcap_filename.
Referenced by OutputJSONBuffer(), and OutputJsonBuilderBuffer().
PcapFileGlobalInit()
void PcapFileGlobalInit (void)
Definition at line 138 of file source-pcap-file.c.
References pcap_g, and SC_ATOMIC_INIT.
Referenced by RunModeFilePcapAutoFp(), and RunModeFilePcapSingle().
PcapIncreaseInvalidChecksum()
void PcapIncreaseInvalidChecksum (void)
Definition at line 456 of file source-pcap-file.c.
References pcap_g, and SC_ATOMIC_ADD.
TmModuleDecodePcapFileRegister()
void TmModuleDecodePcapFileRegister (void)
Definition at line 127 of file source-pcap-file.c.
References TmModule_::name, TmModule_::ThreadInit, TMM_DECODEPCAPFILE, and tmm_modules.
Referenced by RegisterAllModules().
TmModuleReceivePcapFileRegister()
void TmModuleReceivePcapFileRegister (void)
Pcap File Functionality
Definition at line 114 of file source-pcap-file.c.
References TmModule_::name, TmModule_::ThreadInit, tmm_modules, and TMM_RECEIVEPCAPFILE.
Referenced by RegisterAllModules().