suricata: /Users/jlu/suricata/src/source-ipfw.c File Reference
source-ipfw.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "packet-queue.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-queuehandlers.h"
#include "tm-threads.h"
#include "source-ipfw.h"
#include "util-debug.h"
#include "conf.h"
#include "util-byte.h"
#include "util-privs.h"
#include "util-datalink.h"
#include "util-device.h"
#include "runmodes.h"
Data Structures
struct IPFWThreadVars_
Structure to hold thread specific variables.
Macros
#define IPFW_ACCEPT 0
#define IPFW_DROP 1
#define IPFW_SOCKET_POLL_MSEC 300
#define IP_MAXPACKET 65535
Typedefs
typedef struct IPFWThreadVars_ IPFWThreadVars
Structure to hold thread specific variables.
Functions
void TmModuleReceiveIPFWRegister (void)
Registration Function for RecieveIPFW.
void TmModuleVerdictIPFWRegister (void)
Registration Function for VerdictIPFW.
void TmModuleDecodeIPFWRegister (void)
Registration Function for DecodeIPFW.
int IPFWRegisterQueue (char *queue)
Add an IPFW divert.
void * IPFWGetThread (int number)
Get a pointer to the IPFW thread at index.
Variables
int max_pending_packets
Detailed Description
Author
Nick Rogness nick@.nosp@m.rogn.nosp@m.ess.n.nosp@m.et
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
IPFW packet acquisition support
Definition in file source-ipfw.c.
Macro Definition Documentation
IP_MAXPACKET
#define IP_MAXPACKET 65535
Definition at line 50 of file source-ipfw.c.
IPFW_ACCEPT
#define IPFW_ACCEPT 0
Definition at line 44 of file source-ipfw.c.
IPFW_DROP
#define IPFW_DROP 1
Definition at line 45 of file source-ipfw.c.
IPFW_SOCKET_POLL_MSEC
#define IPFW_SOCKET_POLL_MSEC 300
Definition at line 47 of file source-ipfw.c.
Typedef Documentation
IPFWThreadVars
typedef struct IPFWThreadVars_ IPFWThreadVars
Structure to hold thread specific variables.
Function Documentation
IPFWGetThread()
void * IPFWGetThread (int number)
Get a pointer to the IPFW thread at index.
This function is temporary used as configuration parser.
Parameters
number idx of the queue in our array
Return values
ptr pointer to the IPFWThreadVars at index
NULL on error
Definition at line 761 of file source-ipfw.c.
Referenced by RunModeIpsIPFWAutoFp(), and RunModeIpsIPFWWorker().
IPFWRegisterQueue()
int IPFWRegisterQueue (char * queue)
Add an IPFW divert.
Parameters
string with the queue name
Return values
0 on success.
-1 on failure.
Definition at line 696 of file source-ipfw.c.
References SC_ERR_INVALID_ARGUMENT, SCLogError, SCMutexLock, and StringParseUint16().
TmModuleDecodeIPFWRegister()
void TmModuleDecodeIPFWRegister (void)
Registration Function for DecodeIPFW.
Todo:
Unit tests are needed for this module.
Definition at line 186 of file source-ipfw.c.
References TmModule_::name, TmModule_::ThreadInit, TMM_DECODEIPFW, and tmm_modules.
Referenced by RegisterAllModules().
TmModuleReceiveIPFWRegister()
void TmModuleReceiveIPFWRegister (void)
Registration Function for RecieveIPFW.
Todo:
Unit tests are needed for this module.
Todo:
untested
Definition at line 150 of file source-ipfw.c.
References SCMutexInit.
Referenced by RegisterAllModules().
TmModuleVerdictIPFWRegister()
void TmModuleVerdictIPFWRegister (void)
Registration Function for VerdictIPFW.
Todo:
Unit tests are needed for this module.
Todo:
untested
Definition at line 171 of file source-ipfw.c.
References TmModule_::name, TmModule_::ThreadInit, tmm_modules, and TMM_VERDICTIPFW.
Referenced by RegisterAllModules().