suricata: /Users/jlu/suricata/src/source-ipfw.h File Reference
source-ipfw.h File Reference
Data Structures
struct IPFWPacketVars_
struct IPFWQueueVars_
Macros
#define IPFW_MAX_QUEUE 16
Typedefs
typedef struct IPFWPacketVars_ IPFWPacketVars
typedef struct IPFWQueueVars_ IPFWQueueVars
Functions
void * IPFWGetThread (int number)
Get a pointer to the IPFW thread at index.
int IPFWRegisterQueue (char *queue)
Add an IPFW divert.
void TmModuleReceiveIPFWRegister (void)
Registration Function for RecieveIPFW.
void TmModuleVerdictIPFWRegister (void)
Registration Function for VerdictIPFW.
void TmModuleDecodeIPFWRegister (void)
Registration Function for DecodeIPFW.
Detailed Description
Author
Nick Rogness nick@.nosp@m.rogn.nosp@m.ess.n.nosp@m.et
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Definition in file source-ipfw.h.
Macro Definition Documentation
IPFW_MAX_QUEUE
#define IPFW_MAX_QUEUE 16
Definition at line 28 of file source-ipfw.h.
Typedef Documentation
IPFWPacketVars
typedef struct IPFWPacketVars_ IPFWPacketVars
IPFWQueueVars
typedef struct IPFWQueueVars_ IPFWQueueVars
Function Documentation
IPFWGetThread()
void * IPFWGetThread (int number)
Get a pointer to the IPFW thread at index.
This function is temporary used as configuration parser.
Parameters
number idx of the queue in our array
Return values
ptr pointer to the IPFWThreadVars at index
NULL on error
Definition at line 761 of file source-ipfw.c.
Referenced by RunModeIpsIPFWAutoFp(), and RunModeIpsIPFWWorker().
IPFWRegisterQueue()
int IPFWRegisterQueue (char * queue)
Add an IPFW divert.
Parameters
string with the queue name
Return values
0 on success.
-1 on failure.
Definition at line 696 of file source-ipfw.c.
References SC_ERR_INVALID_ARGUMENT, SCLogError, SCMutexLock, and StringParseUint16().
TmModuleDecodeIPFWRegister()
void TmModuleDecodeIPFWRegister (void)
Registration Function for DecodeIPFW.
Todo:
Unit tests are needed for this module.
Definition at line 186 of file source-ipfw.c.
References TmModule_::name, TmModule_::ThreadInit, TMM_DECODEIPFW, and tmm_modules.
Referenced by RegisterAllModules().
TmModuleReceiveIPFWRegister()
void TmModuleReceiveIPFWRegister (void)
Registration Function for RecieveIPFW.
Todo:
Unit tests are needed for this module.
Todo:
untested
Definition at line 150 of file source-ipfw.c.
References SCMutexInit.
Referenced by RegisterAllModules().
TmModuleVerdictIPFWRegister()
void TmModuleVerdictIPFWRegister (void)
Registration Function for VerdictIPFW.
Todo:
Unit tests are needed for this module.
Todo:
untested
Definition at line 171 of file source-ipfw.c.
References TmModule_::name, TmModule_::ThreadInit, tmm_modules, and TMM_VERDICTIPFW.
Referenced by RegisterAllModules().