suricata: /Users/jlu/suricata/src/source-nfq.c File Reference
source-nfq.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "packet-queue.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "tm-queuehandlers.h"
#include "tmqh-packetpool.h"
#include "conf.h"
#include "conf-yaml-loader.h"
#include "source-nfq-prototypes.h"
#include "action-globals.h"
#include "util-datalink.h"
#include "util-debug.h"
#include "util-error.h"
#include "util-byte.h"
#include "util-cpu.h"
#include "util-privs.h"
#include "util-device.h"
#include "runmodes.h"
#include "source-nfq.h"
Data Structures
struct NFQThreadVars_
struct NFQCnf_
Macros
#define MAX_ALREADY_TREATED 5
#define NFQ_VERDICT_RETRY_TIME 3
#define NFQ_BURST_FACTOR 4
#define SOL_NETLINK 270
#define NFQ_FLAG_FAIL_OPEN (1 << 0)
#define NFQMutexLock(nq)
#define NFQMutexUnlock(nq)
#define T_DATA_SIZE 70000
Typedefs
typedef struct NFQThreadVars_ NFQThreadVars
typedef enum NFQMode_ NFQMode
typedef struct NFQCnf_ NFQCnf
Enumerations
enum NFQMode_ { NFQ_ACCEPT_MODE , NFQ_REPEAT_MODE , NFQ_ROUTE_MODE }
Functions
void TmModuleReceiveNFQRegister (void)
void TmModuleVerdictNFQRegister (void)
void TmModuleDecodeNFQRegister (void)
void NFQInitConfig (bool quiet)
To initialize the NFQ global configuration data.
int NFQRegisterQueue (const uint16_t number)
Add a single Netfilter queue.
int NFQParseAndRegisterQueues (const char *queues)
Parses and adds Netfilter queue(s).
void * NFQGetQueue (int number)
Get a pointer to the NFQ queue at index.
void * NFQGetThread (int number)
Get a pointer to the NFQ thread at index.
void NFQContextsClean ()
Clean global contexts. Must be called on exit.
Variables
int max_pending_packets
NFQCnf nfq_config
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Netfilter's netfilter_queue support for reading packets from the kernel and setting verdicts back to it (inline mode).
Definition in file source-nfq.c.
Macro Definition Documentation
MAX_ALREADY_TREATED
#define MAX_ALREADY_TREATED 5
Definition at line 100 of file source-nfq.c.
NFQ_BURST_FACTOR
#define NFQ_BURST_FACTOR 4
Definition at line 105 of file source-nfq.c.
NFQ_FLAG_FAIL_OPEN
#define NFQ_FLAG_FAIL_OPEN (1 << 0)
Definition at line 153 of file source-nfq.c.
NFQ_VERDICT_RETRY_TIME
#define NFQ_VERDICT_RETRY_TIME 3
Definition at line 101 of file source-nfq.c.
NFQMutexLock
#define NFQMutexLock (nq)
Value:
    do {           \
    if ((nq)->use_mutex)                \
        SCMutexLock(&(nq)->mutex_qh);   \
} while (0)
Definition at line 387 of file source-nfq.c.
NFQMutexUnlock
#define NFQMutexUnlock (nq)
Value:
    do {         \
    if ((nq)->use_mutex)                \
        SCMutexUnlock(&(nq)->mutex_qh); \
} while (0)
Definition at line 392 of file source-nfq.c.
SOL_NETLINK
#define SOL_NETLINK 270
Definition at line 108 of file source-nfq.c.
T_DATA_SIZE
#define T_DATA_SIZE 70000
Typedef Documentation
NFQCnf
typedef struct NFQCnf_ NFQCnf
NFQMode
typedef enum NFQMode_ NFQMode
NFQThreadVars
typedef struct NFQThreadVars_ NFQThreadVars
Enumeration Type Documentation
NFQMode_
enum NFQMode_
Enumerator
NFQ_ACCEPT_MODE
NFQ_REPEAT_MODE
NFQ_ROUTE_MODE
Definition at line 147 of file source-nfq.c.
Function Documentation
NFQContextsClean()
void NFQContextsClean (void)
Clean global contexts. Must be called on exit.
Definition at line 1277 of file source-nfq.c.
NFQGetQueue()
void * NFQGetQueue (int number)
Get a pointer to the NFQ queue at index.
Parameters
number idx of the queue in our array
Return values
ptr pointer to the NFQThreadVars at index
NULL on error
Definition at line 926 of file source-nfq.c.
References unlikely.
NFQGetThread()
void * NFQGetThread (int number)
Get a pointer to the NFQ thread at index.
This function is temporary used as configuration parser.
Parameters
number idx of the queue in our array
Return values
ptr pointer to the NFQThreadVars at index
NULL on error
Definition at line 944 of file source-nfq.c.
References unlikely.
Referenced by RunModeIpsNFQAutoFp(), and RunModeIpsNFQWorker().
NFQInitConfig()
void NFQInitConfig (bool quiet)
To initialize the NFQ global configuration data.
Parameters
quiet It tells the mode of operation, if it is TRUE nothing will be get printed.
Definition at line 205 of file source-nfq.c.
References NFQCnf_::batchcount, NFQCnf_::bypass_mark, NFQCnf_::bypass_mask, ConfGet(), ConfGetBool(), ConfGetInt(), FatalError, NFQCnf_::flags, NFQCnf_::mark, NFQCnf_::mask, NFQCnf_::mode, NFQCnf_::next_queue, NFQ_ACCEPT_MODE, nfq_config, NFQ_FLAG_FAIL_OPEN, NFQ_REPEAT_MODE, NFQ_ROUTE_MODE, SC_ERR_FATAL, SC_ERR_INVALID_ARGUMENT, SC_ERR_NFQ_NOSUPPORT, SCLogDebug, SCLogError, SCLogInfo, and SCLogWarning.
NFQParseAndRegisterQueues()
int NFQParseAndRegisterQueues (const char * queues)
Parses and adds Netfilter queue(s).
Parameters
string with the queue number or range
Return values
0 on success.
-1 on failure.
Definition at line 863 of file source-nfq.c.
References SC_ERR_INVALID_ARGUMENT, SCLogError, and SCRealloc.
NFQRegisterQueue()
int NFQRegisterQueue (const uint16_t number)
Add a single Netfilter queue.
Parameters
string with the queue number
Return values
0 on success.
-1 on failure.
Definition at line 804 of file source-nfq.c.
References UtilCpuGetNumProcessorsOnline().
TmModuleDecodeNFQRegister()
void TmModuleDecodeNFQRegister (void)
Definition at line 191 of file source-nfq.c.
References TmModule_::name, TmModule_::ThreadInit, TMM_DECODENFQ, and tmm_modules.
Referenced by RegisterAllModules().
TmModuleReceiveNFQRegister()
void TmModuleReceiveNFQRegister (void)
Definition at line 168 of file source-nfq.c.
Referenced by RegisterAllModules().
TmModuleVerdictNFQRegister()
void TmModuleVerdictNFQRegister (void)
Definition at line 183 of file source-nfq.c.
References TmModule_::name, TmModule_::ThreadInit, tmm_modules, and TMM_VERDICTNFQ.
Referenced by RegisterAllModules().
Variable Documentation
nfq_config
NFQCnf nfq_config
Definition at line 166 of file source-nfq.c.
Referenced by NFQInitConfig().