suricata: /Users/jlu/suricata/src/source-nflog.h File Reference
source-nflog.h File Reference
Data Structures
struct NflogGroupConfig_
struct NFLOGPacketVars_
Macros
#define NFLOG_GROUP_NAME_LENGTH 48
Typedefs
typedef struct NflogGroupConfig_ NflogGroupConfig
typedef struct NFLOGPacketVars_ NFLOGPacketVars
Functions
void TmModuleReceiveNFLOGRegister (void)
void TmModuleDecodeNFLOGRegister (void)
Detailed Description
Author
Giuseppe Longo giuse.nosp@m.ppel.nosp@m.ng@gm.nosp@m.ail..nosp@m.com
Definition in file source-nflog.h.
Macro Definition Documentation
NFLOG_GROUP_NAME_LENGTH
#define NFLOG_GROUP_NAME_LENGTH 48
Definition at line 32 of file source-nflog.h.
Typedef Documentation
NflogGroupConfig
typedef struct NflogGroupConfig_ NflogGroupConfig
NFLOGPacketVars
typedef struct NFLOGPacketVars_ NFLOGPacketVars
Function Documentation
TmModuleDecodeNFLOGRegister()
void TmModuleDecodeNFLOGRegister (void)
Definition at line 55 of file source-nflog.c.
References TmModule_::name, NoNFLOGSupportExit(), TmModule_::ThreadInit, TMM_DECODENFLOG, and tmm_modules.
Referenced by RegisterAllModules().
TmModuleReceiveNFLOGRegister()
void TmModuleReceiveNFLOGRegister (void)
Definition at line 49 of file source-nflog.c.
References TmModule_::name, NoNFLOGSupportExit(), TmModule_::ThreadInit, tmm_modules, and TMM_RECEIVENFLOG.
Referenced by RegisterAllModules().