suricata: /Users/jlu/suricata/src/source-pcap-file-helper.c File Reference
source-pcap-file-helper.c File Reference
#include "source-pcap-file-helper.h"
#include "suricata.h"
#include "util-datalink.h"
#include "util-checksum.h"
#include "util-profiling.h"
#include "source-pcap-file.h"
#include "util-exception-policy.h"
Functions
void CleanupPcapFileFileVars (PcapFileFileVars *pfv)
const char * PcapFileGetFilename (void)
TmEcode PcapFileDispatch (PcapFileFileVars *ptv)
Main PCAP file reading Loop function.
TmEcode InitPcapFile (PcapFileFileVars *pfv)
TmEcode ValidateLinkType (int datalink, DecoderFunc *DecoderFn)
Variables
int max_pending_packets
PcapFileGlobalVars pcap_g
char pcap_filename [PATH_MAX] = "unknown"
Detailed Description
Author
Danny Browning danny.nosp@m..bro.nosp@m.wning.nosp@m.@pro.nosp@m.tectw.nosp@m.ise..nosp@m.com
File based pcap packet acquisition support
Definition in file source-pcap-file-helper.c.
Function Documentation
CleanupPcapFileFileVars()
void CleanupPcapFileFileVars (PcapFileFileVars * pfv)
Cleanup resources associated with a PcapFileFileVars object.
Parameters
pfv Object to be cleaned up
Definition at line 39 of file source-pcap-file-helper.c.
References PcapFileFileVars_::filename, PcapFileFileVars_::pcap_handle, SC_ERR_PCAP_FILE_DELETE_FAILED, SCFree, SCLogDebug, SCLogWarning, PcapFileFileVars_::shared, and PcapFileSharedVars_::should_delete.
Referenced by CleanupPcapFileDirectoryVars().
InitPcapFile()
TmEcode InitPcapFile (PcapFileFileVars * pfv)
From a PcapFileFileVars, prepare the filename for processing by setting pcap_handle, datalink, and filter
Parameters
pfv PcapFileFileVars object to populate
Returns
Definition at line 200 of file source-pcap-file-helper.c.
References PcapFileSharedVars_::bpf_string, PcapFileFileVars_::datalink, DatalinkSetGlobalType(), PcapFileFileVars_::filename, PcapFileFileVars_::filter, PcapFileFileVars_::pcap_handle, SC_ERR_BPF, SC_ERR_FOPEN, SC_ERR_INVALID_ARGUMENT, SCLogDebug, SCLogError, SCLogInfo, SCReturnInt, PcapFileFileVars_::shared, TM_ECODE_FAILED, and unlikely.
PcapFileDispatch()
TmEcode PcapFileDispatch (PcapFileFileVars * ptv)
Main PCAP file reading Loop function.
Dispatch a file for processing, where the information necessary to process that file is as PcapFileFileVars object.
Parameters
ptv PcapFileFileVars object to be processed
Returns
Definition at line 128 of file source-pcap-file-helper.c.
References PcapFileFileVars_::first_pkt_hdr, PcapFileFileVars_::first_pkt_ts, likely, SCEnter, and TmThreadsInitThreadsTimestamp().
PcapFileGetFilename()
const char * PcapFileGetFilename (void)
Definition at line 120 of file source-pcap-file-helper.c.
References pcap_filename.
Referenced by OutputJSONBuffer(), and OutputJsonBuilderBuffer().
ValidateLinkType()
TmEcode ValidateLinkType (int datalink, DecoderFunc * decoder)
Determine if a datalink type is valid, setting a decoder function if valid.
Parameters
datalink Datalink type to validate
decoder Pointer to decoder to set if valid
Returns
TM_ECODE_OK if valid datalink type and decoder has been set.
Definition at line 245 of file source-pcap-file-helper.c.
References DecodeCHDLC(), DecodeEthernet(), DecodeNull(), DecodePPP(), DecodeRaw(), DecodeSll(), LINKTYPE_CISCO_HDLC, LINKTYPE_ETHERNET, LINKTYPE_GRE_OVER_IP, LINKTYPE_IPV4, LINKTYPE_LINUX_SLL, LINKTYPE_NULL, LINKTYPE_PPP, LINKTYPE_RAW, LINKTYPE_RAW2, SC_ERR_UNIMPLEMENTED, SCLogError, SCReturnInt, TM_ECODE_FAILED, and TM_ECODE_OK.
Variable Documentation
pcap_filename
char pcap_filename[PATH_MAX] = "unknown"
Definition at line 118 of file source-pcap-file-helper.c.
Referenced by PcapFileGetFilename().
pcap_g
PcapFileGlobalVars pcap_g extern
Definition at line 36 of file source-pcap-file.c.
Referenced by PcapFileGlobalInit(), and PcapIncreaseInvalidChecksum().