suricata: /Users/jlu/suricata/src/source-pcap-file.c File Reference
source-pcap-file.c File Reference
#include "suricata-common.h"
#include "source-pcap-file.h"
#include "source-pcap-file-helper.h"
#include "source-pcap-file-directory-helper.h"
#include "flow-manager.h"
#include "util-checksum.h"
#include "runmode-unix-socket.h"
#include "suricata.h"
Data Structures
union PcapFileBehaviorVar_
struct PcapFileThreadVars_
Typedefs
typedef union PcapFileBehaviorVar_ PcapFileBehaviorVar
typedef struct PcapFileThreadVars_ PcapFileThreadVars
Functions
void TmModuleReceivePcapFileRegister (void)
void TmModuleDecodePcapFileRegister (void)
void PcapFileGlobalInit ()
void PcapIncreaseInvalidChecksum ()
Variables
int max_pending_packets
PcapFileGlobalVars pcap_g
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
File based pcap packet acquisition support
Definition in file source-pcap-file.c.
Typedef Documentation
PcapFileBehaviorVar
typedef union PcapFileBehaviorVar_ PcapFileBehaviorVar
Union determining whether the behavior of the thread is file or directory
PcapFileThreadVars
typedef struct PcapFileThreadVars_ PcapFileThreadVars
Data specific to the thread
Function Documentation
PcapFileGlobalInit()
void PcapFileGlobalInit (void)
Definition at line 138 of file source-pcap-file.c.
References pcap_g, and SC_ATOMIC_INIT.
Referenced by RunModeFilePcapAutoFp(), and RunModeFilePcapSingle().
PcapIncreaseInvalidChecksum()
void PcapIncreaseInvalidChecksum (void)
Definition at line 456 of file source-pcap-file.c.
References pcap_g, and SC_ATOMIC_ADD.
TmModuleDecodePcapFileRegister()
void TmModuleDecodePcapFileRegister (void)
Definition at line 127 of file source-pcap-file.c.
References TmModule_::name, TmModule_::ThreadInit, TMM_DECODEPCAPFILE, and tmm_modules.
Referenced by RegisterAllModules().
TmModuleReceivePcapFileRegister()
void TmModuleReceivePcapFileRegister (void)
Pcap File Functionality
Definition at line 114 of file source-pcap-file.c.
References TmModule_::name, TmModule_::ThreadInit, tmm_modules, and TMM_RECEIVEPCAPFILE.
Referenced by RegisterAllModules().
Variable Documentation
pcap_g
PcapFileGlobalVars pcap_g
Definition at line 36 of file source-pcap-file.c.
Referenced by PcapFileGlobalInit(), and PcapIncreaseInvalidChecksum().