suricata: /Users/jlu/suricata/src/source-windivert-prototypes.h File Reference
source-windivert-prototypes.h File Reference
Functions
void TmModuleReceiveWinDivertRegister (void)
void TmModuleVerdictWinDivertRegister (void)
void TmModuleDecodeWinDivertRegister (void)
Detailed Description
Author
Jacob Masen-Smith jacob.nosp@m.@eve.nosp@m.ngx.c.nosp@m.om
Definition in file source-windivert-prototypes.h.
Function Documentation
TmModuleDecodeWinDivertRegister()
void TmModuleDecodeWinDivertRegister (void)
Definition at line 74 of file source-windivert.c.
References TmModule_::flags, TmModule_::name, NoWinDivertSupportExit(), TmModule_::ThreadInit, TM_FLAG_DECODE_TM, TMM_DECODEWINDIVERT, and tmm_modules.
Referenced by RegisterAllModules().
TmModuleReceiveWinDivertRegister()
void TmModuleReceiveWinDivertRegister (void)
Definition at line 61 of file source-windivert.c.
References TmModule_::flags, TmModule_::name, NoWinDivertSupportExit(), TmModule_::ThreadInit, TM_FLAG_RECEIVE_TM, tmm_modules, and TMM_RECEIVEWINDIVERT.
Referenced by RegisterAllModules().
TmModuleVerdictWinDivertRegister()
void TmModuleVerdictWinDivertRegister (void)
Definition at line 68 of file source-windivert.c.
References TmModule_::name, NoWinDivertSupportExit(), TmModule_::ThreadInit, tmm_modules, and TMM_VERDICTWINDIVERT.
Referenced by RegisterAllModules().