suricata: /Users/jlu/suricata/src/source-napatech.c File Reference
source-napatech.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "threadvars.h"
#include "util-datalink.h"
#include "util-optimize.h"
#include "tm-queuehandlers.h"
#include "tm-threads.h"
#include "tm-modules.h"
#include "util-privs.h"
#include "tmqh-packetpool.h"
#include "util-napatech.h"
#include "source-napatech.h"
#include <numa.h>
#include <nt.h>
Data Structures
struct NapatechThreadVars_
Typedefs
typedef struct NapatechThreadVars_ NapatechThreadVars
Functions
TmEcode NapatechStreamThreadInit (ThreadVars *tv, const void *initdata, void **data)
Initialize the Napatech receiver thread, generate a single NapatechThreadVar structure for each thread, this will contain a NtNetStreamRx_t stream handle which is used when the thread executes to acquire the packets.
void NapatechStreamThreadExitStats (ThreadVars *tv, void *data)
Print some stats to the log at program exit.
TmEcode NapatechPacketLoop (ThreadVars *tv, void *data, void *slot)
Main Napatechpacket processing loop.
TmEcode NapatechDecodeThreadInit (ThreadVars *tv, const void *initdata, void **data)
Initialization of Napatech Thread.
TmEcode NapatechDecodeThreadDeinit (ThreadVars *tv, void *data)
Deinitialization of Napatech Thread.
TmEcode NapatechDecode (ThreadVars *tv, Packet *p, void *data)
This function passes off to link type decoders.
SC_ATOMIC_DECLARE (uint64_t, total_packets)
SC_ATOMIC_DECLARE (uint64_t, total_drops)
SC_ATOMIC_DECLARE (uint16_t, total_tallied)
SC_ATOMIC_DECLARE (uint16_t, stream_count)
SC_ATOMIC_DECLARE (uint16_t, numa0_count)
SC_ATOMIC_DECLARE (uint16_t, numa1_count)
SC_ATOMIC_DECLARE (uint16_t, numa2_count)
SC_ATOMIC_DECLARE (uint16_t, numa3_count)
SC_ATOMIC_DECLARE (uint64_t, flow_callback_cnt)
SC_ATOMIC_DECLARE (uint64_t, flow_callback_handled_pkts)
SC_ATOMIC_DECLARE (uint64_t, flow_callback_udp_pkts)
SC_ATOMIC_DECLARE (uint64_t, flow_callback_tcp_pkts)
SC_ATOMIC_DECLARE (uint64_t, flow_callback_unhandled_pkts)
void TmModuleNapatechStreamRegister (void)
Register the Napatech receiver (reader) module.
void TmModuleNapatechDecodeRegister (void)
Register the Napatech decoder module.
TmEcode NapatechStreamThreadDeinit (ThreadVars *tv, void *data)
Deinitializes the NAPATECH card.
Variables
int max_pending_packets
Detailed Description
*
Author
nPulse Technologies, LLC.
*
Author
Matt Keeler mk@np.nosp@m.ulse.nosp@m.tech..nosp@m.com
Support for NAPATECH adapter with the 3GD Driver/API. Requires libntapi from Napatech A/S.
Definition in file source-napatech.c.
Typedef Documentation
NapatechThreadVars
typedef struct NapatechThreadVars_ NapatechThreadVars
Function Documentation
NapatechDecode()
TmEcode NapatechDecode (ThreadVars * tv, Packet * p, void * data)
This function passes off to link type decoders.
NapatechDecode decodes packets from Napatech and passes them off to the proper link type decoder.
Parameters
t pointer to ThreadVars
p pointer to the current packet
data pointer that gets cast into PcapThreadVars for ptv
Definition at line 1103 of file source-napatech.c.
References BUG_ON, Packet_::datalink, DecodeEthernet(), DecodeUpdatePacketCounters(), dtv, GET_PKT_DATA, GET_PKT_LEN, LINKTYPE_ETHERNET, PacketDecodeFinalize(), PKT_IS_PSEUDOPKT, SC_ERR_DATALINK_UNIMPLEMENTED, SCEnter, SCLogError, SCReturnInt, TM_ECODE_OK, and tv.
Referenced by TmModuleNapatechDecodeRegister().
NapatechDecodeThreadDeinit()
TmEcode NapatechDecodeThreadDeinit (ThreadVars * tv, void * data)
Deinitialization of Napatech Thread.
Parameters
tv pointer to ThreadVars
data pointer that gets cast into DecoderThreadVars
Definition at line 1156 of file source-napatech.c.
References DecodeThreadVarsFree(), SCReturnInt, TM_ECODE_OK, and tv.
Referenced by TmModuleNapatechDecodeRegister().
NapatechDecodeThreadInit()
TmEcode NapatechDecodeThreadInit (ThreadVars * tv, const void * initdata, void ** data)
Initialization of Napatech Thread.
Parameters
t pointer to ThreadVars
initdata - unused.
data pointer that gets cast into DecoderThreadVars
Definition at line 1136 of file source-napatech.c.
References DecodeRegisterPerfCounters(), DecodeThreadVarsAlloc(), dtv, SCEnter, SCReturnInt, TM_ECODE_FAILED, TM_ECODE_OK, and tv.
Referenced by TmModuleNapatechDecodeRegister().
NapatechPacketLoop()
TmEcode NapatechPacketLoop (ThreadVars * tv, void * data, void * slot)
Main Napatechpacket processing loop.
Parameters
tv Thread variable to ThreadVars
data Pointer to NapatechThreadVars with data specific to Napatech
slot TMSlot where this instance is running.
Definition at line 789 of file source-napatech.c.
References ConfGetBool(), MAX_ADAPTERS, and NapatechThreadVars_::stream_id.
Referenced by TmModuleNapatechStreamRegister().
NapatechStreamThreadDeinit()
TmEcode NapatechStreamThreadDeinit (ThreadVars * tv, void * data)
Deinitializes the NAPATECH card.
Parameters
tv pointer to ThreadVars
data pointer that gets cast into PcapThreadVars for ptv
Definition at line 1082 of file source-napatech.c.
References NapatechThreadVars_::rx_stream, SCEnter, SCLogDebug, SCReturnInt, NapatechThreadVars_::stream_id, and TM_ECODE_OK.
Referenced by TmModuleNapatechStreamRegister().
NapatechStreamThreadExitStats()
void NapatechStreamThreadExitStats (ThreadVars * tv, void * data)
Print some stats to the log at program exit.
Parameters
tv Pointer to ThreadVars.
data Pointer to data, ErfFileThreadVars.
Definition at line 1040 of file source-napatech.c.
References NapatechCurrentStats_::current_bytes, NapatechCurrentStats_::current_drop_packets, NapatechCurrentStats_::current_packets, NapatechGetCurrentStats(), NapatechGetNumConfiguredStreams(), SC_ATOMIC_ADD, SC_ATOMIC_GET, SCLogInfo, and NapatechThreadVars_::stream_id.
Referenced by TmModuleNapatechStreamRegister().
NapatechStreamThreadInit()
TmEcode NapatechStreamThreadInit (ThreadVars * tv, const void * initdata, void ** data)
Initialize the Napatech receiver thread, generate a single NapatechThreadVar structure for each thread, this will contain a NtNetStreamRx_t stream handle which is used when the thread executes to acquire the packets.
Parameters
tv Thread variable to ThreadVars
initdata Initial data to the adapter passed from the user, this is processed by the user.
For now, we assume that we have only a single name for the NAPATECH adapter.
Parameters
data data pointer gets populated with
Definition at line 643 of file source-napatech.c.
References DatalinkSetGlobalType(), FatalError, NapatechThreadVars_::hba, NapatechStreamDevConf::hba, LINKTYPE_ETHERNET, SC_ERR_FATAL, SCCalloc, SCEnter, SCLogDebug, SCReturnInt, NapatechThreadVars_::stream_id, NapatechStreamDevConf::stream_id, TM_ECODE_OK, NapatechThreadVars_::tv, tv, and unlikely.
Referenced by TmModuleNapatechStreamRegister().
SC_ATOMIC_DECLARE() [1/13]
SC_ATOMIC_DECLARE (uint16_t , numa0_count)
SC_ATOMIC_DECLARE() [2/13]
SC_ATOMIC_DECLARE (uint16_t , numa1_count)
SC_ATOMIC_DECLARE() [3/13]
SC_ATOMIC_DECLARE (uint16_t , numa2_count)
SC_ATOMIC_DECLARE() [4/13]
SC_ATOMIC_DECLARE (uint16_t , numa3_count)
SC_ATOMIC_DECLARE() [5/13]
SC_ATOMIC_DECLARE (uint16_t , stream_count)
SC_ATOMIC_DECLARE() [6/13]
SC_ATOMIC_DECLARE (uint16_t , total_tallied)
SC_ATOMIC_DECLARE() [7/13]
SC_ATOMIC_DECLARE (uint64_t , flow_callback_cnt)
SC_ATOMIC_DECLARE() [8/13]
SC_ATOMIC_DECLARE (uint64_t , flow_callback_handled_pkts)
SC_ATOMIC_DECLARE() [9/13]
SC_ATOMIC_DECLARE (uint64_t , flow_callback_tcp_pkts)
SC_ATOMIC_DECLARE() [10/13]
SC_ATOMIC_DECLARE (uint64_t , flow_callback_udp_pkts)
SC_ATOMIC_DECLARE() [11/13]
SC_ATOMIC_DECLARE (uint64_t , flow_callback_unhandled_pkts)
SC_ATOMIC_DECLARE() [12/13]
SC_ATOMIC_DECLARE (uint64_t , total_drops)
SC_ATOMIC_DECLARE() [13/13]
SC_ATOMIC_DECLARE (uint64_t , total_packets)
TmModuleNapatechDecodeRegister()
void TmModuleNapatechDecodeRegister (void)
Register the Napatech decoder module.
Definition at line 161 of file source-napatech.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Func, TmModule_::name, NapatechDecode(), NapatechDecodeThreadDeinit(), NapatechDecodeThreadInit(), TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_DECODE_TM, TMM_DECODENAPATECH, and tmm_modules.
Referenced by RegisterAllModules().
TmModuleNapatechStreamRegister()
void TmModuleNapatechStreamRegister (void)
Register the Napatech receiver (reader) module.
Definition at line 129 of file source-napatech.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Func, TmModule_::name, NapatechPacketLoop(), NapatechStreamThreadDeinit(), NapatechStreamThreadExitStats(), NapatechStreamThreadInit(), TmModule_::PktAcqBreakLoop, TmModule_::PktAcqLoop, SC_ATOMIC_INIT, SC_CAP_NET_RAW, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_RECEIVE_TM, tmm_modules, and TMM_RECEIVENAPATECH.
Referenced by RegisterAllModules().