suricata: /Users/jlu/suricata/src/source-erf-dag.h File Reference
source-erf-dag.h File Reference
Functions
void TmModuleReceiveErfDagRegister (void)
Register the ERF file receiver (reader) module.
void TmModuleDecodeErfDagRegister (void)
Register the ERF file decoder module.
Detailed Description
Author
Endace Technology Limited
Jason MacLulich jason.nosp@m..mac.nosp@m.lulic.nosp@m.h@en.nosp@m.dace..nosp@m.com
Definition in file source-erf-dag.h.
Function Documentation
TmModuleDecodeErfDagRegister()
void TmModuleDecodeErfDagRegister (void)
Register the ERF file decoder module.
Definition at line 151 of file source-erf-dag.c.
References TmModule_::cap_flags, DecodeErfDag(), DecodeErfDagThreadDeinit(), DecodeErfDagThreadInit(), TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_DECODE_TM, TMM_DECODEERFDAG, and tmm_modules.
Referenced by RegisterAllModules().
TmModuleReceiveErfDagRegister()
void TmModuleReceiveErfDagRegister (void)
Register the ERF file receiver (reader) module.
Definition at line 133 of file source-erf-dag.c.
References TmModule_::cap_flags, TmModule_::flags, TmModule_::Func, TmModule_::name, TmModule_::PktAcqBreakLoop, TmModule_::PktAcqLoop, ReceiveErfDagLoop(), ReceiveErfDagThreadExitStats(), ReceiveErfDagThreadInit(), TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TM_FLAG_RECEIVE_TM, tmm_modules, and TMM_RECEIVEERFDAG.
Referenced by RegisterAllModules().