suricata: /Users/jlu/suricata/src/stream-tcp.c File Reference
stream-tcp.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "decode.h"
#include "detect.h"
#include "flow.h"
#include "flow-util.h"
#include "conf.h"
#include "conf-yaml-loader.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "util-pool.h"
#include "util-pool-thread.h"
#include "util-checksum.h"
#include "util-unittest.h"
#include "util-print.h"
#include "util-debug.h"
#include "util-device.h"
#include "stream-tcp-private.h"
#include "stream-tcp-reassemble.h"
#include "stream-tcp.h"
#include "stream-tcp-inline.h"
#include "stream-tcp-sack.h"
#include "stream-tcp-util.h"
#include "stream.h"
#include "pkt-var.h"
#include "host.h"
#include "app-layer.h"
#include "app-layer-parser.h"
#include "app-layer-protos.h"
#include "app-layer-htp-mem.h"
#include "util-host-os-info.h"
#include "util-privs.h"
#include "util-profiling.h"
#include "util-misc.h"
#include "util-validate.h"
#include "util-runmodes.h"
#include "util-random.h"
#include "util-exception-policy.h"
#include "util-time.h"
#include "source-pcap-file.h"
#include "tests/stream-tcp.c"
Macros
#define STREAMTCP_DEFAULT_PREALLOC 2048
#define STREAMTCP_DEFAULT_MEMCAP (64 * 1024 * 1024) /* 64mb */
#define STREAMTCP_DEFAULT_REASSEMBLY_MEMCAP (256 * 1024 * 1024) /* 256mb */
#define STREAMTCP_DEFAULT_TOSERVER_CHUNK_SIZE 2560
#define STREAMTCP_DEFAULT_TOCLIENT_CHUNK_SIZE 2560
#define STREAMTCP_DEFAULT_MAX_SYNACK_QUEUED 5
#define StreamTcpUpdateLastAck(ssn, stream, ack)
macro to update last_ack only if the new value is higher
#define StreamTcpAsyncLastAckUpdate(ssn, stream)
#define StreamTcpUpdateNextSeq(ssn, stream, seq)
#define StreamTcpUpdateNextWin(ssn, stream, win)
macro to update next_win only if the new value is higher
#define PSEUDO_PKT_SET_IPV4HDR(nipv4h, ipv4h)
#define PSEUDO_PKT_SET_IPV6HDR(nipv6h, ipv6h)
#define PSEUDO_PKT_SET_TCPHDR(ntcph, tcph)
Functions
void StreamTcpReturnStreamSegments (TcpStream *)
return all segments in this stream into the pool(s)
void StreamTcpInitConfig (bool quiet)
To initialize the stream global configuration data.
int StreamTcpGetFlowState (void *)
void StreamTcpSetOSPolicy (TcpStream *stream, Packet *p)
Function to set the OS policy for the given stream based on the destination of the received packet.
uint64_t StreamTcpReassembleMemuseGlobalCounter (void)
SC_ATOMIC_DECLARE (uint64_t, st_memuse)
void StreamTcpInitMemuse (void)
void StreamTcpIncrMemuse (uint64_t size)
void StreamTcpDecrMemuse (uint64_t size)
uint64_t StreamTcpMemuseCounter (void)
int StreamTcpCheckMemcap (uint64_t size)
Check if alloc'ing "size" would mean we're over memcap.
int StreamTcpSetMemcap (uint64_t size)
Update memcap value.
uint64_t StreamTcpGetMemcap (void)
Return memcap value.
void StreamTcpStreamCleanup (TcpStream *stream)
void StreamTcpSessionCleanup (TcpSession *ssn)
Session cleanup function. Does not free the ssn.
void StreamTcpSessionClear (void *ssnptr)
Function to return the stream back to the pool. It returns the segments in the stream to the segment pool.
void StreamTcpSessionPktFree (Packet *p)
Function to return the stream segments back to the pool.
int StreamTcpInlineDropInvalid (void)
See if stream engine is dropping invalid packet in inline mode.
void StreamTcpFreeConfig (bool quiet)
int StreamTcpPacket (ThreadVars *tv, Packet *p, StreamTcpThread *stt, PacketQueueNoLock *pq)
int TcpSessionPacketSsnReuse (const Packet *p, const Flow *f, const void *tcp_ssn)
TmEcode StreamTcp (ThreadVars *tv, Packet *p, void *data, PacketQueueNoLock *pq)
TmEcode StreamTcpThreadInit (ThreadVars *tv, void *initdata, void **data)
TmEcode StreamTcpThreadDeinit (ThreadVars *tv, void *data)
void StreamTcpUpdateAppLayerProgress (TcpSession *ssn, char direction, const uint32_t progress)
update reassembly progress
void StreamTcpSetSessionNoReassemblyFlag (TcpSession *ssn, char direction)
disable reassembly
void StreamTcpSetDisableRawReassemblyFlag (TcpSession *ssn, char direction)
Set the No reassembly flag for the given direction in given TCP session.
void StreamTcpSetSessionBypassFlag (TcpSession *ssn)
enable bypass
Packet * StreamTcpPseudoSetup (Packet *parent, uint8_t *pkt, uint32_t len)
Function to fetch a packet from the packet allocation queue for creation of the pseudo packet from the reassembled stream.
void StreamTcpDetectLogFlush (ThreadVars *tv, StreamTcpThread *stt, Flow *f, Packet *p, PacketQueueNoLock *pq)
create packets in both directions to flush out logging and detection before switching protocols. In IDS mode, create first in packet dir, 2nd in opposing In IPS mode, do the reverse. Flag TCP engine that data needs to be inspected regardless of how far we are wrt inspect limits.
int StreamTcpSegmentForEach (const Packet *p, uint8_t flag, StreamSegmentCallback CallbackFunc, void *data)
int StreamTcpSegmentForSession (const Packet *p, uint8_t flag, StreamSegmentCallback CallbackFunc, void *data)
Run callback function on each TCP segment in both directions of a session.
int StreamTcpBypassEnabled (void)
int StreamTcpInlineMode (void)
See if stream engine is operating in inline mode.
void TcpSessionSetReassemblyDepth (TcpSession *ssn, uint32_t size)
const char * StreamTcpStateAsString (const enum TcpState state)
const char * StreamTcpSsnStateAsString (const TcpSession *ssn)
Variables
thread_local uint64_t t_pcapcnt
int g_detect_disabled
TcpStreamCnf stream_config
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Gurvinder Singh gurvi.nosp@m.nder.nosp@m.singh.nosp@m.dahi.nosp@m.ya@gm.nosp@m.ail..nosp@m.com
TCP stream tracking and reassembly engine.
Todo:
4WHS: what if after the 2nd SYN we turn out to be normal 3WHS anyway?
Definition in file stream-tcp.c.
Macro Definition Documentation
PSEUDO_PKT_SET_IPV4HDR
#define PSEUDO_PKT_SET_IPV4HDR (nipv4h, ipv4h)
Value:
        do { \
        IPV4_SET_RAW_VER(nipv4h, IPV4_GET_RAW_VER(ipv4h)); \
        IPV4_SET_RAW_HLEN(nipv4h, IPV4_GET_RAW_HLEN(ipv4h)); \
        IPV4_SET_RAW_IPLEN(nipv4h, IPV4_GET_RAW_IPLEN(ipv4h)); \
        IPV4_SET_RAW_IPTOS(nipv4h, IPV4_GET_RAW_IPTOS(ipv4h)); \
        IPV4_SET_RAW_IPPROTO(nipv4h, IPV4_GET_RAW_IPPROTO(ipv4h)); \
        (nipv4h)->s_ip_src = IPV4_GET_RAW_IPDST(ipv4h); \
        (nipv4h)->s_ip_dst = IPV4_GET_RAW_IPSRC(ipv4h); \
    } while (0)
Definition at line 6101 of file stream-tcp.c.
PSEUDO_PKT_SET_IPV6HDR
#define PSEUDO_PKT_SET_IPV6HDR (nipv6h, ipv6h)
Value:
        do { \
        (nipv6h)->s_ip6_src[0] = (ipv6h)->s_ip6_dst[0]; \
        (nipv6h)->s_ip6_src[1] = (ipv6h)->s_ip6_dst[1]; \
        (nipv6h)->s_ip6_src[2] = (ipv6h)->s_ip6_dst[2]; \
        (nipv6h)->s_ip6_src[3] = (ipv6h)->s_ip6_dst[3]; \
        (nipv6h)->s_ip6_dst[0] = (ipv6h)->s_ip6_src[0]; \
        (nipv6h)->s_ip6_dst[1] = (ipv6h)->s_ip6_src[1]; \
        (nipv6h)->s_ip6_dst[2] = (ipv6h)->s_ip6_src[2]; \
        (nipv6h)->s_ip6_dst[3] = (ipv6h)->s_ip6_src[3]; \
        IPV6_SET_RAW_NH(nipv6h, IPV6_GET_RAW_NH(ipv6h));    \
    } while (0)
Definition at line 6111 of file stream-tcp.c.
PSEUDO_PKT_SET_TCPHDR
#define PSEUDO_PKT_SET_TCPHDR (ntcph, tcph)
Value:
        do { \
        COPY_PORT((tcph)->th_dport, (ntcph)->th_sport); \
        COPY_PORT((tcph)->th_sport, (ntcph)->th_dport); \
        (ntcph)->th_seq = (tcph)->th_ack; \
        (ntcph)->th_ack = (tcph)->th_seq; \
    } while (0)
Definition at line 6123 of file stream-tcp.c.
STREAMTCP_DEFAULT_MAX_SYNACK_QUEUED
#define STREAMTCP_DEFAULT_MAX_SYNACK_QUEUED 5
Definition at line 88 of file stream-tcp.c.
STREAMTCP_DEFAULT_MEMCAP
#define STREAMTCP_DEFAULT_MEMCAP (64 * 1024 * 1024) /* 64mb */
Definition at line 84 of file stream-tcp.c.
STREAMTCP_DEFAULT_PREALLOC
#define STREAMTCP_DEFAULT_PREALLOC 2048
Definition at line 83 of file stream-tcp.c.
STREAMTCP_DEFAULT_REASSEMBLY_MEMCAP
#define STREAMTCP_DEFAULT_REASSEMBLY_MEMCAP (256 * 1024 * 1024) /* 256mb */
Definition at line 85 of file stream-tcp.c.
STREAMTCP_DEFAULT_TOCLIENT_CHUNK_SIZE
#define STREAMTCP_DEFAULT_TOCLIENT_CHUNK_SIZE 2560
Definition at line 87 of file stream-tcp.c.
STREAMTCP_DEFAULT_TOSERVER_CHUNK_SIZE
#define STREAMTCP_DEFAULT_TOSERVER_CHUNK_SIZE 2560
Definition at line 86 of file stream-tcp.c.
StreamTcpAsyncLastAckUpdate
#define StreamTcpAsyncLastAckUpdate (ssn, stream)
Value:
    {                              \
    if ((ssn)->flags & STREAMTCP_FLAG_ASYNC) {                                  \
        if (SEQ_GT((stream)->next_seq, (stream)->last_ack)) {                   \
            uint32_t ack_diff = (stream)->next_seq - (stream)->last_ack;        \
            (stream)->last_ack += ack_diff;                                     \
            SCLogDebug("ssn %p: ASYNC last_ack set to %"PRIu32", moved %u forward",     \
                    (ssn), (stream)->next_seq, ack_diff);                               \
        }                                                                       \
    }                                                                           \
}
Definition at line 829 of file stream-tcp.c.
StreamTcpUpdateLastAck
#define StreamTcpUpdateLastAck (ssn, stream, ack)
Value:
    { \
    if (SEQ_GT((ack), (stream)->last_ack)) \
    { \
        SCLogDebug("ssn %p: last_ack set to %"PRIu32", moved %u forward", (ssn), (ack), (ack) - (stream)->last_ack); \
        if ((SEQ_LEQ((stream)->last_ack, (stream)->next_seq) && SEQ_GT((ack),(stream)->next_seq))) { \
            SCLogDebug("last_ack just passed next_seq: %u (was %u) > %u", (ack), (stream)->last_ack, (stream)->next_seq); \
        } else { \
            SCLogDebug("next_seq (%u) <> last_ack now %d", (stream)->next_seq, (int)(stream)->next_seq - (ack)); \
        }\
        (stream)->last_ack = (ack); \
        StreamTcpSackPruneList((stream)); \
    } else { \
        SCLogDebug("ssn %p: no update: ack %u, last_ack %"PRIu32", next_seq %u (state %u)", \
                    (ssn), (ack), (stream)->last_ack, (stream)->next_seq, (ssn)->state); \
    }\
}
macro to update last_ack only if the new value is higher
Parameters
ssn session
stream stream to update
ack ACK value to test and set
Definition at line 812 of file stream-tcp.c.
StreamTcpUpdateNextSeq
#define StreamTcpUpdateNextSeq (ssn, stream, seq)
Value:
    {                      \
    (stream)->next_seq = seq;                                           \
    SCLogDebug("ssn %p: next_seq %" PRIu32, (ssn), (stream)->next_seq); \
    StreamTcpAsyncLastAckUpdate((ssn), (stream));                       \
}
Definition at line 840 of file stream-tcp.c.
StreamTcpUpdateNextWin
#define StreamTcpUpdateNextWin (ssn, stream, win)
Value:
    { \
    uint32_t sacked_size__ = StreamTcpSackedSize((stream)); \
    if (SEQ_GT(((win) + sacked_size__), (stream)->next_win)) { \
        (stream)->next_win = ((win) + sacked_size__); \
        SCLogDebug("ssn %p: next_win set to %"PRIu32, (ssn), (stream)->next_win); \
    } \
}
macro to update next_win only if the new value is higher
Parameters
ssn session
stream stream to update
win window value to test and set
Definition at line 853 of file stream-tcp.c.
Function Documentation
SC_ATOMIC_DECLARE()
SC_ATOMIC_DECLARE (uint64_t , st_memuse)
StreamTcp()
TmEcode StreamTcp (ThreadVars * tv, Packet * p, void * data, PacketQueueNoLock * pq)
Definition at line 5348 of file stream-tcp.c.
References StreamTcpThread_::counter_tcp_no_flow, Packet_::flow, FlowGetPacketDirection(), Packet_::pcap_cnt, PKT_IS_TCP, SCLogDebug, StatsIncr(), t_pcapcnt, TM_ECODE_OK, TOSERVER, and tv.
StreamTcpBypassEnabled()
int StreamTcpBypassEnabled (void)
Definition at line 6544 of file stream-tcp.c.
References TcpStreamCnf_::flags, stream_config, and STREAMTCP_INIT_FLAG_BYPASS.
StreamTcpCheckMemcap()
int StreamTcpCheckMemcap (uint64_t size)
Check if alloc'ing "size" would mean we're over memcap.
Return values
1 if in bounds
0 if not in bounds
Definition at line 162 of file stream-tcp.c.
References SC_ATOMIC_GET, and stream_config.
StreamTcpDecrMemuse()
void StreamTcpDecrMemuse (uint64_t size)
Definition at line 129 of file stream-tcp.c.
References BUG_ON, RunmodeIsUnittests(), SC_ATOMIC_GET, SC_ATOMIC_SUB, SCLogDebug, and StreamTcpMemuseCounter().
Referenced by StreamTcpSessionCleanup().
StreamTcpDetectLogFlush()
void StreamTcpDetectLogFlush (ThreadVars * tv, StreamTcpThread * stt, Flow * f, Packet * p, PacketQueueNoLock * pq)
create packets in both directions to flush out logging and detection before switching protocols. In IDS mode, create first in packet dir, 2nd in opposing In IPS mode, do the reverse. Flag TCP engine that data needs to be inspected regardless of how far we are wrt inspect limits.
Definition at line 6378 of file stream-tcp.c.
References TcpSession_::client, TcpStream_::flags, PKT_IS_TOSERVER, Flow_::protoctx, TcpSession_::server, STREAMTCP_STREAM_FLAG_TRIGGER_RAW, StreamTcpInlineMode(), and ts.
StreamTcpFreeConfig()
void StreamTcpFreeConfig (bool quiet)
Definition at line 667 of file stream-tcp.c.
References SCMutexLock, and StreamTcpReassembleFree().
Referenced by StreamTcpUTDeinit().
StreamTcpGetFlowState()
int StreamTcpGetFlowState (void *)
StreamTcpGetMemcap()
uint64_t StreamTcpGetMemcap (void)
Return memcap value.
Parameters
memcap memcap value
Definition at line 190 of file stream-tcp.c.
References SC_ATOMIC_GET, and stream_config.
StreamTcpIncrMemuse()
void StreamTcpIncrMemuse (uint64_t size)
Definition at line 122 of file stream-tcp.c.
References SC_ATOMIC_ADD, SCLogDebug, and StreamTcpMemuseCounter().
StreamTcpInitConfig()
void StreamTcpInitConfig (bool quiet)
To initialize the stream global configuration data.
Parameters
quiet It tells the mode of operation, if it is true nothing will be get printed.
Definition at line 359 of file stream-tcp.c.
References TcpStreamCnf_::async_oneside, ConfGet(), ConfGetBool(), ConfGetInt(), ConfGetNode(), EngineModeIsIPS(), ExceptionPolicyParse(), FatalError, TcpStreamCnf_::flags, TcpStreamCnf_::max_synack_queued, TcpStreamCnf_::midstream, TcpStreamCnf_::midstream_policy, ParseSizeStringU16(), ParseSizeStringU32(), ParseSizeStringU64(), TcpStreamCnf_::prealloc_sessions, TcpStreamCnf_::reassembly_depth, TcpStreamCnf_::reassembly_memcap_policy, TcpStreamCnf_::reassembly_toserver_chunk_size, RunmodeIsUnittests(), SC_ATOMIC_GET, SC_ATOMIC_INIT, SC_ATOMIC_SET, SC_ERR_FATAL, SC_ERR_SIZE_PARSE, SC_WARN_OPTION_OBSOLETE, SCLogDebug, SCLogError, SCLogWarning, TcpStreamCnf_::ssn_memcap_policy, stream_config, STREAMTCP_DEFAULT_MAX_SYNACK_QUEUED, STREAMTCP_DEFAULT_MEMCAP, STREAMTCP_DEFAULT_PREALLOC, STREAMTCP_DEFAULT_REASSEMBLY_MEMCAP, STREAMTCP_DEFAULT_TOSERVER_CHUNK_SIZE, STREAMTCP_INIT_FLAG_BYPASS, STREAMTCP_INIT_FLAG_CHECKSUM_VALIDATION, STREAMTCP_INIT_FLAG_DROP_INVALID, STREAMTCP_INIT_FLAG_INLINE, and WarnInvalidConfEntry.
Referenced by PreRunInit(), and StreamTcpUTInit().
StreamTcpInitMemuse()
void StreamTcpInitMemuse (void)
Definition at line 117 of file stream-tcp.c.
References SC_ATOMIC_INIT.
Referenced by UtRunTests().
StreamTcpInlineDropInvalid()
int StreamTcpInlineDropInvalid (void)
See if stream engine is dropping invalid packet in inline mode.
Return values
0 no
1 yes
Definition at line 333 of file stream-tcp.c.
References TcpStreamCnf_::flags, stream_config, STREAMTCP_INIT_FLAG_DROP_INVALID, and STREAMTCP_INIT_FLAG_INLINE.
StreamTcpInlineMode()
int StreamTcpInlineMode (void)
See if stream engine is operating in inline mode.
Return values
0 no
1 yes
Definition at line 6555 of file stream-tcp.c.
References TcpStreamCnf_::flags, stream_config, and STREAMTCP_INIT_FLAG_INLINE.
Referenced by StreamReassembleRaw(), StreamReassembleRawHasDataReady(), StreamTcpDetectLogFlush(), StreamTcpGetUsable(), and StreamTcpReassembleHandleSegment().
StreamTcpMemuseCounter()
uint64_t StreamTcpMemuseCounter (void)
Definition at line 150 of file stream-tcp.c.
References SC_ATOMIC_GET.
Referenced by StreamTcpDecrMemuse(), and StreamTcpIncrMemuse().
StreamTcpPacket()
int StreamTcpPacket (ThreadVars * tv, Packet * p, StreamTcpThread * stt, PacketQueueNoLock * pq)
Definition at line 4935 of file stream-tcp.c.
References TcpSession_::client, StreamTcpThread_::counter_tcp_rst, StreamTcpThread_::counter_tcp_syn, StreamTcpThread_::counter_tcp_synack, DEBUG_ASSERT_FLOW_LOCKED, TcpSession_::flags, Packet_::flow, Packet_::pcap_cnt, PKT_IS_TOCLIENT, PKT_IS_TOSERVER, Flow_::protoctx, SCEnter, SCLogDebug, TcpSession_::server, StatsIncr(), STREAM_PKT_BROKEN_ACK, STREAMTCP_FLAG_ASYNC, StreamTcpSetEvent, TcpStream_::tcp_flags, TCP_GET_ACK, TcpSession_::tcp_packet_flags, Packet_::tcph, TH_ACK, TH_RST, TH_SYN, and tv.
StreamTcpPseudoSetup()
Packet * StreamTcpPseudoSetup (Packet * parent, uint8_t * pkt, uint32_t len)
Function to fetch a packet from the packet allocation queue for creation of the pseudo packet from the reassembled stream.
Parameters
parent Pointer to the parent of the pseudo packet
pkt pointer to the raw packet of the parent
len length of the packet
Returns
upon success returns the pointer to the new pseudo packet otherwise NULL
Definition at line 6140 of file stream-tcp.c.
References Packet_::datalink, len, PacketCopyData(), PacketGetFromQueueOrAlloc(), Packet_::proto, Packet_::recursion_level, Packet_::root, SCEnter, SCReturnPtr, and Packet_::ts.
StreamTcpReassembleMemuseGlobalCounter()
uint64_t StreamTcpReassembleMemuseGlobalCounter (void)
Definition at line 147 of file stream-tcp-reassemble.c.
StreamTcpReturnStreamSegments()
void StreamTcpReturnStreamSegments (TcpStream * stream)
return all segments in this stream into the pool(s)
Parameters
stream the stream to cleanup
Definition at line 385 of file stream-tcp-reassemble.c.
References RB_FOREACH_SAFE, RB_REMOVE, TcpStream_::seg_tree, and StreamTcpSegmentReturntoPool().
Referenced by StreamTcpPruneSession(), StreamTcpSessionPktFree(), and StreamTcpStreamCleanup().
StreamTcpSegmentForEach()
int StreamTcpSegmentForEach (const Packet * p, uint8_t flag, StreamSegmentCallback CallbackFunc, void * data)
Definition at line 6402 of file stream-tcp.c.
Referenced by StreamSegmentForEach().
StreamTcpSegmentForSession()
int StreamTcpSegmentForSession (const Packet * p, uint8_t flag, StreamSegmentCallback CallbackFunc, void * data)
Run callback function on each TCP segment in both directions of a session.
Note
when stream engine is running in inline mode all segments are used, in IDS/non-inline mode only ack'd segments are iterated.
Must be called under flow lock.
Returns
-1 in case of error, the number of segment in case of success
Definition at line 6461 of file stream-tcp.c.
Referenced by StreamSegmentForSession().
StreamTcpSessionCleanup()
void StreamTcpSessionCleanup (TcpSession * ssn)
Session cleanup function. Does not free the ssn.
Parameters
ssn tcp session
Definition at line 209 of file stream-tcp.c.
References TcpSession_::client, TcpStateQueue_::next, TcpSession_::queue, TcpSession_::queue_len, SCEnter, SCFree, SCReturn, TcpSession_::server, StreamTcpDecrMemuse(), and StreamTcpStreamCleanup().
Referenced by StreamTcpSessionClear(), StreamTcpUTClearSession(), and UTHRemoveSessionFromFlow().
StreamTcpSessionClear()
void StreamTcpSessionClear (void * ssnptr)
Function to return the stream back to the pool. It returns the segments in the stream to the segment pool.
This function is called when the flow is destroyed, so it should free everything related to the tcp session. So including the app layer data. We are guaranteed to only get here when the flow's use_cnt is 0.
Parameters
ssn Void ptr to the ssn.
Definition at line 243 of file stream-tcp.c.
References PoolThreadReturn(), TcpSession_::res, SCEnter, and StreamTcpSessionCleanup().
StreamTcpSessionPktFree()
void StreamTcpSessionPktFree (Packet * p)
Function to return the stream segments back to the pool.
We don't clear out the app layer storage here as that is under protection of the "use_cnt" reference counter in the flow. This function is called when the use_cnt is always at least 1 (this pkt has incremented the flow use_cnt itself), so we don't bother.
Parameters
p Packet used to identify the stream.
Definition at line 277 of file stream-tcp.c.
References TcpSession_::client, Packet_::flow, Flow_::protoctx, SCEnter, SCReturn, TcpSession_::server, and StreamTcpReturnStreamSegments().
StreamTcpSetDisableRawReassemblyFlag()
void StreamTcpSetDisableRawReassemblyFlag (TcpSession * ssn, char direction)
Set the No reassembly flag for the given direction in given TCP session.
Parameters
ssn TCP Session to set the flag in
direction direction to set the flag in: 0 toserver, 1 toclient
Definition at line 6085 of file stream-tcp.c.
References TcpSession_::client, TcpStream_::flags, TcpSession_::server, and STREAMTCP_STREAM_FLAG_NEW_RAW_DISABLED.
StreamTcpSetMemcap()
int StreamTcpSetMemcap (uint64_t size)
Update memcap value.
Parameters
size new memcap value
Definition at line 175 of file stream-tcp.c.
References SC_ATOMIC_GET, SC_ATOMIC_SET, and stream_config.
StreamTcpSetOSPolicy()
void StreamTcpSetOSPolicy (TcpStream * stream, Packet * p)
Function to set the OS policy for the given stream based on the destination of the received packet.
Parameters
stream TcpStream of which os_policy needs to set
p Packet which is used to set the os policy
Definition at line 773 of file stream-tcp.c.
References GET_IPV4_DST_ADDR_PTR, GET_IPV6_DST_ADDR, TcpStream_::os_policy, OS_POLICY_BSD, OS_POLICY_BSD_RIGHT, OS_POLICY_DEFAULT, OS_POLICY_OLD_SOLARIS, OS_POLICY_SOLARIS, PKT_IS_IPV4, PKT_IS_IPV6, SCHInfoGetIPv4HostOSFlavour(), SCHInfoGetIPv6HostOSFlavour(), and SCLogDebug.
Referenced by StreamTcpReassembleHandleSegmentHandleData().
StreamTcpSetSessionBypassFlag()
void StreamTcpSetSessionBypassFlag (TcpSession * ssn)
enable bypass
Parameters
ssn TCP Session to set the flag in
direction direction to set the flag in: 0 toserver, 1 toclient
Definition at line 6096 of file stream-tcp.c.
References TcpSession_::flags, and STREAMTCP_FLAG_BYPASS.
StreamTcpSetSessionNoReassemblyFlag()
void StreamTcpSetSessionNoReassemblyFlag (TcpSession * ssn, char direction)
disable reassembly
Disable app layer and set raw inspect to no longer accept new data. Stream engine will then fully disable raw after last inspection.
Parameters
ssn TCP Session to set the flag in
direction direction to set the flag in: 0 toserver, 1 toclient
Definition at line 6069 of file stream-tcp.c.
References TcpSession_::client, TcpStream_::flags, TcpSession_::flags, TcpSession_::server, STREAMTCP_FLAG_APP_LAYER_DISABLED, and STREAMTCP_STREAM_FLAG_NEW_RAW_DISABLED.
StreamTcpSsnStateAsString()
const char * StreamTcpSsnStateAsString (const TcpSession * ssn)
Definition at line 6611 of file stream-tcp.c.
References TcpSession_::state, and StreamTcpStateAsString().
StreamTcpStateAsString()
const char * StreamTcpStateAsString (const enum TcpState state)
Definition at line 6570 of file stream-tcp.c.
References TCP_CLOSE_WAIT, TCP_CLOSED, TCP_CLOSING, TCP_ESTABLISHED, TCP_FIN_WAIT1, TCP_FIN_WAIT2, TCP_LAST_ACK, TCP_NONE, TCP_SYN_RECV, TCP_SYN_SENT, and TCP_TIME_WAIT.
Referenced by StreamTcpSsnStateAsString().
StreamTcpStreamCleanup()
void StreamTcpStreamCleanup (TcpStream * stream)
Definition at line 196 of file stream-tcp.c.
References TcpStream_::sb, StreamingBufferClear(), StreamTcpReturnStreamSegments(), and StreamTcpSackFreeList().
Referenced by StreamTcpSessionCleanup(), and StreamTcpUTClearStream().
StreamTcpThreadDeinit()
TmEcode StreamTcpThreadDeinit (ThreadVars * tv, void * data)
Definition at line 5455 of file stream-tcp.c.
References StreamTcpThread_::ra_ctx, SCEnter, SCFree, SCReturnInt, StreamTcpReassembleFreeThreadCtx(), and TM_ECODE_OK.
StreamTcpThreadInit()
TmEcode StreamTcpThreadInit (ThreadVars * tv, void * initdata, void ** data)
Definition at line 5389 of file stream-tcp.c.
References StreamTcpThread_::counter_tcp_active_sessions, StreamTcpThread_::counter_tcp_invalid_checksum, StreamTcpThread_::counter_tcp_midstream_pickups, StreamTcpThread_::counter_tcp_no_flow, StreamTcpThread_::counter_tcp_pseudo, StreamTcpThread_::counter_tcp_pseudo_failed, TcpReassemblyThreadCtx_::counter_tcp_reass_data_normal_fail, TcpReassemblyThreadCtx_::counter_tcp_reass_data_overlap_fail, TcpReassemblyThreadCtx_::counter_tcp_reass_gap, TcpReassemblyThreadCtx_::counter_tcp_reass_overlap, TcpReassemblyThreadCtx_::counter_tcp_reass_overlap_diff_data, StreamTcpThread_::counter_tcp_rst, TcpReassemblyThreadCtx_::counter_tcp_segment_memcap, StreamTcpThread_::counter_tcp_sessions, StreamTcpThread_::counter_tcp_ssn_memcap, TcpReassemblyThreadCtx_::counter_tcp_stream_depth, StreamTcpThread_::counter_tcp_syn, StreamTcpThread_::counter_tcp_synack, StreamTcpThread_::counter_tcp_wrong_thread, StreamTcpThread_::ra_ctx, SCEnter, SCLogDebug, SCMalloc, SCMutexLock, SCReturnInt, StreamTcpThread_::ssn_pool_id, StatsRegisterCounter(), StreamTcpReassembleInitThreadCtx(), TM_ECODE_FAILED, tv, and unlikely.
StreamTcpUpdateAppLayerProgress()
void StreamTcpUpdateAppLayerProgress (TcpSession * ssn, char direction, const uint32_t progress)
update reassembly progress
Parameters
ssn TCP Session
direction direction to set the flag in: 0 toserver, 1 toclient
Definition at line 6051 of file stream-tcp.c.
References TcpStream_::app_progress_rel, TcpSession_::client, and TcpSession_::server.
Referenced by AppLayerHandleTCPData().
TcpSessionPacketSsnReuse()
int TcpSessionPacketSsnReuse (const Packet * p, const Flow * f, const void * tcp_ssn)
Definition at line 5336 of file stream-tcp.c.
References Packet_::proto, and Packet_::tcph.
TcpSessionSetReassemblyDepth()
void TcpSessionSetReassemblyDepth (TcpSession * ssn, uint32_t size)
Definition at line 6561 of file stream-tcp.c.
References TcpSession_::reassembly_depth.
Variable Documentation
g_detect_disabled
int g_detect_disabled extern
global indicating if detection is enabled
Definition at line 225 of file suricata.c.
stream_config
TcpStreamCnf stream_config
Definition at line 113 of file stream-tcp.c.
Referenced by NapatechGetStreamConfig(), StreamTcpBypassEnabled(), StreamTcpCheckMemcap(), StreamTcpGetMemcap(), StreamTcpInitConfig(), StreamTcpInlineDropInvalid(), StreamTcpInlineMode(), StreamTcpReassembleCheckMemcap(), StreamTcpReassembleGetMemcap(), StreamTcpReassembleSetMemcap(), StreamTcpSetMemcap(), StreamTcpUTDeinit(), StreamTcpUTInitInline(), StreamTcpUTSetupSession(), StreamTcpUTSetupStream(), and UTHAddSessionToFlow().
t_pcapcnt
thread_local uint64_t t_pcapcnt extern
Definition at line 77 of file stream-tcp-reassemble.c.
Referenced by StreamTcp(), and StreamTcpReassembleCheckMemcap().