suricata: /Users/jlu/suricata/src/stream-tcp-inline.h File Reference
stream-tcp-inline.h File Reference
#include "stream-tcp-private.h"
Functions
int StreamTcpInlineSegmentCompare (const TcpStream *, const Packet *, const TcpSegment *)
Compare the shared data portion of two segments.
void StreamTcpInlineSegmentReplacePacket (const TcpStream *, Packet *, const TcpSegment *)
Replace (part of) the payload portion of a packet by the data in a TCP segment.
void StreamTcpInlineRegisterTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file stream-tcp-inline.h.
Function Documentation
StreamTcpInlineRegisterTests()
void StreamTcpInlineRegisterTests (void)
Definition at line 149 of file stream-tcp-inline.c.
References UtRegisterTest().
StreamTcpInlineSegmentCompare()
int StreamTcpInlineSegmentCompare (const TcpStream * stream, const Packet * p, const TcpSegment * seg)
Compare the shared data portion of two segments.
If no data is shared, 0 will be returned.
Parameters
seg1 first segment
seg2 second segment
Return values
0 shared data is the same (or no data is shared)
1 shared data is different
Definition at line 47 of file stream-tcp-inline.c.
References BUG_ON, Packet_::payload, Packet_::payload_len, TcpStream_::sb, TcpSegment::sbseg, SCEnter, SCLogDebug, SCMemcmp, SCReturnInt, seq, TcpSegment::seq, SEQ_EQ, SEQ_GT, SEQ_LT, StreamingBufferSegmentGetData(), and TCP_GET_SEQ.
StreamTcpInlineSegmentReplacePacket()
void StreamTcpInlineSegmentReplacePacket (const TcpStream * stream, Packet * p, const TcpSegment * seg)
Replace (part of) the payload portion of a packet by the data in a TCP segment.
Parameters
p Packet
seg TCP segment
Todo:
What about reassembled fragments?
What about unwrapped tunnel packets?
Definition at line 112 of file stream-tcp-inline.c.
References BUG_ON, Packet_::flags, Packet_::payload, Packet_::payload_len, PKT_STREAM_MODIFIED, TcpStream_::sb, TcpSegment::sbseg, SCEnter, SCLogDebug, SCReturn, seq, TcpSegment::seq, SEQ_GT, SEQ_LT, StreamingBufferSegmentGetData(), TCP_GET_SEQ, and TCP_SEG_LEN.