suricata: /Users/jlu/suricata/src/stream-tcp.h File Reference
stream-tcp.h File Reference
#include "stream-tcp-private.h"
#include "stream.h"
#include "stream-tcp-reassemble.h"
#include "suricata.h"
Data Structures
struct TcpStreamCnf_
struct StreamTcpThread_
Macros
#define STREAM_VERBOSE false
#define STREAMTCP_INIT_FLAG_CHECKSUM_VALIDATION BIT_U8(0)
#define STREAMTCP_INIT_FLAG_DROP_INVALID BIT_U8(1)
#define STREAMTCP_INIT_FLAG_BYPASS BIT_U8(2)
#define STREAMTCP_INIT_FLAG_INLINE BIT_U8(3)
Typedefs
typedef struct TcpStreamCnf_ TcpStreamCnf
typedef struct StreamTcpThread_ StreamTcpThread
typedef int(* StreamReassembleRawFunc) (void *data, const uint8_t *input, const uint32_t input_len, const uint64_t offset)
Enumerations
enum { STREAM_HAS_UNPROCESSED_SEGMENTS_NONE = 0 , STREAM_HAS_UNPROCESSED_SEGMENTS_NEED_ONLY_DETECTION = 1 }
Functions
void StreamTcpInitConfig (bool)
To initialize the stream global configuration data.
void StreamTcpFreeConfig (bool)
void StreamTcpRegisterTests (void)
void StreamTcpSessionPktFree (Packet *)
Function to return the stream segments back to the pool.
void StreamTcpInitMemuse (void)
void StreamTcpIncrMemuse (uint64_t)
void StreamTcpDecrMemuse (uint64_t)
int StreamTcpSetMemcap (uint64_t)
Update memcap value.
uint64_t StreamTcpGetMemcap (void)
Return memcap value.
int StreamTcpCheckMemcap (uint64_t)
Check if alloc'ing "size" would mean we're over memcap.
uint64_t StreamTcpMemuseCounter (void)
uint64_t StreamTcpReassembleMemuseGlobalCounter (void)
Packet * StreamTcpPseudoSetup (Packet *, uint8_t *, uint32_t)
Function to fetch a packet from the packet allocation queue for creation of the pseudo packet from the reassembled stream.
int StreamTcpSegmentForEach (const Packet *p, uint8_t flag, StreamSegmentCallback CallbackFunc, void *data)
int StreamTcpSegmentForSession (const Packet *p, uint8_t flag, StreamSegmentCallback CallbackFunc, void *data)
Run callback function on each TCP segment in both directions of a session.
void StreamTcpReassembleConfigEnableOverlapCheck (void)
void TcpSessionSetReassemblyDepth (TcpSession *ssn, uint32_t size)
int StreamReassembleForFrame (TcpSession *ssn, TcpStream *stream, StreamReassembleRawFunc Callback, void *cb_data, const uint64_t offset, const bool eof)
int StreamReassembleLog (TcpSession *ssn, TcpStream *stream, StreamReassembleRawFunc Callback, void *cb_data, uint64_t progress_in, uint64_t *progress_out, bool eof)
int StreamReassembleRaw (TcpSession *ssn, const Packet *p, StreamReassembleRawFunc Callback, void *cb_data, uint64_t *progress_out, bool respect_inspect_depth)
void StreamReassembleRawUpdateProgress (TcpSession *ssn, Packet *p, uint64_t progress)
update stream engine after detection
void StreamTcpDetectLogFlush (ThreadVars *tv, StreamTcpThread *stt, Flow *f, Packet *p, PacketQueueNoLock *pq)
create packets in both directions to flush out logging and detection before switching protocols. In IDS mode, create first in packet dir, 2nd in opposing In IPS mode, do the reverse. Flag TCP engine that data needs to be inspected regardless of how far we are wrt inspect limits.
const char * StreamTcpStateAsString (const enum TcpState)
const char * StreamTcpSsnStateAsString (const TcpSession *ssn)
TmEcode StreamTcp (ThreadVars *, Packet *, void *, PacketQueueNoLock *)
uint8_t StreamNeedsReassembly (const TcpSession *ssn, uint8_t direction)
see what if any work the TCP session still needs
TmEcode StreamTcpThreadInit (ThreadVars *, void *, void **)
TmEcode StreamTcpThreadDeinit (ThreadVars *tv, void *data)
int StreamTcpPacket (ThreadVars *tv, Packet *p, StreamTcpThread *stt, PacketQueueNoLock *pq)
void StreamTcpSessionClear (void *ssnptr)
Function to return the stream back to the pool. It returns the segments in the stream to the segment pool.
void StreamTcpSessionCleanup (TcpSession *ssn)
Session cleanup function. Does not free the ssn.
void StreamTcpStreamCleanup (TcpStream *stream)
int StreamTcpBypassEnabled (void)
int StreamTcpInlineDropInvalid (void)
See if stream engine is dropping invalid packet in inline mode.
int StreamTcpInlineMode (void)
See if stream engine is operating in inline mode.
int TcpSessionPacketSsnReuse (const Packet *p, const Flow *f, const void *tcp_ssn)
void StreamTcpUpdateAppLayerProgress (TcpSession *ssn, char direction, const uint32_t progress)
update reassembly progress
uint64_t StreamTcpGetAcked (const TcpStream *stream)
uint64_t StreamTcpGetUsable (const TcpStream *stream, const bool eof)
Variables
TcpStreamCnf stream_config
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Gurvinder Singh gurvi.nosp@m.nder.nosp@m.singh.nosp@m.dahi.nosp@m.ya@gm.nosp@m.ail..nosp@m.com
Definition in file stream-tcp.h.
Macro Definition Documentation
STREAM_VERBOSE
#define STREAM_VERBOSE false
Definition at line 34 of file stream-tcp.h.
STREAMTCP_INIT_FLAG_BYPASS
#define STREAMTCP_INIT_FLAG_BYPASS BIT_U8(2)
Definition at line 39 of file stream-tcp.h.
STREAMTCP_INIT_FLAG_CHECKSUM_VALIDATION
#define STREAMTCP_INIT_FLAG_CHECKSUM_VALIDATION BIT_U8(0)
Definition at line 37 of file stream-tcp.h.
STREAMTCP_INIT_FLAG_DROP_INVALID
#define STREAMTCP_INIT_FLAG_DROP_INVALID BIT_U8(1)
Definition at line 38 of file stream-tcp.h.
STREAMTCP_INIT_FLAG_INLINE
#define STREAMTCP_INIT_FLAG_INLINE BIT_U8(3)
Definition at line 40 of file stream-tcp.h.
Typedef Documentation
StreamReassembleRawFunc
typedef int(* StreamReassembleRawFunc) (void *data, const uint8_t *input, const uint32_t input_len, const uint64_t offset)
Definition at line 138 of file stream-tcp.h.
StreamTcpThread
typedef struct StreamTcpThread_ StreamTcpThread
TcpStreamCnf
typedef struct TcpStreamCnf_ TcpStreamCnf
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
STREAM_HAS_UNPROCESSED_SEGMENTS_NONE
STREAM_HAS_UNPROCESSED_SEGMENTS_NEED_ONLY_DETECTION
Definition at line 180 of file stream-tcp.h.
Function Documentation
StreamNeedsReassembly()
uint8_t StreamNeedsReassembly (const TcpSession * ssn, uint8_t direction)
see what if any work the TCP session still needs
Definition at line 878 of file stream-tcp-reassemble.c.
References StreamingBuffer_::buf_offset, TcpSession_::client, TcpStream_::flags, TcpSession_::flags, TcpStream_::sb, SCLogDebug, TcpSession_::server, STREAM_APP_PROGRESS, STREAM_BASE_OFFSET, STREAM_HAS_UNPROCESSED_SEGMENTS_NEED_ONLY_DETECTION, STREAM_HAS_UNPROCESSED_SEGMENTS_NONE, STREAM_RAW_PROGRESS, STREAMTCP_FLAG_APP_LAYER_DISABLED, and STREAMTCP_STREAM_FLAG_DISABLE_RAW.
Referenced by FlowForceReassemblyNeedReassembly().
StreamReassembleForFrame()
int StreamReassembleForFrame (TcpSession * ssn, TcpStream * stream, StreamReassembleRawFunc Callback, void * cb_data, const uint64_t offset, const bool eof)
Definition at line 1812 of file stream-tcp-reassemble.c.
References SCLogDebug, and STREAM_APP_PROGRESS.
StreamReassembleLog()
int StreamReassembleLog (TcpSession * ssn, TcpStream * stream, StreamReassembleRawFunc Callback, void * cb_data, uint64_t progress_in, uint64_t * progress_out, bool eof)
Definition at line 1889 of file stream-tcp-reassemble.c.
References TcpStream_::flags, and STREAMTCP_STREAM_FLAG_NOREASSEMBLY.
StreamReassembleRaw()
int StreamReassembleRaw (TcpSession * ssn, const Packet * p, StreamReassembleRawFunc Callback, void * cb_data, uint64_t * progress_out, bool respect_inspect_depth)
Definition at line 1824 of file stream-tcp-reassemble.c.
References StreamTcpInlineMode(), and TRUE.
Referenced by DetectEngineInspectStreamPayload().
StreamReassembleRawUpdateProgress()
void StreamReassembleRawUpdateProgress (TcpSession * ssn, Packet * p, uint64_t progress)
update stream engine after detection
Tasked with progressing the 'progress' for Raw reassembly. 2 main scenario's:
progress is != 0, so we use this
progress is 0, meaning the detect engine didn't touch raw at all. In this case we need to look into progressing raw anyway.
Additionally, this function is tasked with disabling raw reassembly if the app-layer requested to disable it.
Definition at line 1458 of file stream-tcp-reassemble.c.
References StreamingBuffer_::buf_offset, TcpSession_::client, TcpStream_::flags, TcpSession_::flags, Packet_::pcap_cnt, PKT_IS_TOSERVER, TcpStream_::raw_progress_rel, TcpStream_::sb, SCLogDebug, TcpSession_::server, STREAM_APP_PROGRESS, STREAM_BASE_OFFSET, STREAM_RAW_PROGRESS, STREAMTCP_FLAG_APP_LAYER_DISABLED, STREAMTCP_STREAM_FLAG_DISABLE_RAW, STREAMTCP_STREAM_FLAG_NEW_RAW_DISABLED, STREAMTCP_STREAM_FLAG_TRIGGER_RAW, and TcpStream_::window.
StreamTcp()
TmEcode StreamTcp (ThreadVars * tv, Packet * p, void * data, PacketQueueNoLock * pq)
Definition at line 5348 of file stream-tcp.c.
StreamTcpBypassEnabled()
int StreamTcpBypassEnabled (void)
Definition at line 6544 of file stream-tcp.c.
References TcpStreamCnf_::flags, stream_config, and STREAMTCP_INIT_FLAG_BYPASS.
StreamTcpCheckMemcap()
int StreamTcpCheckMemcap (uint64_t size)
Check if alloc'ing "size" would mean we're over memcap.
Return values
1 if in bounds
0 if not in bounds
Definition at line 162 of file stream-tcp.c.
References SC_ATOMIC_GET, and stream_config.
StreamTcpDecrMemuse()
void StreamTcpDecrMemuse (uint64_t size)
Definition at line 129 of file stream-tcp.c.
References BUG_ON, RunmodeIsUnittests(), SC_ATOMIC_GET, SC_ATOMIC_SUB, SCLogDebug, and StreamTcpMemuseCounter().
Referenced by StreamTcpSessionCleanup().
StreamTcpDetectLogFlush()
void StreamTcpDetectLogFlush (ThreadVars * tv, StreamTcpThread * stt, Flow * f, Packet * p, PacketQueueNoLock * pq)
create packets in both directions to flush out logging and detection before switching protocols. In IDS mode, create first in packet dir, 2nd in opposing In IPS mode, do the reverse. Flag TCP engine that data needs to be inspected regardless of how far we are wrt inspect limits.
Definition at line 6378 of file stream-tcp.c.
References TcpSession_::client, TcpStream_::flags, PKT_IS_TOSERVER, Flow_::protoctx, TcpSession_::server, STREAMTCP_STREAM_FLAG_TRIGGER_RAW, StreamTcpInlineMode(), and ts.
StreamTcpFreeConfig()
void StreamTcpFreeConfig (bool quiet)
Definition at line 667 of file stream-tcp.c.
References SCMutexLock, and StreamTcpReassembleFree().
Referenced by StreamTcpUTDeinit().
StreamTcpGetAcked()
uint64_t StreamTcpGetAcked (const TcpStream * stream)
Definition at line 404 of file stream-tcp-reassemble.c.
StreamTcpGetMemcap()
uint64_t StreamTcpGetMemcap (void)
Return memcap value.
Parameters
memcap memcap value
Definition at line 190 of file stream-tcp.c.
References SC_ATOMIC_GET, and stream_config.
StreamTcpGetUsable()
uint64_t StreamTcpGetUsable (const TcpStream * stream, const bool eof)
Definition at line 409 of file stream-tcp-reassemble.c.
References StreamingBuffer_::buf_offset, FALSE, MIN, TcpStream_::sb, STREAM_BASE_OFFSET, and StreamTcpInlineMode().
Referenced by FrameJsonLogOneFrame().
StreamTcpIncrMemuse()
void StreamTcpIncrMemuse (uint64_t size)
Definition at line 122 of file stream-tcp.c.
References SC_ATOMIC_ADD, SCLogDebug, and StreamTcpMemuseCounter().
StreamTcpInitConfig()
void StreamTcpInitConfig (bool quiet)
To initialize the stream global configuration data.
Parameters
quiet It tells the mode of operation, if it is true nothing will be get printed.
Definition at line 359 of file stream-tcp.c.
References TcpStreamCnf_::async_oneside, ConfGet(), ConfGetBool(), ConfGetInt(), ConfGetNode(), EngineModeIsIPS(), ExceptionPolicyParse(), FatalError, TcpStreamCnf_::flags, TcpStreamCnf_::max_synack_queued, TcpStreamCnf_::midstream, TcpStreamCnf_::midstream_policy, ParseSizeStringU16(), ParseSizeStringU32(), ParseSizeStringU64(), TcpStreamCnf_::prealloc_sessions, TcpStreamCnf_::reassembly_depth, TcpStreamCnf_::reassembly_memcap_policy, TcpStreamCnf_::reassembly_toserver_chunk_size, RunmodeIsUnittests(), SC_ATOMIC_GET, SC_ATOMIC_INIT, SC_ATOMIC_SET, SC_ERR_FATAL, SC_ERR_SIZE_PARSE, SC_WARN_OPTION_OBSOLETE, SCLogDebug, SCLogError, SCLogWarning, TcpStreamCnf_::ssn_memcap_policy, stream_config, STREAMTCP_DEFAULT_MAX_SYNACK_QUEUED, STREAMTCP_DEFAULT_MEMCAP, STREAMTCP_DEFAULT_PREALLOC, STREAMTCP_DEFAULT_REASSEMBLY_MEMCAP, STREAMTCP_DEFAULT_TOSERVER_CHUNK_SIZE, STREAMTCP_INIT_FLAG_BYPASS, STREAMTCP_INIT_FLAG_CHECKSUM_VALIDATION, STREAMTCP_INIT_FLAG_DROP_INVALID, STREAMTCP_INIT_FLAG_INLINE, and WarnInvalidConfEntry.
Referenced by PreRunInit(), and StreamTcpUTInit().
StreamTcpInitMemuse()
void StreamTcpInitMemuse (void)
Definition at line 117 of file stream-tcp.c.
References SC_ATOMIC_INIT.
Referenced by UtRunTests().
StreamTcpInlineDropInvalid()
int StreamTcpInlineDropInvalid (void)
See if stream engine is dropping invalid packet in inline mode.
Return values
0 no
1 yes
Definition at line 333 of file stream-tcp.c.
References TcpStreamCnf_::flags, stream_config, STREAMTCP_INIT_FLAG_DROP_INVALID, and STREAMTCP_INIT_FLAG_INLINE.
StreamTcpInlineMode()
int StreamTcpInlineMode (void)
See if stream engine is operating in inline mode.
Return values
0 no
1 yes
Definition at line 6555 of file stream-tcp.c.
References TcpStreamCnf_::flags, stream_config, and STREAMTCP_INIT_FLAG_INLINE.
Referenced by StreamReassembleRaw(), StreamReassembleRawHasDataReady(), StreamTcpDetectLogFlush(), StreamTcpGetUsable(), and StreamTcpReassembleHandleSegment().
StreamTcpMemuseCounter()
uint64_t StreamTcpMemuseCounter (void)
Definition at line 150 of file stream-tcp.c.
References SC_ATOMIC_GET.
Referenced by StreamTcpDecrMemuse(), and StreamTcpIncrMemuse().
StreamTcpPacket()
int StreamTcpPacket (ThreadVars * tv, Packet * p, StreamTcpThread * stt, PacketQueueNoLock * pq)
Definition at line 4935 of file stream-tcp.c.
References TcpSession_::client, StreamTcpThread_::counter_tcp_rst, StreamTcpThread_::counter_tcp_syn, StreamTcpThread_::counter_tcp_synack, DEBUG_ASSERT_FLOW_LOCKED, TcpSession_::flags, Packet_::flow, Packet_::pcap_cnt, PKT_IS_TOCLIENT, PKT_IS_TOSERVER, Flow_::protoctx, SCEnter, SCLogDebug, TcpSession_::server, StatsIncr(), STREAM_PKT_BROKEN_ACK, STREAMTCP_FLAG_ASYNC, StreamTcpSetEvent, TcpStream_::tcp_flags, TCP_GET_ACK, TcpSession_::tcp_packet_flags, Packet_::tcph, TH_ACK, TH_RST, TH_SYN, and tv.
StreamTcpPseudoSetup()
Packet * StreamTcpPseudoSetup (Packet * parent, uint8_t * pkt, uint32_t len)
Function to fetch a packet from the packet allocation queue for creation of the pseudo packet from the reassembled stream.
Parameters
parent Pointer to the parent of the pseudo packet
pkt pointer to the raw packet of the parent
len length of the packet
Returns
upon success returns the pointer to the new pseudo packet otherwise NULL
Definition at line 6140 of file stream-tcp.c.
References Packet_::datalink, len, PacketCopyData(), PacketGetFromQueueOrAlloc(), Packet_::proto, Packet_::recursion_level, Packet_::root, SCEnter, SCReturnPtr, and Packet_::ts.
StreamTcpReassembleConfigEnableOverlapCheck()
void StreamTcpReassembleConfigEnableOverlapCheck (void)
Definition at line 40 of file stream-tcp-list.c.
StreamTcpReassembleMemuseGlobalCounter()
uint64_t StreamTcpReassembleMemuseGlobalCounter (void)
Definition at line 147 of file stream-tcp-reassemble.c.
References SC_ATOMIC_GET.
Referenced by StreamTcpReassembleDecrMemuse(), and StreamTcpReassembleIncrMemuse().
StreamTcpRegisterTests()
void StreamTcpRegisterTests (void)
Definition at line 4275 of file stream-tcp.c.
References UtRegisterTest().
StreamTcpSegmentForEach()
int StreamTcpSegmentForEach (const Packet * p, uint8_t flag, StreamSegmentCallback CallbackFunc, void * data)
Definition at line 6402 of file stream-tcp.c.
Referenced by StreamSegmentForEach().
StreamTcpSegmentForSession()
int StreamTcpSegmentForSession (const Packet * p, uint8_t flag, StreamSegmentCallback CallbackFunc, void * data)
Run callback function on each TCP segment in both directions of a session.
Note
when stream engine is running in inline mode all segments are used, in IDS/non-inline mode only ack'd segments are iterated.
Must be called under flow lock.
Returns
-1 in case of error, the number of segment in case of success
Definition at line 6461 of file stream-tcp.c.
Referenced by StreamSegmentForSession().
StreamTcpSessionCleanup()
void StreamTcpSessionCleanup (TcpSession * ssn)
Session cleanup function. Does not free the ssn.
Parameters
ssn tcp session
Definition at line 209 of file stream-tcp.c.
References TcpSession_::client, TcpStateQueue_::next, TcpSession_::queue, TcpSession_::queue_len, SCEnter, SCFree, SCReturn, TcpSession_::server, StreamTcpDecrMemuse(), and StreamTcpStreamCleanup().
Referenced by StreamTcpSessionClear(), StreamTcpUTClearSession(), and UTHRemoveSessionFromFlow().
StreamTcpSessionClear()
void StreamTcpSessionClear (void * ssnptr)
Function to return the stream back to the pool. It returns the segments in the stream to the segment pool.
This function is called when the flow is destroyed, so it should free everything related to the tcp session. So including the app layer data. We are guaranteed to only get here when the flow's use_cnt is 0.
Parameters
ssn Void ptr to the ssn.
Definition at line 243 of file stream-tcp.c.
References PoolThreadReturn(), TcpSession_::res, SCEnter, and StreamTcpSessionCleanup().
StreamTcpSessionPktFree()
void StreamTcpSessionPktFree (Packet * p)
Function to return the stream segments back to the pool.
We don't clear out the app layer storage here as that is under protection of the "use_cnt" reference counter in the flow. This function is called when the use_cnt is always at least 1 (this pkt has incremented the flow use_cnt itself), so we don't bother.
Parameters
p Packet used to identify the stream.
Definition at line 277 of file stream-tcp.c.
References TcpSession_::client, Packet_::flow, Flow_::protoctx, SCEnter, SCReturn, TcpSession_::server, and StreamTcpReturnStreamSegments().
StreamTcpSetMemcap()
int StreamTcpSetMemcap (uint64_t size)
Update memcap value.
Parameters
size new memcap value
Definition at line 175 of file stream-tcp.c.
References SC_ATOMIC_GET, SC_ATOMIC_SET, and stream_config.
StreamTcpSsnStateAsString()
const char * StreamTcpSsnStateAsString (const TcpSession * ssn)
Definition at line 6611 of file stream-tcp.c.
References TcpSession_::state, and StreamTcpStateAsString().
StreamTcpStateAsString()
const char * StreamTcpStateAsString (const enum TcpState)
Definition at line 6570 of file stream-tcp.c.
References TCP_CLOSE_WAIT, TCP_CLOSED, TCP_CLOSING, TCP_ESTABLISHED, TCP_FIN_WAIT1, TCP_FIN_WAIT2, TCP_LAST_ACK, TCP_NONE, TCP_SYN_RECV, TCP_SYN_SENT, and TCP_TIME_WAIT.
Referenced by StreamTcpSsnStateAsString().
StreamTcpStreamCleanup()
void StreamTcpStreamCleanup (TcpStream * stream)
Definition at line 196 of file stream-tcp.c.
References TcpStream_::sb, StreamingBufferClear(), StreamTcpReturnStreamSegments(), and StreamTcpSackFreeList().
Referenced by StreamTcpSessionCleanup(), and StreamTcpUTClearStream().
StreamTcpThreadDeinit()
TmEcode StreamTcpThreadDeinit (ThreadVars * tv, void * data)
Definition at line 5455 of file stream-tcp.c.
References StreamTcpThread_::ra_ctx, SCEnter, SCFree, SCReturnInt, StreamTcpReassembleFreeThreadCtx(), and TM_ECODE_OK.
StreamTcpThreadInit()
TmEcode StreamTcpThreadInit (ThreadVars * tv, void * initdata, void ** data)
Definition at line 5389 of file stream-tcp.c.
References StreamTcpThread_::counter_tcp_active_sessions, StreamTcpThread_::counter_tcp_invalid_checksum, StreamTcpThread_::counter_tcp_midstream_pickups, StreamTcpThread_::counter_tcp_no_flow, StreamTcpThread_::counter_tcp_pseudo, StreamTcpThread_::counter_tcp_pseudo_failed, TcpReassemblyThreadCtx_::counter_tcp_reass_data_normal_fail, TcpReassemblyThreadCtx_::counter_tcp_reass_data_overlap_fail, TcpReassemblyThreadCtx_::counter_tcp_reass_gap, TcpReassemblyThreadCtx_::counter_tcp_reass_overlap, TcpReassemblyThreadCtx_::counter_tcp_reass_overlap_diff_data, StreamTcpThread_::counter_tcp_rst, TcpReassemblyThreadCtx_::counter_tcp_segment_memcap, StreamTcpThread_::counter_tcp_sessions, StreamTcpThread_::counter_tcp_ssn_memcap, TcpReassemblyThreadCtx_::counter_tcp_stream_depth, StreamTcpThread_::counter_tcp_syn, StreamTcpThread_::counter_tcp_synack, StreamTcpThread_::counter_tcp_wrong_thread, StreamTcpThread_::ra_ctx, SCEnter, SCLogDebug, SCMalloc, SCMutexLock, SCReturnInt, StreamTcpThread_::ssn_pool_id, StatsRegisterCounter(), StreamTcpReassembleInitThreadCtx(), TM_ECODE_FAILED, tv, and unlikely.
StreamTcpUpdateAppLayerProgress()
void StreamTcpUpdateAppLayerProgress (TcpSession * ssn, char direction, const uint32_t progress)
update reassembly progress
Parameters
ssn TCP Session
direction direction to set the flag in: 0 toserver, 1 toclient
Definition at line 6051 of file stream-tcp.c.
References TcpStream_::app_progress_rel, TcpSession_::client, and TcpSession_::server.
Referenced by AppLayerHandleTCPData().
TcpSessionPacketSsnReuse()
int TcpSessionPacketSsnReuse (const Packet * p, const Flow * f, const void * tcp_ssn)
Definition at line 5336 of file stream-tcp.c.
References Packet_::proto, and Packet_::tcph.
TcpSessionSetReassemblyDepth()
void TcpSessionSetReassemblyDepth (TcpSession * ssn, uint32_t size)
Definition at line 6561 of file stream-tcp.c.
References TcpSession_::reassembly_depth.
Variable Documentation
stream_config
TcpStreamCnf stream_config extern
Definition at line 113 of file stream-tcp.c.
Referenced by StreamTcpBypassEnabled(), StreamTcpCheckMemcap(), StreamTcpGetMemcap(), StreamTcpInitConfig(), StreamTcpInlineDropInvalid(), StreamTcpInlineMode(), and StreamTcpSetMemcap().