suricata: /Users/jlu/suricata/src/stream-tcp-reassemble.c File Reference
stream-tcp-reassemble.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "detect.h"
#include "flow.h"
#include "threads.h"
#include "conf.h"
#include "flow-util.h"
#include "threadvars.h"
#include "tm-threads.h"
#include "util-pool.h"
#include "util-unittest.h"
#include "util-print.h"
#include "util-host-os-info.h"
#include "util-unittest-helper.h"
#include "util-byte.h"
#include "util-device.h"
#include "stream-tcp.h"
#include "stream-tcp-private.h"
#include "stream-tcp-reassemble.h"
#include "stream-tcp-inline.h"
#include "stream-tcp-list.h"
#include "stream-tcp-util.h"
#include "stream.h"
#include "util-debug.h"
#include "app-layer-protos.h"
#include "app-layer.h"
#include "app-layer-events.h"
#include "app-layer-parser.h"
#include "app-layer-frames.h"
#include "detect-engine-state.h"
#include "util-profiling.h"
#include "util-validate.h"
#include "util-exception-policy.h"
#include "tests/stream-tcp-reassemble.c"
Macros
#define STREAMTCP_STREAM_FLAG_FLUSH_FLAGS
#define SET_ISN(stream, setseq)
#define MISSED_START(isn)
#define MISSED_END
#define MISSED_STEP(seq, seg, seglen, buf, buflen)
Functions
SC_ATOMIC_DECLARE (uint64_t, ra_memuse)
bool IsTcpSessionDumpingEnabled (void)
void EnableTcpSessionDumping (void)
TcpSegment * StreamTcpGetSegment (ThreadVars *tv, TcpReassemblyThreadCtx *ra_ctx)
get a segment from the pool
void StreamTcpCreateTestPacket (uint8_t *payload, uint8_t value, uint8_t payload_len, uint8_t len)
The Function to create the packet with given payload, which is used to test the reassembly of the engine.
void StreamTcpReassembleInitMemuse (void)
void StreamTcpReassembleIncrMemuse (uint64_t size)
Function to Increment the memory usage counter for the TCP reassembly segments.
void StreamTcpReassembleDecrMemuse (uint64_t size)
Function to Decrease the memory usage counter for the TCP reassembly segments.
uint64_t StreamTcpReassembleMemuseGlobalCounter (void)
int StreamTcpReassembleCheckMemcap (uint64_t size)
Function to Check the reassembly memory usage counter against the allowed max memory usage for TCP segments.
int StreamTcpReassembleSetMemcap (uint64_t size)
Update memcap value.
uint64_t StreamTcpReassembleGetMemcap ()
Return memcap value.
void * StreamTcpReassembleRealloc (void *optr, size_t orig_size, size_t size)
void StreamTcpSegmentReturntoPool (TcpSegment *seg)
Function to return the segment back to the pool.
void StreamTcpReturnStreamSegments (TcpStream *stream)
return all segments in this stream into the pool(s)
uint64_t StreamTcpGetAcked (const TcpStream *stream)
uint64_t StreamTcpGetUsable (const TcpStream *stream, const bool eof)
void StreamTcpDisableAppLayer (Flow *f)
int StreamTcpAppLayerIsDisabled (Flow *f)
int StreamTcpReassembleInit (bool quiet)
void StreamTcpReassembleFree (bool quiet)
TcpReassemblyThreadCtx * StreamTcpReassembleInitThreadCtx (ThreadVars *tv)
void StreamTcpReassembleFreeThreadCtx (TcpReassemblyThreadCtx *ra_ctx)
int StreamTcpReassembleDepthReached (Packet *p)
check if stream in pkt direction has depth reached
uint32_t StreamDataAvailableForProtoDetect (TcpStream *stream)
int StreamTcpReassembleHandleSegmentHandleData (ThreadVars *tv, TcpReassemblyThreadCtx *ra_ctx, TcpSession *ssn, TcpStream *stream, Packet *p)
Insert a packets TCP data into the stream reassembly engine.
uint8_t StreamNeedsReassembly (const TcpSession *ssn, uint8_t direction)
see what if any work the TCP session still needs
int StreamTcpReassembleAppLayer (ThreadVars *tv, TcpReassemblyThreadCtx *ra_ctx, TcpSession *ssn, TcpStream *stream, Packet *p, enum StreamUpdateDir dir)
Update the stream reassembly upon receiving a packet.
bool StreamReassembleRawHasDataReady (TcpSession *ssn, Packet *p)
does the stream engine have data to inspect?
void StreamReassembleRawUpdateProgress (TcpSession *ssn, Packet *p, uint64_t progress)
update stream engine after detection
int StreamReassembleForFrame (TcpSession *ssn, TcpStream *stream, StreamReassembleRawFunc Callback, void *cb_data, const uint64_t offset, const bool eof)
int StreamReassembleRaw (TcpSession *ssn, const Packet *p, StreamReassembleRawFunc Callback, void *cb_data, uint64_t *progress_out, bool respect_inspect_depth)
int StreamReassembleLog (TcpSession *ssn, TcpStream *stream, StreamReassembleRawFunc Callback, void *cb_data, uint64_t progress_in, uint64_t *progress_out, bool eof)
int StreamTcpReassembleHandleSegment (ThreadVars *tv, TcpReassemblyThreadCtx *ra_ctx, TcpSession *ssn, TcpStream *stream, Packet *p, PacketQueueNoLock *pq)
void StreamTcpReassembleTriggerRawReassembly (TcpSession *ssn, int direction)
Trigger RAW stream reassembly.
void StreamTcpReassemblySetMinInspectDepth (TcpSession *ssn, int direction, uint32_t depth)
int StreamTcpCheckStreamContents (uint8_t *stream_policy, uint16_t sp_size, TcpStream *stream)
The Function Checks the reassembled stream contents against predefined stream contents according to OS policy used.
void StreamTcpReassembleRegisterTests (void)
The Function Register the Unit tests to test the reassembly engine for various OS policies.
Variables
thread_local uint64_t t_pcapcnt = UINT64_MAX
Detailed Description
Author
Gurvinder Singh gurvi.nosp@m.nder.nosp@m.singh.nosp@m.dahi.nosp@m.ya@gm.nosp@m.ail..nosp@m.com
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Reference: Judy Novak, Steve Sturges: Target-Based TCP Stream Reassembly August, 2007
Definition in file stream-tcp-reassemble.c.
Macro Definition Documentation
MISSED_END
#define MISSED_END
Value:
    StreamTcpUTClearSession(&ssn);              \
    StreamTcpUTDeinit(ra_ctx);                  \
    PASS
Definition at line 2168 of file stream-tcp-reassemble.c.
MISSED_START
#define MISSED_START (isn)
Value:
    TcpReassemblyThreadCtx *ra_ctx = NULL;      \
    TcpSession ssn;                             \
    ThreadVars tv;                              \
    memset(&tv, 0, sizeof(tv));                 \
                                                \
    StreamTcpUTInit(&ra_ctx);                   \
                                                \
    StreamTcpUTSetupSession(&ssn);              \
    StreamTcpUTSetupStream(&ssn.server, (isn)); \
    StreamTcpUTSetupStream(&ssn.client, (isn)); \
                                                \
    TcpStream *stream = &ssn.client;
Definition at line 2154 of file stream-tcp-reassemble.c.
MISSED_STEP
#define MISSED_STEP (seq, seg, seglen, buf, buflen)
Value:
    StreamTcpUTAddPayload(&tv, ra_ctx, &ssn, stream, (seq), (uint8_t *)(seg), (seglen));    \
    FAIL_IF(!(VALIDATE(stream, (uint8_t *)(buf), (buflen))));
Definition at line 2173 of file stream-tcp-reassemble.c.
SET_ISN
#define SET_ISN (stream, setseq)
Value:
    (stream)->isn = (setseq);               \
    (stream)->base_seq = (setseq) + 1
unit tests and it's support functions below
Definition at line 2101 of file stream-tcp-reassemble.c.
STREAMTCP_STREAM_FLAG_FLUSH_FLAGS
#define STREAMTCP_STREAM_FLAG_FLUSH_FLAGS
Value:
        (   STREAMTCP_STREAM_FLAG_DEPTH_REACHED \
        |   STREAMTCP_STREAM_FLAG_TRIGGER_RAW   \
        |   STREAMTCP_STREAM_FLAG_NEW_RAW_DISABLED)
Function Documentation
EnableTcpSessionDumping()
void EnableTcpSessionDumping (void)
Definition at line 93 of file stream-tcp-reassemble.c.
IsTcpSessionDumpingEnabled()
bool IsTcpSessionDumpingEnabled (void) inline
Definition at line 88 of file stream-tcp-reassemble.c.
SC_ATOMIC_DECLARE()
SC_ATOMIC_DECLARE (uint64_t , ra_memuse)
StreamDataAvailableForProtoDetect()
uint32_t StreamDataAvailableForProtoDetect (TcpStream * stream)
Definition at line 680 of file stream-tcp-reassemble.c.
References StreamingBuffer_::buf_offset, DEBUG_VALIDATE_BUG_ON, StreamingBuffer_::head, RB_EMPTY, TcpStream_::sb, StreamingBuffer_::sbb_size, StreamingBuffer_::sbb_tree, and StreamingBuffer_::stream_offset.
StreamNeedsReassembly()
uint8_t StreamNeedsReassembly (const TcpSession * ssn, uint8_t direction)
see what if any work the TCP session still needs
Definition at line 878 of file stream-tcp-reassemble.c.
References StreamingBuffer_::buf_offset, TcpSession_::client, TcpStream_::flags, TcpSession_::flags, TcpStream_::sb, SCLogDebug, TcpSession_::server, STREAM_APP_PROGRESS, STREAM_BASE_OFFSET, STREAM_HAS_UNPROCESSED_SEGMENTS_NEED_ONLY_DETECTION, STREAM_HAS_UNPROCESSED_SEGMENTS_NONE, STREAM_RAW_PROGRESS, STREAMTCP_FLAG_APP_LAYER_DISABLED, and STREAMTCP_STREAM_FLAG_DISABLE_RAW.
Referenced by FlowForceReassemblyNeedReassembly().
StreamReassembleForFrame()
int StreamReassembleForFrame (TcpSession * ssn, TcpStream * stream, StreamReassembleRawFunc Callback, void * cb_data, const uint64_t offset, const bool eof)
Definition at line 1812 of file stream-tcp-reassemble.c.
References SCLogDebug, and STREAM_APP_PROGRESS.
StreamReassembleLog()
int StreamReassembleLog (TcpSession * ssn, TcpStream * stream, StreamReassembleRawFunc Callback, void * cb_data, uint64_t progress_in, uint64_t * progress_out, bool eof)
Definition at line 1889 of file stream-tcp-reassemble.c.
References TcpStream_::flags, and STREAMTCP_STREAM_FLAG_NOREASSEMBLY.
StreamReassembleRaw()
int StreamReassembleRaw (TcpSession * ssn, const Packet * p, StreamReassembleRawFunc Callback, void * cb_data, uint64_t * progress_out, bool respect_inspect_depth)
Definition at line 1824 of file stream-tcp-reassemble.c.
References StreamTcpInlineMode(), and TRUE.
Referenced by DetectEngineInspectStreamPayload().
StreamReassembleRawHasDataReady()
bool StreamReassembleRawHasDataReady (TcpSession * ssn, Packet * p)
does the stream engine have data to inspect?
Returns true if there is data to inspect. In IDS case this is about ACK'd data in the packet's direction.
In the IPS case this is about the packet itself.
Definition at line 1414 of file stream-tcp-reassemble.c.
References StreamingBuffer_::buf_offset, TcpSession_::client, FALSE, TcpStream_::flags, PKT_IS_TOSERVER, RB_EMPTY, TcpStream_::sb, TcpStream_::seg_tree, TcpSession_::server, STREAM_BASE_OFFSET, STREAM_RAW_PROGRESS, STREAMTCP_STREAM_FLAG_DISABLE_RAW, STREAMTCP_STREAM_FLAG_NOREASSEMBLY, and StreamTcpInlineMode().
StreamReassembleRawUpdateProgress()
void StreamReassembleRawUpdateProgress (TcpSession * ssn, Packet * p, uint64_t progress)
update stream engine after detection
Tasked with progressing the 'progress' for Raw reassembly. 2 main scenario's:
progress is != 0, so we use this
progress is 0, meaning the detect engine didn't touch raw at all. In this case we need to look into progressing raw anyway.
Additionally, this function is tasked with disabling raw reassembly if the app-layer requested to disable it.
Definition at line 1458 of file stream-tcp-reassemble.c.
References StreamingBuffer_::buf_offset, TcpSession_::client, TcpStream_::flags, TcpSession_::flags, Packet_::pcap_cnt, PKT_IS_TOSERVER, TcpStream_::raw_progress_rel, TcpStream_::sb, SCLogDebug, TcpSession_::server, STREAM_APP_PROGRESS, STREAM_BASE_OFFSET, STREAM_RAW_PROGRESS, STREAMTCP_FLAG_APP_LAYER_DISABLED, STREAMTCP_STREAM_FLAG_DISABLE_RAW, STREAMTCP_STREAM_FLAG_NEW_RAW_DISABLED, STREAMTCP_STREAM_FLAG_TRIGGER_RAW, and TcpStream_::window.
StreamTcpAppLayerIsDisabled()
int StreamTcpAppLayerIsDisabled (Flow * f)
Parameters
f locked flow
Definition at line 446 of file stream-tcp-reassemble.c.
References TcpSession_::flags, Flow_::proto, Flow_::protoctx, and STREAMTCP_FLAG_APP_LAYER_DISABLED.
StreamTcpCheckStreamContents()
int StreamTcpCheckStreamContents (uint8_t * stream_policy, uint16_t sp_size, TcpStream * stream)
The Function Checks the reassembled stream contents against predefined stream contents according to OS policy used.
Parameters
stream_policy Predefined value of stream for different OS policies
stream Reassembled stream returned from the reassembly functions
Definition at line 2132 of file stream-tcp-reassemble.c.
References TcpStream_::sb, and StreamingBufferCompareRawData().
StreamTcpCreateTestPacket()
void StreamTcpCreateTestPacket (uint8_t * payload, uint8_t value, uint8_t payload_len, uint8_t len)
The Function to create the packet with given payload, which is used to test the reassembly of the engine.
Parameters
payload The variable used to store the payload contents of the current packet.
value The value which current payload will have for this packet
payload_len The length of the filed payload for current packet.
len Length of the payload array
Definition at line 2115 of file stream-tcp-reassemble.c.
References len, and payload_len.
StreamTcpDisableAppLayer()
void StreamTcpDisableAppLayer (Flow * f)
Parameters
f locked flow
Definition at line 430 of file stream-tcp-reassemble.c.
References Flow_::alparser, APP_LAYER_PARSER_EOF_TC, APP_LAYER_PARSER_EOF_TS, AppLayerParserStateSetFlag(), TcpSession_::client, Flow_::protoctx, TcpSession_::server, StreamTcpDisableAppLayerReassembly, and StreamTcpSetStreamFlagAppProtoDetectionCompleted.
StreamTcpGetAcked()
uint64_t StreamTcpGetAcked (const TcpStream * stream)
Definition at line 404 of file stream-tcp-reassemble.c.
StreamTcpGetSegment()
TcpSegment * StreamTcpGetSegment (ThreadVars * tv, TcpReassemblyThreadCtx * ra_ctx)
get a segment from the pool
Return values
seg Segment from the pool or NULL
Definition at line 2036 of file stream-tcp-reassemble.c.
References PoolThreadGetById().
Referenced by StreamTcpUTAddSegmentWithByte(), and StreamTcpUTAddSegmentWithPayload().
StreamTcpGetUsable()
uint64_t StreamTcpGetUsable (const TcpStream * stream, const bool eof)
Definition at line 409 of file stream-tcp-reassemble.c.
References StreamingBuffer_::buf_offset, FALSE, MIN, TcpStream_::sb, STREAM_BASE_OFFSET, and StreamTcpInlineMode().
Referenced by FrameJsonLogOneFrame().
StreamTcpReassembleAppLayer()
int StreamTcpReassembleAppLayer (ThreadVars * tv, TcpReassemblyThreadCtx * ra_ctx, TcpSession * ssn, TcpStream * stream, Packet * p, enum StreamUpdateDir dir)
Update the stream reassembly upon receiving a packet.
For IDS mode, the stream is in the opposite direction of the packet, as the ACK-packet is ACK'ing the stream.
One of the utilities call by this function AppLayerHandleTCPData(), has a feature where it will call this very same function for the stream opposing the stream it is called with. This shouldn't cause any issues, since processing of each stream is independent of the other stream.
Definition at line 1301 of file stream-tcp-reassemble.c.
References AppLayerHandleTCPData(), Packet_::flags, TcpStream_::flags, TcpSession_::flags, Packet_::flow, PKT_PSEUDO_STREAM_END, RB_MIN, SCEnter, SCLogDebug, SCReturnInt, TcpStream_::seg_tree, TcpSession_::state, STREAM_APP_PROGRESS, STREAM_HAS_SEEN_DATA, STREAM_RIGHT_EDGE, STREAMTCP_FLAG_APP_LAYER_DISABLED, STREAMTCP_STREAM_FLAG_NOREASSEMBLY, TCP_CLOSING, and tv.
StreamTcpReassembleCheckMemcap()
int StreamTcpReassembleCheckMemcap (uint64_t size)
Function to Check the reassembly memory usage counter against the allowed max memory usage for TCP segments.
Parameters
size Size of the TCP segment and its payload length memory allocated
Return values
1 if in bounds
0 if not in bounds
Definition at line 161 of file stream-tcp-reassemble.c.
References SC_ATOMIC_GET, SCLogNotice, stream_config, t_pcapcnt, and unlikely.
Referenced by StreamTcpReassembleRealloc().
StreamTcpReassembleDecrMemuse()
void StreamTcpReassembleDecrMemuse (uint64_t size)
Function to Decrease the memory usage counter for the TCP reassembly segments.
Parameters
size Size of the TCP segment and its payload length memory allocated
Definition at line 126 of file stream-tcp-reassemble.c.
References BUG_ON, RunmodeIsUnittests(), SC_ATOMIC_GET, SC_ATOMIC_SUB, SCLogDebug, and StreamTcpReassembleMemuseGlobalCounter().
Referenced by StreamTcpReassembleRealloc().
StreamTcpReassembleDepthReached()
int StreamTcpReassembleDepthReached (Packet * p)
check if stream in pkt direction has depth reached
Parameters
p packet with LOCKED flow
Return values
1 stream has depth reached
0 stream does not have depth reached
Definition at line 583 of file stream-tcp-reassemble.c.
References TcpSession_::client, TcpStream_::flags, Packet_::flow, FLOW_PKT_TOSERVER, Packet_::flowflags, Flow_::protoctx, TcpSession_::server, and STREAMTCP_STREAM_FLAG_DEPTH_REACHED.
StreamTcpReassembleFree()
void StreamTcpReassembleFree (bool quiet)
Definition at line 505 of file stream-tcp-reassemble.c.
References SCMutexLock.
Referenced by StreamTcpFreeConfig().
StreamTcpReassembleFreeThreadCtx()
void StreamTcpReassembleFreeThreadCtx (TcpReassemblyThreadCtx * ra_ctx)
Definition at line 565 of file stream-tcp-reassemble.c.
References TcpReassemblyThreadCtx_::app_tctx, AppLayerDestroyCtxThread(), SCEnter, SCFree, and SCReturn.
Referenced by StreamTcpThreadDeinit(), and StreamTcpUTDeinit().
StreamTcpReassembleGetMemcap()
uint64_t StreamTcpReassembleGetMemcap (void)
Return memcap value.
Returns
memcap memcap value
Definition at line 197 of file stream-tcp-reassemble.c.
References SC_ATOMIC_GET, and stream_config.
StreamTcpReassembleHandleSegment()
int StreamTcpReassembleHandleSegment (ThreadVars * tv, TcpReassemblyThreadCtx * ra_ctx, TcpSession * ssn, TcpStream * stream, Packet * p, PacketQueueNoLock * pq)
Definition at line 1921 of file stream-tcp-reassemble.c.
References TcpSession_::client, DEBUG_VALIDATE_BUG_ON, Packet_::flags, Flow_::flags, Packet_::flow, FLOW_DIR_REVERSED, Packet_::payload_len, PKT_PSEUDO_STREAM_END, SCEnter, SCLogDebug, TcpSession_::server, TcpSession_::state, StreamTcpInlineMode(), TCP_CLOSED, TCP_TIME_WAIT, Packet_::tcph, TH_ACK, TH_FIN, TH_RST, UPDATE_DIR_BOTH, UPDATE_DIR_OPPOSING, and UPDATE_DIR_PACKET.
StreamTcpReassembleHandleSegmentHandleData()
int StreamTcpReassembleHandleSegmentHandleData (ThreadVars * tv, TcpReassemblyThreadCtx * ra_ctx, TcpSession * ssn, TcpStream * stream, Packet * p)
Insert a packets TCP data into the stream reassembly engine.
Return values
0 good segment, as far as we checked.
-1 insert failure due to memcap
If the retval is 0 the segment is inserted correctly, or overlap is handled, or it wasn't added because of reassembly depth.
Definition at line 704 of file stream-tcp-reassemble.c.
References TcpSession_::data_first_seen_dir, TcpStream_::flags, TcpSession_::flags, TcpStream_::os_policy, PKT_IS_TOSERVER, SCEnter, SCLogDebug, SCReturnInt, STREAMTCP_FLAG_APP_LAYER_DISABLED, STREAMTCP_STREAM_FLAG_NEW_RAW_DISABLED, and StreamTcpSetOSPolicy().
Referenced by StreamTcpUTAddPayload().
StreamTcpReassembleIncrMemuse()
void StreamTcpReassembleIncrMemuse (uint64_t size)
Function to Increment the memory usage counter for the TCP reassembly segments.
Parameters
size Size of the TCP segment and its payload length memory allocated
Definition at line 113 of file stream-tcp-reassemble.c.
References SC_ATOMIC_ADD, SCLogDebug, and StreamTcpReassembleMemuseGlobalCounter().
Referenced by StreamTcpReassembleRealloc().
StreamTcpReassembleInit()
int StreamTcpReassembleInit (bool quiet)
Definition at line 489 of file stream-tcp-reassemble.c.
References StreamTcpReassembleInitMemuse().
StreamTcpReassembleInitMemuse()
void StreamTcpReassembleInitMemuse (void)
Definition at line 102 of file stream-tcp-reassemble.c.
References SC_ATOMIC_INIT.
Referenced by StreamTcpReassembleInit(), and UtRunTests().
StreamTcpReassembleInitThreadCtx()
TcpReassemblyThreadCtx * StreamTcpReassembleInitThreadCtx (ThreadVars * tv)
Definition at line 524 of file stream-tcp-reassemble.c.
References TcpReassemblyThreadCtx_::app_tctx, AppLayerGetCtxThread(), SCEnter, SCMalloc, SCMutexLock, tv, and unlikely.
Referenced by StreamTcpThreadInit(), and StreamTcpUTInit().
StreamTcpReassembleMemuseGlobalCounter()
uint64_t StreamTcpReassembleMemuseGlobalCounter (void)
Definition at line 147 of file stream-tcp-reassemble.c.
References SC_ATOMIC_GET.
Referenced by StreamTcpReassembleDecrMemuse(), and StreamTcpReassembleIncrMemuse().
StreamTcpReassembleRealloc()
void * StreamTcpReassembleRealloc (void * optr, size_t orig_size, size_t size)
Definition at line 222 of file stream-tcp-reassemble.c.
References SCRealloc, StreamTcpReassembleCheckMemcap(), StreamTcpReassembleDecrMemuse(), and StreamTcpReassembleIncrMemuse().
StreamTcpReassembleRegisterTests()
void StreamTcpReassembleRegisterTests (void)
The Function Register the Unit tests to test the reassembly engine for various OS policies.
Definition at line 3755 of file stream-tcp-reassemble.c.
References UtRegisterTest().
StreamTcpReassembleSetMemcap()
int StreamTcpReassembleSetMemcap (uint64_t size)
Update memcap value.
Parameters
size new memcap value
Definition at line 182 of file stream-tcp-reassemble.c.
References SC_ATOMIC_GET, SC_ATOMIC_SET, and stream_config.
StreamTcpReassembleTriggerRawReassembly()
void StreamTcpReassembleTriggerRawReassembly (TcpSession * ssn, int direction)
Trigger RAW stream reassembly.
Used by AppLayerTriggerRawStreamReassembly to trigger RAW stream reassembly from the applayer, for example upon completion of a HTTP request.
It sets a flag in the stream so that the next Raw call will return the data.
Parameters
ssn TcpSession
Definition at line 2064 of file stream-tcp-reassemble.c.
References BUG_ON, TcpSession_::client, TcpStream_::flags, SCLogDebug, TcpSession_::server, and STREAMTCP_STREAM_FLAG_TRIGGER_RAW.
Referenced by AppLayerParserTriggerRawStreamReassembly().
StreamTcpReassemblySetMinInspectDepth()
void StreamTcpReassemblySetMinInspectDepth (TcpSession * ssn, int direction, uint32_t depth)
Definition at line 2081 of file stream-tcp-reassemble.c.
References BUG_ON, TcpSession_::client, TcpStream_::min_inspect_depth, SCLogDebug, and TcpSession_::server.
Referenced by SMTPProcessDataChunk().
StreamTcpReturnStreamSegments()
void StreamTcpReturnStreamSegments (TcpStream * stream)
return all segments in this stream into the pool(s)
Parameters
stream the stream to cleanup
Definition at line 385 of file stream-tcp-reassemble.c.
References RB_FOREACH_SAFE, RB_REMOVE, TcpStream_::seg_tree, and StreamTcpSegmentReturntoPool().
Referenced by StreamTcpPruneSession(), StreamTcpSessionPktFree(), and StreamTcpStreamCleanup().
StreamTcpSegmentReturntoPool()
void StreamTcpSegmentReturntoPool (TcpSegment * seg)
Function to return the segment back to the pool.
Parameters
seg Segment which will be returned back to the pool.
Definition at line 368 of file stream-tcp-reassemble.c.
References TcpSegment::pcap_hdr_storage, TcpSegmentPcapHdrStorage_::pktlen, and PoolThreadReturn().
Referenced by StreamTcpReturnStreamSegments().
Variable Documentation
t_pcapcnt
thread_local uint64_t t_pcapcnt = UINT64_MAX
Definition at line 77 of file stream-tcp-reassemble.c.
Referenced by StreamTcp(), and StreamTcpReassembleCheckMemcap().