suricata: /Users/jlu/suricata/src/stream-tcp-util.c File Reference
stream-tcp-util.c File Reference
#include "suricata-common.h"
#include "stream-tcp-reassemble.h"
#include "stream-tcp-inline.h"
#include "stream-tcp.h"
#include "stream-tcp-util.h"
#include "util-memcmp.h"
#include "util-print.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "ippair.h"
Functions
void StreamTcpUTInit (TcpReassemblyThreadCtx **ra_ctx)
void StreamTcpUTDeinit (TcpReassemblyThreadCtx *ra_ctx)
void StreamTcpUTInitInline (void)
void StreamTcpUTSetupSession (TcpSession *ssn)
void StreamTcpUTClearSession (TcpSession *ssn)
void StreamTcpUTSetupStream (TcpStream *s, uint32_t isn)
void StreamTcpUTClearStream (TcpStream *s)
int StreamTcpUTAddPayload (ThreadVars *tv, TcpReassemblyThreadCtx *ra_ctx, TcpSession *ssn, TcpStream *stream, uint32_t seq, uint8_t *payload, uint16_t len)
wrapper for StreamTcpReassembleHandleSegmentHandleData
int StreamTcpUTAddSegmentWithPayload (ThreadVars *tv, TcpReassemblyThreadCtx *ra_ctx, TcpStream *stream, uint32_t seq, uint8_t *payload, uint16_t len)
int StreamTcpUTAddSegmentWithByte (ThreadVars *tv, TcpReassemblyThreadCtx *ra_ctx, TcpStream *stream, uint32_t seq, uint8_t byte, uint16_t len)
void StreamTcpUtilRegisterTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Helper functions for the stream engine.
Definition in file stream-tcp-util.c.
Function Documentation
StreamTcpUTAddPayload()
int StreamTcpUTAddPayload (ThreadVars * tv, TcpReassemblyThreadCtx * ra_ctx, TcpSession * ssn, TcpStream * stream, uint32_t seq, uint8_t * payload, uint16_t len)
wrapper for StreamTcpReassembleHandleSegmentHandleData
Definition at line 97 of file stream-tcp-util.c.
References len, seq, StreamTcpReassembleHandleSegmentHandleData(), Packet_::tcph, tv, UTHBuildPacketReal(), and UTHFreePacket().
StreamTcpUTAddSegmentWithByte()
int StreamTcpUTAddSegmentWithByte (ThreadVars * tv, TcpReassemblyThreadCtx * ra_ctx, TcpStream * stream, uint32_t seq, uint8_t byte, uint16_t len)
Definition at line 136 of file stream-tcp-util.c.
References len, Packet_::payload, Packet_::payload_len, seq, TcpSegment::seq, StreamTcpGetSegment(), StreamTcpReassembleInsertSegment(), TCP_GET_SEQ, TCP_SEG_LEN, Packet_::tcph, tv, UTHBuildPacketReal(), and UTHFreePacket().
StreamTcpUTAddSegmentWithPayload()
int StreamTcpUTAddSegmentWithPayload (ThreadVars * tv, TcpReassemblyThreadCtx * ra_ctx, TcpStream * stream, uint32_t seq, uint8_t * payload, uint16_t len)
Definition at line 113 of file stream-tcp-util.c.
References len, Packet_::payload, Packet_::payload_len, seq, TcpSegment::seq, StreamTcpGetSegment(), StreamTcpReassembleInsertSegment(), TCP_GET_SEQ, TCP_SEG_LEN, Packet_::tcph, tv, UTHBuildPacketReal(), and UTHFreePacket().
StreamTcpUTClearSession()
void StreamTcpUTClearSession (TcpSession * ssn)
Definition at line 71 of file stream-tcp-util.c.
References TcpSession_::client, TcpSession_::server, StreamTcpSessionCleanup(), and StreamTcpUTClearStream().
StreamTcpUTClearStream()
void StreamTcpUTClearStream (TcpStream * s)
Definition at line 91 of file stream-tcp-util.c.
References StreamTcpStreamCleanup().
Referenced by StreamTcpUTClearSession().
StreamTcpUTDeinit()
void StreamTcpUTDeinit (TcpReassemblyThreadCtx * ra_ctx)
Definition at line 51 of file stream-tcp-util.c.
References TcpStreamCnf_::flags, stream_config, StreamTcpFreeConfig(), and StreamTcpReassembleFreeThreadCtx().
StreamTcpUtilRegisterTests()
void StreamTcpUtilRegisterTests (void)
Definition at line 245 of file stream-tcp-util.c.
References UtRegisterTest().
StreamTcpUTInit()
void StreamTcpUTInit (TcpReassemblyThreadCtx ** ra_ctx)
Definition at line 44 of file stream-tcp-util.c.
References IPPairInitConfig(), StreamTcpInitConfig(), and StreamTcpReassembleInitThreadCtx().
StreamTcpUTInitInline()
void StreamTcpUTInitInline (void)
Definition at line 58 of file stream-tcp-util.c.
References TcpStreamCnf_::flags, stream_config, and STREAMTCP_INIT_FLAG_INLINE.
StreamTcpUTSetupSession()
void StreamTcpUTSetupSession (TcpSession * ssn)
Definition at line 62 of file stream-tcp-util.c.
References TcpSession_::client, TcpStream_::sb, TcpStreamCnf_::sbcnf, TcpSession_::server, stream_config, and STREAMING_BUFFER_INITIALIZER.
StreamTcpUTSetupStream()
void StreamTcpUTSetupStream (TcpStream * s, uint32_t isn)
Definition at line 79 of file stream-tcp-util.c.
References TcpStream_::base_seq, TcpStream_::isn, TcpStream_::sb, TcpStreamCnf_::sbcnf, stream_config, STREAMING_BUFFER_INITIALIZER, and STREAMTCP_SET_RA_BASE_SEQ.