suricata: /Users/jlu/suricata/src/stream-tcp-reassemble.h File Reference
stream-tcp-reassemble.h File Reference
#include "stream-tcp-private.h"
#include "suricata.h"
Data Structures
struct TcpReassemblyThreadCtx_
Macros
#define OS_POLICY_DEFAULT OS_POLICY_BSD
Typedefs
typedef struct TcpReassemblyThreadCtx_ TcpReassemblyThreadCtx
Enumerations
enum {
OS_POLICY_NONE = 1 , OS_POLICY_BSD , OS_POLICY_BSD_RIGHT , OS_POLICY_OLD_LINUX ,
OS_POLICY_LINUX , OS_POLICY_OLD_SOLARIS , OS_POLICY_SOLARIS , OS_POLICY_HPUX10 ,
OS_POLICY_HPUX11 , OS_POLICY_IRIX , OS_POLICY_MACOS , OS_POLICY_WINDOWS ,
OS_POLICY_VISTA , OS_POLICY_WINDOWS2K3 , OS_POLICY_FIRST , OS_POLICY_LAST
}
enum StreamUpdateDir { UPDATE_DIR_PACKET , UPDATE_DIR_OPPOSING , UPDATE_DIR_BOTH }
Functions
void StreamTcpReassembleInitMemuse (void)
int StreamTcpReassembleHandleSegment (ThreadVars *, TcpReassemblyThreadCtx *, TcpSession *, TcpStream *, Packet *, PacketQueueNoLock *)
int StreamTcpReassembleInit (bool)
void StreamTcpReassembleFree (bool)
void * StreamTcpReassembleRealloc (void *optr, size_t orig_size, size_t size)
void StreamTcpReassembleRegisterTests (void)
The Function Register the Unit tests to test the reassembly engine for various OS policies.
TcpReassemblyThreadCtx * StreamTcpReassembleInitThreadCtx (ThreadVars *tv)
void StreamTcpReassembleFreeThreadCtx (TcpReassemblyThreadCtx *)
int StreamTcpReassembleAppLayer (ThreadVars *tv, TcpReassemblyThreadCtx *ra_ctx, TcpSession *ssn, TcpStream *stream, Packet *p, enum StreamUpdateDir dir)
Update the stream reassembly upon receiving a packet.
void StreamTcpCreateTestPacket (uint8_t *, uint8_t, uint8_t, uint8_t)
The Function to create the packet with given payload, which is used to test the reassembly of the engine.
void StreamTcpSetSessionNoReassemblyFlag (TcpSession *, char)
disable reassembly
void StreamTcpSetSessionBypassFlag (TcpSession *)
enable bypass
void StreamTcpSetDisableRawReassemblyFlag (TcpSession *, char)
Set the No reassembly flag for the given direction in given TCP session.
void StreamTcpSetOSPolicy (TcpStream *, Packet *)
Function to set the OS policy for the given stream based on the destination of the received packet.
int StreamTcpReassembleHandleSegmentHandleData (ThreadVars *tv, TcpReassemblyThreadCtx *ra_ctx, TcpSession *ssn, TcpStream *stream, Packet *p)
Insert a packets TCP data into the stream reassembly engine.
int StreamTcpReassembleInsertSegment (ThreadVars *, TcpReassemblyThreadCtx *, TcpStream *, TcpSegment *, Packet *, uint32_t pkt_seq, uint8_t *pkt_data, uint16_t pkt_datalen)
TcpSegment * StreamTcpGetSegment (ThreadVars *, TcpReassemblyThreadCtx *)
get a segment from the pool
void StreamTcpReturnStreamSegments (TcpStream *)
return all segments in this stream into the pool(s)
void StreamTcpSegmentReturntoPool (TcpSegment *)
Function to return the segment back to the pool.
void StreamTcpReassembleTriggerRawReassembly (TcpSession *, int direction)
Trigger RAW stream reassembly.
void StreamTcpPruneSession (Flow *, uint8_t)
Remove idle TcpSegments from TcpSession.
int StreamTcpReassembleDepthReached (Packet *p)
check if stream in pkt direction has depth reached
void StreamTcpReassembleIncrMemuse (uint64_t size)
Function to Increment the memory usage counter for the TCP reassembly segments.
void StreamTcpReassembleDecrMemuse (uint64_t size)
Function to Decrease the memory usage counter for the TCP reassembly segments.
int StreamTcpReassembleSetMemcap (uint64_t size)
Update memcap value.
uint64_t StreamTcpReassembleGetMemcap (void)
Return memcap value.
int StreamTcpReassembleCheckMemcap (uint64_t size)
Function to Check the reassembly memory usage counter against the allowed max memory usage for TCP segments.
uint64_t StreamTcpReassembleMemuseGlobalCounter (void)
void StreamTcpDisableAppLayer (Flow *f)
int StreamTcpAppLayerIsDisabled (Flow *f)
int StreamTcpCheckStreamContents (uint8_t *, uint16_t, TcpStream *)
The Function Checks the reassembled stream contents against predefined stream contents according to OS policy used.
bool StreamReassembleRawHasDataReady (TcpSession *ssn, Packet *p)
does the stream engine have data to inspect?
void StreamTcpReassemblySetMinInspectDepth (TcpSession *ssn, int direction, uint32_t depth)
bool IsTcpSessionDumpingEnabled (void)
void EnableTcpSessionDumping (void)
uint32_t StreamDataAvailableForProtoDetect (TcpStream *stream)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Gurvinder Singh gurvi.nosp@m.nder.nosp@m.singh.nosp@m.dahi.nosp@m.ya@gm.nosp@m.ail..nosp@m.com
Definition in file stream-tcp-reassemble.h.
Macro Definition Documentation
OS_POLICY_DEFAULT
#define OS_POLICY_DEFAULT OS_POLICY_BSD
Definition at line 83 of file stream-tcp-reassemble.h.
Typedef Documentation
TcpReassemblyThreadCtx
typedef struct TcpReassemblyThreadCtx_ TcpReassemblyThreadCtx
Enumeration Type Documentation
anonymous enum
anonymous enum
Supported OS list and default OS policy is BSD
Enumerator
OS_POLICY_NONE
OS_POLICY_BSD
OS_POLICY_BSD_RIGHT
OS_POLICY_OLD_LINUX
OS_POLICY_LINUX
OS_POLICY_OLD_SOLARIS
OS_POLICY_SOLARIS
OS_POLICY_HPUX10
OS_POLICY_HPUX11
OS_POLICY_IRIX
OS_POLICY_MACOS
OS_POLICY_WINDOWS
OS_POLICY_VISTA
OS_POLICY_WINDOWS2K3
OS_POLICY_FIRST
OS_POLICY_LAST
Definition at line 36 of file stream-tcp-reassemble.h.
StreamUpdateDir
enum StreamUpdateDir
Enumerator
UPDATE_DIR_PACKET
UPDATE_DIR_OPPOSING
UPDATE_DIR_BOTH
Definition at line 56 of file stream-tcp-reassemble.h.
Function Documentation
EnableTcpSessionDumping()
void EnableTcpSessionDumping (void)
Definition at line 93 of file stream-tcp-reassemble.c.
IsTcpSessionDumpingEnabled()
bool IsTcpSessionDumpingEnabled (void) inline
Definition at line 88 of file stream-tcp-reassemble.c.
StreamDataAvailableForProtoDetect()
uint32_t StreamDataAvailableForProtoDetect (TcpStream * stream)
Definition at line 680 of file stream-tcp-reassemble.c.
References StreamingBuffer_::buf_offset, DEBUG_VALIDATE_BUG_ON, StreamingBuffer_::head, RB_EMPTY, TcpStream_::sb, StreamingBuffer_::sbb_size, StreamingBuffer_::sbb_tree, and StreamingBuffer_::stream_offset.
StreamReassembleRawHasDataReady()
bool StreamReassembleRawHasDataReady (TcpSession * ssn, Packet * p)
does the stream engine have data to inspect?
Returns true if there is data to inspect. In IDS case this is about ACK'd data in the packet's direction.
In the IPS case this is about the packet itself.
Definition at line 1414 of file stream-tcp-reassemble.c.
References StreamingBuffer_::buf_offset, TcpSession_::client, FALSE, TcpStream_::flags, PKT_IS_TOSERVER, RB_EMPTY, TcpStream_::sb, TcpStream_::seg_tree, TcpSession_::server, STREAM_BASE_OFFSET, STREAM_RAW_PROGRESS, STREAMTCP_STREAM_FLAG_DISABLE_RAW, STREAMTCP_STREAM_FLAG_NOREASSEMBLY, and StreamTcpInlineMode().
StreamTcpAppLayerIsDisabled()
int StreamTcpAppLayerIsDisabled (Flow * f)
Parameters
f locked flow
Definition at line 446 of file stream-tcp-reassemble.c.
References TcpSession_::flags, Flow_::proto, Flow_::protoctx, and STREAMTCP_FLAG_APP_LAYER_DISABLED.
StreamTcpCheckStreamContents()
int StreamTcpCheckStreamContents (uint8_t * stream_policy, uint16_t sp_size, TcpStream * stream)
The Function Checks the reassembled stream contents against predefined stream contents according to OS policy used.
Parameters
stream_policy Predefined value of stream for different OS policies
stream Reassembled stream returned from the reassembly functions
Definition at line 2132 of file stream-tcp-reassemble.c.
References TcpStream_::sb, and StreamingBufferCompareRawData().
StreamTcpCreateTestPacket()
void StreamTcpCreateTestPacket (uint8_t * payload, uint8_t value, uint8_t payload_len, uint8_t len)
The Function to create the packet with given payload, which is used to test the reassembly of the engine.
Parameters
payload The variable used to store the payload contents of the current packet.
value The value which current payload will have for this packet
payload_len The length of the filed payload for current packet.
len Length of the payload array
Definition at line 2115 of file stream-tcp-reassemble.c.
References len, and payload_len.
StreamTcpDisableAppLayer()
void StreamTcpDisableAppLayer (Flow * f)
Parameters
f locked flow
Definition at line 430 of file stream-tcp-reassemble.c.
References Flow_::alparser, APP_LAYER_PARSER_EOF_TC, APP_LAYER_PARSER_EOF_TS, AppLayerParserStateSetFlag(), TcpSession_::client, Flow_::protoctx, TcpSession_::server, StreamTcpDisableAppLayerReassembly, and StreamTcpSetStreamFlagAppProtoDetectionCompleted.
StreamTcpGetSegment()
TcpSegment * StreamTcpGetSegment (ThreadVars * tv, TcpReassemblyThreadCtx * ra_ctx)
get a segment from the pool
Return values
seg Segment from the pool or NULL
Definition at line 2036 of file stream-tcp-reassemble.c.
References PoolThreadGetById().
Referenced by StreamTcpUTAddSegmentWithByte(), and StreamTcpUTAddSegmentWithPayload().
StreamTcpPruneSession()
void StreamTcpPruneSession (Flow * f, uint8_t flags)
Remove idle TcpSegments from TcpSession.
Checks app progress and raw progress and progresses them if needed, slides the streaming buffer, then gets rid of excess segments.
Parameters
f flow
flags direction flags
Definition at line 880 of file stream-tcp-list.c.
References TcpSession_::client, flags, TcpStream_::flags, TcpSession_::flags, Flow_::protoctx, TcpStream_::sb, SCEnter, SCLogDebug, SCReturn, TcpSession_::server, StreamingBufferClear(), STREAMTCP_FLAG_APP_LAYER_DISABLED, STREAMTCP_STREAM_FLAG_DEPTH_REACHED, STREAMTCP_STREAM_FLAG_DISABLE_RAW, STREAMTCP_STREAM_FLAG_NOREASSEMBLY, and StreamTcpReturnStreamSegments().
StreamTcpReassembleAppLayer()
int StreamTcpReassembleAppLayer (ThreadVars * tv, TcpReassemblyThreadCtx * ra_ctx, TcpSession * ssn, TcpStream * stream, Packet * p, enum StreamUpdateDir dir)
Update the stream reassembly upon receiving a packet.
For IDS mode, the stream is in the opposite direction of the packet, as the ACK-packet is ACK'ing the stream.
One of the utilities call by this function AppLayerHandleTCPData(), has a feature where it will call this very same function for the stream opposing the stream it is called with. This shouldn't cause any issues, since processing of each stream is independent of the other stream.
Definition at line 1301 of file stream-tcp-reassemble.c.
References AppLayerHandleTCPData(), Packet_::flags, TcpStream_::flags, TcpSession_::flags, Packet_::flow, PKT_PSEUDO_STREAM_END, RB_MIN, SCEnter, SCLogDebug, SCReturnInt, TcpStream_::seg_tree, TcpSession_::state, STREAM_APP_PROGRESS, STREAM_HAS_SEEN_DATA, STREAM_RIGHT_EDGE, STREAMTCP_FLAG_APP_LAYER_DISABLED, STREAMTCP_STREAM_FLAG_NOREASSEMBLY, TCP_CLOSING, and tv.
StreamTcpReassembleCheckMemcap()
int StreamTcpReassembleCheckMemcap (uint64_t size)
Function to Check the reassembly memory usage counter against the allowed max memory usage for TCP segments.
Parameters
size Size of the TCP segment and its payload length memory allocated
Return values
1 if in bounds
0 if not in bounds
Definition at line 161 of file stream-tcp-reassemble.c.
References SC_ATOMIC_GET, SCLogNotice, stream_config, t_pcapcnt, and unlikely.
Referenced by StreamTcpReassembleRealloc().
StreamTcpReassembleDecrMemuse()
void StreamTcpReassembleDecrMemuse (uint64_t size)
Function to Decrease the memory usage counter for the TCP reassembly segments.
Parameters
size Size of the TCP segment and its payload length memory allocated
Definition at line 126 of file stream-tcp-reassemble.c.
References BUG_ON, RunmodeIsUnittests(), SC_ATOMIC_GET, SC_ATOMIC_SUB, SCLogDebug, and StreamTcpReassembleMemuseGlobalCounter().
Referenced by StreamTcpReassembleRealloc().
StreamTcpReassembleDepthReached()
int StreamTcpReassembleDepthReached (Packet * p)
check if stream in pkt direction has depth reached
Parameters
p packet with LOCKED flow
Return values
1 stream has depth reached
0 stream does not have depth reached
Definition at line 583 of file stream-tcp-reassemble.c.
References TcpSession_::client, TcpStream_::flags, Packet_::flow, FLOW_PKT_TOSERVER, Packet_::flowflags, Flow_::protoctx, TcpSession_::server, and STREAMTCP_STREAM_FLAG_DEPTH_REACHED.
StreamTcpReassembleFree()
void StreamTcpReassembleFree (bool quiet)
Definition at line 505 of file stream-tcp-reassemble.c.
References SCMutexLock.
Referenced by StreamTcpFreeConfig().
StreamTcpReassembleFreeThreadCtx()
void StreamTcpReassembleFreeThreadCtx (TcpReassemblyThreadCtx * ra_ctx)
Definition at line 565 of file stream-tcp-reassemble.c.
References TcpReassemblyThreadCtx_::app_tctx, AppLayerDestroyCtxThread(), SCEnter, SCFree, and SCReturn.
Referenced by StreamTcpThreadDeinit(), and StreamTcpUTDeinit().
StreamTcpReassembleGetMemcap()
uint64_t StreamTcpReassembleGetMemcap (void)
Return memcap value.
Returns
memcap memcap value
Definition at line 197 of file stream-tcp-reassemble.c.
References SC_ATOMIC_GET, and stream_config.
StreamTcpReassembleHandleSegment()
int StreamTcpReassembleHandleSegment (ThreadVars * tv, TcpReassemblyThreadCtx * ra_ctx, TcpSession * ssn, TcpStream * stream, Packet * p, PacketQueueNoLock * pq)
Definition at line 1921 of file stream-tcp-reassemble.c.
References TcpSession_::client, DEBUG_VALIDATE_BUG_ON, Packet_::flags, Flow_::flags, Packet_::flow, FLOW_DIR_REVERSED, Packet_::payload_len, PKT_PSEUDO_STREAM_END, SCEnter, SCLogDebug, TcpSession_::server, TcpSession_::state, StreamTcpInlineMode(), TCP_CLOSED, TCP_TIME_WAIT, Packet_::tcph, TH_ACK, TH_FIN, TH_RST, UPDATE_DIR_BOTH, UPDATE_DIR_OPPOSING, and UPDATE_DIR_PACKET.
StreamTcpReassembleHandleSegmentHandleData()
int StreamTcpReassembleHandleSegmentHandleData (ThreadVars * tv, TcpReassemblyThreadCtx * ra_ctx, TcpSession * ssn, TcpStream * stream, Packet * p)
Insert a packets TCP data into the stream reassembly engine.
Return values
0 good segment, as far as we checked.
-1 insert failure due to memcap
If the retval is 0 the segment is inserted correctly, or overlap is handled, or it wasn't added because of reassembly depth.
Definition at line 704 of file stream-tcp-reassemble.c.
References TcpSession_::data_first_seen_dir, TcpStream_::flags, TcpSession_::flags, TcpStream_::os_policy, PKT_IS_TOSERVER, SCEnter, SCLogDebug, SCReturnInt, STREAMTCP_FLAG_APP_LAYER_DISABLED, STREAMTCP_STREAM_FLAG_NEW_RAW_DISABLED, and StreamTcpSetOSPolicy().
Referenced by StreamTcpUTAddPayload().
StreamTcpReassembleIncrMemuse()
void StreamTcpReassembleIncrMemuse (uint64_t size)
Function to Increment the memory usage counter for the TCP reassembly segments.
Parameters
size Size of the TCP segment and its payload length memory allocated
Definition at line 113 of file stream-tcp-reassemble.c.
References SC_ATOMIC_ADD, SCLogDebug, and StreamTcpReassembleMemuseGlobalCounter().
Referenced by StreamTcpReassembleRealloc().
StreamTcpReassembleInit()
int StreamTcpReassembleInit (bool quiet)
Definition at line 489 of file stream-tcp-reassemble.c.
References StreamTcpReassembleInitMemuse().
StreamTcpReassembleInitMemuse()
void StreamTcpReassembleInitMemuse (void)
Definition at line 102 of file stream-tcp-reassemble.c.
References SC_ATOMIC_INIT.
Referenced by StreamTcpReassembleInit(), and UtRunTests().
StreamTcpReassembleInitThreadCtx()
TcpReassemblyThreadCtx * StreamTcpReassembleInitThreadCtx (ThreadVars * tv)
Definition at line 524 of file stream-tcp-reassemble.c.
References TcpReassemblyThreadCtx_::app_tctx, AppLayerGetCtxThread(), SCEnter, SCMalloc, SCMutexLock, tv, and unlikely.
Referenced by StreamTcpThreadInit(), and StreamTcpUTInit().
StreamTcpReassembleInsertSegment()
int StreamTcpReassembleInsertSegment (ThreadVars * tv, TcpReassemblyThreadCtx * ra_ctx, TcpStream * stream, TcpSegment * seg, Packet * p, uint32_t pkt_seq, uint8_t * pkt_data, uint16_t pkt_datalen)
Returns
0 ok
-1 segment not inserted due to memcap issue
Parameters
seg segment, this function takes total ownership
In case of error, this function returns the segment to the pool
Definition at line 629 of file stream-tcp-list.c.
References SCEnter.
Referenced by StreamTcpUTAddSegmentWithByte(), and StreamTcpUTAddSegmentWithPayload().
StreamTcpReassembleMemuseGlobalCounter()
uint64_t StreamTcpReassembleMemuseGlobalCounter (void)
Definition at line 147 of file stream-tcp-reassemble.c.
StreamTcpReassembleRealloc()
void * StreamTcpReassembleRealloc (void * optr, size_t orig_size, size_t size)
Definition at line 222 of file stream-tcp-reassemble.c.
References SCRealloc, StreamTcpReassembleCheckMemcap(), StreamTcpReassembleDecrMemuse(), and StreamTcpReassembleIncrMemuse().
StreamTcpReassembleRegisterTests()
void StreamTcpReassembleRegisterTests (void)
The Function Register the Unit tests to test the reassembly engine for various OS policies.
Definition at line 3755 of file stream-tcp-reassemble.c.
References UtRegisterTest().
StreamTcpReassembleSetMemcap()
int StreamTcpReassembleSetMemcap (uint64_t size)
Update memcap value.
Parameters
size new memcap value
Definition at line 182 of file stream-tcp-reassemble.c.
References SC_ATOMIC_GET, SC_ATOMIC_SET, and stream_config.
StreamTcpReassembleTriggerRawReassembly()
void StreamTcpReassembleTriggerRawReassembly (TcpSession * ssn, int direction)
Trigger RAW stream reassembly.
Used by AppLayerTriggerRawStreamReassembly to trigger RAW stream reassembly from the applayer, for example upon completion of a HTTP request.
It sets a flag in the stream so that the next Raw call will return the data.
Parameters
ssn TcpSession
Definition at line 2064 of file stream-tcp-reassemble.c.
References BUG_ON, TcpSession_::client, TcpStream_::flags, SCLogDebug, TcpSession_::server, and STREAMTCP_STREAM_FLAG_TRIGGER_RAW.
Referenced by AppLayerParserTriggerRawStreamReassembly().
StreamTcpReassemblySetMinInspectDepth()
void StreamTcpReassemblySetMinInspectDepth (TcpSession * ssn, int direction, uint32_t depth)
Definition at line 2081 of file stream-tcp-reassemble.c.
References BUG_ON, TcpSession_::client, TcpStream_::min_inspect_depth, SCLogDebug, and TcpSession_::server.
Referenced by SMTPProcessDataChunk().
StreamTcpReturnStreamSegments()
void StreamTcpReturnStreamSegments (TcpStream * stream)
return all segments in this stream into the pool(s)
Parameters
stream the stream to cleanup
Definition at line 385 of file stream-tcp-reassemble.c.
StreamTcpSegmentReturntoPool()
void StreamTcpSegmentReturntoPool (TcpSegment * seg)
Function to return the segment back to the pool.
Parameters
seg Segment which will be returned back to the pool.
Definition at line 368 of file stream-tcp-reassemble.c.
References TcpSegment::pcap_hdr_storage, TcpSegmentPcapHdrStorage_::pktlen, and PoolThreadReturn().
Referenced by StreamTcpReturnStreamSegments().
StreamTcpSetDisableRawReassemblyFlag()
void StreamTcpSetDisableRawReassemblyFlag (TcpSession * ssn, char direction)
Set the No reassembly flag for the given direction in given TCP session.
Parameters
ssn TCP Session to set the flag in
direction direction to set the flag in: 0 toserver, 1 toclient
Definition at line 6085 of file stream-tcp.c.
References TcpSession_::client, TcpStream_::flags, TcpSession_::server, and STREAMTCP_STREAM_FLAG_NEW_RAW_DISABLED.
StreamTcpSetOSPolicy()
void StreamTcpSetOSPolicy (TcpStream * stream, Packet * p)
Function to set the OS policy for the given stream based on the destination of the received packet.
Parameters
stream TcpStream of which os_policy needs to set
p Packet which is used to set the os policy
Definition at line 773 of file stream-tcp.c.
References GET_IPV4_DST_ADDR_PTR, GET_IPV6_DST_ADDR, TcpStream_::os_policy, OS_POLICY_BSD, OS_POLICY_BSD_RIGHT, OS_POLICY_DEFAULT, OS_POLICY_OLD_SOLARIS, OS_POLICY_SOLARIS, PKT_IS_IPV4, PKT_IS_IPV6, SCHInfoGetIPv4HostOSFlavour(), SCHInfoGetIPv6HostOSFlavour(), and SCLogDebug.
Referenced by StreamTcpReassembleHandleSegmentHandleData().
StreamTcpSetSessionBypassFlag()
void StreamTcpSetSessionBypassFlag (TcpSession * ssn)
enable bypass
Parameters
ssn TCP Session to set the flag in
direction direction to set the flag in: 0 toserver, 1 toclient
Definition at line 6096 of file stream-tcp.c.
References TcpSession_::flags, and STREAMTCP_FLAG_BYPASS.
StreamTcpSetSessionNoReassemblyFlag()
void StreamTcpSetSessionNoReassemblyFlag (TcpSession * ssn, char direction)
disable reassembly
Disable app layer and set raw inspect to no longer accept new data. Stream engine will then fully disable raw after last inspection.
Parameters
ssn TCP Session to set the flag in
direction direction to set the flag in: 0 toserver, 1 toclient
Definition at line 6069 of file stream-tcp.c.
References TcpSession_::client, TcpStream_::flags, TcpSession_::flags, TcpSession_::server, STREAMTCP_FLAG_APP_LAYER_DISABLED, and STREAMTCP_STREAM_FLAG_NEW_RAW_DISABLED.