suricata: THashDataConfig_ Struct Reference
THashDataConfig_ Struct Reference
#include <util-thash.h>
Data Fields
uint64_t memcap
uint32_t hash_rand
uint32_t hash_size
uint32_t prealloc
uint32_t data_size
int(* DataSet)(void *dst, void *src)
void(* DataFree)(void *)
uint32_t(* DataHash)(void *)
bool(* DataCompare)(void *, void *)
Detailed Description
Definition at line 126 of file util-thash.h.
Field Documentation
data_size
uint32_t THashDataConfig_::data_size
Definition at line 132 of file util-thash.h.
Referenced by THashInit().
DataCompare
bool(* THashDataConfig_::DataCompare) (void *, void *)
Definition at line 136 of file util-thash.h.
Referenced by THashInit().
DataFree
void(* THashDataConfig_::DataFree) (void *)
Definition at line 134 of file util-thash.h.
Referenced by THashInit().
DataHash
uint32_t(* THashDataConfig_::DataHash) (void *)
Definition at line 135 of file util-thash.h.
Referenced by THashInit().
DataSet
int(* THashDataConfig_::DataSet) (void *dst, void *src)
Definition at line 133 of file util-thash.h.
Referenced by THashInit().
hash_rand
uint32_t THashDataConfig_::hash_rand
Definition at line 128 of file util-thash.h.
Referenced by THashInit().
hash_size
uint32_t THashDataConfig_::hash_size
Definition at line 129 of file util-thash.h.
Referenced by THashCleanup(), THashInit(), and THashWalk().
memcap
uint64_t THashDataConfig_::memcap
Definition at line 127 of file util-thash.h.
Referenced by THashConsolidateMemcap(), and THashInit().
prealloc
uint32_t THashDataConfig_::prealloc
Definition at line 130 of file util-thash.h.
Referenced by THashInit().
The documentation for this struct was generated from the following file:
/Users/jlu/suricata/src/util-thash.h