suricata: SpmTableElmt_ Struct Reference
SpmTableElmt_ Struct Reference
#include <util-spm.h>
Data Fields
const char * name
SpmGlobalThreadCtx *(* InitGlobalThreadCtx)(void)
void(* DestroyGlobalThreadCtx)(SpmGlobalThreadCtx *g_thread_ctx)
SpmThreadCtx *(* MakeThreadCtx)(const SpmGlobalThreadCtx *g_thread_ctx)
void(* DestroyThreadCtx)(SpmThreadCtx *thread_ctx)
SpmCtx *(* InitCtx)(const uint8_t *needle, uint16_t needle_len, int nocase, SpmGlobalThreadCtx *g_thread_ctx)
void(* DestroyCtx)(SpmCtx *)
uint8_t *(* Scan)(const SpmCtx *ctx, SpmThreadCtx *thread_ctx, const uint8_t *haystack, uint32_t haystack_len)
Detailed Description
Definition at line 59 of file util-spm.h.
Field Documentation
DestroyCtx
void(* SpmTableElmt_::DestroyCtx) (SpmCtx *)
Definition at line 67 of file util-spm.h.
Referenced by SpmDestroyCtx().
DestroyGlobalThreadCtx
void(* SpmTableElmt_::DestroyGlobalThreadCtx) (SpmGlobalThreadCtx *g_thread_ctx)
Definition at line 62 of file util-spm.h.
Referenced by SpmDestroyGlobalThreadCtx().
DestroyThreadCtx
void(* SpmTableElmt_::DestroyThreadCtx) (SpmThreadCtx *thread_ctx)
Definition at line 64 of file util-spm.h.
Referenced by SpmDestroyThreadCtx().
InitCtx
SpmCtx *(* SpmTableElmt_::InitCtx) (const uint8_t *needle, uint16_t needle_len, int nocase, SpmGlobalThreadCtx *g_thread_ctx)
Definition at line 65 of file util-spm.h.
Referenced by SpmInitCtx().
InitGlobalThreadCtx
SpmGlobalThreadCtx *(* SpmTableElmt_::InitGlobalThreadCtx) (void)
Definition at line 61 of file util-spm.h.
Referenced by SpmBMRegister(), and SpmInitGlobalThreadCtx().
MakeThreadCtx
SpmThreadCtx *(* SpmTableElmt_::MakeThreadCtx) (const SpmGlobalThreadCtx *g_thread_ctx)
Definition at line 63 of file util-spm.h.
Referenced by SpmMakeThreadCtx().
name
const char* SpmTableElmt_::name
Definition at line 60 of file util-spm.h.
Referenced by SpmBMRegister().
Scan
uint8_t *(* SpmTableElmt_::Scan) (const SpmCtx *ctx, SpmThreadCtx *thread_ctx, const uint8_t *haystack, uint32_t haystack_len)
Definition at line 68 of file util-spm.h.
Referenced by SpmScan().
The documentation for this struct was generated from the following file:
/Users/jlu/suricata/src/util-spm.h