suricata: OutputFlowLogger_ Struct Reference
OutputFlowLogger_ Struct Reference
Data Fields
FlowLogger LogFunc
OutputCtx * output_ctx
struct OutputFlowLogger_ * next
const char * name
TmEcode(* ThreadInit)(ThreadVars *, const void *, void **)
TmEcode(* ThreadDeinit)(ThreadVars *, void *)
void(* ThreadExitPrintStats)(ThreadVars *, void *)
Detailed Description
Definition at line 42 of file output-flow.c.
Field Documentation
LogFunc
FlowLogger OutputFlowLogger_::LogFunc
Definition at line 43 of file output-flow.c.
Referenced by OutputRegisterFlowLogger().
name
const char* OutputFlowLogger_::name
Definition at line 46 of file output-flow.c.
Referenced by OutputRegisterFlowLogger().
next
struct OutputFlowLogger_* OutputFlowLogger_::next
Definition at line 45 of file output-flow.c.
output_ctx
OutputCtx* OutputFlowLogger_::output_ctx
Definition at line 44 of file output-flow.c.
Referenced by OutputRegisterFlowLogger().
ThreadDeinit
TmEcode(* OutputFlowLogger_::ThreadDeinit) (ThreadVars *, void *)
Definition at line 48 of file output-flow.c.
Referenced by OutputRegisterFlowLogger().
ThreadExitPrintStats
void(* OutputFlowLogger_::ThreadExitPrintStats) (ThreadVars *, void *)
Definition at line 49 of file output-flow.c.
Referenced by OutputRegisterFlowLogger().
ThreadInit
TmEcode(* OutputFlowLogger_::ThreadInit) (ThreadVars *, const void *, void **)
Definition at line 47 of file output-flow.c.
Referenced by OutputRegisterFlowLogger().
The documentation for this struct was generated from the following file:
/Users/jlu/suricata/src/output-flow.c