suricata: TmSlot_ Struct Reference
TmSlot_ Struct Reference
#include <tm-threads.h>
Public Member Functions
SC_ATOMIC_DECLARE (void *, slot_data)
Data Fields
union {
TmSlotFunc SlotFunc
TmEcode(* PktAcqLoop)(ThreadVars *, void *, void *)
TmEcode(* Management)(ThreadVars *, void *)
};
struct TmSlot_ * slot_next
TmEcode(* SlotThreadInit)(ThreadVars *, const void *, void **)
void(* SlotThreadExitPrintStats)(ThreadVars *, void *)
TmEcode(* SlotThreadDeinit)(ThreadVars *, void *)
const void * slot_initdata
int tm_id
Detailed Description
Definition at line 52 of file tm-threads.h.
Member Function Documentation
SC_ATOMIC_DECLARE()
TmSlot_::SC_ATOMIC_DECLARE (void * , slot_data)
Field Documentation
union { ... } TmSlot_::@144
Management
TmEcode(* TmSlot_::Management) (ThreadVars *, void *)
Definition at line 57 of file tm-threads.h.
Referenced by TmSlotSetFuncAppend().
PktAcqLoop
TmEcode(* TmSlot_::PktAcqLoop) (ThreadVars *, void *, void *)
Definition at line 56 of file tm-threads.h.
Referenced by TmSlotSetFuncAppend().
slot_initdata
const void* TmSlot_::slot_initdata
Definition at line 70 of file tm-threads.h.
Referenced by TmSlotSetFuncAppend().
slot_next
struct TmSlot_* TmSlot_::slot_next
linked list of slots, used when a pipeline has multiple slots in a single thread.
Definition at line 61 of file tm-threads.h.
Referenced by ReceiveErfDagLoop(), ReceivePfringLoop(), TmSlotSetFuncAppend(), TmThreadDisableReceiveThreads(), and TmThreadsSlotVarRun().
SlotFunc
TmSlotFunc TmSlot_::SlotFunc
Definition at line 55 of file tm-threads.h.
Referenced by TmSlotSetFuncAppend().
SlotThreadDeinit
TmEcode(* TmSlot_::SlotThreadDeinit) (ThreadVars *, void *)
Definition at line 67 of file tm-threads.h.
Referenced by TmSlotSetFuncAppend().
SlotThreadExitPrintStats
void(* TmSlot_::SlotThreadExitPrintStats) (ThreadVars *, void *)
Definition at line 66 of file tm-threads.h.
Referenced by TmSlotSetFuncAppend().
SlotThreadInit
TmEcode(* TmSlot_::SlotThreadInit) (ThreadVars *, const void *, void **)
Definition at line 65 of file tm-threads.h.
Referenced by TmSlotSetFuncAppend().
tm_id
int TmSlot_::tm_id
Definition at line 72 of file tm-threads.h.
Referenced by TmSlotSetFuncAppend(), and TmThreadDisableReceiveThreads().
The documentation for this struct was generated from the following file:
/Users/jlu/suricata/src/tm-threads.h