suricata: MpmTableElmt_ Struct Reference
MpmTableElmt_ Struct Reference
#include <util-mpm.h>
Data Fields
const char * name
void(* InitCtx)(struct MpmCtx_ *)
void(* InitThreadCtx)(struct MpmCtx_ *, struct MpmThreadCtx_ *)
void(* DestroyCtx)(struct MpmCtx_ *)
void(* DestroyThreadCtx)(struct MpmCtx_ *, struct MpmThreadCtx_ *)
int(* AddPattern)(struct MpmCtx_ *, uint8_t *, uint16_t, uint16_t, uint16_t, uint32_t, SigIntId, uint8_t)
int(* AddPatternNocase)(struct MpmCtx_ *, uint8_t *, uint16_t, uint16_t, uint16_t, uint32_t, SigIntId, uint8_t)
int(* Prepare)(struct MpmCtx_ *)
uint32_t(* Search)(const struct MpmCtx_ *, struct MpmThreadCtx_ *, PrefilterRuleStore *, const uint8_t *, uint32_t)
void(* PrintCtx)(struct MpmCtx_ *)
void(* PrintThreadCtx)(struct MpmThreadCtx_ *)
void(* RegisterUnittests)(void)
uint8_t flags
Detailed Description
Definition at line 144 of file util-mpm.h.
Field Documentation
AddPattern
int(* MpmTableElmt_::AddPattern) (struct MpmCtx_ *, uint8_t *, uint16_t, uint16_t, uint16_t, uint32_t, SigIntId, uint8_t)
function pointers for adding patterns to the mpm ctx.
Parameters
mpm_ctx Mpm context to add the pattern to
pattern pointer to the pattern
pattern_len length of the pattern in bytes
offset pattern offset setting
depth pattern depth setting
pid pattern id
sid signature internal id
flags pattern flags
Definition at line 162 of file util-mpm.h.
Referenced by MpmACBSRegister(), MpmACRegister(), MpmACTileRegister(), and MpmAddPatternCS().
AddPatternNocase
int(* MpmTableElmt_::AddPatternNocase) (struct MpmCtx_ *, uint8_t *, uint16_t, uint16_t, uint16_t, uint32_t, SigIntId, uint8_t)
Definition at line 163 of file util-mpm.h.
Referenced by MpmACBSRegister(), MpmACRegister(), MpmACTileRegister(), and MpmAddPatternCI().
DestroyCtx
void(* MpmTableElmt_::DestroyCtx) (struct MpmCtx_ *)
Definition at line 148 of file util-mpm.h.
Referenced by MpmACBSRegister(), MpmACRegister(), MpmACTileRegister(), MpmFactoryDeRegisterAllMpmCtxProfiles(), MpmFactoryReClaimMpmCtx(), and PatternMatchDestroy().
DestroyThreadCtx
void(* MpmTableElmt_::DestroyThreadCtx) (struct MpmCtx_ *, struct MpmThreadCtx_ *)
Definition at line 149 of file util-mpm.h.
Referenced by MpmACBSRegister(), MpmACRegister(), MpmACTileRegister(), and PatternMatchThreadDestroy().
flags
uint8_t MpmTableElmt_::flags
Definition at line 169 of file util-mpm.h.
InitCtx
void(* MpmTableElmt_::InitCtx) (struct MpmCtx_ *)
Definition at line 146 of file util-mpm.h.
Referenced by MpmACBSRegister(), MpmACRegister(), MpmACTileRegister(), and MpmInitCtx().
InitThreadCtx
void(* MpmTableElmt_::InitThreadCtx) (struct MpmCtx_ *, struct MpmThreadCtx_ *)
Definition at line 147 of file util-mpm.h.
Referenced by MpmACBSRegister(), MpmACRegister(), MpmACTileRegister(), and MpmInitThreadCtx().
name
const char* MpmTableElmt_::name
Definition at line 145 of file util-mpm.h.
Referenced by MpmACBSRegister(), MpmACRegister(), and MpmACTileRegister().
Prepare
int(* MpmTableElmt_::Prepare) (struct MpmCtx_ *)
Definition at line 164 of file util-mpm.h.
Referenced by DetectMpmPrepareAppMpms(), DetectMpmPrepareBuiltinMpms(), DetectMpmPrepareFrameMpms(), DetectMpmPreparePktMpms(), MpmACBSRegister(), MpmACRegister(), and MpmACTileRegister().
PrintCtx
void(* MpmTableElmt_::PrintCtx) (struct MpmCtx_ *)
Definition at line 166 of file util-mpm.h.
Referenced by MpmACBSRegister(), MpmACRegister(), and MpmACTileRegister().
PrintThreadCtx
void(* MpmTableElmt_::PrintThreadCtx) (struct MpmThreadCtx_ *)
Definition at line 167 of file util-mpm.h.
Referenced by MpmACBSRegister(), MpmACRegister(), and MpmACTileRegister().
RegisterUnittests
void(* MpmTableElmt_::RegisterUnittests) (void)
Definition at line 168 of file util-mpm.h.
Referenced by MpmACBSRegister(), MpmACRegister(), and MpmACTileRegister().
Search
uint32_t(* MpmTableElmt_::Search) (const struct MpmCtx_ *, struct MpmThreadCtx_ *, PrefilterRuleStore *, const uint8_t *, uint32_t)
Definition at line 165 of file util-mpm.h.
Referenced by MpmACBSRegister(), MpmACRegister(), and MpmACTileRegister().
The documentation for this struct was generated from the following file:
/Users/jlu/suricata/src/util-mpm.h