suricata: Tmqh_ Struct Reference
Tmqh_ Struct Reference
#include <tm-queuehandlers.h>
Data Fields
const char * name
Packet *(* InHandler)(ThreadVars *)
void(* InShutdownHandler)(ThreadVars *)
void(* OutHandler)(ThreadVars *, Packet *)
void *(* OutHandlerCtxSetup)(const char *)
void(* OutHandlerCtxFree)(void *)
void(* RegisterTests)(void)
Detailed Description
Definition at line 36 of file tm-queuehandlers.h.
Field Documentation
InHandler
Packet *(* Tmqh_::InHandler) (ThreadVars *)
Definition at line 38 of file tm-queuehandlers.h.
Referenced by TmqhFlowRegister(), TmqhPacketpoolRegister(), TmqhSimpleRegister(), and TmThreadCreate().
InShutdownHandler
void(* Tmqh_::InShutdownHandler) (ThreadVars *)
Definition at line 39 of file tm-queuehandlers.h.
Referenced by TmqhSimpleRegister().
name
const char* Tmqh_::name
Definition at line 37 of file tm-queuehandlers.h.
Referenced by TmqhFlowRegister(), TmqhPacketpoolRegister(), and TmqhSimpleRegister().
OutHandler
void(* Tmqh_::OutHandler) (ThreadVars *, Packet *)
Definition at line 40 of file tm-queuehandlers.h.
Referenced by TmqhFlowRegister(), TmqhPacketpoolRegister(), TmqhSimpleRegister(), and TmThreadCreate().
OutHandlerCtxFree
void(* Tmqh_::OutHandlerCtxFree) (void *)
Definition at line 42 of file tm-queuehandlers.h.
Referenced by TmqhFlowRegister().
OutHandlerCtxSetup
void *(* Tmqh_::OutHandlerCtxSetup) (const char *)
Definition at line 41 of file tm-queuehandlers.h.
Referenced by TmqhFlowRegister(), and TmThreadCreate().
RegisterTests
void(* Tmqh_::RegisterTests) (void)
Definition at line 43 of file tm-queuehandlers.h.
Referenced by TmqhFlowRegister().
The documentation for this struct was generated from the following file:
/Users/jlu/suricata/src/tm-queuehandlers.h