suricata: HashTable_ Struct Reference
HashTable_ Struct Reference
#include <util-hash.h>
Data Fields
HashTableBucket ** array
uint32_t array_size
uint32_t count
uint32_t(* Hash)(struct HashTable_ *, void *, uint16_t)
char(* Compare)(void *, uint16_t, void *, uint16_t)
void(* Free)(void *)
Detailed Description
Definition at line 35 of file util-hash.h.
Field Documentation
array
HashTableBucket** HashTable_::array
Definition at line 36 of file util-hash.h.
Referenced by HashTableAdd(), HashTableFree(), HashTableInit(), HashTableLookup(), and HashTableRemove().
array_size
uint32_t HashTable_::array_size
Definition at line 37 of file util-hash.h.
Referenced by HashTableAdd(), HashTableFree(), HashTableGenericHash(), HashTableInit(), HashTableLookup(), HashTablePrint(), SCClassConfClasstypeHashFunc(), SCRConfReferenceHashFunc(), and StringHashFunc().
Compare
char(* HashTable_::Compare) (void *, uint16_t, void *, uint16_t)
Definition at line 42 of file util-hash.h.
Referenced by HashTableInit(), HashTableLookup(), and HashTableRemove().
count
uint32_t HashTable_::count
Definition at line 39 of file util-hash.h.
Referenced by HashTableAdd().
Free
void(* HashTable_::Free) (void *)
Definition at line 43 of file util-hash.h.
Referenced by HashTableFree(), HashTableInit(), and HashTableRemove().
Hash
uint32_t(* HashTable_::Hash) (struct HashTable_ *, void *, uint16_t)
Definition at line 41 of file util-hash.h.
Referenced by HashTableAdd(), HashTableInit(), HashTableLookup(), HashTablePrint(), and HashTableRemove().
The documentation for this struct was generated from the following file:
/Users/jlu/suricata/src/util-hash.h