suricata: SCEveFileType_ Struct Reference
SCEveFileType_ Struct Reference
#include <suricata-plugin.h>
Public Member Functions
TAILQ_ENTRY (SCEveFileType_) entries
Data Fields
const char * name
int(* Init)(ConfNode *conf, bool threaded, void **init_data)
int(* Write)(const char *buffer, int buffer_len, void *init_data, void *thread_data)
void(* Deinit)(void *init_data)
int(* ThreadInit)(void *init_data, int thread_id, void **thread_data)
int(* ThreadDeinit)(void *init_data, void *thread_data)
Detailed Description
Structure used to define an Eve output file type plugin.
Definition at line 47 of file suricata-plugin.h.
Member Function Documentation
TAILQ_ENTRY()
SCEveFileType_::TAILQ_ENTRY (SCEveFileType_)
Field Documentation
Deinit
void(* SCEveFileType_::Deinit) (void *init_data)
Definition at line 56 of file suricata-plugin.h.
Referenced by LogFileFreeCtx().
Init
int(* SCEveFileType_::Init) (ConfNode *conf, bool threaded, void **init_data)
Definition at line 52 of file suricata-plugin.h.
Referenced by SyslogInitialize().
name
const char* SCEveFileType_::name
Definition at line 50 of file suricata-plugin.h.
Referenced by SyslogInitialize().
ThreadDeinit
int(* SCEveFileType_::ThreadDeinit) (void *init_data, void *thread_data)
Definition at line 60 of file suricata-plugin.h.
Referenced by LogFileFreeCtx().
ThreadInit
int(* SCEveFileType_::ThreadInit) (void *init_data, int thread_id, void **thread_data)
Definition at line 58 of file suricata-plugin.h.
Write
int(* SCEveFileType_::Write) (const char *buffer, int buffer_len, void *init_data, void *thread_data)
Definition at line 54 of file suricata-plugin.h.
Referenced by LogFileWrite().
The documentation for this struct was generated from the following file:
/Users/jlu/suricata/src/suricata-plugin.h