suricata: Pool_ Struct Reference
Pool_ Struct Reference
#include <util-pool.h>
Data Fields
uint32_t max_buckets
uint32_t preallocated
uint32_t allocated
uint32_t alloc_stack_size
PoolBucket * alloc_stack
PoolBucket * empty_stack
uint32_t empty_stack_size
int data_buffer_size
void * data_buffer
PoolBucket * pb_buffer
void *(* Alloc)(void)
int(* Init)(void *, void *)
void * InitData
void(* Cleanup)(void *)
void(* Free)(void *)
uint32_t elt_size
uint32_t outstanding
Detailed Description
Definition at line 43 of file util-pool.h.
Field Documentation
Alloc
void *(* Pool_::Alloc) (void)
Definition at line 60 of file util-pool.h.
Referenced by PoolGet(), PoolInit(), and PoolThreadExpand().
alloc_stack
PoolBucket* Pool_::alloc_stack
Definition at line 51 of file util-pool.h.
Referenced by PoolFree(), and PoolGet().
alloc_stack_size
uint32_t Pool_::alloc_stack_size
Definition at line 49 of file util-pool.h.
Referenced by PoolGet(), and PoolPrint().
allocated
uint32_t Pool_::allocated
counter of data elements, both currently in the pool and outside of it (outstanding)
Definition at line 46 of file util-pool.h.
Referenced by PoolGet(), and PoolReturn().
Cleanup
void(* Pool_::Cleanup) (void *)
Definition at line 63 of file util-pool.h.
Referenced by PoolFree(), PoolInit(), PoolReturn(), and PoolThreadExpand().
data_buffer
void* Pool_::data_buffer
Definition at line 57 of file util-pool.h.
data_buffer_size
int Pool_::data_buffer_size
Definition at line 56 of file util-pool.h.
Referenced by PoolInit().
elt_size
uint32_t Pool_::elt_size
Definition at line 66 of file util-pool.h.
Referenced by PoolGet(), PoolInit(), and PoolThreadExpand().
empty_stack
PoolBucket* Pool_::empty_stack
Definition at line 53 of file util-pool.h.
Referenced by PoolGet(), and PoolReturn().
empty_stack_size
uint32_t Pool_::empty_stack_size
Definition at line 54 of file util-pool.h.
Referenced by PoolGet(), and PoolPrint().
Free
void(* Pool_::Free) (void *)
Definition at line 64 of file util-pool.h.
Referenced by PoolGet(), PoolInit(), and PoolThreadExpand().
Init
int(* Pool_::Init) (void *, void *)
Definition at line 61 of file util-pool.h.
Referenced by PoolGet(), PoolInit(), and PoolThreadExpand().
InitData
void* Pool_::InitData
Definition at line 62 of file util-pool.h.
Referenced by PoolGet(), PoolInit(), and PoolThreadExpand().
max_buckets
uint32_t Pool_::max_buckets
Definition at line 44 of file util-pool.h.
Referenced by PoolGet(), PoolInit(), PoolPrintSaturation(), and PoolThreadExpand().
outstanding
uint32_t Pool_::outstanding
counter of data items 'in use'. Pretty much the diff between PoolGet and PoolReturn
Definition at line 67 of file util-pool.h.
Referenced by PoolGet(), PoolPrintSaturation(), and PoolReturn().
pb_buffer
PoolBucket* Pool_::pb_buffer
Definition at line 58 of file util-pool.h.
preallocated
uint32_t Pool_::preallocated
Definition at line 45 of file util-pool.h.
Referenced by PoolInit(), and PoolThreadExpand().
The documentation for this struct was generated from the following file:
/Users/jlu/suricata/src/util-pool.h