suricata: TmModule_ Struct Reference
TmModule_ Struct Reference
#include <tm-modules.h>
Data Fields
const char * name
TmEcode(* ThreadInit)(ThreadVars *, const void *, void **)
void(* ThreadExitPrintStats)(ThreadVars *, void *)
TmEcode(* ThreadDeinit)(ThreadVars *, void *)
TmEcode(* Func)(ThreadVars *, Packet *, void *)
TmEcode(* PktAcqLoop)(ThreadVars *, void *, void *)
TmEcode(* PktAcqBreakLoop)(ThreadVars *, void *)
TmEcode(* Management)(ThreadVars *, void *)
TmEcode(* Init)(void)
TmEcode(* DeInit)(void)
void(* RegisterTests)(void)
uint8_t cap_flags
uint8_t flags
Detailed Description
Definition at line 43 of file tm-modules.h.
Field Documentation
cap_flags
uint8_t TmModule_::cap_flags
Flags to indicate the capability requierment of the given TmModule
Definition at line 67 of file tm-modules.h.
Referenced by TmModuleBypassedFlowManagerRegister(), TmModuleDecodeDPDKRegister(), TmModuleDecodeErfDagRegister(), TmModuleNapatechDecodeRegister(), TmModuleNapatechStreamRegister(), TmModuleReceiveDPDKRegister(), TmModuleReceiveErfDagRegister(), TmModuleReceiveErfFileRegister(), TmModuleUnixManagerRegister(), and TmSlotSetFuncAppend().
DeInit
TmEcode(* TmModule_::DeInit) (void)
Definition at line 63 of file tm-modules.h.
Referenced by TmModuleRunDeInit().
flags
uint8_t TmModule_::flags
Definition at line 70 of file tm-modules.h.
Referenced by TmModuleBypassedFlowManagerRegister(), TmModuleDecodeDPDKRegister(), TmModuleDecodeErfDagRegister(), TmModuleDecodePfringRegister(), TmModuleDecodeWinDivertRegister(), TmModuleNapatechDecodeRegister(), TmModuleNapatechStreamRegister(), TmModuleReceiveDPDKRegister(), TmModuleReceiveErfDagRegister(), TmModuleReceiveErfFileRegister(), TmModuleReceivePfringRegister(), TmModuleReceiveWinDivertRegister(), TmModuleUnixManagerRegister(), TmSlotSetFuncAppend(), and TmThreadDisableReceiveThreads().
Func
TmEcode(* TmModule_::Func) (ThreadVars *, Packet *, void *)
the packet processing function
Definition at line 52 of file tm-modules.h.
Referenced by TmModuleDebugList(), TmModuleDecodeDPDKRegister(), TmModuleDecodeErfDagRegister(), TmModuleDecodePfringRegister(), TmModuleNapatechDecodeRegister(), TmModuleNapatechStreamRegister(), TmModuleReceiveDPDKRegister(), TmModuleReceiveErfDagRegister(), TmModuleReceiveErfFileRegister(), TmModuleReceivePfringRegister(), TmModuleRespondRejectRegister(), and TmSlotSetFuncAppend().
Init
TmEcode(* TmModule_::Init) (void)
global Init/DeInit
Definition at line 62 of file tm-modules.h.
Referenced by TmModuleRunInit().
Management
TmEcode(* TmModule_::Management) (ThreadVars *, void *)
Definition at line 59 of file tm-modules.h.
Referenced by TmModuleBypassedFlowManagerRegister(), TmModuleUnixManagerRegister(), and TmSlotSetFuncAppend().
name
const char* TmModule_::name
Definition at line 44 of file tm-modules.h.
Referenced by TmModuleBypassedFlowManagerRegister(), TmModuleDebugList(), TmModuleDecodeAFPRegister(), TmModuleDecodeDPDKRegister(), TmModuleDecodeErfDagRegister(), TmModuleDecodeErfFileRegister(), TmModuleDecodeIPFWRegister(), TmModuleDecodeNetmapRegister(), TmModuleDecodeNFLOGRegister(), TmModuleDecodeNFQRegister(), TmModuleDecodePcapFileRegister(), TmModuleDecodePcapRegister(), TmModuleDecodePfringRegister(), TmModuleDecodeWinDivertRegister(), TmModuleDetectLoaderRegister(), TmModuleFlowManagerRegister(), TmModuleFlowRecyclerRegister(), TmModuleFlowWorkerRegister(), TmModuleGetByName(), TmModuleGetIDForTM(), TmModuleNapatechDecodeRegister(), TmModuleNapatechStreamRegister(), TmModuleReceiveAFPRegister(), TmModuleReceiveDPDKRegister(), TmModuleReceiveErfDagRegister(), TmModuleReceiveErfFileRegister(), TmModuleReceiveNetmapRegister(), TmModuleReceiveNFLOGRegister(), TmModuleReceivePcapFileRegister(), TmModuleReceivePcapRegister(), TmModuleReceivePfringRegister(), TmModuleReceiveWinDivertRegister(), TmModuleRegisterTests(), TmModuleRespondRejectRegister(), TmModuleRunDeInit(), TmModuleRunInit(), TmModuleStatsLoggerRegister(), TmModuleUnixManagerRegister(), TmModuleVerdictIPFWRegister(), TmModuleVerdictNFQRegister(), and TmModuleVerdictWinDivertRegister().
PktAcqBreakLoop
TmEcode(* TmModule_::PktAcqBreakLoop) (ThreadVars *, void *)
terminates the capture loop in PktAcqLoop
Definition at line 57 of file tm-modules.h.
Referenced by TmModuleNapatechStreamRegister(), TmModuleReceiveErfDagRegister(), TmModuleReceiveErfFileRegister(), TmModuleReceivePfringRegister(), and TmSlotSetFuncAppend().
PktAcqLoop
TmEcode(* TmModule_::PktAcqLoop) (ThreadVars *, void *, void *)
Definition at line 54 of file tm-modules.h.
Referenced by TmModuleNapatechStreamRegister(), TmModuleReceiveErfDagRegister(), TmModuleReceiveErfFileRegister(), TmModuleReceivePfringRegister(), and TmSlotSetFuncAppend().
RegisterTests
void(* TmModule_::RegisterTests) (void)
Definition at line 65 of file tm-modules.h.
Referenced by TmModuleRegisterTests().
ThreadDeinit
TmEcode(* TmModule_::ThreadDeinit) (ThreadVars *, void *)
Definition at line 49 of file tm-modules.h.
Referenced by TmModuleBypassedFlowManagerRegister(), TmModuleDecodeDPDKRegister(), TmModuleDecodeErfDagRegister(), TmModuleDecodePfringRegister(), TmModuleNapatechDecodeRegister(), TmModuleNapatechStreamRegister(), TmModuleReceiveDPDKRegister(), TmModuleReceiveErfDagRegister(), TmModuleReceiveErfFileRegister(), TmModuleReceivePfringRegister(), TmModuleUnixManagerRegister(), and TmSlotSetFuncAppend().
ThreadExitPrintStats
void(* TmModule_::ThreadExitPrintStats) (ThreadVars *, void *)
Definition at line 48 of file tm-modules.h.
Referenced by TmModuleDecodeDPDKRegister(), TmModuleDecodeErfDagRegister(), TmModuleDecodePfringRegister(), TmModuleNapatechDecodeRegister(), TmModuleNapatechStreamRegister(), TmModuleReceiveDPDKRegister(), TmModuleReceiveErfDagRegister(), TmModuleReceiveErfFileRegister(), TmModuleReceivePfringRegister(), and TmSlotSetFuncAppend().
ThreadInit
TmEcode(* TmModule_::ThreadInit) (ThreadVars *, const void *, void **)
thread handling
Definition at line 47 of file tm-modules.h.
Referenced by TmModuleBypassedFlowManagerRegister(), TmModuleDecodeAFPRegister(), TmModuleDecodeDPDKRegister(), TmModuleDecodeErfDagRegister(), TmModuleDecodeErfFileRegister(), TmModuleDecodeIPFWRegister(), TmModuleDecodeNetmapRegister(), TmModuleDecodeNFLOGRegister(), TmModuleDecodeNFQRegister(), TmModuleDecodePcapFileRegister(), TmModuleDecodePcapRegister(), TmModuleDecodePfringRegister(), TmModuleDecodeWinDivertRegister(), TmModuleDetectLoaderRegister(), TmModuleFlowManagerRegister(), TmModuleFlowRecyclerRegister(), TmModuleFlowWorkerRegister(), TmModuleNapatechDecodeRegister(), TmModuleNapatechStreamRegister(), TmModuleReceiveAFPRegister(), TmModuleReceiveDPDKRegister(), TmModuleReceiveErfDagRegister(), TmModuleReceiveErfFileRegister(), TmModuleReceiveNetmapRegister(), TmModuleReceiveNFLOGRegister(), TmModuleReceivePcapFileRegister(), TmModuleReceivePcapRegister(), TmModuleReceivePfringRegister(), TmModuleReceiveWinDivertRegister(), TmModuleRespondRejectRegister(), TmModuleStatsLoggerRegister(), TmModuleUnixManagerRegister(), TmModuleVerdictIPFWRegister(), TmModuleVerdictNFQRegister(), TmModuleVerdictWinDivertRegister(), and TmSlotSetFuncAppend().
The documentation for this struct was generated from the following file:
/Users/jlu/suricata/src/tm-modules.h