suricata: HashListTable_ Struct Reference
HashListTable_ Struct Reference
#include <util-hashlist.h>
Data Fields
HashListTableBucket ** array
HashListTableBucket * listhead
HashListTableBucket * listtail
uint32_t array_size
uint32_t(* Hash)(struct HashListTable_ *, void *, uint16_t)
char(* Compare)(void *, uint16_t, void *, uint16_t)
void(* Free)(void *)
Detailed Description
Definition at line 37 of file util-hashlist.h.
Field Documentation
array
HashListTableBucket** HashListTable_::array
Definition at line 38 of file util-hashlist.h.
Referenced by HashListTableAdd(), HashListTableFree(), HashListTableInit(), HashListTableLookup(), and HashListTableRemove().
array_size
uint32_t HashListTable_::array_size
Definition at line 41 of file util-hashlist.h.
Referenced by HashListTableFree(), HashListTableGenericHash(), HashListTableInit(), and HashListTablePrint().
Compare
char(* HashListTable_::Compare) (void *, uint16_t, void *, uint16_t)
Definition at line 43 of file util-hashlist.h.
Referenced by HashListTableInit(), HashListTableLookup(), and HashListTableRemove().
Free
void(* HashListTable_::Free) (void *)
Definition at line 44 of file util-hashlist.h.
Referenced by HashListTableFree(), HashListTableInit(), and HashListTableRemove().
Hash
uint32_t(* HashListTable_::Hash) (struct HashListTable_ *, void *, uint16_t)
Definition at line 42 of file util-hashlist.h.
Referenced by HashListTableAdd(), HashListTableInit(), HashListTableLookup(), HashListTablePrint(), and HashListTableRemove().
listhead
HashListTableBucket* HashListTable_::listhead
Definition at line 39 of file util-hashlist.h.
Referenced by HashListTableAdd(), HashListTableGetListHead(), HashListTableInit(), and HashListTableRemove().
listtail
HashListTableBucket* HashListTable_::listtail
Definition at line 40 of file util-hashlist.h.
Referenced by HashListTableAdd(), HashListTableInit(), and HashListTableRemove().
The documentation for this struct was generated from the following file:
/Users/jlu/suricata/src/util-hashlist.h