suricata: /Users/jlu/suricata/src/tm-queues.h File Reference
tm-queues.h File Reference
#include "packet-queue.h"
Data Structures
struct Tmq_
Typedefs
typedef struct Tmq_ Tmq
Functions
Tmq * TmqCreateQueue (const char *name)
Tmq * TmqGetQueueByName (const char *name)
void TmqDebugList (void)
void TmqResetQueues (void)
void TmValidateQueueState (void)
Checks if all the queues allocated so far have at least one reader and writer.
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file tm-queues.h.
Typedef Documentation
Tmq
typedef struct Tmq_ Tmq
Function Documentation
TmqCreateQueue()
Tmq * TmqCreateQueue (const char * name)
Referenced by TmThreadCreate().
TmqDebugList()
void TmqDebugList (void)
Definition at line 69 of file tm-queues.c.
References Tmq_::id, PacketQueue_::len, PacketQueue_::mutex_q, Tmq_::name, next, Tmq_::pq, SCMutexLock, SCMutexUnlock, and TAILQ_FOREACH.
TmqGetQueueByName()
Tmq * TmqGetQueueByName (const char * name)
Definition at line 59 of file tm-queues.c.
References Tmq_::name, next, and TAILQ_FOREACH.
Referenced by TmThreadCreate().
TmqResetQueues()
void TmqResetQueues (void)
Definition at line 80 of file tm-queues.c.
References Tmq_::name, next, PacketQueueFree(), Tmq_::pq, SCFree, TAILQ_FIRST, and TAILQ_REMOVE.
TmValidateQueueState()
void TmValidateQueueState (void)
Checks if all the queues allocated so far have at least one reader and writer.
Definition at line 101 of file tm-queues.c.
References FatalError, Tmq_::id, PacketQueue_::mutex_q, Tmq_::name, next, Tmq_::pq, Tmq_::reader_cnt, SC_ERR_FATAL, SC_ERR_THREAD_QUEUE, SCLogError, SCMutexLock, SCMutexUnlock, TAILQ_FOREACH, and Tmq_::writer_cnt.