suricata: /Users/jlu/suricata/src/tm-queuehandlers.c File Reference
tm-queuehandlers.c File Reference
#include "suricata-common.h"
#include "packet-queue.h"
#include "decode.h"
#include "threads.h"
#include "threadvars.h"
#include "tm-queuehandlers.h"
#include "tmqh-simple.h"
#include "tmqh-packetpool.h"
#include "tmqh-flow.h"
Functions
void TmqhSetup (void)
void TmqhCleanup (void)
Clean up registration time allocs.
int TmqhNameToID (const char *name)
Tmqh * TmqhGetQueueHandlerByName (const char *name)
Tmqh * TmqhGetQueueHandlerByID (const int id)
Variables
Tmqh tmqh_table [TMQH_SIZE]
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Master Queue Handler
Definition in file tm-queuehandlers.c.
Function Documentation
TmqhCleanup()
void TmqhCleanup (void)
Clean up registration time allocs.
Definition at line 49 of file tm-queuehandlers.c.
TmqhGetQueueHandlerByID()
Tmqh * TmqhGetQueueHandlerByID (const int id)
Definition at line 77 of file tm-queuehandlers.c.
References TMQH_SIZE, and tmqh_table.
TmqhGetQueueHandlerByName()
Tmqh * TmqhGetQueueHandlerByName (const char * name)
Definition at line 65 of file tm-queuehandlers.c.
References TMQH_SIZE, and tmqh_table.
Referenced by TmThreadCreate().
TmqhNameToID()
int TmqhNameToID (const char * name)
Definition at line 53 of file tm-queuehandlers.c.
References TMQH_SIZE, and tmqh_table.
Referenced by TmThreadCreate().
TmqhSetup()
void TmqhSetup (void)
Definition at line 39 of file tm-queuehandlers.c.
References tmqh_table, TmqhFlowRegister(), TmqhPacketpoolRegister(), and TmqhSimpleRegister().
Referenced by RunUnittests().
Variable Documentation
tmqh_table
Tmqh tmqh_table[TMQH_SIZE]
Definition at line 37 of file tm-queuehandlers.c.
Referenced by TmqhFlowRegister(), TmqhGetQueueHandlerByID(), TmqhGetQueueHandlerByName(), TmqhNameToID(), TmqhPacketpoolRegister(), TmqhSetup(), and TmqhSimpleRegister().