suricata: /Users/jlu/suricata/src/tm-threads.c File Reference
tm-threads.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "stream.h"
#include "runmodes.h"
#include "threadvars.h"
#include "tm-queues.h"
#include "tm-queuehandlers.h"
#include "tm-threads.h"
#include "tmqh-packetpool.h"
#include "threads.h"
#include "util-affinity.h"
#include "util-debug.h"
#include "util-privs.h"
#include "util-cpu.h"
#include "util-optimize.h"
#include "util-profiling.h"
#include "util-signal.h"
#include "queue.h"
Data Structures
struct Thread_
struct Threads_
Macros
#define MIN_WAIT_TIME 100
#define MAX_WAIT_TIME 999999
#define STEP 32
Typedefs
typedef struct Thread_ Thread
typedef struct Threads_ Threads
Functions
int TmThreadsCheckFlag (ThreadVars *tv, uint32_t flag)
Check if a thread flag is set.
void TmThreadsSetFlag (ThreadVars *tv, uint32_t flag)
Set a thread flag.
void TmThreadsUnsetFlag (ThreadVars *tv, uint32_t flag)
Unset a thread flag.
TmEcode TmThreadsSlotVarRun (ThreadVars *tv, Packet *p, TmSlot *slot)
Separate run function so we can call it recursively.
void TmSlotSetFuncAppend (ThreadVars *tv, TmModule *tm, const void *data)
Appends a new entry to the slots.
TmEcode TmThreadSetThreadPriority (ThreadVars *tv, int prio)
Set the thread options (thread priority).
void TmThreadSetPrio (ThreadVars *tv)
Adjusting nice value for threads.
TmEcode TmThreadSetCPUAffinity (ThreadVars *tv, uint16_t cpu)
Set the thread options (cpu affinity).
TmEcode TmThreadSetCPU (ThreadVars *tv, uint8_t type)
int TmThreadGetNbThreads (uint8_t type)
TmEcode TmThreadSetupOptions (ThreadVars *tv)
Set the thread options (cpu affinitythread). Priority should be already set by pthread_create.
ThreadVars * TmThreadCreate (const char *name, const char *inq_name, const char *inqh_name, const char *outq_name, const char *outqh_name, const char *slots, void *(*fn_p)(void *), int mucond)
Creates and returns the TV instance for a new thread.
ThreadVars * TmThreadCreatePacketHandler (const char *name, const char *inq_name, const char *inqh_name, const char *outq_name, const char *outqh_name, const char *slots)
Creates and returns a TV instance for a Packet Processing Thread. This function doesn't support custom slots, and hence shouldn't be supplied "custom" as its slot type. All PPT threads are created with a mucond(see TmThreadCreate declaration) of 0. Hence the tv conditional variables are not used to kill the thread.
ThreadVars * TmThreadCreateMgmtThread (const char *name, void *(fn_p)(void *), int mucond)
Creates and returns the TV instance for a Management thread(MGMT). This function supports only custom slot functions and hence a function pointer should be sent as an argument.
ThreadVars * TmThreadCreateMgmtThreadByName (const char *name, const char *module, int mucond)
Creates and returns the TV instance for a Management thread(MGMT). This function supports only custom slot functions and hence a function pointer should be sent as an argument.
ThreadVars * TmThreadCreateCmdThreadByName (const char *name, const char *module, int mucond)
Creates and returns the TV instance for a Command thread (CMD). This function supports only custom slot functions and hence a function pointer should be sent as an argument.
void TmThreadAppend (ThreadVars *tv, int type)
Appends this TV to tv_root based on its type.
void TmThreadDisableReceiveThreads (void)
Disable all threads having the specified TMs.
void TmThreadDisablePacketThreads (void)
Disable all packet threads.
void TmThreadKillThreadsFamily (int family)
void TmThreadKillThreads (void)
void TmThreadSetGroupName (ThreadVars *tv, const char *name)
void TmThreadClearThreadsFamily (int family)
TmEcode TmThreadSpawn (ThreadVars *tv)
Spawns a thread associated with the ThreadVars instance tv.
void TmThreadInitMC (ThreadVars *tv)
Initializes the mutex and condition variables for this TV.
void TmThreadTestThreadUnPaused (ThreadVars *tv)
Tests if the thread represented in the arg has been unpaused or not.
void TmThreadWaitForFlag (ThreadVars *tv, uint32_t flags)
Waits till the specified flag(s) is(are) set. We don't bother if the kill flag has been set or not on the thread.
void TmThreadContinue (ThreadVars *tv)
Unpauses a thread.
void TmThreadContinueThreads ()
Unpauses all threads present in tv_root.
void TmThreadCheckThreadState (void)
Used to check the thread for certain conditions of failure.
TmEcode TmThreadWaitOnThreadInit (void)
Used to check if all threads have finished their initialization. On finding an un-initialized thread, it waits till that thread completes its initialization, before proceeding to the next thread.
uint32_t TmThreadCountThreadsByTmmFlags (uint8_t flags)
returns a count of all the threads that match the flag
void TmThreadsListThreads (void)
int TmThreadsRegisterThread (ThreadVars *tv, const int type)
void TmThreadsUnregisterThread (const int id)
void TmThreadsSetThreadTimestamp (const int id, const struct timeval *ts)
bool TmThreadsTimeSubsysIsReady (void)
void TmThreadsInitThreadsTimestamp (const struct timeval *ts)
void TmThreadsGetMinimalTimestamp (struct timeval *ts)
uint16_t TmThreadsGetWorkerThreadMax ()
void TmThreadsInjectFlowById (Flow *f, const int id)
inject a flow into a threads flow queue
Variables
ThreadVars * tv_root [TVT_MAX] = { NULL }
SCMutex tv_root_lock = SCMUTEX_INITIALIZER
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Thread management functions.
Definition in file tm-threads.c.
Macro Definition Documentation
MAX_WAIT_TIME
#define MAX_WAIT_TIME 999999
Definition at line 1509 of file tm-threads.c.
MIN_WAIT_TIME
#define MIN_WAIT_TIME 100
Definition at line 1508 of file tm-threads.c.
STEP
#define STEP 32
Definition at line 2033 of file tm-threads.c.
Typedef Documentation
Thread
typedef struct Thread_ Thread
Threads
typedef struct Threads_ Threads
Function Documentation
TmSlotSetFuncAppend()
void TmSlotSetFuncAppend (ThreadVars * tv, TmModule * tm, const void * data)
Appends a new entry to the slots.
Parameters
tv TV the slot is attached to.
tm TM to append.
data Data to be passed on to the slot init function.
Return values
The allocated TmSlot or NULL if there is an error
Definition at line 629 of file tm-threads.c.
References ThreadVars_::break_loop, ThreadVars_::cap_flags, TmModule_::cap_flags, TmModule_::flags, TmModule_::Func, TmModule_::Management, TmSlot_::Management, TmModule_::PktAcqBreakLoop, TmModule_::PktAcqLoop, TmSlot_::PktAcqLoop, SC_ATOMIC_INITPTR, SCMalloc, TmSlot_::slot_initdata, TmSlot_::slot_next, TmSlot_::SlotFunc, TmSlot_::SlotThreadDeinit, TmSlot_::SlotThreadExitPrintStats, TmSlot_::SlotThreadInit, TmModule_::ThreadDeinit, TmModule_::ThreadExitPrintStats, TmModule_::ThreadInit, TmSlot_::tm_id, ThreadVars_::tm_slots, ThreadVars_::tmm_flags, TmModuleGetIDForTM(), tv, and unlikely.
Referenced by RunModeErfFileAutoFp(), RunModeErfFileSingle(), RunModeFilePcapAutoFp(), RunModeFilePcapSingle(), RunModeSetIPSAutoFp(), RunModeSetIPSWorker(), RunModeSetLiveCaptureAutoFp(), TmThreadCreateCmdThreadByName(), and TmThreadCreateMgmtThreadByName().
TmThreadAppend()
void TmThreadAppend (ThreadVars * tv, int type)
Appends this TV to tv_root based on its type.
Parameters
type holds the type this TV belongs to.
Definition at line 1139 of file tm-threads.c.
References ThreadVars_::next, SCMutexLock, SCMutexUnlock, tv, tv_root, tv_root_lock, and type.
Referenced by TmThreadSpawn().
TmThreadCheckThreadState()
void TmThreadCheckThreadState (void)
Used to check the thread for certain conditions of failure.
Definition at line 1800 of file tm-threads.c.
References FatalError, ThreadVars_::name, ThreadVars_::next, SC_ERR_FATAL, SCMutexLock, SCMutexUnlock, THV_FAILED, TmThreadsCheckFlag(), tv, tv_root, tv_root_lock, and TVT_MAX.
TmThreadClearThreadsFamily()
void TmThreadClearThreadsFamily (int family)
Definition at line 1611 of file tm-threads.c.
References ThreadVars_::next, SCMutexLock, tv, tv_root, tv_root_lock, and TVT_MAX.
TmThreadContinue()
void TmThreadContinue (ThreadVars * tv)
Unpauses a thread.
Parameters
tv Pointer to a TV instance that has to be unpaused
Definition at line 1773 of file tm-threads.c.
References THV_PAUSE, TmThreadsUnsetFlag(), and tv.
Referenced by TmThreadContinueDetectLoaderThreads(), and TmThreadContinueThreads().
TmThreadContinueThreads()
void TmThreadContinueThreads (void)
Unpauses all threads present in tv_root.
Definition at line 1783 of file tm-threads.c.
References ThreadVars_::next, SCMutexLock, SCMutexUnlock, TmThreadContinue(), tv, tv_root, tv_root_lock, and TVT_MAX.
TmThreadCountThreadsByTmmFlags()
uint32_t TmThreadCountThreadsByTmmFlags (uint8_t flags)
returns a count of all the threads that match the flag
Definition at line 1935 of file tm-threads.c.
Referenced by PacketPoolPostRunmodes().
TmThreadCreate()
ThreadVars * TmThreadCreate (const char * name, const char * inq_name, const char * inqh_name, const char * outq_name, const char * outqh_name, const char * slots, void *(*)(void *) fn_p, int mucond)
Creates and returns the TV instance for a new thread.
Parameters
name Name of this TV instance
inq_name Incoming queue name
inqh_name Incoming queue handler name as set by TmqhSetup()
outq_name Outgoing queue name
outqh_name Outgoing queue handler as set by TmqhSetup()
slots String representation for the slot function to be used
fn_p Pointer to function when "slots" is of type "custom"
mucond Flag to indicate whether to initialize the condition and the mutex variables for this newly created TV.
Return values
the newly created TV instance, or NULL on error
Definition at line 892 of file tm-threads.c.
References Tmqh_::InHandler, ThreadVars_::inq, ThreadVars_::inq_id, StatsPublicThreadContext_::m, ThreadVars_::name, ThreadVars_::outctx, Tmqh_::OutHandler, Tmqh_::OutHandlerCtxSetup, ThreadVars_::outq, ThreadVars_::outq_id, ThreadVars_::perf_public_ctx, Tmq_::reader_cnt, SC_ATOMIC_INIT, SCLogDebug, SCMalloc, SCMutexInit, strlcpy(), THV_PAUSE, THV_USE, TmqCreateQueue(), TmqGetQueueByName(), ThreadVars_::tmqh_in, ThreadVars_::tmqh_out, TmqhGetQueueHandlerByName(), TmqhNameToID(), TmThreadsSetFlag(), tv, unlikely, and Tmq_::writer_cnt.
Referenced by NapatechStartStats(), TmThreadCreateCmdThreadByName(), TmThreadCreateMgmtThread(), TmThreadCreateMgmtThreadByName(), and TmThreadCreatePacketHandler().
TmThreadCreateCmdThreadByName()
ThreadVars * TmThreadCreateCmdThreadByName (const char * name, const char * module, int mucond)
Creates and returns the TV instance for a Command thread (CMD). This function supports only custom slot functions and hence a function pointer should be sent as an argument.
Parameters
name Name of this TV instance
module Name of TmModule with COMMAND flag set.
mucond Flag to indicate whether to initialize the condition and the mutex variables for this newly created TV.
Return values
the newly created TV instance, or NULL on error
Definition at line 1113 of file tm-threads.c.
References ThreadVars_::id, m, MANAGEMENT_CPU_SET, TmModuleGetByName(), TmSlotSetFuncAppend(), TmThreadCreate(), TmThreadSetCPU(), TmThreadsRegisterThread(), tv, TVT_CMD, and ThreadVars_::type.
TmThreadCreateMgmtThread()
ThreadVars * TmThreadCreateMgmtThread (const char * name, void * fn_p)(void *, int mucond)
Creates and returns the TV instance for a Management thread(MGMT). This function supports only custom slot functions and hence a function pointer should be sent as an argument.
Parameters
name Name of this TV instance
fn_p Pointer to function when "slots" is of type "custom"
mucond Flag to indicate whether to initialize the condition and the mutex variables for this newly created TV.
Return values
the newly created TV instance, or NULL on error
Definition at line 1052 of file tm-threads.c.
References ThreadVars_::id, MANAGEMENT_CPU_SET, TmThreadCreate(), TmThreadSetCPU(), TmThreadsRegisterThread(), tv, TVT_MGMT, and ThreadVars_::type.
TmThreadCreateMgmtThreadByName()
ThreadVars * TmThreadCreateMgmtThreadByName (const char * name, const char * module, int mucond)
Creates and returns the TV instance for a Management thread(MGMT). This function supports only custom slot functions and hence a function pointer should be sent as an argument.
Parameters
name Name of this TV instance
module Name of TmModule with MANAGEMENT flag set.
mucond Flag to indicate whether to initialize the condition and the mutex variables for this newly created TV.
Return values
the newly created TV instance, or NULL on error
Definition at line 1080 of file tm-threads.c.
References ThreadVars_::id, m, MANAGEMENT_CPU_SET, TmModuleGetByName(), TmSlotSetFuncAppend(), TmThreadCreate(), TmThreadSetCPU(), TmThreadsRegisterThread(), tv, TVT_MGMT, and ThreadVars_::type.
Referenced by BypassedFlowManagerThreadSpawn().
TmThreadCreatePacketHandler()
ThreadVars * TmThreadCreatePacketHandler (const char * name, const char * inq_name, const char * inqh_name, const char * outq_name, const char * outqh_name, const char * slots)
Creates and returns a TV instance for a Packet Processing Thread. This function doesn't support custom slots, and hence shouldn't be supplied "custom" as its slot type. All PPT threads are created with a mucond(see TmThreadCreate declaration) of 0. Hence the tv conditional variables are not used to kill the thread.
Parameters
name Name of this TV instance
inq_name Incoming queue name
inqh_name Incoming queue handler name as set by TmqhSetup()
outq_name Outgoing queue name
outqh_name Outgoing queue handler as set by TmqhSetup()
slots String representation for the slot function to be used
Return values
the newly created TV instance, or NULL on error
Definition at line 1022 of file tm-threads.c.
References ThreadVars_::id, TmThreadCreate(), TmThreadsRegisterThread(), tv, TVT_PPT, and ThreadVars_::type.
Referenced by RunModeErfFileAutoFp(), RunModeErfFileSingle(), RunModeFilePcapAutoFp(), RunModeFilePcapSingle(), RunModeSetIPSAutoFp(), RunModeSetIPSWorker(), and RunModeSetLiveCaptureAutoFp().
TmThreadDisablePacketThreads()
void TmThreadDisablePacketThreads (void)
Disable all packet threads.
Definition at line 1461 of file tm-threads.c.
Referenced by PostRunDeinit().
TmThreadDisableReceiveThreads()
void TmThreadDisableReceiveThreads (void)
Disable all threads having the specified TMs.
Breaks out of the packet acquisition loop, and bumps into the 'flow loop', where it will process packets from the flow engine's shutdown handling.
Definition at line 1329 of file tm-threads.c.
References FatalError, TmModule_::flags, ThreadVars_::name, SC_ERR_FATAL, SCMutexLock, TmSlot_::slot_next, TM_FLAG_RECEIVE_TM, TmSlot_::tm_id, ThreadVars_::tm_slots, TmModuleGetById(), tv, tv_root, tv_root_lock, and TVT_PPT.
Referenced by PostRunDeinit().
TmThreadGetNbThreads()
int TmThreadGetNbThreads (uint8_t type)
Definition at line 817 of file tm-threads.c.
References MAX_CPU_SET, ThreadsAffinityType_::nb_threads, SC_ERR_INVALID_ARGUMENT, SCLogError, thread_affinity, and type.
Referenced by RunModeErfFileAutoFp(), RunModeFilePcapAutoFp(), and TmThreadsGetWorkerThreadMax().
TmThreadInitMC()
void TmThreadInitMC (ThreadVars * tv)
Initializes the mutex and condition variables for this TV.
It can be used by a thread to control a wait loop that can also be influenced by other threads.
Parameters
tv Pointer to a TV instance
Definition at line 1693 of file tm-threads.c.
References ThreadVars_::ctrl_cond, ThreadVars_::ctrl_mutex, FatalError, SC_ERR_FATAL, SCCtrlCondInit, SCCtrlMutexInit, SCMalloc, and tv.
TmThreadKillThreads()
void TmThreadKillThreads (void)
Definition at line 1539 of file tm-threads.c.
References TmThreadKillThreadsFamily(), and TVT_MAX.
TmThreadKillThreadsFamily()
void TmThreadKillThreadsFamily (int family)
Definition at line 1510 of file tm-threads.c.
References BUG_ON, MIN_WAIT_TIME, SCMutexLock, tv, tv_root, tv_root_lock, and TVT_MAX.
Referenced by TmThreadKillThreads().
TmThreadsCheckFlag()
int TmThreadsCheckFlag (ThreadVars * tv, uint32_t flag)
Check if a thread flag is set.
Return values
1 flag is set.
0 flag is not set.
Definition at line 90 of file tm-threads.c.
References SC_ATOMIC_GET, and tv.
Referenced by FlowDisableFlowManagerThread(), TmThreadCheckThreadState(), TmThreadTestThreadUnPaused(), TmThreadWaitForFlag(), and TmThreadWaitOnThreadInit().
TmThreadSetCPU()
TmEcode TmThreadSetCPU (ThreadVars * tv, uint8_t type)
Definition at line 801 of file tm-threads.c.
References ThreadVars_::cpu_affinity, MAX_CPU_SET, SC_ERR_INVALID_ARGUMENT, SCLogError, THREAD_SET_AFFTYPE, ThreadVars_::thread_setup_flags, threading_set_cpu_affinity, TM_ECODE_FAILED, TM_ECODE_OK, tv, and type.
Referenced by RunModeFilePcapAutoFp(), RunModeFilePcapSingle(), RunModeSetIPSAutoFp(), RunModeSetIPSWorker(), RunModeSetLiveCaptureAutoFp(), TmThreadCreateCmdThreadByName(), TmThreadCreateMgmtThread(), and TmThreadCreateMgmtThreadByName().
TmThreadSetCPUAffinity()
TmEcode TmThreadSetCPUAffinity (ThreadVars * tv, uint16_t cpu)
Set the thread options (cpu affinity).
Parameters
tv pointer to the ThreadVars to setup the affinity.
cpu cpu on which affinity is set.
Return values
TM_ECODE_OK
Definition at line 792 of file tm-threads.c.
References ThreadVars_::cpu_affinity, THREAD_SET_AFFINITY, ThreadVars_::thread_setup_flags, TM_ECODE_OK, and tv.
Referenced by RunModeErfFileAutoFp().
TmThreadSetGroupName()
void TmThreadSetGroupName (ThreadVars * tv, const char * name)
Definition at line 1593 of file tm-threads.c.
References SC_ERR_RUNMODE, SCLogError, SCStrdup, ThreadVars_::thread_group_name, tv, and unlikely.
Referenced by RunModeErfFileAutoFp(), RunModeFilePcapAutoFp(), RunModeSetIPSAutoFp(), and RunModeSetLiveCaptureAutoFp().
TmThreadSetPrio()
void TmThreadSetPrio (ThreadVars * tv)
Adjusting nice value for threads.
Definition at line 756 of file tm-threads.c.
References ThreadVars_::name, SC_ERR_THREAD_NICE_PRIO, SCEnter, SCLogDebug, SCLogError, SCReturn, ThreadVars_::thread_priority, and tv.
TmThreadSetThreadPriority()
TmEcode TmThreadSetThreadPriority (ThreadVars * tv, int prio)
Set the thread options (thread priority).
Parameters
tv Pointer to the ThreadVars to setup the thread priority.
Return values
TM_ECODE_OK.
Definition at line 745 of file tm-threads.c.
References ThreadVars_::thread_priority, THREAD_SET_PRIORITY, ThreadVars_::thread_setup_flags, TM_ECODE_OK, and tv.
Referenced by RunModeErfFileAutoFp().
TmThreadSetupOptions()
TmEcode TmThreadSetupOptions (ThreadVars * tv)
Set the thread options (cpu affinitythread). Priority should be already set by pthread_create.
Parameters
tv pointer to the ThreadVars of the calling thread.
Definition at line 833 of file tm-threads.c.
References ThreadVars_::cpu_affinity, ThreadVars_::name, SCGetThreadIdLong, SCLogPerf, THREAD_SET_AFFINITY, ThreadVars_::thread_setup_flags, and tv.
TmThreadsGetMinimalTimestamp()
void TmThreadsGetMinimalTimestamp (struct timeval * ts)
Definition at line 2162 of file tm-threads.c.
References SCMutexLock.
TmThreadsGetWorkerThreadMax()
uint16_t TmThreadsGetWorkerThreadMax (void)
Definition at line 2197 of file tm-threads.c.
References SC_ERR_RUNMODE, SCLogWarning, threading_detect_ratio, TmThreadGetNbThreads(), UtilCpuGetNumProcessorsOnline(), and WORKER_CPU_SET.
Referenced by RunModeSetIPSAutoFp(), and RunModeSetLiveCaptureAutoFp().
TmThreadsInitThreadsTimestamp()
void TmThreadsInitThreadsTimestamp (const struct timeval * ts)
Definition at line 2147 of file tm-threads.c.
References SCMutexLock.
Referenced by PcapFileDispatch().
TmThreadsInjectFlowById()
void TmThreadsInjectFlowById (Flow * f, const int id)
inject a flow into a threads flow queue
Definition at line 2232 of file tm-threads.c.
References BUG_ON.
Referenced by FlowForceReassemblyForFlow().
TmThreadsListThreads()
void TmThreadsListThreads (void)
Definition at line 2013 of file tm-threads.c.
References SCMutexLock.
TmThreadSpawn()
TmEcode TmThreadSpawn (ThreadVars * tv)
Spawns a thread associated with the ThreadVars instance tv.
Return values
TM_ECODE_OK on success and TM_ECODE_FAILED on failure
Definition at line 1636 of file tm-threads.c.
References FatalError, SC_ERR_THREAD_CREATE, SC_ERR_TM_THREADS_ERROR, SCLogDebug, ThreadVars_::t, threading_set_stack_size, THV_INIT_DONE, THV_RUNNING_DONE, TM_ECODE_OK, ThreadVars_::tm_func, TmThreadAppend(), TmThreadWaitForFlag(), tv, and ThreadVars_::type.
Referenced by BypassedFlowManagerThreadSpawn(), RunModeErfFileAutoFp(), RunModeErfFileSingle(), RunModeFilePcapAutoFp(), RunModeFilePcapSingle(), RunModeSetIPSAutoFp(), RunModeSetIPSWorker(), and RunModeSetLiveCaptureAutoFp().
TmThreadsRegisterThread()
int TmThreadsRegisterThread (ThreadVars * tv, const int type)
Return values
id thread id, or 0 if not found
Definition at line 2037 of file tm-threads.c.
References SCMutexLock.
Referenced by TmThreadCreateCmdThreadByName(), TmThreadCreateMgmtThread(), TmThreadCreateMgmtThreadByName(), and TmThreadCreatePacketHandler().
TmThreadsSetFlag()
void TmThreadsSetFlag (ThreadVars * tv, uint32_t flag)
Set a thread flag.
Definition at line 98 of file tm-threads.c.
References SC_ATOMIC_OR, and tv.
Referenced by FlowDisableFlowManagerThread(), and TmThreadCreate().
TmThreadsSetThreadTimestamp()
void TmThreadsSetThreadTimestamp (const int id, const struct timeval * ts)
Definition at line 2113 of file tm-threads.c.
References SCMutexLock.
TmThreadsSlotVarRun()
TmEcode TmThreadsSlotVarRun (ThreadVars * tv, Packet * p, TmSlot * slot)
Separate run function so we can call it recursively.
Definition at line 114 of file tm-threads.c.
References PACKET_PROFILING_TMM_END, PACKET_PROFILING_TMM_START, SC_ATOMIC_GET, TmSlot_::slot_next, TM_ECODE_FAILED, tv, and unlikely.
TmThreadsTimeSubsysIsReady()
bool TmThreadsTimeSubsysIsReady (void)
Definition at line 2130 of file tm-threads.c.
References SCMutexLock.
TmThreadsUnregisterThread()
void TmThreadsUnregisterThread (const int id)
Definition at line 2080 of file tm-threads.c.
References SCMutexLock.
TmThreadsUnsetFlag()
void TmThreadsUnsetFlag (ThreadVars * tv, uint32_t flag)
Unset a thread flag.
Definition at line 106 of file tm-threads.c.
References SC_ATOMIC_AND, and tv.
Referenced by TmThreadContinue().
TmThreadTestThreadUnPaused()
void TmThreadTestThreadUnPaused (ThreadVars * tv)
Tests if the thread represented in the arg has been unpaused or not.
   The function would return if the thread tv has been unpaused or if the
   kill flag for the thread has been set.
Parameters
tv Pointer to the TV instance.
Definition at line 1741 of file tm-threads.c.
References SleepUsec, THV_KILL, THV_PAUSE, TmThreadsCheckFlag(), and tv.
TmThreadWaitForFlag()
void TmThreadWaitForFlag (ThreadVars * tv, uint32_t flags)
Waits till the specified flag(s) is(are) set. We don't bother if the kill flag has been set or not on the thread.
Parameters
tv Pointer to the TV instance.
Definition at line 1759 of file tm-threads.c.
References flags, SleepUsec, TmThreadsCheckFlag(), and tv.
Referenced by TmThreadSpawn().
TmThreadWaitOnThreadInit()
TmEcode TmThreadWaitOnThreadInit (void)
Used to check if all threads have finished their initialization. On finding an un-initialized thread, it waits till that thread completes its initialization, before proceeding to the next thread.
Return values
TM_ECODE_OK all initialized properly
TM_ECODE_FAILED failure
Definition at line 1824 of file tm-threads.c.
References ThreadVars_::name, ThreadVars_::next, SC_ATOMIC_GET, SC_ERR_THREAD_INIT, SCLogError, SCLogNotice, SCMutexLock, SCMutexUnlock, SleepUsec, strlcat(), strlcpy(), thread_name_autofp, thread_name_flow_mgr, thread_name_flow_rec, thread_name_verdict, thread_name_workers, THV_CLOSED, THV_DEAD, THV_FAILED, THV_INIT_DONE, TM_ECODE_FAILED, TM_ECODE_OK, TmThreadsCheckFlag(), tv, tv_root, tv_root_lock, and TVT_MAX.
Variable Documentation
tv_root
ThreadVars* tv_root[TVT_MAX] = { NULL }
Definition at line 79 of file tm-threads.c.
Referenced by FlowDisableFlowManagerThread(), TmThreadAppend(), TmThreadCheckThreadState(), TmThreadClearThreadsFamily(), TmThreadContinueDetectLoaderThreads(), TmThreadContinueThreads(), TmThreadDisableReceiveThreads(), TmThreadKillThreadsFamily(), TmThreadWaitOnThreadInit(), and TmThreadWakeupDetectLoaderThreads().
tv_root_lock
SCMutex tv_root_lock = SCMUTEX_INITIALIZER
Definition at line 82 of file tm-threads.c.
Referenced by FlowDisableFlowManagerThread(), TmThreadAppend(), TmThreadCheckThreadState(), TmThreadClearThreadsFamily(), TmThreadContinueDetectLoaderThreads(), TmThreadContinueThreads(), TmThreadDisableReceiveThreads(), TmThreadKillThreadsFamily(), TmThreadWaitOnThreadInit(), and TmThreadWakeupDetectLoaderThreads().