suricata: /Users/jlu/suricata/src/tmqh-packetpool.c File Reference
tmqh-packetpool.c File Reference
#include "suricata.h"
#include "packet-queue.h"
#include "decode.h"
#include "detect.h"
#include "detect-uricontent.h"
#include "threads.h"
#include "threadvars.h"
#include "flow.h"
#include "flow-util.h"
#include "host.h"
#include "stream.h"
#include "stream-tcp-reassemble.h"
#include "tm-queuehandlers.h"
#include "tm-threads.h"
#include "tm-modules.h"
#include "pkt-var.h"
#include "tmqh-packetpool.h"
#include "util-debug.h"
#include "util-error.h"
#include "util-profiling.h"
#include "util-device.h"
#include "util-validate.h"
Macros
#define MAX_PENDING_RETURN_PACKETS 32
#define RESERVED_PACKETS 10
Functions
void TmqhPacketpoolRegister (void)
TmqhPacketpoolRegister \initonly.
void PacketPoolWait (void)
void PacketPoolWaitForN (int n)
Wait until we have the requested amount of packets in the pool.
Packet * PacketPoolGetPacket (void)
Get a new packet from the packet pool.
void PacketPoolReturnPacket (Packet *p)
Return packet to Packet pool.
void PacketPoolInitEmpty (void)
void PacketPoolInit (void)
void PacketPoolDestroy (void)
Packet * TmqhInputPacketpool (ThreadVars *tv)
void TmqhOutputPacketpool (ThreadVars *t, Packet *p)
void TmqhReleasePacketsToPacketPool (PacketQueue *pq)
Release all the packets in the queue back to the packetpool. Mainly used by threads that have failed, and wants to return the packets back to the packetpool.
void PacketPoolPostRunmodes (void)
Set the max_pending_return_packets value.
Variables
thread_local PktPool thread_pkt_pool
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Packetpool queue handlers. Packet pool is implemented as a stack.
Definition in file tmqh-packetpool.c.
Macro Definition Documentation
MAX_PENDING_RETURN_PACKETS
#define MAX_PENDING_RETURN_PACKETS 32
Definition at line 55 of file tmqh-packetpool.c.
RESERVED_PACKETS
#define RESERVED_PACKETS 10
number of packets to keep reserved when calculating the the pending return packets count. This assumes we need at max 10 packets in one PacketPoolWaitForN call. The actual number is 9 now, so this has a bit of margin.
Definition at line 506 of file tmqh-packetpool.c.
Function Documentation
PacketPoolDestroy()
void PacketPoolDestroy (void)
Definition at line 336 of file tmqh-packetpool.c.
PacketPoolGetPacket()
Packet * PacketPoolGetPacket (void)
Get a new packet from the packet pool.
Only allocates from the thread's local stack, or mallocs new packets. If the local stack is empty, first move all the return stack packets to the local stack.
Return values
Packet pointer, or NULL on failure.
Definition at line 186 of file tmqh-packetpool.c.
Referenced by FlowForceReassemblyPseudoPacketGet(), PacketGetFromQueueOrAlloc(), and TmqhInputPacketpool().
PacketPoolInit()
void PacketPoolInit (void)
Definition at line 303 of file tmqh-packetpool.c.
References max_pending_packets.
Referenced by PostRunDeinit().
PacketPoolInitEmpty()
void PacketPoolInitEmpty (void)
Definition at line 288 of file tmqh-packetpool.c.
PacketPoolPostRunmodes()
void PacketPoolPostRunmodes (void)
Set the max_pending_return_packets value.
Set it to the max pending packets value, devided by the number of lister threads. Normally, in autofp these are the stream/detect/log worker threads.
The max_pending_return_packets value needs to stay below the packet pool size of the 'producers' (normally pkt capture threads but also flow timeout injection) to avoid a deadlock where all the 'workers' keep packets in their return pools, while the capture thread can't continue because its pool is empty.
Definition at line 521 of file tmqh-packetpool.c.
References FatalError, max_pending_packets, RESERVED_PACKETS, SC_ERR_INVALID_ARGUMENT, TM_FLAG_DETECT_TM, and TmThreadCountThreadsByTmmFlags().
PacketPoolReturnPacket()
void PacketPoolReturnPacket (Packet * p)
Return packet to Packet pool.
Definition at line 226 of file tmqh-packetpool.c.
Referenced by PacketFreeOrRelease(), and PacketGetFromQueueOrAlloc().
PacketPoolWait()
void PacketPoolWait (void)
Definition at line 85 of file tmqh-packetpool.c.
Referenced by FlowForceReassemblyPseudoPacketGet(), ReceiveErfFileLoop(), and ReceivePfringLoop().
PacketPoolWaitForN()
void PacketPoolWaitForN (int n)
Wait until we have the requested amount of packets in the pool.
In some cases waiting for packets is undesirable. Especially when a wait would happen under a lock of some kind, other parts of the engine could have to wait.
This function only returns when at least N packets are in our pool.
If counting in our pool's main stack didn't give us the number we are seeking, we check if the return stack is filled and add those to our main stack. Then we retry.
Parameters
n number of packets needed
Definition at line 114 of file tmqh-packetpool.c.
TmqhInputPacketpool()
Packet * TmqhInputPacketpool (ThreadVars * tv)
Definition at line 371 of file tmqh-packetpool.c.
References PacketPoolGetPacket().
Referenced by TmqhPacketpoolRegister().
TmqhOutputPacketpool()
void TmqhOutputPacketpool (ThreadVars * t, Packet * p)
Definition at line 376 of file tmqh-packetpool.c.
References ACTION_DROP, DEBUG_VALIDATE_BUG_ON, Packet_::flags, IS_TUNNEL_PKT, IS_TUNNEL_PKT_VERDICTED, IS_TUNNEL_ROOT_PKT, m, PACKET_PROFILING_END, PACKET_RELEASE_REFS, PACKET_TEST_ACTION, PKT_ALLOC, PKT_DROP_REASON_NOT_SET, Packet_::ReleasePacket, Packet_::root, SCEnter, SCLogDebug, SCMutex, SCMutexLock, SCMutexUnlock, SCReturn, SET_TUNNEL_PKT_VERDICTED, TUNNEL_INCR_PKT_RTV_NOLOCK, Packet_::tunnel_mutex, TUNNEL_PKT_RTV, and TUNNEL_PKT_TPR.
Referenced by TmqhPacketpoolRegister(), and TmqhReleasePacketsToPacketPool().
TmqhPacketpoolRegister()
void TmqhPacketpoolRegister (void)
TmqhPacketpoolRegister \initonly.
Definition at line 69 of file tmqh-packetpool.c.
References Tmqh_::InHandler, Tmqh_::name, Tmqh_::OutHandler, TMQH_PACKETPOOL, tmqh_table, TmqhInputPacketpool(), and TmqhOutputPacketpool().
Referenced by TmqhSetup().
TmqhReleasePacketsToPacketPool()
void TmqhReleasePacketsToPacketPool (PacketQueue * pq)
Release all the packets in the queue back to the packetpool. Mainly used by threads that have failed, and wants to return the packets back to the packetpool.
Parameters
pq Pointer to the packetqueue from which the packets have to be returned back to the packetpool
Warning
this function assumes that the pq does not use locking
Definition at line 489 of file tmqh-packetpool.c.
References PacketDequeue(), and TmqhOutputPacketpool().
Variable Documentation
thread_pkt_pool
thread_local PktPool thread_pkt_pool
Definition at line 58 of file tmqh-packetpool.c.