suricata: /Users/jlu/suricata/src/tmqh-flow.h File Reference
tmqh-flow.h File Reference
Data Structures
struct TmqhFlowMode_
struct TmqhFlowCtx_
Ctx for the flow queue handler.
Typedefs
typedef struct TmqhFlowMode_ TmqhFlowMode
typedef struct TmqhFlowCtx_ TmqhFlowCtx
Ctx for the flow queue handler.
Functions
void TmqhFlowRegister (void)
void TmqhFlowRegisterTests (void)
void TmqhFlowPrintAutofpHandler (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file tmqh-flow.h.
Typedef Documentation
TmqhFlowCtx
typedef struct TmqhFlowCtx_ TmqhFlowCtx
Ctx for the flow queue handler.
Parameters
size number of queues to output to
queues array of queue id's this flow handler outputs to
TmqhFlowMode
typedef struct TmqhFlowMode_ TmqhFlowMode
Function Documentation
TmqhFlowPrintAutofpHandler()
void TmqhFlowPrintAutofpHandler (void)
Definition at line 82 of file tmqh-flow.c.
References PRINT_IF_FUNC, TmqhOutputFlowHash(), and TmqhOutputFlowIPPair().
TmqhFlowRegister()
void TmqhFlowRegister (void)
Definition at line 49 of file tmqh-flow.c.
References ConfGet(), Tmqh_::InHandler, Tmqh_::name, Tmqh_::OutHandler, Tmqh_::OutHandlerCtxFree, Tmqh_::OutHandlerCtxSetup, Tmqh_::RegisterTests, SC_ERR_INVALID_YAML_CONF_ENTRY, SCLogError, SCLogNotice, TMQH_FLOW, tmqh_table, TmqhFlowRegisterTests(), TmqhInputFlow(), TmqhOutputFlowFreeCtx(), TmqhOutputFlowHash(), TmqhOutputFlowIPPair(), and TmqhOutputFlowSetupCtx().
Referenced by TmqhSetup().
TmqhFlowRegisterTests()
void TmqhFlowRegisterTests (void)
Definition at line 375 of file tmqh-flow.c.
References UtRegisterTest().
Referenced by TmqhFlowRegister().