suricata: /Users/jlu/suricata/src/tmqh-flow.c File Reference
tmqh-flow.c File Reference
#include "suricata.h"
#include "packet-queue.h"
#include "decode.h"
#include "threads.h"
#include "threadvars.h"
#include "tmqh-flow.h"
#include "tm-queuehandlers.h"
#include "conf.h"
#include "util-unittest.h"
Macros
#define PRINT_IF_FUNC(f, msg)
Functions
Packet * TmqhInputFlow (ThreadVars *t)
void TmqhOutputFlowHash (ThreadVars *t, Packet *p)
void TmqhOutputFlowIPPair (ThreadVars *tv, Packet *p)
select the queue to output based on IP address pair.
void * TmqhOutputFlowSetupCtx (const char *queue_str)
setup the queue handlers ctx
void TmqhOutputFlowFreeCtx (void *ctx)
void TmqhFlowRegisterTests (void)
void TmqhFlowRegister (void)
void TmqhFlowPrintAutofpHandler (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Simple output queue handler that makes sure all packets of the same flow are sent to the same queue. We support different kind of q handlers. Have a look at "autofp-scheduler" conf to further undertsand the various q handlers we provide.
Definition in file tmqh-flow.c.
Macro Definition Documentation
PRINT_IF_FUNC
#define PRINT_IF_FUNC (f, msg)
Value:
    if (tmqh_table[TMQH_FLOW].OutHandler == (f))    \
        SCLogConfig("AutoFP mode using \"%s\" flow load balancer", (msg))
Function Documentation
TmqhFlowPrintAutofpHandler()
void TmqhFlowPrintAutofpHandler (void)
Definition at line 82 of file tmqh-flow.c.
References PRINT_IF_FUNC, TmqhOutputFlowHash(), and TmqhOutputFlowIPPair().
TmqhFlowRegister()
void TmqhFlowRegister (void)
Definition at line 49 of file tmqh-flow.c.
References ConfGet(), Tmqh_::InHandler, Tmqh_::name, Tmqh_::OutHandler, Tmqh_::OutHandlerCtxFree, Tmqh_::OutHandlerCtxSetup, Tmqh_::RegisterTests, SC_ERR_INVALID_YAML_CONF_ENTRY, SCLogError, SCLogNotice, TMQH_FLOW, tmqh_table, TmqhFlowRegisterTests(), TmqhInputFlow(), TmqhOutputFlowFreeCtx(), TmqhOutputFlowHash(), TmqhOutputFlowIPPair(), and TmqhOutputFlowSetupCtx().
Referenced by TmqhSetup().
TmqhFlowRegisterTests()
void TmqhFlowRegisterTests (void)
Definition at line 375 of file tmqh-flow.c.
References UtRegisterTest().
Referenced by TmqhFlowRegister().
TmqhInputFlow()
Packet * TmqhInputFlow (ThreadVars * t)
Definition at line 95 of file tmqh-flow.c.
References PacketQueue_::cond_q, ThreadVars_::inq, PacketQueue_::len, PacketQueue_::mutex_q, PacketDequeue(), Tmq_::pq, SCCondWait, SCMutexLock, SCMutexUnlock, StatsSyncCountersIfSignalled, and tv.
Referenced by TmqhFlowRegister().
TmqhOutputFlowFreeCtx()
void TmqhOutputFlowFreeCtx (void * ctx)
Definition at line 209 of file tmqh-flow.c.
References TmqhFlowCtx_::queues, SCFree, SCLogPerf, and TmqhFlowCtx_::size.
Referenced by TmqhFlowRegister().
TmqhOutputFlowHash()
void TmqhOutputFlowHash (ThreadVars * t, Packet * p)
Definition at line 221 of file tmqh-flow.c.
References PacketQueue_::cond_q, Packet_::flags, Packet_::flow_hash, TmqhFlowCtx_::last, PacketQueue_::mutex_q, ThreadVars_::outctx, PacketEnqueue(), PKT_WANTS_FLOW, TmqhFlowMode_::q, TmqhFlowCtx_::queues, SCCondSignal, SCMutexLock, SCMutexUnlock, TmqhFlowCtx_::size, and tv.
Referenced by TmqhFlowPrintAutofpHandler(), and TmqhFlowRegister().
TmqhOutputFlowIPPair()
void TmqhOutputFlowIPPair (ThreadVars * tv, Packet * p)
select the queue to output based on IP address pair.
Parameters
tv thread vars.
p packet.
Definition at line 251 of file tmqh-flow.c.
References PacketQueue_::cond_q, Packet_::dst, Address_::family, PacketQueue_::mutex_q, ThreadVars_::outctx, PacketEnqueue(), TmqhFlowMode_::q, TmqhFlowCtx_::queues, SCCondSignal, SCMutexLock, SCMutexUnlock, TmqhFlowCtx_::size, Packet_::src, and tv.
Referenced by TmqhFlowPrintAutofpHandler(), and TmqhFlowRegister().
TmqhOutputFlowSetupCtx()
void * TmqhOutputFlowSetupCtx (const char * queue_str)
setup the queue handlers ctx
Parses a comma separated string "queuename1,queuename2,etc" and sets the ctx up to devide flows over these queue's.
Parameters
queue_str comma separated string with output queue names
Return values
ctx queues handlers ctx or NULL in error
Definition at line 163 of file tmqh-flow.c.
References SCLogDebug, SCMalloc, SCStrdup, str, and unlikely.
Referenced by TmqhFlowRegister().