suricata: /Users/jlu/suricata/src/util-profiling-rulegroups.c File Reference
util-profiling-rulegroups.c File Reference
#include "suricata-common.h"
#include "decode.h"
#include "detect.h"
#include "detect-engine.h"
#include "conf.h"
#include "tm-threads.h"
#include "util-unittest.h"
#include "util-byte.h"
#include "util-profiling.h"
#include "util-profiling-locks.h"
#include "util-time.h"
Data Structures
struct SCProfileSghData_
struct SCProfileSghDetectCtx_
Macros
#define ADD(name) de_ctx->profile_sgh_ctx->data[i].name += det_ctx->sgh_perf_data[i].name
Typedefs
typedef struct SCProfileSghData_ SCProfileSghData
typedef struct SCProfileSghDetectCtx_ SCProfileSghDetectCtx
Functions
void SCProfilingSghsGlobalInit (void)
void SCProfilingSghUpdateCounter (DetectEngineThreadCtx *det_ctx, const SigGroupHead *sgh)
Update a rule counter.
void SCProfilingSghDestroyCtx (DetectEngineCtx *de_ctx)
void SCProfilingSghThreadSetup (SCProfileSghDetectCtx *ctx, DetectEngineThreadCtx *det_ctx)
void SCProfilingSghThreadCleanup (DetectEngineThreadCtx *det_ctx)
void SCProfilingSghInitCounters (DetectEngineCtx *de_ctx)
Register the keyword profiling counters.
Variables
int profiling_sghs_enabled = 0
Detailed Description
Author
Endace Technology Limited.
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
An API for rule profiling operations.
Definition in file util-profiling-rulegroups.c.
Macro Definition Documentation
ADD
#define ADD (name) de_ctx->profile_sgh_ctx->data[i].name += det_ctx->sgh_perf_data[i].name
Typedef Documentation
SCProfileSghData
typedef struct SCProfileSghData_ SCProfileSghData
Extra data for rule profiling.
SCProfileSghDetectCtx
typedef struct SCProfileSghDetectCtx_ SCProfileSghDetectCtx
Function Documentation
SCProfilingSghDestroyCtx()
void SCProfilingSghDestroyCtx (DetectEngineCtx * de_ctx)
Definition at line 311 of file util-profiling-rulegroups.c.
References de_ctx.
Referenced by DetectEngineCtxFree().
SCProfilingSghInitCounters()
void SCProfilingSghInitCounters (DetectEngineCtx * de_ctx)
Register the keyword profiling counters.
Parameters
de_ctx The active DetectEngineCtx, used to get at the loaded rules.
Definition at line 376 of file util-profiling-rulegroups.c.
References de_ctx, DetectEngineCtx_::profile_sgh_ctx, and profiling_sghs_enabled.
SCProfilingSghsGlobalInit()
void SCProfilingSghsGlobalInit (void)
Definition at line 72 of file util-profiling-rulegroups.c.
References ConfGetNode(), ConfigGetLogDirectory(), ConfNodeChildValueIsTrue(), ConfNodeLookupChildValue(), and profiling_sghs_enabled.
Referenced by PreRunInit().
SCProfilingSghThreadCleanup()
void SCProfilingSghThreadCleanup (DetectEngineThreadCtx * det_ctx)
Definition at line 357 of file util-profiling-rulegroups.c.
References SCProfileSghDetectCtx_::data_m, DetectEngineThreadCtx_::de_ctx, DetectEngineCtx_::profile_sgh_ctx, and DetectEngineThreadCtx_::sgh_perf_data.
SCProfilingSghThreadSetup()
void SCProfilingSghThreadSetup (SCProfileSghDetectCtx * ctx, DetectEngineThreadCtx * det_ctx)
Definition at line 320 of file util-profiling-rulegroups.c.
References DetectEngineThreadCtx_::de_ctx, SCCalloc, DetectEngineCtx_::sgh_array_cnt, and DetectEngineThreadCtx_::sgh_perf_data.
SCProfilingSghUpdateCounter()
void SCProfilingSghUpdateCounter (DetectEngineThreadCtx * det_ctx, const SigGroupHead * sgh)
Update a rule counter.
Parameters
id The ID of this counter.
ticks Number of CPU ticks for this rule.
match Did the rule match?
Definition at line 268 of file util-profiling-rulegroups.c.
References SCProfileSghData_::checks, DetectEngineThreadCtx_::de_ctx, SigGroupHead_::id, DetectEngineThreadCtx_::match_array_cnt, SCProfileSghData_::mpm_match_cnt_max, SCProfileSghData_::mpm_match_cnt_total, SCProfileSghData_::non_mpm_generic, SCProfileSghData_::non_mpm_syn, DetectEngineThreadCtx_::non_pf_store_cnt, DetectEngineThreadCtx_::non_pf_store_ptr, SigGroupHead_::non_pf_syn_store_array, DetectEngineThreadCtx_::pmq, SCProfileSghData_::post_prefilter_sigs_max, SCProfileSghData_::post_prefilter_sigs_total, PrefilterRuleStore_::rule_id_array_cnt, DetectEngineCtx_::sgh_array_cnt, and DetectEngineThreadCtx_::sgh_perf_data.
Variable Documentation
profiling_sghs_enabled
int profiling_sghs_enabled = 0
Definition at line 67 of file util-profiling-rulegroups.c.
Referenced by SCProfilingSghInitCounters(), and SCProfilingSghsGlobalInit().