suricata: /Users/jlu/suricata/src/util-misc.h File Reference
util-misc.h File Reference
Macros
#define WarnInvalidConfEntry(param_name, format, value)
Generic API that can be used by all to log an invalid conf entry.
Functions
int ParseSizeStringU8 (const char *, uint8_t *)
int ParseSizeStringU16 (const char *, uint16_t *)
int ParseSizeStringU32 (const char *, uint32_t *)
int ParseSizeStringU64 (const char *, uint64_t *)
void UtilMiscRegisterTests (void)
void ParseSizeInit (void)
void ParseSizeDeinit (void)
void ShortenString (const char *input, char *output, size_t output_size, char c)
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file util-misc.h.
Macro Definition Documentation
WarnInvalidConfEntry
#define WarnInvalidConfEntry (param_name, format, value)
Value:
        do {            \
        SCLogWarning(SC_ERR_INVALID_YAML_CONF_ENTRY,                    \
                     "Invalid conf entry found for "                    \
                     "\"%s\".  Using default value of \"" format "\".", \
                     param_name, value);                                \
    } while (0)
Generic API that can be used by all to log an invalid conf entry.
Parameters
param_name A string specifying the param name.
format Format for the below value. For example "%s", "%"PRIu32, etc.
value Default value to be printed.
Definition at line 36 of file util-misc.h.
Function Documentation
ParseSizeDeinit()
void ParseSizeDeinit (void)
Definition at line 55 of file util-misc.c.
ParseSizeInit()
void ParseSizeInit (void)
Definition at line 35 of file util-misc.c.
Referenced by InitGlobal().
ParseSizeStringU16()
int ParseSizeStringU16 (const char * size, uint16_t * res)
Definition at line 166 of file util-misc.c.
References res.
Referenced by StreamTcpInitConfig().
ParseSizeStringU32()
int ParseSizeStringU32 (const char * size, uint32_t * res)
Definition at line 183 of file util-misc.c.
References res.
Referenced by RegisterMQTTParsers(), and StreamTcpInitConfig().
ParseSizeStringU64()
int ParseSizeStringU64 (const char * size, uint64_t * res)
Definition at line 200 of file util-misc.c.
References res.
Referenced by FlowInitConfig(), HTPParseMemcap(), HttpRangeContainersInit(), RunModeInitialize(), and StreamTcpInitConfig().
ParseSizeStringU8()
int ParseSizeStringU8 (const char * size, uint8_t * res)
Definition at line 149 of file util-misc.c.
References res.
ShortenString()
void ShortenString (const char * input, char * output, size_t output_size, char c)
Definition at line 217 of file util-misc.c.
References strlcat().
Referenced by DetectAppLayerMpmRegisterByParentId().
UtilMiscRegisterTests()
void UtilMiscRegisterTests (void)
Definition at line 1169 of file util-misc.c.
References UtRegisterTest().