suricata: /Users/jlu/suricata/src/util-runmodes.h File Reference
util-runmodes.h File Reference
Typedefs
typedef void *(* ConfigIfaceParserFunc) (const char *)
typedef void *(* ConfigIPSParserFunc) (int)
typedef int(* ConfigIfaceThreadsCountFunc) (void *)
Functions
int RunModeSetLiveCaptureAuto (ConfigIfaceParserFunc configparser, ConfigIfaceThreadsCountFunc ModThreadsCount, const char *recv_mod_name, const char *decode_mod_name, const char *thread_name, const char *live_dev)
int RunModeSetLiveCaptureAutoFp (ConfigIfaceParserFunc configparser, ConfigIfaceThreadsCountFunc ModThreadsCount, const char *recv_mod_name, const char *decode_mod_name, const char *thread_name, const char *live_dev)
int RunModeSetLiveCaptureSingle (ConfigIfaceParserFunc configparser, ConfigIfaceThreadsCountFunc ModThreadsCount, const char *recv_mod_name, const char *decode_mod_name, const char *thread_name, const char *live_dev)
int RunModeSetLiveCaptureWorkers (ConfigIfaceParserFunc configparser, ConfigIfaceThreadsCountFunc ModThreadsCount, const char *recv_mod_name, const char *decode_mod_name, const char *thread_name, const char *live_dev)
int RunModeSetIPSAutoFp (ConfigIPSParserFunc ConfigParser, const char *recv_mod_name, const char *verdict_mod_name, const char *decode_mod_name)
int RunModeSetIPSWorker (ConfigIPSParserFunc ConfigParser, const char *recv_mod_name, const char *verdict_mod_name, const char *decode_mod_name)
char * RunmodeAutoFpCreatePickupQueuesString (int n)
create a queue string for autofp to pass to the flow queue handler.
Detailed Description
Author
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Definition in file util-runmodes.h.
Typedef Documentation
ConfigIfaceParserFunc
typedef void *(* ConfigIfaceParserFunc) (const char *)
Definition at line 26 of file util-runmodes.h.
ConfigIfaceThreadsCountFunc
typedef int(* ConfigIfaceThreadsCountFunc) (void *)
Definition at line 28 of file util-runmodes.h.
ConfigIPSParserFunc
typedef void *(* ConfigIPSParserFunc) (int)
Definition at line 27 of file util-runmodes.h.
Function Documentation
RunmodeAutoFpCreatePickupQueuesString()
char * RunmodeAutoFpCreatePickupQueuesString (int n)
create a queue string for autofp to pass to the flow queue handler.
The string will be "pickup1,pickup2,pickup3\0"
Definition at line 56 of file util-runmodes.c.
References SC_ERR_MEM_ALLOC, SCLogDebug, SCLogError, SCMalloc, strlcat(), TM_QUEUE_NAME_MAX, and unlikely.
Referenced by RunModeErfFileAutoFp(), RunModeFilePcapAutoFp(), RunModeSetIPSAutoFp(), and RunModeSetLiveCaptureAutoFp().
RunModeSetIPSAutoFp()
int RunModeSetIPSAutoFp (ConfigIPSParserFunc ConfigParser, const char * recv_mod_name, const char * verdict_mod_name, const char * decode_mod_name)
Definition at line 400 of file util-runmodes.c.
References FatalError, LiveGetDeviceCount(), LiveGetDeviceName(), RECEIVE_CPU_SET, RunmodeAutoFpCreatePickupQueuesString(), SC_ERR_RUNMODE, SCEnter, SCFree, SCLogDebug, thread_name_autofp, thread_name_verdict, thread_name_workers, TM_ECODE_OK, TM_QUEUE_NAME_MAX, TM_THREAD_NAME_MAX, TmModuleGetByName(), TmSlotSetFuncAppend(), TmThreadCreatePacketHandler(), TmThreadSetCPU(), TmThreadSetGroupName(), TmThreadsGetWorkerThreadMax(), TmThreadSpawn(), VERDICT_CPU_SET, and WORKER_CPU_SET.
Referenced by RunModeIpsIPFWAutoFp(), RunModeIpsNFQAutoFp(), and RunModeIpsWinDivertAutoFp().
RunModeSetIPSWorker()
int RunModeSetIPSWorker (ConfigIPSParserFunc ConfigParser, const char * recv_mod_name, const char * verdict_mod_name, const char * decode_mod_name)
Definition at line 523 of file util-runmodes.c.
References FatalError, LiveGetDeviceCount(), LiveGetDeviceName(), SC_ERR_INVALID_VALUE, SC_ERR_RUNMODE, SC_ERR_THREAD_CREATE, thread_name_workers, TM_ECODE_OK, TM_THREAD_NAME_MAX, TmModuleGetByName(), TmSlotSetFuncAppend(), TmThreadCreatePacketHandler(), TmThreadSetCPU(), TmThreadSpawn(), tv, and WORKER_CPU_SET.
Referenced by RunModeIpsIPFWWorker(), and RunModeIpsNFQWorker().
RunModeSetLiveCaptureAuto()
int RunModeSetLiveCaptureAuto (ConfigIfaceParserFunc configparser, ConfigIfaceThreadsCountFunc ModThreadsCount, const char * recv_mod_name, const char * decode_mod_name, const char * thread_name, const char * live_dev)
RunModeSetLiveCaptureAutoFp()
int RunModeSetLiveCaptureAutoFp (ConfigIfaceParserFunc configparser, ConfigIfaceThreadsCountFunc ModThreadsCount, const char * recv_mod_name, const char * decode_mod_name, const char * thread_name, const char * live_dev)
Definition at line 87 of file util-runmodes.c.
References FatalError, LiveGetDeviceCount(), LiveGetDeviceName(), LiveGetShortName(), ThreadVars_::printable_name, RECEIVE_CPU_SET, RunmodeAutoFpCreatePickupQueuesString(), SC_ERR_MEM_ALLOC, SC_ERR_RUNMODE, SCFree, SCLogDebug, SCLogInfo, SCMalloc, thread_name_workers, TM_ECODE_OK, TM_QUEUE_NAME_MAX, TM_THREAD_NAME_MAX, TmModuleGetByName(), TmSlotSetFuncAppend(), TmThreadCreatePacketHandler(), TmThreadSetCPU(), TmThreadSetGroupName(), TmThreadsGetWorkerThreadMax(), TmThreadSpawn(), unlikely, and WORKER_CPU_SET.
Referenced by RunModeIdsAFPAutoFp(), RunModeIdsErfDagAutoFp(), and RunModeIdsPcapAutoFp().
RunModeSetLiveCaptureSingle()
int RunModeSetLiveCaptureSingle (ConfigIfaceParserFunc configparser, ConfigIfaceThreadsCountFunc ModThreadsCount, const char * recv_mod_name, const char * decode_mod_name, const char * thread_name, const char * live_dev)
Definition at line 364 of file util-runmodes.c.
References FatalError, LiveGetDeviceCount(), LiveGetDeviceName(), and SC_ERR_RUNMODE.
Referenced by RunModeIdsAFPSingle(), RunModeIdsErfDagSingle(), and RunModeIdsPcapSingle().
RunModeSetLiveCaptureWorkers()
int RunModeSetLiveCaptureWorkers (ConfigIfaceParserFunc configparser, ConfigIfaceThreadsCountFunc ModThreadsCount, const char * recv_mod_name, const char * decode_mod_name, const char * thread_name, const char * live_dev)
Definition at line 330 of file util-runmodes.c.
References FatalError, LiveGetDeviceCount(), LiveGetDeviceName(), SC_ERR_MEM_ALLOC, and unlikely.
Referenced by RunModeIdsAFPWorkers(), RunModeIdsDpdkWorkers(), RunModeIdsErfDagWorkers(), and RunModeIdsPcapWorkers().