suricata: /Users/jlu/suricata/src/util-buffer.c File Reference
util-buffer.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "util-debug.h"
#include "util-buffer.h"
Macros
#define MAX_LIMIT 10485760
Functions
MemBuffer * MemBufferCreateNew (uint32_t size)
int MemBufferExpand (MemBuffer **buffer, uint32_t expand_by)
expand membuffer by size of 'expand_by'
void MemBufferFree (MemBuffer *buffer)
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file util-buffer.c.
Macro Definition Documentation
MAX_LIMIT
#define MAX_LIMIT 10485760
Definition at line 30 of file util-buffer.c.
Function Documentation
MemBufferCreateNew()
MemBuffer * MemBufferCreateNew (uint32_t size)
Definition at line 32 of file util-buffer.c.
References MAX_LIMIT, SC_ERR_MEM_BUFFER_API, SCLogWarning, SCMalloc, and unlikely.
Referenced by CreateEveThreadCtx(), JsonLogThreadInit(), LogHttpLogThreadInit(), LogStatsLogThreadInit(), and LogTcpDataLogThreadInit().
MemBufferExpand()
int MemBufferExpand (MemBuffer ** buffer, uint32_t expand_by)
expand membuffer by size of 'expand_by'
If expansion failed, buffer will still be valid.
Return values
result 0 ok, -1 expansion failed
Definition at line 60 of file util-buffer.c.
References MAX_LIMIT, SC_ERR_MEM_BUFFER_API, SCLogDebug, SCLogWarning, SCRealloc, MemBuffer_::size, and unlikely.
Referenced by OutputJsonBuilderBuffer(), and OutputJSONMemBufferCallback().
MemBufferFree()
void MemBufferFree (MemBuffer * buffer)
Definition at line 82 of file util-buffer.c.
References SCFree.
Referenced by CreateEveThreadCtx(), FreeEveThreadCtx(), JsonLogThreadInit(), LogHttpLogThreadDeinit(), LogStatsLogThreadDeinit(), and LogTcpDataLogThreadDeinit().