suricata: /Users/jlu/suricata/src/util-unittest-helper.c File Reference
util-unittest-helper.c File Reference
#include "suricata-common.h"
#include "decode.h"
#include "flow-private.h"
#include "flow-util.h"
#include "flow-spare-pool.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-sigorder.h"
#include "detect-engine-build.h"
#include "stream-tcp.h"
#include "stream-tcp-private.h"
#include "util-debug.h"
#include "util-time.h"
#include "util-error.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-spm-bs.h"
Functions
Flow * TestHelperBuildFlow (int family, const char *src, const char *dst, Port sp, Port dp)
int TestHelperBufferToFile (const char *name, const uint8_t *data, size_t size)
writes the contents of a buffer into a file
uint32_t UTHSetIPv4Address (const char *str)
return the uint32_t for a ipv4 address string
Packet * UTHBuildPacketIPV6Real (uint8_t *payload, uint16_t payload_len, uint8_t ipproto, const char *src, const char *dst, uint16_t sport, uint16_t dport)
UTHBuildPacketReal is a function that create tcp/udp packets for unittests specifying ip and port sources and destinations (IPV6)
Packet * UTHBuildPacketReal (uint8_t *payload, uint16_t payload_len, uint8_t ipproto, const char *src, const char *dst, uint16_t sport, uint16_t dport)
UTHBuildPacketReal is a function that create tcp/udp packets for unittests specifying ip and port sources and destinations.
Packet * UTHBuildPacket (uint8_t *payload, uint16_t payload_len, uint8_t ipproto)
UTHBuildPacket is a wrapper that build packets with default ip and port fields.
Packet ** UTHBuildPacketArrayFromEth (uint8_t *raw_eth[], int *pktsize, int numpkts)
UTHBuildPacketArrayFromEth is a wrapper that build a packets from an array of packets in ethernet rawbytes. Hint: It also share the flows.
Packet * UTHBuildPacketFromEth (uint8_t *raw_eth, uint16_t pktsize)
UTHBuildPacketFromEth is a wrapper that build a packet for the rawbytes.
Packet * UTHBuildPacketSrcDst (uint8_t *payload, uint16_t payload_len, uint8_t ipproto, const char *src, const char *dst)
UTHBuildPacketSrcDst is a wrapper that build packets specifying IPs and defaulting ports.
Packet * UTHBuildPacketIPV6SrcDst (uint8_t *payload, uint16_t payload_len, uint8_t ipproto, const char *src, const char *dst)
UTHBuildPacketSrcDst is a wrapper that build packets specifying IPs and defaulting ports (IPV6)
Packet * UTHBuildPacketSrcDstPorts (uint8_t *payload, uint16_t payload_len, uint8_t ipproto, uint16_t sport, uint16_t dport)
UTHBuildPacketSrcDstPorts is a wrapper that build packets specifying src and dst ports and defaulting IPs.
void UTHFreePackets (Packet **p, int numpkts)
UTHFreePackets: function to release the allocated data from UTHBuildPacket and the packet itself.
void UTHFreePacket (Packet *p)
UTHFreePacket: function to release the allocated data from UTHBuildPacket and the packet itself.
void UTHAssignFlow (Packet *p, Flow *f)
Flow * UTHBuildFlow (int family, const char *src, const char *dst, Port sp, Port dp)
void UTHFreeFlow (Flow *flow)
int UTHAddStreamToFlow (Flow *f, int direction, uint8_t *data, uint32_t data_len)
int UTHAddSessionToFlow (Flow *f, uint32_t ts_isn, uint32_t tc_isn)
int UTHRemoveSessionFromFlow (Flow *f)
int UTHGenericTest (Packet **pkt, int numpkts, const char *sigs[], uint32_t sids[], uint32_t *results, int numsigs)
UTHGenericTest: function that perfom a generic check taking care of as maximum common unittest elements as possible. It will create a detection engine, append an array of signatures an check the spected results for each of them, it check matches for an array of packets.
int UTHCheckPacketMatchResults (Packet *p, uint32_t sids[], uint32_t results[], int numsids)
UTHCheckPacketMatches: function to check if a packet match some sids.
int UTHAppendSigs (DetectEngineCtx *de_ctx, const char *sigs[], int numsigs)
UTHAppendSigs: Add sigs to the detection_engine checking for errors.
int UTHMatchPacketsWithResults (DetectEngineCtx *de_ctx, Packet **p, int num_packets, uint32_t sids[], uint32_t *results, int numsigs)
int UTHMatchPackets (DetectEngineCtx *de_ctx, Packet **p, int num_packets)
int UTHPacketMatchSigMpm (Packet *p, char *sig, uint16_t mpm_type)
int UTHPacketMatchSig (Packet *p, const char *sig)
uint32_t UTHBuildPacketOfFlows (uint32_t start, uint32_t end, uint8_t dir)
int UTHParseSignature (const char *str, bool expect)
parser a sig and see if the expected result is correct
void * UTHmemsearch (const void *big, size_t big_len, const void *little, size_t little_len)
void UTHRegisterTests (void)
Detailed Description
Author
Pablo Rincon Crespo pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
This file provide a set of helper functions for reducing the complexity when constructing unittests
Definition in file util-unittest-helper.c.
Function Documentation
TestHelperBufferToFile()
int TestHelperBufferToFile (const char * name, const uint8_t * data, size_t size)
writes the contents of a buffer into a file
Definition at line 102 of file util-unittest-helper.c.
TestHelperBuildFlow()
Flow * TestHelperBuildFlow (int family, const char * src, const char * dst, Port sp, Port dp)
Definition at line 51 of file util-unittest-helper.c.
References BUG_ON, dst, FLOW_INITIALIZE, FLOW_IPV4, FLOW_IPV6, SCFree, SCMalloc, src, and unlikely.
Referenced by LLVMFuzzerTestOneInput(), and UTHBuildFlow().
UTHAddSessionToFlow()
int UTHAddSessionToFlow (Flow * f, uint32_t ts_isn, uint32_t tc_isn)
Definition at line 550 of file util-unittest-helper.c.
References TcpSession_::client, FAIL_IF_NULL, TcpStream_::isn, Flow_::protoctx, TcpStream_::sb, TcpStreamCnf_::sbcnf, SCCalloc, TcpSession_::server, stream_config, and STREAMING_BUFFER_INITIALIZER.
UTHAddStreamToFlow()
int UTHAddStreamToFlow (Flow * f, int direction, uint8_t * data, uint32_t data_len)
Definition at line 534 of file util-unittest-helper.c.
References TcpSession_::client, FAIL_IF_NOT, FAIL_IF_NULL, TcpStream_::last_ack, Flow_::proto, Flow_::protoctx, TcpStream_::sb, TcpSession_::server, and StreamingBufferAppend().
UTHAppendSigs()
int UTHAppendSigs (DetectEngineCtx * de_ctx, const char * sigs[], int numsigs)
UTHAppendSigs: Add sigs to the detection_engine checking for errors.
Parameters
de_ctx pointer to the DetectEngineCtx used
sigs array of char* pointing to signatures to load
numsigs number of signatures to load from the array (size of the array)
Return values
int 0 if we have errors; 1 if all the signatures loaded succesfuly
Definition at line 678 of file util-unittest-helper.c.
References BUG_ON, de_ctx, DetectEngineAppendSig(), SC_ERR_INVALID_ARGUMENT, and SCLogError.
Referenced by UTHGenericTest().
UTHAssignFlow()
void UTHAssignFlow (Packet * p, Flow * f)
Definition at line 514 of file util-unittest-helper.c.
References Packet_::flags, Packet_::flow, and PKT_HAS_FLOW.
UTHBuildFlow()
Flow * UTHBuildFlow (int family, const char * src, const char * dst, Port sp, Port dp)
Definition at line 522 of file util-unittest-helper.c.
References dst, src, and TestHelperBuildFlow().
UTHBuildPacket()
Packet * UTHBuildPacket (uint8_t * payload, uint16_t payload_len, uint8_t ipproto)
UTHBuildPacket is a wrapper that build packets with default ip and port fields.
Parameters
payload pointer to the payloadd buffer
payload_len pointer to the length of the payload
ipproto Protocols allowed atm are IPPROTO_TCP and IPPROTO_UDP
Return values
Packet pointer to the built in packet
Definition at line 338 of file util-unittest-helper.c.
References payload_len, and UTHBuildPacketReal().
Referenced by UTHBuildPacketOfFlows().
UTHBuildPacketArrayFromEth()
Packet ** UTHBuildPacketArrayFromEth (uint8_t * raw_eth[], int * pktsize, int numpkts)
UTHBuildPacketArrayFromEth is a wrapper that build a packets from an array of packets in ethernet rawbytes. Hint: It also share the flows.
Parameters
raw_eth pointer to the array of ethernet packets in rawbytes
pktsize pointer to the array of sizes corresponding to each buffer pointed from pktsize.
numpkts number of packets in the array
Return values
Packet pointer to the array of built in packets; NULL if something fail
Definition at line 357 of file util-unittest-helper.c.
References DecodeEthernet(), dtv, PacketGetFromAlloc(), SC_ERR_INVALID_ARGUMENT, SCFree, SCLogError, SCMalloc, and unlikely.
UTHBuildPacketFromEth()
Packet * UTHBuildPacketFromEth (uint8_t * raw_eth, uint16_t pktsize)
UTHBuildPacketFromEth is a wrapper that build a packet for the rawbytes.
Parameters
raw_eth pointer to the rawbytes containing an ethernet packet (and any other headers inside)
pktsize pointer to the length of the payload
Return values
Packet pointer to the built in packet; NULL if something fail
Definition at line 395 of file util-unittest-helper.c.
References DecodeEthernet(), dtv, PacketGetFromAlloc(), and unlikely.
UTHBuildPacketIPV6Real()
Packet * UTHBuildPacketIPV6Real (uint8_t * payload, uint16_t payload_len, uint8_t ipproto, const char * src, const char * dst, uint16_t sport, uint16_t dport)
UTHBuildPacketReal is a function that create tcp/udp packets for unittests specifying ip and port sources and destinations (IPV6)
Parameters
payload pointer to the payloadd buffer
payload_len pointer to the length of the payload
ipproto Protocols allowed atm are IPPROTO_TCP and IPPROTO_UDP
src pointer to a string containing the ip source
dst pointer to a string containing the ip destination
sport pointer to a string containing the port source
dport pointer to a string containing the port destination
Return values
Packet pointer to the built in packet
Definition at line 157 of file util-unittest-helper.c.
References Packet_::dp, dst, Packet_::dst, Address_::family, Packet_::ip6h, PacketGetFromAlloc(), Packet_::payload, Packet_::payload_len, payload_len, Packet_::proto, SCFree, SCMalloc, SET_PKT_LEN, Packet_::sp, src, Packet_::src, Packet_::tcph, TimeGet(), Packet_::ts, and unlikely.
Referenced by UTHBuildPacketIPV6SrcDst().
UTHBuildPacketIPV6SrcDst()
Packet * UTHBuildPacketIPV6SrcDst (uint8_t * payload, uint16_t payload_len, uint8_t ipproto, const char * src, const char * dst)
UTHBuildPacketSrcDst is a wrapper that build packets specifying IPs and defaulting ports (IPV6)
Parameters
payload pointer to the payload buffer
payload_len pointer to the length of the payload
ipproto Protocols allowed atm are IPPROTO_TCP and IPPROTO_UDP
Return values
Packet pointer to the built in packet
Definition at line 437 of file util-unittest-helper.c.
References dst, payload_len, src, and UTHBuildPacketIPV6Real().
UTHBuildPacketOfFlows()
uint32_t UTHBuildPacketOfFlows (uint32_t start, uint32_t end, uint8_t dir)
Definition at line 891 of file util-unittest-helper.c.
References Packet_::dst, Packet_::flow, FlowFree(), FlowHandlePacket(), FLOWLOCK_UNLOCK, FlowQueuePrivateGetFromTop(), FlowLookupStruct_::spare_queue, Packet_::src, Flow_::use_cnt, UTHBuildPacket(), UTHFreePacket(), and FlowLookupStruct_::work_queue.
UTHBuildPacketReal()
Packet * UTHBuildPacketReal (uint8_t * payload, uint16_t payload_len, uint8_t ipproto, const char * src, const char * dst, uint16_t sport, uint16_t dport)
UTHBuildPacketReal is a function that create tcp/udp packets for unittests specifying ip and port sources and destinations.
Parameters
payload pointer to the payloadd buffer
payload_len pointer to the length of the payload
ipproto Protocols allowed atm are IPPROTO_TCP and IPPROTO_UDP
src pointer to a string containing the ip source
dst pointer to a string containing the ip destination
sport pointer to a string containing the port source
dport pointer to a string containing the port destination
Return values
Packet pointer to the built in packet
Definition at line 243 of file util-unittest-helper.c.
References COPY_TIMESTAMP, dst, GET_PKT_DATA, PacketCopyDataOffset(), PacketGetFromAlloc(), payload_len, SCFree, SET_PKT_LEN, src, TimeGet(), tv, and unlikely.
Referenced by StreamTcpUTAddPayload(), StreamTcpUTAddSegmentWithByte(), StreamTcpUTAddSegmentWithPayload(), UTHBuildPacket(), UTHBuildPacketSrcDst(), and UTHBuildPacketSrcDstPorts().
UTHBuildPacketSrcDst()
Packet * UTHBuildPacketSrcDst (uint8_t * payload, uint16_t payload_len, uint8_t ipproto, const char * src, const char * dst)
UTHBuildPacketSrcDst is a wrapper that build packets specifying IPs and defaulting ports.
Parameters
payload pointer to the payloadd buffer
payload_len pointer to the length of the payload
ipproto Protocols allowed atm are IPPROTO_TCP and IPPROTO_UDP
Return values
Packet pointer to the built in packet
Definition at line 419 of file util-unittest-helper.c.
References dst, payload_len, src, and UTHBuildPacketReal().
UTHBuildPacketSrcDstPorts()
Packet * UTHBuildPacketSrcDstPorts (uint8_t * payload, uint16_t payload_len, uint8_t ipproto, uint16_t sport, uint16_t dport)
UTHBuildPacketSrcDstPorts is a wrapper that build packets specifying src and dst ports and defaulting IPs.
Parameters
payload pointer to the payloadd buffer
payload_len pointer to the length of the payload
ipproto Protocols allowed atm are IPPROTO_TCP and IPPROTO_UDP
Return values
Packet pointer to the built in packet
Definition at line 455 of file util-unittest-helper.c.
References payload_len, and UTHBuildPacketReal().
UTHCheckPacketMatchResults()
int UTHCheckPacketMatchResults (Packet * p, uint32_t sids[], uint32_t results[], int numsids)
UTHCheckPacketMatches: function to check if a packet match some sids.
Parameters
p pointer to the Packet
sigs array of char* pointing to signatures to load
numsigs number of signatures to load from the array
results pointer to an array of numbers to check if sids matches that number of times or not.
Return values
int 1 if the match of all the sids is the specified has the specified results; 0 if not
Definition at line 644 of file util-unittest-helper.c.
References PacketAlertCheck(), res, results, SC_ERR_INVALID_ARGUMENT, SCLogError, and SCLogInfo.
Referenced by UTHMatchPacketsWithResults().
UTHFreeFlow()
void UTHFreeFlow (Flow * flow)
Definition at line 527 of file util-unittest-helper.c.
References SCFree.
UTHFreePacket()
void UTHFreePacket (Packet * p)
UTHFreePacket: function to release the allocated data from UTHBuildPacket and the packet itself.
Parameters
p pointer to the Packet
Definition at line 486 of file util-unittest-helper.c.
References Packet_::ip4h, Packet_::proto, SCFree, Packet_::tcph, and Packet_::udph.
Referenced by StreamTcpUTAddPayload(), StreamTcpUTAddSegmentWithByte(), StreamTcpUTAddSegmentWithPayload(), UTHBuildPacketOfFlows(), and UTHFreePackets().
UTHFreePackets()
void UTHFreePackets (Packet ** p, int numpkts)
UTHFreePackets: function to release the allocated data from UTHBuildPacket and the packet itself.
Parameters
p pointer to the Packet
Definition at line 469 of file util-unittest-helper.c.
References UTHFreePacket().
UTHGenericTest()
int UTHGenericTest (Packet ** pkt, int numpkts, const char * sigs[], uint32_t sids[], uint32_t * results, int numsigs)
UTHGenericTest: function that perfom a generic check taking care of as maximum common unittest elements as possible. It will create a detection engine, append an array of signatures an check the spected results for each of them, it check matches for an array of packets.
Parameters
pkt pointer to the array of packets
numpkts number of packets to match
sigs array of char* pointing to signatures to load
numsigs number of signatures to load and check
results pointer to arrays of numbers, each of them foreach packet to check if sids matches that packet as expected with that number of times or not. The size of results should be numpkts * numsigs * sizeof(uint16_t *)
Example: result[1][3] would mean the number of times the pkt[1] match the sid[3]
Return values
int 1 if the match of all the sids is the specified has the specified results; 0 if not
Definition at line 605 of file util-unittest-helper.c.
References de_ctx, DE_QUIET, DetectEngineCtxFree(), DetectEngineCtxInit(), DetectEngineCtx_::flags, results, SC_ERR_INVALID_ARGUMENT, SCLogError, UTHAppendSigs(), and UTHMatchPacketsWithResults().
UTHMatchPackets()
int UTHMatchPackets (DetectEngineCtx * de_ctx, Packet ** p, int num_packets)
Test:
UTHMatchPackets Match a packet or a array of packets against sigs of a de_ctx, but note that the return value doesn't mean that we have a match, we have to check it later with PacketAlertCheck()
Parameters
de_ctx pointer with the signatures loaded
p pointer to the array of packets
num_packets number of packets in the array
Return values
return 1 if all goes well
return 0 if something fail
Definition at line 750 of file util-unittest-helper.c.
References BUG_ON, de_ctx, DetectEngineThreadCtxDeinit(), DetectEngineThreadCtxInit(), dtv, SCSigOrderSignatures(), SCSigRegisterSignatureOrderingFuncs(), SCSigSignatureOrderingModuleCleanup(), SigGroupBuild(), SigGroupCleanup(), and SigMatchSignatures().
UTHMatchPacketsWithResults()
int UTHMatchPacketsWithResults (DetectEngineCtx * de_ctx, Packet ** p, int num_packets, uint32_t sids[], uint32_t * results, int numsigs)
Test:
UTHMatchPacketsWithResults Match a packet or a array of packets against sigs of a de_ctx, checking that each signature match match X times for certain packets
Parameters
de_ctx pointer with the signatures loaded
p pointer to the array of packets
num_packets number of packets in the array
Return values
return 1 if all goes well
return 0 if something fail
Definition at line 711 of file util-unittest-helper.c.
References BUG_ON, de_ctx, DetectEngineThreadCtxDeinit(), DetectEngineThreadCtxInit(), dtv, results, SigGroupBuild(), SigMatchSignatures(), and UTHCheckPacketMatchResults().
Referenced by UTHGenericTest().
UTHmemsearch()
void * UTHmemsearch (const void * big, size_t big_len, const void * little, size_t little_len)
Definition at line 1004 of file util-unittest-helper.c.
References BasicSearch().
UTHPacketMatchSig()
int UTHPacketMatchSig (Packet * p, const char * sig)
Test:
Test if a packet match a signature given as string Hint: Useful for unittests with only one packet and one signature
Parameters
sig pointer to the string signature to test
sid sid number of the signature
Return values
return 1 if match
return 0 if not
Definition at line 842 of file util-unittest-helper.c.
References de_ctx, DE_QUIET, DetectEngineCtxFree(), DetectEngineCtxInit(), DetectEngineThreadCtxDeinit(), DetectEngineThreadCtxInit(), dtv, DetectEngineCtx_::flags, Signature_::id, PacketAlertCheck(), DetectEngineCtx_::sig_list, SigCleanSignatures(), SigGroupBuild(), SigGroupCleanup(), SigInit(), and SigMatchSignatures().
UTHPacketMatchSigMpm()
int UTHPacketMatchSigMpm (Packet * p, char * sig, uint16_t mpm_type)
Test:
Test if a packet match a signature given as string and a mpm_type Hint: Useful for unittests with only one packet and one signature
Parameters
sig pointer to the string signature to test
sid sid number of the signature
Return values
return 1 if match
return 0 if not
Definition at line 788 of file util-unittest-helper.c.
References de_ctx, DE_QUIET, DetectEngineCtxFree(), DetectEngineCtxInit(), DetectEngineThreadCtxDeinit(), DetectEngineThreadCtxInit(), dtv, DetectEngineCtx_::flags, Signature_::id, DetectEngineCtx_::mpm_matcher, PacketAlertCheck(), SCEnter, SCReturnInt, DetectEngineCtx_::sig_list, SigGroupBuild(), SigInit(), and SigMatchSignatures().
UTHParseSignature()
int UTHParseSignature (const char * str, bool expect)
parser a sig and see if the expected result is correct
Definition at line 929 of file util-unittest-helper.c.
References de_ctx, DE_QUIET, DetectEngineAppendSig(), DetectEngineCtxFree(), DetectEngineCtxInit(), FAIL_IF_NOT_NULL, FAIL_IF_NULL, DetectEngineCtx_::flags, PASS, and str.
UTHRegisterTests()
void UTHRegisterTests (void)
Definition at line 1158 of file util-unittest-helper.c.
References UtRegisterTest().
UTHRemoveSessionFromFlow()
int UTHRemoveSessionFromFlow (Flow * f)
Definition at line 570 of file util-unittest-helper.c.
References FAIL_IF_NOT, FAIL_IF_NULL, Flow_::proto, Flow_::protoctx, SCFree, and StreamTcpSessionCleanup().
UTHSetIPv4Address()
uint32_t UTHSetIPv4Address (const char * str)
return the uint32_t for a ipv4 address string
Parameters
str Valid ipaddress in string form (e.g. 1.2.3.4)
Return values
uint the uin32_t representation
Definition at line 133 of file util-unittest-helper.c.
References str.