suricata: /Users/jlu/suricata/src/util-file-swf-decompression.h File Reference
util-file-swf-decompression.h File Reference
Macros
#define MIN_SWF_LEN 2920
Functions
uint8_t FileGetSwfVersion (const uint8_t *buffer, const uint32_t buffer_len)
uint32_t FileGetSwfDecompressedLen (const uint8_t *buffer, uint32_t buffr_len)
int FileSwfZlibDecompression (DetectEngineThreadCtx *det_ctx, uint8_t *compressed_data, uint32_t compressed_data_len, uint8_t *decompressed_data, uint32_t decompressed_data_len)
int FileSwfLzmaDecompression (DetectEngineThreadCtx *det_ctx, uint8_t *compressed_data, uint32_t compressed_data_len, uint8_t *decompressed_data, uint32_t decompressed_data_len)
Detailed Description
Author
Giuseppe Longo giuse.nosp@m.ppe@.nosp@m.glong.nosp@m.o.it
Definition in file util-file-swf-decompression.h.
Macro Definition Documentation
MIN_SWF_LEN
#define MIN_SWF_LEN 2920
Definition at line 31 of file util-file-swf-decompression.h.
Function Documentation
FileGetSwfDecompressedLen()
uint32_t FileGetSwfDecompressedLen (const uint8_t * buffer, uint32_t buffr_len)
Definition at line 44 of file util-file-swf-decompression.c.
References len, MAX_SWF_DECOMPRESSED_LEN, and MIN.
Referenced by FileSwfDecompression().
FileGetSwfVersion()
uint8_t FileGetSwfVersion (const uint8_t * buffer, const uint32_t buffer_len)
Definition at line 69 of file util-file-swf-decompression.c.
Referenced by FileSwfDecompression().
FileSwfLzmaDecompression()
int FileSwfLzmaDecompression (DetectEngineThreadCtx * det_ctx, uint8_t * compressed_data, uint32_t compressed_data_len, uint8_t * decompressed_data, uint32_t decompressed_data_len)
Definition at line 141 of file util-file-swf-decompression.c.
References DetectEngineSetEvent(), and FILE_DECODER_EVENT_LZMA_FORMAT_ERROR.
Referenced by FileSwfDecompression().
FileSwfZlibDecompression()
int FileSwfZlibDecompression (DetectEngineThreadCtx * det_ctx, uint8_t * compressed_data, uint32_t compressed_data_len, uint8_t * decompressed_data, uint32_t decompressed_data_len)
Definition at line 82 of file util-file-swf-decompression.c.
References DetectEngineSetEvent(), FILE_DECODER_EVENT_Z_BUF_ERROR, FILE_DECODER_EVENT_Z_DATA_ERROR, FILE_DECODER_EVENT_Z_STREAM_ERROR, and FILE_DECODER_EVENT_Z_UNKNOWN_ERROR.
Referenced by FileSwfDecompression().