suricata: /Users/jlu/suricata/src/util-affinity.h File Reference
util-affinity.h File Reference
#include "suricata-common.h"
#include "conf.h"
Data Structures
struct ThreadsAffinityType_
Typedefs
typedef struct ThreadsAffinityType_ ThreadsAffinityType
Enumerations
enum {
RECEIVE_CPU_SET , WORKER_CPU_SET , VERDICT_CPU_SET , MANAGEMENT_CPU_SET ,
MAX_CPU_SET
}
enum { BALANCED_AFFINITY , EXCLUSIVE_AFFINITY , MAX_AFFINITY }
Functions
void AffinitySetupLoadFromConfig (void)
Extract cpu affinity configuration from current config file.
ThreadsAffinityType * GetAffinityTypeFromName (const char *name)
find affinity by its name
uint16_t AffinityGetNextCPU (ThreadsAffinityType *taf)
Return next cpu to use for a given thread family.
void BuildCpusetWithCallback (const char *name, ConfNode *node, void(*Callback)(int i, void *data), void *data)
Variables
ThreadsAffinityType thread_affinity [MAX_CPU_SET]
Detailed Description
Author
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Definition in file util-affinity.h.
Typedef Documentation
ThreadsAffinityType
typedef struct ThreadsAffinityType_ ThreadsAffinityType
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
RECEIVE_CPU_SET
WORKER_CPU_SET
VERDICT_CPU_SET
MANAGEMENT_CPU_SET
MAX_CPU_SET
Definition at line 50 of file util-affinity.h.
anonymous enum
anonymous enum
Enumerator
BALANCED_AFFINITY
EXCLUSIVE_AFFINITY
MAX_AFFINITY
Definition at line 58 of file util-affinity.h.
Function Documentation
AffinityGetNextCPU()
uint16_t AffinityGetNextCPU (ThreadsAffinityType * taf)
Return next cpu to use for a given thread family.
Return values
the cpu to used given by its id
Definition at line 297 of file util-affinity.c.
References ThreadsAffinityType_::cpu_set, ThreadsAffinityType_::lcpu, SC_ERR_INVALID_ARGUMENT, SCLogDebug, SCLogError, SCMutexLock, SCMutexUnlock, ThreadsAffinityType_::taf_mutex, and UtilCpuGetNumProcessorsOnline().
AffinitySetupLoadFromConfig()
void AffinitySetupLoadFromConfig (void)
Extract cpu affinity configuration from current config file.
Definition at line 180 of file util-affinity.c.
Referenced by RunModeInitialize().
BuildCpusetWithCallback()
void BuildCpusetWithCallback (const char * name, ConfNode * node, void(*)(int i, void *data) Callback, void * data)
Definition at line 99 of file util-affinity.c.
References next, SC_ERR_INVALID_ARGUMENT, SCLogError, TAILQ_FOREACH, UtilCpuGetNumProcessorsOnline(), and ConfNode_::val.
GetAffinityTypeFromName()
ThreadsAffinityType * GetAffinityTypeFromName (const char * name)
find affinity by its name
Return values
a pointer to the affinity or NULL if not found
Definition at line 69 of file util-affinity.c.
References MAX_CPU_SET, and thread_affinity.
Variable Documentation
thread_affinity
ThreadsAffinityType thread_affinity[MAX_CPU_SET] extern
store thread affinity mode for all type of threads
Definition at line 35 of file util-affinity.c.
Referenced by GetAffinityTypeFromName(), and TmThreadGetNbThreads().