suricata: /Users/jlu/suricata/src/util-path.c File Reference
util-path.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "util-debug.h"
#include "util-path.h"
Macros
#define DIRECTORY_SEPARATOR '/'
Functions
int PathIsAbsolute (const char *path)
Check if a path is absolute.
int PathIsRelative (const char *path)
Check if a path is relative.
TmEcode PathJoin (char *out_buf, uint16_t buf_len, const char *const dir, const char *const fname)
Wrapper to join a directory and filename and resolve using realpath _fullpath is used for WIN32.
int SCDefaultMkDir (const char *path)
Wrapper around SCMkDir with default mode arguments.
int SCCreateDirectoryTree (const char *path, const bool final)
Recursively create a directory.
bool SCPathExists (const char *path)
Check if a path exists.
bool SCIsRegularDirectory (const struct dirent *const dir_entry)
OS independent wrapper for directory check.
bool SCIsRegularFile (const struct dirent *const dir_entry)
OS independent to check for regular file.
char * SCRealPath (const char *path, char *resolved_path)
OS independent wrapper for realpath.
const char * SCBasename (const char *path)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file util-path.c.
Macro Definition Documentation
DIRECTORY_SEPARATOR
#define DIRECTORY_SEPARATOR '/'
Definition at line 33 of file util-path.c.
Function Documentation
PathIsAbsolute()
int PathIsAbsolute (const char * path)
Check if a path is absolute.
Parameters
path string with the path
Return values
1 absolute
0 not absolute
Definition at line 44 of file util-path.c.
Referenced by PathIsRelative().
PathIsRelative()
int PathIsRelative (const char * path)
Check if a path is relative.
Parameters
path string with the path
Return values
1 relative
0 not relative
Definition at line 69 of file util-path.c.
References PathIsAbsolute().
Referenced by ConfLoadCompleteIncludePath(), and DetectLoadCompleteSigPath().
PathJoin()
TmEcode PathJoin (char * out_buf, uint16_t buf_len, const char *const dir, const char *const fname)
Wrapper to join a directory and filename and resolve using realpath _fullpath is used for WIN32.
Parameters
out_buf output buffer. Up to PATH_MAX will be written. Unchanged on exit failure.
buf_len length of output buffer
dir the directory
fname the filename
Return values
TM_ECODE_OK on success
TM_ECODE_FAILED on failure
Definition at line 86 of file util-path.c.
References DIRECTORY_SEPARATOR, MAX, SC_ERR_SPRINTF, SCEnter, SCLogError, SCRealPath(), SCReturnInt, strlcpy(), TM_ECODE_FAILED, and TM_ECODE_OK.
SCBasename()
const char * SCBasename (const char * path)
Definition at line 235 of file util-path.c.
References DIRECTORY_SEPARATOR.
SCCreateDirectoryTree()
int SCCreateDirectoryTree (const char * path, const bool final)
Recursively create a directory.
Parameters
path Path to create
final true will create the final path component, false will not
Return values
0 on success
-1 on error
Definition at line 123 of file util-path.c.
References len, SCDefaultMkDir(), and strlcpy().
SCDefaultMkDir()
int SCDefaultMkDir (const char * path)
Wrapper around SCMkDir with default mode arguments.
Definition at line 109 of file util-path.c.
References SCMkDir.
Referenced by SCCreateDirectoryTree().
SCIsRegularDirectory()
bool SCIsRegularDirectory (const struct dirent *const dir_entry)
OS independent wrapper for directory check.
Parameters
dir_entry object to check
Return values
True if the object is a regular directory, otherwise false. This directory and parent directory will return false.
Definition at line 186 of file util-path.c.
SCIsRegularFile()
bool SCIsRegularFile (const struct dirent *const dir_entry)
OS independent to check for regular file.
Parameters
dir_entry object to check
Return values
True if the object is a regular file. Otherwise false.
Definition at line 204 of file util-path.c.
SCPathExists()
bool SCPathExists (const char * path)
Check if a path exists.
Parameters
Path to check for existence
Return values
true if path exists
false if path does not exist
Definition at line 169 of file util-path.c.
SCRealPath()
char * SCRealPath (const char * path, char * resolved_path)
OS independent wrapper for realpath.
Parameters
path the path to resolve
resolved_path the resolved path; if null, a buffer will be allocated
Return values
the resolved_path; or a pointer to a new resolved_path buffer
Definition at line 220 of file util-path.c.
Referenced by PathJoin().