suricata: /Users/jlu/suricata/src/util-strlcpyu.c File Reference
util-strlcpyu.c File Reference
#include "suricata-common.h"
Functions
size_t strlcpy (char *dst, const char *src, size_t siz)
Function Documentation
strlcpy()
size_t strlcpy (char * dst, const char * src, size_t siz)
Definition at line 43 of file util-strlcpyu.c.
References dst, and src.
Referenced by BytesToStringBuffer(), ConfigSetDataDirectory(), ConfLoadCompleteIncludePath(), DetectAppLayerMpmRegisterByParentId(), DetectContentDataParse(), DetectEngineBufferTypeGetByIdTransforms(), DetectLoadCompleteSigPath(), GetIfaceMTU(), GetIfaceRSSQueuesNum(), JsonAddrInfoInit(), JsonBuildFileInfoRecord(), LogCustomFormatParse(), LogTcpDataLogInitCtx(), PathJoin(), PcapTranslateIPToDevice(), PortParse(), SCCreateDirectoryTree(), SCRadixAddKeyIPV4String(), SCRadixAddKeyIPV6String(), SCStrndupFunc(), SCTimeToStringPattern(), StringAsBase64(), TmThreadCreate(), and TmThreadWaitOnThreadInit().