suricata: /Users/jlu/suricata/src/util-logopenfile.c File Reference
util-logopenfile.c File Reference
#include "suricata-common.h"
#include "util-logopenfile.h"
#include "suricata.h"
#include "conf.h"
#include "output.h"
#include "util-byte.h"
#include "util-time.h"
Macros
#define LOGFILE_NAME_MAX 255
Functions
bool SCLogOpenThreadedFile (const char *log_path, const char *append, LogFileCtx *parent_ctx, int slot_count)
int SCConfLogOpenGeneric (ConfNode *conf, LogFileCtx *log_ctx, const char *default_filename, int rotate)
open a generic output "log file", which may be a regular file or a socket
int SCConfLogReopen (LogFileCtx *log_ctx)
Reopen a regular log file with the side-affect of truncating it.
LogFileCtx * LogFileNewCtx (void)
LogFileNewCtx() Get a new LogFileCtx.
LogFileCtx * LogFileEnsureExists (LogFileCtx *parent_ctx, int thread_id)
LogFileEnsureExists() Ensure a log file context for the thread exists.
int LogFileFreeCtx (LogFileCtx *lf_ctx)
LogFileFreeCtx() Destroy a LogFileCtx (Close the file and free memory)
int LogFileWrite (LogFileCtx *file_ctx, MemBuffer *buffer)
Detailed Description
Author
Mike Pomraning mpomr.nosp@m.anin.nosp@m.g@qua.nosp@m.lys..nosp@m.com
File-like output for logging: regular files and sockets.
Definition in file util-logopenfile.c.
Macro Definition Documentation
LOGFILE_NAME_MAX
#define LOGFILE_NAME_MAX 255
Definition at line 46 of file util-logopenfile.c.
Function Documentation
LogFileEnsureExists()
LogFileCtx * LogFileEnsureExists (LogFileCtx * parent_ctx, int thread_id)
LogFileEnsureExists() Ensure a log file context for the thread exists.
Parameters
parent_ctx
thread_id
Return values
LogFileCtx * pointer if successful; NULL otherwise
Definition at line 662 of file util-logopenfile.c.
References LogThreadedFileCtx_::lf_slots, LogThreadedFileCtx_::mutex, SCLogDebug, SCMutexLock, LogFileCtx_::threaded, and LogFileCtx_::threads.
Referenced by CreateEveThreadCtx(), and JsonLogThreadInit().
LogFileFreeCtx()
int LogFileFreeCtx (LogFileCtx * lf_ctx)
LogFileFreeCtx() Destroy a LogFileCtx (Close the file and free memory)
Parameters
lf_ctx pointer to the OutputCtx
Return values
int 1 if successful, 0 if error
Definition at line 828 of file util-logopenfile.c.
References LogThreadedFileCtx_::append, BUG_ON, LogFileCtx_::Close, SCEveFileType_::Deinit, LogFileCtx_::filename, LogFileCtx_::fp, LogFileCtx_::fp_mutex, LogFileCtx_::id, LogFilePluginCtx_::init_data, LogThreadedFileCtx_::lf_slots, LOGFILE_TYPE_PLUGIN, LogThreadedFileCtx_::mutex, OutputUnregisterFileRotationFlag(), LogFileCtx_::parent, LogFilePluginCtx_::plugin, LogFileCtx_::plugin, LogFileCtx_::prefix, LogFileCtx_::prefix_len, LogFileCtx_::rotation_flag, SCFree, SCMutexDestroy, SCMutexLock, SCMutexUnlock, SCReturnInt, LogFileCtx_::sensor_name, LogThreadedFileCtx_::slot_count, LogFilePluginCtx_::thread_data, SCEveFileType_::ThreadDeinit, LogFileCtx_::threaded, LogFileCtx_::threads, and LogFileCtx_::type.
Referenced by AlertFastLogInitCtx(), LogHttpLogInitCtx(), and LogTcpDataLogInitCtx().
LogFileNewCtx()
LogFileCtx * LogFileNewCtx (void)
LogFileNewCtx() Get a new LogFileCtx.
Return values
LogFileCtx * pointer if successful, NULL if error
Definition at line 643 of file util-logopenfile.c.
References SCCalloc, and LogFileCtx_::Write.
Referenced by AlertFastLogInitCtx(), LogHttpLogInitCtx(), LogTcpDataLogInitCtx(), and OutputJsonInitCtx().
LogFileWrite()
int LogFileWrite (LogFileCtx * file_ctx, MemBuffer * buffer)
Definition at line 896 of file util-logopenfile.c.
References LogFileCtx_::fp_mutex, LogFilePluginCtx_::init_data, LOGFILE_TYPE_FILE, LOGFILE_TYPE_PLUGIN, LOGFILE_TYPE_REDIS, LOGFILE_TYPE_UNIX_DGRAM, LOGFILE_TYPE_UNIX_STREAM, MEMBUFFER_BUFFER, MEMBUFFER_OFFSET, MemBufferWriteString, LogFilePluginCtx_::plugin, LogFileCtx_::plugin, SCMutexLock, SCMutexUnlock, LogFilePluginCtx_::thread_data, LogFileCtx_::type, LogFileCtx_::Write, and SCEveFileType_::Write.
Referenced by OutputJSONBuffer(), and OutputJsonBuilderBuffer().
SCConfLogOpenGeneric()
int SCConfLogOpenGeneric (ConfNode * conf, LogFileCtx * log_ctx, const char * default_filename, int rotate)
open a generic output "log file", which may be a regular file or a socket
Parameters
conf ConfNode structure for the output section in question
log_ctx Log file context allocated by caller
default_filename Default name of file to open, if not specified in ConfNode
rotate Register the file for rotation in HUP.
Return values
0 on success
-1 on error
Definition at line 431 of file util-logopenfile.c.
Referenced by AlertFastLogInitCtx(), LogHttpLogInitCtx(), and LogTcpDataLogInitCtx().
SCConfLogReopen()
int SCConfLogReopen (LogFileCtx * log_ctx)
Reopen a regular log file with the side-affect of truncating it.
This is useful to clear the log file and start a new one, or to re-open the file after its been moved by something external (eg. logrotate).
Definition at line 612 of file util-logopenfile.c.
References LogFileCtx_::filename, LogFileCtx_::fp, LogFileCtx_::is_regular, SC_ERR_INVALID_ARGUMENT, SCLogDebug, and SCLogWarning.
SCLogOpenThreadedFile()
bool SCLogOpenThreadedFile (const char * log_path, const char * append, LogFileCtx * parent_ctx, int slot_count)
Definition at line 327 of file util-logopenfile.c.