suricata: /Users/jlu/suricata/src/util-thash.h File Reference
util-thash.h File Reference
Data Structures
struct THashData_
struct THashHashRow_
struct THashDataQueue_
struct THashDataConfig_
struct THashTableContext_
struct THashDataGetResult
Macros
#define HRLOCK_MUTEX
#define HRLOCK_TYPE SCMutex
#define HRLOCK_INIT(fb) SCMutexInit(&(fb)->lock, NULL)
#define HRLOCK_DESTROY(fb) SCMutexDestroy(&(fb)->lock)
#define HRLOCK_LOCK(fb) SCMutexLock(&(fb)->lock)
#define HRLOCK_TRYLOCK(fb) SCMutexTrylock(&(fb)->lock)
#define HRLOCK_UNLOCK(fb) SCMutexUnlock(&(fb)->lock)
#define HQLOCK_MUTEX
#define HQLOCK_INIT(q) SCMutexInit(&(q)->m, NULL)
#define HQLOCK_DESTROY(q) SCMutexDestroy(&(q)->m)
#define HQLOCK_LOCK(q) SCMutexLock(&(q)->m)
#define HQLOCK_TRYLOCK(q) SCMutexTrylock(&(q)->m)
#define HQLOCK_UNLOCK(q) SCMutexUnlock(&(q)->m)
#define THASH_VERBOSE 0
#define THASH_QUIET 1
#define THASH_DATA_SIZE(ctx) (sizeof(THashData) + (ctx)->config.data_size)
#define THASH_CHECK_MEMCAP(ctx, size) ((((uint64_t)SC_ATOMIC_GET((ctx)->memuse) + (uint64_t)(size)) <= (ctx)->config.memcap))
check if a memory alloc would fit in the memcap
#define THashIncrUsecnt(h) (void)SC_ATOMIC_ADD((h)->use_cnt, 1)
#define THashDecrUsecnt(h) (void)SC_ATOMIC_SUB((h)->use_cnt, 1)
#define THashReference(dst_h_ptr, h)
#define THashDeReference(src_h_ptr)
Typedefs
typedef struct THashData_ THashData
typedef struct THashDataQueue_ THashDataQueue
typedef int(* THashOutputFunc) (void *output_ctx, const uint8_t *data, const uint32_t data_len)
typedef int(* THashFormatFunc) (const void *in_data, char *output, size_t output_size)
typedef struct THashDataConfig_ THashConfig
typedef struct THashTableContext_ THashTableContext
Functions
struct THashHashRow_ __attribute__ ((aligned(CLS))) THashHashRow
THashTableContext * THashInit (const char *cnf_prefix, size_t data_size, int(*DataSet)(void *dst, void *src), void(*DataFree)(void *), uint32_t(*DataHash)(void *), bool(*DataCompare)(void *, void *), bool reset_memcap, uint64_t memcap, uint32_t hashsize)
void THashShutdown (THashTableContext *ctx)
shutdown the flow engine
struct THashDataGetResult THashGetFromHash (THashTableContext *ctx, void *data)
THashData * THashLookupFromHash (THashTableContext *ctx, void *data)
look up data in the hash
THashDataQueue * THashDataQueueNew (void)
void THashCleanup (THashTableContext *ctx)
Cleanup the thash engine.
int THashWalk (THashTableContext *, THashFormatFunc, THashOutputFunc, void *)
Walk the hash.
int THashRemoveFromHash (THashTableContext *ctx, void *data)
void THashConsolidateMemcap (THashTableContext *ctx)
void THashDataMoveToSpare (THashTableContext *ctx, THashData *h)
Variables
HRLOCK_TYPE lock
THashData * head
THashData * tail
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
thash -> thread hash. Hash table with locking handling.
Definition in file util-thash.h.
Macro Definition Documentation
HQLOCK_DESTROY
#define HQLOCK_DESTROY (q) SCMutexDestroy(&(q)->m)
Definition at line 76 of file util-thash.h.
HQLOCK_INIT
#define HQLOCK_INIT (q) SCMutexInit(&(q)->m, NULL)
Definition at line 75 of file util-thash.h.
HQLOCK_LOCK
#define HQLOCK_LOCK (q) SCMutexLock(&(q)->m)
Definition at line 77 of file util-thash.h.
HQLOCK_MUTEX
#define HQLOCK_MUTEX
Spinlocks or Mutex for the queues.
Definition at line 60 of file util-thash.h.
HQLOCK_TRYLOCK
#define HQLOCK_TRYLOCK (q) SCMutexTrylock(&(q)->m)
Definition at line 78 of file util-thash.h.
HQLOCK_UNLOCK
#define HQLOCK_UNLOCK (q) SCMutexUnlock(&(q)->m)
Definition at line 79 of file util-thash.h.
HRLOCK_DESTROY
#define HRLOCK_DESTROY (fb) SCMutexDestroy(&(fb)->lock)
Definition at line 50 of file util-thash.h.
HRLOCK_INIT
#define HRLOCK_INIT (fb) SCMutexInit(&(fb)->lock, NULL)
Definition at line 49 of file util-thash.h.
HRLOCK_LOCK
#define HRLOCK_LOCK (fb) SCMutexLock(&(fb)->lock)
Definition at line 51 of file util-thash.h.
HRLOCK_MUTEX
#define HRLOCK_MUTEX
Spinlocks or Mutex for the buckets.
Definition at line 32 of file util-thash.h.
HRLOCK_TRYLOCK
#define HRLOCK_TRYLOCK (fb) SCMutexTrylock(&(fb)->lock)
Definition at line 52 of file util-thash.h.
HRLOCK_TYPE
#define HRLOCK_TYPE SCMutex
Definition at line 48 of file util-thash.h.
HRLOCK_UNLOCK
#define HRLOCK_UNLOCK (fb) SCMutexUnlock(&(fb)->lock)
Definition at line 53 of file util-thash.h.
THASH_CHECK_MEMCAP
#define THASH_CHECK_MEMCAP (ctx, size) ((((uint64_t)SC_ATOMIC_GET((ctx)->memuse) + (uint64_t)(size)) <= (ctx)->config.memcap))
check if a memory alloc would fit in the memcap
Parameters
size memory allocation size to check
Return values
1 it fits
0 no fit
Definition at line 164 of file util-thash.h.
THASH_DATA_SIZE
#define THASH_DATA_SIZE (ctx) (sizeof(THashData) + (ctx)->config.data_size)
Definition at line 139 of file util-thash.h.
THASH_QUIET
#define THASH_QUIET 1
Definition at line 121 of file util-thash.h.
THASH_VERBOSE
#define THASH_VERBOSE 0
Definition at line 120 of file util-thash.h.
THashDecrUsecnt
#define THashDecrUsecnt (h) (void)SC_ATOMIC_SUB((h)->use_cnt, 1)
Definition at line 169 of file util-thash.h.
THashDeReference
#define THashDeReference (src_h_ptr)
Value:
        do {               \
        if (*(src_h_ptr) != NULL) {                   \
            THashDecrUsecnt(*(src_h_ptr));             \
            *(src_h_ptr) = NULL;                      \
        }                                             \
    } while (0)
Definition at line 179 of file util-thash.h.
THashIncrUsecnt
#define THashIncrUsecnt (h) (void)SC_ATOMIC_ADD((h)->use_cnt, 1)
Definition at line 167 of file util-thash.h.
THashReference
#define THashReference (dst_h_ptr, h)
Value:
        do {            \
        if ((h) != NULL) {                          \
            THashIncrUsecnt((h));                    \
            *(dst_h_ptr) = h;                       \
        }                                           \
    } while (0)
Definition at line 172 of file util-thash.h.
Typedef Documentation
THashConfig
typedef struct THashDataConfig_ THashConfig
THashData
typedef struct THashData_ THashData
THashDataQueue
typedef struct THashDataQueue_ THashDataQueue
THashFormatFunc
typedef int(* THashFormatFunc) (const void *in_data, char *output, size_t output_size)
Definition at line 124 of file util-thash.h.
THashOutputFunc
typedef int(* THashOutputFunc) (void *output_ctx, const uint8_t *data, const uint32_t data_len)
Definition at line 123 of file util-thash.h.
THashTableContext
typedef struct THashTableContext_ THashTableContext
Function Documentation
__attribute__()
struct THashHashRow_ __attribute__ ((aligned(CLS)))
THashCleanup()
void THashCleanup (THashTableContext * ctx)
Cleanup the thash engine.
Cleanup the thash engine from tag and threshold.
Definition at line 415 of file util-thash.c.
References THashTableContext_::array, THashTableContext_::config, THashDataConfig_::hash_size, HRLOCK_LOCK, HRLOCK_UNLOCK, THashData_::next, THashData_::prev, SC_ATOMIC_GET, and THashDataMoveToSpare().
THashConsolidateMemcap()
void THashConsolidateMemcap (THashTableContext * ctx)
Definition at line 338 of file util-thash.c.
References THashTableContext_::config, MAX, THashDataConfig_::memcap, SC_ATOMIC_GET, and SCLogDebug.
THashDataMoveToSpare()
void THashDataMoveToSpare (THashTableContext * ctx, THashData * h)
Definition at line 41 of file util-thash.c.
Referenced by THashCleanup().
THashDataQueueNew()
THashDataQueue * THashDataQueueNew (void)
Definition at line 56 of file util-thash.c.
References SC_ERR_FATAL, SCLogError, and SCMalloc.
THashGetFromHash()
struct THashDataGetResult THashGetFromHash (THashTableContext * ctx, void * data)
Definition at line 529 of file util-thash.c.
References res.
THashInit()
THashTableContext * THashInit (const char * cnf_prefix, size_t data_size, int(*)(void *dst, void *src) DataSet, void(*)(void *) DataFree, uint32_t(*)(void *) DataHash, bool(*)(void *, void *) DataCompare, bool reset_memcap, uint64_t memcap, uint32_t hashsize)
THashLookupFromHash()
THashData * THashLookupFromHash (THashTableContext * ctx, void * data)
look up data in the hash
Parameters
data data to look up
Return values
h LOCKED data or NULL
Definition at line 639 of file util-thash.c.
THashRemoveFromHash()
int THashRemoveFromHash (THashTableContext * ctx, void * data)
Return values
int -1 not found
int 0 found, but it was busy (ref cnt)
int 1 found and removed
Definition at line 774 of file util-thash.c.
THashShutdown()
void THashShutdown (THashTableContext * ctx)
shutdown the flow engine
Warning
Not thread safe
Definition at line 346 of file util-thash.c.
Referenced by HttpRangeContainersDestroy().
THashWalk()
int THashWalk (THashTableContext * ctx, THashFormatFunc FormatterFunc, THashOutputFunc OutputterFunc, void * output_ctx)
Walk the hash.
Definition at line 380 of file util-thash.c.
References THashTableContext_::array, THashTableContext_::config, THashData_::data, THashDataConfig_::hash_size, HRLOCK_LOCK, HRLOCK_UNLOCK, and THashData_::next.
Variable Documentation
head
THashData* head
Definition at line 1 of file util-thash.h.
lock
HRLOCK_TYPE lock
Definition at line 0 of file util-thash.h.
tail
THashData* tail
Definition at line 2 of file util-thash.h.