suricata: /Users/jlu/suricata/src/util-macset.h File Reference
util-macset.h File Reference
Typedefs
typedef struct MacSet_ MacSet
typedef int(* MacSetIteratorFunc) (uint8_t *addr, MacSetSide side, void *)
Enumerations
enum MacSetSide { MAC_SET_SRC = 0 , MAC_SET_DST }
Functions
MacSet * MacSetInit (int size)
void MacSetAdd (MacSet *, uint8_t *src_addr, uint8_t *dst_addr)
void MacSetAddWithCtr (MacSet *, uint8_t *src_addr, uint8_t *dst_addr, ThreadVars *tv, uint16_t ctr_src, uint16_t ctr_dst)
int MacSetForEach (const MacSet *, MacSetIteratorFunc, void *)
int MacSetSize (const MacSet *)
void MacSetReset (MacSet *)
void MacSetFree (MacSet *)
void MacSetRegisterFlowStorage (void)
FlowStorageId MacSetGetFlowStorageID (void)
bool MacSetFlowStorageEnabled (void)
void MacSetRegisterTests (void)
Detailed Description
Author
Sascha Steinbiss sasch.nosp@m.a.st.nosp@m.einbi.nosp@m.ss@d.nosp@m.cso.d.nosp@m.e
Definition in file util-macset.h.
Typedef Documentation
MacSet
typedef struct MacSet_ MacSet
Definition at line 27 of file util-macset.h.
MacSetIteratorFunc
typedef int(* MacSetIteratorFunc) (uint8_t *addr, MacSetSide side, void *)
Definition at line 33 of file util-macset.h.
Enumeration Type Documentation
MacSetSide
enum MacSetSide
Enumerator
MAC_SET_SRC
MAC_SET_DST
Definition at line 28 of file util-macset.h.
Function Documentation
MacSetAdd()
void MacSetAdd (MacSet * ms, uint8_t * src_addr, uint8_t * dst_addr)
Definition at line 188 of file util-macset.c.
References MacSetAddWithCtr().
MacSetAddWithCtr()
void MacSetAddWithCtr (MacSet * ms, uint8_t * src_addr, uint8_t * dst_addr, ThreadVars * tv, uint16_t ctr_src, uint16_t ctr_dst)
Definition at line 179 of file util-macset.c.
Referenced by MacSetAdd().
MacSetFlowStorageEnabled()
bool MacSetFlowStorageEnabled (void)
Definition at line 84 of file util-macset.c.
References g_macset_storage_id, and FlowStorageId::id.
MacSetForEach()
int MacSetForEach (const MacSet * ms, MacSetIteratorFunc IterFunc, void * data)
Definition at line 218 of file util-macset.c.
Referenced by CreateJSONEther().
MacSetFree()
void MacSetFree (MacSet * ms)
Definition at line 270 of file util-macset.c.
References MacSet_::buf, MAC_SET_DST, MAC_SET_SRC, SC_ATOMIC_SUB, SCFree, and MacSet_::size.
MacSetGetFlowStorageID()
FlowStorageId MacSetGetFlowStorageID (void)
Definition at line 113 of file util-macset.c.
References g_macset_storage_id.
Referenced by CreateJSONEther().
MacSetInit()
MacSet * MacSetInit (int size)
Definition at line 90 of file util-macset.c.
References EMPTY_SET, FLOW_CHECK_MEMCAP, MacSet_::last, MAC_SET_DST, MAC_SET_SRC, SC_ATOMIC_ADD, SC_ERR_MEM_ALLOC, SCCalloc, SCLogError, MacSet_::size, MacSet_::state, and unlikely.
MacSetRegisterFlowStorage()
void MacSetRegisterFlowStorage (void)
Definition at line 61 of file util-macset.c.
Referenced by PostConfLoadedSetup().
MacSetRegisterTests()
void MacSetRegisterTests (void)
Definition at line 437 of file util-macset.c.
References UtRegisterTest().
MacSetReset()
void MacSetReset (MacSet * ms)
Definition at line 262 of file util-macset.c.
References EMPTY_SET, MacSet_::last, MAC_SET_DST, MAC_SET_SRC, and MacSet_::state.
MacSetSize()
int MacSetSize (const MacSet * ms)
Definition at line 231 of file util-macset.c.
References EMPTY_SET, MacSet_::last, MAC_SET_DST, MAC_SET_SRC, MULTI_MAC, SINGLE_MAC, and MacSet_::state.
Referenced by CreateJSONEther().