suricata: /Users/jlu/suricata/src/util-mpm-ac-ks.h File Reference
util-mpm-ac-ks.h File Reference
Data Structures
struct SCACTilePatternList_
struct SCACTileOutputTable_
struct SCACTileCtx_
struct SCACTileSearchCtx_
struct SCACTileThreadCtx_
Typedefs
typedef struct SCACTilePatternList_ SCACTilePatternList
typedef struct SCACTileOutputTable_ SCACTileOutputTable
typedef struct SCACTileCtx_ SCACTileCtx
typedef struct SCACTileSearchCtx_ SCACTileSearchCtx
typedef struct SCACTileThreadCtx_ SCACTileThreadCtx
Functions
void MpmACTileRegister (void)
Register the aho-corasick mpm 'ks' originally developed by Ken Steele for Tilera Tile-Gx processor.
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Ken Steele suric.nosp@m.ata@.nosp@m.tiler.nosp@m.a.co.nosp@m.m
Definition in file util-mpm-ac-ks.h.
Typedef Documentation
SCACTileCtx
typedef struct SCACTileCtx_ SCACTileCtx
SCACTileOutputTable
typedef struct SCACTileOutputTable_ SCACTileOutputTable
SCACTilePatternList
typedef struct SCACTilePatternList_ SCACTilePatternList
SCACTileSearchCtx
typedef struct SCACTileSearchCtx_ SCACTileSearchCtx
SCACTileThreadCtx
typedef struct SCACTileThreadCtx_ SCACTileThreadCtx
Function Documentation
MpmACTileRegister()
void MpmACTileRegister (void)
Register the aho-corasick mpm 'ks' originally developed by Ken Steele for Tilera Tile-Gx processor.
Definition at line 1463 of file util-mpm-ac-ks.c.
References MpmTableElmt_::AddPattern, MpmTableElmt_::AddPatternNocase, MpmTableElmt_::DestroyCtx, MpmTableElmt_::DestroyThreadCtx, MpmTableElmt_::InitCtx, MpmTableElmt_::InitThreadCtx, MPM_AC_KS, mpm_table, MpmTableElmt_::name, MpmTableElmt_::Prepare, MpmTableElmt_::PrintCtx, MpmTableElmt_::PrintThreadCtx, MpmTableElmt_::RegisterUnittests, SCACTileAddPatternCI(), SCACTileAddPatternCS(), SCACTileDestroyCtx(), SCACTileDestroyThreadCtx(), SCACTileInitCtx(), SCACTileInitThreadCtx(), SCACTilePreparePatterns(), SCACTilePrintInfo(), SCACTilePrintSearchStats(), SCACTileRegisterTests(), SCACTileSearch(), and MpmTableElmt_::Search.
Referenced by MpmTableSetup().