suricata: /Users/jlu/suricata/src/util-spm-bs2bm.c File Reference
util-spm-bs2bm.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "util-spm-bs2bm.h"
Functions
void Bs2BmBadchars (const uint8_t *needle, uint16_t needle_len, uint8_t *badchars)
Array setup function for Bs2Bm of bad characters index (not found at the needle)
void Bs2BmBadcharsNocase (const uint8_t *needle, uint16_t needle_len, uint8_t *badchars)
Array setup function for Bs2BmNocase of bad characters index (not found at the needle)
uint8_t * Bs2Bm (const uint8_t *haystack, uint32_t haystack_len, const uint8_t *needle, uint16_t needle_len, const uint8_t badchars[])
Basic search with a bad characters array. The array badchars contains flags at character's ascii index that can't be inside the needle. So the skips can be faster.
uint8_t * Bs2BmNocase (const uint8_t *haystack, uint32_t haystack_len, const uint8_t *needle, uint16_t needle_len, const uint8_t badchars[])
Basic search case less with a bad characters array. The array badchars contains flags at character's ascii index that can't be inside the needle. So the skips can be faster.
Detailed Description
Author
Pablo Rincon Crespo pablo.nosp@m..rin.nosp@m.con.c.nosp@m.resp.nosp@m.o@gma.nosp@m.il.c.nosp@m.om
Bs2Bm use a simple context array to determine the charactes that are not present on the pattern. This way on partial matches broken by a char not present, we can skip to the next character making less checks
Definition in file util-spm-bs2bm.c.
Function Documentation
Bs2Bm()
uint8_t * Bs2Bm (const uint8_t * haystack, uint32_t haystack_len, const uint8_t * needle, uint16_t needle_len, const uint8_t badchars[])
Basic search with a bad characters array. The array badchars contains flags at character's ascii index that can't be inside the needle. So the skips can be faster.
Parameters
haystack pointer to the buffer to search in
haystack_len length limit of the buffer
neddle pointer to the pattern we ar searching for
needle_len length limit of the needle
badchars pointer to an array of bachars prepared by Bs2BmBadchars()
Return values
ptr to start of the match; NULL if no match
Definition at line 93 of file util-spm-bs2bm.c.
Referenced by Bs2bmSearch().
Bs2BmBadchars()
void Bs2BmBadchars (const uint8_t * needle, uint16_t needle_len, uint8_t * badchars)
Array setup function for Bs2Bm of bad characters index (not found at the needle)
Parameters
neddle pointer to the pattern we ar searching for
needle_len length limit of the needle
badchars pointer to an empty array of bachars. The array prepared contains characters that can't be inside the needle_len. So the skips can be faster
Definition at line 43 of file util-spm-bs2bm.c.
References ALPHABET_SIZE.
Referenced by Bs2bmNocaseSearch(), and Bs2bmSearch().
Bs2BmBadcharsNocase()
void Bs2BmBadcharsNocase (const uint8_t * needle, uint16_t needle_len, uint8_t * badchars)
Array setup function for Bs2BmNocase of bad characters index (not found at the needle)
Parameters
neddle pointer to the pattern we ar searching for
needle_len length limit of the needle
badchars pointer to an empty array of bachars. The array prepared contains characters that can't be inside the needle_len. So the skips can be faster
Definition at line 65 of file util-spm-bs2bm.c.
References ALPHABET_SIZE, and u8_tolower.
Bs2BmNocase()
uint8_t * Bs2BmNocase (const uint8_t * haystack, uint32_t haystack_len, const uint8_t * needle, uint16_t needle_len, const uint8_t badchars[])
Basic search case less with a bad characters array. The array badchars contains flags at character's ascii index that can't be inside the needle. So the skips can be faster.
Parameters
haystack pointer to the buffer to search in
haystack_len length limit of the buffer
neddle pointer to the pattern we ar searching for
needle_len length limit of the needle
badchars pointer to an array of bachars prepared by Bs2BmBadchars()
Return values
ptr to start of the match; NULL if no match
Definition at line 143 of file util-spm-bs2bm.c.
References u8_tolower.
Referenced by Bs2bmNocaseSearch().