suricata: /Users/jlu/suricata/src/util-time.c File Reference
util-time.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "detect.h"
#include "threads.h"
#include "tm-threads.h"
#include "util-debug.h"
#include "util-time.h"
Macros
#define MONTHSPERYEAR 12
Functions
struct tm * SCLocalTime (time_t timep, struct tm *result)
struct tm * SCUtcTime (time_t timep, struct tm *result)
void TimeInit (void)
void TimeDeinit (void)
bool TimeModeIsReady (void)
void TimeModeSetLive (void)
void TimeModeSetOffline (void)
bool TimeModeIsLive (void)
void TimeSetByThread (const int thread_id, const struct timeval *tv)
void TimeSet (struct timeval *tv)
void TimeSetToCurrentTime (void)
set the time to "gettimeofday" meant for testing
void TimeGet (struct timeval *tv)
void TimeSetIncrementTime (uint32_t tv_sec)
increment the time in the engine
void CreateIsoTimeString (const struct timeval *ts, char *str, size_t size)
void CreateUtcIsoTimeString (const struct timeval *ts, char *str, size_t size)
void CreateFormattedTimeString (const struct tm *t, const char *fmt, char *str, size_t size)
void CreateTimeString (const struct timeval *ts, char *str, size_t size)
time_t SCMkTimeUtc (struct tm *tp)
Convert broken-down time to seconds since Unix epoch.
int SCStringPatternToTime (char *string, const char **patterns, int num_patterns, struct tm *tp)
Parse a date string based on specified patterns.
int SCTimeToStringPattern (time_t epoch, const char *pattern, char *str, size_t size)
Convert epoch time to string pattern.
uint64_t SCParseTimeSizeString (const char *str)
Parse string containing time size (1m, 1h, etc).
uint64_t SCGetSecondsUntil (const char *str, time_t epoch)
Get seconds until a time unit changes.
uint64_t SCTimespecAsEpochMillis (const struct timespec *ts)
uint64_t TimeDifferenceMicros (struct timeval t0, struct timeval t1)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Ken Steele suric.nosp@m.ata@.nosp@m.tiler.nosp@m.a.co.nosp@m.m
Time keeping for offline (non-live) packet handling (pcap files). And time string generation for alerts.
Definition in file util-time.c.
Macro Definition Documentation
MONTHSPERYEAR
#define MONTHSPERYEAR 12
Function Documentation
CreateFormattedTimeString()
void CreateFormattedTimeString (const struct tm * t, const char * fmt, char * str, size_t size)
Definition at line 252 of file util-time.c.
References likely, and str.
Referenced by LogCustomFormatWriteTimestamp().
CreateIsoTimeString()
void CreateIsoTimeString (const struct timeval * ts, char * str, size_t size)
Definition at line 215 of file util-time.c.
References likely, SCLocalTime(), str, and ts.
Referenced by CreateEveHeader(), and EveAddFlow().
CreateTimeString()
void CreateTimeString (const struct timeval * ts, char * str, size_t size)
Definition at line 278 of file util-time.c.
References likely, SCLocalTime(), str, and ts.
Referenced by AlertFastLogger().
CreateUtcIsoTimeString()
void CreateUtcIsoTimeString (const struct timeval * ts, char * str, size_t size)
Definition at line 236 of file util-time.c.
References likely, SCUtcTime(), str, and ts.
SCGetSecondsUntil()
uint64_t SCGetSecondsUntil (const char * str, time_t epoch)
Get seconds until a time unit changes.
Parameters
str String containing time type (minute, hour, etc).
epoch Epoch time.
Return values
seconds.
Definition at line 630 of file util-time.c.
References SCLocalTime(), and str.
SCLocalTime()
struct tm * SCLocalTime (time_t timep, struct tm * result)
Definition at line 273 of file util-time.c.
Referenced by CreateIsoTimeString(), CreateTimeString(), LogCustomFormatWriteTimestamp(), SCGetSecondsUntil(), and SCTimeToStringPattern().
SCMkTimeUtc()
time_t SCMkTimeUtc (struct tm * tp)
Convert broken-down time to seconds since Unix epoch.
This function is based on: http://www.catb.org/esr/time-programming (released to the public domain).
Parameters
tp Pointer to broken-down time.
Return values
Seconds since Unix epoch.
Definition at line 451 of file util-time.c.
References MONTHSPERYEAR.
SCParseTimeSizeString()
uint64_t SCParseTimeSizeString (const char * str)
Parse string containing time size (1m, 1h, etc).
Parameters
str String to parse.
Return values
size on success.
0 on failure.
Definition at line 579 of file util-time.c.
References str.
SCStringPatternToTime()
int SCStringPatternToTime (char * string, const char ** patterns, int num_patterns, struct tm * tp)
Parse a date string based on specified patterns.
This function is based on GNU C library getdate.
Parameters
string Date string to parse.
patterns String array containing patterns.
num_patterns Number of patterns to check.
tp Pointer to broken-down time.
Return values
0 on success.
1 on failure.
Definition at line 494 of file util-time.c.
References strptime().
SCTimespecAsEpochMillis()
uint64_t SCTimespecAsEpochMillis (const struct timespec * ts)
Definition at line 648 of file util-time.c.
References ts.
SCTimeToStringPattern()
int SCTimeToStringPattern (time_t epoch, const char * pattern, char * str, size_t size)
Convert epoch time to string pattern.
This function converts epoch time to a string based on a pattern.
Parameters
epoch Epoch time.
pattern String pattern.
str Formated string.
size Size of allocated string.
Return values
0 on success.
1 on failure.
Definition at line 550 of file util-time.c.
References SCLocalTime(), str, strlcpy(), and unlikely.
SCUtcTime()
struct tm * SCUtcTime (time_t timep, struct tm * result)
Definition at line 261 of file util-time.c.
Referenced by CreateUtcIsoTimeString().
TimeDeinit()
void TimeDeinit (void)
Definition at line 87 of file util-time.c.
References SCSpinDestroy.
TimeDifferenceMicros()
uint64_t TimeDifferenceMicros (struct timeval t0, struct timeval t1)
Definition at line 653 of file util-time.c.
TimeGet()
void TimeGet (struct timeval * tv)
Definition at line 155 of file util-time.c.
References tv.
Referenced by TimeSetIncrementTime(), UTHBuildPacketIPV6Real(), and UTHBuildPacketReal().
TimeInit()
void TimeInit (void)
Definition at line 79 of file util-time.c.
References SCSpinInit.
Referenced by GlobalsInitPreConfig().
TimeModeIsLive()
bool TimeModeIsLive (void)
Definition at line 111 of file util-time.c.
TimeModeIsReady()
bool TimeModeIsReady (void)
Definition at line 92 of file util-time.c.
TimeModeSetLive()
void TimeModeSetLive (void)
Definition at line 99 of file util-time.c.
Referenced by RunModeIdsAFPAutoFp(), RunModeIdsAFPSingle(), RunModeIdsAFPWorkers(), RunModeIdsDpdkWorkers(), RunModeIdsErfDagAutoFp(), RunModeIdsErfDagSingle(), RunModeIdsErfDagWorkers(), RunModeIdsPcapAutoFp(), RunModeIdsPcapSingle(), RunModeIdsPcapWorkers(), RunModeIdsPfringAutoFp(), RunModeIdsPfringSingle(), RunModeIdsPfringWorkers(), RunModeIpsIPFWAutoFp(), RunModeIpsIPFWWorker(), RunModeIpsNFQAutoFp(), RunModeIpsNFQWorker(), and RunModeIpsWinDivertAutoFp().
TimeModeSetOffline()
void TimeModeSetOffline (void)
Definition at line 105 of file util-time.c.
Referenced by RunModeErfFileAutoFp(), RunModeErfFileSingle(), RunModeFilePcapAutoFp(), and RunModeFilePcapSingle().
TimeSet()
void TimeSet (struct timeval * tv)
Definition at line 125 of file util-time.c.
Referenced by TimeSetIncrementTime(), and TimeSetToCurrentTime().
TimeSetByThread()
void TimeSetByThread (const int thread_id, const struct timeval * tv)
Definition at line 116 of file util-time.c.
TimeSetIncrementTime()
void TimeSetIncrementTime (uint32_t tv_sec)
increment the time in the engine
Parameters
tv_sec seconds to increment the time with
Definition at line 184 of file util-time.c.
References TimeGet(), TimeSet(), and tv.
TimeSetToCurrentTime()
void TimeSetToCurrentTime (void)
set the time to "gettimeofday" meant for testing
Definition at line 144 of file util-time.c.
References TimeSet(), and tv.