suricata: /Users/jlu/suricata/src/util-reference-config.h File Reference
util-reference-config.h File Reference
Data Structures
struct SCRConfReference_
Holds a reference from the file - reference.config.
Macros
#define REFERENCE_SYSTEM_NAME_MAX 64
#define REFERENCE_CONTENT_NAME_MAX 1024
Typedefs
typedef struct SCRConfReference_ SCRConfReference
Holds a reference from the file - reference.config.
Functions
SCRConfReference * SCRConfAllocSCRConfReference (const char *, const char *)
Returns a new SCRConfReference instance. The reference string is converted into lowercase, before being assigned to the instance.
void SCRConfDeAllocSCRConfReference (SCRConfReference *)
Frees a SCRConfReference instance.
int SCRConfLoadReferenceConfigFile (DetectEngineCtx *, FILE *)
Loads the Reference info from the reference.config file.
void SCRConfDeInitContext (DetectEngineCtx *)
Releases de_ctx resources related to Reference Config API.
SCRConfReference * SCRConfGetReference (const char *, DetectEngineCtx *)
Gets the reference config from the corresponding hash table stored in the Detection Engine Context's reference conf ht, given the reference name.
int SCRConfAddReference (DetectEngineCtx *de_ctx, const char *line)
Parses a line from the reference config file and adds it to Reference Config hash table DetectEngineCtx->reference_conf_ht.
void SCRConfRegisterTests (void)
This function registers unit tests for Reference Config API.
FILE * SCRConfGenerateValidDummyReferenceConfigFD01 (void)
Creates a dummy reference config, with all valid references, for testing purposes.
FILE * SCRConfGenerateInValidDummyReferenceConfigFD02 (void)
Creates a dummy reference config, with some valid references and a couple of invalid references, for testing purposes.
FILE * SCRConfGenerateInValidDummyReferenceConfigFD03 (void)
Creates a dummy reference config, with all invalid references, for testing purposes.
void SCReferenceConfInit (void)
void SCReferenceConfDeinit (void)
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file util-reference-config.h.
Macro Definition Documentation
REFERENCE_CONTENT_NAME_MAX
#define REFERENCE_CONTENT_NAME_MAX 1024
Definition at line 28 of file util-reference-config.h.
REFERENCE_SYSTEM_NAME_MAX
#define REFERENCE_SYSTEM_NAME_MAX 64
Definition at line 27 of file util-reference-config.h.
Typedef Documentation
SCRConfReference
typedef struct SCRConfReference_ SCRConfReference
Holds a reference from the file - reference.config.
Function Documentation
SCRConfAddReference()
int SCRConfAddReference (DetectEngineCtx * de_ctx, const char * line)
Parses a line from the reference config file and adds it to Reference Config hash table DetectEngineCtx->reference_conf_ht.
Parameters
rawstr Pointer to the string to be parsed.
de_ctx Pointer to the Detection Engine Context.
Return values
0 On success.
-1 On failure.
Definition at line 230 of file util-reference-config.c.
References REFERENCE_CONTENT_NAME_MAX, and REFERENCE_SYSTEM_NAME_MAX.
SCRConfAllocSCRConfReference()
SCRConfReference * SCRConfAllocSCRConfReference (const char * system, const char * url)
Returns a new SCRConfReference instance. The reference string is converted into lowercase, before being assigned to the instance.
Parameters
system Pointer to the system.
url Pointer to the reference url.
Return values
ref Pointer to the new instance of SCRConfReference.
Definition at line 357 of file util-reference-config.c.
References SC_ERR_INVALID_SIGNATURE, SCLogError, SCMalloc, and SCRConfReference_::system.
Referenced by SCRConfGetReference().
SCRConfDeAllocSCRConfReference()
void SCRConfDeAllocSCRConfReference (SCRConfReference * ref)
Frees a SCRConfReference instance.
Parameters
Pointer to the SCRConfReference instance that has to be freed.
Definition at line 391 of file util-reference-config.c.
References SCFree, SCRConfReference_::system, and SCRConfReference_::url.
Referenced by SCRConfGetReference(), and SCRConfReferenceHashFree().
SCRConfDeInitContext()
void SCRConfDeInitContext (DetectEngineCtx * de_ctx)
Releases de_ctx resources related to Reference Config API.
Definition at line 187 of file util-reference-config.c.
References de_ctx, HashTableFree(), and DetectEngineCtx_::reference_conf_ht.
Referenced by DetectEngineCtxFree().
SCRConfGenerateInValidDummyReferenceConfigFD02()
FILE * SCRConfGenerateInValidDummyReferenceConfigFD02 (void)
Creates a dummy reference config, with some valid references and a couple of invalid references, for testing purposes.
Definition at line 569 of file util-reference-config.c.
References SCFmemopen, and SCLogDebug.
SCRConfGenerateInValidDummyReferenceConfigFD03()
FILE * SCRConfGenerateInValidDummyReferenceConfigFD03 (void)
Creates a dummy reference config, with all invalid references, for testing purposes.
Definition at line 589 of file util-reference-config.c.
References SCFmemopen, and SCLogDebug.
SCRConfGenerateValidDummyReferenceConfigFD01()
FILE * SCRConfGenerateValidDummyReferenceConfigFD01 (void)
Creates a dummy reference config, with all valid references, for testing purposes.
Definition at line 549 of file util-reference-config.c.
References SCFmemopen, and SCLogDebug.
SCRConfGetReference()
SCRConfReference * SCRConfGetReference (const char * rconf_name, DetectEngineCtx * de_ctx)
Gets the reference config from the corresponding hash table stored in the Detection Engine Context's reference conf ht, given the reference name.
Parameters
ct_name Pointer to the reference name that has to be looked up.
de_ctx Pointer to the Detection Engine Context.
Return values
lookup_rconf_info Pointer to the SCRConfReference instance from the hash table on success; NULL on failure.
Definition at line 527 of file util-reference-config.c.
References de_ctx, HashTableLookup(), DetectEngineCtx_::reference_conf_ht, SCRConfAllocSCRConfReference(), and SCRConfDeAllocSCRConfReference().
SCRConfLoadReferenceConfigFile()
int SCRConfLoadReferenceConfigFile (DetectEngineCtx * de_ctx, FILE * fd)
Loads the Reference info from the reference.config file.
   The reference.config file contains references that can be used in
   Signatures.  Each line of the file should  have the following format -
   config reference: system_name, reference_url.
Parameters
de_ctx Pointer to the Detection Engine Context that should be updated with reference information.
Return values
0 On success.
-1 On failure.
Definition at line 496 of file util-reference-config.c.
SCRConfRegisterTests()
void SCRConfRegisterTests (void)
This function registers unit tests for Reference Config API.
Definition at line 786 of file util-reference-config.c.
References UtRegisterTest().
SCReferenceConfDeinit()
void SCReferenceConfDeinit (void)
Definition at line 77 of file util-reference-config.c.
SCReferenceConfInit()
void SCReferenceConfInit (void)
Definition at line 56 of file util-reference-config.c.
Referenced by LLVMFuzzerTestOneInput(), PostConfLoadedDetectSetup(), and RunUnittests().