suricata: /Users/jlu/suricata/src/util-hash-string.h File Reference
util-hash-string.h File Reference
Functions
uint32_t StringHashDjb2 (const uint8_t *data, uint32_t datalen)
uint32_t StringHashFunc (HashTable *ht, void *data, uint16_t datalen)
char StringHashCompareFunc (void *data1, uint16_t datalen1, void *data2, uint16_t datalen2)
void StringHashFreeFunc (void *data)
Function Documentation
StringHashCompareFunc()
char StringHashCompareFunc (void * data1, uint16_t datalen1, void * data2, uint16_t datalen2)
Definition at line 38 of file util-hash-string.c.
Referenced by DetectMetadataHashInit().
StringHashDjb2()
uint32_t StringHashDjb2 (const uint8_t * data, uint32_t datalen)
Definition at line 22 of file util-hash-string.c.
Referenced by StringHashFunc().
StringHashFreeFunc()
void StringHashFreeFunc (void * data)
Definition at line 51 of file util-hash-string.c.
References SCFree.
Referenced by DetectMetadataHashInit().
StringHashFunc()
uint32_t StringHashFunc (HashTable * ht, void * data, uint16_t datalen)
Definition at line 33 of file util-hash-string.c.
References HashTable_::array_size, and StringHashDjb2().
Referenced by DetectMetadataHashInit().