suricata: /Users/jlu/suricata/src/util-hashlist.h File Reference
util-hashlist.h File Reference
Data Structures
struct HashListTableBucket_
struct HashListTable_
Macros
#define HASHLIST_NO_SIZE 0
#define HashListTableGetListNext(hb) (hb)->listnext
#define HashListTableGetListData(hb) (hb)->data
Typedefs
typedef struct HashListTableBucket_ HashListTableBucket
typedef struct HashListTable_ HashListTable
Functions
HashListTable * HashListTableInit (uint32_t, uint32_t(*Hash)(struct HashListTable_ *, void *, uint16_t), char(*Compare)(void *, uint16_t, void *, uint16_t), void(*Free)(void *))
void HashListTableFree (HashListTable *)
void HashListTablePrint (HashListTable *)
int HashListTableAdd (HashListTable *, void *, uint16_t)
int HashListTableRemove (HashListTable *, void *, uint16_t)
void * HashListTableLookup (HashListTable *, void *, uint16_t)
uint32_t HashListTableGenericHash (HashListTable *, void *, uint16_t)
HashListTableBucket * HashListTableGetListHead (HashListTable *)
char HashListTableDefaultCompare (void *, uint16_t, void *, uint16_t)
void HashListTableRegisterTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file util-hashlist.h.
Macro Definition Documentation
HASHLIST_NO_SIZE
#define HASHLIST_NO_SIZE 0
Definition at line 47 of file util-hashlist.h.
HashListTableGetListData
#define HashListTableGetListData (hb) (hb)->data
Definition at line 59 of file util-hashlist.h.
HashListTableGetListNext
#define HashListTableGetListNext (hb) (hb)->listnext
Definition at line 58 of file util-hashlist.h.
Typedef Documentation
HashListTable
typedef struct HashListTable_ HashListTable
HashListTableBucket
typedef struct HashListTableBucket_ HashListTableBucket
Function Documentation
HashListTableAdd()
int HashListTableAdd (HashListTable * ht, void * data, uint16_t datalen)
Definition at line 116 of file util-hashlist.c.
References HashListTable_::array, HashListTableBucket_::bucknext, HashListTableBucket_::data, HashListTable_::Hash, HashListTable_::listhead, HashListTableBucket_::listnext, HashListTableBucket_::listprev, HashListTable_::listtail, SCLogDebug, SCMalloc, HashListTableBucket_::size, and unlikely.
Referenced by DetectEngineBufferTypeGetByIdTransforms(), DetectPortHashAdd(), and SigGroupHeadHashAdd().
HashListTableDefaultCompare()
char HashListTableDefaultCompare (void * data1, uint16_t len1, void * data2, uint16_t len2)
Definition at line 237 of file util-hashlist.c.
References SCMemcmp.
Referenced by HashListTableInit().
HashListTableFree()
void HashListTableFree (HashListTable * ht)
Definition at line 82 of file util-hashlist.c.
References HashListTable_::array, HashListTable_::array_size, HashListTableBucket_::bucknext, HashListTableBucket_::data, HashListTable_::Free, and SCFree.
Referenced by DetectAddressMapFree(), DetectParseDupSigHashFree(), DetectPortHashFree(), DumpPatterns(), MpmStoreFree(), PrefilterDeinit(), and SigGroupHeadHashFree().
HashListTableGenericHash()
uint32_t HashListTableGenericHash (HashListTable * ht, void * data, uint16_t datalen)
Definition at line 273 of file util-hashlist.c.
References HashListTable_::array_size.
HashListTableGetListHead()
HashListTableBucket * HashListTableGetListHead (HashListTable * ht)
Definition at line 290 of file util-hashlist.c.
References HashListTable_::listhead.
Referenced by DumpPatterns(), FeatureDump(), and MpmStoreReportStats().
HashListTableInit()
HashListTable * HashListTableInit (uint32_t size, uint32_t(*)(struct HashListTable_ *, void *, uint16_t) Hash, char(*)(void *, uint16_t, void *, uint16_t) Compare, void(*)(void *) Free)
Definition at line 35 of file util-hashlist.c.
References HashListTable_::array, HashListTable_::array_size, HashListTable_::Compare, HashListTable_::Free, HashListTable_::Hash, HashListTableDefaultCompare(), HashListTable_::listhead, HashListTable_::listtail, SCFree, SCMalloc, and unlikely.
Referenced by DetectAddressMapInit(), DetectParseDupSigHashInit(), DetectPortHashInit(), DetectRegisterThreadCtxFuncs(), EngineAnalysisAddAllRulePatterns(), MpmStoreInit(), PrefilterInit(), and SigGroupHeadHashInit().
HashListTableLookup()
void * HashListTableLookup (HashListTable * ht, void * data, uint16_t datalen)
Definition at line 248 of file util-hashlist.c.
References HashListTable_::array, HashListTableBucket_::bucknext, HashListTable_::Compare, HashListTableBucket_::data, HashListTable_::Hash, SCLogDebug, and HashListTableBucket_::size.
Referenced by DetectEngineBufferTypeGetById(), DetectEngineBufferTypeGetByIdTransforms(), DetectPortHashLookup(), SigGroupHeadHashLookup(), VarNameStoreLookupById(), and VarNameStoreLookupByName().
HashListTablePrint()
void HashListTablePrint (HashListTable * ht)
Definition at line 108 of file util-hashlist.c.
References HashListTable_::array_size, and HashListTable_::Hash.
HashListTableRegisterTests()
void HashListTableRegisterTests (void)
Definition at line 501 of file util-hashlist.c.
References UtRegisterTest().
HashListTableRemove()
int HashListTableRemove (HashListTable * ht, void * data, uint16_t datalen)
Definition at line 157 of file util-hashlist.c.
References HashListTable_::array, HashListTableBucket_::bucknext, HashListTable_::Compare, HashListTableBucket_::data, HashListTable_::Free, HashListTable_::Hash, HashListTable_::listhead, HashListTableBucket_::listnext, HashListTableBucket_::listprev, HashListTable_::listtail, SCFree, SCLogDebug, and HashListTableBucket_::size.
Referenced by DetectUnregisterThreadCtxFuncs(), and SigGroupHeadHashRemove().