suricata: /Users/jlu/suricata/src/util-base64.c File Reference
util-base64.c File Reference
#include "util-base64.h"
#include "util-unittest.h"
Macros
#define BASE64_TABLE_MAX 122
Functions
Base64Ecode DecodeBase64 (uint8_t *dest, uint32_t dest_size, const uint8_t *src, uint32_t len, uint32_t *consumed_bytes, uint32_t *decoded_bytes, Base64Mode mode)
Decodes a base64-encoded string buffer into an ascii-encoded byte buffer.
void Base64RegisterTests (void)
Detailed Description
Author
David Abarbanel david.nosp@m..aba.nosp@m.rbane.nosp@m.l@ba.nosp@m.esyst.nosp@m.ems..nosp@m.com
Definition in file util-base64.c.
Macro Definition Documentation
BASE64_TABLE_MAX
#define BASE64_TABLE_MAX 122
Definition at line 28 of file util-base64.c.
Function Documentation
Base64RegisterTests()
void Base64RegisterTests (void)
Definition at line 280 of file util-base64.c.
References UtRegisterTest().
DecodeBase64()
Base64Ecode DecodeBase64 (uint8_t * dest, uint32_t dest_size, const uint8_t * src, uint32_t len, uint32_t * consumed_bytes, uint32_t * decoded_bytes, Base64Mode mode)
Decodes a base64-encoded string buffer into an ascii-encoded byte buffer.
Parameters
dest The destination byte buffer
dest_size The destination byte buffer size
src The source string
len The length of the source string
consumed_bytes The bytes that were actually processed/consumed
decoded_bytes The bytes that were decoded
mode The mode in which decoding should happen
Returns
Error code indicating success or failures with parsing
Definition at line 93 of file util-base64.c.
References B64_BLOCK, BASE64_ECODE_OK, len, and padding.
Referenced by DatasetAddSerialized(), DatasetRemoveSerialized(), and DetectBase64DecodeDoMatch().