suricata: /Users/jlu/suricata/src/util-ja3.c File Reference
util-ja3.c File Reference
#include "suricata-common.h"
#include "app-layer-ssl.h"
#include "util-validate.h"
#include "util-ja3.h"
Macros
#define MD5_STRING_LENGTH 33
Functions
JA3Buffer * Ja3BufferInit (void)
Allocate new buffer.
void Ja3BufferFree (JA3Buffer **buffer)
Free allocated buffer.
int Ja3BufferAppendBuffer (JA3Buffer **buffer1, JA3Buffer **buffer2)
Append buffer to buffer.
int Ja3BufferAddValue (JA3Buffer **buffer, uint32_t value)
Add value to buffer.
char * Ja3GenerateHash (JA3Buffer *buffer)
Generate Ja3 hash string.
int Ja3IsDisabled (const char *type)
Check if JA3 is disabled.
Detailed Description
Author
Mats Klepsland mats..nosp@m.klep.nosp@m.sland.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Functions used to generate JA3 fingerprint.
Definition in file util-ja3.c.
Macro Definition Documentation
MD5_STRING_LENGTH
#define MD5_STRING_LENGTH 33
Definition at line 31 of file util-ja3.c.
Function Documentation
Ja3BufferAddValue()
int Ja3BufferAddValue (JA3Buffer ** buffer, uint32_t value)
Add value to buffer.
Parameters
buffer The buffer.
value The value.
Return values
0 on success.
-1 on failure.
Definition at line 170 of file util-ja3.c.
References JA3_BUFFER_INITIAL_SIZE, Ja3BufferFree(), SC_ERR_INVALID_ARGUMENT, SC_ERR_MEM_ALLOC, SCLogError, and SCMalloc.
Ja3BufferAppendBuffer()
int Ja3BufferAppendBuffer (JA3Buffer ** buffer1, JA3Buffer ** buffer2)
Append buffer to buffer.
Append the second buffer to the first and then free it.
Parameters
buffer1 The first buffer.
buffer2 The second buffer.
Return values
0 on success.
-1 on failure.
Definition at line 106 of file util-ja3.c.
References SC_ERR_INVALID_ARGUMENT, SCFree, and SCLogError.
Ja3BufferFree()
void Ja3BufferFree (JA3Buffer ** buffer)
Free allocated buffer.
Parameters
buffer The buffer to free.
Definition at line 54 of file util-ja3.c.
References DEBUG_VALIDATE_BUG_ON, and SCFree.
Referenced by Ja3BufferAddValue().
Ja3BufferInit()
JA3Buffer * Ja3BufferInit (void)
Allocate new buffer.
Returns
pointer to buffer on success.
NULL on failure.
Definition at line 39 of file util-ja3.c.
References SCCalloc.
Ja3GenerateHash()
char * Ja3GenerateHash (JA3Buffer * buffer)
Generate Ja3 hash string.
Parameters
buffer The Ja3 buffer.
Return values
pointer to hash string on success.
NULL on failure.
Definition at line 215 of file util-ja3.c.
References JA3Buffer_::data, MD5_STRING_LENGTH, SC_ERR_INVALID_ARGUMENT, SC_ERR_INVALID_VALUE, SC_ERR_MEM_ALLOC, SCLogError, SCMalloc, and JA3Buffer_::used.
Ja3IsDisabled()
int Ja3IsDisabled (const char * type)
Check if JA3 is disabled.
Issue warning if JA3 is disabled or if we are lacking support for JA3.
Parameters
type Type to add to warning.
Return values
1 if disabled.
0 otherwise.
Definition at line 249 of file util-ja3.c.
References SC_WARN_JA3_DISABLED, SCLogWarning, SSLJA3IsEnabled(), and type.