suricata: /Users/jlu/suricata/src/util-strlcatu.c File Reference
util-strlcatu.c File Reference
#include "suricata-common.h"
Functions
size_t strlcat (char *dst, const char *src, size_t siz)
Function Documentation
strlcat()
size_t strlcat (char * dst, const char * src, size_t siz)
Definition at line 45 of file util-strlcatu.c.
References dst, and src.
Referenced by ConfLoadCompleteIncludePath(), DetectAppLayerMpmRegisterByParentId(), DetectLoadCompleteSigPath(), RunmodeAutoFpCreatePickupQueuesString(), ShortenString(), SSLVersionToString(), StringAsBase64(), and TmThreadWaitOnThreadInit().