suricata: /Users/jlu/suricata/src/util-device.c File Reference
util-device.c File Reference
Utility functions to handle device list.
#include "suricata-common.h"
#include "conf.h"
#include "util-device.h"
#include "util-ioctl.h"
#include "util-misc.h"
#include "util-dpdk.h"
#include "device-storage.h"
Macros
#define MAX_DEVNAME 10
Functions
void LiveSetOffloadDisable (void)
void LiveSetOffloadWarn (void)
int LiveGetOffload (void)
int LiveRegisterDeviceName (const char *dev)
Add a device for monitoring.
int LiveRegisterDevice (const char *dev)
Add a pcap device for monitoring and create structure.
int LiveGetDeviceCount (void)
Get the number of registered devices.
const char * LiveGetDeviceName (int number)
Get a pointer to the device name at idx.
int LiveGetDeviceNameCount (void)
Get the number of pre registered devices.
const char * LiveGetDeviceNameName (int number)
Get a pointer to the pre device name at idx.
LiveDevice * LiveGetDevice (const char *name)
Get a pointer to the device at idx.
const char * LiveGetShortName (const char *dev)
int LiveBuildDeviceList (const char *runmode)
int LiveBuildDeviceListCustom (const char *runmode, const char *itemname)
void LiveDeviceHasNoStats ()
int LiveDeviceListClean ()
LiveDevice * LiveDeviceForEach (LiveDevice **ldev, LiveDevice **ndev)
void LiveDeviceFinalize (void)
void LiveDevRegisterExtension (void)
int LiveDevUseBypass (LiveDevice *dev)
void LiveDevSetBypassStats (LiveDevice *dev, uint64_t cnt, int family)
void LiveDevAddBypassStats (LiveDevice *dev, uint64_t cnt, int family)
void LiveDevSubBypassStats (LiveDevice *dev, uint64_t cnt, int family)
void LiveDevAddBypassFail (LiveDevice *dev, uint64_t cnt, int family)
void LiveDevAddBypassSuccess (LiveDevice *dev, uint64_t cnt, int family)
Variables
BypassInfo
Detailed Description
Utility functions to handle device list.
Author
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Definition in file util-device.c.
Macro Definition Documentation
MAX_DEVNAME
#define MAX_DEVNAME 10
Definition at line 27 of file util-device.c.
Function Documentation
LiveBuildDeviceList()
int LiveBuildDeviceList (const char * runmode)
Definition at line 308 of file util-device.c.
References LiveBuildDeviceListCustom().
LiveBuildDeviceListCustom()
int LiveBuildDeviceListCustom (const char * runmode, const char * itemname)
Definition at line 313 of file util-device.c.
References ConfGetNode(), LiveRegisterDeviceName(), ConfNode_::name, next, TAILQ_FOREACH, and ConfNode_::val.
Referenced by LiveBuildDeviceList().
LiveDevAddBypassFail()
void LiveDevAddBypassFail (LiveDevice * dev, uint64_t cnt, int family)
Increase number of failed captured flows for a protocol family
Parameters
dev pointer to LiveDevice to set stats for
cnt number of flows to add
family AF_INET to set IPv4 count or AF_INET6 to set IPv6 count
Definition at line 581 of file util-device.c.
LiveDevAddBypassStats()
void LiveDevAddBypassStats (LiveDevice * dev, uint64_t cnt, int family)
Increase number of currently bypassed flows for a protocol family
Parameters
dev pointer to LiveDevice to set stats for
cnt number of flows to add
family AF_INET to set IPv4 count or AF_INET6 to set IPv6 count
Definition at line 543 of file util-device.c.
LiveDevAddBypassSuccess()
void LiveDevAddBypassSuccess (LiveDevice * dev, uint64_t cnt, int family)
Increase number of currently successfully bypassed flows for a protocol family
Parameters
dev pointer to LiveDevice to set stats for
cnt number of flows to add
family AF_INET to set IPv4 count or AF_INET6 to set IPv6 count
Definition at line 600 of file util-device.c.
LiveDeviceFinalize()
void LiveDeviceFinalize (void)
Create registered devices
This function creates all needed LiveDevice from the LiveDeviceName list created via LiveRegisterDevice()
Definition at line 470 of file util-device.c.
References LiveDeviceName_::dev, LiveRegisterDevice(), next, SCFree, SCLogDebug, and TAILQ_FOREACH_SAFE.
LiveDeviceForEach()
LiveDevice * LiveDeviceForEach (LiveDevice ** ldev, LiveDevice ** ndev)
Definition at line 448 of file util-device.c.
References next, TAILQ_FIRST, and TAILQ_NEXT.
LiveDeviceHasNoStats()
void LiveDeviceHasNoStats (void)
Call this function to disable stat on live devices
This can be useful in the case, this is not a real interface.
Definition at line 343 of file util-device.c.
Referenced by RunModeIpsIPFWAutoFp(), RunModeIpsIPFWWorker(), RunModeIpsNFQAutoFp(), RunModeIpsNFQWorker(), and RunModeIpsWinDivertAutoFp().
LiveDeviceListClean()
int LiveDeviceListClean (void)
Definition at line 348 of file util-device.c.
References next, SCEnter, and TAILQ_FOREACH_SAFE.
LiveDevRegisterExtension()
void LiveDevRegisterExtension (void)
Register bypass stats storage
Definition at line 493 of file util-device.c.
Referenced by PostConfLoadedSetup().
LiveDevSetBypassStats()
void LiveDevSetBypassStats (LiveDevice * dev, uint64_t cnt, int family)
Set number of currently bypassed flows for a protocol family
Parameters
dev pointer to LiveDevice to set stats for
cnt number of currently bypassed flows
family AF_INET to set IPv4 count or AF_INET6 to set IPv6 count
Definition at line 524 of file util-device.c.
LiveDevSubBypassStats()
void LiveDevSubBypassStats (LiveDevice * dev, uint64_t cnt, int family)
Decrease number of currently bypassed flows for a protocol family
Parameters
dev pointer to LiveDevice to set stats for
cnt number of flows to remove
family AF_INET to set IPv4 count or AF_INET6 to set IPv6 count
Definition at line 562 of file util-device.c.
LiveDevUseBypass()
int LiveDevUseBypass (LiveDevice * dev)
Prepare a LiveDevice so we can set bypass stats
Definition at line 502 of file util-device.c.
References BypassInfo, LiveDevSetStorageById(), SC_ATOMIC_INIT, SC_ERR_MEM_ALLOC, SCCalloc, and SCLogError.
LiveGetDevice()
LiveDevice * LiveGetDevice (const char * name)
Get a pointer to the device at idx.
Parameters
number idx of the device in our list
Return values
ptr pointer to the string containing the device
NULL on error
Definition at line 279 of file util-device.c.
References LiveDevice_::dev, next, SC_ERR_INVALID_VALUE, SCLogWarning, and TAILQ_FOREACH.
Referenced by LiveGetShortName(), and ReceiveErfDagThreadInit().
LiveGetDeviceCount()
int LiveGetDeviceCount (void)
Get the number of registered devices.
Return values
cnt the number of registered devices
Definition at line 157 of file util-device.c.
References next, and TAILQ_FOREACH.
Referenced by AFPRunModeIsIPS(), RunModeSetIPSAutoFp(), RunModeSetIPSWorker(), RunModeSetLiveCaptureAutoFp(), RunModeSetLiveCaptureSingle(), and RunModeSetLiveCaptureWorkers().
LiveGetDeviceName()
const char * LiveGetDeviceName (int number)
Get a pointer to the device name at idx.
Parameters
number idx of the device in our list
Return values
ptr pointer to the string containing the device
NULL on error
Definition at line 177 of file util-device.c.
References LiveDevice_::dev, next, and TAILQ_FOREACH.
Referenced by AFPRunModeIsIPS(), RunModeSetIPSAutoFp(), RunModeSetIPSWorker(), RunModeSetLiveCaptureAutoFp(), RunModeSetLiveCaptureSingle(), and RunModeSetLiveCaptureWorkers().
LiveGetDeviceNameCount()
int LiveGetDeviceNameCount (void)
Get the number of pre registered devices.
Return values
cnt the number of pre registered devices
Definition at line 198 of file util-device.c.
References next, and TAILQ_FOREACH.
LiveGetDeviceNameName()
const char * LiveGetDeviceNameName (int number)
Get a pointer to the pre device name at idx.
Parameters
number idx of the pre device in our list
Return values
ptr pointer to the string containing the device
NULL on error
Definition at line 218 of file util-device.c.
References LiveDeviceName_::dev, next, and TAILQ_FOREACH.
LiveGetOffload()
int LiveGetOffload (void)
Definition at line 80 of file util-device.c.
LiveGetShortName()
const char * LiveGetShortName (const char * dev)
Definition at line 300 of file util-device.c.
References LiveDevice_::dev_short, and LiveGetDevice().
Referenced by RunModeSetLiveCaptureAutoFp().
LiveRegisterDevice()
int LiveRegisterDevice (const char * dev)
Add a pcap device for monitoring and create structure.
Parameters
dev string with the device name
Return values
0 on success.
-1 on failure.
Definition at line 125 of file util-device.c.
References LiveDevice_::dev, LiveDevStorageSize(), SCCalloc, SCFree, SCStrdup, and unlikely.
Referenced by LiveDeviceFinalize().
LiveRegisterDeviceName()
int LiveRegisterDeviceName (const char * dev)
Add a device for monitoring.
To be used during option parsing. When a device has to be created during runmode init, use LiveRegisterDevice()
Parameters
dev string with the device name
Return values
0 on success.
-1 on failure.
Definition at line 96 of file util-device.c.
References LiveDeviceName_::dev, next, SCCalloc, SCFree, SCLogDebug, SCStrdup, TAILQ_INSERT_TAIL, and unlikely.
Referenced by LiveBuildDeviceListCustom().
LiveSetOffloadDisable()
void LiveSetOffloadDisable (void)
Definition at line 70 of file util-device.c.
Referenced by PostConfLoadedSetup().
LiveSetOffloadWarn()
void LiveSetOffloadWarn (void)
Definition at line 75 of file util-device.c.
Referenced by PostConfLoadedSetup().
Variable Documentation
BypassInfo
BypassInfo
Definition at line 59 of file util-device.c.
Referenced by LiveDevUseBypass().