suricata: /Users/jlu/suricata/src/util-bloomfilter-counting.c File Reference
util-bloomfilter-counting.c File Reference
#include "suricata-common.h"
#include "util-bloomfilter-counting.h"
#include "util-unittest.h"
Functions
BloomFilterCounting * BloomFilterCountingInit (uint32_t size, uint8_t type, uint8_t iter, uint32_t(*Hash)(const void *, uint16_t, uint8_t, uint32_t))
void BloomFilterCountingFree (BloomFilterCounting *bf)
void BloomFilterCountingPrint (BloomFilterCounting *bf)
int BloomFilterCountingAdd (BloomFilterCounting *bf, const void *data, uint16_t datalen)
int BloomFilterCountingRemove (BloomFilterCounting *bf, const void *data, uint16_t datalen)
int BloomFilterCountingTest (BloomFilterCounting *bf, const void *data, uint16_t datalen)
void BloomFilterCountingRegisterTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Counting Bloom Filter implementation. Can be used with 8, 16, 32 bits counters.
Definition in file util-bloomfilter-counting.c.
Function Documentation
BloomFilterCountingAdd()
int BloomFilterCountingAdd (BloomFilterCounting * bf, const void * data, uint16_t datalen)
Definition at line 99 of file util-bloomfilter-counting.c.
References BloomFilterCounting_::array, BloomFilterCounting_::array_size, BloomFilterCounting_::Hash, BloomFilterCounting_::hash_iterations, and BloomFilterCounting_::type.
BloomFilterCountingFree()
void BloomFilterCountingFree (BloomFilterCounting * bf)
Definition at line 78 of file util-bloomfilter-counting.c.
References BloomFilterCounting_::array, and SCFree.
BloomFilterCountingInit()
BloomFilterCounting * BloomFilterCountingInit (uint32_t size, uint8_t type, uint8_t iter, uint32_t(*)(const void *, uint16_t, uint8_t, uint32_t) Hash)
Definition at line 34 of file util-bloomfilter-counting.c.
References BloomFilterCounting_::array, BloomFilterCounting_::array_size, BloomFilterCounting_::Hash, BloomFilterCounting_::hash_iterations, SCFree, SCMalloc, type, BloomFilterCounting_::type, and unlikely.
BloomFilterCountingPrint()
void BloomFilterCountingPrint (BloomFilterCounting * bf)
Definition at line 88 of file util-bloomfilter-counting.c.
References BloomFilterCounting_::array_size, BloomFilterCounting_::Hash, BloomFilterCounting_::hash_iterations, and BloomFilterCounting_::type.
BloomFilterCountingRegisterTests()
void BloomFilterCountingRegisterTests (void)
Definition at line 393 of file util-bloomfilter-counting.c.
References UtRegisterTest().
BloomFilterCountingRemove()
int BloomFilterCountingRemove (BloomFilterCounting * bf, const void * data, uint16_t datalen)
Definition at line 127 of file util-bloomfilter-counting.c.
References BloomFilterCounting_::array, BloomFilterCounting_::array_size, BloomFilterCountingTest(), BloomFilterCounting_::Hash, BloomFilterCounting_::hash_iterations, and BloomFilterCounting_::type.
BloomFilterCountingTest()
int BloomFilterCountingTest (BloomFilterCounting * bf, const void * data, uint16_t datalen)
Definition at line 183 of file util-bloomfilter-counting.c.
References BloomFilterCounting_::array, BloomFilterCounting_::array_size, BloomFilterCounting_::Hash, BloomFilterCounting_::hash_iterations, and BloomFilterCounting_::type.
Referenced by BloomFilterCountingRemove().