suricata: /Users/jlu/suricata/src/util-var-name.c File Reference
util-var-name.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "util-hashlist.h"
#include "util-var-name.h"
Data Structures
struct VarNameStore_
struct VariableName_
Name2idx mapping structure for flowbits, flowvars and pktvars.
Macros
#define VARNAME_HASHSIZE 0x1000
#define VARID_HASHSIZE 0x1000
Typedefs
typedef struct VarNameStore_ VarNameStore
typedef struct VariableName_ VariableName
Name2idx mapping structure for flowbits, flowvars and pktvars.
Functions
SC_ATOMIC_DECLARE (VarNameStore *, g_varnamestore_current)
int VarNameStoreSetupStaging (uint32_t de_ctx_version)
setup staging store. Include current store if there is one.
const char * VarNameStoreLookupById (const uint32_t id, const enum VarTypes type)
uint32_t VarNameStoreLookupByName (const char *name, const enum VarTypes type)
uint32_t VarNameStoreSetupAdd (const char *name, const enum VarTypes type)
add to staging or return existing id if already in there
char * VarNameStoreSetupLookup (uint32_t idx, const enum VarTypes type)
void VarNameStoreActivateStaging (void)
void VarNameStoreFreeOld (void)
void VarNameStoreFree (uint32_t de_ctx_version)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Generic variable name utility functions
Definition in file util-var-name.c.
Macro Definition Documentation
VARID_HASHSIZE
#define VARID_HASHSIZE 0x1000
Definition at line 69 of file util-var-name.c.
VARNAME_HASHSIZE
#define VARNAME_HASHSIZE 0x1000
Definition at line 68 of file util-var-name.c.
Typedef Documentation
VariableName
typedef struct VariableName_ VariableName
Name2idx mapping structure for flowbits, flowvars and pktvars.
VarNameStore
typedef struct VarNameStore_ VarNameStore
Function Documentation
SC_ATOMIC_DECLARE()
SC_ATOMIC_DECLARE (VarNameStore * , g_varnamestore_current)
VarNameStoreActivateStaging()
void VarNameStoreActivateStaging (void)
Definition at line 340 of file util-var-name.c.
References SCMutexLock.
VarNameStoreFree()
void VarNameStoreFree (uint32_t de_ctx_version)
Definition at line 364 of file util-var-name.c.
References SCLogDebug, and SCMutexLock.
VarNameStoreFreeOld()
void VarNameStoreFreeOld (void)
Definition at line 353 of file util-var-name.c.
References SCMutexLock.
VarNameStoreLookupById()
const char * VarNameStoreLookupById (const uint32_t id, const enum VarTypes type)
Definition at line 297 of file util-var-name.c.
References BUG_ON, HashListTableLookup(), VarNameStore_::ids, VariableName_::name, SC_ATOMIC_GET, and type.
VarNameStoreLookupByName()
uint32_t VarNameStoreLookupByName (const char * name, const enum VarTypes type)
Definition at line 309 of file util-var-name.c.
References BUG_ON, HashListTableLookup(), VariableName_::idx, VarNameStore_::names, SC_ATOMIC_GET, SCLogDebug, and type.
Referenced by DetectFlowintMatch().
VarNameStoreSetupAdd()
uint32_t VarNameStoreSetupAdd (const char * name, const enum VarTypes type)
add to staging or return existing id if already in there
Definition at line 323 of file util-var-name.c.
References SCMutexLock.
VarNameStoreSetupLookup()
char * VarNameStoreSetupLookup (uint32_t idx, const enum VarTypes type)
Definition at line 332 of file util-var-name.c.
References SCMutexLock.
Referenced by DetectFlowbitsAnalyze().
VarNameStoreSetupStaging()
int VarNameStoreSetupStaging (uint32_t de_ctx_version)
setup staging store. Include current store if there is one.
Definition at line 247 of file util-var-name.c.
References SCMutexLock.