suricata: /Users/jlu/suricata/src/util-datalink.h File Reference
util-datalink.h File Reference
Functions
void DatalinkSetGlobalType (int datalink)
int DatalinkGetGlobalType (void)
bool DatalinkHasMultipleValues (void)
Function Documentation
DatalinkGetGlobalType()
int DatalinkGetGlobalType (void) inline
Definition at line 36 of file util-datalink.c.
References g_datalink_value.
DatalinkHasMultipleValues()
bool DatalinkHasMultipleValues (void)
Definition at line 41 of file util-datalink.c.
References g_datalink_is_multiple.
DatalinkSetGlobalType()
void DatalinkSetGlobalType (int datalink)
Definition at line 25 of file util-datalink.c.
References g_datalink_is_multiple, g_datalink_value, and LINKTYPE_NULL.
Referenced by InitPcapFile(), NapatechStreamThreadInit(), ReceiveErfDagThreadInit(), and ReceiveErfFileThreadInit().