suricata: /Users/jlu/suricata/src/util-print.c File Reference
util-print.c File Reference
#include "suricata-common.h"
#include "util-print.h"
#include "util-error.h"
#include "util-debug.h"
#include "util-validate.h"
#include "rust.h"
Macros
#define BUFFER_LENGTH 2048
#define BUFFER_LENGTH 2048
#define s6_addr16 __u6_addr.__u6_addr16
Functions
void PrintBufferRawLineHex (char *nbuf, int *offset, int max_size, const uint8_t *buf, uint32_t buflen)
print a buffer as hex on a single line
void PrintRawLineHexBuf (char *retbuf, uint32_t retbuflen, const uint8_t *buf, uint32_t buflen)
print a buffer as hex on a single line in to retbuf buffer
void PrintRawJsonFp (FILE *fp, uint8_t *buf, uint32_t buflen)
void PrintRawUriFp (FILE *fp, uint8_t *buf, uint32_t buflen)
void PrintRawUriBuf (char *retbuf, uint32_t *offset, uint32_t retbuflen, uint8_t *buf, uint32_t buflen)
void PrintRawDataFp (FILE *fp, const uint8_t *buf, uint32_t buflen)
void PrintRawDataToBuffer (uint8_t *dst_buf, uint32_t *dst_buf_offset_ptr, uint32_t dst_buf_size, const uint8_t *src_buf, uint32_t src_buf_len)
void PrintStringsToBuffer (uint8_t *dst_buf, uint32_t *dst_buf_offset_ptr, uint32_t dst_buf_size, const uint8_t *src_buf, const uint32_t src_buf_len)
const char * PrintInet (int af, const void *src, char *dst, socklen_t size)
void PrintHexString (char *str, size_t size, uint8_t *buf, size_t buf_len)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Print utility functions
Definition in file util-print.c.
Macro Definition Documentation
BUFFER_LENGTH [1/2]
#define BUFFER_LENGTH 2048
BUFFER_LENGTH [2/2]
#define BUFFER_LENGTH 2048
s6_addr16
#define s6_addr16 __u6_addr.__u6_addr16
Definition at line 248 of file util-print.c.
Function Documentation
PrintBufferRawLineHex()
void PrintBufferRawLineHex (char * nbuf, int * offset, int max_size, const uint8_t * buf, uint32_t buflen)
print a buffer as hex on a single line
Prints in the format "00 AA BB"
Parameters
nbuf buffer into which the output is written
offset of where to start writting into the buffer
max_size the size of the output buffer
buf buffer to print from
buflen length of the input buffer
Definition at line 44 of file util-print.c.
References offset, and PrintBufferData.
Referenced by AlertFastLogger().
PrintHexString()
void PrintHexString (char * str, size_t size, uint8_t * buf, size_t buf_len)
Definition at line 298 of file util-print.c.
References DEBUG_VALIDATE_BUG_ON, and str.
PrintInet()
const char * PrintInet (int af, const void * src, char * dst, socklen_t size)
Definition at line 274 of file util-print.c.
References af, dst, and src.
Referenced by AddressDebugPrint(), AlertFastLogger(), JsonAddrInfoInit(), SCRadixAddKeyIPV4String(), SCRadixAddKeyIPV6String(), and TLSGetIPInformations().
PrintRawDataFp()
void PrintRawDataFp (FILE * fp, const uint8_t * buf, uint32_t buflen)
Definition at line 143 of file util-print.c.
Referenced by DetectBase64DecodeDoMatch(), HtpBodyPrint(), and StreamingBufferCompareRawData().
PrintRawDataToBuffer()
void PrintRawDataToBuffer (uint8_t * dst_buf, uint32_t * dst_buf_offset_ptr, uint32_t dst_buf_size, const uint8_t * src_buf, uint32_t src_buf_len)
Definition at line 181 of file util-print.c.
References PrintBufferData.
PrintRawJsonFp()
void PrintRawJsonFp (FILE * fp, uint8_t * buf, uint32_t buflen)
Definition at line 73 of file util-print.c.
References BUFFER_LENGTH, offset, and PrintBufferData.
PrintRawLineHexBuf()
void PrintRawLineHexBuf (char * retbuf, uint32_t retbuflen, const uint8_t * buf, uint32_t buflen)
print a buffer as hex on a single line in to retbuf buffer
Prints in the format "00 AA BB"
Parameters
retbuf pointer to the buffer which will have the result
rebuflen length of the buffer
buf buffer to print from
buflen length of the input buffer
Definition at line 63 of file util-print.c.
References offset, and PrintBufferData.
PrintRawUriBuf()
void PrintRawUriBuf (char * retbuf, uint32_t * offset, uint32_t retbuflen, uint8_t * buf, uint32_t buflen)
Definition at line 120 of file util-print.c.
References offset, and PrintBufferData.
Referenced by LogCustomFormatWriteTimestamp().
PrintRawUriFp()
void PrintRawUriFp (FILE * fp, uint8_t * buf, uint32_t buflen)
Definition at line 95 of file util-print.c.
References BUFFER_LENGTH, offset, and PrintBufferData.
PrintStringsToBuffer()
void PrintStringsToBuffer (uint8_t * dst_buf, uint32_t * dst_buf_offset_ptr, uint32_t dst_buf_size, const uint8_t * src_buf, const uint32_t src_buf_len)
Definition at line 230 of file util-print.c.