suricata: /Users/jlu/suricata/src/util-rohash.c File Reference
util-rohash.c File Reference
#include "suricata-common.h"
#include "util-hash.h"
#include "util-unittest.h"
#include "util-memcmp.h"
#include "util-hash-lookup3.h"
#include "queue.h"
#include "util-rohash.h"
Data Structures
struct ROHashTableItem_
struct ROHashTableOffsets_
Typedefs
typedef struct ROHashTableItem_ ROHashTableItem
typedef struct ROHashTableOffsets_ ROHashTableOffsets
Functions
ROHashTable * ROHashInit (uint8_t hash_bits, uint16_t item_size)
initialize a new rohash
void ROHashFree (ROHashTable *table)
uint32_t ROHashMemorySize (ROHashTable *table)
void * ROHashLookup (ROHashTable *table, void *data, uint16_t size)
int ROHashInitQueueValue (ROHashTable *table, void *value, uint16_t size)
Add a new value to the hash.
int ROHashInitFinalize (ROHashTable *table)
create final hash data structure
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Chained read only hash table implementation, meaning that after the initial fill no changes are allowed.
Loading takes 2 stages.
stage1 maps data
stage2 fills blob
Todo:
a bloomfilter in the ROHashTableOffsets could possibly prevent a lot of cache misses when validating a potential match
Todo:
maybe add a user ctx to be returned instead, something like a 4/8 byte ptr or simply a flag
Definition in file util-rohash.c.
Typedef Documentation
ROHashTableItem
typedef struct ROHashTableItem_ ROHashTableItem
item_size data beyond this header
ROHashTableOffsets
typedef struct ROHashTableOffsets_ ROHashTableOffsets
offset table
Function Documentation
ROHashFree()
void ROHashFree (ROHashTable * table)
Definition at line 92 of file util-rohash.c.
References ROHashTable_::data, and SCFree.
Referenced by DetectFileHashFree().
ROHashInit()
ROHashTable * ROHashInit (uint8_t hash_bits, uint16_t item_size)
initialize a new rohash
Parameters
hash_bits hash size as 2^hash_bits, so power of 2, max 31
item_size size of the data to store
Return values
table ptr or NULL on error
Definition at line 64 of file util-rohash.c.
References ROHashTable_::hash_bits, hashsize, ROHashTable_::item_size, ROHashTable_::items, SC_ERR_HASH_TABLE_INIT, SCLogError, SCMalloc, TAILQ_INIT, and unlikely.
ROHashInitFinalize()
int ROHashInitFinalize (ROHashTable * table)
create final hash data structure
Parameters
table the hash table
Return values
0 error
1 ok
Note
after this call the nothing can be added to the hash anymore.
Definition at line 184 of file util-rohash.c.
References ROHashTableOffsets_::cnt, ROHashTable_::data, ROHashTable_::hash_bits, hashmask, hashsize, hashword(), ROHashTable_::item_size, ROHashTable_::items, ROHashTable_::locked, next, ROHashTableOffsets_::offset, offset, ROHashTableItem_::pos, SC_ERR_HASH_TABLE_INIT, SCFree, SCLogError, SCMalloc, TAILQ_FIRST, TAILQ_FOREACH, and TAILQ_REMOVE.
ROHashInitQueueValue()
int ROHashInitQueueValue (ROHashTable * table, void * value, uint16_t size)
Add a new value to the hash.
Note
can only be done when table isn't in a locked state yet
Parameters
table the hash table
value value to add
size value size. MUST match table item_size
Return values
0 error
1 ok
Definition at line 153 of file util-rohash.c.
References ROHashTable_::item_size, ROHashTable_::locked, next, SC_ERR_HASH_TABLE_INIT, SCLogError, SCMalloc, and TAILQ_INSERT_TAIL.
Referenced by LoadHashTable().
ROHashLookup()
void * ROHashLookup (ROHashTable * table, void * data, uint16_t size)
Return values
NULL not found
ptr found
Definition at line 114 of file util-rohash.c.
References ROHashTableOffsets_::cnt, ROHashTable_::data, ROHashTable_::hash_bits, hashmask, hashword(), ROHashTable_::item_size, ROHashTableOffsets_::offset, offset, SCMemcmp, and SCReturnPtr.
ROHashMemorySize()
uint32_t ROHashMemorySize (ROHashTable * table)
Definition at line 103 of file util-rohash.c.
References ROHashTable_::hash_bits, hashsize, ROHashTable_::item_size, and ROHashTable_::items.