suricata: /Users/jlu/suricata/src/util-hashlist.c File Reference
util-hashlist.c File Reference
#include "suricata-common.h"
#include "util-hashlist.h"
#include "util-unittest.h"
#include "util-debug.h"
#include "util-memcmp.h"
Functions
HashListTable * HashListTableInit (uint32_t size, uint32_t(*Hash)(struct HashListTable_ *, void *, uint16_t), char(*Compare)(void *, uint16_t, void *, uint16_t), void(*Free)(void *))
void HashListTableFree (HashListTable *ht)
void HashListTablePrint (HashListTable *ht)
int HashListTableAdd (HashListTable *ht, void *data, uint16_t datalen)
int HashListTableRemove (HashListTable *ht, void *data, uint16_t datalen)
char HashListTableDefaultCompare (void *data1, uint16_t len1, void *data2, uint16_t len2)
void * HashListTableLookup (HashListTable *ht, void *data, uint16_t datalen)
uint32_t HashListTableGenericHash (HashListTable *ht, void *data, uint16_t datalen)
HashListTableBucket * HashListTableGetListHead (HashListTable *ht)
void HashListTableRegisterTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Chained hash table implementation
The 'Free' pointer can be used to have the API free your hashed data. If it's NULL it's the callers responsebility
Definition in file util-hashlist.c.
Function Documentation
HashListTableAdd()
int HashListTableAdd (HashListTable * ht, void * data, uint16_t datalen)
Definition at line 116 of file util-hashlist.c.
References HashListTable_::array, HashListTableBucket_::bucknext, HashListTableBucket_::data, HashListTable_::Hash, HashListTable_::listhead, HashListTableBucket_::listnext, HashListTableBucket_::listprev, HashListTable_::listtail, SCLogDebug, SCMalloc, HashListTableBucket_::size, and unlikely.
Referenced by DetectEngineBufferTypeGetByIdTransforms(), DetectPortHashAdd(), and SigGroupHeadHashAdd().
HashListTableDefaultCompare()
char HashListTableDefaultCompare (void * data1, uint16_t len1, void * data2, uint16_t len2)
Definition at line 237 of file util-hashlist.c.
References SCMemcmp.
Referenced by HashListTableInit().
HashListTableFree()
void HashListTableFree (HashListTable * ht)
Definition at line 82 of file util-hashlist.c.
References HashListTable_::array, HashListTable_::array_size, HashListTableBucket_::bucknext, HashListTableBucket_::data, HashListTable_::Free, and SCFree.
Referenced by DetectAddressMapFree(), DetectParseDupSigHashFree(), DetectPortHashFree(), DumpPatterns(), MpmStoreFree(), PrefilterDeinit(), and SigGroupHeadHashFree().
HashListTableGenericHash()
uint32_t HashListTableGenericHash (HashListTable * ht, void * data, uint16_t datalen)
Definition at line 273 of file util-hashlist.c.
References HashListTable_::array_size.
HashListTableGetListHead()
HashListTableBucket * HashListTableGetListHead (HashListTable * ht)
Definition at line 290 of file util-hashlist.c.
References HashListTable_::listhead.
Referenced by DumpPatterns(), FeatureDump(), and MpmStoreReportStats().
HashListTableInit()
HashListTable * HashListTableInit (uint32_t size, uint32_t(*)(struct HashListTable_ *, void *, uint16_t) Hash, char(*)(void *, uint16_t, void *, uint16_t) Compare, void(*)(void *) Free)
Definition at line 35 of file util-hashlist.c.
References HashListTable_::array, HashListTable_::array_size, HashListTable_::Compare, HashListTable_::Free, HashListTable_::Hash, HashListTableDefaultCompare(), HashListTable_::listhead, HashListTable_::listtail, SCFree, SCMalloc, and unlikely.
Referenced by DetectAddressMapInit(), DetectParseDupSigHashInit(), DetectPortHashInit(), DetectRegisterThreadCtxFuncs(), EngineAnalysisAddAllRulePatterns(), MpmStoreInit(), PrefilterInit(), and SigGroupHeadHashInit().
HashListTableLookup()
void * HashListTableLookup (HashListTable * ht, void * data, uint16_t datalen)
Definition at line 248 of file util-hashlist.c.
References HashListTable_::array, HashListTableBucket_::bucknext, HashListTable_::Compare, HashListTableBucket_::data, HashListTable_::Hash, SCLogDebug, and HashListTableBucket_::size.
Referenced by DetectEngineBufferTypeGetById(), DetectEngineBufferTypeGetByIdTransforms(), DetectPortHashLookup(), SigGroupHeadHashLookup(), VarNameStoreLookupById(), and VarNameStoreLookupByName().
HashListTablePrint()
void HashListTablePrint (HashListTable * ht)
Definition at line 108 of file util-hashlist.c.
References HashListTable_::array_size, and HashListTable_::Hash.
HashListTableRegisterTests()
void HashListTableRegisterTests (void)
Definition at line 501 of file util-hashlist.c.
References UtRegisterTest().
HashListTableRemove()
int HashListTableRemove (HashListTable * ht, void * data, uint16_t datalen)
Definition at line 157 of file util-hashlist.c.
References HashListTable_::array, HashListTableBucket_::bucknext, HashListTable_::Compare, HashListTableBucket_::data, HashListTable_::Free, HashListTable_::Hash, HashListTable_::listhead, HashListTableBucket_::listnext, HashListTableBucket_::listprev, HashListTable_::listtail, SCFree, SCLogDebug, and HashListTableBucket_::size.
Referenced by DetectUnregisterThreadCtxFuncs(), and SigGroupHeadHashRemove().