suricata: /Users/jlu/suricata/src/util-napatech.h File Reference
util-napatech.h File Reference
#include <nt.h>
Data Structures
struct NapatechPacketVars_
struct NapatechStreamConfig_
struct NapatechCurrentStats_
Macros
#define MAX_HOSTBUFFER 4
#define MAX_STREAMS 256
#define MAX_PORTS 80
#define MAX_ADAPTERS 8
#define HB_HIGHWATER 2048
#define NAPATECH_ERROR(err_type, status)
#define NAPATECH_NTPL_ERROR(ntpl_cmd, ntpl_info, status)
#define NAPATECH_DEBUG(...)
#define NAPATECH_PRINTIP(a)
Typedefs
typedef struct NapatechPacketVars_ NapatechPacketVars
typedef struct NapatechStreamConfig_ NapatechStreamConfig
typedef struct NapatechCurrentStats_ NapatechCurrentStats
Functions
void NapatechStartStats (void)
NapatechCurrentStats NapatechGetCurrentStats (uint16_t id)
int NapatechGetStreamConfig (NapatechStreamConfig stream_config[])
Reads and parses the stream configuration defined in the config file.
bool NapatechSetupNuma (uint32_t stream, uint32_t numa)
uint32_t NapatechSetupTraffic (uint32_t first_stream, uint32_t last_stream)
uint32_t NapatechDeleteFilters (void)
Detailed Description
Author
Phil Young py@na.nosp@m.pate.nosp@m.ch.co.nosp@m.m
Definition in file util-napatech.h.
Macro Definition Documentation
HB_HIGHWATER
#define HB_HIGHWATER 2048
Definition at line 61 of file util-napatech.h.
MAX_ADAPTERS
#define MAX_ADAPTERS 8
Definition at line 60 of file util-napatech.h.
MAX_HOSTBUFFER
#define MAX_HOSTBUFFER 4
Definition at line 57 of file util-napatech.h.
MAX_PORTS
#define MAX_PORTS 80
Definition at line 59 of file util-napatech.h.
MAX_STREAMS
#define MAX_STREAMS 256
Definition at line 58 of file util-napatech.h.
NAPATECH_DEBUG
#define NAPATECH_DEBUG (...)
Definition at line 96 of file util-napatech.h.
NAPATECH_ERROR
#define NAPATECH_ERROR (err_type, status)
Value:
    {  \
    char errorBuffer[1024]; \
    NT_ExplainError((status), errorBuffer, sizeof (errorBuffer) - 1); \
    SCLogError((err_type), "Napatech Error: %s", errorBuffer);   \
    }
Definition at line 65 of file util-napatech.h.
NAPATECH_NTPL_ERROR
#define NAPATECH_NTPL_ERROR (ntpl_cmd, ntpl_info, status)
Value:
    { \
    char errorBuffer[1024]; \
    NT_ExplainError(status, errorBuffer, sizeof (errorBuffer) - 1); \
    SCLogError(SC_ERR_NAPATECH_STREAMS_REGISTER_FAILED, \
               "     NTPL failed: %s", errorBuffer); \
    SCLogError(SC_ERR_NAPATECH_STREAMS_REGISTER_FAILED, \
               "         cmd: %s", ntpl_cmd); \
    if (strncmp(ntpl_info.u.errorData.errBuffer[0], "", 256) != 0) \
        SCLogError(SC_ERR_NAPATECH_STREAMS_REGISTER_FAILED, \
                   "         %s", ntpl_info.u.errorData.errBuffer[0]); \
    if (strncmp(ntpl_info.u.errorData.errBuffer[1], "", 256) != 0) \
        SCLogError(SC_ERR_NAPATECH_STREAMS_REGISTER_FAILED, \
                   "         %s", ntpl_info.u.errorData.errBuffer[1]); \
    if (strncmp(ntpl_info.u.errorData.errBuffer[2], "", 256) != 0) \
        SCLogError(SC_ERR_NAPATECH_STREAMS_REGISTER_FAILED, \
                   "         %s", ntpl_info.u.errorData.errBuffer[2]); \
}
Definition at line 71 of file util-napatech.h.
NAPATECH_PRINTIP
#define NAPATECH_PRINTIP (a)
Definition at line 97 of file util-napatech.h.
Typedef Documentation
NapatechCurrentStats
typedef struct NapatechCurrentStats_ NapatechCurrentStats
NapatechPacketVars
typedef struct NapatechPacketVars_ NapatechPacketVars
NapatechStreamConfig
typedef struct NapatechStreamConfig_ NapatechStreamConfig
Function Documentation
NapatechDeleteFilters()
uint32_t NapatechDeleteFilters (void)
Definition at line 1338 of file util-napatech.c.
References NAPATECH_ERROR, NAPATECH_NTPL_ERROR, and SC_ERR_NAPATECH_STREAMS_REGISTER_FAILED.
NapatechGetCurrentStats()
NapatechCurrentStats NapatechGetCurrentStats (uint16_t id)
Definition at line 193 of file util-napatech.c.
References current_stats.
Referenced by NapatechStreamThreadExitStats().
NapatechGetStreamConfig()
int NapatechGetStreamConfig (NapatechStreamConfig stream_config[])
Reads and parses the stream configuration defined in the config file.
Parameters
stream_config - array to be filled in with active stream info.
Returns
the number of streams configured or -1 if an error occurred
Definition at line 804 of file util-napatech.c.
References ConfGetBool(), MAX_STREAMS, NAPATECH_ERROR, NapatechIsAutoConfigEnabled(), SC_ERR_NAPATECH_INIT_FAILED, SC_ERR_NAPATECH_STREAMS_REGISTER_FAILED, SCLogError, and stream_config.
NapatechSetupNuma()
bool NapatechSetupNuma (uint32_t stream, uint32_t numa)
Definition at line 1227 of file util-napatech.c.
References NAPATECH_ERROR, NAPATECH_NTPL_ERROR, and SC_ERR_NAPATECH_STREAMS_REGISTER_FAILED.
NapatechSetupTraffic()
uint32_t NapatechSetupTraffic (uint32_t first_stream, uint32_t last_stream)
Definition at line 1365 of file util-napatech.c.
NapatechStartStats()
void NapatechStartStats (void)
Definition at line 1184 of file util-napatech.c.
References TmThreadCreate().