suricata: /Users/jlu/suricata/src/util-mpm-ac.c File Reference
util-mpm-ac.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-build.h"
#include "conf.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-memcmp.h"
#include "util-mpm-ac.h"
#include "util-memcpy.h"
#include "util-validate.h"
Data Structures
struct StateQueue_
Helper structure used by AC during state table creation.
Macros
#define SC_AC_FAIL (-1)
#define STATE_QUEUE_CONTAINER_SIZE 65536
#define AC_CASE_MASK 0x80000000
#define AC_PID_MASK 0x7FFFFFFF
#define AC_CASE_BIT 31
Typedefs
typedef struct StateQueue_ StateQueue
Helper structure used by AC during state table creation.
Functions
void SCACInitCtx (MpmCtx *mpm_ctx)
Initialize the AC context.
void SCACInitThreadCtx (MpmCtx *mpm_ctx, MpmThreadCtx *mpm_thread_ctx)
Init the mpm thread context.
void SCACDestroyCtx (MpmCtx *mpm_ctx)
Destroy the mpm context.
void SCACDestroyThreadCtx (MpmCtx *mpm_ctx, MpmThreadCtx *mpm_thread_ctx)
Destroy the mpm thread context.
int SCACAddPatternCI (MpmCtx *mpm_ctx, uint8_t *pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Add a case insensitive pattern. Although we have different calls for adding case sensitive and insensitive patterns, we make a single call for either case. No special treatment for either case.
int SCACAddPatternCS (MpmCtx *mpm_ctx, uint8_t *pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Add a case sensitive pattern. Although we have different calls for adding case sensitive and insensitive patterns, we make a single call for either case. No special treatment for either case.
int SCACPreparePatterns (MpmCtx *mpm_ctx)
Process the patterns added to the mpm, and create the internal tables.
uint32_t SCACSearch (const MpmCtx *mpm_ctx, MpmThreadCtx *mpm_thread_ctx, PrefilterRuleStore *pmq, const uint8_t *buf, uint32_t buflen)
The aho corasick search function.
void SCACPrintInfo (MpmCtx *mpm_ctx)
void SCACPrintSearchStats (MpmThreadCtx *mpm_thread_ctx)
void SCACRegisterTests (void)
void MpmACRegister (void)
Register the aho-corasick mpm.
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
    First iteration of aho-corasick MPM from -
    Efficient String Matching: An Aid to Bibliographic Search
    Alfred V. Aho and Margaret J. Corasick
    - Uses the delta table for calculating transitions, instead of having
      separate goto and failure transitions.
    - If we cross 2 ** 16 states, we use 4 bytes in the transition table
      to hold each state, otherwise we use 2 bytes.
    - This version of the MPM is heavy on memory, but it performs well.
      If you can fit the ruleset with this mpm on your box without hitting
      swap, this is the MPM to go for.
Todo:
Do a proper analyis of our existing MPMs and suggest a good one based on the pattern distribution and the expected traffic(say http).
Tried out loop unrolling without any perf increase. Need to dig deeper.
Irrespective of whether we cross 2 ** 16 states or not,shift to using uint32_t for state type, so that we can integrate it's status as a final state or not in the topmost byte. We are already doing it if state_count is > 2 ** 16.
Test case-senstive patterns if they have any ascii chars. If they don't treat them as nocase.
Carry out other optimizations we are working on. hashes, compression.
Definition in file util-mpm-ac.c.
Macro Definition Documentation
AC_CASE_BIT
#define AC_CASE_BIT 31
Definition at line 87 of file util-mpm-ac.c.
AC_CASE_MASK
#define AC_CASE_MASK 0x80000000
Definition at line 85 of file util-mpm-ac.c.
AC_PID_MASK
#define AC_PID_MASK 0x7FFFFFFF
Definition at line 86 of file util-mpm-ac.c.
SC_AC_FAIL
#define SC_AC_FAIL (-1)
Definition at line 81 of file util-mpm-ac.c.
STATE_QUEUE_CONTAINER_SIZE
#define STATE_QUEUE_CONTAINER_SIZE 65536
Definition at line 83 of file util-mpm-ac.c.
Typedef Documentation
StateQueue
typedef struct StateQueue_ StateQueue
Helper structure used by AC during state table creation.
Function Documentation
MpmACRegister()
void MpmACRegister (void)
Register the aho-corasick mpm.
Definition at line 1233 of file util-mpm-ac.c.
References MpmTableElmt_::AddPattern, MpmTableElmt_::AddPatternNocase, MpmTableElmt_::DestroyCtx, MpmTableElmt_::DestroyThreadCtx, MpmTableElmt_::InitCtx, MpmTableElmt_::InitThreadCtx, MPM_AC, mpm_table, MpmTableElmt_::name, MpmTableElmt_::Prepare, MpmTableElmt_::PrintCtx, MpmTableElmt_::PrintThreadCtx, MpmTableElmt_::RegisterUnittests, SCACAddPatternCI(), SCACAddPatternCS(), SCACDestroyCtx(), SCACDestroyThreadCtx(), SCACInitCtx(), SCACInitThreadCtx(), SCACPreparePatterns(), SCACPrintInfo(), SCACPrintSearchStats(), SCACRegisterTests(), SCACSearch(), and MpmTableElmt_::Search.
Referenced by MpmTableSetup().
SCACAddPatternCI()
int SCACAddPatternCI (MpmCtx * mpm_ctx, uint8_t * pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Add a case insensitive pattern. Although we have different calls for adding case sensitive and insensitive patterns, we make a single call for either case. No special treatment for either case.
Parameters
mpm_ctx Pointer to the mpm context.
pat The pattern to add.
patnen The pattern length.
offset Ignored.
depth Ignored.
pid The pattern id.
sid Ignored.
flags Flags associated with this pattern.
Return values
0 On success.
-1 On failure.
Definition at line 1161 of file util-mpm-ac.c.
References flags, MPM_PATTERN_FLAG_NOCASE, MpmAddPattern(), and offset.
Referenced by MpmACRegister().
SCACAddPatternCS()
int SCACAddPatternCS (MpmCtx * mpm_ctx, uint8_t * pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Add a case sensitive pattern. Although we have different calls for adding case sensitive and insensitive patterns, we make a single call for either case. No special treatment for either case.
Parameters
mpm_ctx Pointer to the mpm context.
pat The pattern to add.
patnen The pattern length.
offset Ignored.
depth Ignored.
pid The pattern id.
sid Ignored.
flags Flags associated with this pattern.
Return values
0 On success.
-1 On failure.
Definition at line 1186 of file util-mpm-ac.c.
References flags, MpmAddPattern(), and offset.
Referenced by MpmACRegister().
SCACDestroyCtx()
void SCACDestroyCtx (MpmCtx * mpm_ctx)
Destroy the mpm context.
Parameters
mpm_ctx Pointer to the mpm context.
Definition at line 939 of file util-mpm-ac.c.
References SCACPatternList_::cs, MpmCtx_::ctx, MpmCtx_::init_hash, MpmCtx_::max_pat_id, MpmCtx_::memory_cnt, MpmCtx_::memory_size, MPM_INIT_HASH_SIZE, MpmFreePattern(), SCACCtx_::output_table, SCACCtx_::parray, MpmCtx_::pattern_cnt, SCACCtx_::pid_pat_list, SCACOutputTable_::pids, SC_AC_STATE_TYPE_U16, SC_AC_STATE_TYPE_U32, SCFree, SCACPatternList_::sids, SCACCtx_::state_count, SCACCtx_::state_table_u16, and SCACCtx_::state_table_u32.
Referenced by MpmACRegister().
SCACDestroyThreadCtx()
void SCACDestroyThreadCtx (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx)
Destroy the mpm thread context.
Parameters
mpm_ctx Pointer to the mpm context.
mpm_thread_ctx Pointer to the mpm thread context.
Definition at line 920 of file util-mpm-ac.c.
References MpmThreadCtx_::ctx, MpmThreadCtx_::memory_cnt, MpmThreadCtx_::memory_size, SCACPrintSearchStats(), and SCFree.
Referenced by MpmACRegister().
SCACInitCtx()
void SCACInitCtx (MpmCtx * mpm_ctx)
Initialize the AC context.
Parameters
mpm_ctx Mpm context.
Definition at line 886 of file util-mpm-ac.c.
References MpmCtx_::ctx, MpmCtx_::init_hash, MpmCtx_::memory_cnt, MpmCtx_::memory_size, MPM_INIT_HASH_SIZE, and SCMalloc.
Referenced by MpmACRegister().
SCACInitThreadCtx()
void SCACInitThreadCtx (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx)
Init the mpm thread context.
Parameters
mpm_ctx Pointer to the mpm context.
mpm_thread_ctx Pointer to the mpm thread context.
matchsize We don't need this.
Definition at line 866 of file util-mpm-ac.c.
References MpmThreadCtx_::ctx, MpmThreadCtx_::memory_cnt, MpmThreadCtx_::memory_size, and SCMalloc.
Referenced by MpmACRegister().
SCACPreparePatterns()
int SCACPreparePatterns (MpmCtx * mpm_ctx)
Process the patterns added to the mpm, and create the internal tables.
Parameters
mpm_ctx Pointer to the mpm context.
Definition at line 770 of file util-mpm-ac.c.
References SCACPatternList_::cs, MpmCtx_::ctx, SCACPatternList_::depth, MpmPattern_::depth, FatalError, MpmPattern_::flags, MpmPattern_::id, MpmCtx_::init_hash, MpmPattern_::len, MpmCtx_::max_pat_id, MpmCtx_::memory_cnt, MpmCtx_::memory_size, MPM_INIT_HASH_SIZE, MPM_PATTERN_FLAG_NOCASE, MpmPattern_::next, SCACPatternList_::offset, MpmPattern_::offset, MpmPattern_::original_pat, SCACCtx_::parray, SCACPatternList_::patlen, MpmCtx_::pattern_cnt, SCACCtx_::pid_pat_list, SC_ERR_FATAL, SCFree, SCLogDebug, SCMalloc, SCACPatternList_::sids, MpmPattern_::sids, SCACPatternList_::sids_size, MpmPattern_::sids_size, and SCACCtx_::single_state_size.
Referenced by MpmACRegister().
SCACPrintInfo()
void SCACPrintInfo (MpmCtx * mpm_ctx)
Definition at line 1206 of file util-mpm-ac.c.
References MpmCtx_::ctx, MpmCtx_::maxlen, MpmCtx_::memory_cnt, MpmCtx_::memory_size, MpmCtx_::minlen, MpmCtx_::pattern_cnt, and SCACCtx_::state_count.
Referenced by MpmACRegister().
SCACPrintSearchStats()
void SCACPrintSearchStats (MpmThreadCtx * mpm_thread_ctx)
Definition at line 1193 of file util-mpm-ac.c.
References MpmThreadCtx_::ctx, SCACThreadCtx_::total_calls, and SCACThreadCtx_::total_matches.
Referenced by MpmACRegister(), and SCACDestroyThreadCtx().
SCACRegisterTests()
void SCACRegisterTests (void)
Definition at line 2290 of file util-mpm-ac.c.
References UtRegisterTest().
Referenced by MpmACRegister().
SCACSearch()
uint32_t SCACSearch (const MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx, PrefilterRuleStore * pmq, const uint8_t * buf, uint32_t buflen)
The aho corasick search function.
Parameters
mpm_ctx Pointer to the mpm context.
mpm_thread_ctx Pointer to the mpm thread context.
pmq Pointer to the Pattern Matcher Queue to hold search matches.
buf Buffer to be searched.
buflen Buffer length.
Return values
matches Match count.
Definition at line 1023 of file util-mpm-ac.c.
References AC_CASE_MASK, AC_PID_MASK, SCACPatternList_::cs, MpmCtx_::ctx, SCACPatternList_::depth, SCACOutputTable_::no_of_entries, SCACPatternList_::offset, offset, SCACCtx_::output_table, SCACPatternList_::patlen, SCACCtx_::pattern_id_bitarray_size, SCACCtx_::pid_pat_list, SCACOutputTable_::pids, SC_AC_STATE_TYPE_U16, SCMemcmp, SCACCtx_::state_count, SCACCtx_::state_table_u16, and u8_tolower.
Referenced by MpmACRegister().