suricata: /Users/jlu/suricata/src/util-datalink.c File Reference
util-datalink.c File Reference
#include "suricata-common.h"
#include "conf.h"
#include "util-datalink.h"
Functions
void DatalinkSetGlobalType (int datalink)
int DatalinkGetGlobalType (void)
bool DatalinkHasMultipleValues (void)
Variables
int g_datalink_value = LINKTYPE_NULL
int g_datalink_is_multiple = 0
Function Documentation
DatalinkGetGlobalType()
int DatalinkGetGlobalType (void) inline
Definition at line 36 of file util-datalink.c.
References g_datalink_value.
DatalinkHasMultipleValues()
bool DatalinkHasMultipleValues (void)
Definition at line 41 of file util-datalink.c.
References g_datalink_is_multiple.
DatalinkSetGlobalType()
void DatalinkSetGlobalType (int datalink)
Definition at line 25 of file util-datalink.c.
References g_datalink_is_multiple, g_datalink_value, and LINKTYPE_NULL.
Referenced by InitPcapFile(), NapatechStreamThreadInit(), ReceiveErfDagThreadInit(), and ReceiveErfFileThreadInit().
Variable Documentation
g_datalink_is_multiple
int g_datalink_is_multiple = 0
Definition at line 23 of file util-datalink.c.
Referenced by DatalinkHasMultipleValues(), and DatalinkSetGlobalType().
g_datalink_value
int g_datalink_value = LINKTYPE_NULL
Definition at line 22 of file util-datalink.c.
Referenced by DatalinkGetGlobalType(), and DatalinkSetGlobalType().