suricata: /Users/jlu/suricata/src/util-strptime.c File Reference
util-strptime.c File Reference
#include "suricata-common.h"
#include <ctype.h>
#include <locale.h>
#include <string.h>
#include <time.h>
#include <stdint.h>
Macros
#define _ctloc(x) (_CurrentTimeLocale->x)
#define ALT_E 0x01
#define ALT_O 0x02
#define LEGAL_ALT(x) { if (alt_format & ~(x)) return NULL; }
#define TIME_MAX INT64_MAX
Functions
char * strptime (const char *buf, const char *fmt, struct tm *tm)
Macro Definition Documentation
_ctloc
#define _ctloc (x) (_CurrentTimeLocale->x)
Definition at line 56 of file util-strptime.c.
ALT_E
#define ALT_E 0x01
Definition at line 62 of file util-strptime.c.
ALT_O
#define ALT_O 0x02
Definition at line 63 of file util-strptime.c.
LEGAL_ALT
#define LEGAL_ALT (x) { if (alt_format & ~(x)) return NULL; }
Definition at line 64 of file util-strptime.c.
TIME_MAX
#define TIME_MAX INT64_MAX
Function Documentation
strptime()
char * strptime (const char * buf, const char * fmt, struct tm * tm)
Definition at line 97 of file util-strptime.c.
References ALT_E, ALT_O, LEGAL_ALT, and strptime().
Referenced by SCStringPatternToTime(), and strptime().