suricata: /Users/jlu/suricata/src/util-logopenfile.h File Reference
util-logopenfile.h File Reference
#include "conf.h"
#include "util-buffer.h"
#include "suricata-plugin.h"
Data Structures
struct SyslogSetup_
struct LogThreadedFileCtx_
struct LogFilePluginCtx_
struct LogFileCtx_
Macros
#define LOGFILE_RECONN_MIN_TIME 500
#define LOGFILE_HEADER_WRITTEN 0x01
#define LOGFILE_ALERTS_PRINTED 0x02
#define LOGFILE_ROTATE_INTERVAL 0x04
Typedefs
typedef struct SyslogSetup_ SyslogSetup
typedef struct LogThreadedFileCtx_ LogThreadedFileCtx
typedef struct LogFilePluginCtx_ LogFilePluginCtx
typedef struct LogFileCtx_ LogFileCtx
Enumerations
enum LogFileType {
LOGFILE_TYPE_FILE , LOGFILE_TYPE_UNIX_DGRAM , LOGFILE_TYPE_UNIX_STREAM , LOGFILE_TYPE_REDIS ,
LOGFILE_TYPE_PLUGIN , LOGFILE_TYPE_NOTSET
}
Functions
LogFileCtx * LogFileNewCtx (void)
LogFileNewCtx() Get a new LogFileCtx.
int LogFileFreeCtx (LogFileCtx *)
LogFileFreeCtx() Destroy a LogFileCtx (Close the file and free memory)
int LogFileWrite (LogFileCtx *file_ctx, MemBuffer *buffer)
LogFileCtx * LogFileEnsureExists (LogFileCtx *lf_ctx, int thread_id)
LogFileEnsureExists() Ensure a log file context for the thread exists.
int SCConfLogOpenGeneric (ConfNode *conf, LogFileCtx *, const char *, int)
open a generic output "log file", which may be a regular file or a socket
int SCConfLogReopen (LogFileCtx *)
Reopen a regular log file with the side-affect of truncating it.
bool SCLogOpenThreadedFile (const char *log_path, const char *append, LogFileCtx *parent_ctx, int slot_count)
Detailed Description
Author
Mike Pomraning mpomr.nosp@m.anin.nosp@m.g@qua.nosp@m.lys..nosp@m.com
Definition in file util-logopenfile.h.
Macro Definition Documentation
LOGFILE_ALERTS_PRINTED
#define LOGFILE_ALERTS_PRINTED 0x02
Definition at line 162 of file util-logopenfile.h.
LOGFILE_HEADER_WRITTEN
#define LOGFILE_HEADER_WRITTEN 0x01
Definition at line 161 of file util-logopenfile.h.
LOGFILE_RECONN_MIN_TIME
#define LOGFILE_RECONN_MIN_TIME 500
Definition at line 158 of file util-logopenfile.h.
LOGFILE_ROTATE_INTERVAL
#define LOGFILE_ROTATE_INTERVAL 0x04
Definition at line 163 of file util-logopenfile.h.
Typedef Documentation
LogFileCtx
typedef struct LogFileCtx_ LogFileCtx
Global structure for Output Context
LogFilePluginCtx
typedef struct LogFilePluginCtx_ LogFilePluginCtx
LogThreadedFileCtx
typedef struct LogThreadedFileCtx_ LogThreadedFileCtx
SyslogSetup
typedef struct SyslogSetup_ SyslogSetup
Enumeration Type Documentation
LogFileType
enum LogFileType
Enumerator
LOGFILE_TYPE_FILE
LOGFILE_TYPE_UNIX_DGRAM
LOGFILE_TYPE_UNIX_STREAM
LOGFILE_TYPE_REDIS
LOGFILE_TYPE_PLUGIN
LOGFILE_TYPE_NOTSET
Definition at line 36 of file util-logopenfile.h.
Function Documentation
LogFileEnsureExists()
LogFileCtx * LogFileEnsureExists (LogFileCtx * parent_ctx, int thread_id)
LogFileEnsureExists() Ensure a log file context for the thread exists.
Parameters
parent_ctx
thread_id
Return values
LogFileCtx * pointer if successful; NULL otherwise
Definition at line 662 of file util-logopenfile.c.
References LogThreadedFileCtx_::lf_slots, LogThreadedFileCtx_::mutex, SCLogDebug, SCMutexLock, LogFileCtx_::threaded, and LogFileCtx_::threads.
Referenced by CreateEveThreadCtx(), and JsonLogThreadInit().
LogFileFreeCtx()
int LogFileFreeCtx (LogFileCtx * lf_ctx)
LogFileFreeCtx() Destroy a LogFileCtx (Close the file and free memory)
Parameters
lf_ctx pointer to the OutputCtx
Return values
int 1 if successful, 0 if error
Definition at line 828 of file util-logopenfile.c.
References LogThreadedFileCtx_::append, BUG_ON, LogFileCtx_::Close, SCEveFileType_::Deinit, LogFileCtx_::filename, LogFileCtx_::fp, LogFileCtx_::fp_mutex, LogFileCtx_::id, LogFilePluginCtx_::init_data, LogThreadedFileCtx_::lf_slots, LOGFILE_TYPE_PLUGIN, LogThreadedFileCtx_::mutex, OutputUnregisterFileRotationFlag(), LogFileCtx_::parent, LogFilePluginCtx_::plugin, LogFileCtx_::plugin, LogFileCtx_::prefix, LogFileCtx_::prefix_len, LogFileCtx_::rotation_flag, SCFree, SCMutexDestroy, SCMutexLock, SCMutexUnlock, SCReturnInt, LogFileCtx_::sensor_name, LogThreadedFileCtx_::slot_count, LogFilePluginCtx_::thread_data, SCEveFileType_::ThreadDeinit, LogFileCtx_::threaded, LogFileCtx_::threads, and LogFileCtx_::type.
Referenced by AlertFastLogInitCtx(), LogHttpLogInitCtx(), and LogTcpDataLogInitCtx().
LogFileNewCtx()
LogFileCtx * LogFileNewCtx (void)
LogFileNewCtx() Get a new LogFileCtx.
Return values
LogFileCtx * pointer if successful, NULL if error
Definition at line 643 of file util-logopenfile.c.
References SCCalloc, and LogFileCtx_::Write.
Referenced by AlertFastLogInitCtx(), LogHttpLogInitCtx(), LogTcpDataLogInitCtx(), and OutputJsonInitCtx().
LogFileWrite()
int LogFileWrite (LogFileCtx * file_ctx, MemBuffer * buffer)
Definition at line 896 of file util-logopenfile.c.
References LogFileCtx_::fp_mutex, LogFilePluginCtx_::init_data, LOGFILE_TYPE_FILE, LOGFILE_TYPE_PLUGIN, LOGFILE_TYPE_REDIS, LOGFILE_TYPE_UNIX_DGRAM, LOGFILE_TYPE_UNIX_STREAM, MEMBUFFER_BUFFER, MEMBUFFER_OFFSET, MemBufferWriteString, LogFilePluginCtx_::plugin, LogFileCtx_::plugin, SCMutexLock, SCMutexUnlock, LogFilePluginCtx_::thread_data, LogFileCtx_::type, LogFileCtx_::Write, and SCEveFileType_::Write.
Referenced by OutputJSONBuffer(), and OutputJsonBuilderBuffer().
SCConfLogOpenGeneric()
int SCConfLogOpenGeneric (ConfNode * conf, LogFileCtx * log_ctx, const char * default_filename, int rotate)
open a generic output "log file", which may be a regular file or a socket
Parameters
conf ConfNode structure for the output section in question
log_ctx Log file context allocated by caller
default_filename Default name of file to open, if not specified in ConfNode
rotate Register the file for rotation in HUP.
Return values
0 on success
-1 on error
Definition at line 431 of file util-logopenfile.c.
Referenced by AlertFastLogInitCtx(), LogHttpLogInitCtx(), and LogTcpDataLogInitCtx().
SCConfLogReopen()
int SCConfLogReopen (LogFileCtx * log_ctx)
Reopen a regular log file with the side-affect of truncating it.
This is useful to clear the log file and start a new one, or to re-open the file after its been moved by something external (eg. logrotate).
Definition at line 612 of file util-logopenfile.c.
References LogFileCtx_::filename, LogFileCtx_::fp, LogFileCtx_::is_regular, SC_ERR_INVALID_ARGUMENT, SCLogDebug, and SCLogWarning.
SCLogOpenThreadedFile()
bool SCLogOpenThreadedFile (const char * log_path, const char * append, LogFileCtx * parent_ctx, int slot_count)
Definition at line 327 of file util-logopenfile.c.