suricata: /Users/jlu/suricata/src/util-print.h File Reference
util-print.h File Reference
Macros
#define PrintBufferData(buf, buf_offset_ptr, buf_size, ...)
Functions
void PrintBufferRawLineHex (char *, int *, int, const uint8_t *, uint32_t)
print a buffer as hex on a single line
void PrintRawUriFp (FILE *, uint8_t *, uint32_t)
void PrintRawUriBuf (char *, uint32_t *, uint32_t, uint8_t *, uint32_t)
void PrintRawJsonFp (FILE *, uint8_t *, uint32_t)
void PrintRawDataFp (FILE *, const uint8_t *, uint32_t)
void PrintRawDataToBuffer (uint8_t *dst_buf, uint32_t *dst_buf_offset_ptr, uint32_t dst_buf_size, const uint8_t *src_buf, uint32_t src_buf_len)
void PrintStringsToBuffer (uint8_t *dst_buf, uint32_t *dst_buf_offset_ptr, uint32_t dst_buf_size, const uint8_t *src_buf, const uint32_t src_buf_len)
void PrintRawLineHexBuf (char *, uint32_t, const uint8_t *, uint32_t)
print a buffer as hex on a single line in to retbuf buffer
const char * PrintInet (int, const void *, char *, socklen_t)
void PrintHexString (char *str, size_t size, uint8_t *buf, size_t buf_len)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file util-print.h.
Macro Definition Documentation
PrintBufferData
#define PrintBufferData (buf, buf_offset_ptr, buf_size, ...)
Value:
        do {         \
        int cw = snprintf((buf) + *(buf_offset_ptr),                    \
                          (buf_size) - *(buf_offset_ptr),                \
                          __VA_ARGS__);                                 \
        if (cw >= 0) {                                                  \
            if ( (*(buf_offset_ptr) + cw) >= buf_size) {                \
                SCLogDebug("Truncating data write since it exceeded buffer " \
                           "limit of - %"PRIu32"\n", buf_size);         \
                *(buf_offset_ptr) = buf_size - 1;                       \
            } else {                                                    \
                *(buf_offset_ptr) += cw;                                \
            }                                                           \
        }                                                               \
    } while (0)
Definition at line 29 of file util-print.h.
Function Documentation
PrintBufferRawLineHex()
void PrintBufferRawLineHex (char * nbuf, int * offset, int max_size, const uint8_t * buf, uint32_t buflen)
print a buffer as hex on a single line
Prints in the format "00 AA BB"
Parameters
nbuf buffer into which the output is written
offset of where to start writting into the buffer
max_size the size of the output buffer
buf buffer to print from
buflen length of the input buffer
Definition at line 44 of file util-print.c.
References offset, and PrintBufferData.
Referenced by AlertFastLogger().
PrintHexString()
void PrintHexString (char * str, size_t size, uint8_t * buf, size_t buf_len)
Definition at line 298 of file util-print.c.
References DEBUG_VALIDATE_BUG_ON, and str.
PrintInet()
const char * PrintInet (int af, const void * src, char * dst, socklen_t size)
Definition at line 274 of file util-print.c.
References af, dst, and src.
Referenced by AddressDebugPrint(), AlertFastLogger(), JsonAddrInfoInit(), SCRadixAddKeyIPV4String(), SCRadixAddKeyIPV6String(), and TLSGetIPInformations().
PrintRawDataFp()
void PrintRawDataFp (FILE * fp, const uint8_t * buf, uint32_t buflen)
Definition at line 143 of file util-print.c.
Referenced by DetectBase64DecodeDoMatch(), HtpBodyPrint(), and StreamingBufferCompareRawData().
PrintRawDataToBuffer()
void PrintRawDataToBuffer (uint8_t * dst_buf, uint32_t * dst_buf_offset_ptr, uint32_t dst_buf_size, const uint8_t * src_buf, uint32_t src_buf_len)
Definition at line 181 of file util-print.c.
References PrintBufferData.
PrintRawJsonFp()
void PrintRawJsonFp (FILE * fp, uint8_t * buf, uint32_t buflen)
Definition at line 73 of file util-print.c.
References BUFFER_LENGTH, offset, and PrintBufferData.
PrintRawLineHexBuf()
void PrintRawLineHexBuf (char * retbuf, uint32_t retbuflen, const uint8_t * buf, uint32_t buflen)
print a buffer as hex on a single line in to retbuf buffer
Prints in the format "00 AA BB"
Parameters
retbuf pointer to the buffer which will have the result
rebuflen length of the buffer
buf buffer to print from
buflen length of the input buffer
Definition at line 63 of file util-print.c.
References offset, and PrintBufferData.
PrintRawUriBuf()
void PrintRawUriBuf (char * retbuf, uint32_t * offset, uint32_t retbuflen, uint8_t * buf, uint32_t buflen)
Definition at line 120 of file util-print.c.
References offset, and PrintBufferData.
Referenced by LogCustomFormatWriteTimestamp().
PrintRawUriFp()
void PrintRawUriFp (FILE * fp, uint8_t * buf, uint32_t buflen)
Definition at line 95 of file util-print.c.
References BUFFER_LENGTH, offset, and PrintBufferData.
PrintStringsToBuffer()
void PrintStringsToBuffer (uint8_t * dst_buf, uint32_t * dst_buf_offset_ptr, uint32_t dst_buf_size, const uint8_t * src_buf, const uint32_t src_buf_len)
Definition at line 230 of file util-print.c.