suricata: /Users/jlu/suricata/src/util-profiling.h File Reference
util-profiling.h File Reference
Macros
#define RULE_PROFILING_START(p)
#define RULE_PROFILING_END(ctx, r, m, p)
#define KEYWORD_PROFILING_SET_LIST(ctx, list)
#define KEYWORD_PROFILING_START
#define KEYWORD_PROFILING_END(ctx, type, m)
#define PACKET_PROFILING_START(p)
#define PACKET_PROFILING_RESTART(p)
#define PACKET_PROFILING_END(p)
#define PACKET_PROFILING_RESET_LOCKS
#define PACKET_PROFILING_COPY_LOCKS(p, id)
#define PACKET_PROFILING_TMM_START(p, id)
#define PACKET_PROFILING_TMM_END(p, id)
#define FLOWWORKER_PROFILING_START(p, id)
#define FLOWWORKER_PROFILING_END(p, id)
#define PACKET_PROFILING_RESET(p)
#define PACKET_PROFILING_APP_START(dp, id)
#define PACKET_PROFILING_APP_END(dp, id)
#define PACKET_PROFILING_APP_PD_START(dp)
#define PACKET_PROFILING_APP_PD_END(dp)
#define PACKET_PROFILING_APP_RESET(dp)
#define PACKET_PROFILING_APP_STORE(dp, p)
#define PACKET_PROFILING_DETECT_START(p, id)
#define PACKET_PROFILING_DETECT_END(p, id)
#define PACKET_PROFILING_LOGGER_START(p, id)
#define PACKET_PROFILING_LOGGER_END(p, id)
#define SGH_PROFILING_RECORD(det_ctx, sgh)
#define PREFILTER_PROFILING_START(det_ctx)
#define PREFILTER_PROFILING_END(ctx, profile_id)
#define PREFILTER_PROFILING_ADD_BYTES(det_ctx, bytes)
Functions
void SCProfilingPrintPacketProfile (Packet *)
void SCProfilingAddPacket (Packet *)
int SCProfileRuleStart (Packet *p)
PktProfiling * SCProfilePacketStart (void)
void SCProfilingRulesGlobalInit (void)
void SCProfilingRuleDestroyCtx (struct SCProfileDetectCtx_ *)
void SCProfilingRuleInitCounters (DetectEngineCtx *)
Register the rule profiling counters.
void SCProfilingRuleUpdateCounter (DetectEngineThreadCtx *, uint16_t, uint64_t, int)
Update a rule counter.
void SCProfilingRuleThreadSetup (struct SCProfileDetectCtx_ *, DetectEngineThreadCtx *)
void SCProfilingRuleThreadCleanup (DetectEngineThreadCtx *)
void SCProfilingKeywordsGlobalInit (void)
void SCProfilingKeywordDestroyCtx (DetectEngineCtx *)
void SCProfilingKeywordInitCounters (DetectEngineCtx *)
Register the keyword profiling counters.
void SCProfilingKeywordUpdateCounter (DetectEngineThreadCtx *det_ctx, int id, uint64_t ticks, int match)
Update a rule counter.
void SCProfilingKeywordThreadSetup (struct SCProfileKeywordDetectCtx_ *, DetectEngineThreadCtx *)
void SCProfilingKeywordThreadCleanup (DetectEngineThreadCtx *)
void SCProfilingPrefilterGlobalInit (void)
void SCProfilingPrefilterDestroyCtx (DetectEngineCtx *)
void SCProfilingPrefilterInitCounters (DetectEngineCtx *)
Register the prefilter profiling counters.
void SCProfilingPrefilterUpdateCounter (DetectEngineThreadCtx *det_ctx, int id, uint64_t ticks, uint64_t bytes, uint64_t bytes_called)
Update a rule counter.
void SCProfilingPrefilterThreadSetup (struct SCProfilePrefilterDetectCtx_ *, DetectEngineThreadCtx *)
void SCProfilingPrefilterThreadCleanup (DetectEngineThreadCtx *)
void SCProfilingSghsGlobalInit (void)
void SCProfilingSghDestroyCtx (DetectEngineCtx *)
void SCProfilingSghInitCounters (DetectEngineCtx *)
Register the keyword profiling counters.
void SCProfilingSghUpdateCounter (DetectEngineThreadCtx *det_ctx, const SigGroupHead *sgh)
Update a rule counter.
void SCProfilingSghThreadSetup (struct SCProfileSghDetectCtx_ *, DetectEngineThreadCtx *)
void SCProfilingSghThreadCleanup (DetectEngineThreadCtx *)
void SCProfilingInit (void)
Initialize profiling.
void SCProfilingDestroy (void)
Free resources used by profiling.
void SCProfilingRegisterTests (void)
void SCProfilingDump (void)
Variables
int profiling_rules_enabled
int profiling_packets_enabled
int profiling_sghs_enabled
thread_local int profiling_rules_entered
int profiling_keyword_enabled
thread_local int profiling_keyword_entered
int profiling_prefilter_enabled
thread_local int profiling_prefilter_entered
Detailed Description
Author
Endace Technology Limited.
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file util-profiling.h.
Macro Definition Documentation
FLOWWORKER_PROFILING_END
#define FLOWWORKER_PROFILING_END (p, id)
Value:
    if (profiling_packets_enabled && (p)->profile != NULL) {        \
        if ((id) < PROFILE_FLOWWORKER_SIZE) {                       \
            (p)->profile->flowworker[(id)].ticks_end = UtilCpuGetTicks();  \
        }                                                           \
    }
Definition at line 171 of file util-profiling.h.
FLOWWORKER_PROFILING_START
#define FLOWWORKER_PROFILING_START (p, id)
Value:
    if (profiling_packets_enabled && (p)->profile != NULL) {        \
        if ((id) < PROFILE_FLOWWORKER_SIZE) {                       \
            (p)->profile->flowworker[(id)].ticks_start = UtilCpuGetTicks();\
        }                                                           \
    }
Definition at line 164 of file util-profiling.h.
KEYWORD_PROFILING_END
#define KEYWORD_PROFILING_END (ctx, type, m)
Value:
    if (profiling_keyword_enabled && profiling_keyword_entered) { \
        profile_keyword_end_ = UtilCpuGetTicks(); \
        SCProfilingKeywordUpdateCounter((ctx),(type),(profile_keyword_end_ - profile_keyword_start_),(m)); \
        profiling_keyword_entered--; \
    }
Definition at line 81 of file util-profiling.h.
KEYWORD_PROFILING_SET_LIST
#define KEYWORD_PROFILING_SET_LIST (ctx, list)
Value:
    { \
    (ctx)->keyword_perf_list = (list); \
}
Definition at line 63 of file util-profiling.h.
KEYWORD_PROFILING_START
#define KEYWORD_PROFILING_START
Value:
    uint64_t profile_keyword_start_ = 0; \
    uint64_t profile_keyword_end_ = 0; \
    if (profiling_keyword_enabled) { \
        if (profiling_keyword_entered > 0) { \
            SCLogError(SC_ERR_FATAL, "Re-entered profiling, exiting."); \
            abort(); \
        } \
        profiling_keyword_entered++; \
        profile_keyword_start_ = UtilCpuGetTicks(); \
    }
Definition at line 67 of file util-profiling.h.
PACKET_PROFILING_APP_END
#define PACKET_PROFILING_APP_END (dp, id)
Value:
    if (profiling_packets_enabled) {                                \
        BUG_ON((id) != (dp)->alproto);                              \
        (dp)->ticks_end = UtilCpuGetTicks();                        \
        if ((dp)->ticks_start != 0 && (dp)->ticks_start < ((dp)->ticks_end)) {  \
            (dp)->ticks_spent = ((dp)->ticks_end - (dp)->ticks_start);  \
        }                                                           \
    }
Definition at line 190 of file util-profiling.h.
PACKET_PROFILING_APP_PD_END
#define PACKET_PROFILING_APP_PD_END (dp)
Value:
    if (profiling_packets_enabled) {                                \
        (dp)->proto_detect_ticks_end = UtilCpuGetTicks();           \
        if ((dp)->proto_detect_ticks_start != 0 && (dp)->proto_detect_ticks_start < ((dp)->proto_detect_ticks_end)) {  \
            (dp)->proto_detect_ticks_spent =                        \
                ((dp)->proto_detect_ticks_end - (dp)->proto_detect_ticks_start);  \
        }                                                           \
    }
Definition at line 204 of file util-profiling.h.
PACKET_PROFILING_APP_PD_START
#define PACKET_PROFILING_APP_PD_START (dp)
Value:
    if (profiling_packets_enabled) {                                \
        (dp)->proto_detect_ticks_start = UtilCpuGetTicks();         \
    }
Definition at line 199 of file util-profiling.h.
PACKET_PROFILING_APP_RESET
#define PACKET_PROFILING_APP_RESET (dp)
Value:
    if (profiling_packets_enabled) {                                \
        (dp)->ticks_start = 0;                                      \
        (dp)->ticks_end = 0;                                        \
        (dp)->ticks_spent = 0;                                      \
        (dp)->alproto = 0;                                          \
        (dp)->proto_detect_ticks_start = 0;                         \
        (dp)->proto_detect_ticks_end = 0;                           \
        (dp)->proto_detect_ticks_spent = 0;                         \
    }
Definition at line 213 of file util-profiling.h.
PACKET_PROFILING_APP_START
#define PACKET_PROFILING_APP_START (dp, id)
Value:
    if (profiling_packets_enabled) {                                \
        (dp)->ticks_start = UtilCpuGetTicks();                      \
        (dp)->alproto = (id);                                       \
    }
Definition at line 184 of file util-profiling.h.
PACKET_PROFILING_APP_STORE
#define PACKET_PROFILING_APP_STORE (dp, p)
Value:
    if (profiling_packets_enabled && (p)->profile != NULL) {        \
        if ((dp)->alproto < ALPROTO_MAX) {                          \
            (p)->profile->app[(dp)->alproto].ticks_spent += (dp)->ticks_spent;   \
            (p)->profile->proto_detect += (dp)->proto_detect_ticks_spent;        \
        }                                                           \
    }
Definition at line 224 of file util-profiling.h.
PACKET_PROFILING_COPY_LOCKS
#define PACKET_PROFILING_COPY_LOCKS (p, id)
Definition at line 145 of file util-profiling.h.
PACKET_PROFILING_DETECT_END
#define PACKET_PROFILING_DETECT_END (p, id)
Value:
    if (profiling_packets_enabled  && (p)->profile != NULL) {       \
        if ((id) < PROF_DETECT_SIZE) {                              \
            (p)->profile->detect[(id)].ticks_end = UtilCpuGetTicks();\
            if ((p)->profile->detect[(id)].ticks_start != 0 &&       \
                    (p)->profile->detect[(id)].ticks_start < (p)->profile->detect[(id)].ticks_end) {  \
                (p)->profile->detect[(id)].ticks_spent +=            \
                ((p)->profile->detect[(id)].ticks_end - (p)->profile->detect[(id)].ticks_start);  \
            }                                                       \
        }                                                           \
    }
Definition at line 239 of file util-profiling.h.
PACKET_PROFILING_DETECT_START
#define PACKET_PROFILING_DETECT_START (p, id)
Value:
    if (profiling_packets_enabled && (p)->profile != NULL) {        \
        if ((id) < PROF_DETECT_SIZE) {                              \
            (p)->profile->detect[(id)].ticks_start = UtilCpuGetTicks(); \
        }                                                           \
    }
Definition at line 232 of file util-profiling.h.
PACKET_PROFILING_END
#define PACKET_PROFILING_END (p)
Value:
    if (profiling_packets_enabled && (p)->profile != NULL) {        \
        (p)->profile->ticks_end = UtilCpuGetTicks();                \
        SCProfilingAddPacket((p));                                  \
    }
Definition at line 103 of file util-profiling.h.
PACKET_PROFILING_LOGGER_END
#define PACKET_PROFILING_LOGGER_END (p, id)
Value:
    if (profiling_packets_enabled  && (p)->profile != NULL) {       \
        if ((id) < LOGGER_SIZE) {                              \
            (p)->profile->logger[(id)].ticks_end = UtilCpuGetTicks();\
            if ((p)->profile->logger[(id)].ticks_start != 0 &&       \
                    (p)->profile->logger[(id)].ticks_start < (p)->profile->logger[(id)].ticks_end) {  \
                (p)->profile->logger[(id)].ticks_spent +=            \
                ((p)->profile->logger[(id)].ticks_end - (p)->profile->logger[(id)].ticks_start);  \
            }                                                       \
        }                                                           \
    }
Definition at line 258 of file util-profiling.h.
PACKET_PROFILING_LOGGER_START
#define PACKET_PROFILING_LOGGER_START (p, id)
Value:
    if (profiling_packets_enabled && (p)->profile != NULL) {        \
        if ((id) < LOGGER_SIZE) {                              \
            (p)->profile->logger[(id)].ticks_start = UtilCpuGetTicks(); \
        }                                                           \
    }
Definition at line 251 of file util-profiling.h.
PACKET_PROFILING_RESET
#define PACKET_PROFILING_RESET (p)
Value:
    if (profiling_packets_enabled && (p)->profile != NULL) {        \
        SCFree((p)->profile);                                       \
        (p)->profile = NULL;                                        \
    }
Definition at line 178 of file util-profiling.h.
PACKET_PROFILING_RESET_LOCKS
#define PACKET_PROFILING_RESET_LOCKS
Definition at line 144 of file util-profiling.h.
PACKET_PROFILING_RESTART
#define PACKET_PROFILING_RESTART (p)
Value:
    if (profiling_packets_enabled) {                                \
        if ((p)->profile != NULL)                                   \
            (p)->profile->ticks_start = UtilCpuGetTicks();          \
    }
Definition at line 97 of file util-profiling.h.
PACKET_PROFILING_START
#define PACKET_PROFILING_START (p)
Value:
    if (profiling_packets_enabled) {                                \
        (p)->profile = SCProfilePacketStart();                      \
        if ((p)->profile != NULL)                                   \
            (p)->profile->ticks_start = UtilCpuGetTicks();          \
    }
Definition at line 90 of file util-profiling.h.
PACKET_PROFILING_TMM_END
#define PACKET_PROFILING_TMM_END (p, id)
Value:
    if (profiling_packets_enabled && (p)->profile != NULL) {        \
        if ((id) < TMM_SIZE) {                                      \
            PACKET_PROFILING_COPY_LOCKS((p), (id));                 \
            (p)->profile->tmm[(id)].ticks_end = UtilCpuGetTicks();  \
        }                                                           \
    }
Definition at line 156 of file util-profiling.h.
PACKET_PROFILING_TMM_START
#define PACKET_PROFILING_TMM_START (p, id)
Value:
    if (profiling_packets_enabled && (p)->profile != NULL) {        \
        if ((id) < TMM_SIZE) {                                      \
            (p)->profile->tmm[(id)].ticks_start = UtilCpuGetTicks();\
            PACKET_PROFILING_RESET_LOCKS;                           \
        }                                                           \
    }
Definition at line 148 of file util-profiling.h.
PREFILTER_PROFILING_ADD_BYTES
#define PREFILTER_PROFILING_ADD_BYTES (det_ctx, bytes)
Value:
    (det_ctx)->prefilter_bytes += (bytes);                                                         \
    (det_ctx)->prefilter_bytes_called++
Definition at line 304 of file util-profiling.h.
PREFILTER_PROFILING_END
#define PREFILTER_PROFILING_END (ctx, profile_id)
Value:
    if (profiling_prefilter_enabled && profiling_prefilter_entered) {                              \
        profile_prefilter_end_ = UtilCpuGetTicks();                                                \
        if (profile_prefilter_end_ > profile_prefilter_start_)                                     \
            SCProfilingPrefilterUpdateCounter((ctx), (profile_id),                                 \
                    (profile_prefilter_end_ - profile_prefilter_start_), (ctx)->prefilter_bytes,   \
                    (ctx)->prefilter_bytes_called);                                                \
        profiling_prefilter_entered--;                                                             \
    }
Definition at line 294 of file util-profiling.h.
PREFILTER_PROFILING_START
#define PREFILTER_PROFILING_START (det_ctx)
Value:
    (det_ctx)->prefilter_bytes = 0;                                                                \
    (det_ctx)->prefilter_bytes_called = 0;                                                         \
    uint64_t profile_prefilter_start_ = 0;                                                         \
    uint64_t profile_prefilter_end_ = 0;                                                           \
    if (profiling_prefilter_enabled) {                                                             \
        if (profiling_prefilter_entered > 0) {                                                     \
            SCLogError(SC_ERR_FATAL, "Re-entered profiling, exiting.");                            \
            abort();                                                                               \
        }                                                                                          \
        profiling_prefilter_entered++;                                                             \
        profile_prefilter_start_ = UtilCpuGetTicks();                                              \
    }
Definition at line 278 of file util-profiling.h.
RULE_PROFILING_END
#define RULE_PROFILING_END (ctx, r, m, p)
Value:
    if (profiling_rules_enabled && ((p)->flags & PKT_PROFILE)) { \
        profile_rule_end_ = UtilCpuGetTicks(); \
        SCProfilingRuleUpdateCounter(ctx, r->profiling_id, \
            profile_rule_end_ - profile_rule_start_, m); \
        profiling_rules_entered--; \
    }
Definition at line 52 of file util-profiling.h.
RULE_PROFILING_START
#define RULE_PROFILING_START (p)
Value:
    uint64_t profile_rule_start_ = 0; \
    uint64_t profile_rule_end_ = 0; \
    if (profiling_rules_enabled && SCProfileRuleStart((p))) { \
        if (profiling_rules_entered > 0) { \
            SCLogError(SC_ERR_FATAL, "Re-entered profiling, exiting."); \
            exit(1); \
        } \
        profiling_rules_entered++; \
        profile_rule_start_ = UtilCpuGetTicks(); \
    }
Definition at line 40 of file util-profiling.h.
SGH_PROFILING_RECORD
#define SGH_PROFILING_RECORD (det_ctx, sgh)
Value:
    if (profiling_sghs_enabled) {                                   \
        SCProfilingSghUpdateCounter((det_ctx), (sgh));              \
    }
Definition at line 270 of file util-profiling.h.
Function Documentation
SCProfilePacketStart()
PktProfiling * SCProfilePacketStart (void)
Definition at line 1194 of file util-profiling.c.
References SC_ATOMIC_ADD.
SCProfileRuleStart()
int SCProfileRuleStart (Packet * p)
Definition at line 1204 of file util-profiling.c.
References Packet_::flags, PKT_PROFILE, Packet_::profile, and SC_ATOMIC_ADD.
SCProfilingAddPacket()
void SCProfilingAddPacket (Packet * p)
Definition at line 1104 of file util-profiling.c.
References Packet_::profile, PktProfiling_::ticks_end, and PktProfiling_::ticks_start.
SCProfilingDestroy()
void SCProfilingDestroy (void)
Free resources used by profiling.
Definition at line 268 of file util-profiling.c.
References profiling_packets_enabled.
SCProfilingDump()
void SCProfilingDump (void)
Definition at line 294 of file util-profiling.c.
References SCLogPerf, and SCProfilingDumpPacketStats().
SCProfilingInit()
void SCProfilingInit (void)
Initialize profiling.
Definition at line 140 of file util-profiling.c.
References ConfGetInt(), and SC_ATOMIC_INIT.
Referenced by PreRunInit().
SCProfilingKeywordDestroyCtx()
void SCProfilingKeywordDestroyCtx (DetectEngineCtx * de_ctx)
Definition at line 278 of file util-profiling-keywords.c.
References de_ctx.
Referenced by DetectEngineCtxFree().
SCProfilingKeywordInitCounters()
void SCProfilingKeywordInitCounters (DetectEngineCtx * de_ctx)
Register the keyword profiling counters.
Parameters
de_ctx The active DetectEngineCtx, used to get at the loaded rules.
Definition at line 378 of file util-profiling-keywords.c.
References DetectEngineCtx_::buffer_type_id, de_ctx, DetectEngineCtx_::profile_keyword_ctx, and profiling_keyword_enabled.
SCProfilingKeywordsGlobalInit()
void SCProfilingKeywordsGlobalInit (void)
Definition at line 70 of file util-profiling-keywords.c.
References ConfGetNode(), ConfigGetLogDirectory(), ConfNodeChildValueIsTrue(), ConfNodeLookupChildValue(), and profiling_keyword_enabled.
Referenced by PreRunInit().
SCProfilingKeywordThreadCleanup()
void SCProfilingKeywordThreadCleanup (DetectEngineThreadCtx * det_ctx)
Definition at line 351 of file util-profiling-keywords.c.
References SCProfileKeywordDetectCtx_::data_m, DetectEngineThreadCtx_::de_ctx, DetectEngineThreadCtx_::keyword_perf_data, and DetectEngineCtx_::profile_keyword_ctx.
SCProfilingKeywordThreadSetup()
void SCProfilingKeywordThreadSetup (struct SCProfileKeywordDetectCtx_ * ctx, DetectEngineThreadCtx * det_ctx)
Definition at line 294 of file util-profiling-keywords.c.
References DetectEngineCtx_::buffer_type_id, BUG_ON, DetectEngineThreadCtx_::de_ctx, DETECT_TBLSIZE, DetectEngineThreadCtx_::keyword_perf_data, DetectEngineThreadCtx_::keyword_perf_data_per_list, SCCalloc, and SCMalloc.
SCProfilingKeywordUpdateCounter()
void SCProfilingKeywordUpdateCounter (DetectEngineThreadCtx * det_ctx, int id, uint64_t ticks, int match)
Update a rule counter.
Parameters
id The ID of this counter.
ticks Number of CPU ticks for this rule.
match Did the rule match?
Definition at line 224 of file util-profiling-keywords.c.
References SCProfileKeywordData_::checks, DETECT_TBLSIZE, DetectEngineThreadCtx_::keyword_perf_data, DetectEngineThreadCtx_::keyword_perf_data_per_list, DetectEngineThreadCtx_::keyword_perf_list, SCProfileKeywordData_::matches, SCProfileKeywordData_::max, SCProfileKeywordData_::ticks_match, and SCProfileKeywordData_::ticks_no_match.
SCProfilingPrefilterDestroyCtx()
void SCProfilingPrefilterDestroyCtx (DetectEngineCtx * de_ctx)
Definition at line 246 of file util-profiling-prefilter.c.
References de_ctx.
Referenced by DetectEngineCtxFree().
SCProfilingPrefilterGlobalInit()
void SCProfilingPrefilterGlobalInit (void)
Definition at line 69 of file util-profiling-prefilter.c.
References ConfGetNode(), ConfigGetLogDirectory(), ConfNodeChildValueIsTrue(), ConfNodeLookupChildValue(), and profiling_prefilter_enabled.
Referenced by PreRunInit().
SCProfilingPrefilterInitCounters()
void SCProfilingPrefilterInitCounters (DetectEngineCtx * de_ctx)
Register the prefilter profiling counters.
Parameters
de_ctx The active DetectEngineCtx, used to get at the loaded rules.
Definition at line 311 of file util-profiling-prefilter.c.
References de_ctx, DetectEngineCtx_::prefilter_id, DetectEngineCtx_::profile_prefilter_ctx, and profiling_prefilter_enabled.
SCProfilingPrefilterThreadCleanup()
void SCProfilingPrefilterThreadCleanup (DetectEngineThreadCtx * det_ctx)
Definition at line 292 of file util-profiling-prefilter.c.
References SCProfilePrefilterDetectCtx_::data_m, DetectEngineThreadCtx_::de_ctx, DetectEngineThreadCtx_::prefilter_perf_data, and DetectEngineCtx_::profile_prefilter_ctx.
SCProfilingPrefilterThreadSetup()
void SCProfilingPrefilterThreadSetup (struct SCProfilePrefilterDetectCtx_ * ctx, DetectEngineThreadCtx * det_ctx)
Definition at line 255 of file util-profiling-prefilter.c.
References DetectEngineThreadCtx_::de_ctx, DetectEngineCtx_::prefilter_id, DetectEngineThreadCtx_::prefilter_perf_data, and SCMalloc.
SCProfilingPrefilterUpdateCounter()
void SCProfilingPrefilterUpdateCounter (DetectEngineThreadCtx * det_ctx, int id, uint64_t ticks, uint64_t bytes, uint64_t bytes_called)
Update a rule counter.
Parameters
id The ID of this counter.
ticks Number of CPU ticks for this rule.
match Did the rule match?
Definition at line 201 of file util-profiling-prefilter.c.
References SCProfilePrefilterData_::bytes_called, SCProfilePrefilterData_::called, DetectEngineThreadCtx_::de_ctx, SCProfilePrefilterData_::max, SCProfilePrefilterData_::max_bytes, DetectEngineCtx_::prefilter_id, DetectEngineThreadCtx_::prefilter_perf_data, SCProfilePrefilterData_::total, and SCProfilePrefilterData_::total_bytes.
SCProfilingPrintPacketProfile()
void SCProfilingPrintPacketProfile (Packet * p)
Definition at line 776 of file util-profiling.c.
SCProfilingRegisterTests()
void SCProfilingRegisterTests (void)
Definition at line 1422 of file util-profiling.c.
References UtRegisterTest().
SCProfilingRuleDestroyCtx()
void SCProfilingRuleDestroyCtx (struct SCProfileDetectCtx_ * ctx)
Definition at line 589 of file util-profiling-rules.c.
Referenced by DetectEngineCtxFree().
SCProfilingRuleInitCounters()
void SCProfilingRuleInitCounters (DetectEngineCtx * de_ctx)
Register the rule profiling counters.
Parameters
de_ctx The active DetectEngineCtx, used to get at the loaded rules.
Definition at line 651 of file util-profiling-rules.c.
References de_ctx, DetectEngineCtx_::profile_ctx, and profiling_rules_enabled.
SCProfilingRulesGlobalInit()
void SCProfilingRulesGlobalInit (void)
Definition at line 115 of file util-profiling-rules.c.
References ConfGetNode(), ConfNodeChildValueIsTrue(), ConfNodeLookupChildValue(), profiling_rules_enabled, SC_ERR_INVALID_ARGUMENT, SC_PROFILING_RULES_SORT_BY_AVG_TICKS, SC_PROFILING_RULES_SORT_BY_AVG_TICKS_MATCH, SC_PROFILING_RULES_SORT_BY_AVG_TICKS_NO_MATCH, SC_PROFILING_RULES_SORT_BY_CHECKS, SC_PROFILING_RULES_SORT_BY_MATCHES, SC_PROFILING_RULES_SORT_BY_MAX_TICKS, SC_PROFILING_RULES_SORT_BY_TICKS, SCLogError, SET_ONE, and StringParseUint32().
Referenced by PreRunInit().
SCProfilingRuleThreadCleanup()
void SCProfilingRuleThreadCleanup (DetectEngineThreadCtx * det_ctx)
Definition at line 631 of file util-profiling-rules.c.
References SCProfileDetectCtx_::data_m, DetectEngineThreadCtx_::de_ctx, DetectEngineCtx_::profile_ctx, and DetectEngineThreadCtx_::rule_perf_data.
SCProfilingRuleThreadSetup()
void SCProfilingRuleThreadSetup (struct SCProfileDetectCtx_ * ctx, DetectEngineThreadCtx * det_ctx)
Definition at line 600 of file util-profiling-rules.c.
References DetectEngineThreadCtx_::rule_perf_data, DetectEngineThreadCtx_::rule_perf_data_size, SCMalloc, and SCProfileDetectCtx_::size.
SCProfilingRuleUpdateCounter()
void SCProfilingRuleUpdateCounter (DetectEngineThreadCtx * det_ctx, uint16_t id, uint64_t ticks, int match)
Update a rule counter.
Parameters
id The ID of this counter.
ticks Number of CPU ticks for this rule.
match Did the rule match?
Definition at line 558 of file util-profiling-rules.c.
References SCProfileData_::checks, SCProfileData_::matches, SCProfileData_::max, DetectEngineThreadCtx_::rule_perf_data, DetectEngineThreadCtx_::rule_perf_data_size, SCProfileData_::ticks_match, and SCProfileData_::ticks_no_match.
SCProfilingSghDestroyCtx()
void SCProfilingSghDestroyCtx (DetectEngineCtx * de_ctx)
Definition at line 311 of file util-profiling-rulegroups.c.
References de_ctx.
Referenced by DetectEngineCtxFree().
SCProfilingSghInitCounters()
void SCProfilingSghInitCounters (DetectEngineCtx * de_ctx)
Register the keyword profiling counters.
Parameters
de_ctx The active DetectEngineCtx, used to get at the loaded rules.
Definition at line 376 of file util-profiling-rulegroups.c.
References de_ctx, DetectEngineCtx_::profile_sgh_ctx, and profiling_sghs_enabled.
SCProfilingSghsGlobalInit()
void SCProfilingSghsGlobalInit (void)
Definition at line 72 of file util-profiling-rulegroups.c.
References ConfGetNode(), ConfigGetLogDirectory(), ConfNodeChildValueIsTrue(), ConfNodeLookupChildValue(), and profiling_sghs_enabled.
Referenced by PreRunInit().
SCProfilingSghThreadCleanup()
void SCProfilingSghThreadCleanup (DetectEngineThreadCtx * det_ctx)
Definition at line 357 of file util-profiling-rulegroups.c.
References SCProfileSghDetectCtx_::data_m, DetectEngineThreadCtx_::de_ctx, DetectEngineCtx_::profile_sgh_ctx, and DetectEngineThreadCtx_::sgh_perf_data.
SCProfilingSghThreadSetup()
void SCProfilingSghThreadSetup (struct SCProfileSghDetectCtx_ * ctx, DetectEngineThreadCtx * det_ctx)
Definition at line 320 of file util-profiling-rulegroups.c.
References DetectEngineThreadCtx_::de_ctx, SCCalloc, DetectEngineCtx_::sgh_array_cnt, and DetectEngineThreadCtx_::sgh_perf_data.
SCProfilingSghUpdateCounter()
void SCProfilingSghUpdateCounter (DetectEngineThreadCtx * det_ctx, const SigGroupHead * sgh)
Update a rule counter.
Parameters
id The ID of this counter.
ticks Number of CPU ticks for this rule.
match Did the rule match?
Definition at line 268 of file util-profiling-rulegroups.c.
References SCProfileSghData_::checks, DetectEngineThreadCtx_::de_ctx, SigGroupHead_::id, DetectEngineThreadCtx_::match_array_cnt, SCProfileSghData_::mpm_match_cnt_max, SCProfileSghData_::mpm_match_cnt_total, SCProfileSghData_::non_mpm_generic, SCProfileSghData_::non_mpm_syn, DetectEngineThreadCtx_::non_pf_store_cnt, DetectEngineThreadCtx_::non_pf_store_ptr, SigGroupHead_::non_pf_syn_store_array, DetectEngineThreadCtx_::pmq, SCProfileSghData_::post_prefilter_sigs_max, SCProfileSghData_::post_prefilter_sigs_total, PrefilterRuleStore_::rule_id_array_cnt, DetectEngineCtx_::sgh_array_cnt, and DetectEngineThreadCtx_::sgh_perf_data.
Variable Documentation
profiling_keyword_enabled
int profiling_keyword_enabled extern
Definition at line 65 of file util-profiling-keywords.c.
Referenced by SCProfilingKeywordInitCounters(), and SCProfilingKeywordsGlobalInit().
profiling_keyword_entered
thread_local int profiling_keyword_entered extern
Definition at line 66 of file util-profiling-keywords.c.
profiling_packets_enabled
int profiling_packets_enabled extern
Definition at line 101 of file util-profiling.c.
Referenced by SCProfilingDestroy(), and SCProfilingDumpPacketStats().
profiling_prefilter_enabled
int profiling_prefilter_enabled extern
Definition at line 64 of file util-profiling-prefilter.c.
Referenced by SCProfilingPrefilterGlobalInit(), and SCProfilingPrefilterInitCounters().
profiling_prefilter_entered
thread_local int profiling_prefilter_entered extern
Definition at line 65 of file util-profiling-prefilter.c.
profiling_rules_enabled
int profiling_rules_enabled extern
Definition at line 82 of file util-profiling-rules.c.
Referenced by SCProfilingRuleInitCounters(), and SCProfilingRulesGlobalInit().
profiling_rules_entered
thread_local int profiling_rules_entered extern
Used as a check so we don't double enter a profiling run.
Definition at line 117 of file util-profiling.c.
profiling_sghs_enabled
int profiling_sghs_enabled extern
Definition at line 67 of file util-profiling-rulegroups.c.
Referenced by SCProfilingSghInitCounters(), and SCProfilingSghsGlobalInit().