suricata: /Users/jlu/suricata/src/util-thash.c File Reference
util-thash.c File Reference
#include "suricata-common.h"
#include "conf.h"
#include "util-debug.h"
#include "util-thash.h"
#include "util-random.h"
#include "util-misc.h"
#include "util-byte.h"
#include "util-hash-lookup3.h"
#include "util-validate.h"
Macros
#define THASH_DEFAULT_HASHSIZE 4096
#define THASH_DEFAULT_MEMCAP 16777216
#define THASH_DEFAULT_PREALLOC 1000
#define GET_VAR(prefix, name) snprintf(varname, sizeof(varname), "%s.%s", (prefix), (name))
Functions
void THashDataMoveToSpare (THashTableContext *ctx, THashData *h)
THashDataQueue * THashDataQueueNew (void)
THashTableContext * THashInit (const char *cnf_prefix, size_t data_size, int(*DataSet)(void *, void *), void(*DataFree)(void *), uint32_t(*DataHash)(void *), bool(*DataCompare)(void *, void *), bool reset_memcap, uint64_t memcap, uint32_t hashsize)
void THashConsolidateMemcap (THashTableContext *ctx)
void THashShutdown (THashTableContext *ctx)
shutdown the flow engine
int THashWalk (THashTableContext *ctx, THashFormatFunc FormatterFunc, THashOutputFunc OutputterFunc, void *output_ctx)
Walk the hash.
void THashCleanup (THashTableContext *ctx)
Cleanup the thash engine.
struct THashDataGetResult THashGetFromHash (THashTableContext *ctx, void *data)
THashData * THashLookupFromHash (THashTableContext *ctx, void *data)
look up data in the hash
int THashRemoveFromHash (THashTableContext *ctx, void *data)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file util-thash.c.
Macro Definition Documentation
GET_VAR
#define GET_VAR (prefix, name) snprintf(varname, sizeof(varname), "%s.%s", (prefix), (name))
Definition at line 205 of file util-thash.c.
THASH_DEFAULT_HASHSIZE
#define THASH_DEFAULT_HASHSIZE 4096
Definition at line 201 of file util-thash.c.
THASH_DEFAULT_MEMCAP
#define THASH_DEFAULT_MEMCAP 16777216
Definition at line 202 of file util-thash.c.
THASH_DEFAULT_PREALLOC
#define THASH_DEFAULT_PREALLOC 1000
Definition at line 203 of file util-thash.c.
Function Documentation
THashCleanup()
void THashCleanup (THashTableContext * ctx)
Cleanup the thash engine.
Cleanup the thash engine from tag and threshold.
Definition at line 415 of file util-thash.c.
References THashTableContext_::array, THashTableContext_::config, THashDataConfig_::hash_size, HRLOCK_LOCK, HRLOCK_UNLOCK, THashData_::next, THashData_::prev, SC_ATOMIC_GET, and THashDataMoveToSpare().
THashConsolidateMemcap()
void THashConsolidateMemcap (THashTableContext * ctx)
Definition at line 338 of file util-thash.c.
References THashTableContext_::config, MAX, THashDataConfig_::memcap, SC_ATOMIC_GET, and SCLogDebug.
THashDataMoveToSpare()
void THashDataMoveToSpare (THashTableContext * ctx, THashData * h)
Definition at line 41 of file util-thash.c.
Referenced by THashCleanup().
THashDataQueueNew()
THashDataQueue * THashDataQueueNew (void)
Definition at line 56 of file util-thash.c.
References SC_ERR_FATAL, SCLogError, and SCMalloc.
THashGetFromHash()
struct THashDataGetResult THashGetFromHash (THashTableContext * ctx, void * data)
Definition at line 529 of file util-thash.c.
References res.
THashInit()
THashTableContext * THashInit (const char * cnf_prefix, size_t data_size, int(*)(void *, void *) DataSet, void(*)(void *) DataFree, uint32_t(*)(void *) DataHash, bool(*)(void *, void *) DataCompare, bool reset_memcap, uint64_t memcap, uint32_t hashsize)
Definition at line 294 of file util-thash.c.
References BUG_ON, THashTableContext_::config, THashDataConfig_::data_size, THashDataConfig_::DataCompare, THashDataConfig_::DataFree, THashDataConfig_::DataHash, THashDataConfig_::DataSet, THashDataConfig_::hash_rand, THashDataConfig_::hash_size, hashsize, THashDataConfig_::memcap, THashDataConfig_::prealloc, RandomGet(), SC_ATOMIC_INIT, SCCalloc, THASH_DEFAULT_HASHSIZE, THASH_DEFAULT_MEMCAP, and THASH_DEFAULT_PREALLOC.
Referenced by HttpRangeContainersInit().
THashLookupFromHash()
THashData * THashLookupFromHash (THashTableContext * ctx, void * data)
look up data in the hash
Parameters
data data to look up
Return values
h LOCKED data or NULL
Definition at line 639 of file util-thash.c.
THashRemoveFromHash()
int THashRemoveFromHash (THashTableContext * ctx, void * data)
Return values
int -1 not found
int 0 found, but it was busy (ref cnt)
int 1 found and removed
Definition at line 774 of file util-thash.c.
THashShutdown()
void THashShutdown (THashTableContext * ctx)
shutdown the flow engine
Warning
Not thread safe
Definition at line 346 of file util-thash.c.
Referenced by HttpRangeContainersDestroy().
THashWalk()
int THashWalk (THashTableContext * ctx, THashFormatFunc FormatterFunc, THashOutputFunc OutputterFunc, void * output_ctx)
Walk the hash.
Definition at line 380 of file util-thash.c.
References THashTableContext_::array, THashTableContext_::config, THashData_::data, THashDataConfig_::hash_size, HRLOCK_LOCK, HRLOCK_UNLOCK, and THashData_::next.