suricata: /Users/jlu/suricata/src/util-hash-lookup3.h File Reference
util-hash-lookup3.h File Reference
Macros
#define hashsize(n) ((uint32_t)1<<(n))
#define hashmask(n) (hashsize(n)-1)
Functions
uint32_t hashword (const uint32_t *k, size_t length, uint32_t initval)
void hashword2 (const uint32_t *k, size_t length, uint32_t *pc, uint32_t *pb)
uint32_t hashlittle (const void *key, size_t length, uint32_t initval)
uint32_t hashlittle_safe (const void *key, size_t length, uint32_t initval)
void hashlittle2 (const void *key, size_t length, uint32_t *pc, uint32_t *pb)
uint32_t hashbig (const void *key, size_t length, uint32_t initval)
Macro Definition Documentation
hashmask
#define hashmask (n) (hashsize(n)-1)
Definition at line 41 of file util-hash-lookup3.h.
hashsize
#define hashsize (n) ((uint32_t)1<<(n))
Definition at line 40 of file util-hash-lookup3.h.
Function Documentation
hashbig()
uint32_t hashbig (const void * key, size_t length, uint32_t initval)
Definition at line 818 of file util-hash-lookup3.c.
References HASH_BIG_ENDIAN, and mix.
hashlittle()
uint32_t hashlittle (const void * key, size_t length, uint32_t initval)
Definition at line 283 of file util-hash-lookup3.c.
References HASH_LITTLE_ENDIAN, and mix.
hashlittle2()
void hashlittle2 (const void * key, size_t length, uint32_t * pc, uint32_t * pb)
Definition at line 637 of file util-hash-lookup3.c.
References HASH_LITTLE_ENDIAN, and mix.
hashlittle_safe()
uint32_t hashlittle_safe (const void * key, size_t length, uint32_t initval)
Definition at line 484 of file util-hash-lookup3.c.
References HASH_LITTLE_ENDIAN, and mix.
hashword()
uint32_t hashword (const uint32_t * k, size_t length, uint32_t initval)
Definition at line 174 of file util-hash-lookup3.c.
References mix.
Referenced by FlowKeyGetHash(), ROHashInitFinalize(), and ROHashLookup().
hashword2()
void hashword2 (const uint32_t * k, size_t length, uint32_t * pc, uint32_t * pb)
Definition at line 218 of file util-hash-lookup3.c.
References mix.