suricata: /Users/jlu/suricata/src/util-mpm-ac-ks.c File Reference
util-mpm-ac-ks.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "detect.h"
#include "detect-parse.h"
#include "detect-engine.h"
#include "detect-engine-build.h"
#include "conf.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-unittest-helper.h"
#include "util-memcmp.h"
#include "util-memcpy.h"
#include "util-validate.h"
#include "util-mpm-ac-ks.h"
#include "util-mpm-ac-ks-small.c"
Data Structures
struct StateQueue_
Helper structure used by AC during state table creation.
Macros
#define SC_AC_TILE_FAIL (-1)
#define STATE_QUEUE_CONTAINER_SIZE 65536
#define SCHECK(x) ((x) > 0)
#define BUF_TYPE int32_t
#define BYTE0(x) (((x) & 0x000000ff) >> 0)
#define BYTE1(x) (((x) & 0x0000ff00) >> 8)
#define BYTE2(x) (((x) & 0x00ff0000) >> 16)
#define BYTE3(x) (((x) & 0xff000000) >> 24)
#define EXTRA 4
#define SINDEX_INTERNAL(y, x, log_mult, width) ((1<<log_mult) * (x & ((1<<width) - 1)))
#define STYPE int16_t
#define SLOAD(x) *(STYPE * restrict)(x)
#define FUNC_NAME SCACTileSearchSmall256
#define SINDEX(y, x) SINDEX_INTERNAL(y, x, 8, 15)
#define FUNC_NAME SCACTileSearchSmall128
#define SINDEX(y, x) SINDEX_INTERNAL(y, x, 7, 15)
#define FUNC_NAME SCACTileSearchSmall64
#define SINDEX(y, x) SINDEX_INTERNAL(y, x, 6, 15)
#define FUNC_NAME SCACTileSearchSmall32
#define SINDEX(y, x) SINDEX_INTERNAL(y, x, 5, 15)
#define FUNC_NAME SCACTileSearchSmall16
#define SINDEX(y, x) SINDEX_INTERNAL(y, x, 4, 15)
#define FUNC_NAME SCACTileSearchSmall8
#define SINDEX(y, x) SINDEX_INTERNAL(y, x, 3, 15)
#define STYPE int8_t
#define FUNC_NAME SCACTileSearchTiny256
#define SINDEX(y, x) SINDEX_INTERNAL(y, x, 8, 7)
#define FUNC_NAME SCACTileSearchTiny128
#define SINDEX(y, x) SINDEX_INTERNAL(y, x, 7, 7)
#define FUNC_NAME SCACTileSearchTiny64
#define SINDEX(y, x) SINDEX_INTERNAL(y, x, 6, 7)
#define FUNC_NAME SCACTileSearchTiny32
#define SINDEX(y, x) SINDEX_INTERNAL(y, x, 5, 7)
#define FUNC_NAME SCACTileSearchTiny16
#define SINDEX(y, x) SINDEX_INTERNAL(y, x, 4, 7)
#define FUNC_NAME SCACTileSearchTiny8
#define SINDEX(y, x) SINDEX_INTERNAL(y, x, 3, 7)
Typedefs
typedef struct StateQueue_ StateQueue
Helper structure used by AC during state table creation.
Functions
void SCACTileInitCtx (MpmCtx *mpm_ctx)
Initialize the AC context.
void SCACTileInitThreadCtx (MpmCtx *mpm_ctx, MpmThreadCtx *mpm_thread_ctx)
Init the mpm thread context.
void SCACTileDestroyCtx (MpmCtx *mpm_ctx)
Destroy the mpm context.
void SCACTileDestroyThreadCtx (MpmCtx *mpm_ctx, MpmThreadCtx *mpm_thread_ctx)
Destroy the mpm thread context.
int SCACTileAddPatternCI (MpmCtx *mpm_ctx, uint8_t *pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Add a case insensitive pattern. Although we have different calls for adding case sensitive and insensitive patterns, we make a single call for either case. No special treatment for either case.
int SCACTileAddPatternCS (MpmCtx *mpm_ctx, uint8_t *pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Add a case sensitive pattern. Although we have different calls for adding case sensitive and insensitive patterns, we make a single call for either case. No special treatment for either case.
int SCACTilePreparePatterns (MpmCtx *mpm_ctx)
Process the patterns added to the mpm, and create the internal tables.
uint32_t SCACTileSearch (const MpmCtx *mpm_ctx, MpmThreadCtx *mpm_thread_ctx, PrefilterRuleStore *pmq, const uint8_t *buf, uint32_t buflen)
The aho corasick search function.
void SCACTilePrintInfo (MpmCtx *mpm_ctx)
void SCACTilePrintSearchStats (MpmThreadCtx *mpm_thread_ctx)
void SCACTileRegisterTests (void)
uint32_t SCACTileSearchLarge (const SCACTileSearchCtx *ctx, MpmThreadCtx *mpm_thread_ctx, PrefilterRuleStore *pmq, const uint8_t *buf, uint32_t buflen)
uint32_t SCACTileSearchSmall256 (const SCACTileSearchCtx *ctx, MpmThreadCtx *mpm_thread_ctx, PrefilterRuleStore *pmq, const uint8_t *buf, uint32_t buflen)
uint32_t SCACTileSearchSmall128 (const SCACTileSearchCtx *ctx, MpmThreadCtx *mpm_thread_ctx, PrefilterRuleStore *pmq, const uint8_t *buf, uint32_t buflen)
uint32_t SCACTileSearchSmall64 (const SCACTileSearchCtx *ctx, MpmThreadCtx *mpm_thread_ctx, PrefilterRuleStore *pmq, const uint8_t *buf, uint32_t buflen)
uint32_t SCACTileSearchSmall32 (const SCACTileSearchCtx *ctx, MpmThreadCtx *mpm_thread_ctx, PrefilterRuleStore *pmq, const uint8_t *buf, uint32_t buflen)
uint32_t SCACTileSearchSmall16 (const SCACTileSearchCtx *ctx, MpmThreadCtx *mpm_thread_ctx, PrefilterRuleStore *pmq, const uint8_t *buf, uint32_t buflen)
uint32_t SCACTileSearchSmall8 (const SCACTileSearchCtx *ctx, MpmThreadCtx *mpm_thread_ctx, PrefilterRuleStore *pmq, const uint8_t *buf, uint32_t buflen)
uint32_t SCACTileSearchTiny256 (const SCACTileSearchCtx *ctx, MpmThreadCtx *mpm_thread_ctx, PrefilterRuleStore *pmq, const uint8_t *buf, uint32_t buflen)
uint32_t SCACTileSearchTiny128 (const SCACTileSearchCtx *ctx, MpmThreadCtx *mpm_thread_ctx, PrefilterRuleStore *pmq, const uint8_t *buf, uint32_t buflen)
uint32_t SCACTileSearchTiny64 (const SCACTileSearchCtx *ctx, MpmThreadCtx *mpm_thread_ctx, PrefilterRuleStore *pmq, const uint8_t *buf, uint32_t buflen)
uint32_t SCACTileSearchTiny32 (const SCACTileSearchCtx *ctx, MpmThreadCtx *mpm_thread_ctx, PrefilterRuleStore *pmq, const uint8_t *buf, uint32_t buflen)
uint32_t SCACTileSearchTiny16 (const SCACTileSearchCtx *ctx, MpmThreadCtx *mpm_thread_ctx, PrefilterRuleStore *pmq, const uint8_t *buf, uint32_t buflen)
uint32_t SCACTileSearchTiny8 (const SCACTileSearchCtx *ctx, MpmThreadCtx *mpm_thread_ctx, PrefilterRuleStore *pmq, const uint8_t *buf, uint32_t buflen)
void MpmACTileRegister (void)
Register the aho-corasick mpm 'ks' originally developed by Ken Steele for Tilera Tile-Gx processor.
Detailed Description
Author
Ken Steele suric.nosp@m.ata@.nosp@m.tiler.nosp@m.a.co.nosp@m.m
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
    Aho-corasick MPM optimized for the Tilera Tile-Gx architecture.
    Efficient String Matching: An Aid to Bibliographic Search
    Alfred V. Aho and Margaret J. Corasick
    - Started with util-mpm-ac.c:
        - Uses the delta table for calculating transitions,
          instead of having separate goto and failure
          transitions.
        - If we cross 2 ** 16 states, we use 4 bytes in the
          transition table to hold each state, otherwise we use
          2 bytes.
        - This version of the MPM is heavy on memory, but it
          performs well.  If you can fit the ruleset with this
          mpm on your box without hitting swap, this is the MPM
          to go for.
    - Added these optimizations:
        - Compress the input alphabet from 256 characters down
          to the actual characters used in the patterns, plus
          one character for all the unused characters.
        - Reduce the size of the delta table so that each state
          is the smallest power of two that is larger than the
          size of the compressed alphabet.
        - Specialized the search function based on state count
          (small for 8-bit large for 16-bit) and the size of
          the alphabet, so that it is constant inside the
          function for better optimization.
Todo:
Do a proper analyis of our existing MPMs and suggest a good one based on the pattern distribution and the expected traffic(say http).
Irrespective of whether we cross 2 ** 16 states or not,shift to using uint32_t for state type, so that we can integrate it's status as a final state or not in the topmost byte. We are already doing it if state_count is > 2 ** 16.
Test case-senstive patterns if they have any ascii chars. If they don't treat them as nocase.
Reorder the compressed alphabet to put the most common characters first.
Definition in file util-mpm-ac-ks.c.
Macro Definition Documentation
BUF_TYPE
#define BUF_TYPE int32_t
Definition at line 1156 of file util-mpm-ac-ks.c.
BYTE0
#define BYTE0 (x) (((x) & 0x000000ff) >> 0)
Definition at line 1158 of file util-mpm-ac-ks.c.
BYTE1
#define BYTE1 (x) (((x) & 0x0000ff00) >> 8)
Definition at line 1159 of file util-mpm-ac-ks.c.
BYTE2
#define BYTE2 (x) (((x) & 0x00ff0000) >> 16)
Definition at line 1160 of file util-mpm-ac-ks.c.
BYTE3
#define BYTE3 (x) (((x) & 0xff000000) >> 24)
Definition at line 1161 of file util-mpm-ac-ks.c.
EXTRA
#define EXTRA 4
Definition at line 1162 of file util-mpm-ac-ks.c.
FUNC_NAME [1/12]
#define FUNC_NAME SCACTileSearchSmall256
Definition at line 1370 of file util-mpm-ac-ks.c.
FUNC_NAME [2/12]
#define FUNC_NAME SCACTileSearchSmall128
Definition at line 1370 of file util-mpm-ac-ks.c.
FUNC_NAME [3/12]
#define FUNC_NAME SCACTileSearchSmall64
Definition at line 1370 of file util-mpm-ac-ks.c.
FUNC_NAME [4/12]
#define FUNC_NAME SCACTileSearchSmall32
Definition at line 1370 of file util-mpm-ac-ks.c.
FUNC_NAME [5/12]
#define FUNC_NAME SCACTileSearchSmall16
Definition at line 1370 of file util-mpm-ac-ks.c.
FUNC_NAME [6/12]
#define FUNC_NAME SCACTileSearchSmall8
Definition at line 1370 of file util-mpm-ac-ks.c.
FUNC_NAME [7/12]
#define FUNC_NAME SCACTileSearchTiny256
Definition at line 1370 of file util-mpm-ac-ks.c.
FUNC_NAME [8/12]
#define FUNC_NAME SCACTileSearchTiny128
Definition at line 1370 of file util-mpm-ac-ks.c.
FUNC_NAME [9/12]
#define FUNC_NAME SCACTileSearchTiny64
Definition at line 1370 of file util-mpm-ac-ks.c.
FUNC_NAME [10/12]
#define FUNC_NAME SCACTileSearchTiny32
Definition at line 1370 of file util-mpm-ac-ks.c.
FUNC_NAME [11/12]
#define FUNC_NAME SCACTileSearchTiny16
Definition at line 1370 of file util-mpm-ac-ks.c.
FUNC_NAME [12/12]
#define FUNC_NAME SCACTileSearchTiny8
Definition at line 1370 of file util-mpm-ac-ks.c.
SC_AC_TILE_FAIL
#define SC_AC_TILE_FAIL (-1)
Definition at line 149 of file util-mpm-ac-ks.c.
SCHECK
#define SCHECK (x) ((x) > 0)
Definition at line 1155 of file util-mpm-ac-ks.c.
SINDEX [1/12]
#define SINDEX (y, x) SINDEX_INTERNAL(y, x, 8, 15)
Definition at line 1372 of file util-mpm-ac-ks.c.
SINDEX [2/12]
#define SINDEX (y, x) SINDEX_INTERNAL(y, x, 7, 15)
Definition at line 1372 of file util-mpm-ac-ks.c.
SINDEX [3/12]
#define SINDEX (y, x) SINDEX_INTERNAL(y, x, 6, 15)
Definition at line 1372 of file util-mpm-ac-ks.c.
SINDEX [4/12]
#define SINDEX (y, x) SINDEX_INTERNAL(y, x, 5, 15)
Definition at line 1372 of file util-mpm-ac-ks.c.
SINDEX [5/12]
#define SINDEX (y, x) SINDEX_INTERNAL(y, x, 4, 15)
Definition at line 1372 of file util-mpm-ac-ks.c.
SINDEX [6/12]
#define SINDEX (y, x) SINDEX_INTERNAL(y, x, 3, 15)
Definition at line 1372 of file util-mpm-ac-ks.c.
SINDEX [7/12]
#define SINDEX (y, x) SINDEX_INTERNAL(y, x, 8, 7)
Definition at line 1372 of file util-mpm-ac-ks.c.
SINDEX [8/12]
#define SINDEX (y, x) SINDEX_INTERNAL(y, x, 7, 7)
Definition at line 1372 of file util-mpm-ac-ks.c.
SINDEX [9/12]
#define SINDEX (y, x) SINDEX_INTERNAL(y, x, 6, 7)
Definition at line 1372 of file util-mpm-ac-ks.c.
SINDEX [10/12]
#define SINDEX (y, x) SINDEX_INTERNAL(y, x, 5, 7)
Definition at line 1372 of file util-mpm-ac-ks.c.
SINDEX [11/12]
#define SINDEX (y, x) SINDEX_INTERNAL(y, x, 4, 7)
Definition at line 1372 of file util-mpm-ac-ks.c.
SINDEX [12/12]
#define SINDEX (y, x) SINDEX_INTERNAL(y, x, 3, 7)
Definition at line 1372 of file util-mpm-ac-ks.c.
SINDEX_INTERNAL
#define SINDEX_INTERNAL (y, x, log_mult, width) ((1<<log_mult) * (x & ((1<<width) - 1)))
Definition at line 1269 of file util-mpm-ac-ks.c.
SLOAD
#define SLOAD (x) *(STYPE * restrict)(x)
Definition at line 1274 of file util-mpm-ac-ks.c.
STATE_QUEUE_CONTAINER_SIZE
#define STATE_QUEUE_CONTAINER_SIZE 65536
Definition at line 151 of file util-mpm-ac-ks.c.
STYPE [1/2]
#define STYPE int16_t
Definition at line 1326 of file util-mpm-ac-ks.c.
STYPE [2/2]
#define STYPE int8_t
Definition at line 1326 of file util-mpm-ac-ks.c.
Typedef Documentation
StateQueue
typedef struct StateQueue_ StateQueue
Helper structure used by AC during state table creation.
Function Documentation
MpmACTileRegister()
void MpmACTileRegister (void)
Register the aho-corasick mpm 'ks' originally developed by Ken Steele for Tilera Tile-Gx processor.
Definition at line 1463 of file util-mpm-ac-ks.c.
References MpmTableElmt_::AddPattern, MpmTableElmt_::AddPatternNocase, MpmTableElmt_::DestroyCtx, MpmTableElmt_::DestroyThreadCtx, MpmTableElmt_::InitCtx, MpmTableElmt_::InitThreadCtx, MPM_AC_KS, mpm_table, MpmTableElmt_::name, MpmTableElmt_::Prepare, MpmTableElmt_::PrintCtx, MpmTableElmt_::PrintThreadCtx, MpmTableElmt_::RegisterUnittests, SCACTileAddPatternCI(), SCACTileAddPatternCS(), SCACTileDestroyCtx(), SCACTileDestroyThreadCtx(), SCACTileInitCtx(), SCACTileInitThreadCtx(), SCACTilePreparePatterns(), SCACTilePrintInfo(), SCACTilePrintSearchStats(), SCACTileRegisterTests(), SCACTileSearch(), and MpmTableElmt_::Search.
Referenced by MpmTableSetup().
SCACTileAddPatternCI()
int SCACTileAddPatternCI (MpmCtx * mpm_ctx, uint8_t * pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Add a case insensitive pattern. Although we have different calls for adding case sensitive and insensitive patterns, we make a single call for either case. No special treatment for either case.
Parameters
mpm_ctx Pointer to the mpm context.
pat The pattern to add.
patnen The pattern length.
offset Ignored.
depth Ignored.
pid The pattern id.
sid Ignored.
flags Flags associated with this pattern.
Return values
0 On success.
-1 On failure.
Definition at line 1393 of file util-mpm-ac-ks.c.
References flags, MPM_PATTERN_FLAG_NOCASE, MpmAddPattern(), and offset.
Referenced by MpmACTileRegister().
SCACTileAddPatternCS()
int SCACTileAddPatternCS (MpmCtx * mpm_ctx, uint8_t * pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Add a case sensitive pattern. Although we have different calls for adding case sensitive and insensitive patterns, we make a single call for either case. No special treatment for either case.
Parameters
mpm_ctx Pointer to the mpm context.
pat The pattern to add.
patnen The pattern length.
offset Ignored.
depth Ignored.
pid The pattern id.
sid Ignored.
flags Flags associated with this pattern.
Return values
0 On success.
-1 On failure.
Definition at line 1419 of file util-mpm-ac-ks.c.
References flags, MpmAddPattern(), and offset.
Referenced by MpmACTileRegister().
SCACTileDestroyCtx()
void SCACTileDestroyCtx (MpmCtx * mpm_ctx)
Destroy the mpm context.
Parameters
mpm_ctx Pointer to the mpm context.
Definition at line 1113 of file util-mpm-ac-ks.c.
References MpmCtx_::ctx.
Referenced by MpmACTileRegister().
SCACTileDestroyThreadCtx()
void SCACTileDestroyThreadCtx (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx)
Destroy the mpm thread context.
Parameters
mpm_ctx Pointer to the mpm context.
mpm_thread_ctx Pointer to the mpm thread context.
Definition at line 1036 of file util-mpm-ac-ks.c.
References MpmThreadCtx_::ctx, MpmThreadCtx_::memory_cnt, MpmThreadCtx_::memory_size, SCACTilePrintSearchStats(), and SCFree.
Referenced by MpmACTileRegister().
SCACTileInitCtx()
void SCACTileInitCtx (MpmCtx * mpm_ctx)
Initialize the AC context.
Parameters
mpm_ctx Mpm context.
Definition at line 991 of file util-mpm-ac-ks.c.
References MpmCtx_::ctx, SCACTileSearchCtx_::init_ctx, MpmCtx_::init_hash, MpmCtx_::memory_cnt, MpmCtx_::memory_size, MPM_INIT_HASH_SIZE, and SCMalloc.
Referenced by MpmACTileRegister().
SCACTileInitThreadCtx()
void SCACTileInitThreadCtx (MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx)
Init the mpm thread context.
Parameters
mpm_ctx Pointer to the mpm context.
mpm_thread_ctx Pointer to the mpm thread context.
Definition at line 973 of file util-mpm-ac-ks.c.
References MpmThreadCtx_::ctx, MpmThreadCtx_::memory_cnt, MpmThreadCtx_::memory_size, and SCMalloc.
Referenced by MpmACTileRegister().
SCACTilePreparePatterns()
int SCACTilePreparePatterns (MpmCtx * mpm_ctx)
Process the patterns added to the mpm, and create the internal tables.
Parameters
mpm_ctx Pointer to the mpm context.
Definition at line 870 of file util-mpm-ac-ks.c.
References MpmCtx_::ctx, SCACTileSearchCtx_::init_ctx, MpmCtx_::init_hash, MPM_INIT_HASH_SIZE, MpmPattern_::next, SCACTileCtx_::parray, MpmCtx_::pattern_cnt, SCLogDebug, and SCMalloc.
Referenced by MpmACTileRegister().
SCACTilePrintInfo()
void SCACTilePrintInfo (MpmCtx * mpm_ctx)
Definition at line 1437 of file util-mpm-ac-ks.c.
References MpmCtx_::ctx, SCACTileSearchCtx_::init_ctx, MpmCtx_::maxlen, MpmCtx_::memory_cnt, MpmCtx_::memory_size, MpmCtx_::minlen, MpmCtx_::pattern_cnt, and SCACTileCtx_::state_count.
Referenced by MpmACTileRegister().
SCACTilePrintSearchStats()
void SCACTilePrintSearchStats (MpmThreadCtx * mpm_thread_ctx)
Definition at line 1427 of file util-mpm-ac-ks.c.
References MpmThreadCtx_::ctx, SCACTileThreadCtx_::total_calls, and SCACTileThreadCtx_::total_matches.
Referenced by MpmACTileRegister(), and SCACTileDestroyThreadCtx().
SCACTileRegisterTests()
void SCACTileRegisterTests (void)
Definition at line 2519 of file util-mpm-ac-ks.c.
References UtRegisterTest().
Referenced by MpmACTileRegister().
SCACTileSearch()
uint32_t SCACTileSearch (const MpmCtx * mpm_ctx, MpmThreadCtx * mpm_thread_ctx, PrefilterRuleStore * pmq, const uint8_t * buf, uint32_t buflen)
The aho corasick search function.
Parameters
mpm_ctx Pointer to the mpm context.
mpm_thread_ctx Pointer to the mpm thread context.
pmq Pointer to the Pattern Matcher Queue to hold search matches.
buf Buffer to be searched.
buflen Buffer length.
Return values
matches Match count.
Definition at line 1227 of file util-mpm-ac-ks.c.
References MpmCtx_::ctx, and SCACTileSearchCtx_::Search.
Referenced by MpmACTileRegister().
SCACTileSearchLarge()
uint32_t SCACTileSearchLarge (const SCACTileSearchCtx * ctx, MpmThreadCtx * mpm_thread_ctx, PrefilterRuleStore * pmq, const uint8_t * buf, uint32_t buflen)
Definition at line 1240 of file util-mpm-ac-ks.c.
References DEBUG_VALIDATE_BUG_ON, SCACTileSearchCtx_::mpm_bitarray_size, SCHECK, SCACTileSearchCtx_::state_table, and SCACTileSearchCtx_::translate_table.
SCACTileSearchSmall128()
uint32_t SCACTileSearchSmall128 (const SCACTileSearchCtx * ctx, MpmThreadCtx * mpm_thread_ctx, PrefilterRuleStore * pmq, const uint8_t * buf, uint32_t buflen)
SCACTileSearchSmall16()
uint32_t SCACTileSearchSmall16 (const SCACTileSearchCtx * ctx, MpmThreadCtx * mpm_thread_ctx, PrefilterRuleStore * pmq, const uint8_t * buf, uint32_t buflen)
SCACTileSearchSmall256()
uint32_t SCACTileSearchSmall256 (const SCACTileSearchCtx * ctx, MpmThreadCtx * mpm_thread_ctx, PrefilterRuleStore * pmq, const uint8_t * buf, uint32_t buflen)
SCACTileSearchSmall32()
uint32_t SCACTileSearchSmall32 (const SCACTileSearchCtx * ctx, MpmThreadCtx * mpm_thread_ctx, PrefilterRuleStore * pmq, const uint8_t * buf, uint32_t buflen)
SCACTileSearchSmall64()
uint32_t SCACTileSearchSmall64 (const SCACTileSearchCtx * ctx, MpmThreadCtx * mpm_thread_ctx, PrefilterRuleStore * pmq, const uint8_t * buf, uint32_t buflen)
SCACTileSearchSmall8()
uint32_t SCACTileSearchSmall8 (const SCACTileSearchCtx * ctx, MpmThreadCtx * mpm_thread_ctx, PrefilterRuleStore * pmq, const uint8_t * buf, uint32_t buflen)
SCACTileSearchTiny128()
uint32_t SCACTileSearchTiny128 (const SCACTileSearchCtx * ctx, MpmThreadCtx * mpm_thread_ctx, PrefilterRuleStore * pmq, const uint8_t * buf, uint32_t buflen)
SCACTileSearchTiny16()
uint32_t SCACTileSearchTiny16 (const SCACTileSearchCtx * ctx, MpmThreadCtx * mpm_thread_ctx, PrefilterRuleStore * pmq, const uint8_t * buf, uint32_t buflen)
SCACTileSearchTiny256()
uint32_t SCACTileSearchTiny256 (const SCACTileSearchCtx * ctx, MpmThreadCtx * mpm_thread_ctx, PrefilterRuleStore * pmq, const uint8_t * buf, uint32_t buflen)
SCACTileSearchTiny32()
uint32_t SCACTileSearchTiny32 (const SCACTileSearchCtx * ctx, MpmThreadCtx * mpm_thread_ctx, PrefilterRuleStore * pmq, const uint8_t * buf, uint32_t buflen)
SCACTileSearchTiny64()
uint32_t SCACTileSearchTiny64 (const SCACTileSearchCtx * ctx, MpmThreadCtx * mpm_thread_ctx, PrefilterRuleStore * pmq, const uint8_t * buf, uint32_t buflen)
SCACTileSearchTiny8()
uint32_t SCACTileSearchTiny8 (const SCACTileSearchCtx * ctx, MpmThreadCtx * mpm_thread_ctx, PrefilterRuleStore * pmq, const uint8_t * buf, uint32_t buflen)