suricata: /Users/jlu/suricata/src/util-conf.c File Reference
util-conf.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "conf.h"
#include "runmodes.h"
#include "util-conf.h"
Functions
TmEcode ConfigSetLogDirectory (const char *name)
const char * ConfigGetLogDirectory ()
TmEcode ConfigCheckLogDirectoryExists (const char *log_dir)
TmEcode ConfigSetDataDirectory (char *name)
const char * ConfigGetDataDirectory ()
TmEcode ConfigCheckDataDirectory (const char *data_dir)
ConfNode * ConfFindDeviceConfig (ConfNode *node, const char *iface)
Find the configuration node for a specific device.
int ConfUnixSocketIsEnable (void)
Detailed Description
Author
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Definition in file util-conf.c.
Function Documentation
ConfFindDeviceConfig()
ConfNode * ConfFindDeviceConfig (ConfNode * node, const char * iface)
Find the configuration node for a specific device.
Basically hunts through the list of maps for the first one with a key of "interface", and a value of the provided interface.
Parameters
node The node to start looking for the device configuration. Typically this would be something like the af-packet or pf-ring node.
iface The name of the interface to find the config for.
Definition at line 129 of file util-conf.c.
References ConfNode_::name, next, TAILQ_FOREACH, and ConfNode_::val.
Referenced by AFPRunModeIsIPS(), and ConfSetIfaceNode().
ConfigCheckDataDirectory()
TmEcode ConfigCheckDataDirectory (const char * data_dir)
Definition at line 102 of file util-conf.c.
References SCEnter, SCReturnInt, TM_ECODE_FAILED, and TM_ECODE_OK.
ConfigCheckLogDirectoryExists()
TmEcode ConfigCheckLogDirectoryExists (const char * log_dir)
Definition at line 54 of file util-conf.c.
References SCEnter, SCReturnInt, TM_ECODE_FAILED, and TM_ECODE_OK.
ConfigGetDataDirectory()
const char * ConfigGetDataDirectory (void)
Definition at line 83 of file util-conf.c.
References ConfGet(), DEFAULT_DATA_DIR, and SCLogDebug.
ConfigGetLogDirectory()
const char * ConfigGetLogDirectory (void)
Definition at line 36 of file util-conf.c.
References ConfGet(), and DEFAULT_LOG_DIR.
Referenced by DumpPatterns(), LogTcpDataLogInitCtx(), RulesDumpMatchArray(), RulesDumpTxMatchArray(), SCProfilingKeywordsGlobalInit(), SCProfilingPrefilterGlobalInit(), and SCProfilingSghsGlobalInit().
ConfigSetDataDirectory()
TmEcode ConfigSetDataDirectory (char * name)
Definition at line 69 of file util-conf.c.
References ConfSetFinal(), strlcpy(), TM_ECODE_FAILED, and TM_ECODE_OK.
ConfigSetLogDirectory()
TmEcode ConfigSetLogDirectory (const char * name)
Definition at line 31 of file util-conf.c.
References ConfSetFinal(), TM_ECODE_FAILED, and TM_ECODE_OK.
Referenced by LLVMFuzzerTestOneInput().
ConfUnixSocketIsEnable()
int ConfUnixSocketIsEnable (void)
Definition at line 144 of file util-conf.c.
References ConfGet(), ConfValIsTrue(), IsRunModeOffline(), RunmodeGetCurrent(), SC_ERR_INVALID_YAML_CONF_ENTRY, SCLogError, and SCLogInfo.