suricata: /Users/jlu/suricata/src/util-var.c File Reference
util-var.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "util-var.h"
#include "flow-var.h"
#include "flow-bit.h"
#include "pkt-var.h"
#include "host-bit.h"
#include "ippair-bit.h"
#include "util-debug.h"
Functions
void XBitFree (XBit *fb)
void GenericVarFree (GenericVar *gv)
void GenericVarAppend (GenericVar **list, GenericVar *gv)
void GenericVarRemove (GenericVar **list, GenericVar *gv)
int AddVariableToResolveList (ResolvedVariablesList *list, const char *var)
void CleanVariableResolveList (ResolvedVariablesList *var_list)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Generic variable utility functions
Definition in file util-var.c.
Function Documentation
AddVariableToResolveList()
int AddVariableToResolveList (ResolvedVariablesList * list, const char * var)
Definition at line 133 of file util-var.c.
CleanVariableResolveList()
void CleanVariableResolveList (ResolvedVariablesList * var_list)
Definition at line 162 of file util-var.c.
References next, SCFree, TAILQ_FIRST, and TAILQ_REMOVE.
GenericVarAppend()
void GenericVarAppend (GenericVar ** list, GenericVar * gv)
Definition at line 92 of file util-var.c.
Referenced by FlowVarAddIdValue(), FlowVarAddIntNoLock(), and FlowVarAddKeyValue().
GenericVarFree()
void GenericVarFree (GenericVar * gv)
Definition at line 47 of file util-var.c.
References DETECT_FLOWBITS, DETECT_FLOWVAR, DETECT_PKTVAR, DETECT_XBITS, FlowBitFree(), FlowVarFree(), GenericVarFree(), GenericVar_::next, PktVarFree(), SCLogDebug, GenericVar_::type, and XBitFree().
Referenced by GenericVarFree().
GenericVarRemove()
void GenericVarRemove (GenericVar ** list, GenericVar * gv)
Definition at line 111 of file util-var.c.
XBitFree()
void XBitFree (XBit * fb)
Definition at line 39 of file util-var.c.
References SCFree.
Referenced by GenericVarFree().