suricata: /Users/jlu/suricata/src/util-mpm.c File Reference
util-mpm.c File Reference
#include "suricata-common.h"
#include "util-mpm.h"
#include "util-debug.h"
#include "util-mpm-ac.h"
#include "util-mpm-ac-bs.h"
#include "util-mpm-ac-ks.h"
#include "util-mpm-hs.h"
#include "util-hashlist.h"
#include "detect-engine.h"
#include "util-misc.h"
#include "conf.h"
#include "conf-yaml-loader.h"
#include "queue.h"
#include "util-unittest.h"
#include "util-memcpy.h"
Macros
#define DEFAULT_MPM MPM_AC
Functions
int32_t MpmFactoryRegisterMpmCtxProfile (DetectEngineCtx *de_ctx, const char *name, const int sm_list)
Register a new Mpm Context.
int32_t MpmFactoryIsMpmCtxAvailable (const DetectEngineCtx *de_ctx, const MpmCtx *mpm_ctx)
MpmCtx * MpmFactoryGetMpmCtxForProfile (const DetectEngineCtx *de_ctx, int32_t id, int direction)
void MpmFactoryReClaimMpmCtx (const DetectEngineCtx *de_ctx, MpmCtx *mpm_ctx)
void MpmFactoryDeRegisterAllMpmCtxProfiles (DetectEngineCtx *de_ctx)
void MpmInitThreadCtx (MpmThreadCtx *mpm_thread_ctx, uint16_t matcher)
void MpmInitCtx (MpmCtx *mpm_ctx, uint8_t matcher)
void MpmTableSetup (void)
int MpmAddPatternCS (struct MpmCtx_ *mpm_ctx, uint8_t *pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
int MpmAddPatternCI (struct MpmCtx_ *mpm_ctx, uint8_t *pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
void MpmFreePattern (MpmCtx *mpm_ctx, MpmPattern *p)
int MpmAddPattern (MpmCtx *mpm_ctx, uint8_t *pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
void MpmRegisterTests (void)
Variables
MpmTableElmt mpm_table [MPM_TABLE_SIZE]
uint8_t mpm_default_matcher
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Pattern matcher utility Functions
Definition in file util-mpm.c.
Macro Definition Documentation
DEFAULT_MPM
#define DEFAULT_MPM MPM_AC
Definition at line 212 of file util-mpm.c.
Function Documentation
MpmAddPattern()
int MpmAddPattern (MpmCtx * mpm_ctx, uint8_t * pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Definition at line 427 of file util-mpm.c.
References flags, MPM_PATTERN_CTX_OWNS_ID, SC_ERR_INVALID_ARGUMENTS, SCLogDebug, and SCLogWarning.
Referenced by SCACAddPatternCI(), SCACAddPatternCS(), SCACBSAddPatternCI(), SCACBSAddPatternCS(), SCACTileAddPatternCI(), and SCACTileAddPatternCS().
MpmAddPatternCI()
int MpmAddPatternCI (struct MpmCtx_ * mpm_ctx, uint8_t * pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Definition at line 250 of file util-mpm.c.
References MpmTableElmt_::AddPatternNocase, flags, mpm_table, MpmCtx_::mpm_type, and offset.
MpmAddPatternCS()
int MpmAddPatternCS (struct MpmCtx_ * mpm_ctx, uint8_t * pat, uint16_t patlen, uint16_t offset, uint16_t depth, uint32_t pid, SigIntId sid, uint8_t flags)
Definition at line 241 of file util-mpm.c.
References MpmTableElmt_::AddPattern, flags, mpm_table, MpmCtx_::mpm_type, and offset.
MpmFactoryDeRegisterAllMpmCtxProfiles()
void MpmFactoryDeRegisterAllMpmCtxProfiles (DetectEngineCtx * de_ctx)
Definition at line 168 of file util-mpm.c.
References de_ctx, MpmTableElmt_::DestroyCtx, MpmCtxFactoryContainer_::items, DetectEngineCtx_::mpm_ctx_factory_container, MpmCtxFactoryItem::mpm_ctx_tc, MpmCtxFactoryItem::mpm_ctx_ts, MPM_NOTSET, mpm_table, MpmCtx_::mpm_type, next, MpmCtxFactoryItem::next, and SCFree.
Referenced by DetectEngineCtxFree().
MpmFactoryGetMpmCtxForProfile()
MpmCtx * MpmFactoryGetMpmCtxForProfile (const DetectEngineCtx * de_ctx, int32_t id, int direction)
Definition at line 130 of file util-mpm.c.
References de_ctx, FatalError, MpmCtxFactoryContainer_::items, MpmCtxFactoryContainer_::max_id, DetectEngineCtx_::mpm_ctx_factory_container, MPM_CTX_FACTORY_UNIQUE_CONTEXT, MpmCtxFactoryItem::next, SC_ERR_FATAL, SC_ERR_INVALID_ARGUMENTS, SCLogError, SCMalloc, and unlikely.
Referenced by DetectMpmPrepareAppMpms(), DetectMpmPrepareBuiltinMpms(), DetectMpmPrepareFrameMpms(), and DetectMpmPreparePktMpms().
MpmFactoryIsMpmCtxAvailable()
int32_t MpmFactoryIsMpmCtxAvailable (const DetectEngineCtx * de_ctx, const MpmCtx * mpm_ctx)
Definition at line 113 of file util-mpm.c.
References de_ctx, MpmCtxFactoryContainer_::items, DetectEngineCtx_::mpm_ctx_factory_container, and MpmCtxFactoryItem::next.
Referenced by MpmFactoryReClaimMpmCtx().
MpmFactoryReClaimMpmCtx()
void MpmFactoryReClaimMpmCtx (const DetectEngineCtx * de_ctx, MpmCtx * mpm_ctx)
Definition at line 156 of file util-mpm.c.
References de_ctx, MpmTableElmt_::DestroyCtx, MPM_NOTSET, mpm_table, MpmCtx_::mpm_type, MpmFactoryIsMpmCtxAvailable(), and SCFree.
MpmFactoryRegisterMpmCtxProfile()
int32_t MpmFactoryRegisterMpmCtxProfile (DetectEngineCtx * de_ctx, const char * name, const int sm_list)
Register a new Mpm Context.
Parameters
name A new profile to be registered to store this MpmCtx.
sm_list sm_list for this name (might be variable with xforms)
Return values
id Return the id created for the new MpmCtx profile.
Definition at line 59 of file util-mpm.c.
References de_ctx, ENGINE_SGH_MPM_FACTORY_CONTEXT_START_ID_RANGE, FatalError, MpmCtx_::flags, MpmCtxFactoryItem::id, MpmCtxFactoryContainer_::items, MpmCtxFactoryContainer_::max_id, DetectEngineCtx_::mpm_ctx_factory_container, MpmCtxFactoryItem::mpm_ctx_tc, MpmCtxFactoryItem::mpm_ctx_ts, MPMCTX_FLAGS_GLOBAL, MpmCtxFactoryItem::name, MpmCtxFactoryItem::next, MpmCtxFactoryContainer_::no_of_items, SC_ERR_FATAL, SCCalloc, MpmCtxFactoryItem::sm_list, and unlikely.
Referenced by DetectAppLayerMpmRegisterByParentId(), and DetectEngineFrameMpmRegister().
MpmFreePattern()
void MpmFreePattern (MpmCtx * mpm_ctx, MpmPattern * p)
Definition at line 349 of file util-mpm.c.
References MpmPattern_::ci, MpmPattern_::cs, MpmPattern_::len, MpmCtx_::memory_cnt, MpmCtx_::memory_size, MpmPattern_::original_pat, and SCFree.
Referenced by SCACBSDestroyCtx(), and SCACDestroyCtx().
MpmInitCtx()
void MpmInitCtx (MpmCtx * mpm_ctx, uint8_t matcher)
Definition at line 200 of file util-mpm.c.
References MpmTableElmt_::InitCtx, mpm_table, and MpmCtx_::mpm_type.
MpmInitThreadCtx()
void MpmInitThreadCtx (MpmThreadCtx * mpm_thread_ctx, uint16_t matcher)
Definition at line 195 of file util-mpm.c.
References MpmTableElmt_::InitThreadCtx, and mpm_table.
Referenced by PatternMatchThreadPrepare().
MpmRegisterTests()
void MpmRegisterTests (void)
Definition at line 563 of file util-mpm.c.
References g_ut_modules, MPM_NOTSET, mpm_table, and MPM_TABLE_SIZE.
MpmTableSetup()
void MpmTableSetup (void)
Definition at line 215 of file util-mpm.c.
References DEFAULT_MPM, mpm_default_matcher, mpm_table, MpmACBSRegister(), MpmACRegister(), MpmACTileRegister(), MpmHSRegister(), and SCLogInfo.
Referenced by ListAppLayerProtocols(), ListKeywords(), LLVMFuzzerTestOneInput(), PostConfLoadedSetup(), and RunUnittests().
Variable Documentation
mpm_default_matcher
uint8_t mpm_default_matcher
Definition at line 49 of file util-mpm.c.
Referenced by MpmTableSetup(), and PatternMatchDefaultMatcher().
mpm_table
MpmTableElmt mpm_table[MPM_TABLE_SIZE]
Definition at line 48 of file util-mpm.c.
Referenced by DetectMpmPrepareAppMpms(), DetectMpmPrepareBuiltinMpms(), DetectMpmPrepareFrameMpms(), DetectMpmPreparePktMpms(), MpmACBSRegister(), MpmACRegister(), MpmACTileRegister(), MpmAddPatternCI(), MpmAddPatternCS(), MpmFactoryDeRegisterAllMpmCtxProfiles(), MpmFactoryReClaimMpmCtx(), MpmInitCtx(), MpmInitThreadCtx(), MpmRegisterTests(), MpmTableSetup(), PatternMatchDefaultMatcher(), PatternMatchDestroy(), and PatternMatchThreadDestroy().