suricata: /Users/jlu/suricata/src/util-running-modes.h File Reference
util-running-modes.h File Reference
Functions
int ListKeywords (const char *keyword_info)
int ListAppLayerProtocols (const char *conf_filename)
Detailed Description
Author
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Definition in file util-running-modes.h.
Function Documentation
ListAppLayerProtocols()
int ListAppLayerProtocols (const char * conf_filename)
Definition at line 42 of file util-running-modes.c.
References AppLayerListSupportedProtocols(), AppLayerSetup(), ConfYamlLoadFile(), MpmTableSetup(), SCLogLoadConfig(), SpmTableSetup(), and TM_ECODE_DONE.
ListKeywords()
int ListKeywords (const char * keyword_info)
Definition at line 32 of file util-running-modes.c.
References AppLayerSetup(), MpmTableSetup(), SCLogLoadConfig(), SigTableList(), SigTableSetup(), and SpmTableSetup().