suricata: /Users/jlu/suricata/src/util-storage.c File Reference
util-storage.c File Reference
#include "suricata-common.h"
#include "util-unittest.h"
#include "util-storage.h"
Data Structures
struct StorageMapping_
struct StorageList_
list of StorageMapping used at registration time
struct StorageTest02Data
Typedefs
typedef struct StorageMapping_ StorageMapping
typedef struct StorageList_ StorageList
list of StorageMapping used at registration time
Functions
void StorageInit (void)
void StorageCleanup (void)
int StorageRegister (const StorageEnum type, const char *name, const unsigned int size, void *(*Alloc)(unsigned int), void(*Free)(void *))
Register new storage.
int StorageFinalize (void)
unsigned int StorageGetCnt (StorageEnum type)
unsigned int StorageGetSize (StorageEnum type)
get the size of the void array used to store the pointers
void * StorageGetById (const Storage *storage, const StorageEnum type, const int id)
get storage for id
int StorageSetById (Storage *storage, const StorageEnum type, const int id, void *ptr)
set storage for id
void * StorageAllocByIdPrealloc (Storage *storage, StorageEnum type, int id)
AllocById func for prealloc'd base storage (storage ptrs are part of another memory block)
void * StorageAllocById (Storage **storage, StorageEnum type, int id)
AllocById func for when we manage the Storage ptr itself.
void StorageFreeById (Storage *storage, StorageEnum type, int id)
void StorageFreeAll (Storage *storage, StorageEnum type)
void StorageFree (Storage **storage, StorageEnum type)
void StorageRegisterTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Storage API
Definition in file util-storage.c.
Typedef Documentation
StorageList
typedef struct StorageList_ StorageList
list of StorageMapping used at registration time
StorageMapping
typedef struct StorageMapping_ StorageMapping
Function Documentation
StorageAllocById()
void * StorageAllocById (Storage ** storage, StorageEnum type, int id)
AllocById func for when we manage the Storage ptr itself.
Definition at line 257 of file util-storage.c.
References BUG_ON.
StorageAllocByIdPrealloc()
void * StorageAllocByIdPrealloc (Storage * storage, StorageEnum type, int id)
AllocById func for prealloc'd base storage (storage ptrs are part of another memory block)
Definition at line 239 of file util-storage.c.
References BUG_ON.
Referenced by FlowAllocStorageById(), HostAllocStorageById(), IPPairAllocStorageById(), and LiveDevAllocStorageById().
StorageCleanup()
void StorageCleanup (void)
Definition at line 75 of file util-storage.c.
StorageFinalize()
int StorageFinalize (void)
Definition at line 139 of file util-storage.c.
Referenced by RunUnittests().
StorageFree()
void StorageFree (Storage ** storage, StorageEnum type)
Definition at line 333 of file util-storage.c.
References BUG_ON.
StorageFreeAll()
void StorageFreeAll (Storage * storage, StorageEnum type)
Definition at line 310 of file util-storage.c.
References BUG_ON.
Referenced by FlowFreeStorage(), HostFreeStorage(), IPPairFreeStorage(), and LiveDevFreeStorage().
StorageFreeById()
void StorageFreeById (Storage * storage, StorageEnum type, int id)
Definition at line 288 of file util-storage.c.
References BUG_ON.
Referenced by FlowFreeStorageById(), HostFreeStorageById(), IPPairFreeStorageById(), and LiveDevFreeStorageById().
StorageGetById()
void * StorageGetById (const Storage * storage, const StorageEnum type, const int id)
get storage for id
Definition at line 216 of file util-storage.c.
References BUG_ON.
Referenced by FlowGetStorageById(), HostGetStorageById(), IPPairGetStorageById(), and LiveDevGetStorageById().
StorageGetCnt()
unsigned int StorageGetCnt (StorageEnum type)
Definition at line 200 of file util-storage.c.
StorageGetSize()
unsigned int StorageGetSize (StorageEnum type)
get the size of the void array used to store the pointers
Return values
size size in bytes, can return 0 if not storage is needed
Todo:
we could return -1 when registration isn't closed yet, however this will break lots of tests currently, so not doing it now
Definition at line 211 of file util-storage.c.
Referenced by FlowStorageSize(), HostStorageSize(), IPPairStorageSize(), and LiveDevStorageSize().
StorageInit()
void StorageInit (void)
Definition at line 67 of file util-storage.c.
Referenced by PostConfLoadedSetup(), and RunUnittests().
StorageRegister()
int StorageRegister (const StorageEnum type, const char * name, const unsigned int size, void *(*)(unsigned int) Alloc, void(*)(void *) Free)
Register new storage.
Parameters
type type from StorageEnum
name name
size size of the per instance storage
Alloc alloc function for per instance storage
Free free function for per instance storage
Note
if size == ptr size (so sizeof(void *)) and Alloc == NULL the API just gives the caller a ptr to store something it alloc'ed itself.
Definition at line 99 of file util-storage.c.
Referenced by FlowStorageRegister(), HostStorageRegister(), IPPairStorageRegister(), and LiveDevStorageRegister().
StorageRegisterTests()
void StorageRegisterTests (void)
Definition at line 545 of file util-storage.c.
References UtRegisterTest().
StorageSetById()
int StorageSetById (Storage * storage, const StorageEnum type, const int id, void * ptr)
set storage for id
Definition at line 227 of file util-storage.c.
References BUG_ON.
Referenced by FlowSetStorageById(), HostSetStorageById(), IPPairSetStorageById(), and LiveDevSetStorageById().