suricata: /Users/jlu/suricata/src/util-mpm-ac-bs.h File Reference
util-mpm-ac-bs.h File Reference
#include "util-mpm.h"
Data Structures
struct SCACBSPatternList_
struct SCACBSOutputTable_
struct SCACBSCtx_
struct SCACBSThreadCtx_
Macros
#define SC_AC_BS_STATE_TYPE_U16 uint16_t
#define SC_AC_BS_STATE_TYPE_U32 uint32_t
Typedefs
typedef struct SCACBSPatternList_ SCACBSPatternList
typedef struct SCACBSOutputTable_ SCACBSOutputTable
typedef struct SCACBSCtx_ SCACBSCtx
typedef struct SCACBSThreadCtx_ SCACBSThreadCtx
Functions
void MpmACBSRegister (void)
Register the aho-corasick mpm.
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file util-mpm-ac-bs.h.
Macro Definition Documentation
SC_AC_BS_STATE_TYPE_U16
#define SC_AC_BS_STATE_TYPE_U16 uint16_t
Definition at line 27 of file util-mpm-ac-bs.h.
SC_AC_BS_STATE_TYPE_U32
#define SC_AC_BS_STATE_TYPE_U32 uint32_t
Definition at line 28 of file util-mpm-ac-bs.h.
Typedef Documentation
SCACBSCtx
typedef struct SCACBSCtx_ SCACBSCtx
SCACBSOutputTable
typedef struct SCACBSOutputTable_ SCACBSOutputTable
SCACBSPatternList
typedef struct SCACBSPatternList_ SCACBSPatternList
SCACBSThreadCtx
typedef struct SCACBSThreadCtx_ SCACBSThreadCtx
Function Documentation
MpmACBSRegister()
void MpmACBSRegister (void)
Register the aho-corasick mpm.
Definition at line 97 of file util-mpm-ac-bs.c.
References MpmTableElmt_::AddPattern, MpmTableElmt_::AddPatternNocase, MpmTableElmt_::DestroyCtx, MpmTableElmt_::DestroyThreadCtx, MpmTableElmt_::InitCtx, MpmTableElmt_::InitThreadCtx, MPM_AC_BS, mpm_table, MpmTableElmt_::name, MpmTableElmt_::Prepare, MpmTableElmt_::PrintCtx, MpmTableElmt_::PrintThreadCtx, MpmTableElmt_::RegisterUnittests, SCACBSAddPatternCI(), SCACBSAddPatternCS(), SCACBSDestroyCtx(), SCACBSDestroyThreadCtx(), SCACBSInitCtx(), SCACBSInitThreadCtx(), SCACBSPreparePatterns(), SCACBSPrintInfo(), SCACBSPrintSearchStats(), SCACBSRegisterTests(), SCACBSSearch(), and MpmTableElmt_::Search.
Referenced by MpmTableSetup().