suricata: /Users/jlu/suricata/src/util-misc.c File Reference
util-misc.c File Reference
#include "suricata-common.h"
#include "suricata.h"
#include "util-byte.h"
#include "util-debug.h"
#include "util-unittest.h"
#include "util-misc.h"
Macros
#define PARSE_REGEX "^\\s*(\\d+(?:.\\d+)?)\\s*([a-zA-Z]{2})?\\s*$"
Functions
void ParseSizeInit (void)
void ParseSizeDeinit (void)
int ParseSizeStringU8 (const char *size, uint8_t *res)
int ParseSizeStringU16 (const char *size, uint16_t *res)
int ParseSizeStringU32 (const char *size, uint32_t *res)
int ParseSizeStringU64 (const char *size, uint64_t *res)
void ShortenString (const char *input, char *output, size_t output_size, char c)
void UtilMiscRegisterTests (void)
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file util-misc.c.
Macro Definition Documentation
PARSE_REGEX
#define PARSE_REGEX "^\\s*(\\d+(?:.\\d+)?)\\s*([a-zA-Z]{2})?\\s*$"
Definition at line 31 of file util-misc.c.
Function Documentation
ParseSizeDeinit()
void ParseSizeDeinit (void)
Definition at line 55 of file util-misc.c.
ParseSizeInit()
void ParseSizeInit (void)
Definition at line 35 of file util-misc.c.
Referenced by InitGlobal().
ParseSizeStringU16()
int ParseSizeStringU16 (const char * size, uint16_t * res)
Definition at line 166 of file util-misc.c.
References res.
Referenced by StreamTcpInitConfig().
ParseSizeStringU32()
int ParseSizeStringU32 (const char * size, uint32_t * res)
Definition at line 183 of file util-misc.c.
References res.
Referenced by RegisterMQTTParsers(), and StreamTcpInitConfig().
ParseSizeStringU64()
int ParseSizeStringU64 (const char * size, uint64_t * res)
Definition at line 200 of file util-misc.c.
References res.
Referenced by FlowInitConfig(), HTPParseMemcap(), HttpRangeContainersInit(), RunModeInitialize(), and StreamTcpInitConfig().
ParseSizeStringU8()
int ParseSizeStringU8 (const char * size, uint8_t * res)
Definition at line 149 of file util-misc.c.
References res.
ShortenString()
void ShortenString (const char * input, char * output, size_t output_size, char c)
Definition at line 217 of file util-misc.c.
References strlcat().
Referenced by DetectAppLayerMpmRegisterByParentId().
UtilMiscRegisterTests()
void UtilMiscRegisterTests (void)
Definition at line 1169 of file util-misc.c.
References UtRegisterTest().