suricata: /Users/jlu/suricata/src/util-reference-config.c File Reference
util-reference-config.c File Reference
#include "suricata-common.h"
#include "detect.h"
#include "detect-engine.h"
#include "util-hash.h"
#include "util-reference-config.h"
#include "conf.h"
#include "util-unittest.h"
#include "util-error.h"
#include "util-debug.h"
#include "util-fmemopen.h"
Macros
#define SC_RCONF_REGEX "^\\s*config\\s+reference\\s*:\\s*([a-zA-Z][a-zA-Z0-9-_]*)\\s+(.+)\\s*$"
#define SC_RCONF_DEFAULT_FILE_PATH CONFIG_DIR "/reference.config"
Functions
uint32_t SCRConfReferenceHashFunc (HashTable *ht, void *data, uint16_t datalen)
Hashing function to be used to hash the Reference name. Would be supplied as an argument to the HashTableInit function for DetectEngineCtx->reference_conf_ht.
char SCRConfReferenceHashCompareFunc (void *data1, uint16_t datalen1, void *data2, uint16_t datalen2)
Used to compare two References that have been stored in the HashTable. This function is supplied as an argument to the HashTableInit function for DetectionEngineCtx->reference_conf_ct.
void SCRConfReferenceHashFree (void *data)
Used to free the Reference Config Hash Data that was stored in DetectEngineCtx->reference_conf_ht Hashtable.
void SCReferenceConfInit (void)
void SCReferenceConfDeinit (void)
void SCRConfDeInitContext (DetectEngineCtx *de_ctx)
Releases de_ctx resources related to Reference Config API.
int SCRConfAddReference (DetectEngineCtx *de_ctx, const char *line)
Parses a line from the reference config file and adds it to Reference Config hash table DetectEngineCtx->reference_conf_ht.
SCRConfReference * SCRConfAllocSCRConfReference (const char *system, const char *url)
Returns a new SCRConfReference instance. The reference string is converted into lowercase, before being assigned to the instance.
void SCRConfDeAllocSCRConfReference (SCRConfReference *ref)
Frees a SCRConfReference instance.
int SCRConfLoadReferenceConfigFile (DetectEngineCtx *de_ctx, FILE *fd)
Loads the Reference info from the reference.config file.
SCRConfReference * SCRConfGetReference (const char *rconf_name, DetectEngineCtx *de_ctx)
Gets the reference config from the corresponding hash table stored in the Detection Engine Context's reference conf ht, given the reference name.
FILE * SCRConfGenerateValidDummyReferenceConfigFD01 (void)
Creates a dummy reference config, with all valid references, for testing purposes.
FILE * SCRConfGenerateInValidDummyReferenceConfigFD02 (void)
Creates a dummy reference config, with some valid references and a couple of invalid references, for testing purposes.
FILE * SCRConfGenerateInValidDummyReferenceConfigFD03 (void)
Creates a dummy reference config, with all invalid references, for testing purposes.
void SCRConfRegisterTests (void)
This function registers unit tests for Reference Config API.
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file util-reference-config.c.
Macro Definition Documentation
SC_RCONF_DEFAULT_FILE_PATH
#define SC_RCONF_DEFAULT_FILE_PATH CONFIG_DIR "/reference.config"
Definition at line 42 of file util-reference-config.c.
SC_RCONF_REGEX
#define SC_RCONF_REGEX "^\\s*config\\s+reference\\s*:\\s*([a-zA-Z][a-zA-Z0-9-_]*)\\s+(.+)\\s*$"
Definition at line 39 of file util-reference-config.c.
Function Documentation
SCRConfAddReference()
int SCRConfAddReference (DetectEngineCtx * de_ctx, const char * line)
Parses a line from the reference config file and adds it to Reference Config hash table DetectEngineCtx->reference_conf_ht.
Parameters
rawstr Pointer to the string to be parsed.
de_ctx Pointer to the Detection Engine Context.
Return values
0 On success.
-1 On failure.
Definition at line 230 of file util-reference-config.c.
References REFERENCE_CONTENT_NAME_MAX, and REFERENCE_SYSTEM_NAME_MAX.
SCRConfAllocSCRConfReference()
SCRConfReference * SCRConfAllocSCRConfReference (const char * system, const char * url)
Returns a new SCRConfReference instance. The reference string is converted into lowercase, before being assigned to the instance.
Parameters
system Pointer to the system.
url Pointer to the reference url.
Return values
ref Pointer to the new instance of SCRConfReference.
Definition at line 357 of file util-reference-config.c.
References SC_ERR_INVALID_SIGNATURE, SCLogError, SCMalloc, and SCRConfReference_::system.
Referenced by SCRConfGetReference().
SCRConfDeAllocSCRConfReference()
void SCRConfDeAllocSCRConfReference (SCRConfReference * ref)
Frees a SCRConfReference instance.
Parameters
Pointer to the SCRConfReference instance that has to be freed.
Definition at line 391 of file util-reference-config.c.
References SCFree, SCRConfReference_::system, and SCRConfReference_::url.
Referenced by SCRConfGetReference(), and SCRConfReferenceHashFree().
SCRConfDeInitContext()
void SCRConfDeInitContext (DetectEngineCtx * de_ctx)
Releases de_ctx resources related to Reference Config API.
Definition at line 187 of file util-reference-config.c.
References de_ctx, HashTableFree(), and DetectEngineCtx_::reference_conf_ht.
Referenced by DetectEngineCtxFree().
SCRConfGenerateInValidDummyReferenceConfigFD02()
FILE * SCRConfGenerateInValidDummyReferenceConfigFD02 (void)
Creates a dummy reference config, with some valid references and a couple of invalid references, for testing purposes.
Definition at line 569 of file util-reference-config.c.
References SCFmemopen, and SCLogDebug.
SCRConfGenerateInValidDummyReferenceConfigFD03()
FILE * SCRConfGenerateInValidDummyReferenceConfigFD03 (void)
Creates a dummy reference config, with all invalid references, for testing purposes.
Definition at line 589 of file util-reference-config.c.
References SCFmemopen, and SCLogDebug.
SCRConfGenerateValidDummyReferenceConfigFD01()
FILE * SCRConfGenerateValidDummyReferenceConfigFD01 (void)
Creates a dummy reference config, with all valid references, for testing purposes.
Definition at line 549 of file util-reference-config.c.
References SCFmemopen, and SCLogDebug.
SCRConfGetReference()
SCRConfReference * SCRConfGetReference (const char * rconf_name, DetectEngineCtx * de_ctx)
Gets the reference config from the corresponding hash table stored in the Detection Engine Context's reference conf ht, given the reference name.
Parameters
ct_name Pointer to the reference name that has to be looked up.
de_ctx Pointer to the Detection Engine Context.
Return values
lookup_rconf_info Pointer to the SCRConfReference instance from the hash table on success; NULL on failure.
Definition at line 527 of file util-reference-config.c.
References de_ctx, HashTableLookup(), DetectEngineCtx_::reference_conf_ht, SCRConfAllocSCRConfReference(), and SCRConfDeAllocSCRConfReference().
SCRConfLoadReferenceConfigFile()
int SCRConfLoadReferenceConfigFile (DetectEngineCtx * de_ctx, FILE * fd)
Loads the Reference info from the reference.config file.
   The reference.config file contains references that can be used in
   Signatures.  Each line of the file should  have the following format -
   config reference: system_name, reference_url.
Parameters
de_ctx Pointer to the Detection Engine Context that should be updated with reference information.
Return values
0 On success.
-1 On failure.
Definition at line 496 of file util-reference-config.c.
SCRConfReferenceHashCompareFunc()
char SCRConfReferenceHashCompareFunc (void * data1, uint16_t datalen1, void * data2, uint16_t datalen2)
Used to compare two References that have been stored in the HashTable. This function is supplied as an argument to the HashTableInit function for DetectionEngineCtx->reference_conf_ct.
Parameters
data1 Pointer to the first SCRConfReference to be compared.
len1 Not used by this function.
data2 Pointer to the second SCRConfReference to be compared.
len2 Not used by this function.
Return values
1 On data1 and data2 being equal.
0 On data1 and data2 not being equal.
Definition at line 445 of file util-reference-config.c.
References SCLogDebug, and SCRConfReference_::system.
SCRConfReferenceHashFree()
void SCRConfReferenceHashFree (void * data)
Used to free the Reference Config Hash Data that was stored in DetectEngineCtx->reference_conf_ht Hashtable.
Parameters
data Pointer to the data that has to be freed.
Definition at line 476 of file util-reference-config.c.
References SCRConfDeAllocSCRConfReference().
SCRConfReferenceHashFunc()
uint32_t SCRConfReferenceHashFunc (HashTable * ht, void * data, uint16_t datalen)
Hashing function to be used to hash the Reference name. Would be supplied as an argument to the HashTableInit function for DetectEngineCtx->reference_conf_ht.
Parameters
ht Pointer to the HashTable.
data Pointer to the data to be hashed. In this case, the data would be a pointer to a SCRConfReference instance.
datalen Not used by this function.
Definition at line 416 of file util-reference-config.c.
References HashTable_::array_size, len, SCRConfReference_::system, and u8_tolower.
SCRConfRegisterTests()
void SCRConfRegisterTests (void)
This function registers unit tests for Reference Config API.
Definition at line 786 of file util-reference-config.c.
References UtRegisterTest().
SCReferenceConfDeinit()
void SCReferenceConfDeinit (void)
Definition at line 77 of file util-reference-config.c.
SCReferenceConfInit()
void SCReferenceConfInit (void)
Definition at line 56 of file util-reference-config.c.
Referenced by LLVMFuzzerTestOneInput(), PostConfLoadedDetectSetup(), and RunUnittests().