suricata: /Users/jlu/suricata/src/util-ioctl.c File Reference
util-ioctl.c File Reference
#include "suricata-common.h"
#include "conf.h"
#include "util-device.h"
#include "decode-sll.h"
#include "util-ioctl.h"
Functions
int GetIfaceMTU (const char *pcap_dev)
output the link MTU
int GetIfaceMaxPacketSize (const char *pcap_dev)
output max packet size for a link
int GetIfaceOffloading (const char *dev, int csum, int other)
output offloading status of the link
int DisableIfaceOffloading (LiveDevice *dev, int csum, int other)
void RestoreIfaceOffloading (LiveDevice *dev)
int GetIfaceRSSQueuesNum (const char *pcap_dev)
Detailed Description
Author
Eric Leblond eric@.nosp@m.regi.nosp@m.t.org
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file util-ioctl.c.
Function Documentation
DisableIfaceOffloading()
int DisableIfaceOffloading (LiveDevice * dev, int csum, int other)
Definition at line 708 of file util-ioctl.c.
References LiveDevice_::offload_orig.
GetIfaceMaxPacketSize()
int GetIfaceMaxPacketSize (const char * pcap_dev)
output max packet size for a link
This does a best effort to find the maximum packet size for the link. In case of uncertainty, it will output a majorant to be sure avoid the cost of dynamic allocation.
Parameters
Name of a network interface
Return values
0 in case of error
Definition at line 133 of file util-ioctl.c.
References GetIfaceMTU().
GetIfaceMTU()
int GetIfaceMTU (const char * pcap_dev)
output the link MTU
Parameters
Name of link
Return values
-1 in case of error, 0 if MTU can not be found
Definition at line 92 of file util-ioctl.c.
References SC_ERR_SYSCALL, SCLogInfo, SCLogWarning, and strlcpy().
Referenced by GetIfaceMaxPacketSize().
GetIfaceOffloading()
int GetIfaceOffloading (const char * dev, int csum, int other)
output offloading status of the link
Test interface for offloading features. If one of them is activated then suricata mays received packets merge at reception. The result is oversized packets and this may cause some serious problem in some capture mode where the size of the packet is limited (AF_PACKET in V2 more for example).
Parameters
Name of link
csum check if checksums are offloaded
other check if other things are offloaded: TSO, GRO, etc.
Return values
-1 in case of error, 0 if none, 1 if some
Definition at line 695 of file util-ioctl.c.
GetIfaceRSSQueuesNum()
int GetIfaceRSSQueuesNum (const char * pcap_dev)
Definition at line 738 of file util-ioctl.c.
References SC_ERR_SYSCALL, SCLogInfo, SCLogWarning, and strlcpy().
RestoreIfaceOffloading()
void RestoreIfaceOffloading (LiveDevice * dev)
Definition at line 725 of file util-ioctl.c.
References LiveDevice_::offload_orig.