suricata: /Users/jlu/suricata/src/util-hash.h File Reference
util-hash.h File Reference
Data Structures
struct HashTableBucket_
struct HashTable_
Macros
#define HASH_NO_SIZE 0
Typedefs
typedef struct HashTableBucket_ HashTableBucket
typedef struct HashTable_ HashTable
Functions
HashTable * HashTableInit (uint32_t, uint32_t(*Hash)(struct HashTable_ *, void *, uint16_t), char(*Compare)(void *, uint16_t, void *, uint16_t), void(*Free)(void *))
void HashTableFree (HashTable *)
void HashTablePrint (HashTable *)
int HashTableAdd (HashTable *, void *, uint16_t)
int HashTableRemove (HashTable *, void *, uint16_t)
void * HashTableLookup (HashTable *, void *, uint16_t)
uint32_t HashTableGenericHash (HashTable *, void *, uint16_t)
char HashTableDefaultCompare (void *, uint16_t, void *, uint16_t)
void HashTableRegisterTests (void)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file util-hash.h.
Macro Definition Documentation
HASH_NO_SIZE
#define HASH_NO_SIZE 0
Definition at line 46 of file util-hash.h.
Typedef Documentation
HashTable
typedef struct HashTable_ HashTable
HashTableBucket
typedef struct HashTableBucket_ HashTableBucket
Function Documentation
HashTableAdd()
int HashTableAdd (HashTable * ht, void * data, uint16_t datalen)
Definition at line 113 of file util-hash.c.
References HashTable_::array, HashTable_::array_size, HashTable_::count, HashTableBucket_::data, HashTable_::Hash, HashTableBucket_::next, SC_ERR_INVALID_VALUE, SCFree, SCLogWarning, SCMalloc, HashTableBucket_::size, and unlikely.
HashTableDefaultCompare()
char HashTableDefaultCompare (void * data1, uint16_t len1, void * data2, uint16_t len2)
Definition at line 238 of file util-hash.c.
References SCMemcmp.
Referenced by HashTableInit().
HashTableFree()
void HashTableFree (HashTable * ht)
Definition at line 79 of file util-hash.c.
References HashTable_::array, HashTable_::array_size, HashTableBucket_::data, HashTable_::Free, HashTableBucket_::next, and SCFree.
Referenced by DetectEngineThreadCtxDeinit(), DetectMetadataHashFree(), SCClassConfDeInitContext(), and SCRConfDeInitContext().
HashTableGenericHash()
uint32_t HashTableGenericHash (HashTable * ht, void * data, uint16_t datalen)
Definition at line 221 of file util-hash.c.
References HashTable_::array_size.
HashTableInit()
HashTable * HashTableInit (uint32_t size, uint32_t(*)(struct HashTable_ *, void *, uint16_t) Hash, char(*)(void *, uint16_t, void *, uint16_t) Compare, void(*)(void *) Free)
Definition at line 34 of file util-hash.c.
References HashTable_::array, HashTable_::array_size, HashTable_::Compare, HashTable_::Free, HashTable_::Hash, HashTableDefaultCompare(), SCFree, SCMalloc, and unlikely.
Referenced by DetectMetadataHashInit().
HashTableLookup()
void * HashTableLookup (HashTable * ht, void * data, uint16_t datalen)
Definition at line 193 of file util-hash.c.
References HashTable_::array, HashTable_::array_size, HashTable_::Compare, HashTableBucket_::data, HashTable_::Hash, HashTableBucket_::next, SC_ERR_INVALID_VALUE, SCLogWarning, and HashTableBucket_::size.
Referenced by SCClassConfGetClasstype(), SCGetProtoByName(), and SCRConfGetReference().
HashTablePrint()
void HashTablePrint (HashTable * ht)
Definition at line 105 of file util-hash.c.
References HashTable_::array_size, and HashTable_::Hash.
HashTableRegisterTests()
void HashTableRegisterTests (void)
Definition at line 427 of file util-hash.c.
References UtRegisterTest().
HashTableRemove()
int HashTableRemove (HashTable * ht, void * data, uint16_t datalen)
Definition at line 152 of file util-hash.c.
References HashTable_::array, HashTable_::Compare, HashTableBucket_::data, HashTable_::Free, HashTable_::Hash, HashTableBucket_::next, SCFree, and HashTableBucket_::size.