suricata: /Users/jlu/suricata/src/util-rule-vars.h File Reference
util-rule-vars.h File Reference
Enumerations
enum SCRuleVarsType { SC_RULE_VARS_ADDRESS_GROUPS , SC_RULE_VARS_PORT_GROUPS }
Functions
const char * SCRuleVarsGetConfVar (const DetectEngineCtx *, const char *, SCRuleVarsType)
void SCRuleVarsRegisterTests (void)
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file util-rule-vars.h.
Enumeration Type Documentation
SCRuleVarsType
enum SCRuleVarsType
Enum indicating the various vars type in the yaml conf file
Enumerator
SC_RULE_VARS_ADDRESS_GROUPS
SC_RULE_VARS_PORT_GROUPS
Definition at line 28 of file util-rule-vars.h.
Function Documentation
SCRuleVarsGetConfVar()
const char * SCRuleVarsGetConfVar (const DetectEngineCtx * de_ctx, const char * conf_var_name, SCRuleVarsType conf_vars_type)
Definition at line 65 of file util-rule-vars.c.
References ConfGet(), DetectEngineCtx_::config_prefix, de_ctx, SC_ERR_UNDEFINED_VAR, sc_rule_vars_type_map, SCEnter, SCLogDebug, SCLogError, SCMapEnumValueToName(), and SCReturnCharPtr.
SCRuleVarsRegisterTests()
void SCRuleVarsRegisterTests (void)
Definition at line 399 of file util-rule-vars.c.
References UtRegisterTest().