suricata: /Users/jlu/suricata/src/util-debug.h File Reference
util-debug.h File Reference
#include "suricata-common.h"
#include "threads.h"
#include "util-error.h"
#include "util-debug-filters.h"
Data Structures
struct SCLogOPBuffer_
Structure to be used when log_level override support would be provided by the logging module.
struct SCLogOPIfaceCtx_
The output interface context for the logging module.
struct SCLogInitData_
Structure containing init data, that would be passed to SCInitDebugModule()
struct SCLogConfig_
Holds the config state used by the logging api.
Macros
#define SC_LOG_ENV_LOG_LEVEL "SC_LOG_LEVEL"
ENV vars that can be used to set the properties for the logging module.
#define SC_LOG_ENV_LOG_OP_IFACE "SC_LOG_OP_IFACE"
#define SC_LOG_ENV_LOG_FILE "SC_LOG_FILE"
#define SC_LOG_ENV_LOG_FACILITY "SC_LOG_FACILITY"
#define SC_LOG_ENV_LOG_FORMAT "SC_LOG_FORMAT"
#define SC_LOG_ENV_LOG_OP_FILTER "SC_LOG_OP_FILTER"
#define SC_LOG_DEF_LOG_FORMAT_REL "%t - <%d> - "
#define SC_LOG_DEF_LOG_FORMAT_DEV "[%i] %t - (%f:%l) <%d> (%n) -- "
#define SC_LOG_MAX_LOG_MSG_LEN 2048
#define SC_LOG_MAX_LOG_FORMAT_LEN 128
#define SC_LOG_DEF_LOG_LEVEL SC_LOG_INFO
#define SC_LOG_DEF_LOG_OP_IFACE SC_LOG_OP_IFACE_CONSOLE
#define SC_LOG_DEF_LOG_FILE "suricata.log"
#define SC_LOG_DEF_SYSLOG_FACILITY_STR "local0"
#define SC_LOG_DEF_SYSLOG_FACILITY LOG_LOCAL0
#define SC_LOG_FMT_TIME 't' /* Timestamp in standard format */
#define SC_LOG_FMT_PID 'p' /* PID */
#define SC_LOG_FMT_TID 'i' /* Thread ID */
#define SC_LOG_FMT_TM 'm' /* Thread module name */
#define SC_LOG_FMT_LOG_LEVEL 'd' /* Log level */
#define SC_LOG_FMT_FILE_NAME 'f' /* File name */
#define SC_LOG_FMT_LINE 'l' /* Line number */
#define SC_LOG_FMT_FUNCTION 'n' /* Function */
#define SC_LOG_FMT_PREFIX '%'
#define SCLogInfo(...)
Macro used to log INFORMATIONAL messages.
#define SCLogInfoRaw(file, func, line, ...)
#define SCLogConfig(...)
#define SCLogPerf(...)
#define SCLogNotice(...)
Macro used to log NOTICE messages.
#define SCLogNoticeRaw(file, func, line, ...)
#define SCLogWarning(err_code, ...)
Macro used to log WARNING messages.
#define SCLogWarningRaw(err_code, file, func, line, ...) SCLogErr(SC_LOG_WARNING, (file), (func), (line), err_code, __VA_ARGS__)
#define SCLogError(err_code, ...)
Macro used to log ERROR messages.
#define SCLogErrorRaw(err_code, file, func, line, ...)
#define SCLogCritical(err_code, ...)
Macro used to log CRITICAL messages.
#define SCLogAlert(err_code, ...)
Macro used to log ALERT messages.
#define SCLogEmerg(err_code, ...)
Macro used to log EMERGENCY messages.
#define SCLogDebug(...) do { } while (0)
#define SCEnter(...)
#define SCReturn return
#define SCReturnInt(x) return x
#define SCReturnUInt(x) return x
#define SCReturnDbl(x) return x
#define SCReturnChar(x) return x
#define SCReturnCharPtr(x) return x
#define SCReturnCT(x, type) return x
#define SCReturnPtr(x, type) return x
#define SCReturnBool(x) return x
#define SCReturnStruct(x) return x
#define FatalError(x, ...)
#define FatalErrorOnInit(x, ...)
Fatal error IF we're starting up, and configured to consider errors to be fatal errors.
#define BOOL2STR(b) (b) ? "true" : "false"
Typedefs
typedef struct SCLogOPBuffer_ SCLogOPBuffer
Structure to be used when log_level override support would be provided by the logging module.
typedef struct SCLogOPIfaceCtx_ SCLogOPIfaceCtx
The output interface context for the logging module.
typedef struct SCLogInitData_ SCLogInitData
Structure containing init data, that would be passed to SCInitDebugModule()
typedef struct SCLogConfig_ SCLogConfig
Holds the config state used by the logging api.
Enumerations
enum SCLogLevel {
SC_LOG_NOTSET = -1 , SC_LOG_NONE = 0 , SC_LOG_EMERGENCY , SC_LOG_ALERT ,
SC_LOG_CRITICAL , SC_LOG_ERROR , SC_LOG_WARNING , SC_LOG_NOTICE ,
SC_LOG_INFO , SC_LOG_PERF , SC_LOG_CONFIG , SC_LOG_DEBUG ,
SC_LOG_LEVEL_MAX
}
The various log levels NOTE: when adding new level, don't forget to update SCLogMapLogLevelToSyslogLevel() or it may result in logging to syslog with LOG_EMERG priority.
enum SCLogOPIface { SC_LOG_OP_IFACE_CONSOLE , SC_LOG_OP_IFACE_FILE , SC_LOG_OP_IFACE_SYSLOG , SC_LOG_OP_IFACE_MAX }
The various output interfaces supported.
enum SCLogOPType { SC_LOG_OP_TYPE_REGULAR = 0 , SC_LOG_OP_TYPE_JSON }
Functions
void SCLog (int x, const char *file, const char *func, const int line, const char *fmt,...) ATTR_FMT_PRINTF(5
void void SCLogErr (int x, const char *file, const char *func, const int line, const int err, const char *fmt,...) ATTR_FMT_PRINTF(6
SCLogInitData * SCLogAllocLogInitData (void)
Returns a pointer to a new SCLogInitData. This is a public interface intended to be used after the logging paramters are read from the conf file.
SCLogOPIfaceCtx * SCLogInitOPIfaceCtx (const char *, const char *, int, const char *)
Creates a new output interface based on the arguments sent. The kind of output interface to be created is decided by the iface_name arg. If iface_name is "file", the arg argument will hold the filename to be used for logging purposes. If iface_name is "syslog", the arg argument holds the facility code. If iface_name is "console", arg is NULL.
void SCLogAppendOPIfaceCtx (SCLogOPIfaceCtx *, SCLogInitData *)
Appends an output_interface to the output_interface list sent in head.
void SCLogInitLogModule (SCLogInitData *)
Initializes the logging module.
void SCLogDeInitLogModule (void)
De-Initializes the logging module.
SCError SCLogMessage (const SCLogLevel, const char *, const unsigned int, const char *, const SCError, const char *message)
Adds the global log_format to the outgoing buffer.
SCLogOPBuffer * SCLogAllocLogOPBuffer (void)
Allocates an output buffer for an output interface. Used when we want the op_interface log_format to override the global_log_format. Currently not used.
int SCLogDebugEnabled (void)
Returns whether debug messages are enabled to be logged or not.
void SCLogRegisterTests (void)
void SCLogLoadConfig (int daemon, int verbose, uint32_t userid, uint32_t groupid)
SCLogLevel SCLogGetLogLevel (void)
Variables
SCLogLevel sc_log_global_log_level
Holds the global log level. Is the same as sc_log_config->log_level.
int sc_log_module_initialized
Used to indicate whether the logging module has been init or not.
int sc_log_module_cleaned
Used to indicate whether the logging module has been cleaned or not.
Detailed Description
Author
Anoop Saldanha anoop.nosp@m.sald.nosp@m.anha@.nosp@m.gmai.nosp@m.l.com
Definition in file util-debug.h.
Macro Definition Documentation
BOOL2STR
#define BOOL2STR (b) (b) ? "true" : "false"
Definition at line 554 of file util-debug.h.
FatalError
#define FatalError (x, ...)
Value:
    do {                                             \
    SCLogError(x, __VA_ARGS__);                                             \
    exit(EXIT_FAILURE);                                                     \
} while(0)
Definition at line 530 of file util-debug.h.
FatalErrorOnInit
#define FatalErrorOnInit (x, ...)
Value:
    do {                                                                                           \
        SC_ATOMIC_EXTERN(unsigned int, engine_stage);                                              \
        int init_errors_fatal = 0;                                                                 \
        (void)ConfGetBool("engine.init-failure-fatal", &init_errors_fatal);                        \
        if (init_errors_fatal && (SC_ATOMIC_GET(engine_stage) == SURICATA_INIT)) {                 \
            SCLogError(x, __VA_ARGS__);                                                            \
            exit(EXIT_FAILURE);                                                                    \
        }                                                                                          \
        SCLogWarning(x, __VA_ARGS__);                                                              \
    } while (0)
Fatal error IF we're starting up, and configured to consider errors to be fatal errors.
Definition at line 538 of file util-debug.h.
SC_LOG_DEF_LOG_FILE
#define SC_LOG_DEF_LOG_FILE "suricata.log"
Definition at line 96 of file util-debug.h.
SC_LOG_DEF_LOG_FORMAT_DEV
#define SC_LOG_DEF_LOG_FORMAT_DEV "[%i] %t - (%f:%l) <%d> (%n) -- "
Definition at line 81 of file util-debug.h.
SC_LOG_DEF_LOG_FORMAT_REL
#define SC_LOG_DEF_LOG_FORMAT_REL "%t - <%d> - "
Definition at line 80 of file util-debug.h.
SC_LOG_DEF_LOG_LEVEL
#define SC_LOG_DEF_LOG_LEVEL SC_LOG_INFO
Definition at line 90 of file util-debug.h.
SC_LOG_DEF_LOG_OP_IFACE
#define SC_LOG_DEF_LOG_OP_IFACE SC_LOG_OP_IFACE_CONSOLE
Definition at line 93 of file util-debug.h.
SC_LOG_DEF_SYSLOG_FACILITY
#define SC_LOG_DEF_SYSLOG_FACILITY LOG_LOCAL0
Definition at line 100 of file util-debug.h.
SC_LOG_DEF_SYSLOG_FACILITY_STR
#define SC_LOG_DEF_SYSLOG_FACILITY_STR "local0"
Definition at line 99 of file util-debug.h.
SC_LOG_ENV_LOG_FACILITY
#define SC_LOG_ENV_LOG_FACILITY "SC_LOG_FACILITY"
Definition at line 39 of file util-debug.h.
SC_LOG_ENV_LOG_FILE
#define SC_LOG_ENV_LOG_FILE "SC_LOG_FILE"
Definition at line 38 of file util-debug.h.
SC_LOG_ENV_LOG_FORMAT
#define SC_LOG_ENV_LOG_FORMAT "SC_LOG_FORMAT"
Definition at line 40 of file util-debug.h.
SC_LOG_ENV_LOG_LEVEL
#define SC_LOG_ENV_LOG_LEVEL "SC_LOG_LEVEL"
ENV vars that can be used to set the properties for the logging module.
Definition at line 36 of file util-debug.h.
SC_LOG_ENV_LOG_OP_FILTER
#define SC_LOG_ENV_LOG_OP_FILTER "SC_LOG_OP_FILTER"
Definition at line 41 of file util-debug.h.
SC_LOG_ENV_LOG_OP_IFACE
#define SC_LOG_ENV_LOG_OP_IFACE "SC_LOG_OP_IFACE"
Definition at line 37 of file util-debug.h.
SC_LOG_FMT_FILE_NAME
#define SC_LOG_FMT_FILE_NAME 'f' /* File name */
Definition at line 192 of file util-debug.h.
SC_LOG_FMT_FUNCTION
#define SC_LOG_FMT_FUNCTION 'n' /* Function */
Definition at line 194 of file util-debug.h.
SC_LOG_FMT_LINE
#define SC_LOG_FMT_LINE 'l' /* Line number */
Definition at line 193 of file util-debug.h.
SC_LOG_FMT_LOG_LEVEL
#define SC_LOG_FMT_LOG_LEVEL 'd' /* Log level */
Definition at line 191 of file util-debug.h.
SC_LOG_FMT_PID
#define SC_LOG_FMT_PID 'p' /* PID */
Definition at line 188 of file util-debug.h.
SC_LOG_FMT_PREFIX
#define SC_LOG_FMT_PREFIX '%'
Definition at line 197 of file util-debug.h.
SC_LOG_FMT_TID
#define SC_LOG_FMT_TID 'i' /* Thread ID */
Definition at line 189 of file util-debug.h.
SC_LOG_FMT_TIME
#define SC_LOG_FMT_TIME 't' /* Timestamp in standard format */
Definition at line 187 of file util-debug.h.
SC_LOG_FMT_TM
#define SC_LOG_FMT_TM 'm' /* Thread module name */
Definition at line 190 of file util-debug.h.
SC_LOG_MAX_LOG_FORMAT_LEN
#define SC_LOG_MAX_LOG_FORMAT_LEN 128
Definition at line 87 of file util-debug.h.
SC_LOG_MAX_LOG_MSG_LEN
#define SC_LOG_MAX_LOG_MSG_LEN 2048
Definition at line 84 of file util-debug.h.
SCEnter
#define SCEnter (...)
Definition at line 298 of file util-debug.h.
SCLogAlert
#define SCLogAlert (err_code, ...)
Value:
        SCLogErr(SC_LOG_ALERT, \
        __FILE__, __FUNCTION__, __LINE__, \
        err_code, __VA_ARGS__)
Macro used to log ALERT messages.
Return values
err_code Error code that has to be logged along with the alert message
... Takes as argument(s), a printf style format message
Definition at line 278 of file util-debug.h.
SCLogConfig
#define SCLogConfig (...)
Value:
        SCLog(SC_LOG_CONFIG, \
        __FILE__, __FUNCTION__, __LINE__, __VA_ARGS__)
Definition at line 220 of file util-debug.h.
SCLogCritical
#define SCLogCritical (err_code, ...)
Value:
        SCLogErr(SC_LOG_CRITICAL, \
        __FILE__, __FUNCTION__, __LINE__, \
        err_code, __VA_ARGS__)
Macro used to log CRITICAL messages.
Return values
err_code Error code that has to be logged along with the critical message
... Takes as argument(s), a printf style format message
Definition at line 268 of file util-debug.h.
SCLogDebug
#define SCLogDebug (...) do { } while (0)
Definition at line 296 of file util-debug.h.
SCLogEmerg
#define SCLogEmerg (err_code, ...)
Value:
        SCLogErr(SC_LOG_EMERGENCY, \
        __FILE__, __FUNCTION__, __LINE__, \
        err_code, __VA_ARGS__)
Macro used to log EMERGENCY messages.
Return values
err_code Error code that has to be logged along with the emergency message
... Takes as argument(s), a printf style format message
Definition at line 288 of file util-debug.h.
SCLogError
#define SCLogError (err_code, ...)
Value:
        SCLogErr(SC_LOG_ERROR, \
        __FILE__, __FUNCTION__, __LINE__, \
        err_code, __VA_ARGS__)
Macro used to log ERROR messages.
Return values
err_code Error code that has to be logged along with the error message
... Takes as argument(s), a printf style format message
Definition at line 255 of file util-debug.h.
SCLogErrorRaw
#define SCLogErrorRaw (err_code, file, func, line, ...)
Value:
        SCLogErr(SC_LOG_ERROR, \
        (file), (func), (line), err_code, __VA_ARGS__)
Definition at line 258 of file util-debug.h.
SCLogInfo
#define SCLogInfo (...)
Value:
        SCLog(SC_LOG_INFO, \
        __FILE__, __FUNCTION__, __LINE__, __VA_ARGS__)
Macro used to log INFORMATIONAL messages.
Return values
... Takes as argument(s), a printf style format message
Definition at line 215 of file util-debug.h.
SCLogInfoRaw
#define SCLogInfoRaw (file, func, line, ...)
Value:
        SCLog(SC_LOG_INFO, \
        (file), (func), (line), __VA_ARGS__)
Definition at line 217 of file util-debug.h.
SCLogNotice
#define SCLogNotice (...)
Value:
        SCLog(SC_LOG_NOTICE, \
        __FILE__, __FUNCTION__, __LINE__, __VA_ARGS__)
Macro used to log NOTICE messages.
Return values
... Takes as argument(s), a printf style format message
Definition at line 230 of file util-debug.h.
SCLogNoticeRaw
#define SCLogNoticeRaw (file, func, line, ...)
Value:
        SCLog(SC_LOG_NOTICE, \
        (file), (func), (line), __VA_ARGS__)
Definition at line 232 of file util-debug.h.
SCLogPerf
#define SCLogPerf (...)
Value:
        SCLog(SC_LOG_PERF, \
        __FILE__, __FUNCTION__, __LINE__, __VA_ARGS__)
Definition at line 222 of file util-debug.h.
SCLogWarning
#define SCLogWarning (err_code, ...)
Value:
        SCLogErr(SC_LOG_WARNING, \
        __FILE__, __FUNCTION__, __LINE__, \
        err_code, __VA_ARGS__)
Macro used to log WARNING messages.
Return values
err_code Error code that has to be logged along with the warning message
... Takes as argument(s), a printf style format message
Definition at line 242 of file util-debug.h.
SCLogWarningRaw
#define SCLogWarningRaw (err_code, file, func, line, ...) SCLogErr(SC_LOG_WARNING, (file), (func), (line), err_code, __VA_ARGS__)
Definition at line 245 of file util-debug.h.
SCReturn
#define SCReturn return
Definition at line 300 of file util-debug.h.
SCReturnBool
#define SCReturnBool (x) return x
Definition at line 316 of file util-debug.h.
SCReturnChar
#define SCReturnChar (x) return x
Definition at line 308 of file util-debug.h.
SCReturnCharPtr
#define SCReturnCharPtr (x) return x
Definition at line 310 of file util-debug.h.
SCReturnCT
#define SCReturnCT (x, type) return x
Definition at line 312 of file util-debug.h.
SCReturnDbl
#define SCReturnDbl (x) return x
Definition at line 306 of file util-debug.h.
SCReturnInt
#define SCReturnInt (x) return x
Definition at line 302 of file util-debug.h.
SCReturnPtr
#define SCReturnPtr (x, type) return x
Definition at line 314 of file util-debug.h.
SCReturnStruct
#define SCReturnStruct (x) return x
Definition at line 318 of file util-debug.h.
SCReturnUInt
#define SCReturnUInt (x) return x
Definition at line 304 of file util-debug.h.
Typedef Documentation
SCLogConfig
typedef struct SCLogConfig_ SCLogConfig
Holds the config state used by the logging api.
SCLogInitData
typedef struct SCLogInitData_ SCLogInitData
Structure containing init data, that would be passed to SCInitDebugModule()
SCLogOPBuffer
typedef struct SCLogOPBuffer_ SCLogOPBuffer
Structure to be used when log_level override support would be provided by the logging module.
SCLogOPIfaceCtx
typedef struct SCLogOPIfaceCtx_ SCLogOPIfaceCtx
The output interface context for the logging module.
Enumeration Type Documentation
SCLogLevel
enum SCLogLevel
The various log levels NOTE: when adding new level, don't forget to update SCLogMapLogLevelToSyslogLevel() or it may result in logging to syslog with LOG_EMERG priority.
Enumerator
SC_LOG_NOTSET
SC_LOG_NONE
SC_LOG_EMERGENCY
SC_LOG_ALERT
SC_LOG_CRITICAL
SC_LOG_ERROR
SC_LOG_WARNING
SC_LOG_NOTICE
SC_LOG_INFO
SC_LOG_PERF
SC_LOG_CONFIG
SC_LOG_DEBUG
SC_LOG_LEVEL_MAX
Definition at line 48 of file util-debug.h.
SCLogOPIface
enum SCLogOPIface
The various output interfaces supported.
Enumerator
SC_LOG_OP_IFACE_CONSOLE
SC_LOG_OP_IFACE_FILE
SC_LOG_OP_IFACE_SYSLOG
SC_LOG_OP_IFACE_MAX
Definition at line 67 of file util-debug.h.
SCLogOPType
enum SCLogOPType
Enumerator
SC_LOG_OP_TYPE_REGULAR
SC_LOG_OP_TYPE_JSON
Definition at line 74 of file util-debug.h.
Function Documentation
SCLog()
void SCLog (int x, const char * file, const char * func, const int line, const char * fmt, ...)
SCLogAllocLogInitData()
SCLogInitData * SCLogAllocLogInitData (void)
Returns a pointer to a new SCLogInitData. This is a public interface intended to be used after the logging paramters are read from the conf file.
Return values
sc_lid Pointer to the newly created SCLogInitData \initonly
Definition at line 1148 of file util-debug.c.
References SCMalloc.
Referenced by SCLogLoadConfig().
SCLogAllocLogOPBuffer()
SCLogOPBuffer * SCLogAllocLogOPBuffer (void)
Allocates an output buffer for an output interface. Used when we want the op_interface log_format to override the global_log_format. Currently not used.
Return values
buffer Pointer to the newly created output_buffer
Definition at line 668 of file util-debug.c.
References SCMalloc.
SCLogAppendOPIfaceCtx()
void SCLogAppendOPIfaceCtx (SCLogOPIfaceCtx * iface_ctx, SCLogInitData * sc_lid)
Appends an output_interface to the output_interface list sent in head.
Parameters
iface_ctx Pointer to the output_interface that has to be added to head
head Pointer to the output_interface list
Definition at line 1211 of file util-debug.c.
References head, SCLogOPIfaceCtx_::next, SCLogInitData_::op_ifaces, and SCLogInitData_::op_ifaces_cnt.
SCLogDebugEnabled()
int SCLogDebugEnabled (void)
Returns whether debug messages are enabled to be logged or not.
Return values
1 if debug messages are enabled to be logged
0 if debug messages are not enabled to be logged
Definition at line 649 of file util-debug.c.
References SC_LOG_DEBUG, and sc_log_global_log_level.
Referenced by DetectBytejumpDoMatch(), FlowVarPrint(), HtpBodyPrint(), and SMTPProcessDataChunk().
SCLogDeInitLogModule()
void SCLogDeInitLogModule (void)
De-Initializes the logging module.
Definition at line 1510 of file util-debug.c.
Referenced by SCLogInitLogModule().
SCLogErr()
void void SCLogErr (int x, const char * file, const char * func, const int line, const int err, const char * fmt, ...)
SCLogGetLogLevel()
SCLogLevel SCLogGetLogLevel (void)
Definition at line 968 of file util-debug.c.
References sc_log_global_log_level.
SCLogInitLogModule()
void SCLogInitLogModule (SCLogInitData * sc_lid)
Initializes the logging module.
Parameters
sc_lid The initialization data for the logging module. If sc_lid is NULL, we would stick to the default configuration for the logging subsystem. \initonly
Definition at line 1296 of file util-debug.c.
References FatalError, SC_ERR_FATAL, SCLogDeInitLogModule(), and SCMutexInit.
Referenced by InitGlobal().
SCLogInitOPIfaceCtx()
SCLogOPIfaceCtx * SCLogInitOPIfaceCtx (const char * iface_name, const char * log_format, int log_level, const char * arg)
Creates a new output interface based on the arguments sent. The kind of output interface to be created is decided by the iface_name arg. If iface_name is "file", the arg argument will hold the filename to be used for logging purposes. If iface_name is "syslog", the arg argument holds the facility code. If iface_name is "console", arg is NULL.
Parameters
iface_name Interface name. Can be "console", "file" or "syslog"
log_format Override for the global_log_format
log_level Override for the global_log_level
log_level Parameter required by a particular interface. Explained in the function description
Return values
iface_ctx Pointer to the newly created output interface
Definition at line 1256 of file util-debug.c.
References SC_LOG_DEBUG, SC_LOG_NOTSET, SC_LOG_OP_IFACE_CONSOLE, sc_log_op_iface_map, and SCMapEnumNameToValue().
SCLogLoadConfig()
void SCLogLoadConfig (int daemon, int verbose, uint32_t userid, uint32_t groupid)
Definition at line 1329 of file util-debug.c.
References ConfGet(), ConfGetNode(), SCLogInitData_::global_log_format, SCLogInitData_::global_log_level, MAX, SC_ERR_INVALID_ARGUMENT, sc_log_level_map, SC_LOG_NOTICE, SCLogAllocLogInitData(), SCLogDebug, SCLogError, and SCMapEnumNameToValue().
Referenced by ListAppLayerProtocols(), and ListKeywords().
SCLogMessage()
SCError SCLogMessage (const SCLogLevel log_level, const char * file, const unsigned int line, const char * function, const SCError error_code, const char * message)
Adds the global log_format to the outgoing buffer.
Parameters
log_level log_level of the message that has to be logged
msg Buffer containing the outgoing message
file File_name from where the message originated
function Function_name from where the message originated
line Line_no from where the messaged originated
Return values
SC_OK on success; else an error code
Definition at line 528 of file util-debug.c.
References SC_LOG_MAX_LOG_MSG_LEN, sc_log_module_initialized, and SC_OK.
Referenced by SCLog(), and SCLogErr().
SCLogRegisterTests()
void SCLogRegisterTests (void)
Definition at line 1713 of file util-debug.c.
References UtRegisterTest().
Variable Documentation
sc_log_global_log_level
SCLogLevel sc_log_global_log_level extern
Holds the global log level. Is the same as sc_log_config->log_level.
Definition at line 97 of file util-debug.c.
Referenced by SCLog(), SCLogDebugEnabled(), SCLogErr(), and SCLogGetLogLevel().
sc_log_module_cleaned
int sc_log_module_cleaned extern
Used to indicate whether the logging module has been cleaned or not.
Definition at line 107 of file util-debug.c.
sc_log_module_initialized
int sc_log_module_initialized extern
Used to indicate whether the logging module has been init or not.
Definition at line 102 of file util-debug.c.
Referenced by SCLogMessage().