suricata: /Users/jlu/suricata/src/util-profiling-prefilter.c File Reference
util-profiling-prefilter.c File Reference
#include "suricata-common.h"
#include "decode.h"
#include "detect.h"
#include "detect-engine.h"
#include "detect-engine-prefilter.h"
#include "conf.h"
#include "tm-threads.h"
#include "util-unittest.h"
#include "util-byte.h"
#include "util-profiling.h"
#include "util-profiling-locks.h"
#include "util-time.h"
Data Structures
struct SCProfilePrefilterData_
struct SCProfilePrefilterDetectCtx_
Typedefs
typedef struct SCProfilePrefilterData_ SCProfilePrefilterData
typedef struct SCProfilePrefilterDetectCtx_ SCProfilePrefilterDetectCtx
Functions
void SCProfilingPrefilterGlobalInit (void)
void SCProfilingPrefilterUpdateCounter (DetectEngineThreadCtx *det_ctx, int id, uint64_t ticks, uint64_t bytes, uint64_t bytes_called)
Update a rule counter.
void SCProfilingPrefilterDestroyCtx (DetectEngineCtx *de_ctx)
void SCProfilingPrefilterThreadSetup (SCProfilePrefilterDetectCtx *ctx, DetectEngineThreadCtx *det_ctx)
void SCProfilingPrefilterThreadCleanup (DetectEngineThreadCtx *det_ctx)
void SCProfilingPrefilterInitCounters (DetectEngineCtx *de_ctx)
Register the prefilter profiling counters.
Variables
int profiling_prefilter_enabled = 0
thread_local int profiling_prefilter_entered = 0
Detailed Description
Author
Endace Technology Limited.
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
An API for rule profiling operations.
Definition in file util-profiling-prefilter.c.
Typedef Documentation
SCProfilePrefilterData
typedef struct SCProfilePrefilterData_ SCProfilePrefilterData
SCProfilePrefilterDetectCtx
typedef struct SCProfilePrefilterDetectCtx_ SCProfilePrefilterDetectCtx
Function Documentation
SCProfilingPrefilterDestroyCtx()
void SCProfilingPrefilterDestroyCtx (DetectEngineCtx * de_ctx)
Definition at line 246 of file util-profiling-prefilter.c.
References de_ctx.
Referenced by DetectEngineCtxFree().
SCProfilingPrefilterGlobalInit()
void SCProfilingPrefilterGlobalInit (void)
Definition at line 69 of file util-profiling-prefilter.c.
References ConfGetNode(), ConfigGetLogDirectory(), ConfNodeChildValueIsTrue(), ConfNodeLookupChildValue(), and profiling_prefilter_enabled.
Referenced by PreRunInit().
SCProfilingPrefilterInitCounters()
void SCProfilingPrefilterInitCounters (DetectEngineCtx * de_ctx)
Register the prefilter profiling counters.
Parameters
de_ctx The active DetectEngineCtx, used to get at the loaded rules.
Definition at line 311 of file util-profiling-prefilter.c.
References de_ctx, DetectEngineCtx_::prefilter_id, DetectEngineCtx_::profile_prefilter_ctx, and profiling_prefilter_enabled.
SCProfilingPrefilterThreadCleanup()
void SCProfilingPrefilterThreadCleanup (DetectEngineThreadCtx * det_ctx)
Definition at line 292 of file util-profiling-prefilter.c.
References SCProfilePrefilterDetectCtx_::data_m, DetectEngineThreadCtx_::de_ctx, DetectEngineThreadCtx_::prefilter_perf_data, and DetectEngineCtx_::profile_prefilter_ctx.
SCProfilingPrefilterThreadSetup()
void SCProfilingPrefilterThreadSetup (SCProfilePrefilterDetectCtx * ctx, DetectEngineThreadCtx * det_ctx)
Definition at line 255 of file util-profiling-prefilter.c.
References DetectEngineThreadCtx_::de_ctx, DetectEngineCtx_::prefilter_id, DetectEngineThreadCtx_::prefilter_perf_data, and SCMalloc.
SCProfilingPrefilterUpdateCounter()
void SCProfilingPrefilterUpdateCounter (DetectEngineThreadCtx * det_ctx, int id, uint64_t ticks, uint64_t bytes, uint64_t bytes_called)
Update a rule counter.
Parameters
id The ID of this counter.
ticks Number of CPU ticks for this rule.
match Did the rule match?
Definition at line 201 of file util-profiling-prefilter.c.
References SCProfilePrefilterData_::bytes_called, SCProfilePrefilterData_::called, DetectEngineThreadCtx_::de_ctx, SCProfilePrefilterData_::max, SCProfilePrefilterData_::max_bytes, DetectEngineCtx_::prefilter_id, DetectEngineThreadCtx_::prefilter_perf_data, SCProfilePrefilterData_::total, and SCProfilePrefilterData_::total_bytes.
Variable Documentation
profiling_prefilter_enabled
int profiling_prefilter_enabled = 0
Definition at line 64 of file util-profiling-prefilter.c.
Referenced by SCProfilingPrefilterGlobalInit(), and SCProfilingPrefilterInitCounters().
profiling_prefilter_entered
thread_local int profiling_prefilter_entered = 0
Definition at line 65 of file util-profiling-prefilter.c.