suricata: /Users/jlu/suricata/src/util-base64.h File Reference
util-base64.h File Reference
#include "suricata-common.h"
Macros
#define ASCII_BLOCK 3
#define B64_BLOCK 4
Enumerations
enum Base64Mode { BASE64_MODE_RELAX , BASE64_MODE_RFC2045 , BASE64_MODE_STRICT }
enum Base64Ecode { BASE64_ECODE_ERR = -1 , BASE64_ECODE_OK = 0 , BASE64_ECODE_BUF }
Functions
Base64Ecode DecodeBase64 (uint8_t *dest, uint32_t dest_size, const uint8_t *src, uint32_t len, uint32_t *consumed_bytes, uint32_t *decoded_bytes, Base64Mode mode)
Decodes a base64-encoded string buffer into an ascii-encoded byte buffer.
void Base64RegisterTests (void)
Detailed Description
Author
David Abarbanel david.nosp@m..aba.nosp@m.rbane.nosp@m.l@ba.nosp@m.esyst.nosp@m.ems..nosp@m.com
Definition in file util-base64.h.
Macro Definition Documentation
ASCII_BLOCK
#define ASCII_BLOCK 3
Definition at line 31 of file util-base64.h.
B64_BLOCK
#define B64_BLOCK 4
Definition at line 32 of file util-base64.h.
Enumeration Type Documentation
Base64Ecode
enum Base64Ecode
Enumerator
BASE64_ECODE_ERR
BASE64_ECODE_OK
BASE64_ECODE_BUF
Definition at line 40 of file util-base64.h.
Base64Mode
enum Base64Mode
Enumerator
BASE64_MODE_RELAX
BASE64_MODE_RFC2045
BASE64_MODE_STRICT
Definition at line 34 of file util-base64.h.
Function Documentation
Base64RegisterTests()
void Base64RegisterTests (void)
Definition at line 280 of file util-base64.c.
References UtRegisterTest().
DecodeBase64()
Base64Ecode DecodeBase64 (uint8_t * dest, uint32_t dest_size, const uint8_t * src, uint32_t len, uint32_t * consumed_bytes, uint32_t * decoded_bytes, Base64Mode mode)
Decodes a base64-encoded string buffer into an ascii-encoded byte buffer.
Parameters
dest The destination byte buffer
dest_size The destination byte buffer size
src The source string
len The length of the source string
consumed_bytes The bytes that were actually processed/consumed
decoded_bytes The bytes that were decoded
mode The mode in which decoding should happen
Returns
Error code indicating success or failures with parsing
Definition at line 93 of file util-base64.c.
References B64_BLOCK, BASE64_ECODE_OK, len, and padding.
Referenced by DatasetAddSerialized(), DatasetRemoveSerialized(), and DetectBase64DecodeDoMatch().