suricata: /Users/jlu/suricata/src/util-exception-policy.h File Reference
util-exception-policy.h File Reference
Enumerations
enum ExceptionPolicy {
EXCEPTION_POLICY_IGNORE = 0 , EXCEPTION_POLICY_PASS_PACKET , EXCEPTION_POLICY_PASS_FLOW , EXCEPTION_POLICY_BYPASS_FLOW ,
EXCEPTION_POLICY_DROP_PACKET , EXCEPTION_POLICY_DROP_FLOW , EXCEPTION_POLICY_REJECT
}
Functions
void ExceptionPolicyApply (Packet *p, enum ExceptionPolicy policy, enum PacketDropReason drop_reason)
enum ExceptionPolicy ExceptionPolicyParse (const char *option, const bool support_flow)
int ExceptionSimulationCommandlineParser (const char *name, const char *arg)
Enumeration Type Documentation
ExceptionPolicy
enum ExceptionPolicy
Enumerator
EXCEPTION_POLICY_IGNORE
EXCEPTION_POLICY_PASS_PACKET
EXCEPTION_POLICY_PASS_FLOW
EXCEPTION_POLICY_BYPASS_FLOW
EXCEPTION_POLICY_DROP_PACKET
EXCEPTION_POLICY_DROP_FLOW
EXCEPTION_POLICY_REJECT
Definition at line 25 of file util-exception-policy.h.
Function Documentation
ExceptionPolicyApply()
void ExceptionPolicyApply (Packet * p, enum ExceptionPolicy policy, enum PacketDropReason drop_reason)
Definition at line 28 of file util-exception-policy.c.
References EngineModeIsIPS(), EXCEPTION_POLICY_IGNORE, EXCEPTION_POLICY_REJECT, Packet_::pcap_cnt, and SCLogDebug.
Referenced by AppLayerHandleTCPData().
ExceptionPolicyParse()
enum ExceptionPolicy ExceptionPolicyParse (const char * option, const bool support_flow)
Definition at line 75 of file util-exception-policy.c.
References ConfGet(), EXCEPTION_POLICY_BYPASS_FLOW, EXCEPTION_POLICY_DROP_FLOW, EXCEPTION_POLICY_DROP_PACKET, EXCEPTION_POLICY_IGNORE, EXCEPTION_POLICY_PASS_FLOW, EXCEPTION_POLICY_PASS_PACKET, EXCEPTION_POLICY_REJECT, FatalErrorOnInit, SC_ERR_INVALID_ARGUMENT, SC_WARN_COMPATIBILITY, and SCLogWarning.
Referenced by FlowInitConfig(), and StreamTcpInitConfig().
ExceptionSimulationCommandlineParser()
int ExceptionSimulationCommandlineParser (const char * name, const char * arg)
Definition at line 125 of file util-exception-policy.c.