suricata: /Users/jlu/suricata/src/util-var.h File Reference
util-var.h File Reference
Data Structures
struct GenericVar_
struct XBit_
struct ResolvedVariable_
Typedefs
typedef struct GenericVar_ GenericVar
typedef struct XBit_ XBit
typedef struct ResolvedVariable_ ResolvedVariable
Enumerations
enum VarTypes {
VAR_TYPE_NOT_SET , VAR_TYPE_PKT_BIT , VAR_TYPE_PKT_INT , VAR_TYPE_PKT_VAR ,
VAR_TYPE_PKT_VAR_KV , VAR_TYPE_FLOW_BIT , VAR_TYPE_FLOW_INT , VAR_TYPE_FLOW_VAR ,
VAR_TYPE_HOST_BIT , VAR_TYPE_HOST_INT , VAR_TYPE_HOST_VAR , VAR_TYPE_IPPAIR_BIT ,
VAR_TYPE_IPPAIR_INT , VAR_TYPE_IPPAIR_VAR
}
Functions
void XBitFree (XBit *)
typedef TAILQ_HEAD (, ResolvedVariable_) ResolvedVariablesList
void GenericVarFree (GenericVar *)
void GenericVarAppend (GenericVar **, GenericVar *)
void GenericVarRemove (GenericVar **, GenericVar *)
int AddVariableToResolveList (ResolvedVariablesList *list, const char *var)
void CleanVariableResolveList (ResolvedVariablesList *var_list)
Detailed Description
Author
Victor Julien victo.nosp@m.r@in.nosp@m.linia.nosp@m.c.ne.nosp@m.t
Definition in file util-var.h.
Typedef Documentation
GenericVar
typedef struct GenericVar_ GenericVar
ResolvedVariable
typedef struct ResolvedVariable_ ResolvedVariable
XBit
typedef struct XBit_ XBit
Enumeration Type Documentation
VarTypes
enum VarTypes
Enumerator
VAR_TYPE_NOT_SET
VAR_TYPE_PKT_BIT
VAR_TYPE_PKT_INT
VAR_TYPE_PKT_VAR
VAR_TYPE_PKT_VAR_KV
VAR_TYPE_FLOW_BIT
VAR_TYPE_FLOW_INT
VAR_TYPE_FLOW_VAR
VAR_TYPE_HOST_BIT
VAR_TYPE_HOST_INT
VAR_TYPE_HOST_VAR
VAR_TYPE_IPPAIR_BIT
VAR_TYPE_IPPAIR_INT
VAR_TYPE_IPPAIR_VAR
Definition at line 27 of file util-var.h.
Function Documentation
AddVariableToResolveList()
int AddVariableToResolveList (ResolvedVariablesList * list, const char * var)
Definition at line 133 of file util-var.c.
CleanVariableResolveList()
void CleanVariableResolveList (ResolvedVariablesList * var_list)
Definition at line 162 of file util-var.c.
References next, SCFree, TAILQ_FIRST, and TAILQ_REMOVE.
GenericVarAppend()
void GenericVarAppend (GenericVar ** list, GenericVar * gv)
Definition at line 92 of file util-var.c.
Referenced by FlowVarAddIdValue(), FlowVarAddIntNoLock(), and FlowVarAddKeyValue().
GenericVarFree()
void GenericVarFree (GenericVar * gv)
Definition at line 47 of file util-var.c.
References DETECT_FLOWBITS, DETECT_FLOWVAR, DETECT_PKTVAR, DETECT_XBITS, FlowBitFree(), FlowVarFree(), GenericVarFree(), GenericVar_::next, PktVarFree(), SCLogDebug, GenericVar_::type, and XBitFree().
Referenced by GenericVarFree().
GenericVarRemove()
void GenericVarRemove (GenericVar ** list, GenericVar * gv)
Definition at line 111 of file util-var.c.
TAILQ_HEAD()
typedef TAILQ_HEAD (ResolvedVariable_)
XBitFree()
void XBitFree (XBit * fb)
Definition at line 39 of file util-var.c.
References SCFree.
Referenced by GenericVarFree().